### ISSUE TITLE
Release script doesn't remove old files

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#1000]
The release script doesn't remove old files from the `build` folder.

It will still have files like this one: https://github.com/OnsenUI/OnsenUI-dist/blob/2.0.0-alpha.9/js/onsenui_all.js even though it's not present in the build folder.
 
Please fix this.

**Comment by frankdiox** [comment]
@argelius Thanks for reporting. Your OnsenUI-dist local folder had old files from the previous versions. I just added `rm *` if OnsenUI-dist folder already exists.

**Comment by argelius** [comment]
Thanks @frankdiox !
