### ISSUE TITLE
Material Range thumb element doesn't grow when touched on Android

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#1002]
When dragging the material range on Nexus 7 (Android 5.0) the thumb element doesn't animate.

**Comment by anatoo** [comment]
I have investigated this problem and realized that pure css component can't implements range thumb growing when dragging on Android. 
There is same problem on MDL's slider components(http://www.getmdl.io/components/#sliders-section).
This feature is implemented on Angular Material's "md-slider" directive(https://material.angularjs.org/latest/demo/slider) but this is not pure css.
To solve this problem, I think we should create custom elements. 
Any thoughts?

**Comment by argelius** [comment]
Thanks @anatoo ! Looks like we must implement it in JavaScript.
