### ISSUE TITLE
Ripple effect on Speed dial children broken.

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#1003]
When using `<ons-ripple>` on the `<ons-speed-dial>` children the ripple effect covers the shadow.

**Comment by argelius** [comment]
It can be reproduced in this sample. Ripple effect for the child elements is broken.

https://github.com/OnsenUI/OnsenUI/blob/master/demo/ripple/index.html

**Comment by anatoo** [comment]
Ok, Thanks!
