### ISSUE TITLE
Bower.son makes reference to build dir but files are not packaged there

### ISSUE THREAD

**Issue by tachu** [OnsenUI/OnsenUI#1005]
on 1.3.12 version the packaged bower.json file references 
  "main": [
    "build/js/onsenui.js"
  ],
  "styles": [
    "build/css/onsenui.css",
    "build/css/onsen-css-components.css"
  ],

but the actual shipped structure through bower doesn't have build dir and has files directly under ./js and ./css like 

drwxr-xr-x  10 tachu  staff    340 Nov  4 13:32 .
drwxr-xr-x   4 tachu  staff    136 Nov  4 13:32 ..
-rw-r--r--   1 tachu  staff   1281 Nov  4 13:32 .bower.json
-rw-r--r--   1 tachu  staff  14004 Nov  1 20:29 CHANGELOG.md
-rw-r--r--   1 tachu  staff    562 Nov  1 20:29 LICENSE
-rw-r--r--   1 tachu  staff   7929 Nov  1 20:29 README.md
-rw-r--r--   1 tachu  staff    977 Nov  1 20:29 bower.json
drwxr-xr-x  12 tachu  staff    408 Nov  1 20:29 css
drwxr-xr-x   6 tachu  staff    204 Nov  1 20:29 js
drwxr-xr-x   8 tachu  staff    272 Nov  1 20:29 stylus

This causes gulp to not package the files when creating a build.

**Comment by argelius** [comment]
Thanks for reporting @tachu ! We will fix this.

@frankdiox Can you take a look at this? You maybe need to update the tags.

**Comment by frankdiox** [comment]
Looks like we didn't update to the new `bower.json` in 1.3.12. The other releases were fine. I fixed 1.3.12 so it should work now :)
