### ISSUE TITLE
Alert-dialog animation is slow on material design dialog.

### ISSUE THREAD

**Issue by anatoo** [OnsenUI/OnsenUI#1008]
Alert-dialog animation is slow with material design on "demo/alert-dialog/index.html".
My device is Nexus 7 Android 5.1.1.

**Comment by argelius** [comment]
I tested building with Crosswalk and it's still super slow. I think this has very high priority so I will start working on it today.

**Comment by frankdiox** [comment]
Looks like `box-shadow` property in `.alert-dialog` and `.alert-dialog--material` is slowing down the performance, specially the blur effect.

**Comment by frankdiox** [comment]
The problem is the combination of `box-shadow` and `border-radius`. That slows down the alert for Material and Flat designs.
