### ISSUE TITLE
ons-alert-dialog from html template is broken on material design.

### ISSUE THREAD

**Issue by anatoo** [OnsenUI/OnsenUI#1013]
![screenshot_2015-11-06-13-27-32](https://cloud.githubusercontent.com/assets/59784/10994564/9b0a2352-84ba-11e5-9aca-b0228cfe235d.png)

**Comment by frankdiox** [comment]
@anatoo If the device is Android and has `modifier="material"` it uses `.alert-dialog-*--android` and also `.alert-dialog-*--material`. Material overwrites almost everything that Android includes, except a `border-bottom: 1px solid #ddd;` located in `.alert-dialog-title--android`. Do you think this is OK? Shouldn't it include only one of them?

**Comment by argelius** [comment]
It should only include one of them.

**Comment by anatoo** [comment]
@frankdiox It should use "material" modifier instead of "android" modifier(.alert-dialog-*--android) on Onsen UI v2 and android device. In ons-alert-dialog, current implementation add "android" modifier automatically. I think ons-alert-dialog and other components(e.g. ons-toolbar) should add "material" modifier automatically instead of "android" modifier on android device.

**Comment by argelius** [comment]
I removed the automatic "android" modifier. I didn't add the "material" modifier. However, I think there should be a way to automatically get a Material layout on Android.
