### ISSUE TITLE
<ons-back-button> remains showing after resetToPage()

### ISSUE THREAD

**Issue by cither1** [OnsenUI/OnsenUI#1018]
Take a look at this <https://jsfiddle.net/kLs6a47p/>.
I press Reset button in the third page to `resetToPage()`, but `<ons-back-button>` doesn't hide, although it should. I think some refresh process is needed.

Acctually, I found a workaround for this problem, as seen here <https://stackoverflow.com/questions/33510986/>. I know I can refresh `<ons-back-button>` and hide it by calling `$rootScope.$apply()` on `resetToPage()` manually,  but it's a bit bothering. Can you fix this?

**Comment by frankdiox** [comment]
@cither1 Thanks for reporting! Looks like the pages destruction in `resetToPage()` is out of Angular's digest cycle.

This is not applicable to Onsen UI 2.0 but I think we can release a new 1.x version to fix this. What do you think, @argelius ?

Adding `self._scope.$digest();` before [navigator.js#L602](https://github.com/OnsenUI/OnsenUI/blob/1.3.12/framework/views/navigator.js#L602) fixes this.

**Comment by argelius** [comment]
Yes, please release a patch to fix this bug @frankdiox .

**Comment by frankdiox** [comment]
@cither1 We just released 1.3.13 with this fixed. Try it out please!
