### ISSUE TITLE
ons-button missing in apk

### ISSUE THREAD

**Issue by GoGross** [OnsenUI/OnsenUI#1020]
here is my button code, 

```
<ons-button modifier="large--cta" class="login-button" ng-click="loginFunct()">Log In</ons-button>
```

everything displays fine but disappears when I emulate or export to APK.

**Comment by frankdiox** [comment]
@tinocosta84 Could you please elaborate it a bit? Is it the only button that disappears? Have you tried changing it somehow until it appears again? It's hard to figure out why it happens without an example or more information.

**Comment by tinocosta84** [comment]
<!DOCTYPE html>
<html lang="en" ng-app="app" ng-csp>
<head>
    <title>nipSpy</title>
    <meta charset="utf-8" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="mobile-web-app-capable" content="yes" />

    
    <script src="lib/angular/angular.js"></script>
    <script src="lib/onsen/js/onsenui.js"></script>

    
    <link rel="stylesheet" href="lib/onsen/css/onsenui.css" />
    <link rel="stylesheet" href="css/onsen-dark-css-components.min.css" />
    <link rel="stylesheet" href="css/style.css" />

    <script type="text/javascript" src="https://sandbox.zooz.co/mobile/checkoutapi/js/checkout-ext-api.js"></script>
    <script src="//www.parsecdn.com/js/parse-1.6.7.min.js"></script>

    
    <script src="cordova.js"></script>
    <script src="scripts/index.js"></script>
    <script src="scripts/app.js"></script>
    
</head>

<body ng-controller="nsCtrl">
<ons-navigator  title="Navigator" var="myNavigator" >
</ons-navigator>

    <ons-tabbar>
        <ons-tab active="true" page="login.html">
            <div class="tab">
                <ons-icon icon="ion-log-in" class="tab-icon"></ons-icon>
                <div class="tab-label">Login</div>
            </div>
        </ons-tab>

        <ons-tab page="signup.html">
            <div class="tab">
                <ons-icon icon="ion-compose" class="tab-icon"></ons-icon>
                <div class="tab-label">Signup</div>
            </div>
        </ons-tab>

        <ons-tab page="enquire.html">
            <div class="tab">
                <ons-icon icon="ion-android-chat" class="tab-icon"></ons-icon>
                <div class="tab-label">Enquire</div>
            </div>
        </ons-tab>

    </ons-tabbar>

    <ons-template id="login.html">
        <ons-navigator>
            <ons-page class="login-page">


                <form class="login-form" ng-controller="loginFunct">
                    <br />
                    <ons-row>
                        <ons-col class="align-center">
                            <img src="images/logo.png" class="page-logo">
                        </ons-col>
                    </ons-row>
                    <input type="text" class="text-input--underbar width-full susername" placeholder="Username" value="" ng-model="lgemail">
                    <input type="password" class="text-input--underbar" placeholder="Password" value="" ng-model="lgpass">

                    <br><br>
                    <ons-button modifier="large--cta" class="login-button" ng-click="loginFunct()">Log In</ons-button>
                    <br><br>


                    <ons-tab page="recover.html">
                            <div class="tab-label" style="font-size: 14px;">Recover Login</div>
                    </ons-tab>


                </form>

            </ons-page>
        </ons-navigator>
    </ons-template>

    <ons-template id="signup.html">
        <ons-page>

            <form class="formarea" ng-controller="signupFunct">
                <br />
                <ons-row>
                    <ons-col class="align-center">
                        <img src="images/logo.png" class="page-logo">
                    </ons-col>
                </ons-row>
                <div class="form-row">
                    <input type="text" class="text-input--underbar width-half sfname" placeholder="First" value="" ng-model="sfname">
                    <input type="text" class="text-input--underbar width-half slname" placeholder="Last" value="" style="border-width-left: 1px" ng-model="slname">
                </div>

                <div class="form-row">
                    <input type="text" class="text-input--underbar width-full susername" placeholder="Username"
                           value="" ng-model="susername">
                </div>

                <div class="form-row">
                    <input type="text" class="text-input--underbar width-full snemail" placeholder="Email" value="" ng-model="snemail">
                </div>

                <div class="form-row">
                    <input type="password" class="text-input--underbar width-full snpass" placeholder="Password" value="" ng-model="snpass">
                </div>

                <div class="lucent">
                    <p class="note">Password - 6 characters or more</p>
                </div>

                <div class="vspc form-row">
                    <ons-button modifier="large--cta" class="signupBtn" ng-click="signupFunct()">Sign up</ons-button>
                </div>
            </form>

        </ons-page>
    </ons-template>

    <ons-template id="recover.html">
        <ons-page class="login-page">

            <form class="login-form"  ng-controller="recover">
                <br />
                <ons-row>
                    <ons-col class="align-center">
                        <img src="images/logo.png" class="page-logo">
                    </ons-col>
                </ons-row>
                <input type="email" ng-model="recemail" class="text-input--underbar" placeholder="Email" value="">
                <br><br>
                <ons-button modifier="large" class="login-button" ng-click="recover()">Recover Login</ons-button>
            </form>

        </ons-page>
    </ons-template>

    <ons-template id="enquire.html">
        <ons-page class="login-page" ng-controller="enquire">
            <br />
            <ons-row>
                <ons-col class="align-center">
                    <img src="images/logo.png" class="page-logo">
                </ons-col>
            </ons-row>
            <ons-list modifier="inset" style="margin-top: 10px">
                <ons-list-item class="to-wrapper">
                    <ons-row>
                        <ons-col>
                            <div class="to-email">@_nipspy</div>
                        </ons-col>
                    </ons-row>
                </ons-list-item>
                <ons-list-item>
                    <input type="text" class="text-input text-input--transparent" placeholder="Name" style="width:
                    100%" ng-model="appsendername">
                </ons-list-item>

                <ons-list-item>
                    <input type="text" class="text-input text-input--transparent" placeholder="Email"
                           style="width:100%" ng-model="appsendermail">
                </ons-list-item>

                <ons-list-item>
                    <textarea class="textarea textarea--transparent" placeholder="Message" style="width: 100%;
                    height: 100px;" ng-model="appsendermessage"></textarea>
                </ons-list-item>

                <ons-list-item modifier="chevron">
                    <ons-icon icon="fa-tag" style="opacity:0.2"></ons-icon>
                </ons-list-item>

            </ons-list>

            <div style="padding: 10px 9px">
                <ons-button modifier="large--cta" style="margin: 0 auto;" ng-click="enquire()">
                    Send
                </ons-button>
            </div>

        </ons-page>
    </ons-template>
</body>
</html>

**Comment by tinocosta84** [comment]
When I export the above code, it doesn't show the ons-button in the apk, but just fine in the browser
