### ISSUE TITLE
Onsen slider and AngularJS on Mobile Touch

### ISSUE THREAD

**Issue by Bjoern3003** [OnsenUI/OnsenUI#1023]
Hi, it is not possible to set a new value on mobilephones with onsen Slider.

I can move the slider, but get no new value in my Angular Script.

Does anyone have the same problem?

**Comment by argelius** [comment]
Hi @Bjoern3003 !

What device are you running? Are you running as a Cordova application or a website?

**Comment by Bjoern3003** [comment]
Hi, I am using Android Device. Onsen is running as a website in my private network.

**Comment by Bjoern3003** [comment]
Hi Argelius, could you find the Problem? Could I give you more Informations to help?
