### ISSUE TITLE
ons-lazy-repeat taking full screen height

### ISSUE THREAD

**Issue by eidorianyeo** [OnsenUI/OnsenUI#1029]
If i remove ons-lazy-repeat from ons-list-item, this issue won't happen. Basically whenever I use ons-lazy-repeat, it takes on full height, overlap and cover on top of ons-toobar which is at the top of screen. Hope this can be fixed.

**Comment by argelius** [comment]
Hi @eidorianyeo ! Thanks for the report.

Can you provide some code that reproduces this issue?

**Comment by eidorianyeo** [comment]
Hi @argelius ,

Screen shot 1 show alignment without ons-lazy-repeat.
Screen shot 2 show alignment with ons-lazy-repeat.

All I did was add/remove that single function.

![issue1](https://cloud.githubusercontent.com/assets/8005098/11091539/435cb67e-88b6-11e5-9349-ea43167c90ff.png)
![issue2](https://cloud.githubusercontent.com/assets/8005098/11091540/4484d32e-88b6-11e5-8d60-9d7851adc86d.png)

<ons-page ng-controller="testCtrl">
    <ons-toolbar>
        <div class="left"><ons-back-button ng-click="menu.setMenuPage('menu.html');">Back</ons-back-button></div>
        <div class="right">
            <ons-toolbar-button ng-click="menu.toggle()">
                <ons-icon icon="ion-navicon" size="28px" fixed-width="false"></ons-icon>
            </ons-toolbar-button>
        </div>
        <div class="center">Test App</div>
    </ons-toolbar>

    <div class="navigation-bar">
        <div class="navigation-bar__center">
            <input type="search" class="search-input" style="width: 96%; margin: 6px auto 6px auto;" placeholder="Search">
        </div>
    </div>

    <ons-list-header>Ons Header</ons-list-header>
    <ons-list>
        <ons-list-item class="item" modifier="chevron" ons-lazy-repeat="MyDelegate" ng-click="app.navi.pushPage('chatroom.html'); menu.setMenuPage('menuChatRoom.html');">
            <ons-row>
                <ons-col width="80px">
                    <img ng-src="http://lorempixel.com/60/60/?22" class="item-thum"/>
                </ons-col>
                <ons-col>
                    <header>
                        <span class="item-title">{{ item.name }}</span>
                        <span class="item-label">{{ item.category }}</span>
                    </header>
                    <div ng-show="item.description==''">
                        <p><span style='opacity: 0.7;'><ons-icon icon='fa-spinner' spin='true'></ons-icon> Loading...</p></span></div>
                    <p class="item-desc">{{ item.description }}</p>
                </ons-col>
            </ons-row>
        </ons-list-item>
    </ons-list>
</ons-page>

**Comment by eidorianyeo** [comment]
Hi @argelius , can you help to confirm this is a genuine bug in ons-lazy-repeat?

**Comment by kenprice** [comment]
I found this Googling about my issue without much luck. I can confirm this bug. See [my screenshot here](http://pasteboard.co/27TuxuHB.png)

[gist of my view](https://gist.github.com/kenprice/918a7f1bffde865c3859)

See the gist of my view above. The commented out code is just a regular `ng-repeat` which works just fine. I replaced that line with a `ons-list-item` node with the `ons-lazy-repeat` directive. The list takes up the entire page. The first item in the list has `position: absolute; top: 0px`, and consequently starts right below the `ons-toolbar`. The list does not overflow on top of my `ons-tabbar` (not shown in the gist).

I've tried changing the parent `<ons-list>` node to `<ons-list style="position: relative; height: 100%">`, which appeared to work (list items no longer started at the top, but where I expected them) except the page ended up _loading less items_ than my maximum. I'm assuming the addition of `position: relative` somehow affected the way `ons-lazy-repeat` computed how far down I've scrolled.

**Comment by kenprice** [comment]
This seems to solve the issue for me. In `onsenui.js`'s `_getItemsInView`:
```
@@ -9053,9 +9053,12 @@ limitations under the License.
 
           this._maxIndex = Math.max(i, this._maxIndex);
 
+          var toolbar = document.getElementsByTagName('ons-toolbar');
+          var toolbarHeight = toolbar.length > 0 ? document.getElementsByTagName('ons-toolbar')[0].clientHeight : 0;
+
           items.push({
             index: i,
-            top: topPosition - topOffset
+            top: topPosition - topOffset + this._parentElement[0].getBoundingClientRect().top - toolbarHeight
           });
 
           topPosition += h;
```

**Comment by kenprice** [comment]
I replaced `_getTopOffset` for `LazyRepeatView` in `onensui.js` with this: 
```
      _getTopOffset: function() {
      	var toolbar = document.getElementsByTagName('ons-toolbar');
      	var toolbarHeight = toolbar.length > 0 ? toolbar[0].clientHeight : 0;
        return this._parentElement[0].getBoundingClientRect().top + toolbarHeight;
      }
```
That seemed to do it for me.

**Comment by eidorianyeo** [comment]
I'm quite amazed nobody from onsen team has acknowledge this issue and assigned anyone.

**Comment by argelius** [comment]
Hi @eidorianyeo @kenprice!

I've been busy the last two weeks. I will check out this bug as soon as I have time. Probably early next week since I'm travelling.

**Comment by kenprice** [comment]
@eidorianyeo Have you tried my fix? It's just a quick fix and I haven't accounted for all possible cases  (worked fine for my needs), but I think it might benefit the maintainers to provide hints at a possible solution. Why don't you try it and report back here in the meantime?

**Comment by eidorianyeo** [comment]
Hi @kenprice. Yes your fix works. However if people add in additional stuff such as search input below tool bar, the issue will persist. The issue also occur when people uses bottom-tool-bar.
Ons-Lazy-Repeat is a great feature but just poorly documented (calculateditemheigh & itemcount) and currently still very buggy.

**Comment by PvanHengel** [comment]
Hi I am still seeing this same issue in my project.  One slight difference is that I am async loading the entire list, such that when it first loads there are zero items.  The onReady function makes an HTTP call to add items to the list and change the count so they appear in the UI.

**Comment by OmarHassan25** [comment]
How we can set dynamic item height in lazy repeat ????????????

**Comment by IliaSky** [comment]
@PvanHengel 
I seem to be unable to reproduce it. Here's a [demo](http://codepen.io/IliaSky/pen/vGbqJO?editors=1010) which again loads first with zero items and 1 second later adds them and it seems to be working fine. Maybe there is something specific in you code which triggers the issue.

@OmarHassan25 
Closed issues and github in general is not the place for such questions. We have a [community](https://community.onsen.io/) and [stackoverflow](stackoverflow.com/tags/onsen-ui) for questions. 

And now the answer - you just need to set the `calculateItemHeight` property of the delegate which you are providing - you can set it to a function which returns the height for the item at the specific index. 

Our docs recently changed but that's something which was documented in both the [new](https://onsen.io/v2/docs/js/lazy-repeat.html) and the [old](https://onsen.io/v2/docs/js/ons-lazy-repeat.html#properties) docs.
