### ISSUE TITLE
Bug: ons-pull-hook + lazy-repeat

### ISSUE THREAD

**Issue by d3orn** [OnsenUI/OnsenUI#1034]
If I use the ons-pull-hook together with a lazy repeat list sometimes the list vanishes for as long as the pull-hook is spinning.

**Comment by frankdiox** [comment]
@d3orn Thanks for reporting! I'd like to take a look at it. Could you please link to a simple example in Codepen or jsfiddle? Also, which version of Onsen UI do you use?
