### ISSUE TITLE
Bug: lazy-repeat with ons-scroller

### ISSUE THREAD

**Issue by d3orn** [OnsenUI/OnsenUI#1035]
Although lazy-repeat is allowed inside an ons-scroller I can only scroll a couple of elements on non iPhone devices (tested on browser and android). As soon as I remove the ons-scroller it works like a charm.

Keep up the awesome work, cannot wait for the onsen 2 release xD

**Comment by argelius** [comment]
Thanks @d3orn ! We will investigate this.

**Comment by argelius** [comment]
@andipavllo Can you investigate this and release a patch if you solve it?

**Comment by andipavllo** [comment]
@argelius sure, I'll take a look at it today

**Comment by andipavllo** [comment]
@d3orn Are you using the lazy-repeat with an ons-list? If yes, is there any specific reason to add the list inside ons-scroller? It will already scroll by itself.

**Comment by d3orn** [comment]
I guess that was a fix for windows but as far as I can see at the point of writing it works in windows without the scroller so I will just go without it.

**Comment by IliaSky** [comment]
The issue has been fixed, even though we are planning on removing `ons-scroller` soon.
