### ISSUE TITLE
directive ng-show and ng-hide is not working with elements ons-icon

### ISSUE THREAD

**Issue by dayerdl** [OnsenUI/OnsenUI#104]
I have a list of items. Those have 2 icons that i hide or show accordingly if i want to remove them or not.
 <ons-col size="10" class="right">
           <ons-icon icon="angle-right" ng-hide="editEnabled"> </ons-icon>
           <ons-icon icon="minus-square-o" ng-show="editEnabled" ng-click="deleteAccount(account)"> </ons-icon>
         </ons-col>

The problem is that the 1st time the list appears on the screen both element are show and looks like they dont care about the directive.

**Comment by salztorte** [comment]
try ng-if
