### ISSUE TITLE
Options object in <ons-back-button>

### ISSUE THREAD

**Issue by frankdiox** [OnsenUI/OnsenUI#1040]
@argelius @anatoo We can have an options object for `navigator.popPage({...})` with things like `refresh` or `onTransitionEnd`, but currently `ons-back-button` is set to do `navigator.popPage({cancelIfRunning: true});` and nothing else. I guess we should add a way to assign an options object to `ons-back-button`. How do you think it should be done?

- As a parameter of `pushPage`: `navigator.pushPage( 'newpage.html', { ... , backButtonOptions: { ... } }
- As attributes in HTML: `<ons-back-button options="objectVariableName">` or `<ons-back-button refresh="true" onTransitionEnd="functionName">`. The last example can be a bit hard to pass functions with arguments.
- As a method of navigator page object: `navigator.getCurrentPage().setBackButtonOptions( { ... } );`
- Any other.

What do you think?

**Comment by anatoo** [comment]
:+1: 
It's good to have a way to assign popPage() options such as ons-back-button attributes and pushPage() method's options.

**Comment by frankdiox** [comment]
Which way do you think it's better? I just implemented getter/setter in `ons-back-button` so it's possible to do it like this: `document.querySelector('ons-back-button').options = { ... }`. With this I think it's not necessary to add an option to `navi.pushPage(...)`, but what about the HTML attributes? `options="myObject"`, `options="JSON"` or `refresh="true" onTransitionEnd="myFunction"` etc.?

**Comment by anatoo** [comment]
Could you write proposal spec shortly? When andreas and I agree its proposal, it's OK to implement.
I personally think it's good to have "refresh-on-pop" and "cancel-if-running" and "on-transition-end" attributes.

**Comment by frankdiox** [comment]
@anatoo @argelius We need to pass the options object to `ons-back-button` somehow. I think we need at least 1 way to do it programmatically and 1 way directly in the HTML of the button:

* Programmatically: `backButtonElement.options = { ... }`. I think this is better than passing the object with `pushPage` since it can be added on `init` event or page controller and is coherent with web components
* HTML: we can have 1 attribute per option: `animation`, `onTransitionEnd`, `refresh` and `cancelIfRunning`. The latter is not documented.

**Comment by anatoo** [comment]
:+1:

**Comment by argelius** [comment]
I think this looks good!
