### ISSUE TITLE
Onsen2: Unable to load polyfills/promise-6.1.0.js.map

### ISSUE THREAD

**Issue by luposlip** [OnsenUI/OnsenUI#1042]
Browser on iOS device throws this error:
```
Failed to load resource: The requested URL was not found on this server. file:///polyfills/promise-6.1.0.js.map
```
Best,
Henrik

**Comment by frankdiox** [comment]
@luposlip Thanks for reporting! That file is not included in Onsen UI 2.0, I can only find a reference to that file in CSS-components patterns. When is that error thrown in your app?

**Comment by luposlip** [comment]
@frankdiox It's thrown during initialization of onsen, at least it seems like that.
No line in any JS file, so I guess you're right about the CSS.

**Comment by argelius** [comment]
@luposlip @frankdiox I removed the reference to the source map.

**Comment by luposlip** [comment]
Thanks.
ons. 25. nov. 2015 kl. 10.19 skrev Andreas Argelius <
notifications@github.com>:
