### ISSUE TITLE
Onsen2: navigator .pushPage

### ISSUE THREAD

**Issue by luposlip** [OnsenUI/OnsenUI#1043]
I have a page with a navigator. I use plain Javascript/React, e.g. no Angular.
I use .pushPage from the API of the navigator, and before calling that, I add a "postpush" event using the following code:

```
navigator.addEventListener("postpush", function(){//code goes here})
```

After pushing I get this error in my console (on iOS):
```
TypeError: element._show is not a function. (In 'element._show()', 'element._show' is undefined) onsenui.js 14886
(anonymous function)onsenui.js:14885
```

Best,
Henrik

**Comment by frankdiox** [comment]
Hello @luposlip ! This is working for me with pure JavaScript in Chrome:

```javascript
  <script>
    var myNavigator;
    ons.ready(function() {
      myNavigator = document.querySelector('ons-navigator');
      myNavigator.addEventListener('postpush', function(event) {
        console.log(event);
      });
    });
  </script>
```

```
<ons-button onclick="myNavigator.pushPage('page1.html')">
    Push Page
</ons-button>
```

I guess you do something similar. Can you provide a failing example so we can test it?
Thanks!

**Comment by luposlip** [comment]
I've just tried again, in exactly the way you describe.

It works fine on desktop (Chrome), but when wrapped in a Cordova app and installed on iOS, the embedded browser still throws this error:
![image](https://cloud.githubusercontent.com/assets/763627/11235291/8f677f30-8dd0-11e5-8323-3c1371c95d93.png)

Please try that yourself, I guess you'll the the same error right away.

**Comment by navinnd** [comment]
Try the below code instead:

menu.setMainPage('home.html', {closeMenu: true});
