### ISSUE TITLE
Onsen2 Tabbar with persistent tabs

### ISSUE THREAD

**Issue by michaeleparkour** [OnsenUI/OnsenUI#1044]
Persistent tabs animated wrong: content blinks and dissappears. If fade transition - page still have opacity:0, if transition slide - page still have -webkit-transform: translate3d(-100%, 0, 0);. Looks like wrong indexes on reactive event or smth.

**Comment by frankdiox** [comment]
@michaeleparkour Thanks for reporting! I can confirm this, we will fix it asap!
