### ISSUE TITLE
Unable to load a Onsen iu 2 project on Monaca

### ISSUE THREAD

**Issue by fabricelepro** [OnsenUI/OnsenUI#1045]
hi, 
i'have create a new project with the brand new Onsen iu Material, but wwhen iam compiling 
the project on "Live Preview" on my smartphone the error is
"Uncaught SyntaxError: Unexpected token native "  on -- > www/lib/onsenui/js/onsenui.js:825 
without changing anythings from the js file

**Comment by frankdiox** [comment]
Hello @fabricelepro ! I guess you created a new "Onsen 2.0 Quick Start" project in Monaca. I have tried the live preview in the browser and in a device with Monaca Debugger and both work fine. Have you modified anything? Also, which device are you using?

**Comment by fabricelepro** [comment]
not yet! My device is running on Android 2.3, live preview in the browser work correctly, but and syntax error append when i run on device

**Comment by argelius** [comment]
Hi @fabricelepro !

We're actually not supporting the Android 2.3 WebView. We try to support Android from 4.0 and later and recommend using the Crosswalk library. All animations will be a lot smoother in Crosswalk.

Cordova performance is extremely flaky in the Android 2.3 webview and Crosswalk is only supported from Android 4.0 and later. If there is just some unsupported JavaScript code we might release a patch for it. Don't expect smooth performance though. :)

You're welcome to submit a PR that solves the issue or we will take a look at it when we have time.

**Comment by argelius** [comment]
Looking at your error I think it might be an issue with the `CustomElements.js` polyfill.

**Comment by fabricelepro** [comment]
Thanks, not problem
