### ISSUE TITLE
missing autocompletion onsen tags in visual studio

### ISSUE THREAD

**Issue by cSteusloff** [OnsenUI/OnsenUI#1046]
It is possible to get a autocompletion for the onsen specific tags in visual studio 2015?

Thanks

**Comment by frankdiox** [comment]
@cSteusloff Hello! In short, currently there is no autocomplete for VS2015. Truth is that we implemented a working version of autocomplete few months ago, but we found some problems/ limitations and had to stop that project for a while. Probably we will continue it but I cannot say any date yet.

In case you have experience with IntelliSense extensions or related stuff, any help would be really welcome!
