### ISSUE TITLE
BUG:ons-bottom-toolbar In the IOS on the page will go up to the top as v1.3.13

### ISSUE THREAD

**Issue by gazxm** [OnsenUI/OnsenUI#1047]
ons-bottom-toolbar In the IOS on the page will go up to the top

**Comment by argelius** [comment]
Thanks for the report! We will investigate it.

**Comment by gazxm** [comment]
@argelius thank you

**Comment by AlberTajuelo** [comment]
+1

I tried with Safari (in Mac) and it works. Only it is in iOS

**Comment by danjarvis** [comment]
:+1: Just encountered a likely related issue with iOS and `ons-bottom-toolbar`: When using both top and bottom toolbars, the extra padding that is usually added on iOS to move the page down from the status bar is no longer applied correctly.

![simulator screen shot jan 8 2016 10 21 51 am](https://cloud.githubusercontent.com/assets/116640/12201325/b41697c8-b5f1-11e5-92f5-584c61bb3b28.png)

**Comment by asial-matagawa** [comment]
This problem seems to have been fixed by #1163 and #1291.

Closing this.
