### ISSUE TITLE
Onsen2: Toolbar too close to iOS statusbar

### ISSUE THREAD

**Issue by luposlip** [OnsenUI/OnsenUI#1048]
Hi there!

I'm using Onsen2 beta.
When using Onsen2 on iOS, the toolbar is too close to the native statusbar:
![image](https://cloud.githubusercontent.com/assets/763627/11236238/4a8aaaa6-8dd8-11e5-8bfa-88393e13f980.png)

This was not an issue with Onsen 1.x.

Best,
Henrik

**Comment by gazxm** [comment]
You use ons-bottom-toolbar on these pages?

**Comment by luposlip** [comment]
No.
But I didn't when I used Onsen1.x either.

**Comment by gazxm** [comment]
I used the 1.3.13 version only to use the ons-bottom-toolbar to do this，2 has not used

**Comment by argelius** [comment]
Thanks @luposlip ! We will investigate this. Seems like it doesn't detect the platform correctly.

**Comment by luposlip** [comment]
Great @argelius, perhaps this is related to #1042 and #1043 as well!

**Comment by argelius** [comment]
@luposlip By the way, does this happen on a real device? Maybe the version is not detected correctly because it's running in the simulator.

**Comment by luposlip** [comment]
Yes, it hampens on a real device. Haven't tested it in a simulator.
ons. 25. nov. 2015 kl. 10.28 skrev Andreas Argelius <
notifications@github.com>:

**Comment by d3orn** [comment]
@luposlip Are you using cordova and especially the device plugin? I have the same issue as soon as I start using the device plugin. Removing it brings back to old behaviour

**Comment by luposlip** [comment]
Yes to both questions. And I need both :-)
ons. 25. nov. 2015 kl. 18.02 skrev Dominique Rahm <notifications@github.com

**Comment by d3orn** [comment]
I will look into it. Maybe there is a bug. Will keep you posted if I find the error

**Comment by luposlip** [comment]
Thanks.

As mentioned earlier it worked with a similar setup when I used Onsen1.x.
ons. 25. nov. 2015 kl. 18.15 skrev Dominique Rahm <notifications@github.com

**Comment by d3orn** [comment]
@argelius as far as I can see 'isIOS' and 'isIOS7above' both try to use the cordova device plugin but they do not wait for the device ready event which is needed for the plugins to work. If you can tell me how you did this for other things I can try to fix and pr it

**Comment by d3orn** [comment]
fixed! will PR this tomorrow need some rest 10h work day xD

**Comment by luposlip** [comment]
Thanks guys! :-)
ons. 25. nov. 2015 kl. 20.10 skrev Dominique Rahm <notifications@github.com

**Comment by argelius** [comment]
Thanks @d3orn !

Returning a promise with `shouldStatusBarFill()` makes sense if we need to wait for `deviceready`. Looking forward to the PR :)

**Comment by d3orn** [comment]
mhm my fix somehow breaks orientation detection on my Samsung Note III
