### ISSUE TITLE
onsen 2.0 quickstart uncaught referenceerror: cordova is not defined

### ISSUE THREAD

**Issue by cooplarsh** [OnsenUI/OnsenUI#1051]
Using the Monaca IDE on a Mac Notebook I created a new project with the Onsen 2.0 Quick Start template, selected run on device.  After I load the app in Monaca debugger on my Samsung Galaxy S5 and then select select any of the 3 demos in the (material, react, flat) they work great until I try and close the app using the back button on the phone.

Expected behavior: app closes down like all of the other android apps.  

Instead I get an Uncaught ReferenceError: cordova is not defined and the app doesn't close (so I have to kill the app).

**Comment by cooplarsh** [comment]
After seeing your blog that you've just added Cordova 5.2 support I checked my Cordova version and it is 5.3.3.  Could that be the problem (and why not all of the Cordova features, like Vibrate, didn't work on the Hello World sample)?

If so, given your note ("Once Cordova 5.2 is updated, you cannot downgrade to older Cordova versions.") and the fact that I have other cordova apps on my machine created with other hybrid mobile frameworks, I'm not exactly sure how/if I can proceed with my evaluation of Onsen 2 - which is too bad since it looks great.

**Comment by masahirotanaka** [comment]
Thanks for the issue report. It is likely a problem of QuickStart template that it forgets to include Cordova.js. Our blog post mentions we will update  Cordova version on our remote build server, but that does not affect your local environment. Therefore, we will fix the template to include Cordova.js to solve your issues. Thanks!

**Comment by frankdiox** [comment]
This is fixed in https://github.com/OnsenUI/onsenui2-quickstart/pull/4
