### ISSUE TITLE
Create ons-material-button instead of ons-button with "material" modifier.

### ISSUE THREAD

**Issue by anatoo** [OnsenUI/OnsenUI#1053]
Currently ons-button with "material" modifier does not have ripple effect and developer must put ons-ripple elements by hand.
We should implements ons-material-button have ripple effect by default.
Any thoughts?

**Comment by frankdiox** [comment]
That's like `ons-list-item` with `modifier="material"`, we don't include ripple effect either. Perhaps we can include `ons-ripple` directly when `modifier="material"` is specified unless it has `ripple="false"` attribute?

**Comment by andipavllo** [comment]
I like Fran's proposal more than a new button tag :)

**Comment by asial-matagawa** [comment]
Now we have the implementation of the Fran's proposal in Onsen UI 2.0.4.
Closing this.
