### ISSUE TITLE
Async methods should return promise on all elements.

### ISSUE THREAD

**Issue by anatoo** [OnsenUI/OnsenUI#1054]
Async methods(e.g. ons-navigator.pushPage()) on all elements should provide not only callback option but also promise object as return value.

**Comment by frankdiox** [comment]
I think this is a very good idea!

**Comment by anatoo** [comment]
@frankdiox So could you implements this?

**Comment by frankdiox** [comment]
@anatoo Yes I can try. Let's see what @argelius thinks about it first anyway :)

**Comment by argelius** [comment]
I like it! :)

Also, I think we should have promises for `ons.notification` methods.
