### ISSUE TITLE
onsen2.0 ons-back-button

### ISSUE THREAD

**Issue by d3orn** [OnsenUI/OnsenUI#1062]
Hey guys, I have been using Onsen2.0 for a new project and I am amazed so far, awesome work!

I am trying to use material design for my current project and there is a small bug with the ons-back-button.
When I use ons-back-button within a ons-toolbar(modifier='material')  the .center part moves a little bit to the left because ons-back-button takes up less space than ons-toolbar-button.
Therefore navigating from a page with a menu button to a page with a back button looks jumpy.

![onsenmaterial](https://cloud.githubusercontent.com/assets/411479/11372180/58c1c0ac-92cc-11e5-87e2-516ecede7fc7.jpg)

As you can see in the picture above the toolbar has the material modifier but the back-button is far more left.

I looked at those two types of buttons and maybe they should be implemented in the same way.
```
<ons-toolbar-button>
          <ons-icon icon="md-menu" class="ons-icon zmdi zmdi-menu" ></ons-icon>
 </ons-toolbar-button>
```

vs

```
<ons-back-button>
         <span class="toolbar-button toolbar-button--material">
                  <i class="zmdi zmdi-arrow-left"></i>
          </span>
</ons-back-button>
```

Furthermore I wanted to ask if it is possible to change modifiers based on the device the app is running on. I would like to have material on android/windows and flat on iOS

Thanks for your awesome framework! You rock

**Comment by argelius** [comment]
Thanks @d3orn !

I will remake the layout of the the material toolbar to make it more close to the spec. I also noticed there is a problem with the size of the buttons. I will add some padding to the buttons to make the clickable area larger and also add active class.

**Comment by argelius** [comment]
I have rewritten the CSS for the material toolbar so it's more consistent with the Material Design spec.

Now there will always be at least `72px` to the left of the center element and I've also changed the size of the buttons and added some styles for the `:active` pseudo-class so it reacts on touch.

By the way, you will automatically get a material icon for the back button if you use `<ons-back-button>` inside a material toolbar so there's no need to add the icon.

**Comment by d3orn** [comment]
yeah I know the code I posted was the generated HTML. Thanks a lot for those changes
