### ISSUE TITLE
Onsen UI drag and drop creator like Ionic creator ? 

### ISSUE THREAD

**Issue by DILEEP-YADAV** [OnsenUI/OnsenUI#1075]
@anatoo 

Are You working on drag and drop App creator in Onsen UI like iONIC CRATOR .
If yes ! How much time far  for that, everyone are waiting for that. that is  time and money saving idea.

**Comment by argelius** [comment]
Hi @DILEEP-YADAV !

We are not currently working on a tool like this and it's not something we currently have planned.

**Comment by DILEEP-YADAV** [comment]
ok !
