### ISSUE TITLE
Scrollbar issues on desktop browsers. (2.0-beta)

### ISSUE THREAD

**Issue by FLHerne** [OnsenUI/OnsenUI#1078]
In Firefox 42, pages always have both vertical and horizontal scrollbars.
In Chromium 46, pages never have scrollbars, even if required (scrolling with wheel does work).

-----
Editing line 93 of css/onsenui.css to replace `overflow: scroll;` with `overflow: auto;` causes the scrollbars to be shown only when required on desktop Firefox.

Commenting out the various instances of `::-webkit-scrollbar { display: none; }`
causes scrollbars to be displayed in desktop Chromium when needed.

Presumably those changes (at least the second one) would be undesirable for mobile browsers; I might try to find a non-breaking solution if no-one else is interested.

**Comment by AlberTajuelo** [comment]
+1!

Thanks FLHerne!

**Comment by argelius** [comment]
We have made scrollbars visible on all browsers by default now so I will close this.
