### ISSUE TITLE
Onsen2: Angular 2 compatibility

### ISSUE THREAD

**Issue by jondavidjohn** [OnsenUI/OnsenUI#1083]
I've created a small repository to illustrate the issues I'm seeing.

https://github.com/jondavidjohn/onsenui-ng2

From the looks of it, I believe there may be some conflicts in the way the web components in OnsenUI interact with the way Angular 2 is using the shadow dom.

You get different resulting DOM when using identical onsen markup when using Angular 2.

Given:

```html
<ons-page>
  <ons-toolbar>
    <div class="center">Title</div>
  </ons-toolbar>
</ons-page>

```

Static Result (correct):

```html
<ons-page class="page">
  <ons-toolbar class="navigation-bar" style="position: absolute; z-index: 10000; left: 0px; right: 0px; top: 0px;">
    <div class="center navigation-bar__center navigation-bar__title">Title</div>
  </ons-toolbar>
  <div class="page__background"></div>
  <div class="page__content" no-status-bar-fill=""></div>
</ons-page>
```

Angular 2 Result (broken):

```html
  <ons-page class="page">
    <div class="page__background"></div>
    <div class="page__content"></div>
    <ons-toolbar class="navigation-bar" style="position: absolute; z-index: 10000; left: 0px; right: 0px; top: 0px;">
      <div class="left navigation-bar__left">&nbsp;</div>
      <div class="center navigation-bar__center navigation-bar__title">&nbsp;</div>
      <div class="right navigation-bar__right">&nbsp;</div>
      <div class="center">Title</div>
    </ons-toolbar>
  </ons-page>
```

**Comment by argelius** [comment]
Thanks for reporting @jondavidjohn ! We will investigate this behavior.

**Comment by jondavidjohn** [comment]
Just thought I'd update that I tested with `beta.2` and it is still an issue. :+1:

**Comment by jondavidjohn** [comment]
I've also now upgraded the example repository to the newly dropped Angular 2 Beta release.

**Comment by letmejustfixthatohitsbroken** [comment]
any updates here? When are the angular2 bindings going to be released? I'd love to use both, angular2 and onsen2
