### ISSUE TITLE
onsen2.0 ons-toolbar material right

### ISSUE THREAD

**Issue by d3orn** [OnsenUI/OnsenUI#1084]
The right part of the toolbar is too small if used on an iOS device. For example my magnifying glass gets pushed to the edge of the screen. I think the right part of the toolbar should have a min-width like .left has.

**Comment by argelius** [comment]
Thanks @d3orn !

I have confirmed this bug. We haven't tested Material Design extensively on iOS since it's mainly for Android. Sorry about that.

Of course it should render nicely on iOS as well so I will take a look at this.
