### ISSUE TITLE
problem with android browser and android 4.2.2 - onsen ui 2 beta

### ISSUE THREAD

**Issue by aliv** [OnsenUI/OnsenUI#1085]
hi.
i tested my app and onsenui2-quickstart with browsers and build cordova app too and user interface is broken on this condition:
application on android 4.2.2 device.
application/www with android browser on 4.2.2 and 5.0.1

application on android 5.0.1 and application/www  on chrome browser (4.2.2 and 5.0.1) are ok.

**Comment by argelius** [comment]
Thanks for reporting @aliv !

We will investigate this behavior.
