### ISSUE TITLE
is OnsenUI meant to be used as browser based app ie ( across all browsers )

### ISSUE THREAD

**Issue by istvano** [OnsenUI/OnsenUI#1086]
Dear OnsenUI gurus. 

I am completelly new to OnsenUI but I love the UI.
Currently I am doing a research for my next project and I am not sure if it is the right tool for me in my project. 

Currently I would like to use the UI with AngularJS in a web application which is meant to be used on Desktop. ( Chrome, Safari, IE, Firefox ) as well with iOS and Android devices.

Do you recommend going ahead with OnsenUI 2.0 or ONsenUI is meant to be used with PhoneGap only to build hybrid applications ?

Thanks very much for any insight.

Istvan

**Comment by argelius** [comment]
Hi @istvano !

You can use both Onsen UI and Onsen UI 2.0 to make mobile web pages. We test it on Chrome, Firefox and Safari. Recently we're also trying to support IE/Edge better.

If you have any issues on a modern desktop browser, please report them.
