### ISSUE TITLE
Carousel

### ISSUE THREAD

**Issue by kountouretis** [OnsenUI/OnsenUI#1087]
i want to use a carousel as slider but i can't find how to put next and preview buttons.

**Comment by argelius** [comment]
Hi @kountouretis !

There is no built-in feature like this. However, you can put those buttons yourself and wire them up with the carousel.

**Comment by frankdiox** [comment]
@kountouretis Something like this was asked few days ago: http://stackoverflow.com/a/34057158/4468962
