### ISSUE TITLE
Popover 

### ISSUE THREAD

**Issue by kountouretis** [OnsenUI/OnsenUI#1088]
I use navigation inside the popover but when navigate to the new page the popover stay visible.

**Comment by argelius** [comment]
Hi @kountouretis !

I don't really understand what you mean. Can you provide an example? You need to hide the popover manually with `popover.hide()`. When you don't need it anymore you can destroy it with `popover.destroy()`.

**Comment by kountouretis** [comment]
thank you for your reply. i try to find how to use the popover.hide(). but i don't find.
 my example code is <script type="text/ons-template" id="index.html">
      <ons-popover direction="left" cancelable>
       <ons-list>
	   <ons-button modifier="light" onclick="myNavigator.pushPage('favnew.html', { animation : 'slide' } )">
       <ons-icon icon="ion-heart"></ons-icon>new page
      </ons-button>
         
        
      </ons-popover>
    </script>

when i navigate to the favnew.html page the popover is still visible 
![1](https://cloud.githubusercontent.com/assets/9192697/11587637/7b1dcf38-9a83-11e5-8fbe-cb2bfb93feb4.jpg)

**Comment by argelius** [comment]
@kountouretis I made a simple example where you can click a button inside the popover to close it.

```html
<ons-page ng-controller="PageController">
  <ons-button ng-click="popover.show($event)">Show</ons-button>
</ons-page>

<ons-template id="popover.html">
  <ons-popover cancelable>
    I am a popover! :)
    <ons-button ng-click="popover.hide()">Hide</ons-button>
  </ons-popover>
</ons-template>
```

http://codepen.io/argelius/pen/OMPLrQ

**Comment by kountouretis** [comment]
hi i also copy and paste your code  from codepen to my project and is not wrok. here is the code:
<!doctype html>
<html lang="en" ng-app="myApp">
  <head>
    <meta charset="utf-8">
    <title>Popover | Onsen UI</title>
    <link rel="stylesheet" href="styles/app.css"/>
	<link rel="stylesheet" href="styles/ionicons.css"/>
	<link rel="stylesheet" href="styles/list_thumbnails.css">
    <link rel="stylesheet" href="build/css/onsenui.css">
    <link rel="stylesheet" href="build/css/onsen-css-components.css">
	<link rel="stylesheet" href="build/css/onsen-css-components-blue-basic-theme.css">

    <script src="build/js/onsenui.js"></script>
    <script src="build/js/angular/angular.js"></script>
    <script src="build/js/angular-onsenui.js"></script>
    <script src="app.js"></script>
	
	<script>
ons.bootstrap()
</script>
<script>
.controller('PageController', function($scope) {
  $scope.ons.createPopover('popover.html', {parentScope: $scope}).then(
    function(popover) {
      $scope.popover = popover;
    }
  );
});
</script>
<body>
<ons-page ng-controller="PageController">
  <ons-button ng-click="popover.show($event)">Show</ons-button>
</ons-page>

<ons-template id="popover.html">
  <ons-popover cancelable>
    I am a popover! :)
    
    <ons-button ng-click="popover.hide()">Hide</ons-button>
    <ons-button ng-click="popover.hide()">Hide</ons-button>
  </ons-popover>
</ons-template>


</body>

**Comment by argelius** [comment]
I read your issue again. Are you assuming that the popover will close automatically when you navigate to another page?

There is no such feature so you need to hide it automatically. Also you need to destroy it when the page that spawned it is destroyed to avoid memory leaks.

To close the popover and navigate to another page you can do: 
```html
<button onclick="popover.hide(); myNavigator.pushPage('page.html');">
```

**Comment by kountouretis** [comment]
Thank you argelius for your reply.i can't test if the popover is hide or not because the popover is not working. i don't know if i must include more .js or .css files.

**Comment by argelius** [comment]
@kountouretis You only need to include `onsenui.css`, `onsenui.js` and `onsen-css-components.css` to use the popover.

http://codepen.io/argelius/pen/zrxxop

### HTML
```html
<ons-button id="button" onclick="popover.show('#button')">Show</ons-button>

<ons-popover id="popover" cancelable>
    I am a popover! :)
    
    <ons-button onclick="popover.hide()">Hide</ons-button>
</ons-popover>
```

### JavaScript
```js
window.popover = document.getElementById('popover');
```

**Comment by kountouretis** [comment]
i try to run this code inluded only the   onsenui.css, onsenui.js and onsen-css-components.css but is not working

**Comment by argelius** [comment]
Can you put your failing code on Codepen?

Also, you need to tell us what errors you get, otherwise it will be hard to debug.

**Comment by kountouretis** [comment]
the code is the code you put on codepen and i copy from codepen inlcuding the js and css files

**Comment by argelius** [comment]
@kountouretis I don't really understand. Is the code I wrote not working? In that case I need to know what device you are running it on.

**Comment by kountouretis** [comment]
i run with browser chrome and xampp

**Comment by argelius** [comment]
@kountouretis In that case I don't have any idea what is happening. Do you get any JavaScript errors?

**Comment by kountouretis** [comment]
no i just click the button but nothing happen.

**Comment by kountouretis** [comment]
@argelius  the popover is working perfect but when i enable Ripple Mission Control not working, the only thing i see is the loading icon... any idea about this
