### ISSUE TITLE
i got this error in android 4.2.2

### ISSUE THREAD

**Issue by shayanea** [OnsenUI/OnsenUI#1094]
www/js/onsenui.min.js:3158 HUAWEI Y330-U11Uncaught Error: Invalid state
www/js/angular-onsenui.min.js:357 HUAWEI Y330-U11Uncaught TypeError: Cannot call method 'lock' of undefined
www/index.html:28 HUAWEI Y330-U11Uncaught TypeError: Object #<Object> has no method 'ready'

**Comment by Haice** [comment]
Hi,

Were you able to resolve this issue? I'm having the same problem.
