### ISSUE TITLE
Interactive tutorial for Onsen UI 2.0

### ISSUE THREAD

**Issue by frankdiox** [OnsenUI/OnsenUI#1098]
@argelius @anatoo @masahirotanaka @andipavllo 

We could have some kind of interactive tutorial for Onsen UI 2.0 were the users can write code and see a live preview explaining things like `ons.ready()` and basic stuff for beginners. Something simple similar to Knockout's: http://learn.knockoutjs.com/

What do you think?

**Comment by argelius** [comment]
I think this is a good idea! :+1:

**Comment by masahirotanaka** [comment]
Nice!
:+1:

**Comment by andipavllo** [comment]
sound good to me! :)

**Comment by anatoo** [comment]
It's good to have.

**Comment by frankdiox** [comment]
http://tutorial.onsen.io
