### ISSUE TITLE
Add `<ons-textarea>`

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#1099]
We should add this element because it's impossible to autogrow a textarea with just CSS.

It should expose all the normal textarea attributes.

There should be a `grow` attribute that makes it automatically grow while the user is writing.

What do you think @anatoo?

**Comment by anatoo** [comment]
I think it's OK to have. But I don't know why we should implements auto-grow feature on v2.0. Is this feature so important than other material design components?

**Comment by argelius** [comment]
Yes, maybe we can add this in a later version. I will remove it from the milestone.

**Comment by co3k** [comment]
This element is looks good to me. Is it possible to consider again?
