### ISSUE TITLE
pushPage not working

### ISSUE THREAD

**Issue by d3orn** [OnsenUI/OnsenUI#1104]
this commit 655cd4f7e31dab8cff2b83e8f4b78385ccb397cc broke the pushPage function on iOS. I figured out what the problem is but I have no time to fix it at the moment. 
The show() and hide() functions are not called or not available on iOS and this causes the pushPage not to work.
If I replace the calls to show and hide with what they do (set the style of the backbutton) everything works perfectly.
So the problem is in core/lib/navigator-page.es6 and core/elements/ons-back-button.es6
Hope this helps.
Cheers!

**Comment by argelius** [comment]
Thanks @d3orn !

**Comment by d3orn** [comment]
Well I added a console.log to each of those functions but it seems as if they are not called / defined. The if-else is correct.
