### ISSUE TITLE
Ripple

### ISSUE THREAD

**Issue by d3orn** [OnsenUI/OnsenUI#1110]
I have been working on a ripple directive which can be added to any clickable object as an Attribute Directive (Angular only). I wanted to ask if this is something you guys would like to have for Onsen 2.0?

**Comment by argelius** [comment]
Do you mean something like `<div ons-ripple></div>` ?

I think that would be good to have as an Angular directive since it makes it easier to use the ripple element in Angular.

**Comment by d3orn** [comment]
Yeah exactly, I have been working on an Angular Attribute Directive, but it is not perfect yet. How should I proceed? 
I can finish it and PR so you guys can decide what to do with it?

**Comment by argelius** [comment]
Sounds great! Please create a PR when you've finished it :+1:
