### ISSUE TITLE
ons.softwareKeyboard.on won't remove listener on $destroy

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#1118]
Hi @argelius ,

I have the case, where I need to listen on

``` js
ons.softwareKeyboard.on('show', function() {
});
```

I do some nasty stuff inside of it, but it gets applied to all my inputs as it persits even on destroyed controller. If I re-init the controller, it also re-registers and triggers multiple times.

The functions of softwareKeyboard are not documented. I can't find anything about it (only ons-keyboard-active / ons-keyboard-inactive)

I need a solution

1) Destroy listener automatically when controller is destroyed
2) Or please tell me how to deactivate the listener by myself. (I would add a `$scope.$on('$destroy', function(){
...unregister});`

**Comment by Hirbod** [comment]
I'm not sure what this line does
https://github.com/OnsenUI/OnsenUI/blob/f0c87264c5bcd38100e1d600ef414e66a3cb3907/framework/directives/keyboard.js#L81

but it looks to me like you actually want to remove the listener. So it's a bug?

**Comment by Hirbod** [comment]
For now, I've managed to fix it like this:

```js
        $scope.initKeyboardActions = function() {

            if(device.platform.toLowerCase() == 'android') {
                var handler = function() {
                    $('.ons-page-inner:last').scrollTop($(document.activeElement).offset().top);
                };

                ons.softwareKeyboard.on('show', handler);
                $scope.$on("$destroy", function() {
                    ons.softwareKeyboard.off('show', handler);
                });
            }
        };
```

**Comment by argelius** [comment]
Hi @Hirbod ! 

I can investigate this behavior. Looks like the listener is not correctly removed.
