### ISSUE TITLE
popover backbutton error

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#1119]
Hi @argelius,

(just to mention, I'm still on 1.3.14)

When I open a popover and try to use the backbutton on my S6 Edge (or Genymotion), I get:
Uncaught Error: Capturing backbutton-handler is failure.

Default behaviour on android should be to close the popover (when "cancelable" is set)

For now, is there any way to achieve what I need without hacking around much?

**Comment by frankdiox** [comment]
@Hirbod We will check that, meanwhile you can find some information about this in SOF: https://stackoverflow.com/questions/28766130/how-to-handle-hardware-back-button-on-ons-dialog/32200011#32200011
