### ISSUE TITLE
Routing in OnsenUI

### ISSUE THREAD

**Issue by spidfire** [OnsenUI/OnsenUI#112]
I was wondering if someone has a working routing example?
with something like ngRoute

**Comment by 111crb111** [comment]
Example for ui.route please.

**Comment by argelius** [comment]
@111crb111 

You can describe the states and how to transition with `ui-router`. Onsen UI doesn't use URL routing but navigates from one page to another programmatically using the custom elements. 

I made a simple example using `<ons-navigator>` but you can extend this to use `<ons-sliding-menu>`, `<ons-tabbar>` or any combination of them.

http://codepen.io/argelius/pen/WveKKO

I use the `onEnter()` and `onExit()` methods to define the state transitions:

```javascript
ons.bootstrap(['ui.router']).config(function($stateProvider, $urlRouterProvider) {
  $urlRouterProvider.otherwise("/page1");

  $stateProvider
  .state('page1', {
    url: "/page1"
  })
  .state('page2', {
    parent: 'page1',
    onEnter: function($rootScope) {
      $rootScope.navi.pushPage('page2.html');
    },
    onExit: function($rootScope) {
    	$rootScope.navi.popPage();
    }
  })
  .state('page3', {
    parent: 'page2',
    onEnter: function($rootScope) {
      $rootScope.navi.pushPage('page3.html');
    },
    onExit: function($rootScope) {
      $rootScope.navi.popPage();
    }
  })
});
```

This will set up the finite state machine so we can now use `ui-sref` links in our view:

```html
<ons-navigator title="Navigator" var="navi">
  <ons-page>
    <ons-toolbar>
      <div class="center">Simple Navigation</div>
    </ons-toolbar>
    <div style="text-align: center">
      <br>
      <ons-button modifier="light" ui-sref="page2">
        Push Page
      </ons-button>
    </div>
  </ons-page>
</ons-navigator>

<ons-template id="page2.html">
  <ons-page>
    <ons-toolbar>
      <div class="center">Page 2</div>
    </ons-toolbar>

    <div style="text-align: center">
      <br />
      <ons-button modifier="light" ui-sref="page3">
        Push Page
      </ons-button>
      <ons-button modifier="light" ui-sref="^">
        Pop Page
      </ons-button>
    </div>
  </ons-page>
</ons-template>

<ons-template id="page3.html">
  <ons-page>
    <ons-toolbar>
      <div class="center">Page 3</div>
    </ons-toolbar>

    <div style="text-align: center">
      <br />
      <ons-button modifier="light" ui-sref="^">
        Pop Page
      </ons-button>
      <ons-button modifier="light" ui-sref="page1">
        Back to top
      </ons-button>
    </div>
  </ons-page>
</ons-template>
```

**Comment by 111crb111** [comment]
Thanks for fast response :D i will look on it!

**Comment by argelius** [comment]
Great! I'm actually thinking about adding native support for `ui-router`. We can't use `ngRoute` because it only works will URLs but `ui-router` is perfect since we can define state transitions.

I'll also investigate the new router but I think the `ui-router` is enough for our needs.

**Comment by 111crb111** [comment]
Yes would be awesome to have native ui-router!

**Comment by byhoratiss** [comment]
@argelius I could not make both "ui-router" and "ons-sliding-menu" component together.
I tried your example using the navigator component, but, if I want to use the sliding-menu component, it seems very strange to let him "switch" the templates, and not let "ui-router" to do the magic.

For example, I don't want to put the template of the sliding-menu inside all templates, and of course, don't want to use an "abstract" state to make all states a child and share the same template with the sliding-menu in it.

Any hint about how to make them work?

**Comment by argelius** [comment]
@byhoratiss You can do something similar to what I did with navigator and define the state transitions with the `slidingMenu.setMainPage()` method.

There is no builtin integration between the sliding menu and the router right now but we will add it in an upcoming version.

**Comment by s134319** [comment]
@argelius: Just asking: Did you decide in which upcoming version you want to add this feature? Yet the next version, or sometimes in the future?

**Comment by frankdiox** [comment]
@s134319 @byhoratiss @111crb111 
You may find useful this blog article: http://onsen.io/blog/onsen-ui-router-app/
