### ISSUE TITLE
SlidingMenuView setMainPage method is checking an undefined currentPageUrl variable

### ISSUE THREAD

**Issue by matikun86** [OnsenUI/OnsenUI#1120]
Onsen v1.3.14
In the module factory 'SlidingMenuView' method `setMainPage`
is doing `if (this.currentPageUrl === pageUrl) {`
where `this.currentPageUrl` is `undefined`. I think that it should be `this._currentPageUrl === pageUrl` instead.

**Comment by frankdiox** [comment]
@matikun86 This was already fixed in master branch but thanks for pointing it out again so we don't forget to include it in the next release!

**Comment by asial-matagawa** [comment]
This problem has already been fixed. Closing this.
