### ISSUE TITLE
missing methods for ons-toolbar-button

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#1121]
@argelius @frankdiox while ons-button has some methods, ons-toolbar-button has none.
The most important one is setDisabled and isDisabled()

Would you mind to implement this?

**Comment by frankdiox** [comment]
@Hirbod I just answered this in SOF: http://stackoverflow.com/a/34280311/4468962

**Comment by asial-matagawa** [comment]
As http://stackoverflow.com/a/34280311/4468962 says, toolbar buttons are usually removed or hidden rather than disabled, so I am sorry but we are not planning to implement this. Closing this.
