### ISSUE TITLE
Support multi-platform design

### ISSUE THREAD

**Issue by masahirotanaka** [OnsenUI/OnsenUI#1125]
Modify/add components, attributes and modifiers to automatically adjust the design based on the running operating system.

* By default, `modifier` attribute is automatically set based on the running OS.
* New `ons.disableAutomaticStyling()` function to prohibit automatic platform adjustment.
* New `<ons-button>`, `<ons-range>` and `<ons-input>` components.
* Remove `<ons-material-input>` component.
* New `effect` attribute to manually enable/disable ripple effect (default: `ripple` for Android).
* New `disable-auto-styling` attribute to manually enable/disable modifier and ripple effect (default: `false`)
* Change `<ons-list-item>` to support ripple effect.
 * Also change `tappable` from modifier to an attribute.
 * Also remove effect from `chevron` modifier.
* Keep `<ons-ripple>` as it is.
* Add new modifier to `<ons-fav>` to remove show when displaying in iOS.
* Add `<ons-if-platform>` element.
 * Example usage: `<ons-page>...<ons-if-platform android>...</ons-if-platform>...</ons-page>`

**Comment by frankdiox** [comment]
@masahirotanaka @argelius What about `<ons-if>` element instead of `ons-if-platform`? We can add attributes `platform`, `orientation` or anything else we need. Or is `platform` totally enough?

**Comment by masahirotanaka** [comment]
That's a super nice idea. fran++;
