### ISSUE TITLE
Components page gives a 403 forbidden error

### ISSUE THREAD

**Issue by bozzmob** [OnsenUI/OnsenUI#1129]
Hi,

The Components page gives a 403 forbidden error.

URL - http://onsen.io/guide/components.html

Screenshot-

![403forbidden](https://cloud.githubusercontent.com/assets/1252941/11836395/7a472d8a-a400-11e5-8695-c9f119e69cc5.png)

**Comment by argelius** [comment]
Thanks @bozzmob !

We're having an outage right now. Working on fixing it.

**Comment by bozzmob** [comment]
@argelius Ok :+1:

**Comment by argelius** [comment]
@bozzmob It has been fixed now. You should be able to access the site in a ~10 minutes. Again, thanks a lot for reporting :)
