### ISSUE TITLE
Back button animation is broken in beta.3

### ISSUE THREAD

**Issue by frankdiox** [OnsenUI/OnsenUI#1131]
Back button's icon appears and disappears directly without animation on pushPage and popPage. The text, however, has animation. `git bisect` points out this commit: 7a226c100738ce831353dff0587bfdd07171d404

Since it's a merging commit I guessed the error was actually in another commit but I couldn't find where.
@argelius @anatoo Perhaps something went wrong with the conflicts merge and some styles were not updated?

**Comment by anatoo** [comment]
@frankdiox Thanks for this report. 
Probably I had broken something on the navigator's animation. I will fix this problem.

**Comment by frankdiox** [comment]
@anatoo Thanks!
