### ISSUE TITLE
Problems with High-Performance iDevices

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#1134]
@argelius @frankdiox  Well, this sounds very stupid, but the better the devices, the more problems.

Since iPad Pro and iPad Air 2 + iPhone 6S and 6S Plus, I have some problems. They are just too fast and change pages and elements before rendering is done. This means, that it happen, that I see unrendered elements on pushPage, onTabChange. Mostly due too third party directives, (most problems with angular-translate) but also with the toolbar.

Have a look at my screenshot. It happens, that for a matter of ms, the menu button will stay there and hide. 

![img_0006](https://cloud.githubusercontent.com/assets/504909/11870308/d72aedb8-a4c6-11e5-80ea-e68802086354.PNG)

After the pushPage is done, it will disappear. Older devices won't have this problem and this bug does not appear on Simulator, only real devices.

**Comment by Hirbod** [comment]
Here the proof
https://youtu.be/BRodICol7qQ

**Comment by Hirbod** [comment]
Finally figuered out why all the problems appear. It's because of ng-hide/ng-show. Since the new devices are too fast, the rendering won't be applied at perfect time. I had some ng-hide stuff on that toolbar buttons.
```html
        <div class="left">
            <ons-back-button ng-show="!menucall"></ons-back-button>
            <ons-toolbar-button ng-click="menu.toggleMenu();" ng-show="menucall">
                <ons-icon icon="bars"></ons-icon>
            </ons-toolbar-button>
        </div>
```

 I've added following CSS

```css
[translate\:cloak], [translate-cloak], [ng\:cloak], [ng-cloak], [data-ng-cloak], [x-ng-cloak], .ng-cloak, .x-ng-cloak, .ng-hide:not(.ng-hide-animate) {
  display: none !important;
}
```

and I add the class="ng-hide ng-cloak" on that toolbar-button.

```html
        <div class="left">
            <ons-back-button class="ng-cloak ng-hide" ng-show="!menucall"></ons-back-button>
            <ons-toolbar-button ng-click="menu.toggleMenu();" class="ng-cloak ng-hide" ng-show="menucall">
                <ons-icon icon="bars"></ons-icon>
            </ons-toolbar-button>
        </div>
```

Fixed! I don't know if you find a better way for that.. @argelius @frankdiox

**Comment by frankdiox** [comment]
@Hirbod Thanks a lot for all of this information! We will think about it :)
