### ISSUE TITLE
Make ons-lazy-repeat faster on initialization.

### ISSUE THREAD

**Issue by anatoo** [OnsenUI/OnsenUI#1138]
Most simple example of "ons-lazy-repeat" take 80ms-140ms on initialization with my Mac mini and Google Chrome. I can try to optimize ons-lazy-repeat.

**Comment by argelius** [comment]
Yes, I've long been wanting to improve the `<ons-lazy-repeat>`. Please try to optimize it.

**Comment by anatoo** [comment]
As a result of investigating the example of ons-lazy-repeat(examples/lazy_repeat_element/index.html), the bottleneck seems to be to ons-list-item.

A case of using 'ons-list-item':
![image](https://cloud.githubusercontent.com/assets/59784/12137877/a850322e-b497-11e5-91dc-77548a736db5.png)

A case of using 'div':
![image](https://cloud.githubusercontent.com/assets/59784/12137884/b7fd823a-b497-11e5-8940-cadaee977974.png)

When ons-lazy-repeat have simple div elements instead of ons-list-item elements, it's very fast.

**Comment by anatoo** [comment]
Closing. Feel free to reopen this issue.
