### ISSUE TITLE
ons-tab active attribute bugged in Onsen UI 2.0

### ISSUE THREAD

**Issue by andipavllo** [OnsenUI/OnsenUI#1158]
If `active="true"` has been set, the following error will be displayed:

`Uncaught TypeError: Cannot read property 'rewritables' of undefined`

This happens on CodePen but not on Chrome ([see CodePen example](http://codepen.io/andipavllo/pen/eJWdrE))

**Comment by argelius** [comment]
Thanks @andipavllo ! I will fix this and release a new version.
