### ISSUE TITLE
Issue binding values from Controller in dialog

### ISSUE THREAD

**Issue by RezaRahmati** [OnsenUI/OnsenUI#1164]
Hi
I am facing this strange behavior and it might be a bug.
If you have a dialog and a controller for that dialog and you bind something to scope, the binding doesn't work for the first time.

see the below link
http://codepen.io/anon/pen/gPROje

it has a $scope.volume in controller and if you open the dialog for the first time you will see {{volume}} on top of the dialog and the volume is not set, but if you click on that for the second time everything is ok.

Is it a bug, or I missed something?

**Comment by danjarvis** [comment]
A general practice to follow when setting initial data in a controller is to wrap code in calls to `$timeout` or `$evalAsync`. These will trigger the digest cycle and your bindings will get set properly.

```
ons.bootstrap()

.controller('DialogController', function($scope) {
  $scope.dialogs = {};

  $scope.show = function(dlg) {
    if (!$scope.dialogs[dlg]) {
      ons.createDialog(dlg).then(function(dialog) {
        $scope.dialogs[dlg] = dialog;
        dialog.show();
      });
    } else {
      $scope.dialogs[dlg].show();
    }
  }
}).controller('MaterialController', function($scope, $timeout) {
  $timeout(function() {
    $scope.volume = 5;
  }, 10);
});
```

**Comment by RezaRahmati** [comment]
@danjarvis Thanks, it solved my problem
