### ISSUE TITLE
issue pull hook when scroll up  both onsen ui V1x and V2 on iphone5&6s

### ISSUE THREAD

**Issue by pvsong** [OnsenUI/OnsenUI#1166]
Hi, 
I have a problem when I use pull hook in my project to load more items. when I scroll page up, it was flicker
Here my video: 
https://www.youtube.com/watch?v=6Rt_NkNpVKM
I have to tried with simple demo many times on  https://onsen.io/2/reference/ons-pull-hook.html , I just created the simple template and some items , but it still flick.
When I remove pull hook it work fine! 
sorry for my English :smile: 

Many thanks.

**Comment by juspriet** [comment]
same problem...

**Comment by argelius** [comment]
@pvsong @juspriet We will investigate this behavior.

Can you give me information on how to reproduce this. Does it happen in a simple app using only a list with pull hook or do you need some special conditions?

Please provide all information that you think could be usesul, such as sample code and under what conditions it happens.

**Comment by pvsong** [comment]
Well, as you see in my video. Behavior is users scroll page fast in first time, when page still move users
 touch on page and scroll it up slow .. and slow. 
I've  created just a basic app with pull hook. with some items on list:

ons-page
      ons-pull-hook
            ....................
     ons-pull-hook
     ons-list
           ons-list-item
                     (about 100 items)
           ons-list-item
     ons-list
ons-page

You can see it quite clear on iphone4 or iphone5, 
on iphone6 it seem like smoother a litter bit. 

On Android no problem :smiley:

**Comment by argelius** [comment]
Thanks @pvsong !

**Comment by pvsong** [comment]
Ah, use onsen UI with monaca.

**Comment by argelius** [comment]
I think this has been solved. Please reopen if you're still having issues.

**Comment by luidiva** [comment]
What's the solution for this problem?

**Comment by luidiva** [comment]
What's the solution for this problem, please?

**Comment by misterjunio** [comment]
@luidiva do you still experience this problem? Could you create a pen or maybe try to reproduce it on [the tutorial app](https://tutorial.onsen.io/?framework=vanilla&category=reference&module=pull-hook) and create a new issue?
