### ISSUE TITLE
ons-carousel's initial-index does not work with ng-repeat

### ISSUE THREAD

**Issue by frankdiox** [OnsenUI/OnsenUI#1168]
1.3.14
Looks like `ons-carousel-item`s are generated with `ng-repeat` after the `initial-index` is checked.

**Comment by argelius** [comment]
Thanks @frankdiox !

When you have time, please fix this in 1.3.* and release a new version. Also please fix it in 2.0 if it's also an issue there.

**Comment by githubkyo** [comment]
you can fix it like this 
<ons-carousel-item ng-repeat="item in items">
</ons-carousel-item>

**Comment by jallen0927** [comment]
+ 1
