### ISSUE TITLE
How can I access angular's $templateCache from html in OnsenUI 2.0?

### ISSUE THREAD

**Issue by cither1** [OnsenUI/OnsenUI#1174]
I'm trying 2.0.0-beta with angular, gulp and browserify environment and I bumped into a problem.
If I bundle `.html` templates into one `.js` file caching them in the $templateCache, how can I refer to them in the view? I suppose that's the way many angularians do.
OnsenUI's `templateStore` object seems not published for now, I wonder if there is any way to handle templates?

**Comment by argelius** [comment]
If you're using Angular there shouldn't be any difference in Onsen UI 2.0.

**Comment by argelius** [comment]
I will close this for now. Please feel free to open it if you think it's necessary.

**Comment by cither1** [comment]
It's working fine now. Maybe I was doing something wrong. Thank you!

**Comment by argelius** [comment]
@cither1 No problem! If you have any other issues, don't hesitate to ask! :)

**Comment by cither1** [comment]
Again the problem reproduced. Please take a look at this fiddle and the console log. https://jsfiddle.net/0bs5anv2/1/ OnsenUI2.0 appearently loads `home.html` over XHR although it is defined in the `$templateCache`. I believe it was working in 1.3.x.  Is this a bug or am I doing something wrong again?

**Comment by cither1** [comment]
@argelius I created the [1.3.15 version](https://jsfiddle.net/b3eajzwo/). We can't use the `$templateCache` in this way any more? If so, is there any alternative means to use the `$templateCache`?
