### ISSUE TITLE
Feature request: Either add ons-scrollbar element or modify ons-scroller.

### ISSUE THREAD

**Issue by IliaSky** [OnsenUI/OnsenUI#1179]
The current `ons-scroller` element doesn't seem to do much. 
Even though it has `overflow: scroll` it doesn't provide a scrollbar. In some cases where a user has scrollable content not having a scrollbar could be an issue.
The two options which come to mind to solve this problem are:
1. Addition of a new `ons-scrollbar` element
2. Modification of `ons-scroller`, so that it can have a scrollbar
In either case the final result could look [something like this](http://codepen.io/IliaSky/pen/obowmv).

__Option 1__:
Whenever an ons-scrollbar element is attached to the DOM it makes sure its parent can support it by changing its overflow and position css properties if needed;

__Option 2__:
Add the scrollbar logic to the already existing `ons-scroller`. In that case it can just have an attribute like `scrollbar="visible|hidden|auto|autohide"`.

In both cases it the element could have some different options like touchable radius around it or disappearing some time after a scroll event.

The `ons-scrollbar` has the bonus of being available for non-ons elements, but has a higher chance of causing some issues. The `ons-scroller` option sounds safer, adds meaning behind the tag, but is more limiting.

Which of the two options would be better in your opinion? 
@anatoo @frankdiox @argelius @andipavllo

I should be able to implement it without causing any issues.

**Comment by frankdiox** [comment]
@IliaSky I like it, but since the scrollbar should also be available for `ons-page` (and maybe any other div) perhaps it's better to have it as a new component (option 1). Since it's already listening for `scroll` perhaps it could also throw a custom event when it's near the bottom or some position configurable by the user.

**Comment by argelius** [comment]
I like option 1! :)
