### ISSUE TITLE
<ons-back-button> generates back-button twice 

### ISSUE THREAD

**Issue by bdedardel** [OnsenUI/OnsenUI#1181]
Hi,

I notice that &lt;ons-back-button&gt;...&lt;/ons-back-button&gt; generates back-button twice 
(<span class="back-button__icon"> X 2)

```
<ons-back-button class="back-button" style="display: inline-block;"><span class="back-button__icon"></span><span class="back-button__label"><span class="back-button__icon"></span><span class="back-button__label">&nbsp;</span></span></ons-back-button>
```
onsenui: 2.0.0-beta.5
android: 4.2.2 

Regards,
Benjamin

**Comment by argelius** [comment]
Thanks @bdedardel ! :)

@frankdiox Also mentioned this and I think he will fix it soon.

**Comment by frankdiox** [comment]
@argelius Yes I checked this the other day, but I'm actually a bit confused. There is a double back-button only using Chrome in Codepen: http://codepen.io/frankdiox/pen/mVXLZR

I'm not able to reproduce the error in a local environment though...

**Comment by argelius** [comment]
@frankdiox Codepen loads JS at the end of the body. Can you reproduce it if you move the imports?

**Comment by frankdiox** [comment]
@argelius Exactly, that's why. If I load it at the end then I also get two back-buttons in my local environment!

**Comment by frankdiox** [comment]
@argelius It works if we replace `ons-template` with `script type="text/ons-template"`. Looks like this is not a trivial problem :sweat_smile:

**Comment by argelius** [comment]
I believe it is because the Angular code is executed before the Web Components.

**Comment by frankdiox** [comment]
But there is no Angular code, it´s just Web Components in that example.

**Comment by argelius** [comment]
Oh! I guess the `document.registerElement('ons-template', ...)` must happen before everything else.

**Comment by frankdiox** [comment]
Yes, I think since `ons-template` is a component a bit special it's better to import it before the others.
