### ISSUE TITLE
Dialog back button broken in current build.

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#1183]
It fails binding the back button handler:

```
Uncaught TypeError: Cannot read property 'createHandler' of undefined
```

**Comment by tdiddi** [comment]
Same here on WP 8.1 with Intel XDK

**Comment by frankdiox** [comment]
@argelius Please reassign it to me when you finish the example.

**Comment by argelius** [comment]
Should be working fine now. It was using the global `ons._deviceBackButtonDispatcher` variable instead of importing it using es6 imports.

**Comment by tdiddi** [comment]
It's working now for me!
