### ISSUE TITLE
onsenui2-quickstart remove package gulp-livereload

### ISSUE THREAD

**Issue by leocaseiro** [OnsenUI/OnsenUI#1191]
I've noticed that the **gulpfile.js** from the [Onsen UI 2 Quick Start](https://github.com/OnsenUI/onsenui2-quickstart) project is using browserSync which is an alternative for Live Reload. With that said, I believe we should remove the package **gulp-livereload**.

**Comment by argelius** [comment]
Thanks @leocaseiro!

I merged your PR so I will close this.
