### ISSUE TITLE
broken interface with android browser - onsen ui 2 beta 6

### ISSUE THREAD

**Issue by aliv** [OnsenUI/OnsenUI#1197]
hi, 
related to closed issue #1085:
i tested my app again and there is new result with beta 6
interface for application/www on chrome is ok (android 5 and 4.2.2).
interface for builded apk is ok (android 5).
interface for application/www on android 5 browser is **broken**.
interface for builded apk on android 4.2.2 and application/www on android 4.2.2 browser is not broken anymore but there is some problem with some components like circular loading and modifier icon on list item.

**Comment by corneyl** [comment]
I think I have a related problem, my list is not displayed properly on older Android device, as is the titlebar.

**Android 4.1.2**
![screenshot_2016-06-02-22-09-15](https://cloud.githubusercontent.com/assets/5320363/15759683/15098a5e-2910-11e6-9330-65900ee15660.png)

**Android 6.0.1**
![screenshot_20160602-220435](https://cloud.githubusercontent.com/assets/5320363/15759684/150a81a2-2910-11e6-9d07-bce88ec1133d.png)

__Environment__
Onsen 2 RC 9
react 15.1.0
react-onsenui 0.2.21

**Comment by IliaSky** [comment]
Hmm, even with the same configuration [Onsen 2 RC 9, react 15.1.0, react-onsenui 0.2.21] I seem to be unable to reproduce the issue (both the toolbar and the list render fine). 

I tested it on Android 4.0.4 and 4.4.2. Might be something specific for 4.1.2...

The other option would be if there is something else which triggers it. Even though it's such a simple case, would you mind posting the exact code which you're using?

@philolo1 - maybe you may have a better idea what might be the problem?

**Comment by argelius** [comment]
@IliaSky @corneyl We had a previous report about something similar on Android 4.1. Looks like the browser on 4.1 in some cases have a broken implementation of flexbox... :|

**Comment by corneyl** [comment]
Sorry, I've found the problem. I compiled the CSS myself, and did not use autoprefixer. With autoprefixer enabled it looks fine.

**Comment by argelius** [comment]
@corneyl Great! :)

Autotprefixer is important because older browsers only support the old version of flexbox.
