### ISSUE TITLE
Onsen UI 2.0  material design is not working with android 4.2 

### ISSUE THREAD

**Issue by DILEEP-YADAV** [OnsenUI/OnsenUI#1201]
HI! @anatoo,  
Greeting for the day! 
Onsen UI 2.0  material design is not working with android 4.2 when I tested it. another, this not faster than previous version onsen UI 1.x.
What is the benefit of 2.0 version?

**Comment by anatoo** [comment]
Hello @DILEEP-YADAV,
Thank for your reporting, we will investigate this problem.

>What is the benefit of 2.0 version?

We are aiming to be the Onsen UI to framework agnostic on 2.0.
In 2.0, developers will be able to use favorite framework such like React, Angular2 or jQuery.

**Comment by RezaRahmati** [comment]
Hu, same problem here, Onsen2 + AngularJs,
Is there any workaround or fix for that?
My app just published and I get a lot negative feedback from users

**Comment by frankdiox** [comment]
@RezaRahmati Can you be more specific? What does not work exactly? I just tested 4.2 and the only problem I've seen so far is a wrong transition effect in `ons-input` and `ons-switch`, what looks like a minor issue. Components like navigator or splitter seem to work as intended.

**Comment by RezaRahmati** [comment]
Sure, I attach some screen shots comparing on 4.2 and 4.4
p.s It's the same on Sim and Device
also when you try to open slide menu it comes and then it detaches from side of screen and then it gets back to proposed position (see 4-2_3.png)
In 4-2_1 the background is gone and style is somehow changed
In 4-2_2 main page is not loaded (it might be some (mine or yours) script which is not supported by 4.2 script engine and it prevents angular controller to run)
In 4-2_3 There is alight ui change, and one important weird behavior, by default when user taps on list item in menu it should shows sub items and when he taps on that tiny button in list items it should close the menu and loads the main screen. it's fine in 4.4, but in 4.2 it seems that tapping on that tiny button cascade event to parent and instead on closing menu and loading items it act as clicking on list item

If you are interested I can send you the apk to see the difference.

![4-4_2](https://cloud.githubusercontent.com/assets/10086092/16718850/af0bbf42-46f1-11e6-8303-9ab487df9ed5.png)
![4-4_3](https://cloud.githubusercontent.com/assets/10086092/16718848/af07bc6c-46f1-11e6-9e5e-136f7f440f54.png)
![4-4_1](https://cloud.githubusercontent.com/assets/10086092/16718849/af0b7708-46f1-11e6-8e2f-48227ecbee7e.png)

![4-2_2](https://cloud.githubusercontent.com/assets/10086092/16718761/da2b29d4-46f0-11e6-89be-398d829106fd.png)
![4-2_3](https://cloud.githubusercontent.com/assets/10086092/16718762/da2d71f8-46f0-11e6-9f14-d8504e0f83c8.png)
![4-2_1](https://cloud.githubusercontent.com/assets/10086092/16718763/da31d77a-46f0-11e6-81ac-72dfcbccf057.png)

**Comment by frankdiox** [comment]
@RezaRahmati Thanks for the images. Is this all related to `ons-sliding-menu`, then? Or are you using `ons-splitter`?

What kind of styles are you applying in the menu? Is it just `background-color`?

**Comment by RezaRahmati** [comment]
This is how I use it
```
    <ons-splitter>
        <ons-splitter-content page="templates\main.html"></ons-splitter-content>
        <ons-splitter-side var="rmenu" side="right" width="250px" collapse="(max-width: 600px)" swipeable page="templates\rmenu.html">
        </ons-splitter-side>
        <ons-splitter-side var="lmenu" side="left" width="250px" collapse="(max-width: 850px)" swipeable page="templates\lmenu.html">
        </ons-splitter-side>
    </ons-splitter>

```

**Comment by frankdiox** [comment]
@RezaRahmati Thanks! I'll try that when I have some free time :)

**Comment by RezaRahmati** [comment]
@frankdiox Thanks a lot, if you say it should work I will try more on it too
