### ISSUE TITLE
OnsenUI 2, without angular/react/jquery

### ISSUE THREAD

**Issue by EddyVerbruggen** [OnsenUI/OnsenUI#1206]
Hey guys,

This may be something I'm overlooking. I very much like the idea that v2 is framework agnostic, but do you have a sample of a v2 app/gist/codepen that uses vanilla JS/ES6 and nothing else?

Cheers,
Eddy

**Comment by frankdiox** [comment]
@EddyVerbruggen Hi! I recently made a simple app with two implementations, AngularJS and vanilla JS. Check it out here: https://github.com/frankdiox/OnsenUI-Material-Tabbar/tree/js-implementation
The link to the demo is actually using the AngularJS version, but you can checkout the JS branch and try it yourself :)

**Comment by EddyVerbruggen** [comment]
Awesome, exactly what I need :+1:  :+1:
