### ISSUE TITLE
When the popover is active and press the back button of device is not work , must touch to the screen to hide the popover and the  device back button work.Any suggestions to control this? Thanks in advance

### ISSUE THREAD

**Issue by kountouretis** [OnsenUI/OnsenUI#1210]
app.js
 `app.controller('DropdownController', function($scope, myService) {
  ons.createPopover('popover.html').then(function(popover) {
    $scope.popover = popover;
    myService.setPopover($scope.popover);
  });
});

app.controller('MyController', function($scope, myService) {
  $scope.hidePopover = function() {
        $scope.popover = myService.getPopover();  
        $scope.popover.hide();
  }
});

app.service("myService", function(){
  var sharedPopover

  var setPopover = function(pop){
    sharedPopover = pop;
  };

  var getPopover = function(){
    return sharedPopover;
  };

  return {
    setPopover: setPopover,
    getPopover: getPopover,
  };
});`
index.html
`<div class="navigation-bar" ng-controller="DropdownController" style=" background-image: url(img/Nicosia-Home-CY.jpg); background-size:100% 100%; font-size:32px; vertical-align:-6px; height:48%;" >
    <div style="width:100%; height:60px; ">

```
        <div style="margin-top:5px; margin-right:5px; color:white;  width:60px; float:right;">
        <label ng-click="popover.show($event);" class="tab-bar__item">
      <input type="radio" name="tab-bar-b">
      <button id="pie" class="tab-bar__button">
        <i class="tab-bar__icon ion-android-menu" style="width:60px; background-color: rgba(25, 142, 187, 0.5);  color:white; height:30px; margin-top:5px;"></i>
        <div class="tab-bar__label" style=" color:white; background-color: rgba(25, 142, 187, 0.5); ">menu</div>

      </button>
    </label>
    </div>
    </div>`
```

`<ons-template id="popover.html" >
  <ons-popover direction="left up" style="height:325px; width:165px;" cancelable >
    <ons-list ng-controller="MyController">
       <ons-list-item modifier="tappable"  id="menu" ng-click="hidePopover(); myNavigator.pushPage('favourites.html', { animation : 'slide' } )">
       <ons-icon icon="ion-chatboxes"></ons-icon>
       &nbsp;&nbsp;language</ons-list-item>  </ons-list>
  </ons-popover>
</ons-template>
`

**Comment by asial-matagawa** [comment]
This issue seems to be duplicated with #1299 (but this issue has more code than #1299). Closing this.
