### ISSUE TITLE
Behavior of ons-navigator replacePage pop animation

### ISSUE THREAD

**Issue by philolo1** [OnsenUI/OnsenUI#1215]
I am a little bit confused about ons-navigator replacePage animation function. Currently it works like this.

We have page1, page2, page3 on the stack. lets say they were pushed by slide animation. Now we replace page3 by newPage with no animation. When i go back on the stack the transition from newPage to page2 is 'none'. I think it would make more sense to have it behave like the previous page (like the transiton from page2 to page3). On the other hand if the animation is not none, and the transitions of page1->page2->page3 are none then it I am not sure what makes sense. 
My main point of discussion is whether we should use the animator of the to be replaced page or not. The user can always specify the animation in popPage options, so its not such a big deal, but still worth the discussion.

**Comment by frankdiox** [comment]
@philolo1 Push and pop animations are created when the page is pushed. If you push a page without animation then it will pop without animation unless you specify something else. By default `replacePage` has 'slide' animation if I'm not wrong, so you will get a 'slide' pop animation as well by default. I think that's the desired behavior.
