### ISSUE TITLE
ons-split-view slides back after scrolling within the content of it

### ISSUE THREAD

**Issue by rockneverdies55** [OnsenUI/OnsenUI#1222]
I have an `ons-split-view` with a long list of chevron (tappable) items wrapped in a `ons-splitter-side`. If I scroll the list within the split to select an item, the split view slides back without letting me click on a list item. 
Is there a way to stop this?

**Comment by IliaSky** [comment]
Thank you for the report. This should be fixed when we release beta 7.
In the meantime you can use this ugly hack:
```javascript
onsSplitter.addEventListener('dragstart', function(e){
	if (e.gesture.direction === 'up' || e.gesture.direction === 'down') {
		onsSplitterSide._getModeStrategy()._ignoreDrag = true;
	}
});
```
`onsSplitter` and `onsSplitterSide` being the `ons-splitter` and `ons-splitter-side` elements.

**Comment by rockneverdies55** [comment]
Thanks for taking care of this and offering a working temp solution.

**Comment by IliaSky** [comment]
You're welcome. The fix is already in place, so feel free to use the newer version when it becomes available. I am closing this issue.
