### ISSUE TITLE
Add e2e test for navigator.insertPage

### ISSUE THREAD

**Issue by philolo1** [OnsenUI/OnsenUI#1233]
Looking through the e2e tests I realized the navigator test is testing replacePage and resetPage, push and pop page, but not insertPage. @argelius does it make sense to add one, i can do it.

**Comment by argelius** [comment]
I think it makes sense to add one.

**Comment by philolo1** [comment]
@argelius ok, will do it then, i assigned it to myself, since i am working on the tests right now anyway.

**Comment by argelius** [comment]
Thanks!

**Comment by philolo1** [comment]
@argelius added the test in a pull request.
