### ISSUE TITLE
Where is checkbox--list-item modifier?

### ISSUE THREAD

**Issue by c58** [OnsenUI/OnsenUI#1244]
I'm playing with latest Onsen 2 beta and i found that there is no "list-item" checkbox modifier anymore. How should i use checkboxes and radio buttons with "list-item" now?

**Comment by c58** [comment]
I found answer in a doc, sorry
```HTML
<div class="list__item__left">
          <label class="checkbox">
            <input type="checkbox" id="checkbox1" class="checkbox__input" name="c" checked="checked">
            <div class="checkbox__checkmark"></div>
          </label>
        </div>
        <label for="checkbox1" class="list__item__center">
          Checkbox
        </label>
</div>
```

**Comment by philolo1** [comment]
@c58 we also released a community, feel free to ask there : https://community.onsen.io/.

**Comment by frankdiox** [comment]
@c58 In beta.7 you will be able to do `<ons-input type="checkbox"></ons-input>` :)
