### ISSUE TITLE
ons-navigation page on OnsenUI2 not loading from $templateCache

### ISSUE THREAD

**Issue by leocaseiro** [OnsenUI/OnsenUI#1245]
I updated my app from OnsenUI1 to OnsenUI2 and I realized that doesn't work if I want to cache with
[$templateCache](https://docs.angularjs.org/api/ng/service/$templateCache).

I have some plunker to show what I meant.
Please ignore CSS, I didn't add to plunkr.

* Working **ons-navigation** without $templateCache
http://plnkr.co/edit/wnJn2WqIbbSGGNzob4YC?p=preview

* Working with **$templateCache** and **ng-include**
http://plnkr.co/edit/8GpkSVl5Ywg6YoXfarh3?p=preview

* Not working with **$templateCache** and **ons-navigation**
http://plnkr.co/edit/1b4awWKUr8ovmFzGv2j3?p=preview

PS: On OnsenUI1 it used to work normally.

Any thoughts?

**Comment by cither1** [comment]
Same problem: https://github.com/OnsenUI/OnsenUI/issues/1209

**Comment by leocaseiro** [comment]
My bad, didn't see it.

**Comment by cskiwi** [comment]
Hi, was this fixed or not?
because I can't seem to get it working. I'm on RC4

**Comment by IliaSky** [comment]
I answered you at #1209.
Unfortunately it's not properly fixed, but I provided a simple hack to make it work.
