### ISSUE TITLE
Missing documentation ons-splitter-side function toggle 

### ISSUE THREAD

**Issue by philolo1** [OnsenUI/OnsenUI#1256]
The function toggle in OnsenUI/core/src/elements/ons-splitter-side.js is not documented and thus does not appear on https://onsen.io/2/reference/ons-splitter-side.html

@anatoo  can you take a look at it?

**Comment by anatoo** [comment]
@philolo1 OK, I will write the doc comment for "toggle" method.

**Comment by IliaSky** [comment]
Update: 
The documentation was added to master when branch `ons-splitter-refactor` was merged. It should be available on the website when we rebuild the docs again, so I'm closing this issue.
