### ISSUE TITLE
attach click event handler to elements within ons-popover

### ISSUE THREAD

**Issue by rockneverdies55** [OnsenUI/OnsenUI#1268]
Since you guys don't support html `select` element, I'm trying to use `ons-popover` instead. But having some difficulties doing so.

I have a button that launches a popover when clicked. The popover contains a list of elements to choose from. When user clicks on list item within the popover, I would like to catch that click and mark the list item as the selected element. However I can't do that. I cannot attach event listener to list-item elements.

jquery event listener doesn't work: `$('ons-list-item').on('click', function() {....});` 
backbone events hash also doesn't work: `events: {'click ons-list-item': 'listitemClickHandler'}`

I cannot even use `popover.on` function because it returns `popover` doesn't have `on` function. Though I can see that the function is documented [in here](https://onsen.io/2/reference/ons-popover.html)

What should I do? I need a `select` like solution within a non-angular app. Any recommendation would be appreciated.

**Comment by munsterlander** [comment]
I accomplished this using the following code:

```
var popover;

        ons.createPopover('x01_options.html').then(function(element) {
          popover = element;
        });
```

```
<ons-popover direction="down" cancelable>
    <ons-list>
      <ons-list-item modifier="tappable" onclick="document.getElementById('gmMode').innerHTML='301';popover.hide();">301</ons-list-item>
      <ons-list-item modifier="tappable" onclick="document.getElementById('gmMode').innerHTML='501';popover.hide();">501</ons-list-item>
      <ons-list-item modifier="tappable" onclick="document.getElementById('gmMode').innerHTML='701';popover.hide();">701</ons-list-item>
    </ons-list>
</ons-popover>
```


```
<ons-page>
    <ons-toolbar>
        <div class="left"><ons-back-button>Back</ons-back-button></div>
        <div class="center">X01</div>
        <div class="right">
            <ons-toolbar-button onclick="show('#x01Opt')" id="x01Opt">
                <ons-icon icon="ion-navicon" style="font-size: 32px; width: 1em;"></ons-icon>
            </ons-toolbar-button>
        </div>
    </ons-toolbar>    
</ons-page>
```

**Comment by rockneverdies55** [comment]
Thank you @munsterlander. I have done something similar to overcome the problem. I attached event bubbling event listener on `document` object.
