### ISSUE TITLE
Material Tappable ons-list-item in a ons-list fails to change state when tapped

### ISSUE THREAD

**Issue by SharkChips** [OnsenUI/OnsenUI#1280]
Version: 2.0.0-beta5
Affected Platforms: all

When putting a ons-list-item with the modifiers "material" and "tappable", only the *last* item shows the color change when tapping. The others do not change state. 

Note that tappable does work when not used with the material modifier

**Comment by IliaSky** [comment]
Sorry about the late response. 

From beta5 we have made a lot of changes, so right now I don't seem to be able to reproduce the issue with beta15 ([Demo](http://codepen.io/IliaSky/pen/eZPBgL?editors=1000)), so I will close this.

If you are still able to reproduce it with the newer version please tell us.
