### ISSUE TITLE
can't exit from app if page has ons-splitter element

### ISSUE THREAD

**Issue by prophetzoli** [OnsenUI/OnsenUI#1300]
Maybe bug:
file: elements/ons-splitter/index.js
line: 304 ( _onDeviceBackButton )
const left = this._getSideElement('left');
const right = this._getSideElement('right');

If <ons-splitter-side> element is set as "left", than test if "right.isOpen()" return error, because "const right" is null.

I removed these lines, and now I'm able to exit from app.

**Comment by frankdiox** [comment]
@prophetzoli Thanks for reporting!
