### ISSUE TITLE
Onsen-UI material glow effect when scrolling

### ISSUE THREAD

**Issue by qqruza** [OnsenUI/OnsenUI#1316]
I am trying to achieve the effect which has been used in Material Design when you're scrolling and at the top and bottom there is a glow effect when you reach the end of the content.

I have found the java script example (see the link below) but curious if there is any simpler solution for Onsen UI?

https://jsfiddle.net/psd1768d/

**Comment by IliaSky** [comment]
Currently we don't provide any way to do that effect from within Onsen UI. 
We may consider it for a future release, so stay tuned.
Util then feel free to use the example which you provided.

**Comment by vasilyzakharov** [comment]
Is there any update on this enhancement? Thank you in advance
