### ISSUE TITLE
Component prototypes are broken in React+iOS+Safari

### ISSUE THREAD

**Issue by ryanfields** [OnsenUI/OnsenUI#1328]
In iOS Safari, components fetched with React's ```ref``` attribute seem to have broken prototypes.  My code looks like this:

```jsx
export default class AppMenu extends React.Component {
  componentDidMount() {
    this.updateOpenState();
  }

  componentDidUpdate() {
    this.updateOpenState();
  }

  updateOpenState() {
    let side = this.refs.side;

    if (this.props.isOpen) {
      side.open();
    } else {
      side.close();
    }
  }

  render() {
    return (
      <ons-splitter-side side="left" width="80%" collapse="portrait" ref="side">
        <ons-page></ons-page>
      </ons-splitter-side>
    )
  }
}
```

In the other browsers I've tested, this works exactly as expected.  I click a button somewhere else, the isOpen prop changes, and the menu slides open or closed.

On iOS Safari, any attempt to call methods on ```side``` results in a ```TypeError: side.method is not a function.``` error.

I can't call ```open``` or ```close```.  I can't call ```isOpened```.  Nothing works.  However, if I do a ```console.dir``` on side and expand its prototype, I can see those methods defined there.  It's really bizarre and I've got no idea what's going on.  Nothing looks wrong with the prototype on visual inspection, but it's just not working and I can't find a workaround.

**Comment by argelius** [comment]
Thanks for reporting @ryanfields ! We will take a look at this.

**Comment by philolo1** [comment]
probably you should do something like this:
```
  componentDidMount() {
    CustomElements.upgrade(this.refs.side);
    this.updateOpenState();
  }
```
In the future we will have an ons-splitter element. We recently only started with the react support, have a look at this post: https://onsen.io/blog/react-onsen-ui-preview/.

**Comment by ryanfields** [comment]
@philolo1 Attempting the CustomElements.upgrade call results in:

```
TypeError: null is not an object (evaluating 'this._mask.style')
```

I realize React support is new, and I've read that page.  However, this seems to be a quirk of iOS Safari.  My code is working fine everywhere I've been able to test except for that specific browser.

**Comment by philolo1** [comment]
@ryanfields thanks i will look at it and come back to you, appreciate your feedback and your bug report!

**Comment by trungtin** [comment]
I can't even make it work with React while using OnsenUI-dist.git#2.0.0-react.5, maybe make mistake somewhere, but:
- this.refs.side._collapseMode return {_active: false, _state: "closed", _element: ons-splitter-side, _lock: DoorLock}.
- And because of that this.refs.side.open() and .close() return a Promise resolve to `false`. 
I have try CustomElements.upgrade for both `ons-splitter` and `ons-splitter-side` to no avail :(. 
And when ons-splitter have attr collapse="portrait", it throw `ons is not defined` with this function ons.orientation.isPortrait()

**Comment by argelius** [comment]
Since we release React components I will close this. Please take a look at [this page](https://onsen.io/v2/react.html)
