### ISSUE TITLE
ReferenceError: ons is not defined with browserify

### ISSUE THREAD

**Issue by kirantpatil** [OnsenUI/OnsenUI#1335]
Steps to reproduce:
------------------------
1. $ npm install onsenui@2.0.0-beta.7

2. create main.js file with below contents
   
 var onsen = require('onsenui/js/onsenui');

onsen.ready(function() {
  onsen.notification.alert({message: 'Onsen UI works with browserify!'});
});

3. $ browserify main.js -o bundle.js

4. create a on_test.html file with only below line

 `<script src="bundle.js"></script>` 

5. Then open the on_test.html file in firefox browser and it gives below error as shown in screenshot

![screenshot from 2016-04-04 11-26-43](https://cloud.githubusercontent.com/assets/1178055/14239353/4cd00968-fa58-11e5-8812-034d021ead68.png)

**Comment by frankdiox** [comment]
@kirantpatil Thanks. That's already fixed in beta.8. I'm closing this now, open it again if you still get errors.

**Comment by kirantpatil** [comment]
Thanks and checked and it works.
