### ISSUE TITLE
Toolbar display not well while using both slide menu and navigator (Iphone only)

### ISSUE THREAD

**Issue by tienuit** [OnsenUI/OnsenUI#1340]
I use the example code (onsen 2 beta9)
http://codepen.io/frankdiox/pen/qEyvxB

but I got a problem on Iphone, the status bar and toolbar got something wrong
P1 - With both slide menu anf navigator
![img_2639](https://cloud.githubusercontent.com/assets/5275476/14279135/c3c235f2-fb55-11e5-9d03-8e73ded221ef.PNG)

P2 - Remove navigator
![img_2640](https://cloud.githubusercontent.com/assets/5275476/14279137/ca209eb6-fb55-11e5-8f07-dc7859a0476b.PNG)

**Comment by IliaSky** [comment]
Thank you for the bug report and sorry for the late reaction. It should be fixed now.
Also if you run into similar problems and we don't respond in time you can disable the `auto status bar fill` feature and just manually add a `status-bar-fill` attribute to the element which you want to consume the iOS status bar.
