### ISSUE TITLE
OnsenUI Forms

### ISSUE THREAD

**Issue by kirantpatil** [OnsenUI/OnsenUI#1341]
Hi,

I would like to convert bootstrap forms to OnsenUI forms. May I know how achieve this ?

I could not find Onsen form tag in https://onsen.io/2/reference/javascript.html.

Thanks.

**Comment by munsterlander** [comment]
Onsen does not have that tag other than material input.  A form in Onsen, is just a regular HTML form, so code it like normal.

**Comment by kirantpatil** [comment]
Thanks.
