### ISSUE TITLE
AngularJs+Onsen scroller not working 

### ISSUE THREAD

**Issue by zilinxueyue** [OnsenUI/OnsenUI#1345]
Hi, All I am try to used the ons-scroller with angularjs. but when I set ng-model for the ons-scorller. the $scope can not get the scroller element. Can some one can help to share how to do it? Or some demo for it?
Thanks so much!

**Comment by IliaSky** [comment]
Which version of Onsen UI are you using?
We removed the `ons-scroller` from version 2 recently. For a long time it was being used only for css.
If that's what you need then feel free to use this css instead:


	.scroller {
	  display: block;
	  height: 100%;
	  overflow: auto;
	  -webkit-overflow-scrolling: touch;
	  -ms-overflow-style: none;
	  -ms-scroll-snap-type: mandatory;
	}

This is what the `ons-scroller` had.

If you need some other functionality then feel free to use `ons-page` instead. (For example you should be able to use `<ons-page var="myScroller">` and get the reference that way.)
