### ISSUE TITLE
Dynamic Icon Display Issue (Angular/Onsen v2.0.0-beta.5)

### ISSUE THREAD

**Issue by ginevive** [OnsenUI/OnsenUI#1352]
When setting an icon dynamically via Angular scope variable, it appears that the icon prefix is not taken into account.  

When I set the icon statically, the icon is displayed as expected.  However, when I set it dynamically, it does not.  When the element is inspected in the browser the correct icon code appears exactly the same as when set statically, but further inspection shows that the classes applied on the dynamically set icon are for font awesome rather than ion.  This leads me to believe that the ons-icon template is looking for a font awesome icon rather than an ion icon.

**Working**

My HTML
`<ons-icon icon="ion-ios-home" fixed-width="true"></ons-icon>`

Styles (Inspected in Chrome Dev Tools)
```
ons-icon[fixed-width="true"] {
    width: 1.28571429em;
    text-align: center;
}
.ons-icon--ion {
    line-height: 0.75em;
    vertical-align: -25%;
}
.ons-icon {
    display: inline-block;
    font-style: normal;
    font-weight: normal;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
```

**Not Working**

My HTML
`<ons-icon icon="{{path.link.icon}}" fixed-width="true"></ons-icon>`

Styles (Inspected in Chrome Dev Tools)
```
ons-icon[fixed-width="true"] {
    width: 1.28571429em;
    text-align: center;
}

.ons-icon {
    display: inline-block;
    font-style: normal;
    font-weight: normal;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
.fa {
    display: inline-block;
    font: normal normal normal 14px/1 FontAwesome;
    font-size: inherit;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
```

**Comment by argelius** [comment]
@ginevive It looks like something goes wrong when it's initialized with `icon="{{path.link.icon}}"`, you can solve this by using `ng-attr-icon="{{path.link.icon}}"` instead.

Does that work?

I believe we can make the code you wrote work as well so I will keep this open.

**Comment by ginevive** [comment]
Works perfectly.  Thank you for the quick response.

If it helps, the original code I used is working in OnsenUI v1.3.15.
