### ISSUE TITLE
[Onsen 2.0.0-beta.9] iOS 8.4 - Angular ons-page ons-show never fired

### ISSUE THREAD

**Issue by logicweb** [OnsenUI/OnsenUI#1359]
The "show" event is never fired on iOS 8.4, both real device and simulator.
Everything is fine on iOS 9.x and Android.

My app is a Cordova app and use a SlideMenu as base. The mainPage.html recive only the init event.

**Comment by logicweb** [comment]
Version 2.0.0-beta.8 was fine.

**Comment by logicweb** [comment]
This is a test project, based on my app structure. 
I have included even the beta.8 lib, which works, to comparison.
The bug is present even on Safari on iOS 8.4, so it's not related to cordova.
[onsen_beta_9_page_show_bug.zip](https://github.com/OnsenUI/OnsenUI/files/217715/onsen_beta_9_page_show_bug.zip)

**Comment by logicweb** [comment]
Tested with the latest build (just compiled), still doesn't work
I've prepared an even simpler test:

**app.js**
`

    var app = angular.module('app', ['onsen.directives']);

    app.controller('NavigationController', function ($scope, $timeout) {
        console.log("NavigationController - constructor");
        var _this = this;
        var myNav
        
        ons.ready(function () {
            console.log("Ready");

            //            $timeout(function () {
            _this.initNav();
            //            }, 100);
        })

        this.initNav = function () {
            myNav = ons.findComponent("ons-navigator", document.body);
            myNav.on("init", function (evt) {
                console.log("onPageInit", evt.page);
            })
            myNav.on("show", function (evt) {
                console.log("onPageShow", evt.page.name);
            })
            console.log("NavigationController - myNav", myNav);
            var options = {
                callback: function () {
                    console.log("Home Pushed Success");
                }
            };
            myNav.pushPage("home.html", options);
            //            myNav.replacePage("home.html", options);
            //            myNav.insertPage(0, "home.html", options);
        }

        this.show = function () {
            console.log("NavigationController.show");
        };

    });

    app.controller('HomePageController', function ($scope, $timeout) {
        console.log("HomePageController - constructor");
        this.divText = document.getElementsByClassName("textDiv")[0];
        this.isLoading = false;

        this.showHome = function () {
            console.log("HomePageController.show");
            this.divText.innerHTML = "Show!";
        };

        this.hideHome = function () {
            console.log("HomePageController.hide");
        };
    });
`


**index.html**
`
<div ng-controller="NavigationController as nc" ons-show="nc.show()">
        <ons-navigator var="nav"> </ons-navigator>
    </div>

    <ons-template id="home.html">
        <ons-page ng-controller="HomePageController as hpc" ons-show="hpc.showHome()" ons-hide="hpc.hideHome()">
            <div ng-if="hpc.isLoading">
                <ons-progress-circular indeterminate class="circlePreloader"></ons-progress-circular>
            </div>
            <div class="textDiv">waiting...</div>
        </ons-page>
    </ons-template>`

**Comment by logicweb** [comment]
I think I have just find out... the ons-progress-circular.
Without this:
`<ons-progress-circular indeterminate class="circlePreloader"></ons-progress-circular>`
all works fine.

**Comment by logicweb** [comment]
I think I have just find out... the ons-progress-circular.
Without this:
`<ons-progress-circular indeterminate class="circlePreloader"></ons-progress-circular>`
all works fine.

**Comment by IliaSky** [comment]
@logicweb Thank you very much for your help.
The bug was being caused by the svg being used in `ons-progress-circular`. It turns out on iOS 8.4 the `svg` elements don't have a `children` property which we were using in some dome traversals. And for some other reasons the error was hidden.
This has just been fixed, so it should be fine as soon as we release beta 14.
