### ISSUE TITLE
empty ons-list-item content with chevron modifier

### ISSUE THREAD

**Issue by prophetzoli** [OnsenUI/OnsenUI#1360]
I have an issue with ons-list-item. If I add chevron modifier to this item, the whole content is empty. But only on some Android devices (maybe on android 4.1.x versions).

Maybe "display:flex" CSS property in ".list__item--chevron:before" class is the problem.

**Comment by argelius** [comment]
Thanks for reporting @prophetzoli ! Can you supply some code that reproduces this error?

I will try myself. The old version of flexbox is supposed to work on Android 4.1 but there may be some inconsistencies.

**Comment by argelius** [comment]
@prophetzoli By the way. Is using Crosswalk an option? There probably won't be any trouble like this if you're using Crosswalk.

**Comment by argelius** [comment]
@prophetzoli I have verified that this happens in Android 4.1 WebView. Remote debugging is not supported in this WebView so solving the issue might take some time since we need to use trial and error.

**Comment by prophetzoli** [comment]
I tried one Huawei device and also Asus Fonepad from testdroid online service (both 4.1.2 android version)

I dont use Crosswalk.

But as I wrote, when you change display option (from flex to i.e. block), the content is visible (but the arrow is not on the correct position :))
