### ISSUE TITLE
White Blank Screen after Splash Screen 

### ISSUE THREAD

**Issue by wishbooks** [OnsenUI/OnsenUI#1363]
__Environment__
Onsen 2 beta
Angular 1.4.3
iOS 9.3
Cordova iOS - 4.0.1
Cordova cli - 6.1.1

__Encountered problem__
Some times white screen (plain index.html) page is coming. Ons.ready event is also not firing in this case. 

__How to reproduce__
With this environment this issue always occuring

**Comment by argelius** [comment]
Thanks for reporting @wishbooks ! Do you get any errors in the console?

**Comment by wishbooks** [comment]
No. Errors are coming.

**Comment by argelius** [comment]
I will close this since we are unable to reproduce it.
