### ISSUE TITLE
ons.popover does not work in iOS

### ISSUE THREAD

**Issue by kanakoubukata** [OnsenUI/OnsenUI#1370]
__Environment__
Onsen UI2 beta9
iOS8.1.3 / iOS9.0.4

**Comment by IliaSky** [comment]
Are you sure you updated the css files? The implementation for popover was changed in beta 8, so the styles also changed. 

I just checked iOS 9.0 and it works fine, so maybe it's either an update issue or some specific problem for the page and way of calling it. Can you provide some more information?

**Comment by IliaSky** [comment]
The issue was found elsewhere so I'm closing this one.
