### ISSUE TITLE
【OnsenUI2.0.0-beta9】 ons-speed-dial does not work.

### ISSUE THREAD

**Issue by kanakoubukata** [OnsenUI/OnsenUI#1371]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Monaca Cloud IDE
Android6.0.1
Onsen UI2 beta9
（When beta7, It does worked. )

__Encountered problem__
Error Message: 
www/components/loader.js:1468 Uncaught TypeError: Cannot read property 'setAttribute' of null
www/components/loader.js:1468 Uncaught TypeError: Cannot read property 'setAttribute' of null

__How to reproduce__

```
<ons-speed-dial position="bottom center" direction="up">        
        <ons-icon icon="plus" size="20px"></ons-icon>        
        <ons-speed-dial-item>A</ons-speed-dial-item>        
        <ons-speed-dial-item>B</ons-speed-dial-item>        
</ons-speed-dial>
```

**Comment by frankdiox** [comment]
@kanakoubukata `ons-speed-dial` does not create an internal `ons-fab` automatically anymore. From beta.9 you have to provide the `ons-fab`:

```
      <ons-speed-dial position="left bottom" direction="right">
        <ons-fab>
          <ons-icon icon="md-car"></ons-icon>
        </ons-fab>
        <ons-speed-dial-item>C</ons-speed-dial-item>
        <ons-speed-dial-item>B</ons-speed-dial-item>
        <ons-speed-dial-item>A</ons-speed-dial-item>
      </ons-speed-dial>
```
