### ISSUE TITLE
Dynamic carousel item size

### ISSUE THREAD

**Issue by smartm0use** [OnsenUI/OnsenUI#1378]
It could be great if item-width is applicable to single carousel item, instead of to carousel.
In this way partial swipe could be possible.

I mean something like "Right Menu Solution 2" described here: http://stackoverflow.com/questions/36745281/onsen-how-to-make-partial-swipe-on-item/36747886

**Comment by IliaSky** [comment]
Thank you for the suggestion. Right now we're busy with the official release of Onsen 2, so we're focusing mainly on bugs, but adding the option for dynamic carousel width is definitely something which we may consider adding in the future. However our experience has shown us that these type of things tend to become hard to support if not very well written, so right now it's not on our priority list.
