### ISSUE TITLE
Replace mutation events with MutationObserver.

### ISSUE THREAD

**Issue by anatoo** [OnsenUI/OnsenUI#1388]
There are mutation events in ons-popover implementation:  https://github.com/OnsenUI/OnsenUI/blob/87e4f4aba127a823ba61a940adcb1ebcd3ad1447/core/src/elements/ons-popover/index.js#L523-L524

Mutation events are deprecated. We should replace with MutationObserver.

**Comment by argelius** [comment]
Looks like these lines are not needed anymore so I will just remove them.
