### ISSUE TITLE
Input elements should maintain internal state

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#1390]
Because of the `contentReady` function all the input elements, `<ons-input>`, `<ons-switch>` and `<ons-range>` setter methods are asynchronous.

I think we should add an internal `_value` or `_checked` state for these elements and correctly set the value of the internal input when it's rendered.

Right now this fails:

```
const input = document.createElement('ons-input')
input.value = 'Test';
console.log(input.value); // Uncaught TypeError: Cannot read property 'value' of null(…)
```

**Comment by frankdiox** [comment]
`var a = document.createElement('ons-input'); a.value = 'hoge';`
`a.value // hoge`

```
<ons-input value="hoge">
  <label class="text-input__container">
    <input class="text-input" value="hoge">
    <span class="_helper text-input__label text-input__label--active" style="color: rgba(0, 0, 0, 0.498039);"></span>
    <span class="input-label"></span>
  </label>
</ons-input>
```
This works under normal conditions as of today, maybe something changed in the core and it was fixed. Closing this for now.
