### ISSUE TITLE
navigator.getCurrentPage is not a function

### ISSUE THREAD

**Issue by bdedardel** [OnsenUI/OnsenUI#1393]
__Environment__
Onsen 2 rc4
Angularjs

__Encountered problem__
TypeError: $scope.myNavigator.getCurrentPage is not a function

__How to reproduce__
Migrating from onsenui2.beta to onsenui2.rc

**Comment by philolo1** [comment]
Try this $scope.myNavigator.topPage , 
I think we renamed it.

**Comment by bdedardel** [comment]
If i log myNavigator, i obtain : 

```
constructor Class()
_boundOnPostpop _onPostpop()
_boundOnPrepop _onPrepop()
_clearDerivingEvents function()
_clearDerivingMethods function()
_compileAndLink _compileAndLink(pageElement, callback)
_createPageScope _createPageScope()
_destroy _destroy()
_onPostpop _onPostpop(event)
_onPrepop _onPrepop(event)
bringPageTop function()
canPopPage function()
emit function(event /*, args... */)
init init(scope, element, attrs)
insertPage function()
off function(event, fct)
on function(event, fct)
once function(event, fct)
popPage function()
pushPage function()
replacePage function()
resetToPage function()
```

I don't find topPage or currentPage

**Comment by argelius** [comment]
@bdedardel `navigator.topPage` is a property, not a method. Did you update both `onsenui.js` and `angular-onsenui.js` ?

The `topPage` property works fine when I try to access it.

**Comment by bdedardel** [comment]
... Yes, it works fine as property !
Many thanks for your help.

**Comment by argelius** [comment]
@bdedardel Glad you were able to solve it :+1:
