### ISSUE TITLE
Passing param1 to pushPage

### ISSUE THREAD

**Issue by bdedardel** [OnsenUI/OnsenUI#1395]
__Environment__
Onsen 2 rc4
Angularjs

__Encountered problem__

I try to pass parameter, as explain in the doc: https://onsen.io/v2/docs/angular1/navigation.html
... but I fail to get it, in then() function

```
this.myNavigator.pushPage('my-page.html', {param1 : 'test', animationOptions: {animation: "none"}})
  	.then(function(page) {
    	console.log("Parameter passed: ", page); 
});

=> Parameter passed: <ons-page id="my-page" class="page ng-scope" on-device-backbutton="onBackButton();" ng-controller="MyController as myCtl" _compiled="" name="my-page.html" style="display: block;">
```

Notice: I can see parameters in pageinit event:

```
document.addEventListener("pageinit", function(e) {
	console.debug("pageinit: '" + e.target.id + "'", e);

=> pageinit: 'my-page'
       target.pushedOptions => Object { animationOptions={...},  param1="test",  page="my-page.html"}
```

**Comment by IliaSky** [comment]
I guess there is a small error in the docs. The `options` property is currently called `pushedOptions` as I guess you noticed when you were accessing it from the `pageinit` handler. Just to be sure - after 

    console.log("Parameter passed: ", page); 
you have something like

    console.log("Options: ", page.pushedOptions); 
right? 

But it's `undefined` is what you're saying, right?

__Side note:__ If you have some data which you want to use we recommend putting it inside the `data` property of the `options` object. If everything works fine you should be able to access it through `page.data`.

**Comment by frankdiox** [comment]
@bdedardel As @IliaSky mentioned, the correct way to get the parameters is with [`page.data` property](https://onsen.io/v2/docs/angular1/ons-page.html#properties). This requires to pass the parameters in a `data` object like this: `myNavigator.pushPage('page.html', { data: { ... }, animation: 'lift', animationOptions: { ... } }`. Looks like we made a mistake when writing that part of the docs in Angular 1, we'll fix it :)

**Comment by bdedardel** [comment]
Thanks, it works fine with 'data' property

```
this.myNavigator.pushPage('my-page.html', {data : 'test', animation: "none"})
    .then(function(page) {
        console.log("Parameter passed: ", page.data); 
});
```

Note: for those who use typescript, don't forget to update (or modify) onsenui.d.ts

```
interface navigatorOptions {
    animation?: string;
    onTransitionEnd?: any;
    animationOptions?: any;
    data?: any;
}
```
