### ISSUE TITLE
Stop loading css files dynamically

### ISSUE THREAD

**Issue by gotenxds** [OnsenUI/OnsenUI#1398]
**Environment**
Onsen 2 beta 6
Angular 1.5.2
android

**Encountered problem**
In my prod env I pack all of my css files into a single all.css file.

Onsen errors because It tries to load font_awesome and more css files (that already exist in the all.css file) this makes no sense, you should not load those files dynamically, instead include them in a bundle.css file or require the user to add them himself.

**Comment by munsterlander** [comment]
Just responded on Gitter, but how would Onsen know that you repacked the files?  Those are built-in pointers.  Comparing class names on build would be a tremendous burden to the compiler.  Additionally, I for one do not repack them and if they change Onsen to support that, then it would mean everyone else would have to change their default behavior for what is an expected result, i.e. ons-icon. 

On a side note, are you see a drastic performance increase by doing this or is it a personal preference?

**Comment by gotenxds** [comment]
They dont need to know, they shouldent do it in the first place, its bad practice, what If I change my file location?
Why do I have to discover in a prod build that the app wont work because they load files from the node_modules - that I, like most npm users dont pack in my final build.

Instead just requiering the user to load the css file manualy (just like they require you to load onsenui.css AND the onsen-css-components.css) is a better solution that will not surprise any one later.
Even a better solution would be to just pack all the needed css files onsenui onsen components and the font awesome + material iconic css files into a single file, they are required after all.

**Comment by munsterlander** [comment]
But that is exactly what is happening.  In onsenui.css:

```
@import url("font_awesome/css/font-awesome.min.css");
@import url("ionicons/css/ionicons.min.css");
@import url("material-design-iconic-font/css/material-design-iconic-font.min.css");
```

All of this is within the Onsen CSS folder.  If you are copying the Onsen CSS to another file, then you would also need to grab those.

**Comment by gotenxds** [comment]
Its very simple, i have a list of files (css's, js's) that i need in my project, when I compile to a prod environment I have gulp compress all of my css files into one file.
If somewhere in that file there is an import statement that runs in run time, it will fail beacuse the content does not exist in a seperate file, but in the same file.

I dont understand why this is so weird to you, its a standard thing to do in a prod environment. 
https://www.npmjs.com/package/gulp-concat
--------------------

If a library like this one does not expose its requirements a head of time but instead tries to load them in run time, there is nothing I or anyone can do without changing their code.

**Comment by munsterlander** [comment]
I do understand what you are saying and you are saying exactly what I am trying to point out.  This is not an Onsen issue.  As you have stated, you are using Gulp to compress your files.  It is Gulps issue, hence why they have [gulp-cssimport](https://www.npmjs.com/package/gulp-cssimport), [gulp-concat-css](https://www.npmjs.com/package/gulp-concat-css), and lots of others.

This isn't an Onsen problem.  This is a compiler / minify-er / compresser issue.  Imports are normal for dev and that is what the framework allows you to do. If you want to minify your code for prod then of course you will have to do some modifications to get to your goal.  Onsen also includes angular and react now, which I strip out for my production apps to reduce overall size;  BUT I do not think that Onsen needs to remove that just to fit my project needs.  That is all I am trying to say.

Each persons / companies project needs vary and to call it a bug, it would have to affect everyone which I do not think it does.  Just my two cents.  That is all.

**Comment by gotenxds** [comment]
Imports are normal for devs and the gulp-concat-css are for DEVS, not for a final product, a framework should come packed and finished and should not work diferently on different environments,  if the guide says all you need to do for the framework to run is to include files A and B then thats all you need to do.

For example take both bootstrap and material, you can bet they have loads of @imports in thier code. 
But none in the final css file they publish and for that exact reason.
In the docs they specify, if you need feature X include bootstrap_x.css file
They do not include files beacuse they cannot know in advance the project stracture of the user, they as a framework need to give a closed black box for the end user.

I will change my code to use concat css, but I do believe this is a framework issue that should be fixed.

**Comment by munsterlander** [comment]
Can this be closed as I believe there isn't any further discussion?
