### ISSUE TITLE
List header has the same color as list items

### ISSUE THREAD

**Issue by corneyl** [OnsenUI/OnsenUI#1401]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Onsen 2 RC 4

__Encountered problem__
List header has the same background as list items, and `$list-header-background-color` from the theme files is ignored.

__How to reproduce__
Just create a list:
```
<ons-list modifier="inset">
  <ons-list-header>Header Text (should be gray?)</ons-list-header>
  <ons-list-item>Item</ons-list-item>
  <ons-list-item>Item</ons-list-item>
</ons-list>
```

**Comment by frankdiox** [comment]
@corneyl Hi! Sorry but I can't see any problem [here](http://tutorial.onsen.io/?framework=vanilla&category=Reference&module=list). That's rc.4.

**Comment by IliaSky** [comment]
@frankdiox I think I'm able to reproduce it there (actually it seems that over there they are transparent but the `.page__background` is gray). Anyway it seems like it's just not used in the stylus. Adding the missing line will fix the issue. :)

**Comment by IliaSky** [comment]
@corneyl The issue was fixed but then we checked that actually in the new iOS design it was supposed to be transparent. 

So I guess if you want you can set it by yourself. As you noted, the `$list-header-background-color` isn't used and thus has been removed.

**Comment by corneyl** [comment]
And it seems like the same counts for Android: [design specs](https://www.google.com/design/spec/components/lists.html). 
Thanks!
