### ISSUE TITLE
ons-carousel doesn't show up in full-screen

### ISSUE THREAD

**Issue by brampauwelyn** [OnsenUI/OnsenUI#1404]
__Environment__
Monaca CLI
Brackets
Onsen 2 beta 6
Onsen UI
iOS 9.2
Chrome 50.0.2661.94 (64-bit)

__Encountered problem__

Carousel doesn't show up in fullscreen when used on an other page than the active page.

__How to reproduce__

Make two pages with an ons-tabbar.
Page 1 is the current active page.
Page 2 is the non-active page which contains the actual carousel.

When switching from page 1 to page 2, the carousel shows up but it **doesn't** show up in fullscreen. However when we resize / rescale the window of the browser or rotate our device it seems to be fixed and the carousel shows up in fullscreen. 

```
<!-- TABBAR -->
<ons-tabbar>
     <ons-tab page="page1" label="page 1" active></ons-tab>
     <ons-tab page="page2" label="page 2"></ons-tab>
</ons-tabbar>
       
<!-- PAGE 1 -->
<ons-template id="page1">
    <ons-page >
   
       <ons-toolbar>
         <p class="center">Page 1</p>
       </ons-toolbar>
         
   	</ons-page>
</ons-template>


<!-- PAGE 2 -->
<ons-template id="page2">
    <ons-page>
                
		<ons-toolbar>
          <p class="center">Page2</p>
       </ons-toolbar>
            
      <!-- CAROUSEL -->
      
        <ons-carousel fullscreen swipeable auto-scroll id="carousel" var="carousel">
              
            <ons-carousel-item style="background-color:blue;">
             <p>slide 1</p>
            </ons-carousel-item>
            
              
            <ons-carousel-item style="background-color:red;">
         			<p>slide 2</p>
            </ons-carousel-item>
            
         
            <ons-carousel-item style="background-color:yellow;">
              	<p>slide 3</p>
            </ons-carousel-item>
            
        </ons-carousel>
      
   </ons-page>
</ons-template>
```
#### When previewing the application in the browser, we see page 1 (page 1 is also highlighted as active in the tabbar).
![page 1](https://cloud.githubusercontent.com/assets/9402377/15148471/b13c60a2-16c5-11e6-848a-28015b6a8e12.png)

#### When switching to page 2, we see that the carousel is showing up however it isn't in fullscreen and we don't see the background-colors of the different slides:
![page 2](https://cloud.githubusercontent.com/assets/9402377/15148556/facbc03c-16c5-11e6-9819-a83deaffdd8f.png)

#### When we resize the window of the browser or rotate our device, the carousel changes suddenly into fullscreen and the background-color is visible. 
![page 2 with fullscreen carousel](https://cloud.githubusercontent.com/assets/9402377/15148708/ba5f55a8-16c6-11e6-84d4-b9244d0ea576.png)

**Comment by argelius** [comment]
Thanks for reporting @brampauwelyn !

We will take a look at this

**Comment by argelius** [comment]
@brampauwelyn I tried to run your code in the latest release `2.0.0-rc.4` and it works fine. Maybe it isn't an issue anymore.

Can you try again in the latest version?

**Comment by argelius** [comment]
@brampauwelyn There was some code that set the height dynamically causing the issue. It should be fixed now.

We will release a new version with this fix pretty soon

**Comment by brampauwelyn** [comment]
@argelius Thx, looking forward to it 👍
