### ISSUE TITLE
pull-hook doesn't work inside ons-template 

### ISSUE THREAD

**Issue by aarbar** [OnsenUI/OnsenUI#1405]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

** Sorry for the rubbish desc - no time!!

pullHook is null if it is inside a `<page>` element.

__Environment__
Onsen 2 RC 4
Angular 1.5.5

__Encountered problem__
index.html:509 Uncaught TypeError: Cannot read property 'addEventListener' of null

__How to reproduce__
Can't find the ID(var pullHook is null):
```
ons.ready:
var pullHook = document.getElementById('pull-hook');
//pullHook is null ???
 pullHook.addEventListener('changestate', function(event) {


<ons-page>
 <ons-pull-hook id="pull-hook" var="pull-hook">
          Pull to refresh
        </ons-pull-hook>
</ons-page>
```

Can find the ID:
```
var pullHook = document.getElementById('pull-hook');
//pullHook is NOT null ???

 <ons-pull-hook id="pull-hook" var="pull-hook">
          Pull to refresh
        </ons-pull-hook>
<ons-page>
</ons-page>
```

**Comment by argelius** [comment]
@aarbar Probably the `<ons-pull-hook>` element is not attached to the DOM when you try to access it.

The `<ons-template>` will just consume all the content and remove it. It will be inserted when used somewhere in the page.

Maybe you can use event delegation:

jQuery:
```
$(document).on('changestate', '#pull-hook', function() {
  // do something here...
});
```

or you can add the event listener when the page is initialized.

I will close this since I don't think it's an issue. Please feel free to open again if you feel otherwise.

**Comment by aarbar** [comment]
@argelius I'm putting the call inside ons.ready()
```
ons.ready(function(){
   var pullHook = document.getElementById('pull-hook');
})
```
Shouldn't everything be in the dom when ons.ready is fired?
Or is this triggered after The <ons-template> has consumed all the content?

I'm looking at the tutorial:
http://tutorial.onsen.io/?framework=vanilla&category=Reference&module=pull-hook

When I see inspect the dom with chrome developer tools (remote debugging) I can inspect the element and see it in the dom (when I pause/break on the getDocumentByID)
```
<ons-pull-hook id="pull-hook" var="pull-hook">
            Pull to refresh
          </ons-pull-hook>
```

**Anyway - Thanks for your help!**
I'll add a event listener when the page is initialized. 

:)

**Comment by argelius** [comment]
@aarbar I hope you will be able to solve it! Please ask again if you run into some other issues :+1:
