### ISSUE TITLE
ons-lazy-repeat example to use ajax call with multiple rows

### ISSUE THREAD

**Issue by alegauss** [OnsenUI/OnsenUI#1413]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Onsen 2 beta 6
Angular 1.5.2
iOS 9.2

__Encountered problem__

I suggest to create an example to use the ons-lazy-repeat with ajax call that returns multiples rows (i.e. 15 rows per request to webserver). I am trying to implement, and I am using  $scope.$watch to wait te request and update the ons-list-item, but it is not working well.

```
  $scope.MyDelegate = {
            configureItemScope: function (index, itemScope) {
                if (!itemScope.item) {
                    itemScope.canceler = $q.defer();
                    itemScope.moviefeed = JSON.parse(JSON.stringify($scope.jsonMovieFeed));
                    $scope.$watch('wsUpdated', function (newval, oldval) {
                        itemScope.moviefeed = $scope.moviefeeds.feed[index];
                    });
                }

                var itemsPerPage = 5;
                var remainder = index % itemsPerPage;
                if ((remainder === 0) && ($scope.onSenAfter < ((index / itemsPerPage) + 1))) {

                    $scope.onSenAfter = index / itemsPerPage + 1;
                    moviefeeds_service = http://www.example.com/general/page/' + $scope.onSenAfter + '/';
                
              
                    $http.get(moviefeeds_service, {timeout: itemScope.canceler.promise}
                    ).success(function (data) {
                        var items = data.feed;
                        for (var i = 0; i < items.length; i++) {
                            $scope.moviefeeds.feed.push(items[i]);
                        }
                        $scope.wsUpdated = $scope.onSenAfter;
                        itemScope.moviefeed = $scope.moviefeeds.feed[index];

                    });

                } else {
          
                    if (index < $scope.moviefeeds.feed.length) {

                        itemScope.moviefeed = $scope.moviefeeds.feed[index];
                  
                    } else {

                    }
                }
            },
            calculateItemHeight: function (index) {
                    return 100;
            
            },
            countItems: function () {
                return 1000;
            },
            destroyItemScope: function (index, scope) {
                console.log("Destroyed item #" + index);
            }
        };

```
Regards
__How to reproduce__
[](If possible provide a working example where the issue is reproduced. For this, go to http://tutorial.onsen.io/ , select a framework and a template and modify or replace it. This will use the latest Onsen UI version released. After you finish, click 'Export to Codepen' button, save it and link it here.)

**Comment by frankdiox** [comment]
@alegauss Hi! I think what you want to do here can be achieved with [page's infinite scroll](https://onsen.io/v2/docs/angular1/ons-page.html#attributes). Check out `ng-infinite-scroll` attribute or `onInfiniteScroll` property.
We don't plan to support something like this for lazy-repeat for now since this component was made for a different purpose. I'm closing this for now.
