### ISSUE TITLE
<ons-list-item/> child div generated, and sometimes not?

### ISSUE THREAD

**Issue by luposlip** [OnsenUI/OnsenUI#1414]
__Environment__
Onsen 2 2.0.0.-rc4
Cordova 6.1.1

__Encountered problem__

I render a menu with

```  <ons-splitter>
    <ons-splitter-side>
      <ons-page>
        <ons-list-item>Item 1</ons-splitter-item>
        <ons-list-item>Item 2</ons-splitter-item>
        <ons-list-item>Item 3</ons-splitter-item>
        <ons-list-item>Item 4</ons-splitter-item>
        <ons-list-item>Item 5</ons-splitter-item>
        ...
```

When the UI renders (in browser) sometimes the ons-list-item elements contain a child `<div/>` element, sometimes not.

This makes it really difficult to render the UI correctly, and seem like a bug?

Best,
Henrik

**Comment by luposlip** [comment]
Well, when I hardcode the list, it works fine.
But when I dynamically render/change the list using react, it gets messed up.
In a list of 5 items, the first two had the child `<div/>` - thus rendered incorrectly. The rest was fine.

If I add icons to the items (as `<ons-icon/>` children to the `<ons-list-item/>`) the first 2 list items have the same icons as the two last. But the labels (text elements of the list items) and the on-click events are correct. This is weird.

**Comment by luposlip** [comment]
Bummer, I missed the **`^{:key (:id item)}`** in front of the individual items `[menu-item item]`.
Putting it here for future reference, closing issue.

**Comment by argelius** [comment]
Referenced the wrong issue :)
