### ISSUE TITLE
<ons-pull-hook> doesn't work with <ons-sliding-menu>

### ISSUE THREAD

**Issue by Legolaser** [OnsenUI/OnsenUI#1415]
__Environment__
Onsen 2 RC 4
Angular 1.5.5
Google Chrome v. 50.0.2661.75 (64-bit)

__Encountered problem__
Hello, I ran into an issue when I'm trying to use ons-pull-hook in ons-page which is set as main-page parameter of ons-sliding-menu. I can get working only ons-pull-hook inside ons-page right inside body of index.html. Ons-sliding-menu  main-page="pullTemplate.html" which is ons-page without ons-pull-hook works as well. But It can't be combined. When I do it, It gives theese errors.

`angular.js:13550 
TypeError: Cannot read property 'addEventListener' of undefined
    at http://localhost:8383/CordovaTest/lib/onsen/js/angular-onsenui.js:11936:20
    at Array.forEach (native)
    at Object.deriveEvents (http://localhost:8383/CordovaTest/lib/onsen/js/angular-onsenui.js:11931:22)
    at Class.init (http://localhost:8383/CordovaTest/lib/onsen/js/angular-onsenui.js:2341:44)
    at new Class (http://localhost:8383/CordovaTest/lib/onsen/js/angular-onsenui.js:50:49)
    at pre (http://localhost:8383/CordovaTest/lib/onsen/js/angular-onsenui.js:8868:28)
    at invokeLinkFn (http://localhost:8383/CordovaTest/lib/onsen/js/angular/angular.js:9694:9)
    at nodeLinkFn (http://localhost:8383/CordovaTest/lib/onsen/js/angular/angular.js:9072:11)
    at compositeLinkFn (http://localhost:8383/CordovaTest/lib/onsen/js/angular/angular.js:8397:13)
    at compositeLinkFn (http://localhost:8383/CordovaTest/lib/onsen/js/angular/angular.js:8400:13) (anonymous function) @ angular.js:13550
(anonymous function) @ angular.js:10225
invokeLinkFn @ angular.js:9696
nodeLinkFn @ angular.js:9072
compositeLinkFn @ angular.js:8397
compositeLinkFn @ angular.js:8400
nodeLinkFn @ angular.js:9088
compositeLinkFn @ angular.js:8397
publicLinkFn @ angular.js:8277
_appendMainPage @ slidingMenu.js:450
(anonymous function) @ slidingMenu.js:458
processQueue @ angular.js:15961
(anonymous function) @ angular.js:15977
Scope.$eval @ angular.js:17229
Scope.$digest @ angular.js:17045
Scope.$apply @ angular.js:17337
bootstrapApply @ angular.js:1749
invoke @ angular.js:4665
doBootstrap @ angular.js:1747
bootstrap @ angular.js:1767
angularInit @ angular.js:1652
(anonymous function) @ angular.js:30863
trigger @ angular.js:3166
defaultHandlerWrapper @ angular.js:3456
eventHandler @ angular.js:3444

angular.js:13550
TypeError: Cannot read property 'childNodes' of undefined
    at nodeLinkFn (angular.js:9088)
    at compositeLinkFn (angular.js:8397)
    at compositeLinkFn (angular.js:8400)
    at nodeLinkFn (angular.js:9088)
    at compositeLinkFn (angular.js:8397)
    at publicLinkFn (angular.js:8277)
    at Class._appendMainPage (slidingMenu.js:450)
    at slidingMenu.js:458
    at processQueue (angular.js:15961)
    at angular.js:15977
(anonymous function) @ angular.js:13550
(anonymous function) @ angular.js:10225
processQueue @ angular.js:15969
(anonymous function) @ angular.js:15977
Scope.$eval @ angular.js:17229
Scope.$digest @ angular.js:17045
Scope.$apply @ angular.js:17337
bootstrapApply @ angular.js:1749
invoke @ angular.js:4665
doBootstrap @ angular.js:1747
bootstrap @ angular.js:1767
angularInit @ angular.js:1652
(anonymous function) @ angular.js:30863
trigger @ angular.js:3166
defaultHandlerWrapper @ angular.js:3456
eventHandler @ angular.js:3444`

__How to reproduce__
Just look into the console of this plunker:

[https://plnkr.co/edit/MabXraStn21NLox3FzeV?p=preview](https://plnkr.co/edit/MabXraStn21NLox3FzeV?p=preview)

I tested it with Angular 1.4.10 and 1.4.3 and it gives the same error.

**Comment by argelius** [comment]
Thanks @Legolaser!

We will take a look at this issue.

**Comment by vjoomens** [comment]
Hi, I'm having the same issue with angular 1.5.0 - 1.5.5, Chrome only. Safari works.

**Comment by frankdiox** [comment]
Has anyone tried using `ons-splitter` instead of `ons-sliding-menu`?

**Comment by frankdiox** [comment]
@argelius Looks like this is related to CustomElements implementation. It works perfectly with the polyfill...

With the native implementation I could fix the first error but not the second... `document.registerElement = undefined;` and everything works like a charm... not sure what to do about this :confused:

**Comment by argelius** [comment]
I will take a look at this issue now

**Comment by argelius** [comment]
@Legolaser This has been fixed now. Thanks for the bug report! :+1: 

@frankdiox Looks like we need to do DOM mutations in `attachedCallback` otherwise the timing is incorrect for Angular. But this was only triggered with Sliding menu so I honestly don't know exactly why this happened.

**Comment by Legolaser** [comment]
Thanks @argelius

**Comment by vjoomens** [comment]
Hi, when can we expect rc7 to be released? We're anxiously waiting for this update 😃
