### ISSUE TITLE
<ons-splitter> <ons-toolbar> Long Toolbar-Strings breaching out of Splitter-Area

### ISSUE THREAD

**Issue by ThomasLochbrunner** [OnsenUI/OnsenUI#1419]
__Environment__
Onsen 2 RC 4
Angular 1.5.2
Firefox 46.01
InternetExplorer 11
iOS
(In Chrome the whole Demo is not even working correctly)

__Encountered problem__
If the side-component of an Onsen-Splitter Component contains an Onsen-Toolbar with a String that longer than the width of the side-component, this String will breach out of the side-components "box".

__How to reproduce__

1. Go to codepen :  https://codepen.io/anon/pen/VaNjVZ?editors=101
2. Resize the browser-window until the displayed webapp switches automatically to portrait-mode (splitter-side-comonent is hidden).
3. Now you should see the end of the Toolbar-String that doesn´t fit into the splitter side-component.
    If you mangae to open the splitter-side-component the text also breaches out of the side-comonent.

On Android it´s working fine (String is cut).

**Comment by IliaSky** [comment]
Thank you very much for the bug report. Actually we were sort of informed about these 2 issues. We will fix both of them as soon as possible.

**Comment by IliaSky** [comment]
It looks like the Chrome bug has been fixed 2 days ago and I just fixed the other issue, so both problems should be gone in RC 5.

**Comment by ThomasLochbrunner** [comment]
Thank you, that was fast!
