### ISSUE TITLE
Components2 theme roller css problem

### ISSUE THREAD

**Issue by Maximvdw** [OnsenUI/OnsenUI#1420]
Dear,

Using the example at: https://github.com/frankdiox/OnsenUI-Todo-App
The default compiled CSS files work perfect, however when generated using the components2.onsen.io theme roller the "back button" and left/right alignments seem to have some line-height problems on ios (material is fine).

Normal:
![normal layout](http://i.mvdw-software.com/17-05-2016_00-17-24.png)

Link to custom theme (link coppied today 17/05/2016):
http://components2.onsen.io/onsen-css-components.zip?background-color=%23ededed&text-color=%23333&sub-text-color=%23999&highlight-color=%23eb482f&second-highlight-color=%23f28227&border-color=%23ddd&toolbar-background-color=%23ff722a&toolbar-button-color=%23ffffff&toolbar-text-color=%23ffffff&toolbar-border-color=%23ddd&buttonbar-color=rgba(235%2C+94%2C+47%2C+0.84)&buttonbar-active-text-color=%23fff&list-background-color=%23fff&list-header-background-color=%23eee&list-tap-active-background-color=%23d9d9d9&tabbar-background-color=%23fff&tabbar-text-color=%23ccc&tabbar-highlight-text-color=%23eb5e2f&tabbar-border-color=%23ddd&switch-highlight-color=%23e69e33&modal-background-color=rgba(0%2C+0%2C+0%2C+0.7)&modal-text-color=%23fff&alert-dialog-background-color=rgba(255%2C+255%2C+255%2C+0.92)&alert-dialog-text-color=%231f1f21&alert-dialog-button-color=%23eb482f&alert-dialog-separator-color=%23ddd&dialog-background-color=rgba(255%2C+255%2C+255%2C+0.92)&popover-background-color=white&popover-text-color=%231f1f21&notification-background-color=%23eb5e2f&material-switch-active-thumb-color=%23ff722a&material-switch-inactive-thumb-color=%23f1f1f1&material-switch-active-background-color=%23eb8f5e&material-switch-inactive-background-color=%23b0afaf&material-range-track-color=%23e0e0e0&material-range-thumb-color=%23ff722a&material-toolbar-background-color=%23ff722a&material-toolbar-text-color=%23ffffff&material-toolbar-button-color=%23ffffff&material-button-background-color=%23ff722a&material-button-text-color=%23ffffff&material-checkbox-active-color=%23ff722a&material-checkbox-inactive-color=%23717171&material-checkbox-checkmark-color=%23ffffff&material-radio-button-active-color=%23ff722a&material-radio-button-inactive-color=%23717171&material-text-input-text-color=%23212121&material-text-input-active-color=%23ff722a&material-text-input-inactive-color=%23afafaf&material-dialog-background-color=%23fafafa&material-alert-dialog-background-color=%23fafafa&material-alert-dialog-title-color=%23212121&material-alert-dialog-content-color=%23727272&material-alert-dialog-button-color=%23ff722a&material-progress-bar-primary-color=%23fff129&material-progress-bar-secondary-color=%23c7967b&material-progress-bar-background-color=%23e0e0e0&material-progress-circle-primary-color=%23ff722a&material-progress-circle-secondary-color=%23c29074&fab-text-color=%23fafafa&fab-background-color=%23ff722a

After the layout is applied the **iOS version (flat design)**:
![image after layout is applied](http://i.mvdw-software.com/17-05-2016_00-20-10.png)
As you can see the left and right alignments seem to have the line-height missing, however adding this manually will mess up the material design

It seems that the components2 css compiler seems to be using an older version (may be mentioned somewhere that I missed -> in this case sry for missing it :S) as there are also some other components that seem to be messed up

Let me know if you need some more info,
Maxim Van de Wynckel

**Comment by argelius** [comment]
@Maximvdw The Theme Roller has not been updated for the new version yet. I think we will update it pretty soon.

Sorry for the inconvenience!

**Comment by argelius** [comment]
I will close this for now.

**Comment by ambatiram** [comment]
Hello @Maximvdw, 

is this issue fixed ?? I don't think Theme Roller is updated with new version. I can see this issue till now .
