### ISSUE TITLE
Carousel does not update on orientation change

### ISSUE THREAD

**Issue by vineshhpatel** [OnsenUI/OnsenUI#1423]
__Environment__
Onsen 1.3.14
Angular 1.4.10

__Encountered problem__
I am working with fullscreen OnsenUI carousel. The issue is when I swipe/change carousel item and then change the orientation OR resize the window, it does not look good. This issue is with the official OnsenUI carousel example as well.

__How to reproduce__
You can goto [this](http://codepen.io/onsen/full/xbbzOQ/) pen and swipe/change the carousel item and then resize the window OR change orientation to see the issue.

You may also like to refer [this stackoverflow question](http://stackoverflow.com/q/37342804/842386) to get more details. 

Thanks !!

**Comment by argelius** [comment]
Thank you @vineshhpatel ! I have verified that this happens in v2 as well.

We will take a look it this.

**Comment by IliaSky** [comment]
The fix will be available as soon as Onsen 2 RC 6 is released, so feel free to use that @vineshhpatel.
