### ISSUE TITLE
modifier transparent not working for material toolbar

### ISSUE THREAD

**Issue by Maximvdw** [OnsenUI/OnsenUI#1427]
Dear,

The transparent modifier for ons-toolbar does not seem to be working on material design.
<ons-toolbar modifier="transparent"></ons-toolbar>

This works using RC5 on flat design, however using material it stil shows the toolbar.
![](http://i.mvdw-software.com/23-05-2016_19-26-34.png)

This is using the default provided theme (no custom)

Best Regards,
Maxim

**Comment by frankdiox** [comment]
@Maximvdw Thanks for the report but maybe this is not working on purpose. I think transparent toolbars are not common in Material Design. Anyway, for now you can just overwrite the CSS with `background-color: transparent` and change also the font color to black or something visible (it's white by default) in left/center/right children. If you need to remove the shadow, you have `modifier="noshadow"` available (and working :)).

**Comment by Maximvdw** [comment]
Thanks for the answer @frankdiox that was the approach I was taking atm to bypass this. But shouldn't it be something that could be added by default? Since the goal is to get something 'hybrid', and not something that requires changes per OS (or future modifiers).

^ just my 50 cents ;)

**Comment by Maximvdw** [comment]
Closing it for now
