### ISSUE TITLE
strange behaviour with popPage({refresh:true})

### ISSUE THREAD

**Issue by bdedardel** [OnsenUI/OnsenUI#1429]
__Environment__
Onsen 2 rc5
Angular 

__Encountered problem__
If I push and pop pages without refresh, it's fine.
But if I push and pop pages with refresh, I get NS_ERROR_DOM_BAD_URI: Access to restricted URI denied the second time !

**Comment by Maximvdw** [comment]
I suggest trying RC6, it seems a fix that looks similar to your problem has been made

https://github.com/OnsenUI/OnsenUI/blob/2.0.0-rc.6/CHANGELOG.md

**Comment by frankdiox** [comment]
@bdedardel @Maximvdw Yes, I think that's fixed in rc6. Please try it :)

**Comment by argelius** [comment]
Since it looks like this is fixed I will close this issue :)

**Comment by bdedardel** [comment]
I confirm that it works fine with rc6.
Regards,
Benjamin
