### ISSUE TITLE
Broken page transitions with ons-navigator on ios

### ISSUE THREAD

**Issue by vegetablesalad** [OnsenUI/OnsenUI#1430]
__Environment__
OS X El Capitan 10.11.5
Onsen 2 beta 6
iOS (9.3.1 and 9.3.2 on real iPhone 5) iOS 9.3 on 6s emulator 

__Encountered problem__
Page transition animation is broken, tested on (fade and slide) it will briefly flash the next page and then start the animation. Back animation looks fine, but there is no way to know if it has the same “flash” problem - as it would be unnoticeable. 

__Pen__
But there is no problem running from mobile browser
https://codepen.io/anon/pen/WxeRGL?editors=101

__Forum thread I made__
https://community.onsen.io/topic/453/broken-page-transitions-on-ios/2

__How to reproduce__
With latest version and example from https://onsen.io/v2/docs/js/ons-navigator.html

**Comment by vegetablesalad** [comment]
I noticed the same issue in browser (chrome and safari), but this time it happens only on first animation. If I remove page from stack and open it again, then it will run smoothly.

**Comment by benbvs** [comment]
Same thing. Only the first transition is bad.

**Comment by Chozzle** [comment]
I am having this issue with iOS 9.3.5 on a iPhone 4s

**Comment by milosh012** [comment]
Hi guys.... this is still broken... anyone tried to solve it?

**Comment by milosh012** [comment]
@argelius ^
