### ISSUE TITLE
ons-modal not working with ng-binding on Safari and iOS devices

### ISSUE THREAD

**Issue by dndoanh** [OnsenUI/OnsenUI#1433]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Onsen 2 rc 4
Angular 1.4.8
jQuery 2.2.1
iOS 9.2 Or Safari 9.0.3

__Encountered problem__
When I used ng-include to include a ons-modal then it works fine without any ng-binding, but error occurs when there is any ng-binding such as {{}} or ng-click.
In my case, I must use ng-include, because this ons-modal will be used in many places. If I put all code of ons-modal inside ons-page instead of using ng-include, then everything works fine. 

Please take a look at it.

__How to reproduce__
[](If possible provide a working example where the issue is reproduced. For this, go to http://tutorial.onsen.io/ , select a framework and a template and modify or replace it. This will use the latest Onsen UI version released. After you finish, click 'Export to Codepen' button, save it and link it here.)
Sampl code: http://plnkr.co/edit/VWK6iz9uipfIwEMZjHov?p=preview

**Comment by tfutada** [comment]
i'm hitting the same issue. somehow it works if ons-dialog is used instead of ons-modal...

**Comment by argelius** [comment]
@dndoanh @tfutada Very sorry for the late reply!

Is this bug still present in the latest RC version?

**Comment by argelius** [comment]
@IliaSky When you have time can you take a look at this?

**Comment by psfutada** [comment]
Hi, unfortunately the issue still persists in RC14. AngularJS 1.5.7 expressions embedded in ons-modal fails when running on Safari 9.1.1, while the ones embedded in ons-dialog work right.

**Comment by IliaSky** [comment]
Sorry for the delay - lately we've been busy with the Angular 2 Release, so we didn't have much time. The fix will be available when we release RC16.

**Comment by tfutada** [comment]
No worries. Angular 2 sounds great. Nothing can stop you guys. What's next? Riot.js?
