### ISSUE TITLE
Update AngularJS to latest minor version

### ISSUE THREAD

**Issue by pa-de-solminihac** [OnsenUI/OnsenUI#1437]
__Environment__
Onsen 1.3.15 / Onsen 2 beta 6
Angular 1.4.3

__Encountered problem__
AngularJS version is 1.4.3, should be at least 1.4.11.

__How to reproduce__
Clone the repo or fresh install.

**Comment by pa-de-solminihac** [comment]
The reason behin this request is that there are important bugfixes in recent angularjs versions.

For example, you can't cancel a $resource promise in 1.4.3 but this is fixed in https://github.com/angular/angular.js/commit/4fc734665e5dddef26ed30a9d4f75632cd269481

**Comment by frankdiox** [comment]
@pa-de-solminihac If I'm not mistaken, we don't provide AngularJS in a normal installation with `bower`, `npm` or `jspm`. For example, you can see the files you get for rc.6 [here](https://github.com/OnsenUI/OnsenUI-dist/tree/2.0.0-rc.6).
We have a version of AngularJS in the main repo for our own testing and examples, but you can download and use another version if you want. While it's true that we haven't tested newer versions as much as 1.4.3, we have checked breaking changes even for 1.5.5 and didn't find anything to fix so far. We are actually using 1.5.5 in the [interactive tutorial](http://tutorial.onsen.io/?framework=angular1&category=Getting%20started&module=Introduction) without troubles.

I guess we will update it at some point but this should not affect anyone, so I'm closing this. Thanks for the suggestion anyway!

**Comment by pa-de-solminihac** [comment]
Thanks for you advice, I will update AngularJS separately.

FYI, I just tried a fresh install using bower version `1.7.9`:
```bash
bower cache clean
bower install onsenui
```
I still see references to angular version `1.4.3` in `./bower_components/OnsenUI/js/onsenui_all.js` for example.

**Comment by frankdiox** [comment]
@pa-de-solminihac That's because the version you install is Onsen UI 1.3.14, which is based on AngularJS. 

I was speaking about Onsen UI 2 (sorry if I didn't specify!), what is still a release candidate and you need to specify the version with `bower install onsenui#2.0.0-rc.7` to install it.

**Comment by pa-de-solminihac** [comment]
Of course! Thank you.
