### ISSUE TITLE
Tappable list-item pushPage() action is delayed by ripple effect

### ISSUE THREAD

**Issue by corneyl** [OnsenUI/OnsenUI#1440]
By default, when a list item is tappable, Onsen adds the ripple effect when material design is used. When the list item triggers a `pushPage()` event, the page transition is delayed until the ripple effect is finished. It would be better if the `pushPage()` event is not delayed by the ripple effect, or that it is possible to disable the ripple effect on certain elements.
By the way, this does not count for other functions, e.g. a `console.log()` is not delayed by the ripple.

__Environment__
Onsen 2 RC 9
react 15.1.0
react-onsenui 0.2.21

**Comment by IliaSky** [comment]
Actually it's more likely that it just feels that way. The default animation for Android is `fade-md` which has a `0.2`s delay by default. That delay is not actually connected with the ripple effect. So you can just set the animation options to `{delay: 0}` and it should be fine.

Could you confirm whether you're experiencing the issue if you set the `duration` to 0?

**Comment by argelius** [comment]
@IliaSky Do you know what's the reason for this delay? I'm guessing this delay can make it feel unresponsive

**Comment by IliaSky** [comment]
Well I think fran analysed the native animation and decided to put it at 200ms. We can remove it or make it smaller I guess.

**Comment by argelius** [comment]
Maybe @frankdiox's phone was slow :)

**Comment by corneyl** [comment]
I tried several other applications, including from Google itself, and I get the impression that they do not introduce a delay. The delays that occur are only the result of data loading or render delays.
In my opinion the default delay feels unresponsive, but using `{delay: 0}` solves the problem, thanks!

**Comment by argelius** [comment]
What do you think @frankdiox ? Should we remove the delay?

**Comment by frankdiox** [comment]
@argelius yeah I don't mind removing it. I checked it many times with different combinations and thought that there was a small delay while showing the mask, at least for md-lift. I don't remember adding delay for md-fade, though. Just remove, it's fine :)
