### ISSUE TITLE
Scrollbar on ons-toolbar & hidden ons-speed-dial

### ISSUE THREAD

**Issue by ming-k** [OnsenUI/OnsenUI#1441]
__Environment__
Onsen 2 rc.8
Javascript
Android (material)

__Encountered problem__
1. When I add `ons-back-button` inside `ons-toolbar`, the toolbar's content becomes slightly taller, and as a result, a scrollbar appears at the right side of the toolbar.
2. Unlike `ons-fab`, `ons-speed-dial` does not have a `z-index` CSS property. As a result, if I add both `ons-list` and `ons-speed-dial` to an `ons-page`, the speed dial will be hidden behind the list.

**Comment by argelius** [comment]
Thanks for reporting @ming-k !

We will take a look at these issues

**Comment by IliaSky** [comment]
Well these sounds like 2 separate issues to me, but never mind.

For the first one could you specify what browser does this occur in? The height of the button should be the same as the toolbar (`56px`). Here's a [demo](http://codepen.io/IliaSky/pen/WxvwEw?editors=1000). 

You're correct about the second one. We can fix it easily.

**Comment by ming-k** [comment]
Thanks for the response,
@IliaSky: I'm using firefox ESR 45.1.1. Your codepen demo is using the rc.4 CSS, I tried to change it to rc.8, and the scrollbar appears.

**Comment by argelius** [comment]
@IliaSky @ming-k 

I also noticed the scrollable toolbar in Firefox when there is a back button.

**Comment by IliaSky** [comment]
It seems that the combination of `overflow-y: visible` and `overflow-x: hidden` wasn't working properly. And in firefox there seemed to be an issue where the `line-height` property was making some issues. However if it's fixed the backbutton is shifted by a couple of pixels up, and making more patches would be pretty ugly. So the final and simplest solution was just to make the overflow hidden by default.
