### ISSUE TITLE
`page.data` is `undefined` during `init` event

### ISSUE THREAD

**Issue by DidiYordanov** [OnsenUI/OnsenUI#1449]
__Environment__
Visual Studio 2015
Onsen UI v2 RC.9
Javascript
Android 4.4.4 and Windows 10 phone

__Encountered problem__
When running the [ons-navigator template](https://github.com/OnsenUI/project-templates/tree/master/templates/navigation) in certain devices there is a strange bug.

When I click an item for the first time it works fine, however if I go back and click another one it get errors with `page.data` is `undefined` in the `init` event handler.
On Android 4.4.4 the application continues to work regardless of the missing data.
On Windows 10 phone this error actually crashes and closes the whole app.
 

__How to reproduce__
Run the navigator template in either OS.

**Comment by frankdiox** [comment]
@DidiYordanov Can you check if this works with #1451 ? It works now in Edge so it should also work in Windows 10 and probably the other browsers.
