### ISSUE TITLE
Popover arrow misplaced using Windows 10 and Edge 13

### ISSUE THREAD

**Issue by gjkr** [OnsenUI/OnsenUI#1450]
__Environment__
Onsen 2 rc.9
Windows 10
Browser Edge 13.10586 
(Free virtualbox from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/windows/)

__Encountered problem__
Popover arrow misplaced - see image:
![popover](https://cloud.githubusercontent.com/assets/19851689/15955794/66b31f12-2ee4-11e6-847b-e5ebbcd43b3a.png)

__How to reproduce__
- Open: https://onsen.io/tutorial/index.html?framework=vanilla&category=Reference&module=popover
   (Note that button is not visble at all)
- Download Tutorial (Generate Cordova project)
- Open www/index.html in Edge browser. Button is now visible but arrow is misplaced after clicking the button.

**Comment by argelius** [comment]
@gjkr Thank you for the bug report! We will take a look at this.
