### ISSUE TITLE
Ons-Navigator throws exception when resetting page using lift animation

### ISSUE THREAD

**Issue by SharkChips** [OnsenUI/OnsenUI#1453]
_EDIT_: This only occurs when using the "lift" animation. No other animations are affected by this bug.

__Environment__
Anything after Onsen 2.0.0-beta.8
Any browser (tested chrome 51)

__Encountered problem__
When using `navigator.resetToPage()` while specifying the lift animation (both iOS and md are affected), the following error is thrown:

`Uncaught TypeError: _this9.pages[0]._destroy is not a function`

__How to reproduce__
1. Use any version of Onsen UI after beta.8 (so basically beta.9 onwards)
2. Make any app with navigator and several pages
3. Use `navi.resetToPage("somePageName", {animation: "lift"});` <--Must be lift animation
4. Notice that the following error is thrown: `Uncaught TypeError: _this9.pages[0]._destroy is not a function`

[](If possible provide a working example where the issue is reproduced. For this, go to http://tutorial.onsen.io/ , select a framework and a template and modify or replace it. This will use the latest Onsen UI version released. After you finish, click 'Export to Codepen' button, save it and link it here.)

**Comment by frankdiox** [comment]
@SharkChips Thanks for the detailed report. I was able to reproduce it in the interactive tutorial. We'll check it!
