### ISSUE TITLE
"ios-slide" animation is slightly broken.

### ISSUE THREAD

**Issue by anatoo** [OnsenUI/OnsenUI#1457]
"ios-slide" animation is slightly broken. It animated incorrectly in toolbar.

__Environment__
master branch
Google Chrome

__How to reproduce__
Access "examples/navigator/index.html" and click 'Push Page 2' button and click "Pop Page" button.

__Expected Behavior__
[v1.x slide animation](https://onsen.io/v1/reference/ons-navigator.html#example)

**Comment by argelius** [comment]
Thank you @anatoo ! I can take a look at this.
