### ISSUE TITLE
A Switch component inside a Splitter component makes drag events overlap each other.

### ISSUE THREAD

**Issue by airamrguez** [OnsenUI/OnsenUI#1464]
__Environment__
Onsen 2 beta 6
Javascript
Every platform

__Encountered problem__

A Switch component inside a Splitter component makes drag events overlap each other animating both at the same time.

__How to reproduce__
[Codepen example](https://codepen.io/anon/pen/VjKwdB)

**Comment by argelius** [comment]
Thank you @airamrguez !

We will take a look. Probably we need to stop propagation at the switch.
