### ISSUE TITLE
Onsen UI Templates for Visual Studio 2015 - Onsen UI Splitter Bug

### ISSUE THREAD

**Issue by jonathandotchin** [OnsenUI/OnsenUI#1467]
**Environment**
Onsen UI Templates for Visual Studio 2.0.0
Onsen 2.0.0-rc.8 Initially (comes with template)
Onsen 2.0.0-rc.11 Afterward (updated manually)
Windows Phone 8.1, Windows Phone 10, Windows 10

**Encountered problem**
The toggle menu button and the hamburger menu button does not work on in the Onsen UI Splitter template.

**How to reproduce**
In Visual Studio 2015 Community Edition with Tools for Apache Cordova installed
1. Install Onsen UI Templates for Visual Studio (https://visualstudiogallery.msdn.microsoft.com/8968a18d-cc94-4ebf-8183-ed0e1f6247f3)
2. Create application using the  Onsen UI Splitter template
3. Build and run the application in any windows emulator and local machine
4. Notice that swipe left to right display menu
5. Notice that hamburger and toggle menu button does nothing
6. Build and run the application in any android emulator
7. Notice that hamburger and toggle menu button works correctly

**Comment by masahirotanaka** [comment]
Thanks for the report @jonathandotchin. We'll take a look.

**Comment by masahirotanaka** [comment]
@frankdiox @argelius Looks like this is a issue with Windows Phone (Edge?) environment. If it can be fixed rather quickly that's appreciated.

**Comment by frankdiox** [comment]
@masahirotanaka This works on Microsoft Edge. You can open [this tutorial](http://tutorial.onsen.io/?framework=vanilla&category=Reference&module=splitter) with Edge. I guess the window emulator has something different?

**Comment by DidiYordanov** [comment]
@jonathandotchin Please take a look [here](https://taco.visualstudio.com/en-us/docs/tutorial-onsen/#troubleshooting-lets-fix-it) and the documentation about [Get your app running on Windows](https://taco.visualstudio.com/en-us/docs/tutorial-onsen/#get-your-app-running-on-windows). I tested the Onsen UI Splitter template on Windows-x64 Local Machine, Windows 10 Phone and it works.

**Comment by jonathandotchin** [comment]
@frankdiox I will try tonight to open the tutorial directly in the emulator and on the hardware to see. Back with some news soon.

@DidiYordanov That was the tutorial that I was using when I tested on emulator and hardware. The only thing I didn't try is the content security policy since the page load and the swipe works. Only the hamburger and the button didn't. I'll test it again tonight.

**Comment by frankdiox** [comment]
@jonathandotchin We tested it yesterday again and we could reproduce your exact problems only when choosing `windows 8.1` as target version. With `Windows 10.0` it worked without troubles :/
