### ISSUE TITLE
ng-click event unresponsive with PhoneGap built mobile apps

### ISSUE THREAD

**Issue by trazek** [OnsenUI/OnsenUI#147]
I understand FastClick.js is built into Onsen UI to mitigate the delay, but I went through a full build and install onto my mobile device and still experienced unresponsive button clicks. Swiping and tapping the left menu items were all fine, it's just the buttons. 

Is this simply a compromise to deal with when developing hybrid apps or is there a solution I am missing?

**Comment by OmarHassan25** [comment]
I have the same issue on some android devices

**Comment by willbittner** [comment]
Just FYI - I have hit lots of bugs that exist only in PhoneGap builds and not local cordova builds . Can you verify that this bug exists with a local cordova build as well?
