### ISSUE TITLE
[Question] Automatic inversion of elements for Arabic layouts

### ISSUE THREAD

**Issue by rogervila** [OnsenUI/OnsenUI#1474]
Hello, I would like to know if there is an automated way to reverse the onsen components like a mirror. 

I need to do this for the Arabic layout of an App, where everything must go from right to left.

Thank you.

**Comment by munsterlander** [comment]
Do you need the icons and such to be on the other side of the device as well or just the strings to be reversed?

**Comment by rogervila** [comment]
I have reversed all the static components with jQuery, but I have to change also the ons-sliding-menu side attribute from right to left.

I have been looking on the docs, but [there is no method to do it](https://onsen.io/v1/reference/ons-sliding-menu.html#methods-summary).

The language change is dynamic, so reloading is not an option.

**Comment by frankdiox** [comment]
@rogervila If you use `ons-splitter` you can set `side="right"`. Few stuff like `ons-back-button` cannot be reverted right now, but probably it's not hard to make it manually.

**Comment by rogervila** [comment]
@frankdiox  I will try it. 

I was thinking on removing the entire menu and compiling it as a new one.

I will give feedback of the result.

**Comment by rogervila** [comment]
I can't use ons-splitter because we are using v1.

I have not achieved a smooth and clean way to change the `side` attribute of a ons-sliding-menu component without messing up the animation.

Is it possible to add this feature for ons-sliding-menu on the v1?

**Comment by frankdiox** [comment]
It's still the same, `side="right"` if I don't remember wrong. It should be in the docs. 
You have a migration guide [here](https://onsen.io/v2/docs/guide/angular1/from-v1-to-v2.html) if you want to start using Onsen UI 2.
