### ISSUE TITLE
typescript: error TS2656: Exported external package typings file '.../node_modules/onsenui/js/onsenui.d.ts' is not a module

### ISSUE THREAD

**Issue by untsamphan** [OnsenUI/OnsenUI#1475]
For a few days, I've tested successfully Onsen 2rc with TypeScript using a hand-made type definition file. Then today I saw this error from tsc.

`error TS2656: Exported external package typings file '.../node_modules/onsenui/js/onsenui.d.ts' is not a module. Please contact the package author to update the package definition.`

tsc seems to find an incorrect type definition file in node_modules.

__Environment__
Onsen 2.0.0-rc.13
tsc 1.8.10
Meteor 1.3.3.1

__How to reproduce__
* npm install onsenui
* put this in a .tsx
`import * as ons from 'onsenui';`
* then compile with tsc

**Comment by frankdiox** [comment]
@untsamphan We recently included `onsenui.d.ts` in the release but looks like it has some issues. I guess if you remove the `typings` entry from `package.json` it will work as before.
If you want to check the new typings we'd appreciate your feedback :)

**Comment by untsamphan** [comment]
The onsenui.d.ts in npm release works now. Thanks.

Looking forward to see typedef for react-onsenui too.
