### ISSUE TITLE
feature request : material design datetime picker ?

### ISSUE THREAD

**Issue by joeblew99** [OnsenUI/OnsenUI#1479]
i cant see a datetime picker in the components at all....

**Comment by argelius** [comment]
Thanks @joeblew99 !

We also want to add a date picker, both for iOS and Material Design. We will need to discuss it but it's definitely something that can be added for the next version together with some other components.

**Comment by munsterlander** [comment]
Curious, the new HTML5 standard has `input type="date"` which resolves to native date picker in iOS and Android.  Is the requirement a different date picker than what is already available and supported by `ons-input`?  I tested both on Android and both work.

**Comment by argelius** [comment]
@munsterlander Yes, that's what I usually do but depending on the version of Android it will look different and there is no way to style it.

**Comment by badbod99** [comment]
There isn't really a good javascript datepicker that works nicely with OnsenUI.  Most come with front end frameworks like Bootstrap and Angular Material, which are alternatives to OnsenUI.  Due to those, most standalone ones are no longer in development or supported.

**Comment by frankdiox** [comment]
@badbod99 Can Crosswalk + native datepicker be an option for you?

**Comment by badbod99** [comment]
@frankdiox - Doesn't really help for browser based experience.  Mobile device isn't really and issue as it pulls up the native device date picker.  Issue in on in-browser experience.  Native datepicker on Chrome and others is pretty poor and not all browsers support it.
