### ISSUE TITLE
Cant load in angular 2 

### ISSUE THREAD

**Issue by gotenxds** [OnsenUI/OnsenUI#1480]
Hello, when I try to load the OnS_DIRECTIVES and use it in my app I get this runtime error:
![image](https://cloud.githubusercontent.com/assets/3519520/16319645/b27f2806-399c-11e6-9006-8fad1bbb5343.png)

my file is as follows:
`import {Component} from '@angular/core';
import {ROUTER_DIRECTIVES} from '@angular/router';
import {HTTP_PROVIDERS} from '@angular/http';
import {MapComponent} from '../map/map.component';
import {ToolbarComponent} from './toolbar.component';
import {ONS_DIRECTIVES} from 'angular2-onsenui';

@Component({
  selector: 'wit-app',
  templateUrl: 'app/components/app.component.html',
  directives: [ROUTER_DIRECTIVES, MapComponent, ToolbarComponent, ONS_DIRECTIVES],
  providers: [HTTP_PROVIDERS]
})
export class AppComponent {
}
`

I've done a bit of digging and it seems that this is an error with RC1 and RC 2 of angular :
https://github.com/angular/angular/issues/8519

Any way of fixing this?

**Comment by IliaSky** [comment]
I guess a lot of people in the angular community have been running into this issue recently. Unfortunately I haven't been able to reproduce it. 

Looking at the issues and commits of the angular repo it seems that they may have fixed it in RC3, which was released 3 days ago, can you confirm whether it still persists when using that?

**Comment by gotenxds** [comment]
Thanks for the answer, I'l try and upgrade today and update here when done.
