### ISSUE TITLE
cant rotate screen with cordova device orientation plugin

### ISSUE THREAD

**Issue by spiritbrother** [OnsenUI/OnsenUI#1481]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Onsen 2 beta 6
Angular 1.5.2
iOS 9.2

__Encountered problem__

__How to reproduce__
[](If possible provide a working example where the issue is reproduced. For this, go to http://tutorial.onsen.io/ , select a framework and a template and modify or replace it. This will use the latest Onsen UI version released. After you finish, click 'Export to Codepen' button, save it and link it here.)
how to rotate screen by using cordova device orientation?the app log said that screen object has no method lockOrientation

**Comment by IliaSky** [comment]
As you may have noticed in the start of the issue template - questions should be asked in either [stackoverflow.com/tags/onsen-ui](https://stackoverflow.com/tags/onsen-ui) or [community.onsen.io](https://community.onsen.io).

Also the problem specified does not seem to be related to onsen ui, as it does not interact with the mentioned plugin.

That being said I can think of several potential reasons for the error which you're describing:
- if cordova/phonegap was not loaded properly
- if cordova-device-orientation-plugin was not loaded properly
- if you're executing the code in an emulator which does not support the `lockOrientation` method
- or most likely if you're not waiting for the `deviceready` event when executing your code.

For the last one you could do either of:
```
document.addEventListener('deviceready', function(){
  // lock screen here
});

ons.ready(function(){
  // lock screen here
});
```

Anyway I am closing this issue as it doesn't seem to be a bug related to Onsen UI.
