### ISSUE TITLE
<ons-speed-dial> not accessible via 'var' attribute

### ISSUE THREAD

**Issue by ruaanvds** [OnsenUI/OnsenUI#1485]
__Environment__
Onsen 2 (v2.0.0-rc.14)
Angular 1.5.0
All platforms

__Encountered problem__
I'm trying to access the `<ons-speed-dial>` element via the `var` attribute, but no matter what I'm doing, I can't seem to reference the element. For reference, I'm trying to invoke `hideItems()` on the element itself. 

All other elements seem to be working, so it appears to be isolated to speed dials. 

__How to reproduce__
Please see this [jsFiddle](https://codepen.io/ruaanvds/pen/pbRXGm?editors=101). 

Is there something I'm missing?

**Comment by argelius** [comment]
Thank you @ruaanvds ! Looks like the var attribute has not been implemented for `<ons-speed-dial>`.

We will fix it!

**Comment by frankdiox** [comment]
@argelius We actually don't have bindings for `ons-speed-dial`. I guess we should add them now that it has `open` and `close` events.

**Comment by ruaanvds** [comment]
@frankdiox @argelius Is there any other way to target `ons-speed-dial` to invoke its methods in the meantime?

**Comment by argelius** [comment]
@ruaanvds You can run the methods directly on the DOM element.

**Comment by ruaanvds** [comment]
@argelius Excellent. 

I'm currently using the following pattern, with success:

`$("[var='dialchannellist']").get(0).hideItems()`

Think this is a pretty viable workaround in the meantime. Thanks!

**Comment by argelius** [comment]
@ruaanvds Great that you were able to solve it! :)

We will support the `var` attribute from the next version.

**Comment by ruaanvds** [comment]
Thanks for the quick turnaround, @argelius. Looking forward to the next release.
