### ISSUE TITLE
Exposing modifier functions

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#1486]
@OnsenUI/members @OnsenUI/owners

Adding and removing modifiers from elements can be a bit tricky right now.

We already have functions for this internally so I propose that we expose them to the users. I want your opinions on how to export them.

Here are some options:

**1)** Export the methods directly

```
import {addModifier, removeModifier, hasModifier} from 'onsenui';
```

**2)** Attach them to an object and export that

```
import {modifier} from 'onsenui';

const el = document.createElement('ons-list-item');

modifier.add(el, 'chevron');
modifier.remove(el, 'chevron');
```

**3)** Export the `util` object

```
import {util} from 'onsenui';

const el = document.createElement('ons-list-item');

util.addModifier(el, 'chevron');
```

Which of these do you prefer?

**Comment by frankdiox** [comment]
I think I slightly prefer **3** since `util` would also contain `createElement` and maybe other methods.
Maybe **2** is also fine if we can do `import { createElement, modfierList } from 'onsenui';` and we don't export other methods.

**Comment by argelius** [comment]
@frankdiox I prefer 2 over 3 since exporting the whole `util` object would export a bunch of functions that are very specific and not useful to the user. I think option 2 is generally cleaner and also consistent with things like `ons.platform` and `ons.notification`.

**Comment by anatoo** [comment]
👍 
I like **2** and dislike **3**.

**Comment by argelius** [comment]
Let's go with **option 2**!

Does anyone have any idea about what we should call the object? Is `ons.modifier` OK?

I think these method names are good for adding and removing modifiers:
```
ons.modifier.add(el, modifier)
ons.modifier.remove(el, modifier);
```

I can't really think of a good name to check for existance.

Maybe like this:

```
ons.modifier.exists(el, modifier);
```

**Comment by frankdiox** [comment]
@argelius What about `contains`? Like `classList`.
