### ISSUE TITLE
Popover incorrectly positioned when target is inside dialog.

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#1488]
Probably due to the positioning of the dialog the popover doesn't calculate its own position correctly.

This issue was originally reported in the [react-onsenui repo](https://github.com/OnsenUI/react-onsenui/issues/56).

**Comment by IliaSky** [comment]
Hmm I seem to be unable to reproduce the issue. It seems to be working fine. Maybe there is some specific case/browser in which the issue appears? [Working Demo](https://codepen.io/IliaSky/pen/QEvOva?editors=101)

**Comment by argelius** [comment]
@IliaSky I asked in the other issue for some more information.

**Comment by argelius** [comment]
I will close this since we are unable to reproduce it.
