### ISSUE TITLE
Checkbox inside list items sometimes does not change on tap

### ISSUE THREAD

**Issue by rogervila** [OnsenUI/OnsenUI#1495]
__Environment__
Onsen 1.3.14
Angular 1.4.3
iOS 9.2
iPhone 5, 5s and 6
Safari, Firefox & Chrome

__Encountered problem__
Checkbox inside list items sometimes does not change on tap. On Android it works perfectly

__How to reproduce__
Create a Checkbox in List Item component from [Onsen Components](http://components.onsen.io/). 

If you click on the list item, but not in the checkbox circle, sometimes its status does not change.

**Comment by munsterlander** [comment]
It would be nice if they auto bound, but I think this is actually by design.  List items could contain all sorts of items and it would be hard to know what everyone is adding.  I usually just add a click event listener on the list-item and then have it modify the state of my component.

**Comment by frankdiox** [comment]
@rogervila I don't think there is any feature like that in v1.3.14. Those are just CSS components (without any logic) so looks like Chrome assumes you want to click them but Safari does not assume the same. If you want to trigger the checkbox always you need to add an event listener as @munsterlander says.
In v2, however, we do have [a way to do this easier](http://tutorial.onsen.io/?framework=vanilla&category=Reference&module=input). If you are interested in migrating to v2, we have a [guide for you](https://onsen.io/v2/docs/guide/angular1/from-v1-to-v2.html).
