### ISSUE TITLE
Unable to change platform with ons.platform.select

### ISSUE THREAD

**Issue by cyclops24** [OnsenUI/OnsenUI#1497]
Hi guys,
I start using OnsenUI 2 and your awesome package in Meteor 1.3.2.4 but I have small issue with them. I create a small demo app in github to fix issues for demo. Later when this fix completely you can refer to it as a complete example of OnsenUI+Meteor for meteor users.

This is my repo URL:
https://github.com/MeteorDemoApps/OnsenUI2JS-demo

And this is a line that not working and not switch to Android view:
https://github.com/MeteorDemoApps/OnsenUI2JS-demo/blob/master/client/main.js#L23

**Comment by masahirotanaka** [comment]
Hi! Thanks for trying to use Onsen UI with Meteor.
If that's not too complex, we might be able to solve the issue. Please stay tuned!

**Comment by cyclops24** [comment]
Hi @masahirotanaka,
Thanks for your quick answer. I create demo for reproduce this issue as simple as possible. It's a small bare project.
When I click on "Android View" button it return below output to me in firebug but it's not change platform view also it's not return any error.
![onsenui](https://cloud.githubusercontent.com/assets/8266479/16610427/66b2a82a-4370-11e6-91d5-325697a2dcba.png)

**Comment by frankdiox** [comment]
@cyclops24 Hey! Thanks for trying out Onsen UI. Some quick thoughts here:

`ons.platform.select` only works at the beginning of the app. Obviously we don't expect to change platform during the app execution :sweat_smile: 
Therefore, you should call `ons.platform.select` right after importing `onsenui`, not on button click event.
If what you want to do is some kind of OnsenUI+Meteor showcase application ([like this](https://frankdiox.github.io/frame-auto-style/example.html)), then you can use another function called `ons.forcePlatformStyling('android')`. This is not documented as is intended for internal usage and can be changed at any moment. This also needs `ons.platform.select` to be called at the very beginning with any value.

**Comment by cyclops24** [comment]
Thanks @frankdiox, 
I moved `ons.platform.select` after import `onsenui` and It's fixed now.
