### ISSUE TITLE
iOS: status-bar-fill between ons-navigation and ons-tabbar

### ISSUE THREAD

**Issue by alegauss** [OnsenUI/OnsenUI#1501]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Onsen 2 beta 15
Angular 1.5.2
iOS 9.2

__Encountered problem__
When use ons-navigation with ons-tabbar (modifier="material top") on iOS, it add status-bar-fill between these 2 components.

__How to reproduce__
[](If possible provide a working example where the issue is reproduced. For this, go to http://tutorial.onsen.io/ , select a framework and a template and modify or replace it. This will use the latest Onsen UI version released. After you finish, click 'Export to Codepen' button, save it and link it here.)
![screen shot 2016-07-08 at 00 00 26](https://cloud.githubusercontent.com/assets/331174/16676449/99dbe758-44a0-11e6-8f1c-b795564a8b8e.png)

**Comment by IliaSky** [comment]
Thanks for the bug report. The issue has been fixed. We will probably release RC.16 soon so feel free to use that. :)
