### ISSUE TITLE
material text input labels don't use custom theme color

### ISSUE THREAD

**Issue by copleykj** [OnsenUI/OnsenUI#1505]
__Environment__
Onsen 2 RC15
React 15
Android 6

__Encountered problem__
First the custom color for the text input label is improperly compiled by the theme roller.. I chose a dark theme with a light gray label color and it compiled to a blue that I had selected for something else, however instead of actually using the blue, the element's color style is set to rgba(0, 0, 0, 0.498039); when it is rendered.

**Comment by copleykj** [comment]
This seems to be the source of the label's style being set: https://github.com/OnsenUI/OnsenUI/blob/master/core/src/elements/ons-input.js#L263

**Comment by argelius** [comment]
Thanks @copleykj ! I will take a look at this
