### ISSUE TITLE
Ons-tabbar different controllers on each tab

### ISSUE THREAD

**Issue by Drozdin** [OnsenUI/OnsenUI#1506]
Hello, i've encountered a problem with ons-tabbar after migration to Onsen v2.
I have different controller on each ons-tab page which are separately HTML files and when the page with <ons-tabbar> loads , all the controllers from each ons-tab page load. In Onsen v1.x everything worked fine. Controllers loaded only after click on ons-tab. It is possible to achieve the same behaviour on Onsen v2?

**Comment by frankdiox** [comment]
@Drozdin Hello! Tabs where lazy in Onsen 1, what means that they were initialized only when you clicked on them the first time. This could cause delay the first time you see those pages. In Onsen 2 all the tabs are persistent and are loaded at the beginning. This behavior now triggers all your angular controllers at the start. There is no possible lazy load for tabs anymore.

However, you possibly can move part of your code to tabbar's [`postchange` event](https://onsen.io/v2/docs/angular1/ons-tabbar.html#events-summary) or page's [`show` event](https://onsen.io/v2/docs/angular1/ons-page.html#events-summary) (in angular you can use `ons-postchange` and `ons-show` attribute handlers).

Feel free to open this again if you have further doubts.
