### ISSUE TITLE
Onsen2 - Bad transition within page changes

### ISSUE THREAD

**Issue by dnish** [OnsenUI/OnsenUI#1510]
__Environment__
Onsen 2 rc 15
React
iOS 9.3
Safari (development)

__Encountered problem__
We change the page via:

       this.props.navigator.pushPage({
            component: Chat
        });

If the page change happens, we can see the whole new page for a few milliseconds - after that, the transition animation starts. I think it would be better if the new page get's visible while the animation plays and not before.

**Comment by argelius** [comment]
@dnish: I was unable to reproduce this issue. Can you provide some simple code that we can try?

I've tried on iOS 9.3 both as a Cordova app and in Mobile Safari.

**Comment by MyG494** [comment]
For me occurs the same problem on iOS 9.3, iPhone 5 with Cordova and Angular 1. The following example produces the problem when using the Monaca Navigation template and putting the www into a fresh Cordova project. 
On the index I modified only the loader.js import and the content to make the second page a bit more slowly.
[index.html.zip](https://github.com/OnsenUI/OnsenUI/files/376351/index.html.zip)

**Comment by frankdiox** [comment]
@MyG494 What's the Onsen UI version in the template you are using? This should be fixed in the last versions at least for Angular1. Not sure about React, though.

**Comment by MyG494** [comment]
Thank you, using the rc15 fixed it for me!

**Comment by argelius** [comment]
Great @MyG494 !

I will close this issue for now.
