### ISSUE TITLE
Ons-Navigator corrupts page stack when back button pressed

### ISSUE THREAD

**Issue by SharkChips** [OnsenUI/OnsenUI#1512]
__Environment__
Onsen UI 2.0.0 RC-15
Any Environment (tested android, iOS 9, Chrome 50)

__Encountered problem__
Immediately after firing a `backbutton` event, the page stack of `ons-navigator` (normally full of `ons-page`) is temporarily corrupted by a `div` element (WTF?).

__How to reproduce__

1. Make a `ons-navigator`
2. Push some pages onto the stack
3. Call `document.dispatchEvent(new Event("backbutton")); navi.pages;` in the chrome dev tools terminal

__Expected result__
In the past, the call to `navi.pages` would return the ons-page that the navigator was *going to*. So if there were two pages in the stack, firing the `backbutton` on page two would return page *one*.

__What happened instead?__
`navi.pages` returns the page it's currently on, a div, and the rest of the stack. The content of the div is:

`<div style="position: absolute; width: 100%; height: 100%; z-index: 2; opacity: 0; transform: translate3d(0px, 0px, 0px); transition: all 0.35s cubic-bezier(0.1, 0.7, 0.4, 1); background-color: black;"></div>`

Thanks for all your hard work!
SharkChips

**Comment by argelius** [comment]
@SharkChips Thanks for reporting!

The div that you are seeing is the semitransparent mask that is faded in while the animation is running. It only exists during the animation and is removed after.

Looks like we need to filter the `pages` property to only include `<ons-page>` elements. We will fix this.
