### ISSUE TITLE
`show` fires before `init` on 1st page

### ISSUE THREAD

**Issue by bladeSk** [OnsenUI/OnsenUI#1513]
__Environment__
2.0.0-rc.15
plain js
Browser

__Encountered problem__
`show` event is fired before the `init` event, but only on the first page. All the other pushed pages fire `init` and then `show` as expected. I'm not sure if this is the intented behavior, but it's not consistent for sure.

__How to reproduce__
https://codepen.io/anon/pen/WxraNp - check the console

**Comment by frankdiox** [comment]
@bladeSk Thanks for the report. Looks like this bug was introduced in rc.5. The problem is not about the initial page, it actually happens when there is no animation. We'll fix this :)
