### ISSUE TITLE
iOS/Safari slide animation doesn't work when using babel-polyfill

### ISSUE THREAD

**Issue by aminch** [OnsenUI/OnsenUI#1519]
**Environment**
Onsen 2 rc 15
Onsen React 0.6.2
iOS 9.3 or Safari 9.1.2

**Encountered problem**
I'm using generator functions in my project so I added babel-polyfill, after that transition animations stopped working. The animation when pushing pages in the navigator doesn't work in iOS or Safari, and you cannot pop pages. 

The animations do work in Chrome, or if your force the platform to be android with ons.platform.select("android") they will work in Safari, but then only for the Material style.

**How to reproduce**
I created a Codepen to demonstrate the issue: https://codepen.io/minch/pen/vKjdaY

You need to run it in Safari to see the issue.

To have the animation work correctly again simply remove the reference the babel polyfill js file.

**Comment by aminch** [comment]
Hi, I'd like to know if any more information is needed to look into this issue, Thanks.

**Comment by argelius** [comment]
Thanks for reporting @aminch ! That is very strange. Maybe the babel polyfill overrides something.

We will take a look at this.

**Comment by macchiitaka** [comment]
Please see `onsenui/js/onsenui.js`, around line 18,049.
This error occurs in the case of `typeof this._contentElement === 'undefined'`.
```
value: function _canAnimateToolbar() {
if (util.findChild(this, 'ons-toolbar')) {
  return true;
}
return !!util.findChild(this._contentElement, function (el) {
  return util.match(el, 'ons-toolbar') && !el.hasAttribute('inline');
});
}
```
