### ISSUE TITLE
TypeScript definitions are incorrect

### ISSUE THREAD

**Issue by danielearwicker** [OnsenUI/OnsenUI#1520]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Onsen 2 rc 15
TypeScript 2.1-dev

__Encountered problem__
I am trying to use onsenui 2.0 RC 15 with TypeScript. When importing the onsenui module from a TS file, if it compiles successfully then it fails at runtime because the structure of the module is not correctly described by the declarations.

__How to reproduce__
In your package.json you correctly refer to:

    "typings": "js/onsenui.d.ts",

And in that file you have:

    export declare var ons: onsStatic;

So that means that TS will believe that the module exports a variable called `ons`.

This means that in my code I can say:

    import { ons } from "onsenui";

However at runtime it exceptions in the browser. The `onsenui` commonjs module doesn't export anything called `ons`. It exports things like `notification` at the top level. So the `.d.ts` is incorrect.

Instead of declaring an interface `onsStatic`, all its members should be exported at the top level, like this:

    export declare function isReady(): boolean;

or for variables:

    export declare var notification: onsNotification;

Also this declaration is wrong:

    bringPageTop({item: String,item: Number}, options?: Object): Promise<HTMLElement>;

From the docs I think it should be:

    bringPageTop(item: string|number, options?: Object): Promise<HTMLElement>;

i.e. `item` can be either `string` or `number`.

**Comment by danielearwicker** [comment]
Looks like you've prepared `onsenui.d.ts` for use by anyone who is **NOT** using module system (browserify/webpack etc), so for those users there is a global `ons` object.

Whereas for users of a module system, the module itself is equivalent to the `ons` object.

So currently your `.d.ts` file is not compatible with the `typings` property in `package.json`.

See [immutablejs](https://github.com/facebook/immutable-js/tree/master/dist) project - they have two versions of the `d.ts` file, and the `immutable-nonambient.d.ts` version is the one used by typings` in `package.json`. This is done by a bit of scripting in their build process to fix it up.

**Comment by argelius** [comment]
Thank you @danielearwicker !

We will definitely fix this. The file was originally made to get source code completion in editors but we will update it to support module systems as well.

Personally I don't have much experience with Typescript but I will take this opportunity to learn :)
