### ISSUE TITLE
Tabbar broken in React

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#1528]
@anatoo I think https://github.com/OnsenUI/OnsenUI/pull/1492 broke the tabbar in React.

It's trying to use the `pageLoader` but that is not necessary in React since the pages are already rendered by React. Do you have any idea what changed? I tried to debug the code but there are a lot of changes in both `<ons-tabbar>` and `<ons-tab>` and I couldn't find what change is causing the problem.

In React the pages are rendered and put into the `.tab-bar__content` element so there is no need to load pages.

**Comment by anatoo** [comment]
@argelius What about setting a page loader that do nothing?

```
onsTab.pageLoader = new ons.PageLoader(({page, parent}, done) => {
  done({element: document.createElement('div'), unload: () => {}});
});
```

**Comment by argelius** [comment]
@anatoo Good idea! I will try this

**Comment by argelius** [comment]
Actually this is still causing an error:

```
VM3262:23001 Uncaught Error: Invalid state: page element must be a "ons-page" element.
```

**Comment by anatoo** [comment]
hmm...

Do you set "page" attribute on ons-tab? 
I think you should not page attribute or property because it cause page-loader's load.
