### ISSUE TITLE
problem with ons-navigator and ons-splitter works together

### ISSUE THREAD

**Issue by meisam3322** [OnsenUI/OnsenUI#1530]
i want use navigator animation for my app and also want to have global splitter in it. i set navigator to **tempHome** template and also splitter content page attribute to **tempHome** template. 

so i have 2 **tempHome** template in my app first page. is there any idea to solve it?
thank you all

**Comment by frankdiox** [comment]
Have you checked the [tutorial for this](http://tutorial.onsen.io/?framework=vanilla&category=Community%20tutorials&module=splitter_navigator)?
