### ISSUE TITLE
Onsen2 - ons-back-button needs sane default when "ons-navigator's page stack is empty"

### ISSUE THREAD

**Issue by erikcw** [OnsenUI/OnsenUI#1533]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

**Environment**
Onsen 2 RC (git master)
Angular 1.5.7
Chrome/OSX

**Encountered problem**

If I re-open my app into a "deep" screen, then click the `ons-back-button` -- I get the following stacktrace

```
index.js:401 
Uncaught (in promise) ons-navigator's page stack is empty._popPage @ index.js:401
popPage @ index.js:365_onClick @ ons-back-button.js:176FastClick.sendClick @ fastclick-patched.js:308
FastClick.onTouchEnd @ fastclick-patched.js:606(anonymous function) @ fastclick-patched.js:111
range-touch.js:123 
Uncaught TypeError: Cannot read property 'trigger' of undefined(anonymous function) @ range-touch.js:123
```

This puts the app in a state where it is not possible to exit that screen without doing a hard restart on the app.  ons-back-button should support exiting to the home screen or some other user defined page in that case.

**How to reproduce**
[](If possible provide a working example where the issue is reproduced. For this, go to http://tutorial.onsen.io/ , select a framework and a template and modify or replace it. This will use the latest Onsen UI version released. After you finish, click 'Export to Codepen' button, save it and link it here.)

**Comment by IliaSky** [comment]
@erikcw We generally don't expect users to be clicking the `ons-back-button` when the stack is empty. There is some onsen logic trying to hide the button in that case. I am not sure how exactly you reopen the app with only the "deep" page. I'm not sure I have a complete grasp of how it comes to that situation.

In my opinion it's fine if we throw an exception if someone tries to do that.

As for the app going into a non-responsive state - does that occur on any exception or is this one more special?

If you want to override the default behaviour of the button you can do it via setting its `onClick` property (it's a custom one, so the case matters). You can find it in the [docs](https://onsen.io/v2/docs/js/ons-back-button.html#properties).

**Comment by erikcw** [comment]
So the app saves its current page in localstorage and then on startup will load that page page to take the user back to where they left off.  I should have been more clear -- it's not that the app becomes unresponsive -- it's just that the user is then trapped on that screen since the backbutton is the only way to get out...

I inherited this app from another dev -- so if you're saying the on-back-button is behaving as designed -- I'll probably just tweak the app a bit so it all works more smoothly for the end user in this edge case.

**Comment by munsterlander** [comment]
Sorry for the late reply, but yes Onsen is behaving as it should.  What is happening, is that on open, my guess is that you are only pushing the one page to the stack, meaning it only has the 1 item and nothing to go back too.  Hence, the back button is missing.  The easiest fix would be to push the main page first and then the page you want.  You would probably need to show the splash screen a bit longer until this is done, otherwise the users will see a very brief flash of the first page.  Hope this helps - even though it is late.

**Comment by misterjunio** [comment]
@erikcw I read what you reported and I agree with @munsterlander, nothing wrong with the back button. I'll close this
