### ISSUE TITLE
Onsen UI 2 'longdivider' modifier does not work for infinite list created in Angular Delegate

### ISSUE THREAD

**Issue by rgins16** [OnsenUI/OnsenUI#1536]
The chevron modifier appears correctly. However when I change the modifier to 'longdivider', the longdivider does not appear.

I believe this is a bug. 

Here is my Angular delegate code:

 ```
     unverifiedPicturesInfiniteList.delegate = {
       createItemContent: function(i) {

        var pictureObject = $scope.unverifiedPictures[i];
        var currentPictureID = $scope.unverifiedPictures[i]._id + 'VERIFYBUTTON';

        var profilePictureSource = '/getProfilePic/' + pictureObject.profilePicture.fileName;

        return  ons._util.createElement(
          "<ons-list-item modifier='longdivider' style='background-color: #C4C4C4;'>" + 
          "<div>" +
            "<img src=" + profilePictureSource + "></img>" + 
            "<br/><button id=" + currentPictureID + " class='btn btn-primary' type='submit'>Verify Picture</button>" +
          "</div>" + 
          "</ons-list-item>"
        );
      },
      countItems: function() {
        return $scope.unverifiedPictures.length;
      },
      calculateItemHeight: function() {
        return 275;
      }
  };
...

**Comment by munsterlander** [comment]
This appears to be answered by @IliaSky here:  http://stackoverflow.com/questions/38796616/onsen-ui-infinite-list-setting-the-modifier-as-longdivider-does-not-work

It appears to not be a bug due to your background color choice blending in.

**Comment by IliaSky** [comment]
Oh I didn't notice an issue was created - thanks for the help @munsterlander .  

@rgins16 - for similar problems feel free to discuss them @ the community first.

I will close this now.

**Comment by rgins16** [comment]
Apologies.

**Comment by munsterlander** [comment]
@rgins16 No apologies needed!  Just one big happy community trying to help everyone out and keep things organized so the Onsen team can focus on getting 2.0 out completely and bring us neat new cool stuff!
