### ISSUE TITLE
pageLoader issue

### ISSUE THREAD

**Issue by frankdiox** [OnsenUI/OnsenUI#1537]
@anatoo @argelius There is a problem with the new `pageLoader` in rc.16. Some user reported that a page loaded in `ons-splitter` fires `init` event twice. Here's why:

```javascript
  load(page, options = {}) {
    ...
    return new Promise(resolve => {

      this._pageLoader.load({page, parent: this}, ({element, unload}) => {

        rewritables.link(this, element, options, fragment => {

          // Remove old content
          this._hide();
          while (this.firstChild) {
            this.firstChild.remove();
          }

          // Attach new content
          this.appendChild(fragment);
          this._show();

          resolve(this.firstChild);
        });
      });
    });
  }
```

Before the last changes, `getPageHTMLAsync` was just creating the page element. After that this method removed the current loaded page in the splitter-content and then it attached the new created element.

However, right now pageLoader creates and attaches the new page element, i.e. at some point there are 2 pages (the old and the new) attached to the splitter. After that it removes everything and reattaches the new element.
If we simply remove the old page before calling pageLoader there will be a flickering since pageLoader is async method and for some miliseconds the splitter-content will be empty.

### Concusion
I think creating the page element and attaching it to the DOM should be separated in two different steps. This would also improve extensibility since a framework could overwrite only 1 step or the 2 of them, and also do whatever it needs between those steps.
Maybe something like `pageLoader.create` and `pageLoader.attach` instead of `pageLoader.load`? I guess Angular could overwrite `create` to use `templateCache` and things like that.

I know this issue in the splitter can be fixed just with a custom pageLoader (instead of `instantPageLoader`), but I want to know what you guys think about all of this. Opinions?

**Comment by anatoo** [comment]
>I think creating the page element and attaching it to the DOM should be separated in two different steps.

I agree your opinion, but it is simply impossible in Angular2. I struggled to just create element that bound Angular2 component without attaching but I could not find the way a few months ago. I think we should improve this problem in other ways.
