### ISSUE TITLE
pop multi pages

### ISSUE THREAD

**Issue by qifuren1985** [OnsenUI/OnsenUI#1541]
popPage method add support for pop multi pages.
for example: signup has three steps, when I finish signup, I need to pop to first page, so if popPage method support pop multi pages, I don't need to call popPage for multi time and also pop faster.

**Comment by munsterlander** [comment]
This is already a function, `resetToPage(page, [options])`.  The documents discuss it further here: https://onsen.io/v2/docs/js/ons-navigator.html

**Comment by qifuren1985** [comment]
@munsterlander 
resetToPage(page, [options])	Clears page stack and adds the specified page to the stack. Extends pushPage() parameters.

If I have A->B->C1->C2->C3 views in stack, I just want to pop to B, and I don't want to clear page stack and then create a new page.

**Comment by munsterlander** [comment]
@qifuren1985 I don't think there is a method where Onsen would know what arbitrary page you want to pop to.  You would either need to pop then push, as you work through the sign up, or delete the stack and then push back A and B.  It's just not possible for a method to know where you want to pop too as it will change for every use case.  

The only way I can "maybe" think of pulling this off, would be to use the `pages` attribute to copy your stack, know how many you want to pop, strip those off your copy of the array, clear the navigator, and then move the array back to the stack.  This is totally untested theory.  Maybe some of the Onsen team have a more elegant way of doing it.

**Comment by qifuren1985** [comment]
@munsterlander 
In iOS, it has a method called popToViewController.
- (nullable NSArray<__kindof UIViewController *> *)popToViewController:(UIViewController *)viewController animated:(BOOL)animated; // Pops view controllers until the one specified is on top. Returns the popped controllers.

**Comment by munsterlander** [comment]
@qifuren1985 Onsen doesn't have anything like that, that I am aware of.  That would need to be added.  Paging @argelius and @frankdiox for input.

**Comment by IliaSky** [comment]
@qifuren1985 from what I understand you don't want to see 3 popPage animations, right? In that case you can just do something like `navi.pages[2].remove()` twice and then do `navi.popPage()`. I think our current navigator should be able to handle if you simply remove the `ons-page` dom elements and do one animation :) 

We might consider adding such a feature in the future, but for now I think simply removing the elements yourself seems simple enough.

**Comment by argelius** [comment]
@qifuren1985 Yes, I think the easiest way is just top remove the pages manually from the stack. Another option might be to use two navigators.

I will close this for now.

**Comment by frankdiox** [comment]
@qifuren1985 @IliaSky Just one quick note, you must remove pages using `navi.children` instead of `navi.pages`. The first one is the real HTMLCollection, but the second one is just a normal array that cannot modify the DOM.
