### ISSUE TITLE
Missing method in DTS

### ISSUE THREAD

**Issue by gotenxds** [OnsenUI/OnsenUI#1544]
Hii, Im using onsen ui with angular 2 and ts and when compiling my project I get the following error :

```
error TS2339: Property 'pushComponent' does not exist on type 'OnsNavigator
```

Adding this method to the dts file fixes this for me.

**Comment by frankdiox** [comment]
@gotenxds Are you using the latest version? There is no `pushComponent` anymore: #1517

**Comment by gotenxds** [comment]
Well then this should be updated in the docs as well as it got me confused :
https://onsen.io/v2/docs/angular2/navigation.html

**Comment by frankdiox** [comment]
@gotenxds Thanks for pointing it out. @anatoo Can you update that? Not sure if what changed was the name or something else.

**Comment by anatoo** [comment]
I already removed doc comments of `pushComponent()` and `popComponent()`. Probably it is website issue. @argelius @frankdiox Could you check that?
