### ISSUE TITLE
bottom toolbar is scrolling with the page

### ISSUE THREAD

**Issue by rockneverdies55** [OnsenUI/OnsenUI#1545]
The behavior is fine in rc.15. However when I upgrade to rc.17 the bottom toolbar component starts scrolling with the page.

**Comment by IliaSky** [comment]
Hi - we haven't heard from you in a while.

I'm guessing you are using only the core (vanilla js). If the problem occurs only with a specific framework it would be good to mention it.

Currently I am unable to reproduce the issue. [Here](https://codepen.io/IliaSky/pen/AXNPBO?&editors=100) it seems to be working fine with RC.17.

Possible reasons I can come up with for your behaviour are

 - the toolbar has an `inline` attribute
 - the toolbar is located inside either an element with classes `content` or `page__content`

If you could give us a way to reproduce the issue it would be most helpful. An easy way to do that is from the [tutorial](http://tutorial.onsen.io/?framework=vanilla&category=Reference&module=page) and clicking the `export to codepen` and then you can give us your codepen url :) .

**Comment by rockneverdies55** [comment]
Thanks for the quick reply @IliaSky . Here is how I have it in my code: https://codepen.io/rockneverdies55/pen/dXAXAk?editors=0010#0

**Comment by IliaSky** [comment]
Oh ok so you are currently trying react. 

With react the toolbars for the pages should be created using additional render methods. I see you are using `renderToolbar` - there is a similar one for the bottom one -`renderBottomToolbar`. 

[Here](https://codepen.io/IliaSky/pen/AXwLBL?editors=0010)'s your codepen with that modification. 

As for why these components are created using those methods maybe you will receive a better answer from the [react-onsenui](https://github.com/OnsenUI/react-onsenui) repo.

**Comment by rockneverdies55** [comment]
Thank you @IliaSky. The issue with using `renderBottomToolbar` instead is that then I can't use `ref` to reference either the bottom-toolbar itself or any elements it contains (same exact thing is true for the actual toolbar -- I personally think that the component that renders the `Page` should have some kind of access to its Page & Toolbar elements... though I guess that's a thing to be discussed in react-onsenui project).
