### ISSUE TITLE
Ons Template in doesn't work pull hook

### ISSUE THREAD

**Issue by bado57** [OnsenUI/OnsenUI#1546]
Hi everyone;

My html code; 

```html
<ons-template id='home.html'>
   <ons-navigator var="Navigator">
        <ons-page>
            <ons-toolbar>
                <div class="left">
                    <ons-toolbar-button ng-click="menu.toggleMenu()">
                        <ons-icon icon="ion-navicon"></ons-icon>
                    </ons-toolbar-button>
                </div>
                <div class="center">Title</div>
            </ons-toolbar>
            <ons-pull-hook id="pull-hook" var="pull-hook">
                <ons-icon class="arrow" size="35px" icon="ion-arrow-down-a"></ons-icon>
                <ons-icon class="loader" size="35px" spin="true" icon="ion-load-d"></ons-icon>
                <span>Pull to refresh</span>
            </ons-pull-hook>
        </ons-page>
    </ons-navigator>
</ons-template>
```

My html code this one. I run pull hook in ons template  but not working.

My script code;

```javascript
var pullHook = document.getElementById('pull-hook');

    pullHook.addEventListener('changestate', function (event) {
        var message = '';

        switch (event.state) {
            case 'initial':
                console.log("Pull to refresh");
                message = 'Pull to refresh';
                break;
            case 'preaction':
                console.log("Release");
                message = 'Release';
                break;
            case 'action':
                console.log("Loading");
                message = 'Loading...';
                break;
        }

        pullHook.querySelector('span').innerHTML = message;
    });
```

Thanks .

**Comment by munsterlander** [comment]
Are you mixing vanilla JS with AngularJS?  Which do you prefer to implement for this?

**Comment by frankdiox** [comment]
@bado57 `ons-template` is just a *template* (surprisingly), it's not a component or instance of component. That implies its content is not attached to the DOM and you cannot simply get it with `getElementById`. I'm not sure how is the flow of your application, but putting `ons-navigator` inside `ons-template` means you have an `ons-splitter` or `ons-tabbar` loading it, right? If that's not the case then you don't need `ons-template` there.

Also, as @munsterlander pointed out, you are mixing Vanilla JS and AngularJS stuff. [This](http://tutorial.onsen.io/?framework=vanilla&category=Reference&module=pull-hook) is a JS pullhook and [this](http://tutorial.onsen.io/?framework=angular1&category=Reference&module=pull-hook) is the AngularJS one. Hope it helps!

**Comment by munsterlander** [comment]
@frankdiox Awesome, this is right in line with my thinking.  I was trying to figure out if there was a controller loading this with Angular and I was going to suggest after attachment to the DOM, then instantiate the pullhook listener; otherwise, if it was vanilla, then obviously the item doesn't exist and is probably returning undefined for null.

**Comment by argelius** [comment]
I will close this.
