### ISSUE TITLE
MacOS: Chrome 'flicker' when infinite scrolling with <LazyList />

### ISSUE THREAD

**Issue by curtispatrick84** [OnsenUI/OnsenUI#1548]
**Environment**
Onsen 2.0.0-rc.17
React 15.2.1
Mac OS (10.11.5) and Chrome (52.0.2743.116 64-bit)

**Encountered problem**
In Chrome ONLY (not in FireFox nor Safari): as a user scrolls through a LazyList, the rendered data ‘flickers.’ Here is a link to a GIF showing a side-by-side comparison with the same App in Safari and in Chrome: http://g.recordit.co/TOPA56PFmK.gif

Out of curiosity, is there a method to increase the 'buffer' of rendered items before and after the visible LazyList area? I'm wondering if that would be a good workaround?

**How to reproduce**
Codepen to follow...

**Comment by argelius** [comment]
@curtispatrick84 Thanks for reporting! I was unable to reproduce this myself. 

Please ping me again when you have made a Codepen example. :+1:
