### ISSUE TITLE
Angular 2 bindings - RC.2 doesn't like pageLoader

### ISSUE THREAD

**Issue by IliaSky** [OnsenUI/OnsenUI#1549]
__Environment__
Onsen 2 RC.17
Angular 2 RC.2 - RC.4
Chrome

__Encountered problem__
When loading a tab in the tabbar or page in the navigator using the `page` property. Bindings like `{{sth}}` or `*ngFor` don't work out of the box and require some action like a click on an element with `(click)="..."` to start working. 

The page's `ngOnInit` method is also not called until that point, whereas it would be called with the old navigator.

__How to reproduce__:
```
@Component({
  selector: 'ons-page',
  directives: [ONS_DIRECTIVES],
  template: `
    <div class="page__content">
      <ons-list>
        <ons-list-item *ngFor="let item of items">
          <div class="center">{{item}}</div>
        </ons-list-item>
      </ons-list>
    </div>
  `,
})
export class MyPage {
  items = ['das', 'sa'];
}

@Component({
  selector: 'app',
  directives: [OnsNavigator],
  template: `<ons-navigator [page]="myPage"></ons-navigator>`,
})
export class App {
  page = MyPage;
}
```

In the constructor of MyPage a list can be seen with `console.log`, but in the html there is only a comment `<!--template bindings={}-->`.

When the button is clicked the `ngOnInit` of the page is called and the comment and content update themselves.

I had found this bug a while ago, but kept thinking it was a problem with my setup. I was having a hard time finding the cause as for why these things work in the tests, but not in the project. I was thinking that may be fixed when angular2-onsenui@0.1.0-beta.9 and onsenui@2.0.0-rc.16. I just checked that it was the Angular 2 version which was the cause, so that's why I'm reporting it now.

**Comment by anatoo** [comment]
@IliaSky Thank you for reporting. Ok, I will investigate this problem.

**Comment by frankdiox** [comment]
@anatoo Can we close this issue?

**Comment by anatoo** [comment]
Yes, this problem can't be reproduced in current master branch.
