### ISSUE TITLE
Adding device feedback

### ISSUE THREAD

**Issue by dnish** [OnsenUI/OnsenUI#1550]
Hey,
I'm just wondering if we could add "haptic feedback" for Android devices, if the user clicks on a component. There is a Cordova [plugin](https://github.com/VVelda/device-feedback) for that feature. I think it would be cool if we could enable it via plugin (or if the plugin is installed). This should give Android users a more native feeling.

**Comment by munsterlander** [comment]
With Onsen and Monaca you can!  Just use the import option described here:  https://docs.monaca.io/en/manual/dependencies/custom_cordova_plugin/#custom-cordova-plugin

**Comment by dnish** [comment]
Yeah I know, but I want to fire the <code>window.plugins.deviceFeedback.acoustic()</code> on every click that happens on a React component like a button or a list item. Now I have to add a onClick handler manually to all my own components, but I think it would be better if Onsens would integrate it in it's own React component since they want give their users a "real native feeling".

**Comment by munsterlander** [comment]
@dnish Although I have not tried this plugin, I did find several that can be used with React and also do not require onClick handlers.  Maybe these could help out!  Googling for haptic plugins found a bunch.

https://github.com/VVelda/device-feedback

**Comment by argelius** [comment]
@dnish Instead of adding a click handler to every button you could make a new component that wraps the Onsen Button component and adds the feedback on click.

I will close this since I don't think we will implement this.
