### ISSUE TITLE
exception on mac os safari 9.1.2 and ios 9.3.3

### ISSUE THREAD

**Issue by qifuren1985** [OnsenUI/OnsenUI#1552]
when push page without toolbar in safari, it will throw an exception.

**Environment**
Onsen 2.0.0-rc.15
react 15.3.0
iOS 9.3.3 safari and mac osx safari 9.1.2

**Encountered problem**
in function _canAnimateToolbar, this._contentElement is undefined

TypeError: undefined is not an object (evaluating 'element.children')
findChild — lazy-repeat.js:333
_canAnimateToolbar — ons-splitter-side.js:274
_shouldAnimateToolbar — ons-pull-hook.js:242
push — ons-pull-hook.js:443
push — ons-splitter-content.js:149
link — ons-speed-dial.js:213
（匿名函数） — ons-splitter-content.js:202
lib$es6$promise$$internal$$initializePromise — vendor.36d807e3ef51bdc8b34f.js:38320
lib$es6$promise$promise$$Promise — vendor.36d807e3ef51bdc8b34f.js:38493:106
（匿名函数） — ons-splitter-content.js:124
lib$es6$promise$$internal$$tryCatch — vendor.36d807e3ef51bdc8b34f.js:38273
lib$es6$promise$$internal$$invokeCallback — vendor.36d807e3ef51bdc8b34f.js:38285
（匿名函数） — vendor.36d807e3ef51bdc8b34f.js:38077
lib$es6$promise$asap$$flush — vendor.36d807e3ef51bdc8b34f.js:38030

**How to reproduce**
`
render() {
    return (
      <Page>
        <div className="login__page">
          <img className="login__logo"
               src={ require('../../img/logo.png')} />
          </div>
        </div>
      </Page>
    );
`

**Comment by lideen** [comment]
+1
