### ISSUE TITLE
The range component cannot "touch and slide" with Splitter Side Menu

### ISSUE THREAD

**Issue by gnokit** [OnsenUI/OnsenUI#1554]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Onsen 2 rc 16
Chrome/Android

__Encountered problem__

The Range component cannot "touch and slide" with Splitter Side Menu

__How to reproduce__
[](If possible provide a working example where the issue is reproduced. For this, go to http://tutorial.onsen.io/ , select a framework and a template and modify or replace it. This will use the latest Onsen UI version released. After you finish, click 'Export to Codepen' button, save it and link it here.)
https://codepen.io/gnokit/pen/zBbPYV?&editors=101#

**Comment by argelius** [comment]
Thank you for reporting @gnokit ! I will take a look at this next week

**Comment by argelius** [comment]
@gnokit Sure sorry for the long delay. This has been fixed now.
