### ISSUE TITLE
Input Placeholder - After user input, placeholder moves to upper left corner in material

### ISSUE THREAD

**Issue by munsterlander** [OnsenUI/OnsenUI#1557]
**Environment**
Onsen 2 RC 17
Android 6.0.1

**Encountered problem**

https://community.onsen.io/topic/618/rc-16-text-input-placeholder-issues

**How to reproduce**

`<ons-input placeholder="00"></ons-input>` 

View on Android with Material design.   Type anything into the input and the placeholder will go to the upper left corner outside of the input.

Edit:  This has been confirmed to only affect material design.

**Comment by argelius** [comment]
@munsterlander I will take a look at this. Is this happening even if you don't have the `float` attribute?

**Comment by munsterlander** [comment]
@argelius Yes it happens without float.  So basically my test is, brand new project using baseline template (no custom anything), just add an input field with a placeholder, use the default material style on Android and it happens as the images show.  If you force the style to ios, it works fine on Android.

**Comment by lucandrade** [comment]
@munsterlander How do i force ios style?

**Comment by munsterlander** [comment]
With the following:

```
<script>  
        ons.disableAutoStyling();
</script>
```

**Comment by lucandrade** [comment]
@munsterlander thanks man!

**Comment by schonmann** [comment]
I don't know if my problem deserve a new issue, so im posting here. Well, i started developing with OnsenUI-2 today. I am having issues dealing with `<ons-input>` and the placeholder attribute. 

* Code:

<ons-page modifier="material">

    <div style="text-align: center;">
        <p> 
            <ons-input placeholder="Username" id="username" modifier="material" float></ons-input>
        </p>
        <p>
            <ons-input placeholder="Password" id="password" modifier="material" type="password" float></ons-input>
        </p>
        <ons-row style="margin-top: 30px;padding-left:50px;padding-right:50px;">
            <ons-button id="loginButton" modifier="large" onclick="AuthController.login()">Login</ons-button>
        </ons-row>
    </div>

</ons-page>

* Compiled code running on Android: http://pastebin.com/qswLAHFy

* In the view, it looks something like this: http://imgur.com/a/QfO47

Why the placeholder text is floating right and not left? If i use the modifier "underbar", or the attribute "content-left", the results are the same running from Android. Am i missing something?
Thanks!

Ps: the only thing i changed after installing onsen to my project was to download a customized theme style sheet from http://components2.onsen.io/ .

**Comment by argelius** [comment]
@schonmann Does it work correctly if you use the default template?

**Comment by schonmann** [comment]
@argelius 
Sorry for the delay. Ok, i think i found the problem. The css stuff i downloaded from 'http://components2.onsen.io/' messed it up. I've rolled back and now it's working fine.
