### ISSUE TITLE
React Popover component does not work reliably in Safari/Firefox

### ISSUE THREAD

**Issue by porchdog** [OnsenUI/OnsenUI#1558]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

**Environment**
Onsen 2 beta 17
React 15.3.1
OS X 10.11
iOS 9.3

**Encountered problem**

When I used a Popover, it wouldn't display in Safari or Firefox.  It worked perfectly in Chrome.

**How to reproduce**

https://codepen.io/anon/pen/rLgjjA?editors=1011

You'll notice that I'm using the Popover component in a slightly unusual way.  That's because setting it's isOpen property to my state variable (the way it's intended to work) also doesn't work if the Popover is used as a Popover for a marker in a Google Map.  

Using it the way the codepen illustrates makes it work perfectly with Google Maps in Chrome.  But not in Safari or Firefox.

**Comment by davidperrenoud** [comment]
Wasn't this fixed with commit https://github.com/OnsenUI/OnsenUI/commit/738c7f0787767506f0365dc9325f6d8f0e279fc3?
