### ISSUE TITLE
Dialog show() method parameters are broken

### ISSUE THREAD

**Issue by rgins16** [OnsenUI/OnsenUI#1561]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Onsen 2
MEAN.JS
Latest Version of Chrome

__Encountered problem__
I have created a dialog in my jade file. I am displaying it in JavaScript using the dialog show method and optional show parameters like this:

```
ons.createDialog('dialog.html').then(function(dialog) {
  var options = {
    animation: "fade",
    animationOptions: {delay: 2.0}
  };

  dialog.show(options);
});
```

The dialog does not "fade", but it slides from the bottom. The delay still works as expected. 

Additionally, when I changed the animation to "none", there is no animation as expected, but the delay does not work.

**Comment by argelius** [comment]
Thanks @rgins16 ! We will take a look at this.

**Comment by argelius** [comment]
@rgins16 I took a look at the code and it looks like the docs for the "fade" animator is a mistake. There is only two default animators for iOS and Android + a simple slide animation.

We will consider adding a simple fade animator for the dialogs as well.

The `delay` parameter currently doesn't work for the `none` animator. We will fix this but I think it's not only for the dialog, it's probably the case for other components as well that that you can't put a delay on the `none` animator.

I will close this for now.
