### ISSUE TITLE
iOS app keyboard bug when focussing on a select drop-down

### ISSUE THREAD

**Issue by jitu-git** [OnsenUI/OnsenUI#1562]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

So I have a Cordova 6.2.9 app running on iOS 8.4.1 using both Onsen 2.0.0

I have a form on the app with text input fields and select drop downs. In the video you see I am focussed on a text field, and when try to touch a select box, the drop-down appears, but then the focus moves back to the text field, even randomly to other text fields sometimes.

I don't have any event listeners hooked up to any of the fields. Any one have any ideas as to how I can't stop this behaviour?
__Environment__
Onsen 2.0.0
Angular 1.5.2
iOS 9.2

__Encountered problem__

__How to reproduce__
[](If possible provide a working example where the issue is reproduced. For this, go to http://tutorial.onsen.io/ , select a framework and a template and modify or replace it. This will use the latest Onsen UI version released. After you finish, click 'Export to Codepen' button, save it and link it here.)

**Comment by argelius** [comment]
@jitu-git Sorry for the late reply. Can you provide some steps to reproduce this bug?

I will close this for now but please feel free to open again if you feel it's a bug in Onsen UI.

**Comment by jitu-git** [comment]
I am not using any special code for this. it just a simple form. 
Here code  of the full page - 

`<ons-page ng-device-backbutton="myNavigator.popPage()" ng-controller="BookingController as Booking" >
    <ons-toolbar>
        <div class="left">
            <ons-back-button>Back</ons-back-button>
        </div>
        <div class="center">Car Wash Booking</div>
        <div class="right">
            <ons-toolbar-button ng-click="myNavigator.pushPage('templates/notifications.html',{animation: 'slide'})">
                <ons-icon  icon="fa-eye"></ons-icon>
            </ons-toolbar-button>
        </div>
    </ons-toolbar>
    <div class="homeLogo">
        <img src="img/screenLogo.png" />
    </div>
    <h3 class="heading">Select Car for Wash</h3>
    <div class="addCar">
        <ons-list-item tappable>
            <label class="left">
                <ons-input type="checkbox" input-id="check-1" ng-model="other_car" ng-click="wash.car='';wash.price=0;add_car.car_type_id=''"></ons-input>
            </label>
            <label for="check-1" class="center smallFont">
                I am washing someone else's car as a gift.
            </label>
        </ons-list-item>
        <ons-list>
            <div ng-init="Booking.myCars()" ng-show="!other_car">
                <select id="my_cars" ng-model="wash.car" ng-options="car.car_number_plate for car in Cars track by car.id" ng-change="Booking.getCarWashPrice(wash.car)" >
                    <option value="">Select Car</option>
                </select>
            </div>
            <div  ng-show="other_car">
                <label style=" margin-bottom:10px">
                    <h3 class="heading">Add Car Details</h3>
                </label>
            </div>
        </ons-list>
        <div ng-show="other_car" ng-init="Booking.carTypes()">
            <section style="text-align: center;">
                <p>
                    <select modifier="tappable" ng-model="add_car.car_brand_id" ng-change="Booking.getModels(add_car.car_brand_id)">
                        <option value="">Select Car Brand</option>
                        <option ng-repeat="brand in brands" ng-value="{{brand.id}}">{{brand.brand_name}}</option>
                    </select>
                </p>
                <p>
                    <select modifier="tappable" ng-model="add_car.car_model_id" ng-show="models">
                        <option value="">Select Car Model</option>
                        <option ng-repeat="car_model in car_models" ng-value="{{car_model.id}}">{{car_model.model_name}}</option>
                    </select>
                </p>
                <p>
                    <ons-input modifier="underbar" placeholder="CAR NUMBER PLATE" ng-model="add_car.car_number_plate" ></ons-input>
                </p>
                <p>
                    <select modifier="tappable" ng-model="add_car.car_type_id"  ng-options="types.car_type for types in car_types track by types.id" ng-change="Booking.getCarWashPrice(add_car.car_type_id)">
                        <option value="">Select Car Type</option>
                    </select>
                </p>
            </section>
        </div>

        <ons-input placeholder="Location of car" ng-model="wash.address" type="textarea"></ons-input>
        <select ng-init="Booking.parkingAreas()" ng-model="wash.parking" ng-options="place.car_space for place in parking track by place.id" ng-change="Booking.parkingDesc(wash.parking)">
            <option value="">Select Car Parking</option>
        </select>
        <ons-list-item>
            <div class="left">Total amount to be paid : </div>
            <div class="right">SGD {{wash.price}}</div>
        </ons-list-item>
    </div>
    <div class="gap"></div>
    <ons-row ng-show="provide_service" class="row ons-row-inner row-bottom bottomFix" align="bottom" ng-click="Booking.proceedToPayment()">
        <ons-col class="col ons-col-inner ">
            <ons-button modifier="large" class="button button--large fixedRight">Proceed To Next</ons-button>
        </ons-col>
    </ons-row>
</ons-page>
`

**Comment by RamiAlmofleh** [comment]
have you answer for your Problem.
I have the same Problem with iPhone 7
