### ISSUE TITLE
ons-carousel - 'postchange' fired in an unexpected page on Android

### ISSUE THREAD

**Issue by puku0x** [OnsenUI/OnsenUI#1565]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

Hi,

Thank you for your great job.
I'm developing an app and facing a big problem about 'ons-carousel' component now.

**Environment**
Onsen 2 RC17
Angular 1.5.8
Android 5.1.1

**Encountered problem**
After pushed from a page with a ons-carousel to a page with a text input, the index of the carousel was set to 0 and 'postchange' was fired when the text input was focused.

This problem was caused only on Android.

**How to reproduce**
1. Create a page which has an ons-carousel component.
2. Push a page which has a text input tag.
3. Focus the text input to display the software keyboard.
https://codepen.io/puku0x/pen/XKvVoJ

[](If possible provide a working example where the issue is reproduced. For this, go to http://tutorial.onsen.io/ , select a framework and a template and modify or replace it. This will use the latest Onsen UI version released. After you finish, click 'Export to Codepen' button, save it and link it here.)

**Comment by argelius** [comment]
Thanks @puku0x ! We will take a look at this issue.

**Comment by puku0x** [comment]
Unfortunately, I found this problem happened on iOS too.

**How to reproduce**
1. Create a page which has an ons-carousel component.
2. Push a page which has a text input tag.
3. Rotate the orientation of the page.

**Comment by nodefish** [comment]
I'm experiencing something similar: push a page which contains an html5 `<video>` tag. Once the video request is completed (initial load), I have a carousel on another page which fires `postchange`.

The event seems to originate from `_onResize` which seems to be tied to a global listener (`window` scope); that explains why it can happen from an entirely different page.

I'm not sure how to solve this at the moment.

**Comment by misterjunio** [comment]
@puku0x @nodefish Sorry for the delay. I cannot reproduce your errors with the latest release (2.2.2). Do you mind checking if they keep occurring to you?

**Comment by puku0x** [comment]
I confirmed that the issue was solved on both iOS and Android since Onsen UI v2.0.5.
Thank you very much !!

**Comment by nodefish** [comment]
It's still happening for me FYI. Basically I have a carousel inside 1 `<ons-tab>`, and in another `<ons-tab>` I've got a dynamic html5 `<video>`. When the video loads, the carousel in the other tab fires `postchange`.

**Comment by misterjunio** [comment]
@nodefish you're right, I managed to recreate your issue and opened another ticket (#1952). I fixed it already and will make a PR, thanks for your input 👍
