### ISSUE TITLE
Docs Issue: React Modal live example not exist (404 error)

### ISSUE THREAD

**Issue by cyclops24** [OnsenUI/OnsenUI#1566]
Hi guys,
I try use Modal live example in react but it's not working:
https://onsen.io/v2/docs/react/Modal.html
This error message also printed in my firebug console:
`"NetworkError: 404 Not Found - https://onsen.io/tutorial/tutorial/react/Reference/modal.html"`
All other live example works well except this one.

**Comment by munsterlander** [comment]
Good catch.  I will work on it right now and put in a PR.

**Comment by frankdiox** [comment]
It's been merged so I'm closing this now. The website will be updated soon :smile: 
Thanks guys!

**Comment by cyclops24** [comment]
Thanks @munsterlander and @frankdiox. :wink:
