### ISSUE TITLE
support ios8

### ISSUE THREAD

**Issue by ilovezy** [OnsenUI/OnsenUI#1569]
on ios8  the dialog component did not position at center and vertical middle, suggest to add prefix to cover some css3 attributes

**Comment by argelius** [comment]
@ilovezy Sorry for the late reply. We will take a look at this.

**Comment by argelius** [comment]
@ilovezy I am unable to reproduce this. Can you please provide some steps to reproduce it? 

Are you running in Cordova? Can you show some very simple code that reproduces this bug?

**Comment by argelius** [comment]
I will close this for now but please feel free to open it if you can provide a way to reproduce the issue.
