### ISSUE TITLE
Support <template> tag

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#1573]
I think we should support normal `<template>` tag so you can do:

```
<template id="my-template">
  <ons-page>
   Hello, world!!
  </ons-page>
</template>
```

And then you  can use these templates normally like:

```
nav.pushPage('my-template');
```

@anatoo @frankdiox What do you think?

**Comment by anatoo** [comment]
👍

**Comment by frandiox** [comment]
Continues in #1814
