### ISSUE TITLE
ons-tabbar doesn't store "options" objects

### ISSUE THREAD

**Issue by alegauss** [OnsenUI/OnsenUI#1578]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Onsen 2 vue 2

__Encountered problem__
On page (https://onsen.io/v2/docs/js/ons-tabbar.html) describes that:
loadPage(url, [options])	

> Displays a new page without changing the active index.

setActiveTab(index, [options])
> Show specified tab page. Animations and **other options can be specified** by the second parameter.

__How to reproduce__
 I  tried to pass parameter for example:
myTabbar.loadPage('url_test', {'var1':'value1', 'var2': 'value2'})
or
myTabbar.setActiveTab('1', {'var1':'value1', 'var2': 'value2'})

But I can't find the attributes var1 and var2 into object myTabbar. I analyzed the source code and I checked that the "options" object isn't stored, it is used for example to animation parameter: options.animation, but in documentation page describes "..other options can be specified.."

**Comment by argelius** [comment]
@alegauss Thanks! I think this might be a problem with the documentation. I will fix it.

You can not pass options like this in the tabbar at this point.
