### ISSUE TITLE
ons-back-button doesn't work after pushpage with splitter in ios cordova

### ISSUE THREAD

**Issue by juspriet** [OnsenUI/OnsenUI#1580]
__Environment__
Onsen 2.0.0-rc.18
jquery
iOS 9.3.5

__Encountered problem__
I have a ios cordova application with splitter and ons-navigator inside ons-splitter-content.
After pushPage, ons-back-button doesn't work.
And pushPage animation doesn't slide !

**Comment by argelius** [comment]
@juspriet Can you create a simple example that reproduces this bug?

**Comment by juspriet** [comment]
here is a working exemple.
No need to put a ons-splitter component.
The problem seems to be when there is no ons-toolbar on the first page but there is one in the second page....


[Archive.zip](https://github.com/OnsenUI/OnsenUI/files/467226/Archive.zip)

**Comment by munsterlander** [comment]
@juspriet I will look at your code, but below is fully functioning code on both platforms for me.

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="mobile-web-app-capable" content="yes" />
    <meta http-equiv="Content-Security-Policy" content="default-src * data:; style-src * 'unsafe-inline'; script-src * 'unsafe-inline' 'unsafe-eval'">
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,300italic,300,400italic,500,700,700italic,500italic' rel='stylesheet' type='text/css'>
    <title>Onsen UI Forum Help by Munsterlander</title>

    <link rel="stylesheet" href="https://cdn.rawgit.com/OnsenUI/OnsenUI-dist/2.0.0-rc.18/css/onsenui.css" type="text/css" media="all" />
    <link rel="stylesheet" href="https://cdn.rawgit.com/OnsenUI/OnsenUI-dist/2.0.0-rc.18/css/onsen-css-components.css">
    <script src="https://cdn.rawgit.com/OnsenUI/OnsenUI-dist/2.0.0-rc.18/js/onsenui.js"></script>
    <script src="components/loader.js"></script> 

  </head>
  <body>
<ons-navigator page="home.html" id="myNav"></ons-navigator>
<ons-template id="home.html">
    <ons-page>
        <ons-button onclick="document.getElementById('myNav').pushPage('page1.html');">Push Page</ons-button>
    </ons-page>
</ons-template>
<ons-template id="page1.html">
<ons-page>
    <ons-toolbar>
  <div class="left">
    <ons-back-button>Back</ons-back-button>
  </div>
  <div class="center">Page 1</div>
 </ons-toolbar>
</ons-page>
</ons-template>
    
</body>
</html>
```

**Comment by juspriet** [comment]
I've just tryed your exemple both with :
- My IPhone 6 with ios 9.3.5 (cordova)
- An IPhone 5 simulator with  ios 9.3.5 on my mac (cordova)
And it doesn't work !! Same problem !

When I try your exemple with Safari on my Iphone, It works (without cordova, but with apache)

When I try your exemple with 2.0.0-rc.17 on cordova, it works too... 

not easy...

**Comment by munsterlander** [comment]
Hmmm, that is odd.  Hopefully someone else can try some other devices.  I used the Monaca debugger to test.  Are you building the app?  Is there anything in the console?

**Comment by juspriet** [comment]
yes, i’m building the app with the last version of cordova and no, there is absolutely nothing in the console, even with the cordova-plugin-console plugin.

**Comment by argelius** [comment]
@juspriet @munsterlander 

Maybe it's related to this issue: https://github.com/OnsenUI/OnsenUI/issues/1552

However, in this case an error was thrown.

**Comment by juspriet** [comment]
I’ve just tried it with safari, i have a warning :
Failed to load resource: the server responded with a status of 404 (Not Found)
Cannot GET /exemple/www/components/loader.js

**Comment by asial-matagawa** [comment]
It also reproduced with my macOS Safari 9.1.3 and I found that this issue is caused by the following line:
https://github.com/OnsenUI/OnsenUI/blob/5d24ffb8708fa2446fca030931bdcefb9e65146b/core/src/elements/ons-page.js#L32

When I replaced
```
  _getToolbarElement() {
    return util.findChild(this, 'ons-toolbar') || nullToolbarElement;
  }
```
with
```
  _getToolbarElement() {
    return util.findChild(this, 'ons-toolbar') || document.createElement('ons-toolbar');
  }
```
then the munsterlander's code worked fine.

It seems that when `document.createElement('ons-toolbar')` is invoked too early, the evaluated value gets a broken prototype chain.
This behavior reproduced only with Safari (didn't reproduce with Chrome).

**Comment by iqmeta** [comment]
Same here on **r18, broke back button**.. on r17 same code is working.

Also there is a **tab-bar problem with iOS / mobile Safari,** on Chrome it's working fine:

```
document.addEventListener('init', function (event)
{
	var page = event.target;   
	console.log("init:" + page.id);
}
```


**Chrome console is correct:**
```
init:tabBar
init:menu
init:gruppenPage
init:home
```

**On iOS gruppePage is added 3x times:**
```
init:menu
init:gruppenPage
init:gruppenPage
init:gruppenPage
init:home
```

**Markup Tabbar** no where else in code gruppen.html was referenced
```
 <ons-tabbar id="tabs" animation="slide">
        <ons-tab active page="home.html" id="alarm">
            <div class="tab-bar__icon">
                <ons-icon icon="ion-ios-bell" size="33px" style="line-height:0px"></ons-icon>
            </div>
        </ons-tab>
        <ons-tab id="gruppen" page="gruppen.html">
            <div class="tab-bar__icon">
                <ons-icon icon="ion-radio-waves" size="33px" style="line-height:0px"></ons-icon>
            </div>
        </ons-tab>
</ons-tabbar>
```
**gruppen.html**
```
<ons-page id="gruppenPage">
    <div id="testX">X</div>
    <ons-list id="groupList">
    </ons-list>
</ons-page>
```

```
tabs.addEventListener('postchange', function(event)
{
	$("#textX").text("Y") <= works only on chrome. on iOS not! because tabBar added 3 times the gruppenPage.html. Th
}

```

**Screenshot from Cordova Remote Debugger**
![image](https://cloud.githubusercontent.com/assets/7533842/18483683/67da9054-79e5-11e6-86d9-a00c98e6dcf8.png)

**Comment by asial-matagawa** [comment]
@iqmeta:
Thank you for reporting.
I created a new issue page for the problem you reported, so please check #1584.
