### ISSUE TITLE
Theme Roller: missing declarations for custom themes

### ISSUE THREAD

**Issue by copleykj** [OnsenUI/OnsenUI#1590]
Using the theme roller, there seems to be some missing declarations. Specifically the ones I have found are for `list__item__left`, `list__item__right`, and `list__item__center`.

When trying to lay out a list item with center, left, and right classes they stack as block elements when using the custom theme css. If I use the css directly from the node_modules dir everything lays out like it's supposed to.

**Comment by argelius** [comment]
@copleykj Hi! It's still generating themes for 1.3.

We will update the Theme Roller to the latest version soon.

**Comment by copleykj** [comment]
Is there any ETA on this? Looking to release an app very soon at which point this becomes top priority. Either that or I'm gonna have to modify the theme by hand :)
