### ISSUE TITLE
Not backward compatible with v1?

### ISSUE THREAD

**Issue by xemox** [OnsenUI/OnsenUI#1591]
__Environment__
Onsen 2.0
Angular 1.4.7
Android 5.1.1

__Encountered problem__
My application cannot run when running with onsen v2.
Some functions are missing in this v2.0.0, usually I don't encounter problem with v1.3.14
1. I encounter callback error with my javascript
2. some functions are no longer exist, setChecked for example

What should I do?
Should I rewrite my application?

The only good point in v2 is the new design.

**Comment by frankdiox** [comment]
@xemox I think there are many good points in v2, personally. We changed the API with the version change. There is a [migration guide in the docs](https://onsen.io/v2/docs/guide/angular1/from-v1-to-v2.html).
