### ISSUE TITLE
Feature Request: Change ons-prompt input type to 'password'

### ISSUE THREAD

**Issue by rgins16** [OnsenUI/OnsenUI#1594]
I am using an ons-promt in my app. Instead of using messageHTML, I would like to be able to set the type of input in the ons-promt to password. After reviewing the documentation and experimenting on my own, there is currently no way to do this.

**Comment by frankdiox** [comment]
@rgins16 That makes sense, we should implement `options.inputType` or something simmilar :)
In the meantime you can create your own `ons-alert-dialog` with that input.

**Comment by rgins16** [comment]
Alrighty. Hope I helped :)
