### ISSUE TITLE
ons.notification layout is broken in Android

### ISSUE THREAD

**Issue by kanakoubukata** [OnsenUI/OnsenUI#1595]
See attached file.

__Environment__
Onsen 2.0.0

![ons-notification](https://cloud.githubusercontent.com/assets/8393422/18664606/4c20a8f2-7f5e-11e6-9d0e-a4a5bd84cd8d.png)

**Comment by frankdiox** [comment]
Thanks @kanakoubukata ! I just made a PR to fix this.
