### ISSUE TITLE
Documentation/Tutorial/KitchenSink for Angular2 final is outdated

### ISSUE THREAD

**Issue by Dynalon** [OnsenUI/OnsenUI#1598]
Angular2 final uses the `@NgModule` syntax (a major api change), but all of the samples and documentation I could find to Onsen still use the old `ONS_DIRECTIVES` Api which is incompatible to Angular2 final.

Additionally, the latest OnsenUi installed via `npm install angular2-onsenui` today has removed the `ONS_DIRECTIVES` export and replaced it with a `OnsenModule` export which is correct according to the final API. However, some directives (i.e.`ons-page`) are not available in Angular2, in contrast to the docs.

**Comment by anatoo** [comment]
Documentation, tutorials and kitchen sink is updated now.
