### ISSUE TITLE
Meteor/React: HTML.Raw is not a function

### ISSUE THREAD

**Issue by erikanthonywall** [OnsenUI/OnsenUI#1599]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
onsen 2.0.0
react-onsenui 1.0.0
react 15.3.2
meteor 1.4.1.1

__Encountered problem__
Meteor apps built with OnsenUI fail to bootstrap due to an error being thrown to the console:

![image](https://cloud.githubusercontent.com/assets/4763166/18725262/8f61ef72-800d-11e6-855e-839224a7f2e4.png)

__How to reproduce__
This issue can be reproduced by cloning the [Meteor ToDo app](https://github.com/frankdiox/OnsenUI-Meteor-ToDo/tree/master/client) repo by @frankdiox and running it with the latest version of Onsen. I've confirmed that it still works by downgrading to rc17.

**Comment by Meloncon** [comment]
I'm having the same problem, however I get it with the Meteor ToDo app out-of-the-box with no modifications. It doesn't seem to matter if I'm running rc17 or the final 2.0.0 version.

**Comment by frankdiox** [comment]
@erikanthonywall @Meloncon Thanks for reporting! We will check this as soon as we can, but right now we are traveling to London for Angular Connect event.

**Comment by kaiyes** [comment]
I have the same issue. Instead of opening another issue, I will just follow this one. No matter what, this issue persists.  We might have to stop using onsen for the current project since we are on a deadline.

**Comment by frankdiox** [comment]
I just came back to Tokyo and will try to reproduce this tomorrow!

**Comment by frankdiox** [comment]
In any case, this is likely to be related to the CustomElements polyfill update. We didn't change too much since  rc.16 or rc.17 except that so you can probably use that version for now. [The changelog is here](https://github.com/OnsenUI/OnsenUI/blob/master/CHANGELOG.md).

**Comment by robort** [comment]
The same issue was met in Meteor React ToDo App with **2.0.0-rc.17**, and will disappear after my downgrading to **2.0.0-rc.16**. Hope the info helps.

    "meteor": "1.4.1.1",
    "onsenui": "2.0.0-rc.16",
    "react": "^15.3.0",
    "react-onsenui": "^0.7.5"

**Comment by kaiyes** [comment]
Okay I solved the issue by downgrading to `2.0.0-rc.16`

**Comment by frankdiox** [comment]
The app in the repo is already using `rc.17` and actually that release only modifies type definitions, so `rc.17` works. I got the error only with `2.0.0` right when I do `import ons from 'onsenui'`.

Looks like Blaze is running something under the hood and it breaks. There is a related question here without Onsen UI: https://stackoverflow.com/questions/39391076/html-raw-is-undefined-in-meteorblazereact-app-after-meteor-npm-update

I'm not sure if this is something fixable on this side. I will try find some solution anyway.

**Comment by frankdiox** [comment]
@erikanthonywall @Meloncon @robort @kaiyes Looks like this issue is related to Blaze (yes, it runs somehow under React). Maybe there is something in the new polyfill that Blaze doesn't like, but it is not an issue in Onsen UI core library. If you want to use Blaze then `rc.17` is compatible.

If you don't need Blaze because you use React for example, then simply run this:

```
meteor remove blaze-html-templates
meteor add static-html
```
That fixes this issue for me with `onsenui@2.0.0` and `react-onsenui@1.0.0`. Perhaps you will need to try `meteor run` more than once after that.

More info here: https://github.com/meteor/meteor/issues/5580
