### ISSUE TITLE
ons-input edit bug

### ISSUE THREAD

**Issue by rgins16** [OnsenUI/OnsenUI#1601]
**Environment**
Onsen 2
Angular 1.5.9
Newest Version of Chrome

**Encountered problem**
I have a few ons-input fields on the same page
I can successfully type some input into any of them
I click into another ons-input and type input for that one
I click back to the first ons-input to edit it
the very first character I type is displayed at the position where I clicked (expected behavior)

UNEXPECTED BEHAVIOR // BUG
Once a second character is typed, the cursor is moved to the end of ons-input
Every character I type after the first character is appended to the end of the ons-input, not on the position I clicked to edit

**Comment by argelius** [comment]
@rgins16 Thanks for reporting! We will take a look at this issue.

**Comment by frandiox** [comment]
Fixed in e74c931 .
