### ISSUE TITLE
Initial Value Issue on ons-input with type="date"

### ISSUE THREAD

**Issue by leventkaragol** [OnsenUI/OnsenUI#1603]
**Environment**
Onsen 2.0
Angular 1.5.7
Android 6.0

**Encountered problem**

I could not set initial value an ons-input with date type anywise. For example;

`<ons-input type="date" placeholder="Test" ng-model="dateValue"></ons-input>`

or even

`<ons-input type="date" placeholder="Test" value="2016-06-01"></ons-input>`

(Controller has following code; `$scope.dateValue=new Date()`)

Is there anyone achieved this or is this a bug with onsenui 2.0? By the way, following code line (standard html form control) works without any problem.

`<input type="date" placeholder="Test" ng-model="dateValue">`

**Comment by argelius** [comment]
@leventkaragol We will take a look at this.

@asial-matagawa Can you take a look at this issue?

**Comment by asial-matagawa** [comment]
@argelius 
I'm fixing another issue now, but I will fix this issue as soon as possible.

**Comment by HatemJerbi** [comment]
same problem with react

**Comment by nodefish** [comment]
I've got the same issue as well on iOS with Onsen UI + Cordova and using riot.js for data binding the `value` attribute.

Updating the `value` attribute programmatically doesn't update the display. For example, if the initial value is empty, and later it's set to `'1990-01-01'`, the date displayed remains empty. If we explore the DOM, we see that the `value` attribute was indeed updated.

When the user taps on the date `input` after it has been updated (even though it's displaying stale data), the iOS native date picker is set to the correct (updated) date.

**Comment by JoshuaASmith** [comment]
Also having this issue...

**Comment by slash-84** [comment]
I have the same problem:

`<input>` is working correctly whilte `<ons.input>` doesn't get the initial date value.

I'm on React, so i'm using `<Input>`, but i think the bug is the same.

**Comment by Ziggoto** [comment]
I'm with same problem on React

**Comment by misterjunio** [comment]
@Ziggoto which versions of `onsenui` and `react-onsenui` are you using? I remembered I fixed it in #1918, released on `onsenui@2.2.4` and `react-onsenui@1.3.0`. I tried again now and it seems to be working, can you provide an example where it doesn't?
