### ISSUE TITLE
Splitter collapse="portrait" not working correctly

### ISSUE THREAD

**Issue by ThomasLochbrunner** [OnsenUI/OnsenUI#1605]
__Environment__
Onsen 2.0
Angular 1.5.2
Firefox 49.0
Chrome 53.0.2785.116

__Encountered problem__
If the Splitter Side Component is configured to collapse only in portrait mode (`collapse="portrait"`) and the app is opened/started in landscape mode, then the splitter side component is not shown and can not be opened until you switch to portrait mode.

__How to reproduce__
See codepen:
https://codepen.io/anon/pen/BLROVo?&editors=101
(this is simply the Side Menu example where the collapse-attribute of the side component is set to `portrait`.

**Comment by Z6P0** [comment]
I have the same bug when I use a media query, for example `collapse="(max-width: 400px)"`

**Comment by argelius** [comment]
This has been fixed now.
