### ISSUE TITLE
ons-dialog angular variable is not rendered at first call

### ISSUE THREAD

**Issue by ctc** [OnsenUI/OnsenUI#1609]
Environment
Onsen 2
Angular 1.5.5
Newest Version of Chrome

Sample:
https://codepen.io/anon/pen/BLdAvV?&editors=101
Sample is based at: https://onsen.io/tutorial/?framework=angular1&category=Reference&module=dialog

Click at "From template"

First call: {{variable}} is not filled with value
2nd call: {{variable}} is replaced with "value"

**Comment by argelius** [comment]
@ctc Thanks for reporting!

This has been fixed now and will be released with the next version. In the meanwhile you can just do something like `$scope.$evalAsync()` after creating the dialog to refresh the view.
