### ISSUE TITLE
ons.confirm design issue on Android

### ISSUE THREAD

**Issue by HugoGiraudel** [OnsenUI/OnsenUI#1616]
__Environment__
Onsen 2

__Encountered problem__
The buttons on the dialog opened by `ons.confirm` look broken on Android.

<img width="571" alt="screen shot 2016-10-07 at 11 53 52" src="https://cloud.githubusercontent.com/assets/1889710/19186410/6f5dc554-8c86-11e6-8717-47699b9eba47.png">

__How to reproduce__
1. Go to https://onsen.io/v2/docs/js/ons.notification.html.
2. Click on “Android view”.
3. Click on “Confirm”.

**Comment by frankdiox** [comment]
@HugoGiraudel Thanks for reporting. This was already fixed in https://github.com/OnsenUI/OnsenUI/pull/1596
It will be released in `2.0.1`, probably next week.
