### ISSUE TITLE
ons-splitter has not methods or properties in angular2

### ISSUE THREAD

**Issue by gotenxds** [OnsenUI/OnsenUI#1618]
ons-splitter and ons-splitter-center/side does not have the properties or methods described in the docs
such as
left,right
or toggle().

**Comment by frankdiox** [comment]
@gotenxds I guess you are trying to call methods from the directive instead of the native element. Can you [have a look at this](https://onsen.io/v2/docs/guide/angular2/#calling-components-during-initialization) and try again?

**Comment by argelius** [comment]
I will close this for now. Please feel free to open this again if this is still an issue.
