### ISSUE TITLE
Angular2 directives methods and docs.

### ISSUE THREAD

**Issue by frandiox** [OnsenUI/OnsenUI#1619]
@anatoo @asial-matagawa @argelius 

A couple of things about Angular2 bindings:
- We have an `element` getter that returns `this._elementRef.nativeElement`. However, when using `@ViewChild` we must use `nativeElement` syntax directly. I know both cases are different but it feels a bit confusing for me. It's just my opinion but if it's possible, can't we make a `nativeElement` getter for the first case?
- Some directives have methods like `ons-lazy-repeat`'s `refresh()`. This method is used with `this.lazyRepeat.refresh()`. However, other directives uses the native element methods: `this.navigator.element.pushPage()`, or `this.carousel.nativeElement.prev()`. These differences are not described in the reference page. I guess this could also be confusing.

What do you think?

Edit: By the way, here 3fc9873abd17603af6cd1f8cd77edd069ef4ff24 I removed docs from the directive method because the result was 2 different `refresh` methods in the website and the one from the directive had no description (I guess `@desc` should be `@description`). In any case, I think this should replace the method from the core instead of taking both of them and show some kind of message explaining it's a directive method?

**Comment by anatoo** [comment]
@fran What you're saying is reasonable. Let me think about it for a while.

**Comment by argelius** [comment]
@anatoo Maybe we can map the element methods to component methods like we do in Angular 1.

**Comment by frankdiox** [comment]
@anatoo @asial-matagawa Related to this issue, there are other problems in [docs like `pushPage`](https://onsen.io/v2/docs/angular2/ons-navigator.html#method-pushPage). It says `page`, `options.page` or `options.pageHTML` are `string` and say to use `ons-template`. This is directly taken from the core library so I think it should be overwritten by Angular2 docs.

**Comment by asial-matagawa** [comment]
@frankdiox 
Thank you for reporting. I have added an entry to our TODO list.

**Comment by puku0x** [comment]
+1
