### ISSUE TITLE
Event leak in the resetToPage().

### ISSUE THREAD

**Issue by pinpikokun** [OnsenUI/OnsenUI#1620]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Encountered problem__
Event leak in the resetToPage function

__How to reproduce__
http://plnkr.co/edit/XF6BbSpLOI81cQIAkSXR?p=preview
**Please check the console log.**

$destroy() does not run when run the resetToPage() in page2.
and it will continue to accumulate events.

$destroy() is run that it popPage().

**Comment by argelius** [comment]
Thanks @pinpikokun ! We will take a look at this issue.
