### ISSUE TITLE
ons-navigator nested inside ons-navigator does not expose methods/proporties

### ISSUE THREAD

**Issue by SharkChips** [OnsenUI/OnsenUI#1622]
__Environment__
Onsen 2.0.0
Vanilla JS
iOS 10.0.2 (or any other safari)
__Encountered problem__
I first nested an `ons-navigator` inside an `ons-page` inside another `ons-navigator`. After calling `outerNavi.pushPage("innerNaviPage.html");`, the inner navi cannot be manipulated. For instance, calling  `innerNavi.topPage` or `innerNavi.pushPage("otherPage");` does not work. This is broken in Safari (both iOS and macOS), but not Chrome or MS Edge.

__How to reproduce__
1. Make a `ons-navigator`
2. Make a page `innerNaviPage.html`, with another `ons-navigator` inside.
3. Push the first navi to the `innerNaviPage.html`
4. Try to interact with inner navigator by calling `innerNavi.<anything>`
5. It no worko.

**Comment by munsterlander** [comment]
Just curious, why would you nest navigators instead of just using one to push pages too?  It just feels to me like the app navigation stack is incorrect, but hey, whatever works for your app.  So, what error is generated in the console?

**Comment by SharkChips** [comment]
@munsterlander come to think of it I don't really know. Probably technical debt or some workaround or something.
Despite the reason, this issue should definately be addressed, as it is a regression beginning with v2.0.0

**Comment by munsterlander** [comment]
@SharkChips Interesting that it started in 2.0.

**Comment by SharkChips** [comment]
@munsterlander Yes, It works without issue on v2.0.0-rc.17 but is broken on v2.0.0. Looking at the changelog, it may have broken starting with v2.0.0-rc.18, as many changes to `ons-navigator` occurred during that version.

Would you mind testing it out with rc18? I do not have a mac with me at the moment

**Comment by munsterlander** [comment]
@SharkChips Interesting as I just tried it with RC.17 with the updated code I posted and it will not work as anticipated on Chrome or Mac.

**Comment by SharkChips** [comment]
@munsterlander Weird indeed....perhaps @anatoo or @argelius may be able to provide some insight?

**Comment by munsterlander** [comment]
@SharkChips I updated the codepen again to try to track down what is going on, what is very weird is that the page count increases but you lose the animation after you push to nav1.  If you reset everything and then just push to nav2, you get the animation and the count increases.  I wonder what stops that from happening.  Very weird indeed.

**Comment by argelius** [comment]
@SharkChips @munsterlander I think this works as expected. As @munsterlander mentioned IDs are unique so there should only be one element for every ID.

If you inspect the DOM, pushing to nav2 will actually push a page to the navigator that is at the bottom of the page stack since it's the first element with the `nav2` ID. That's the reason why you can't see it.

I will close this now but feel free to open if you believe it's a bug.
