### ISSUE TITLE
contenteditable can not be edited in the iOS browser.

### ISSUE THREAD

**Issue by pinpikokun** [OnsenUI/OnsenUI#1627]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
iOS

__How to reproduce__
contenteditable can not be edited in the iOS browser.
However, it seems can be avoided by stopPropagation the touchstart of onsen-ui.

Please access the following ulr in iphone browser.
[link](https://pinpikokun.github.io/)

The actual source is less than
[link](https://github.com/pinpikokun/pinpikokun.github.io/blob/master/index.html)

**Comment by pinpikokun** [comment]
Operation check the terminal
- iphone iOS9,10
- ipad iOS9,10
- safari, Chrome

**Comment by argelius** [comment]
@asial-matagawa Can you take a look at this Safari issue when you have time?

**Comment by asial-matagawa** [comment]
@argelius
I will not be busy in this week, so I will check this issue as soon as possible.

**Comment by argelius** [comment]
@asial-matagawa Thanks!

**Comment by asial-matagawa** [comment]
@pinpikokun
The problem has been fixed.
For more details, please check the PR #1646.
