### ISSUE TITLE
Toolbar transparent modifier does not work on Android

### ISSUE THREAD

**Issue by corneyl** [OnsenUI/OnsenUI#1628]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Onsen 2.0.1
React 15.3.2
React-Onsenui 1.0.1

__Encountered problem__
When the modifier `modifier="transparent"` is added to a Toolbar, the Material design look does not have a transparent toolbar, but a toolbar with the default toolbar background color.

Sometimes you want to have a toolbar with light background, e.g. used in the Gmail app for a search input:
<img src="http://i1-news.softpedia-static.com/images/news2/google-promises-faster-answers-for-inbox-by-gmail-app-499459-3.jpg" width="300">

__How to reproduce__
[](If possible provide a working example where the issue is reproduced. For this, go to http://tutorial.onsen.io/ , select a framework and a template and modify or replace it. This will use the latest Onsen UI version released. After you finish, click 'Export to Codepen' button, save it and link it here.)
I used a regular Toolbar with the modifier, e.g.:
```
import React from 'react';
import * as Ons from 'react-onsenui';

<Ons.Toolbar modifier="transparent">
    <div className='left'>
        <Ons.BackButton>
            Back
        </Ons.BackButton>
    </div>
    <div className="center">
        Search
    </div>
</Ons.Toolbar>
```

**Comment by frankdiox** [comment]
@corneyl Thanks for reporting. `material` modifier was overwriting `transparent` modifier, we just fixed that. However, I don't think `transparent` modifier is what you are looking for. It sets the background to transparent but it also removes the box-shadow. And the toolbar-buttons are white by default you you wouldn't see anything. I think this modifier is only useful if you want to have an image as the page background, [like this](https://raw.githubusercontent.com/florent37/MaterialViewPager/master/screenshots/screenshot_2_small.png).

For your case you can modify the stylus files or just apply some custom CSS in your app:

```
  .navigation-bar--material {
    background-color: #fff;
  }
  .back-button--material,
  .toolbar-button--material,
  .navigation-bar--material__left,
  .navigation-bar--material__center,
  .navigation-bar--material__right {
    color: #888;
  }
  .toolbar-button--material:active,
  .back-button--material:active{
    background-color: rgba(200,200,200,0.15);
  }
```

Something like that should work.

**Comment by corneyl** [comment]
Thanks for the explanation and the fix! 
I indeed got it working with some custom css, though it still might be an idea to add a modifier for a toolbar with white background.
