### ISSUE TITLE
onsenui + jquery: different dom behaviour with ons-page and ons-tabbar

### ISSUE THREAD

**Issue by bdedardel** [OnsenUI/OnsenUI#1629]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Onsen 2.0.1
Angular 1.5.8
Linux / Firefox

Hi,

I've prepared some examples with some issues I 've encountered.
This one has blocked my current development and I don't know how to bypass it.

I have different behaviour since I use ons-tabbar.

- with ons-page, I could modify dom with jquery, for example:

```
$('#mydiv').html('<div>TEST</div>');
```

- but with ons-tabbar, it doesnot work.

 

__Encountered problem__

__How to reproduce__
I put an example in my github repo:

[bdedardel/cordova-test/tree/master/onsenui/bug1629](https://github.com/bdedardel/cordova-test/tree/master/onsenui/bug1629)

**Comment by argelius** [comment]
Thanks for reporting @bdedardel ! I will take a look at this now.

**Comment by argelius** [comment]
@bdedardel I think this is related to this: https://github.com/OnsenUI/OnsenUI/issues/1584

This has been fixed in this PR: https://github.com/OnsenUI/OnsenUI/pull/1634

Hopefully we can merge and release this pretty soon.

**Comment by bdedardel** [comment]
Resolution confirmed with onsenui 2.0.5.
It was my mistake by imbricating *ons-template* inside *ons-template*!

```
<ons-template id="show-onstabbar.html">
	<ons-page ng-controller="MyModelController as mymodelCtl"
		id="showonstabbar-page">
		<form id="showonstabbar-form" name="showonstabbarForm" class="onstabbar-form"><!-- 
				novalidate="true" -->
			<!-- ===== begin toolbar: show-onstabbar ===== -->
			<ons-toolbar id="show-onstabbar-toolbar" style="background-color:#333;">
				...
			</ons-toolbar><!-- end toolbar: show-onstabbar -->
			<!-- ===== begin tabbar: show-onstabbar ===== -->

<ons-template id="tab-form.html">
	<ons-page id="tab-form-page">
		...
	</ons-page>
</ons-template>

			<ons-tabbar id="show-onstabbar-tabbar" position="top">
				<ons-tab label="FORM" page="tab-form.html" active="true"
					style="background-color:#333;">
				</ons-tab>
			</ons-tabbar><!-- end tabbar: show-onstabbar -->
		</form>
	</ons-page>
</ons-template>
```

instead of:

```
<ons-template id="tab-form.html">
	<ons-page id="tab-form-page">
		...
	</ons-page>
</ons-template>

<ons-template id="show-onstabbar.html">
	<ons-page ng-controller="MyModelController as mymodelCtl"
		id="showonstabbar-page">
		<form id="showonstabbar-form" name="showonstabbarForm" class="onstabbar-form"><!-- 
				novalidate="true" -->
			<!-- ===== begin toolbar: show-onstabbar ===== -->
			<ons-toolbar id="show-onstabbar-toolbar" style="background-color:#333;">
				...
			</ons-toolbar><!-- end toolbar: show-onstabbar -->
			<!-- ===== begin tabbar: show-onstabbar ===== -->

			<ons-tabbar id="show-onstabbar-tabbar" position="top">
				<ons-tab label="FORM" page="tab-form.html" active="true"
					style="background-color:#333;">
				</ons-tab>
			</ons-tabbar><!-- end tabbar: show-onstabbar -->
		</form>
	</ons-page>
</ons-template>
```

**Comment by asial-matagawa** [comment]
@bdedardel 
Thank you for reporting.
I think Onsen UI should report an error in such situations, so I would like to implement something like it in the future.
