### ISSUE TITLE
form hidden by toolbar 

### ISSUE THREAD

**Issue by bdedardel** [OnsenUI/OnsenUI#1630]
[](Github issues should be used only for bugs and feature requests. For questions please visit https://stackoverflow.com/tags/onsen-ui or https://community.onsen.io. For bugs please use the following template.)

__Environment__
Onsen 2.0.1
Angular 1.5.8
Linux / Firefox

__Encountered problem__

- if ons-toolbar is inside form, form is hidden by toolbar

```
<ons-template>
	<ons-page>
		<form>
			<ons-toolbar>
				<!-- ... -->
			</ons-toolbar>
			<!-- ... -->
		</form>
	</ons-page>
</ons-template>
```

- if ons-toolbar is over form, form is displayed well

```
<ons-template>
	<ons-page>
		<ons-toolbar>
			<!-- ... -->
		</ons-toolbar>
		<form>
			<!-- ... -->
		</form>
	</ons-page>
</ons-template>
```

__How to reproduce__

I put an example in my github repo:

[bdedardel/cordova-test/tree/master/onsenui/bug1630](https://github.com/bdedardel/cordova-test/tree/master/onsenui/bug1630)

**Comment by frankdiox** [comment]
@bdedardel Hey, thanks for reporting! Internally `ons-toolbar` is moved around to fix scolling issues. Basically, the final structure is like this:

```
<ons-page>
  <ons-toolbar>...</ons-toolbar>

  <div class="page__content">
     form
     ...
  </div>
</ons-page>
```

The toolbar must be separated from the content. Closing this now since there's nothing to fix :)
