### ISSUE TITLE
ion icons are misaligned in Android toolbar

### ISSUE THREAD

**Issue by rancor1223** [OnsenUI/OnsenUI#1636]
__Environment__
Onsen 2.0.1
Android

__Encountered problem__
_ion icons_ are misaligned in the toolbar (and maybe elsewhere?) when using Android.

```
.ons-icon--ion {
    line-height: 0.75em;
    vertical-align: -25%;
}
```

Problem is the `vertical-align: -25%;`, which is supposed to center it vertically. It does so on iOS, but it misaligns it on Android.

__How to reproduce__
I [wasn't able to reproduce this in a CodePen](https://codepen.io/anon/pen/NRLBKa) as it doesn't let me change platform to Android. However, it's possible to reproduce it in the [Onsen Tutorial Environment](http://tutorial.onsen.io), so you can just paste it there and change the platform to Android.

**Comment by argelius** [comment]
@rancor1223 Thanks for reporting!

I will take a look at this issue.
