### ISSUE TITLE
ons-toolbar come to follow in the ons-pull-hook in the iOS of safari

### ISSUE THREAD

**Issue by pinpikokun** [OnsenUI/OnsenUI#1637]
**Environment**
iOS 9, 10
safari

**Encountered problem**
ons-toolbar come to follow in the ons-pull-hook in the iOS of safari

**How to reproduce**
Please access the iPhone safari to the following url.
The list pull Then toolber will to follow.

**preview**
[link](https://pinpikokun.github.io/index2.html)

**source**
[link](https://github.com/pinpikokun/pinpikokun.github.io/blob/master/index2.html)

**Comment by argelius** [comment]
@pinpikokun Thanks for reporting! We will take a look at this

@asial-matagawa Can you take a look at this iOS issue?
