### ISSUE TITLE
Notification prompt tenacious selection markers

### ISSUE THREAD

**Issue by Wieltje** [OnsenUI/OnsenUI#1644]
**Environment**
Onsen 2.01 + fix from issue #1638
Cordova
Android 5.01 + 6.01

**Encountered problem**
I'm using ons.notification.prompt with cancelable = true. When I select text in the prompt textinput and then cancel the notification by pressing the backbutton, the selection markers maintain in view:

![](https://cloud.githubusercontent.com/assets/22632746/19471274/c3ca7912-9522-11e6-9995-9e2e1f2026fc.png)

**How to reproduce**
Using [this code](https://codepen.io/anon/pen/NREKmb?) in a cordova app.

As long as the page does not overflow, the problem exists. After filling the div so that the page overflows, problem is gone.

**Question**
Can anyone confirm or refute that this is an onsen bug or an android bug?

**Comment by argelius** [comment]
Thank you, @Wieltje!

I will try to reproduce this but haven't been successful yet.
