### ISSUE TITLE
Uncaught DOMException: Failed to execute 'createElement' on 'Document': The result must not have attributes(…)

### ISSUE THREAD

**Issue by copleykj** [OnsenUI/OnsenUI#1645]
After the most recent Chrome update I'm getting this issue. This seems to be an issue with Custom Elements, but thought you guys should be aware so that as it gets patched you can update things. The error comes from this line [here](https://github.com/OnsenUI/OnsenUI/blob/353a3e13185978a634595d64cf2136a6c5216f60/core/vendor/document-register-element.max.js#L1013).

__Environment__
Onsen 2
React 15
Linux Mint 17, Chrome 54.0.2840.71 (64-bit)

__Encountered problem__

__How to reproduce__
[](If possible provide a working example where the issue is reproduced. For this, go to http://tutorial.onsen.io/ , select a framework and a template and modify or replace it. This will use the latest Onsen UI version released. After you finish, click 'Export to Codepen' button, save it and link it here.)

**Comment by asial-matagawa** [comment]
@copleykj 
Thank you for reporting!

We have already known the issue and we fixed it in Onsen UI 2.0.1.
If you use Onsen UI 2.0.0, could you try to replace 2.0.0 with 2.0.1?
We would appreciate if you could send the result on 2.0.1.
