### ISSUE TITLE
ons-navigator pushPage(): page.data and page.name are not available on page init event

### ISSUE THREAD

**Issue by frosdqy** [OnsenUI/OnsenUI#1649]
__Environment__
Onsen 2.0.2
Chrome 54

__Encountered problem__
Using the pushPage() method of ons-navigator, page.data and page.name are not available on page init event.

__How to reproduce__
Try with this tutorial:
https://tutorial.onsen.io/?framework=vanilla&category=Reference&module=navigator
Click the 'Push Page' button.
Title is not showing on Page 2.
Error in console: Uncaught TypeError: Cannot read property 'title' of undefined

**Comment by frankdiox** [comment]
@frosdqy Thanks for reporting. It's been fixed already and will be available for 2.0.3.

If you want to use 2.0.2 I think you can just wrap your `init` code in a timeout:

```
document.addEventListener('init', function(event) {
  setTimeout(function() {
    event.page.data
  }, 0);
});
```
