### ISSUE TITLE
ons-toolbar no longer gets hoisted

### ISSUE THREAD

**Issue by nodefish** [OnsenUI/OnsenUI#1651]
**Environment**
Onsen 2.0.2
Chrome, iOS 9.2

**Encountered problem**

I was previously using an older build (RC.12) and was benefiting from `ons-toolbar` hoisting, meaning that if I insert a `ons-toolbar` inside a `ons-page`, the `ons-toolbar` was automatically moved to the first position compared to its siblings. This has changed in 2.0.2.

Page content (in my case, I'm generating this content dynamically):

```
<ons-page>
    <wrapper>
        <ons-toolbar>toolbar items</ons-toolbar>
        <div id="c1"> content here </div>
    </wrapper>
</ons-page>
```

The `wrapper` is actually a custom tag (riot.js, same concept as with React). So I attach this custom element (`wrapper` tag) to the DOM and push the page into the navigator.

_Onsen UI RC.12 output:_

```
<ons-page>
    <ons-toolbar>toolbar items</ons-toolbar>
    <div class="page__background"></div>
    <div class="page__content">
        <wrapper>
            <div id="c1">content here</div>
        </wrapper>
    </div>
</ons-page>
```

(The toolbar is hoisted)

_Onsen UI 2.0.2 output:_

```
<ons-page>
    <div class="page__background"></div>
    <div class="page__content">
        <wrapper>
        <ons-toolbar>toolbar items</ons-toolbar>
            <div id="c1">content here</div>
        </wrapper>
    </div>
</ons-page>
```

(the toolbar is no longer hoisted)

I know this isn't a bug per se, but I feel like the hoisting made it much easier to generate the entire page dynamically and then just attach it into `<ons-template>`, and navigate to it. Was this regression intentional?

**Comment by argelius** [comment]
@nodefish The toolbar is still supposed to be hoisted so I don't really know what is going on here. Maybe it's because how riot is rendering the HTML.

You can try rendering the toolbar with the `.page__background` and `.page__content` instead of letting Onsen do it. Onsen will only create those elements if they don't already exist.

**Comment by frankdiox** [comment]
@nodefish @argelius Actually this behavior changed somewhere during RC. Some versions ago everything was wrapped inside `page__content` and the toolbar was hoisted. That was kind of absurd because the toolbar was moved twice when it could just remain on its original position. That's basically the change, the toolbar and other elements like `ons-fab`, `ons-modal`, etc. don't move from the original position.

So yeah, it should only be wrapped by `ons-page`, nothing else :/

```
<ons-page>
  <ons-toolbar></ons-toolbar>
  <div class="content">
     This will become ".page__content"
  </div>
</ons-page>
```

**Comment by nodefish** [comment]
> You can try rendering the toolbar with the .page__background and .page__content instead of letting Onsen do it. Onsen will only create those elements if they don't already exist.

This solution works, combined with making riot push the tag contents directly into the ons-page and thus excluding the wrapper. I have to admit I kind of liked the hoisting (reminds me a bit of how React Native treats statusbars nested at depth>0), but this works just fine. :)

Is it safe in the long run to generate `div.page__background` and `div.page__content` or can I expect this to break at some point?

**Comment by argelius** [comment]
@nodefish The DOM structure of the page will not change so you can safely render the elements like this.

We will investigate why the hoisting broke in this case. We changed how it works to make it more efficient but it looks like the change broke something in your case.

**Comment by nodefish** [comment]
@argelius Understood. Based on the answer @frankdiox, this seems like it may be an intentional design decision.

**Comment by frandiox** [comment]
As explained in previous answers, this is now the correct behavior. Elements like Toolbar, Fab, etc. are not moved from its original position (so there's no need for hoisting them afterward). Page's content div can be created beforehand with `.page__content` class or simply `.content` (the other class will be added automatically).
