### ISSUE TITLE
ons-input select bug

### ISSUE THREAD

**Issue by milanjaros** [OnsenUI/OnsenUI#1653]
**Environment**
Onsen 2.0.0
React Onsen 1.0.0
Firefox 49.0.2

**Encountered problem**
It is not possible to select text in the input box in the latest Firefox.

Firefox 47 was okay. Possible cause: "-webkit-user-select" on input.

**How to reproduce**
1. Visit https://onsen.io/v2/docs/react/Input.html in Firefox 49.
2. Type "Text" into form input (e.g. User name).
3. Select text using mouse. (BUG)
4. Select text using Shift+arrows. (BUG)

**Comment by argelius** [comment]
Thanks for reporting @milanjaros !
