### ISSUE TITLE
ons-tab defaults to ion-cloud icon after pushPage()

### ISSUE THREAD

**Issue by vjoomens** [OnsenUI/OnsenUI#1654]
**Environment**
Onsen 2.0.3
Angular 1.5.8
Safari, iOS

**Encountered problem**
When using an ons-tabbar and ons-tab elements in a template which opens after a navigator pushPage, all icons default to ion-cloud.

**How to reproduce**
Please check enclosed example
[Archief.zip](https://github.com/OnsenUI/OnsenUI/files/552971/Archief.zip)

I've added a pen: https://codepen.io/vjoomens/details/JRVbZR/
.

**Comment by argelius** [comment]
@vjoomens I have verified this issue, it looks like it only happens in Safari.

@anatoo Can you take a look at this issue when you have time?

**Comment by anatoo** [comment]
@vjoomens @argelius Ok, I'm going to fix this problem.

**Comment by Henry0126** [comment]
Recently, I upgrade onsenui from 2.4.0 to 2.7.1,this problem happens again and not in Safari, the error print:"icon.attributeChangedCallback is not a function"
