### ISSUE TITLE
Error opening Popover

### ISSUE THREAD

**Issue by rgins16** [OnsenUI/OnsenUI#1655]
__Environment__
Onsen 2 v2.0.3
Angular 1.5.8
Chrome latest version

__Encountered problem__

I am receiving this error in the terminal when trying to open a popover

![image](https://cloud.githubusercontent.com/assets/16677164/19731582/e0b9c98e-9b6b-11e6-9c83-071b77e3d428.png)

__How to reproduce__
![image](https://cloud.githubusercontent.com/assets/16677164/19731618/046c69ae-9b6c-11e6-81e9-92d022a00c70.png)

**Comment by argelius** [comment]
@rgins16 The popover needs a `target` attribute for the `show(target)` method.

I have improved the error message to make it more clear.
