### ISSUE TITLE
ons-switch not emitting changes

### ISSUE THREAD

**Issue by milkisevil** [OnsenUI/OnsenUI#1663]
**Environment**
Onsen 2.0.3
angular2-onsenui: 1.0.0-rc.1
Angular 2.0.0

ALSO Code Example on: https://onsen.io/v2/docs/angular2/ons-switch.html

**Encountered problem**
`ons-switch` doesn't emit changes. 

**How to reproduce**
1. Go to https://onsen.io/v2/docs/angular2/ons-switch.html
2. Click the switch
3. Notice how the checkbox state isn't updated

💡  Please also consider writing unit tests to test angular all bindings before release.

**Comment by argelius** [comment]
@milkisevil Thanks for reporting. This has been fixed.

I have also added tests and we will add more tests for the Angular 2 bindings.
