### ISSUE TITLE
Onsen with Angular1 ons-splitter-side event attributes don't work

### ISSUE THREAD

**Issue by toramanlis** [OnsenUI/OnsenUI#1677]
__Environment__
Onsen 2.0.3
Angular 1.5.8
Firefox, Chrome and probably other browsers

__Encountered problem__

When you add one of the `ons-<event-name>` attributes to the `ons-splitter-side`, it doesn't run the code in it. Nothing happens and causes no errors.

__How to reproduce__
https://codepen.io/toramanlis/pen/NbWBZY

**Comment by frankdiox** [comment]
@toramanlis Thanks for reporting!

**Comment by toramanlis** [comment]
thanks for developing onsen :)
