### ISSUE TITLE
ons-back-button onClick still pops page

### ISSUE THREAD

**Issue by Wieltje** [OnsenUI/OnsenUI#1680]
__Environment__
Onsen 2.01
Android 6.01

__Encountered problem__
I'm trying to override the onClick handler of ons-back-button. According to [documentation](https://onsen.io/v2/docs/js/ons-back-button.html), no page should be popped in navigator when overriding the button. This does not work as documented: the given onclick function is called properly, but afterwards there's still a page being popped in the navigator.

__How to reproduce__
See [this codepen](https://codepen.io/Wheelie/pen/Wobqgj?&editors=101)

__Question__
If this is a bug, I'd love to see it fixed.
If this is a feature, documentation should be changed and I'd love to get a hint how to get the desired behaviour (using a custom function for a ons-back-button without popping a page in navigator).

**Comment by frankdiox** [comment]
@Wieltje It's a property, not an attribute:

```
    document.querySelector('ons-back-button').onClick = function() {
      alert('onClick event overridden');
    };
```

@argelius What do you think about considering `onclick` attribute as well?

**Comment by Wieltje** [comment]
Thank you! I didn't knew about any significant difference between <ons-back-button onclick=x()> and document.querySelector('ons-back-button').onClick = x;

Would be nice if both methods would lead to the same result I think.

**Comment by argelius** [comment]
I don't think we should encourage adding event handlers as attributes.
