### ISSUE TITLE
Why there are no button groups in second version of OnsenUi - React?

### ISSUE THREAD

**Issue by botezatpv** [OnsenUI/OnsenUI#1681]
__React__
Onsen 2 beta 
__Encountered problem__
Why there are no button groups in react? How can they be implemented and do I have to w8 them?

**Comment by argelius** [comment]
@botezatpv Hi!

There is a "segment" component. You can find it on this page:
http://components.onsen.io/

We are not planning to make it into a Web Component at this time so I will close this issue.

**Comment by markhats** [comment]
Seems like a good candidate for a web component (with also Material version). Any reason for it not being considered?
