### ISSUE TITLE
Support for a React <select> component

### ISSUE THREAD

**Issue by robcaldecott** [OnsenUI/OnsenUI#1684]
I am using Onsen and React and I love it. But I desperately need a <select> component. Are there any plans to add one? Or does anyone know of one that I can use?

**Comment by argelius** [comment]
@robcaldecott We don't have it at this time but we are planning to add it.

Maybe you can use this one: https://github.com/JedWatson/react-select

**Comment by robcaldecott** [comment]
Thanks for such a prompt reply. I would be fine with a native select, I just need to style it to look more like an input. Perhaps I can achieve this with some Onsen CSS. I'll experiment but it's good to know you have plans for this.

**Comment by argelius** [comment]
@robcaldecott Yes, we would probably style a native select since the user would get nice behavior on iOS and Android devices.

**Comment by argelius** [comment]
We are planning on adding an `<ons-select>` element to the core so I will close this issue.

**Comment by lyf1988** [comment]
@argelius Thank you for your suggestion. 

It looks like react-onsenui and newest react-select does not working well.
I am now using "react-onsenui": "^1.3.4" with "react-select": "^0.9.1". 
The select operation mostly works fine.

But when I try to upgrade react-select to 1.0.0-rc-5(newest) it seems touch select and mouse select no longer working. Using arrow key and enter key to select option works fine.

Below is the basic code I tried
```
<Ons.Page>
<Select 
  ref="stateSelect" 
  autofocus 
  options={options} 
  simpleValue 
  clearable={this.state.clearable} 
  name="selected-state" 
  disabled={this.state.disabled} 
  value={this.state.selectValue} 
  onChange={this.updateValue} 
  searchable={this.state.searchable} />
</Ons.Page>
```

Any idea why?

**Comment by misterjunio** [comment]
@lyf1988 while I can't tell why `react-select` is not working properly maybe I can suggest you use Onsen UI's select? It has been added in `react-onsenui@1.2.0`
