### ISSUE TITLE
Carousel not working with knockoutjs

### ISSUE THREAD

**Issue by paulg446** [OnsenUI/OnsenUI#1686]
ons-carousel works with knockoutjs (albeit not well) with onsen v 2.0.2, but not at all with v 2.0.3 and 2.0.4 (the latest release).  With v2.0.2, on instantiating a knockout model with an observableArray, binding elements of the array to new ons-carousel-items works, but adding a new element to the array (using the example, click the "Carousel" label in the toolbar) results in a new ons-carousel-item, but it doesn't render properly.  Similar behaviour with ons-list (and ons-list-items) works as expected.

Demo here: https://codepen.io/anon/pen/ZBbXXz?&editors=101

**Comment by frankdiox** [comment]
@paulg446 The item is added but the styles are not correct. Simply call carousel's `refresh()` method after adding an element to fix that. For example: `document.querySelector('ons-carousel').refresh();`.

**Comment by paulg446** [comment]
@frankdiox thanks, that works. I assumed that ons-carousel would work in the same way as ons-list (with regard to dynamically generated items), but you know what they say about assumptions. By the way, great work you're all doing with Onsen!
