### ISSUE TITLE
Failed to execute 'setAttribute' on 'Element': ';' is not a valid attribute name.

### ISSUE THREAD

**Issue by shoobm** [OnsenUI/OnsenUI#169]
Hi, I'm using Onsen 1.0.4 and it seems that angular is not loading properly.
It generates following error at angular.js:9400
`Error: Failed to execute 'setAttribute' on 'Element': ';' is not a valid attribute name.
at Error (native)
at n.extend.attr (http://localhost:8000/app/js/jquery-2.1.1.min.js:3:32015)
at n.access (http://localhost:8000/app/js/jquery-2.1.1.min.js:2:30155)
at n.fn.extend.attr (http://localhost:8000/app/js/jquery-2.1.1.min.js:3:31538)
at Object.Attributes.$set (http://localhost:8000/app/lib/onsen/js/angular/angular.js:5434:28)
at http://localhost:8000/app/lib/onsen/js/angular/angular.js:6314:15
at forEach (http://localhost:8000/app/lib/onsen/js/angular/angular.js:310:20)
at mergeTemplateAttributes (http://localhost:8000/app/lib/onsen/js/angular/angular.js:6309:7)
at http://localhost:8000/app/lib/onsen/js/angular/angular.js:6378:13
at http://localhost:8000/app/lib/onsen/js/angular/angular.js:7559:11`

Also, i'm confused what is to be used for referencing the scope: $scope or $rootScope?

**Comment by edukni** [comment]
Same to me, thank you! Verify your .html .

**Comment by MiguelGonzalezAravena** [comment]
This happen to me, and was because i has a # like attribute without a name.

**Comment by ibrahimmahjoubi** [comment]
same thing to me but with an ')'
'setAttribute' on 'Element': ')' is not a valid attribute name.

**Comment by totalknowledge** [comment]
Seems pretty serious for something the browser is going to ignore.

**Comment by JimmyTheNerd** [comment]
Thanks @shoobm. I probably confused HTML with JS (see end of line 2). ;-)

```
<my-component
    attribute1="foo";
    attribute2="bar"></my-component>
```

**Comment by agm1984** [comment]
Lol, oops, I just generated this error by putting the `="blah"` part inside the `]`

**Incorrect**
`[(ngModel)="serverName"]`

**Correct**
`[(ngModel)]="serverName"`

**Comment by hemantshelar** [comment]
Thanks @shoobm 
This happens to me when I accidentally placed ','

app-cockpit
    (serverCreated)="onServerAdded($event)" **,** 
    (bluePrintCreaed)="onBlueprintAdded($event)"

  ></app-cockpit>
