### ISSUE TITLE
Close carousel on overlay click

### ISSUE THREAD

**Issue by JulianKingman** [OnsenUI/OnsenUI#1693]
__Environment__
Onsen 2.0.1
React 15.3.2
iOS/Web/Android

__Encountered problem__
When I click the overlay, I would expect it to close, or at least to have an option to close it, as the modal does.

**Comment by munsterlander** [comment]
What do you mean by overlay?  Are you doing a modal over the carousel or a dialog with the carousel?  Can you post a codepen with what is occuring?

**Comment by JulianKingman** [comment]
Ah yes, my bad, the carousel is inside a modal, so I just need to pass the right prop in there.
