### ISSUE TITLE
popPage does not work

### ISSUE THREAD

**Issue by josekenya** [OnsenUI/OnsenUI#1694]
Whenever i use popPage() with {refresh:true} option i get an error.
In my case i am injecting item dynamically to the dom.
I have a page to add items from where i save the items on localstorage then display them on the previous page.It is on this page that i apply the popPage().
On first attempt it work fine,however with subsequent popPage()  it gives the error.

What am i doing wrong.Here is the code:

page.querySelector('#save').onclick = function() {
	        var newTitle = page.querySelector('#title-input').value;
            
	        if (newTitle) {
	         var newTask=[];
             var items={
			              title: newTitle,
			              time: page.querySelector('#time-input').value,
			              date: page.querySelector('#date-input').value,
			              description: page.querySelector('#description-input').value,
			              done:false
	                    };
	        if(storage.isSet('tasks'))
	        {
	        	var localstorage_items=storage.get('tasks');
	        	localstorage_items.push(items);
	            storage.set('tasks',localstorage_items);
	            
	            document.querySelector('#myNavigator').popPage({refresh:true});

	        }
	        else
	        {
	        	//add items to array
	        	newTask.push(items)
	        	storage.set('tasks',newTask);

	        	document.querySelector('#myNavigator').popPage({refresh:true});
	        	//document.querySelector('#myNavigator').refresh=true;
	        }

	        } else {
	          // Show alert if the input title is empty.
	          ons.notification.alert({title:"Error",message:"You must provide a task title."});
	        }
	      }

**Comment by expertsa** [comment]
Just rewriting your exemple for more visibility

```js
page.querySelector('#save').onclick = function() {

   var newTitle = page.querySelector('#title-input').value;

   if (newTitle) {

         var newTask = [];
         var items = {
		   title: newTitle,
		   time: page.querySelector('#time-input').value,
		   date: page.querySelector('#date-input').value,
		   description: page.querySelector('#description-input').value,
		   done: false
        };

        if (storage.isSet('tasks')) {

              var localstorage_items = storage.get('tasks');
              localstorage_items.push(items);
              storage.set('tasks', localstorage_items);
              document.querySelector('#myNavigator').popPage({refresh: true});

        } else {

              //add items to array
              newTask.push(items)
              storage.set('tasks', newTask);
              document.querySelector('#myNavigator').popPage({refresh: true});
              //document.querySelector('#myNavigator').refresh = true;

        }

   } else {

        // Show alert if the input title is empty.
        ons.notification.alert({title: "Error", message: "You must provide a task title."});

   }
}

popPage means you go back to the previous page in the stack, so in order to work you need to have pages in the stack. You need to pushPage at some point.

**Comment by munsterlander** [comment]
@josekenya I am confused as to what is not working.  Here is a working example with dynamic data.  https://codepen.io/anon/pen/KNMVJm  If you push the page and then use the back button, you will see the time does not change.  If you push the page again and then pop the page, you will see the data is refreshed.

**Comment by josekenya** [comment]
@munsterlander @expertsa 
Let me list everything concisely.

**HTML Pages**
**index.html**
<!DOCTYPE HTML>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <meta http-equiv="Content-Security-Policy" content="default-src * data:; style-src * 'unsafe-inline'; script-src * 'unsafe-inline' 'unsafe-eval'">
    <script src="components/loader.js"></script>
    <script src="lib/onsenui/js/onsenui.min.js"></script>
    <script src="lib/jquery/jquery-3.1.0.min.js"></script>
       <script src="lib/jquery/storageApi.js"></script>

    <link rel="stylesheet" href="components/loader.css">
    <link rel="stylesheet" href="lib/onsenui/css/onsenui.css">
    <link rel="stylesheet" href="lib/onsenui/css/onsen-css-components.css">
    <link rel="stylesheet" href="css/style.css">
    <script type="text/javascript" src="js/app.js"></script>
    <script type="text/javascript" src="js/controller.js"></script>
    <script type="text/javascript" src="js/service.js"></script>
</head>
<body>
     <ons-navigator id="myNavigator" animation="slide" page="home-tabs.html" ></ons-navigator>
</body>
</html>

**home-tabs.html**
<ons-page id="homePage">
<ons-toolbar>
    <div class="center">Elections</div>
</ons-toolbar>
<ons-tabbar position="auto" modifier="material" animation="slide">
      <ons-tab  page="html/constituencies.html">
         <ons-ripple>Sub-Counties</ons-ripple>
      </ons-tab>
      <ons-tab  page="html/schedule.html" active>
         <ons-ripple>Schedules</ons-ripple>
      </ons-tab>
      <ons-tab  page="html/results.html">
         <ons-ripple>Results</ons-ripple>
      </ons-tab>
</ons-tabbar>
<ons-fab position="bottom right" id="newSchedule">
     <ons-icon icon="md-plus"></ons-icon>
</ons-fab>
</ons-page>

**schedule.html**
<ons-page modifier="material" id="schedulePage">
	<ons-list modifier="material" class="input_list" id="scheduleList">
		
	</ons-list>
	
</ons-page>

**newSchedule.html**
<ons-page modifier="material" id="newschedulePage">
	<ons-toolbar>
		<div class="left"><ons-back-button></ons-back-button></div>
	    <div class="center">New Schedule</div>
	    <div class="right"><ons-toolbar-button id="save"><ons-icon size="30px" icon="md-save"></ons-icon></ons-toolbar-button></div>
    </ons-toolbar>
    <ons-list>
	    <ons-list-header>Add a new schedule</ons-list-header>
	    <ons-list-item modifier="nodivider">
	      <div class="center">
	        <ons-input id="title-input" type="text" placeholder="I want to..." float></ons-input>
	      </div>
	    </ons-list-item>
	    <ons-list-item modifier="nodivider">
	      <div class="center">
	        <ons-input id="time-input" type="text" placeholder="Time" float></ons-input>
	      </div>
	    </ons-list-item>
	    <ons-list-item modifier="nodivider">
	      <div class="center">
	        <ons-input id="date-input" type="text" placeholder="Date" float></ons-input>
	      </div>
	    </ons-list-item>
	    <ons-list-item modifier="nodivider">
	      <div class="center">
	        <ons-input id="description-input" type="text" placeholder="Description" float></ons-input>
	      </div>
	    </ons-list-item>
  </ons-list>
</ons-page>

**Javascript**
**app.js**
//gloabal objject
window.MAPPS={};
//create a global storage object
window.storage=$.localStorage;
//
document.addEventListener('init', function(event) {
 //even to bind to our application
  var page = event.target;
  // initialize all controller functions
  if (MAPPS.Controller.hasOwnProperty(page.id))
   {
      MAPPS.Controller[page.id](page);
   }
});

**controller.js**
MAPPS.Controller={
homePage:function(page){
       page.querySelector('#newSchedule').onclick=function()
       {
       	   document.querySelector('#myNavigator').pushPage('html/newSchedule.html',{animation:'fade'});
       }
	},
	schedulePage:function(page)
	{ 
		 console.log(document.querySelector('#myNavigator'));
		if(storage.isSet('tasks'))
		{
			var schedule=storage.get('tasks');
		    schedule.forEach(function(data,index){
				 MAPPS.Service.schedules.create(data,index);
			}); 
		}
		else
		{
			MAPPS.Service.schedules.nodata();
		}
	},
	newschedulePage:function(page){
       // Set button functionality to save a new task.
	   page.querySelector('#save').onclick = function() {
	        var newTitle = page.querySelector('#title-input').value;
            
	        if (newTitle) {
	         var newTask=[];
             var items={
			              title: newTitle,
			              time: page.querySelector('#time-input').value,
			              date: page.querySelector('#date-input').value,
			              description: page.querySelector('#description-input').value,
			              done:false
	                    };
	        if(storage.isSet('tasks'))
	        {
	        	var localstorage_items=storage.get('tasks');
	        	localstorage_items.push(items);
	            storage.set('tasks',localstorage_items);
	            
	            document.querySelector('#myNavigator').popPage({refresh:true});

	        }
	        else
	        {
	        	//add items to array
	        	newTask.push(items)
	        	storage.set('tasks',newTask);

	        	document.querySelector('#myNavigator').popPage({refresh:true});
	        	//document.querySelector('#myNavigator').refresh=true;
	        }

	        } else {
	          // Show alert if the input title is empty.
	          ons.notification.alert({title:"Error",message:"You must provide a task title."});
	        }
	      }
	}
}
**service.js**
schedules:{
       create:function(data,index){
          var ctemplate=document.createElement('div');
          //contact length
          if(data.done===true)
          {  
                ctemplate.innerHTML=
                 '<ons-list-item modifier="material" tappable>'+
                    '<div class="left">'+
                      '<ons-icon style="color:#377e27;" size="30px" icon="ion-android-checkbox"></ons-icon>'+
                    '</div>'+
                    '<div class="center">'+
                      '<div class="list__item__title list__item--material__title">'+data.title+'</div>'+
                      '<div class="list__item__subtitle list__item--material__subtitle"><ons-icon style="color:#49e10c;" icon="ion-android-calendar"></ons-icon>'+data.date+'</div>'+
                      '<div class="list__item__subtitle list__item--material__subtitle"><ons-icon style="color:#bd0404;" icon="ion-android-time"></ons-icon>'+data.time+'</div>'+
                    
                    '</div>'+
                    '<div class="right">'+
                      '<ons-icon size="30px" icon="ion-android-delete"></ons-icon>'+
                    '</div>'+
                  '</ons-list-item>';
          }
          else
          {
             ctemplate.innerHTML=
               '<ons-list-item modifier="material" tappable>'+
                  '<div class="left">'+
                    '<ons-icon style="color:#bd0d0d;" size="30px" icon="ion-ios-list-outline"></ons-icon>'+
                  '</div>'+
                  '<div class="center">'+
                    '<div class="list__item__title list__item--material__title">'+data.title+'</div>'+
                    '<div class="list__item__subtitle list__item--material__subtitle"><ons-icon style="color:#49e10c;" icon="ion-android-calendar"></ons-icon>'+data.date+'</div>'+
                    '<div class="list__item__subtitle list__item--material__subtitle"><ons-icon style="color:#bd0404;" icon="ion-android-time"></ons-icon>'+data.time+'</div>'+
                  
                  '</div>'+
                  '<div class="right">'+
                    '<ons-input type="checkbox" class="numbers" value=""></ons-input>'+
                  '</div>'+
                '</ons-list-item>';
          }
         
            var taskItem = ctemplate.firstChild;
            // Store data within the element.
            taskItem.data = data;
            //append items
            document.querySelector("#scheduleList").appendChild(taskItem);

            taskItem.querySelector('.center').onclick = function() 
            {
              document.querySelector('#myNavigator').pushPage('html/editSchedule.html',{animation:'slide',data:{elements:taskItem,idx:index}});
            } 
       },
       nodata:function(){
         var ctemplate=document.createElement('div');
         ctemplate.innerHTML='<ons-list-item modifier="material" tappable>'+
                         '<div class="center">No Items.</div>'+
                      '</ons-list-item>';
          var taskItem = ctemplate.firstChild;            
           document.querySelector("#scheduleList").appendChild(taskItem);            
       },
       add:function(){

       },
       deleteSchedule:function(){

       },
       complete:function(){

       }
    }

The issue is that whenever i add an item to the localstorage for the first time the page refresh at **schedule.html** is okay.However when i navigate to **newSchedule.html** and save another item i get this error on the console:

onsenui.min.js:4 GET http://localhost/election_new/www/undefined 404 (Not Found)
(anonymous function) @ onsenui.min.js:4
(anonymous function) @ onsenui.min.js:4
(anonymous function) @ onsenui.min.js:2runIfPresent @ onsenui.min.js:2onGlobalMessage @ onsenui.min.js:2
localhost/:1 Uncaught (in promise) <?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
<title>Object not found!</title>
<link rev="made" href="mailto:postmaster@localhost" />
<style type="text/css"><![CDATA[/*></style>
</head>

<body>
<h1>Object not found!</h1>
<p>


    The requested URL was not found on this server.

  

    The link on the
    <a href="http://localhost/election_new/www/">referring
    page</a> seems to be wrong or outdated. Please inform the author of
    <a href="http://localhost/election_new/www/">that page</a>
    about the error.

  

</p>
<p>
If you think this is a server error, please contact
the <a href="mailto:postmaster@localhost">webmaster</a>.

</p>

<h2>Error 404</h2>
<address>
  <a href="/">localhost</a><br />
  <span>Apache/2.4.12 (Win32) OpenSSL/1.0.1l PHP/5.6.8</span>
</address>
</body>
</html>

I am building the app on localhost.
Any help will be highly appreciated.

**Comment by munsterlander** [comment]
Hmm, well I would assume you have a pathing issue based on the 404 obviously.  Onsen, to my knowledge, doesn't make calls to external files after it is loaded.  My base recommendation for users new to Onsen is to develop your app like a single page web site (template tag files are really just includes, utilize AJAX processes, etc.)

I would assume based on your code that after popping, you are going back to the index.html file where the schedule.html file does not exist as it is in a different folder.  While this should not matter, I wonder if you have an empty stack once popped?  Are you removing pages prior to pushing them?

**Comment by josekenya** [comment]
Not really am simply pushing a new page then pop it.

**Comment by josekenya** [comment]
@munsterlander I have found a work around on it.I have tried what you suggested and it woks.Thanks alot.
