### ISSUE TITLE
monaca create helloworld

### ISSUE THREAD

**Issue by harshvardhan12** [OnsenUI/OnsenUI#1698]
Hi,
when i give the command monaca create helloworld
i am getting the error Error in getting project templates list: EAI_AGAIN
pls help me in this regard

**Comment by asial-matagawa** [comment]
@harshvardhan12 
Thank you for reporting!

Maybe it was a temporary problem on Monaca.
It works fine now:
![2016-11-15 20 21 44](https://cloud.githubusercontent.com/assets/19771915/20303949/287e0428-ab71-11e6-8525-957a5b5cd5df.png)

Could you try again?

**Comment by harshvardhan12** [comment]
hi thanks for your reply
i am getting this error Error in getting project templates list: ECONNRESET
i have given the proxy setting  and also npm config set registry http://registry.npmjs.org/
but still not able to create

**Comment by asial-matagawa** [comment]
@harshvardhan12 
Could you check whether your `monaca` is up-to-date or not?
The latest version is 2.1.6.
Older version may cause errors like that.

**Comment by argelius** [comment]
I will close this issue. Please open an issue in https://github.com/monaca/monaca-cli if you are still having trouble.
