### ISSUE TITLE
dynamic popover in iOS causes display bug

### ISSUE THREAD

**Issue by paulg446** [OnsenUI/OnsenUI#1699]
**Environment**
Onsen 2.0.4
ios 9.3 (mobile safari, mobile chrome, packaged cordova app)

**Encountered problem**
On creating a popover from a template (ie, using ons.createPopover()) the page temporarily resizes in an awkward way. It seems that when the popover is initially appended to the dom, it causes the page to re-scale temporarily. When the popover is eventually positioned correctly, the page returns to normal.

**How to reproduce**
https://codepen.io/anon/pen/ZBbXXz ,export, and view in iOS, either in mobile safari, chrome, or as a cordova packaged app.  Notice the rescale/flicker on clicking the "Create Popover" button.

This bug does not seem to affect android.

**Comment by nodefish** [comment]
I've experienced this too. Currently I've managed to alleviate it by doing `document.body.appendChild(popoverElement);` before calling `show()`.

**Comment by paulg446** [comment]
@nodefish thanks the tip - I'll try that
