### ISSUE TITLE
Uncaught Error: maxDistance must be greater then zero.

### ISSUE THREAD

**Issue by expertsa** [OnsenUI/OnsenUI#1713]
Hi,

I'm using **onsen UI 2.0.1** and **angular 1** binding with it.

When I start my app (mostly when it's the first time) I have this error message and my menu doesn't open. If I close my app and open it again, it works. I don't know why.

```diff
- angular-onsenui.js:3232 Uncaught Error: maxDistance must be greater then zero.
```
Comming from this : 

```js
/**
 * @param {Number} maxDistance
 */
setMaxDistance: function setMaxDistance(maxDistance) {
  if (maxDistance <= 0) {
    throw new Error('maxDistance must be greater then zero.');
  }

  if (this.isOpened()) {
    this._distance = maxDistance;
  }
  this._maxDistance = maxDistance;
},
```

This is my index.html entry file :

```html
<body>

<ons-navigator var="router" animation="none" page="app/routes/menu/menu.html"></ons-navigator>

<mail></mail>
<info-modal></info-modal>

<!-- start image cache -->
<!-- end image cache -->

</body>
```

and this is my app/routes/menu/menu.html file : 

```html
<ons-page ng-controller="MenuCtrl">
   <ons-sliding-menu id="menu" var="menu" main-page="app/routes/accueil/accueil.html" menu-page="app/routes/menu/side-menu.html"
                     max-slide-distance="80%" type="reveal" side="left">
   </ons-sliding-menu>
</ons-page>

```

**Comment by frankdiox** [comment]
@expertsa I made a small example. Can you check if [this work](https://codepen.io/frankdiox/pen/xRrQPY?&editors=101) with Onsen UI 2.0.4? If it doesn't, which device and OS version are you using?

**Comment by expertsa** [comment]
Didn't know about ons-splitter, will try on monday.
About the OS, tried on iOS 10 and android 4.4 with crosswalk 51.
