### ISSUE TITLE
Second splitter menu does not work

### ISSUE THREAD

**Issue by Z6P0** [OnsenUI/OnsenUI#1717]
__Environment__ 

```
[Core]
    Onsen UI 2.0.4

[Framework]
    None

[Framework binding]
    None

[Additional libraries]
    None

[Platform]
    Desktop - Linux

[Browser]
    Desktop - Chrome 53.0.2785.116
    Desktop - Chromium 53.0.2785.143
    Desktop - Firefox 50.0
```

__Encountered problem__

I have 2 splitter menus on left and right sides.
One is collapsed and swipeable, the other is not.
But the swipe does not work properly: the content is not grayed out, and the menu does not collapse if I tap outside.

__How to reproduce__

https://codepen.io/anon/pen/eBGgvJ

**Comment by Z6P0** [comment]
Forum discussion here: https://community.onsen.io/topic/1036/splitter-menus-bug/

**Comment by munsterlander** [comment]
I am not certain if this is doing something that Onsen was not designed for and thats why we had issues or there is just a bug.  Either way, having 2 splitter menus definitely causes some bugs.

**Comment by asial-matagawa** [comment]
@Z6P0 @munsterlander 
At least the content should be grayed out, so I consider this as a bug.
We will deal with this problem as soon as possible.

Thank you for reporting!
