### ISSUE TITLE
ng-show is called twice.

### ISSUE THREAD

**Issue by keijiodagawa** [OnsenUI/OnsenUI#1718]
__Environment__ 

```
[Core]
    Onsen UI 2.0.4

[Framework]
    Angular 1.5.8

[Framework binding]
    angular-onsenui 2.0.4

[Additional libraries]
    None

[Platform]
    All

[Browser]
    All
```

__Encountered problem__

ng-show is called twice.
I want to work ng-show only once.

__How to reproduce__

https://codepen.io/keiji/pen/MbEOVK

**Comment by frankdiox** [comment]
@keijiodagawa `ng-show` has nothing to do with Onsen UI. It works the same way using only AngularJS: https://codepen.io/frankdiox/pen/eBedzv

Did you mean `ons-show`?
