### ISSUE TITLE
Double curly brace notation is not working in `ons-list-item`

### ISSUE THREAD

**Issue by asial-matagawa** [OnsenUI/OnsenUI#1719]
Reported by @keijiodagawa.

__Environment__ 

```
[Core]
    Onsen UI 2.0.4

[Framework]
    Angular 1.4.3
    Angular 1.5.9

[Framework binding]
    angular-onsenui 2.0.4

[Additional libraries]
    None

[Platform]
    Mobile - Android 6.0.1
    Desktop - macOS Sierra

[Browser]
    Mobile - Android Chrome 52.0.2743.98
    Desktop - Chrome 54.0.2840.98
```

__Encountered problem__
In some situation, double curly brace notation is not working in `ons-list-item`.
It might be a problem of execution order of Angular and Onsen UI.

This problem occurs only on Chrome.
It works fine on macOS Safari and iOS Safari.

__How to reproduce__

```html
<!DOCTYPE HTML>
<html ng-app="app">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
  <meta http-equiv="Content-Security-Policy" content="default-src * data:; style-src * 'unsafe-inline'; script-src * 'unsafe-inline' 'unsafe-eval'">
  <link rel="stylesheet" href="lib/onsenui/css/onsenui.css">
  <link rel="stylesheet" href="lib/onsenui/css/onsen-css-components.css">
  <script src="lib/angular-1.5.9/angular.js"></script>
  <script src="lib/onsenui/js/onsenui.js"></script>
  <script src="lib/onsenui/js/angular-onsenui.js"></script>
  <script>
    var app = angular.module('app', ['onsen']);
    app.controller('HomeController', function($scope) {
      $scope.lists = [
        [{name:'TEST1', year:2016, month:1, day:10, memo:{test1:'test01'}}, {name:'TEST2', year:2016, month:1, day:20, memo:{test1:'test02'}}, {name:'TEST3', year:2016, month:1, day:30, memo:{test1:'test03'}}],
        [{name:'TEST1', year:2016, month:2, day:10, memo:{test1:'test01'}}, {name:'TEST2', year:2016, month:2, day:20, memo:{test1:'test02'}}],
        [{name:'TEST1', year:2016, month:3, day:10, memo:{test1:'test01'}}, {name:'TEST2', year:2016, month:3, day:20, memo:{test1:'test02'}}],
        [{name:'TEST1', year:2016, month:4, day:10, memo:{test1:'test01'}}],
        [],
        [{name:'TEST1', year:2016, month:6, day:10, memo:{test1:'test01'}}, {name:'TEST2', year:2016, month:6, day:20, memo:{test1:'test02'}}],
        [{name:'TEST1', year:2016, month:7, day:10, memo:{test1:'test01'}}, {name:'TEST2', year:2016, month:7, day:20, memo:{test1:'test02'}}, {name:'TEST3', year:2016, month:7, day:30, memo:{test1:'test03'}}, {name:'TEST4', year:2016, month:7, day:31, memo:{test1:'test04'}}],
        [{name:'TEST1', year:2016, month:8, day:10, memo:{test1:'test01'}}, {name:'TEST2', year:2016, month:8, day:20, memo:{test1:'test02'}}],
        [{name:'TEST1', year:2016, month:9, day:10, memo:{test1:'test01'}}],
        [{name:'TEST1', year:2016, month:10, day:10, memo:{test1:'test01'}}, {name:'TEST2', year:2016, month:10, day:20, memo:{test1:'test02'}}],
        [],
        [{name:'TEST1', year:2016, month:12, day:10, memo:{test1:'test01'}}, {name:'TEST2', year:2016, month:12, day:20, memo:{test1:'test02'}}]
      ];
    });
  </script>
</head>
<body>
<ons-page ng-controller="HomeController as home">
  <ons-list ng-repeat="(month, value) in lists">
    <ons-list-header>2016/{{month + 1}}</ons-list-header>
    <ons-list-item ng-repeat="(key, row) in value">
        ({{key}}) {{row.name}} ({{row.memo.test1}})
    </ons-list-item>
    <!-- If we use `div` instead of `ons-list-item`, it works -->
    <!--
    <div ng-repeat="(key, row) in value">
        ({{key}}) {{row.name}} ({{row.memo.test1}})
    </div>
    -->
  </ons-list>
</ons-page>
</body>
</html>
```

CodePen:
https://codepen.io/anon/pen/ZBXxwp/?editors=1010

Note:
1. If we swap `angular.js` and `onsenui.js`, it works.
2. If we move the main script element from `<head>` to the bottom of `<body>`, it works.
3. If we use `div` instead of `ons-list-item`, it works.

**Comment by frankdiox** [comment]
@asial-matagawa I cannot actually reproduce the behavior in my Chrome 54.0.2840.100. In any case, can you try with `<ons-list-item><div class="center">{{content}}</div></ons-list-item>`? That's the way it should be used although I'm not completely sure if it affects.

**Comment by asial-matagawa** [comment]
@frankdiox 
>I cannot actually reproduce the behavior in my Chrome 54.0.2840.100.
This problem can be reproduced on Android Chrome, too.
If you have time, could you try with it?

```html
<ons-list-item><div class="center">{{content}}</div></ons-list-item>
```
I have tried with the code above and it works.

But [the official reference](https://onsen.io/v2/docs/js/ons-list-item.html) has a code like:
```html
<ons-list>
  <ons-list-header>Default</ons-list-header>
  <ons-list-item>Item A</ons-list-item>
  <ons-list-item>Item B</ons-list-item>
````

So I think this behavior is what should be investigated and fixed.

**Comment by frankdiox** [comment]
@asial-matagawa Onsen UI core creates `<div class="center">` automatically if the user doesn't provide it, like in the toolbar. I guess there's a conflict with AngularJS in that situation. I think we should promote writing this divs like we do in the toolbar to avoid DOM manipulation. We already have this information in the [overview guide](https://onsen.io/v2/docs/guide/js/#lists) and also in `ons-list-item` [reference page](https://onsen.io/v2/docs/js/ons-list-item.html). The only place where it's not updated is in the tutorial. I guess it was made like that for simplicity. We can of course try to fix it for the old use case but still I think we should try to avoid DOM manipulation by including this divs in our examples and docs.

**Comment by asial-matagawa** [comment]
@frankdiox 
Thank you! I understand.
I will close this issue for now and focus on the documents instead of the implementation.

**Comment by asial-matagawa** [comment]
@keijiodagawa
It was not an issue.
The following code does not follow the correct usage of Onsen UI 2.
```html
<ons-list-item ng-repeat="(key, row) in value">
    ({{key}}) {{row.name}} ({{row.memo.test1}})
</ons-list-item>
```

Since Onsen UI 2, we have to write code like:
```html
<ons-list-item ng-repeat="(key, row) in value">
    <div class="center">({{key}}) {{row.name}} ({{row.memo.test1}})</div>
</ons-list-item>
```

**Comment by frankdiox** [comment]
@keijiodagawa @asial-matagawa It's just like `ons-toolbar`. This is also possible:

```
<ons-list-item ng-repeat="(key, row) in value">
    <div class="left">({{key}})</div>
    <div class="center">{{row.name}}</div>
    <div class="right">({{row.memo.test1}})</div>
</ons-list-item>
```

**Comment by keijiodagawa** [comment]
@frankdiox @asial-matagawa 

Thank you very much!! I understand.
Unfortunately there were no explanations below on the Japanese site.

Component that represents each item in the list. Must be put inside the <ons-list> component. The list item is composed of three parts that are represented with the left, center and right classes. These classes can be used to ensure that the content of the list items is properly aligned.

```
<ons-list-item>
  <div class="left">Left</div>
  <div class="center">Center</div>
  <div class="right">Right</div>
</ons-list-item>
```

There is also a number of classes (prefixed with list__item__*) that help when putting things like icons and thumbnails into the list items.

Please add documentation.
