### ISSUE TITLE
Can't use Angular2 template features with Tabbar

### ISSUE THREAD

**Issue by wahid** [OnsenUI/OnsenUI#1725]
```
[Core]
    Onsen UI 2.0.4

[Framework]
    Angular 2.1.2

[Framework binding]
    angular2-onsenui 1.0.0-rc.1

[Additional libraries]
    None

[Platform]
    Desktop - Windows 10

[Browser]
    Desktop - Chrome 54.0.2840.87
```

__Encountered problem__

When having a tabbar in Angular2 it seems you can't use any angular template features. In the example below neither the name variable or the other html gets displayed.

__How to reproduce__

```html
<ons-page>
  <ons-toolbar [attr.modifier]="modifier">
    <div class="center">Tabbar</div>
  </ons-toolbar>

  <div class="content">
    <ons-tabbar [attr.animation]="animation" position="auto">
      <div class="tab-bar__content"></div>
      <div class="tab-bar">
        <ons-tab icon="square" label="Tab 1" [page]="first" active></ons-tab>
        <ons-tab icon="square" label="Tab 2" [page]="second"></ons-tab>
      </div>
    </ons-tabbar>
  </div>
</ons-page>
```

```js
import {Component} from '@angular/core';

@Component({
  selector: 'ons-page[second]',
  template: `
    <div class="content">
      <p>I am the second tab. {{ name }}</p>
    </div>
  `
})
export class Second {
name: string = "Wahid";
  constructor() {}
}
```

**Comment by anatoo** [comment]
@wahid Thanks for reporting. I will investigate this problem.

**Comment by wahid** [comment]
I have a sidebar in my app and everything works fine in there. When I click on a button that is attached to angular2 in the sidebar the tab shows the {{ name }}. So it seems it only loads the data in the tab until a angular2 event has happened?

**Comment by asial-matagawa** [comment]
I have investigated this problem briefly and found that change detection seems not working.
This problem occurs even on the latest packages below:
- onsenui 2.0.5
- @angular/* 2.4.3
- angular2-onsenui 1.0.0-rc.4

So we just need to make change detection working on pages managed by `OnsTab` directive.

**Comment by asial-matagawa** [comment]
A possible workaround is to manually execute `this.cd.detectChanges()` when you need to detect changes.
Please be patient until we fix this problem...

**Comment by asial-matagawa** [comment]
@wahid 
This problem has been fixed.
You can use the template features if you update each of `@angular/*`, `onsenui`, `angular2-onsenui`, `rxjs` and `zone.js` to the latest version.
