### ISSUE TITLE
ons-tabbar/index.js: Cannot read property 'newAnimator' of undefined

### ISSUE THREAD

**Issue by asial-matagawa** [OnsenUI/OnsenUI#1727]
__Environment__ 

```
[Core]
    Onsen UI 2.0.2
    Onsen UI 2.0.3
    Onsen UI 2.0.4

[Framework]
    Angular 2.2.4

[Framework binding]
    angular2-onsenui 1.0.0-rc.1

[Additional libraries]
    None

[Platform]
    Desktop - Windows 10

[Browser]
    Desktop - Chrome 54.0.2840.99
```

__Encountered problem__

ons-tabbar.setActiveTab does not work when we set a tab page in `ngAfterViewInit`.

![snapcrab_noname_2016-12-4_4-43-37_no-00](https://cloud.githubusercontent.com/assets/19771915/20861846/73f0f346-b9dd-11e6-83e5-e1bdce668a71.png)

Note:
- It worked fine on `2.0.1`. So `2.0.2` and later causes this problem.
- If we replace angular2-onsenui `1.0.0-rc.1` with `1.0.0-rc.3`, another error (related to PageLoader, #1728) occurs.

__How to reproduce__
```js
@Component({
    selector: 'app',
    template: `
        <ons-tabbar>
            <ons-tab label="Home1" active>
            </ons-tab>
        </ons-tabbar>
    `,
    providers: []
})
class AppComponent implements AfterViewInit {
    @ViewChildren(OnsTab) tabQueryList: QueryList<OnsTab>;

    ngAfterViewInit() {
        this.tabQueryList.toArray()[0].page = TwitterPageComponent;
    }
}
```

Here is a Plunker which reproduces this problem. See `src/main.ts`.
https://plnkr.co/edit/RMabcYkdrFtT9Otp9KTG

**Comment by misterjunio** [comment]
@asial-matagawa Like I discussed with @anatoo this does not seem to be a bug, it's just a consequence of the tabs being loaded asynchronously. I suggested a solution for choosing the tab dynamically on load by touching the DOM [here](https://community.onsen.io/topic/1203/tabbar-and-angular-2/2). It's a bit dirty but I don't see another possibility

**Comment by asial-matagawa** [comment]
@misterjunio 
Thank you for investigating, I got it.
I think we have to fix `ons-tabbar#setActiveTab` to wait for tabs to be loaded.
Looks like it is a problem of the core.

**Comment by frandiox** [comment]
@asial-matagawa This should be fixed after the last refactoring. The problem, as you know, is that Zone.js breaks the tab's `loaded` promise somehow. In any case, I think it should be working now.

**Comment by asial-matagawa** [comment]
Thank you!
