### ISSUE TITLE
Consider adding peerDependency `onsenui` into `bindings/angular2/package.json`.

### ISSUE THREAD

**Issue by asial-matagawa** [OnsenUI/OnsenUI#1731]
@anatoo
angular2-onsenui 1.0.0-rc.3 depends on Onsen UI 2.0.5 and later, so there should be `"onsenui": "^2.0.5",` in `peerDependencies` of `bindings/angular2/package.json`.

What do you think?
Should I create a PR?

**Comment by anatoo** [comment]
I agree with you. I'll update `peerDependencies`.

**Comment by asial-matagawa** [comment]
@anatoo Thank you!

**Comment by asial-matagawa** [comment]
This suggestion has been commited in #1731. Closing this.
