### ISSUE TITLE
OnsDialog not rendering angular controller data

### ISSUE THREAD

**Issue by Sunil2197** [OnsenUI/OnsenUI#1733]
[Core]
    Onsen UI 2.0.4

[Framework]
    Angular 1.5.9
  

[Framework binding]
    angular-onsenui 2.0.4

[Additional libraries]
    jQuery 3.1.1

[Platform]
    Desktop - Windows 10

[Browser]
    Mobile - Android WebView

__Encountered problem__

onsDialog not rendering controller data Or I mean passing data from controller to onsDialog here
code snippet

```
  ons.createDialog('dialog.html',{parentScope:$scope })
            .then(function(dialog) {
                this.dialog = dialog;
                dialog.show();
            }.bind(this));
```

```

<ons-page modifier="home" ng-controller="HomeContentController as homeCtrl">
<ons-template id="dialog.html">
        <ons-dialog>
            <p>Hello</p>
            {{'This is print with curly braces'}}
   </ons-dialog>
    </ons-template>
</ons-page>
```

angular is not interpreting that curly braces and print same as string
' {{'This is print with curly braces'}} '

**Comment by asial-matagawa** [comment]
@Sunil2197 
Thank you for reporting.

I have tried to reproduce this problem but it was not reproduced.
I guess you forgot to:
- Load `angular-onsenui.js`.
- Execute `ons.bootstrap` or `angular.module('myApp', ['onsen'])`.

Also, `ons-template`should be just under the `body` element.
It cannot be located in any element except for `body`.

Closing this.
