### ISSUE TITLE
non-button ng-clicks work on Android, but not iOS

### ISSUE THREAD

**Issue by gogodigimo** [OnsenUI/OnsenUI#1740]
[Core]
    Onsen UI 2.0.4

[Framework]
    Angular 1.5.5

[Framework binding]
    angular-onsenui 2.0.4

[Additional libraries]
    jQuery 1.9.1
    fastclick.js

[Platform]
    Mobile - iOS 10.1.1

[Browser]
    Mobile - iOS UIWebView

__Encountered problem__ & __How to reproduce__
I have created an app using Onsen that works perfectly well on Android, but on iOS I have been experiencing issues that a user must double tap on any object other than a button with an ng-click function attached. A regular tap seems to have no affect, but two swift taps and it acts as it normally would. I have attached fastclick.js, but that does not seem to be helping. I would be extremely appreciative of any guidance in resolving this.

**Comment by asial-matagawa** [comment]
Hi, @gogodigimo!

Thank you for reporting, but we need some code to reproduce the problem and fix it.
We would appreciate if you paste some part of the code you have.

**Comment by gogodigimo** [comment]
Thanks for the quick response, @asial-matagawa . 
Here is a good example of what I am experiencing:

```
<ons-template` id="homepage.html">
        <ons-page>
            <div class="hero-div-container">
                <div class="hero-div">
                    <div><img class="logo" src="img/logo.png" /></div>
                    <div class="large-search-bar">
                        <img id="btnSearch" src="img/Search-Icon.png" data-tap-disabled="true" ng-click="SearchFromJumpStart()" class="search-icon-large" align="right" />
                        <input id="SearchJumpStart" type="number" class="embedded-textbox" onkeyup="return isKeypressEnter(event, callJumpStartSearch)" ng-attr-placeholder="{{translations['search-by-zip-code']}}">
                    </div>
                    <div class="account-link"><button id="signinlink" class="button-noborder" ng-click="GoToSignInPage()" ng-bind="translations['sign-in']"></button></div>
                    <div class="account-link"><button id="registerlink" class="button-noborder" ng-click="GoToCreateAccountPage()" ng-bind="translations['create-account']"></button></div>
                </div>
            </div>
        </ons-page>
    </ons-template>
```

In the above code, the button with ID signinlink works great on both iOS and Android, however the button with ID btnSearch is only calling the SearchFromJumpStart() on Android, not iOS.

**Comment by gogodigimo** [comment]
I have found in iOS that if I double tap the image with ID "btnSearch" in the code above, it works. It just doesn't work with a single tap as it does in Android.

**Comment by asial-matagawa** [comment]
@gogodigimo 
Thank you!
I will investigate this problem by using your code.

**Comment by gogodigimo** [comment]
Thanks very much, @asial-matagawa 
What is also interesting is that if I wrap the btnSearch image in a button container it works exactly as it should in iOS:
```
<div class="large-search-bar">
    <button ng-click="SearchFromJumpStart()"><img src="img/Search-Icon.png" class="search-icon-large" align="right" /></button>
    <input id="SearchJumpStart" type="number" class="embedded-textbox" onkeyup="return isKeypressEnter(event, callJumpStartSearch)" ng-attr-placeholder="{{translations['search-by-zip-code']}}">
</div>
```

**Comment by gogodigimo** [comment]
I believe I have tracked this down to Angular, not Onsen.
I eventually stumbled upon this helpful chain and was able to get my functions firing using the ng-mobile-click attribute:
http://stackoverflow.com/questions/25032237/ng-click-on-firing-on-mobile-or-tablet-devices

Thanks for your efforts, @asial-matagawa .

**Comment by asial-matagawa** [comment]
@gogodigimo 
I am glad to hear that you have found a solution.
I investigated this problem a bit, so I will paste a memo:

>I have tried to reproduce the problem with iOS 10.1 simulator and iOS Safari (instead of iOS UIWebView due to some reasons), but unfortunately I was not able to reproduce the problem.
>
>But I have an idea to solve this problem:
>- Onsen UI uses FastClick internally.
>- This problem must be a problem of FastClick.
>- FastClick has a feature that if you set `needsClick` to the element, FastClick will ignore it.
>  - Implemented in this function: >https://github.com/OnsenUI/OnsenUI/blob/7bb5ab55bd470c0563ab6f5c50d8cb146c4c2a30/core/vendor/fastclick-patched.js#L227
>
>This code might fix the problem:
>```html
><img
>    id="btnSearch"
>    src="img/Search-Icon.png"
>    data-tap-disabled="true"
>    ng-click="SearchFromJumpStart()"
>    class="search-icon-large needsClick"
>    align="right" />
>```

**Comment by gogodigimo** [comment]
Very cool. Thanks for the idea, @asial-matagawa . I will try it out :)
