### ISSUE TITLE
`alert` runs twice on Onsen UI + <input type="file">

### ISSUE THREAD

**Issue by asial-matagawa** [OnsenUI/OnsenUI#1743]
Reported by @keijiodagawa in 2016/11/07.

__Environment__ 

```
[Core]
    Onsen UI 2.0.4

[Framework]
    None

[Framework binding]
    None

[Additional libraries]
    None

[Platform]
    Mobile - iOS 9.2.1 (iPad mini 1 (Model: A1455))

[Browser]
    Mobile - iOS UIWebView
    Mobile - iOS Safari
```

__Encountered problem__
- If we click the span element in the following code on iOS 9.2.1 Safari, `alert` runs twice.
    - This does not occur on iPhone 5s Simulator + iOS 9.2 Safari.
- If we remove `document.getElementById('input_file').click();`, it works fine.
- If we remove Onsen UI from the HTML, it works fine.
    - So I think this might be a FastClick-related problem.

__How to reproduce__
```html
<input type="file" id="input_file"><br>
<br>
<span onclick="test1();">test1</span>
```

```js
function test1() {
  alert("test1");
  document.getElementById('input_file').click();

  // if we swap the two statements above, browser crashes
  // document.getElementById('input_file').click();
  // alert("test1");

  // if we only run `alert`, this problem does not occur
  // alert("test1");
}
```

Here is a CodePen:
https://codepen.io/anon/pen/xRzdMP?editors=1010

**Comment by anatoo** [comment]
@asial-matagawa Thanks! I will investigate this problem.

**Comment by asial-matagawa** [comment]
@anatoo 
It is not an urgent task to solve this problem since the original issue reported by @keijiodagawa has already been solved. Thank you for checking.
