### ISSUE TITLE
problem when animation: lift of navigation is used.

### ISSUE THREAD

**Issue by koheiokazaki** [OnsenUI/OnsenUI#1745]
__Environment__ 

```
[Core]
    Onsen UI 2.0.4

[Framework]
    Angular 2.2.4

[Framework binding]
    angular-onsenui 2.0.4

[Platform]
    Mobile - iOS 10.1.1

[Browser]
    Mobile - iOS UIWebView
```

__Encountered problem__

It is a problem when animation: lift of navigation is used. After using lift, when you return to the previous screen, the whole previous screen will rise.

sorry it is difficult for me to explain. please see this screen shot.

![slack_for_ios_upload_720](https://cloud.githubusercontent.com/assets/8564296/21040643/9c199eb8-be29-11e6-9a55-20d8532984b9.jpg)

**Comment by asial-matagawa** [comment]
@koheiokazaki 
Thank you for reporting!

>[Framework binding]
>    angular-onsenui 2.0.4

If you are using Angular 2.2.4, Framework binding must not be `angular-onsenui`, but `angular2-onsenui`.
Could you tell us `angular2-onsenui` version which you are using?
It is written in `package.json`.

[ja]
`package.json` に `angular2-onsenui` のバージョンが書かれているはずです。よろしければ確認していただけないでしょうか？

**Comment by asial-matagawa** [comment]
This issue is similar to #780, so it can be a problem of the Onsen UI core.

**Comment by koheiokazaki** [comment]
Thanks for review!

I use
"angular2-onsenui": "^1.0.0-rc.1",

**Comment by asial-matagawa** [comment]
Thank you! We will investigate this issue as soon as possible.
