### ISSUE TITLE
Provide a way to set custom click event listeners for onsBackButton directive

### ISSUE THREAD

**Issue by asial-matagawa** [OnsenUI/OnsenUI#1749]
Reported by @puku0x in http://qiita.com/puku0x/items/5104e78a7794a94ee004 (Thank you @puku0x !).
Also, I have reproduced the problem in my environment.

__Environment__ 

```
[Core]
    Onsen UI 2.0.4

[Framework]
    Angular 1.5.9

[Framework binding]
    angular-onsenui 2.0.4

[Additional libraries]
    None

[Platform]
    Desktop - Windows 10

[Browser]
    Desktop - Chrome 55.0.2883.87
```

__Encountered problem__
Style of a back button can be broken in a particular situation.

![snapcrab_noname_2016-12-14_1-31-9_no-00](https://cloud.githubusercontent.com/assets/19771915/21148886/0bdbabf8-c19d-11e6-9384-71c6abecc8c1.png)

__How to reproduce__

```html
<ons-navigator var="navi" page="main.html"></ons-navigator>

<!-- Main -->
<ons-template id="main.html">
  <ons-page ng-controller="MainController as ctrl">
    <ons-toolbar>
      <div class="center">Schedule App</div>
    </ons-toolbar>
    <div style="width:100%; height:70%">
      <ons-carousel var="carousel" style="height:100%; background-color:red;" swipeable auto-scroll></overscrollable>
        <ons-carousel-item>Calendar 1</ons-carousel-item>
        <ons-carousel-item>Calendar 2</ons-carousel-item>
        <ons-carousel-item>Calendar 3</ons-carousel-item>
      </ons-carousel>
    </div>
    <div style="width:100%; height:30%; overflow-y:auto;">
      <ons-list>
        <ons-list-item tappable ng-click="ctrl.detail()">Tap me!</ons-list-item>
        <ons-list-item tappable ng-click="ctrl.detail()">Tap me!</ons-list-item>
        <ons-list-item><input placeholder="input here is ok"></ons-list-item>
      </ons-list>
    </div>
  </ons-page>
</ons-template>

<!-- Detail -->
<ons-template id="detail.html">
  <ons-page ng-controller="DetailController as ctrl">
    <ons-toolbar>
      <div class="left">
        <ons-toolbar-button ng-click="ctrl.back()">
          <ons-icon icon="ion-ios-arrow-back, material:md-arrow-back" size="32px, material:24px"></ons-icon>
          <ons-if platform="ios other">Back</ons-if>
        </ons-toolbar-button>
      </div>
      <div class="center">Detail</div>
    </ons-toolbar>
    <p>This is the Onsen Page Template.</p>
    <input type="text">
  </ons-page>
</ons-template>
```

```js
// Module
ons.bootstrap('app', ['onsen']);

// Controller
angular
  .module('app')
  .controller('MainController', MainController)
  .controller('DetailController', DetailController);

// DI
MainController.$inject = ['$scope', '$timeout'];
DetailController.$inject = [];

// Controller
function MainController($scope, $timeout) {
    var vm = this;
    vm.detail = detail;

    // Variables for carousel bug
    var lastIndex = 0;
    var needFix = false;
    var pagePushed = false;
    function checkCarouselBug() {
        pagePushed = false;
        if (needFix) {
            needFix = false;
            $timeout(function() {
                vm.carousel.setActiveIndex(lastIndex);
            });
        }
    }

    // Detail
    function detail() {
        var options = {
            prePop: checkCarouselBug,
        };
        navi.pushPage('detail.html', options).then(function() {
            pagePushed = true;
        });;
    }

    // Init
    $timeout(function(){
        vm.carousel = $scope.carousel;
        vm.carousel.on('postchange', function(event) {
            if (pagePushed) {
                needFix = true;
            } else {
                lastIndex = event.activeIndex;
            }
        });
    });
}

// Controller
function DetailController() {
    var page = navi.topPage;
    var args = page.pushedOptions;
    var vm = this;
    vm.back = back;

    function back() {
        var options = {};
        args.prePop();
        navi.popPage(options);
    }
}
```

Here is a CodePen by @puku0x :
http://codepen.io/puku0x/pen/WogwRg

**Comment by frankdiox** [comment]
@asial-matagawa This is not an `ons-back-button`. It's an `ons-toolbar-button` with an `ons-icon` and text inside it. It does not contain the necessary CSS to be aligned and it doesn't work with the slide-ios animation either.

I guess it's used in this way to use a custom "onclick", but the `ons-back-button` already have an `onClick` and even `options` properties to overwrite its behavior. Perhaps it could be a bit hard to use in AngularJS since it's a DOM property. Maybe we should add a directive like `ng-ons-click` or whatever.

**Comment by asial-matagawa** [comment]
@frankdiox 
>It's an ons-toolbar-button with an ons-icon and text inside it.

Oh I missed it, sorry.

>I guess it's used in this way to add a custom "onclick", but the ons-back-button already has an onClick and even options properties to overwrite its behavior.

I have seen many users suffer from the problem of custom `onclick` on back buttons.
I think we should deal with it by adding more detailed guides as well as API references.

**Comment by frankdiox** [comment]
@asial-matagawa It's documented in the `ons-back-button` reference. The only problem is that there is not specific directive in Angular so it is necessary to get the DOM element and modify the prop. I think we should add an attribute for this in AngularJS. React or Vue don't have any problem since they can modify props easily. I'm not sure about Angular2 either.

**Comment by asial-matagawa** [comment]
@frankdiox 
Yes, it's documented and I know it is an Angular 1 specific problem.
What I meant is just the document can be improved more.
(Or we can add conditional warnings which appears when a user writes something not recommended)

**Comment by puku0x** [comment]
Quick fix in case of using ons-toolbar-button.

<pre>
<ons-toolbar-button ng-click="navi.pop()">
    <ons-icon icon="ion-ios-arrow-back, material:md-arrow-back" size="32px, material:24px"></ons-icon>
        <ons-if platform="ios other" class="back-button__label">Back</ons-if>
</ons-toolbar-button>
</pre>
