### ISSUE TITLE
ng-show/ng-hide does not work correctly

### ISSUE THREAD

**Issue by knight9999** [OnsenUI/OnsenUI#175]
For Onsen UI 1.1.1, assume that the index.html is

&lt;ons-navigator title="navi" page="page1.html">
&lt;/ons-navigator>

and the page1.html is
&lt;div ng-hide="showFlag">Show False&lt;/div>
&lt;div ng-show="showFlag">Show True&lt;/div>

&lt;button ng-click="showFlag = !showFlag">Change&lt;button>

In such case, one expect either of one of 'Show False' or 'Show True' should be shown.
Unfortunately, both 'Show False' and 'Show True' are shown at first time in Onsen UI 1.1.1. 
For Onsen UI 1.1.0, this works well.

**Comment by martSforever** [comment]
try remove the directive: ng-csp, i remove ng-csp directive and that my ng-show and ng-hide is working
