### ISSUE TITLE
ons-dialog event propagation causes usability issues

### ISSUE THREAD

**Issue by nodefish** [OnsenUI/OnsenUI#1754]
```
[Core]
    Onsen UI 2.0.4

[Framework]
    None

[Framework binding]
    None

[Additional libraries]
    None
    jQuery 3.1.1

[Platform]
    Mobile - iOS 10.1.1
    Desktop - Linux
    Desktop - Windows 10

[Browser]
    Mobile - iOS UIWebView
    Mobile - iOS Safari
    Desktop - Firefox 50+
```

__Encountered problem__

This is most likely related to #422.

If you have a `textarea` inside an `ons-dialog`, due to this event propagation issue (scroll & touch events seem to propagate), it makes it very hard to edit the text inside the `textarea` as tapping on the text is unresponsive. Additionally, the scroll event propagates to the background.

This issue occurs on Desktop Firefox but not Chrome. It also occurs in iOS Safari and UIWebView (cordova).

__How to reproduce__

Simply include a `textarea` with `rows` > 1 inside `ons-dialog`: https://codepen.io/anon/pen/qqQomq?&editors=101

On iOS Safari, I can't seem to even select the textarea without holding my finger down on it. In Cordova, it's selectable but just very difficult to tap a specific word and the cursor keeps resetting to the beginning or end of the text contents.

**Comment by anatoo** [comment]
@nodefish Thanks for reporting. It seems that FastClick occur this behavior. We will fix the problem.

**Comment by asialgearoid** [comment]
This may be related to #2254, and possibly fixed by the same code.

**Comment by asialgearoid** [comment]
This seems to have been fixed by our changes to FastClick. Please feel free to re-open if this is not fixed for you in the latest version of Onsen UI.
