### ISSUE TITLE
React: Dialogs are created outside of the root context

### ISSUE THREAD

**Issue by corneyl** [OnsenUI/OnsenUI#1758]
Because [OnsenIO/react-onsenui](/OnsenUI/react-onsenui) is closing down, here a repost of the issue.

__Environment__
+-- onsenui@2.0.4
+-- react@15.4.0
`-- react-onsenui@1.0.3

It would be nice in my opinion to create all `Dialog`s (and `AlertDialog`s etc.) within the `Navigator` or root context.

The problem now is that when one uses a root tag which provides a certain context in React, the `Dialog`s do not have this context. Examples are the context provided by `MuiThemeProvider` ([link](http://www.material-ui.com/#/get-started/usage)) or `react-intl`'s `IntlProvider` ([link](https://github.com/yahoo/react-intl)) from which the theme and i18n functionality cannot be used in `Dialog`s etc. because they lack the proper context.

It would be nice if there is a solution for this problem, but maybe it's not possible to fix this easily.

**Comment by anatoo** [comment]
@corneyl Thanks for reporting. Okay, we will try to fix this problem.

**Comment by frandiox** [comment]
Fixed in #1852
