### ISSUE TITLE
problem with intel xdk

### ISSUE THREAD

**Issue by aahmyu** [OnsenUI/OnsenUI#1761]
Hello im trying to use intel xdk wiht onsen ui 2 latest version but the problem is i cant use the debugger from intel xdk because im getting an error which is:
Remote debugging has been terminated with reason: websocket_closed. Please reattach to the new target.

so i tried to figure out why im getting this problem and started commenting stuff in my index html and found out the culprit which is <script src="lib/onsen/js/onsenui.js"></script>
so the debugger breaks when it loads this library and works fine without. its easy to reproduce.

Regards

**Comment by anatoo** [comment]
@aahmyu Thanks for reporting. But I don't intend to investigate this problem because it seems to be intel xdk problem not Onsen UI. The debugger fail for some application code, it's debugger's bug.
