### ISSUE TITLE
Angular JS: Tutorial Splitter fails

### ISSUE THREAD

**Issue by asalgueiro** [OnsenUI/OnsenUI#1764]
__Environment__ Google Chrome

[Core]
    Onsen UI 2.0.5

[Framework]
    Angular 1.5.9

[Framework binding]
    angular-onsenui 2.0.4

[Additional libraries]
    None

[Platform]
    Desktop and Mobile

__Encountered problem__
The Splitter tutorial with Angular JS don't change the page on menu click.
The same behavior creating and blank example in my PC.

__How to reproduce__
Go to: https://tutorial.onsen.io/?framework=angular1&category=Reference&module=splitter
or navigate: Tutorial  > Angular JS > Slide menu (Splitter)

**Comment by frankdiox** [comment]
@asalgueiro  I found this issue after [fixing it](https://github.com/OnsenUI/OnsenUI/pull/1771/commits/363d7f3cdcf587c54c83546f40e8ece66411e462) :sweat_smile: Thanks for reporting anyway.
