### ISSUE TITLE
How to avoid "popPage is already running"

### ISSUE THREAD

**Issue by koheiokazaki** [OnsenUI/OnsenUI#1767]
[Core]
    Onsen UI 2.0.4

[Framework]
    Angular 2.2.4

[Framework binding]
    angular-onsenui 2.0.4

[Additional libraries]
    None

[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1

[Browser]
    Mobile - Android WebView
    Mobile - Android Chrome 54.0.2840.85
    Mobile - iOS UIWebView
    Mobile - iOS Safari

__Encountered problem__
I get this error when I tap the back button continuously.
How to avoid this error? and, Can you catch this error?

**Comment by frankdiox** [comment]
@koheiokazaki This is similar to [this post](https://community.onsen.io/topic/1062/cancel-prepop-event-shows-an-error/2). It's just a rejected promise. Maybe we should catch it in back button and just print a warning or something instead.

**Comment by asial-matagawa** [comment]
I talked with @koheiokazaki on another place and he managed to solve his problem by the solution above.

Closing this.
