### ISSUE TITLE
React : Some callbacks (onChange and OnClose) are only treated once

### ISSUE THREAD

**Issue by sylvain-hamel** [OnsenUI/OnsenUI#1768]
__Environment__ 

```
[Core]
    Onsen UI 2.0.4

[Framework]
    React 15.4.1

[Framework binding]
    react-onsenui 1.0.4

[Additional libraries]
    None

[Platform]
    Desktop - Windows 10

[Browser]
    Desktop - Chrome 55.0.2883.75
```

__Encountered problem__

Some callbacks like `Switch.onChange` or `SplitterSide.onClose` don't use updated prop value. If a new function is passed to the component in a render cycle, the original function still is used.

This is a big issue with _functional stateless component_ because they rely on closures, not on `this.state` or `this.props`.

__How to reproduce__

Here is a codepen that demonstrate the issue : https://codepen.io/anon/pen/NdPzJa?editors=1011

- The outer container (`MyPage`) uses `setInterval` to increment  `i`
- `MyPage` contains a `MyComponent` which is a _functional stateless component_
- `MyComponent` uses `i` in two different callbacks : a callback to `Switch.onChange` and a callback to `Button.onClick`
- When you click the button, the correct value is displayed in the console.
- Bug : When you click the Switch, the first value (`1`) is displayed in the console.

**Comment by anatoo** [comment]
@sylvain-hamel Thanks for reporting. I will investigate this problem.

**Comment by sylvain-hamel** [comment]
@anatoo Hi, did you have a chance to look into this problem?

**Comment by anatoo** [comment]
@sylvain-hamel Oh sorry for delay, I'm going to fix this problem.
