### ISSUE TITLE
[ons-list-item] modifier `tappable` is not working on Android

### ISSUE THREAD

**Issue by asial-matagawa** [OnsenUI/OnsenUI#1773]
Reported by @kanakoubukata.

__Environment__ 

```
[Core]
    Onsen UI 2.0.5

[Framework]
    None

[Framework binding]
    None

[Additional libraries]
    None

[Platform]
    Mobile - Android

[Browser]
    Mobile - Android WebView
```

__Encountered problem__

The modifier `tappable` is not working on Android.
It works fine on iOS UIWebView.

__How to reproduce__

```html
<ons-list-item modifier="tappable"></ons-list-item>
```

**Comment by asial-matagawa** [comment]
I guess the automatic styling does not work properly.

**Comment by frandiox** [comment]
@asial-matagawa I believe this happens because the automatic styling is actually [working properly](https://github.com/OnsenUI/OnsenUI/blob/master/core/src/ons/autostyle.js#L33). It removes `tappable` modifier and adds `ripple` attribute. `disable-auto-styling` attribute should avoid this.

**Comment by asial-matagawa** [comment]
👍
