### ISSUE TITLE
ons.createpopover error

### ISSUE THREAD

**Issue by zineer** [OnsenUI/OnsenUI#1775]
__Environment__ 

```
[Core]
    Onsen UI 2.0.5

[Framework]
    Angular 1.6.1

[Framework binding]
    angular-onsenui 2.0.5
 
[Additional libraries]
    None

[Platform]
    Desktop - OSX El Capitan

[Browser]
    Desktop - Safari 9.1.2 (11601.7.7)
```

__Encountered problem__
Popover doesn't properly get initialized. Fills whole page width when shown. Error that comes up is 
```
[Error] TypeError: null is not an object (evaluating 'element.children')
	findChild (onsenui.min.js:4:4123)
	get (onsenui.min.js:10:19194)
	(anonymous function) (onsenui.min.js:10:17962)
	(anonymous function) (onsenui.min.js:3:28240)
	forEach
	consumeQueue (onsenui.min.js:3:28205)
	contentReady (onsenui.min.js:3:28426)
	value (onsenui.min.js:10:17759)
	verifyAndSetupAndAction (onsenui.min.js:2:15804)
	(anonymous function) (onsenui.min.js:2:13290)
	checkEmAll (onsenui.min.js:2:30046)
	(anonymous function) (onsenui.min.js:2:30232)
```
__How to reproduce__
https://codepen.io/zineer/pen/zNqQYG

__Details__
I tracked the issue to the fact that when the popover is created, `_createPopoverOriginal` is called, which loads the page HTML and calls `util.createElement` on the HTML. In turn, `innerHTML` is called, then calling `initialize`. When initialize is called on the ons-popover, the `createdCallback` is called. At this point I lost track, but somewhere in callback.call, the `popover` class gets added to the class list.
Then in the `PopoverElement`, `_compile`, it checks if `this.classList.contains('popover')` and when it does, it skips the rest of the styling that should be done, including adding in the `popover__content` that is missing and causing the error.

**Comment by anatoo** [comment]
@zinner Thanks for reporting. I will investigate this problem.

**Comment by frandiox** [comment]
@zineer You are mixing JS and CSS versions (`2.0.5` and `latest`, respectively). Simply use the latest version for JS as well or specify "2.0.5" in the CDN URL for the CSS.

**Comment by zineer** [comment]
Thanks! I just tried using the 2.0.5 CSS, but had the same issue. But then I tried the codepen with the latest 2.2.4 JS/CSS and the issue seems to have been resolved somewhere along the line.
