### ISSUE TITLE
<ons-pull-hook> in lazy loading can not use

### ISSUE THREAD

**Issue by zmkn** [OnsenUI/OnsenUI#1776]
**Environment**
Onsen 2.0.5
Angular 2.4.3
angular2-onsenui 1.0.0-rc.3
Google Chrome

**Encountered problem**
The (action) output is invalid when `<ons-pull-hook>` with lazy loading in the router  in the web browser.

**Code**

![image](https://cloud.githubusercontent.com/assets/1784566/21915846/7717ee44-d977-11e6-98ab-df8649bdb692.png)

![image](https://cloud.githubusercontent.com/assets/1784566/21915866/9381a232-d977-11e6-92e7-a4893c5f799a.png)

![image](https://cloud.githubusercontent.com/assets/1784566/21915896/b55707e4-d977-11e6-9edc-e088956db044.png)

![image](https://cloud.githubusercontent.com/assets/1784566/21915910/c531dcca-d977-11e6-8549-b9f2dbfe2cd9.png)

![image](https://cloud.githubusercontent.com/assets/1784566/21915917/d5adc334-d977-11e6-9222-19cdcc2135bf.png)

**Google Chrome Console Log**
![image](https://cloud.githubusercontent.com/assets/1784566/21916000/5c755684-d978-11e6-8f31-01510bd6b50d.png)

**Comment by anatoo** [comment]
@zmkn Do you import `OnsenModule`? It seems that your code does not include `OnsenModule` importing.

**Comment by zmkn** [comment]
@anatoo I'm import `OnsenModule` in `AppModule`. `AppRouterModule` lazy loading `VideoModule`, `VideoRouterModule` lazy loading `VideoIndexModule`. `ons-pull-hook` in the `VideoIndexComponent`.

**Comment by anatoo** [comment]
Ok, could you share whole code not screenshots that reproduce your problem?

**Comment by zmkn** [comment]
@anatoo 
Files:[https://github.com/zmkn/ssgo-webapp](url)
Preview:[http://onsen.zmkn.com/](url)

**Comment by anatoo** [comment]
@zmkn Thanks! I will investigate this problem.

**Comment by zmkn** [comment]
@anatoo Ok,Thanks!
