### ISSUE TITLE
iOS toolbar

### ISSUE THREAD

**Issue by ivaylopivanov** [OnsenUI/OnsenUI#1778]
Not enough space / margin for the top toolbar

```
[Core]
    Onsen UI 2.0.4

[Framework]
    Angular 2.2.4

[Framework binding]
    angular2-onsenui 1.0.0-rc.3

[Platform]
    Mobile - iOS 10.2
```
Using the https://github.com/OnsenUI/angular2-onsenui-kitchensink example. Tested as well on real device - iphone 5s with iOS 9.3.5

<img width="377" alt="screen shot 2017-01-13 at 22 50 42" src="https://cloud.githubusercontent.com/assets/8849904/21946994/1e2b97c4-d9e3-11e6-8e05-9b4ab23f6132.png">

**Comment by ivaylopivanov** [comment]
Forgot to mention it - I'm using it with cordova. In this case I guess it's not an issue.

**Comment by frankdiox** [comment]
@ivaylopivanov Did you include `cordova.js`?

**Comment by ivaylopivanov** [comment]
Fuck, sorry, Thanks.
