### ISSUE TITLE
angular 2 lazy loading

### ISSUE THREAD

**Issue by ivaylopivanov** [OnsenUI/OnsenUI#1780]
Hey guys, in the past few days I was playing around with Onsen UI and Angular 2. I was trying to make Onsen work with Angular lazy loading. Unfortunately there is no straight forward way to do that and the solution is a bit [hacky](https://github.com/ivaylopivanov/onsenui-angular2-lazy-loading/blob/master/src/app/modules/custom-navigation/custom-navigation.ts#L51). Also, the splitter needs an ugly [trick](https://github.com/ivaylopivanov/onsenui-angular2-lazy-loading/blob/master/src/app/modules/app/app.component.html#L5) to make it work in the root component. However, the end result was impressive. The produced bundle is more than 300kb smaller than Ionic 2. Huge performance improvement on both Android and iOS compared to Ionic (both iOS and Android) and Nativescript (Android). Thank you very much for the great work! Any suggestions on how to accomplish the lazy loading and the menu in more elegant way?

The project could be found [here](https://github.com/ivaylopivanov/onsenui-angular2-lazy-loading)

**Comment by anatoo** [comment]
Hi @ivaylopivanov, what do you mean by`lazy loading`? Do you want to load lazily `onsenui.js` or Angular 2 framework or both?

**Comment by ivaylopivanov** [comment]
Hi @anatoo, by lazy loading I refer to [lazy modules](https://angular.io/docs/ts/latest/guide/ngmodule.html#!#lazy-load).  The problem is that the lazy loaded module doesn't have the same instance of `ComponentFactoryResolver`, so I can't provide `entryComponents` in the lazy loaded module. From the example above, you can replace  the `custom-navigation` with the `OnsNavigator` and you will get that error there is no factory for that component.

**Comment by anatoo** [comment]
Oh, I see. 

> Any suggestions on how to accomplish the lazy loading and the menu in more elegant way?

Sorry, I have no idea for that. Currently we have no plans to support lazy modules because Onsen UI is built for Cordova apps.

**Comment by ivaylopivanov** [comment]
@anatoo why did you close the issue?
1.  Just because you have no plans to support it doesn't mean it does not exist.
2. I would say that this is nice-to-have-feature because, for example, if you're building an e-commerce app, you don't want the checkout route to be served to the client on first load - hope you got the idea. Every application that is beyond the `hello-world` app will benefit of that, because the main bundle, which is loaded on first load will be smaller, hence the app will load faster.

**Comment by anatoo** [comment]
@ivaylopivanov I closed it because I can not just help you about how to implement lazy modules. if you are doing feature request, you can reopen this issue.
