### ISSUE TITLE
Animit#saveStyle should support !important.

### ISSUE THREAD

**Issue by asial-matagawa** [OnsenUI/OnsenUI#1789]
Reported by @kanakoubukata.

__Environment__ 

```
[Core]
    Onsen UI 2.0.5

[Framework]
    None

[Framework binding]
    None

[Additional libraries]
    None

[Platform]
    Desktop - macOS Sierra

[Browser]
    Desktop - Chrome 55.0.2883.95
```

__Encountered problem__
Animit#saveStyle saves `background-color: red !important;`  as `background-color: red;`, so styles are sometimes broken by an animation.

__How to reproduce__
In https://tutorial.onsen.io/?framework=vanilla&category=Reference&module=navigator , replace `page2.html` with the following code:
```html
<ons-template id="page2.html">
  <ons-page id="page2">
  <div class="content" style="background-color: red !important;">
    <ons-toolbar>
      <div class="left"><ons-back-button>Back</ons-back-button></div>
      <div class="center"></div>
    </ons-toolbar>

    <p>This is the second page.</p>
  </div>
  </ons-page>
</ons-template>
```

**Comment by frankdiox** [comment]
@asial-matagawa The background color should go in `<div class="background" style="...">` instead of `<div="content">`, but I guess it should keep the `!important` anyway.
