### ISSUE TITLE
ons-input DOM manipulation

### ISSUE THREAD

**Issue by frandiox** [OnsenUI/OnsenUI#1791]
@anatoo As mentioned in #1262 by @sukima, `ons-input` does some DOM manipulation inside `contentReady` that perhaps could be moved directly to `connectedCallback` since it's an empty element. I have found some limitations as well with this component while implementing Vue 2 bindings due to the same thing. Either moving it to `connectedCallback` or removing `setImmediate` from `contentReady` break Angular 2 bindings. Since you know more about the timing in Angular 2 to create components and add attributes, could you please check it? Thanks!

**Comment by sukima** [comment]
At this time I stopped trying to port this to Ember. If I continue the only solution I found was to completely reinvent the entire `ons-input` behavior in Ember and *only* use the CSS.

Many rendering engine assume normal DOM elements where one can dynamically set attributes. Some components in OnsenUI (i.e. `ons-input`) will not account for dynamic attributes. Which means that these elements are only useful in plain HTML and not when created from a rendering engine like Angular2, glimmer, react, etc.

**Comment by anatoo** [comment]
@sukima Oh that's right, currently `ons-input` doesn't handle some dynamic attributes. So it's just ons-input's problem not `contentReady` or `setImmediate` problem.

**Comment by frankdiox** [comment]
Looks like the problem with Vue.js bindings and `ons-input` was related to the way Vue's `v-model` directive internally works with non native inputs. Nothing to do with `ons-input` implementation but in any case I guess it would be better to refactor it a bit.

**Comment by frandiox** [comment]
@sukima We decided to split `ons-input` into different components: `ons-checkbox`, `ons-radio`, etc. There are no more attributes that modify the compilation. Now it should work well in Ember since the components are quite simple. It will be released in 2.4.0 in a few days (already in master branch) :+1:
