### ISSUE TITLE
Tabbar on Android 4 support

### ISSUE THREAD

**Issue by madagon** [OnsenUI/OnsenUI#1803]
__Environment__ Android 15-16

```
[Core]
    Onsen UI 2.1.0

[Framework]
    Angular 1.5.9

[Framework binding]
    angular-onsenui 2.1.0

[Additional libraries]
    jQuery 3.1.1

[Platform]
    Mobile - Android 4.2.2

[Browser]
    Desktop - Chrome 55.0.2883.75
```

__Encountered problem__

Hello! Most parts of onsen ui work fine on android 4 but today i found an exception when using ons-tabbar! I tried to analyze the DOM element using weinre but i couldn't figure out the problem. Compiler had already applied its changes to DOM based on properties and child nodes given to ons-tabbar but no ons-tab pages were actually compiled. I tried to compile the tabbar and child tabs manually using "ons.compile()" but nothing changed. I don't even have my tab buttons on bottom side.

It should be noted that everything works fine on higher android versions. Please help me with bug-fix or a temporary solution for now since it's urgently required for my work.

Thanks in advance.

__How to reproduce__

```
<ons-page>
    <ons-toolbar class="nav">
        <div class="left">
            <ons-back-button></ons-back-button>
        </div>
        <div class="center">Title</div>
    </ons-toolbar>
    <ons-tabbar>
        <ons-tab page="tab1.html" label="Tab1" icon="pencil-square-o" active="true"></ons-tab>
        <ons-tab page="tab2.html" label="Tab2" icon="film"></ons-tab>
    </ons-tabbar>
    <ons-template id="tab1.html">
        <ons-page>
...
```

**Comment by frankdiox** [comment]
@madagon Hi! `ons-template` should not be nested in any component! Use it directly in the body of `index.html`, nowhere else. #1802

**Comment by madagon** [comment]
@frankdiox thanks for your quick answer! I moved templates to index.html page and body tag, now i can see tab buttons but i can't still see contents neither i can switch between tabs. Didn't work for me.
I don't think using Crosswalk plugin should be an alternative to this problem since it increases a lot on apk size and one one my points for picking cordova is the small size of the output application.

Everything work fine so far except this one. any plan for fixing the issue on android 4?

**Comment by madagon** [comment]
the problem can be fixed by just swapping the place of ons-tabbar and ons-template.

```
<ons-page>
    <ons-toolbar class="nav">
        <div class="left">
            <ons-back-button></ons-back-button>
        </div>
        <div class="center">Title</div>
    </ons-toolbar>
    <ons-template id="tab1.html">
        <ons-page>
        </ons-page>
    </ons-template>
    <ons-template id="tab2.html">
        <ons-page>
        </ons-page>
    </ons-template>
    <ons-tabbar>
        <ons-tab page="tab1.html" label="Tab1" icon="pencil-square-o" active="true"></ons-tab>
        <ons-tab page="tab2.html" label="Tab2" icon="film"></ons-tab>
    </ons-tabbar>
</ons-page>
```

**Comment by frankdiox** [comment]
@madagon Hmm... Did you try it this way?

```
<body>

<ons-page>
    <ons-toolbar class="nav">
        <div class="left">
            <ons-back-button></ons-back-button>
        </div>
        <div class="center">Title</div>
    </ons-toolbar>

    <ons-tabbar>
        <ons-tab page="tab1.html" label="Tab1" icon="pencil-square-o" active="true"></ons-tab>
        <ons-tab page="tab2.html" label="Tab2" icon="film"></ons-tab>
    </ons-tabbar>
</ons-page>

<ons-template id="tab1.html">
  <ons-page>
  </ons-page>
</ons-template>

<ons-template id="tab2.html">
  <ons-page>
  </ons-page>
</ons-template>

</body>
```

When I said
>should not be nested in any component! Use it directly in the body of index.html

I actually meant it :sweat_smile: . Move your `ons-template` to the `body` tag or otherwise create your pages in separate files without `ons-template` tag. If it doesn't work this way, then we should worry about it.

And I mentioned Crosswalk because [*officially*](https://github.com/OnsenUI/OnsenUI#browser-support) we only support Android 4.4+, and 4.0+ with Crosswalk.

Anyway, glad it works now :)

**Comment by madagon** [comment]
I follow the standard patterns defined by your team in designing my app so i have my pages in separate html files but in some places it doesn't make sense to move some templates to separate files actually and i had no problem on newer devices with embedded templates.

Though you mentioned Android 4.4+ as your supported platforms, Hopefully Onsen UI works great on Android 4.2.2 too with little tricky changes in design in some places (like i did about ons-tabbar in this issue).

Anyway, Thanks for your assist. You're all great!
