### ISSUE TITLE
Icon font paths don't match with Webpack build and React

### ISSUE THREAD

**Issue by drwelby** [OnsenUI/OnsenUI#1809]
__Environment__ 

```
[Core]
    Onsen UI 2.1.0

[Framework]
    React 15.4.1

[Framework binding]
    react-onsenui 1.1.0

[Additional libraries]
    react-create-app

[Platform]
    Desktop - Windows 10

[Browser]
    Desktop - Chrome 55.0.2883.75
```

__Encountered problem__

Webpack is placing the icon fonts in a location that doesn't match the generated CSS.

The fonts are placed in `/static/media`
The CSS font source is referencing `/static/css/static/media`

__How to reproduce__

1. Create a React app with create-react-app

2. Make a page with an Ion icon

3. Include CSS:
```
import 'onsenui/css/onsenui.css';
import 'onsenui/css/onsen-css-components.css';
import 'onsenui/css/ionicons/css/ionicons.min.css'
```

4. build with `npm run build`

I'm not sure if this can be fixed by modifying the current CSS structure, or by changing the webpack configuration.

**Comment by frankdiox** [comment]
@drwelby Hi! It's not necessary to manually import the icons. `onsenui.css` file is already importing them. If you installed `onsenui` and `react-onsenui` with NPM, this should be enough:

```
import 'onsenui/css/onsenui.css';
import 'onsenui/css/onsen-css-components.css';
```

I just tried it with `create-react-app` and `npm start`. It shows the icons as expected with a code like this:

```
import { Icon } from 'react-onsenui';
...
 <Icon icon="md-face" />`
```

`npm run build` locates the icons in `/build/static/media/...` and in the generated CSS I can see something like this `src:url(/static/media/ionicons.19e65b89.eot);`. I guess that's fine.

**Comment by drwelby** [comment]
@frankdiox Thanks for checking! I tried with a new create-react-app project and a [simplified version of my layout](https://gist.github.com/drwelby/57c68805d42f32652cd35862f378b195) and it works. 

But my app still doesn't work, even with removing the extra css import. I'm going to try recreating the app to see if that makes a difference.

**Comment by drwelby** [comment]
I found the source of the problem: the "homepage" setting in package.json.
