### ISSUE TITLE
OnsenUI Carousel - Automatically scrolls to first element on page scroll (mobile devices)

### ISSUE THREAD

**Issue by varung-optimus** [OnsenUI/OnsenUI#1815]
__Environment__ 

```
[Core]
    Onsen UI 2.1.0

[Framework]
    Angular 2

[Framework binding]
    angular2-onsenui 1.0.0-rc.4

[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1

[Browser]
    Mobile - Android Chrome 54.0.2840.85
    Mobile - iOS Safari
```

__Encountered problem__
We have implemented horizontal carousel with multiple items being displayed depending on viewport size. Everything works as desired on desktop, however, on both Android and iOS devices, we noticed that when we scroll the page, the carousel automatically scrolls to first element.

__How to reproduce__

- When on a page with multiple items being displayed for horizontal carousel. Select an item after scrolling to the right. 

- Scroll the page down and then up

- You will notice that carousel automatically scrolls to the left most item.

**Comment by FineRapha** [comment]
Hello.

I faced an issue like this one.
But, in my case, all my ons-carousel would reset everytime my setInterval() got triggered.

Without further tests, I'll assume anything changing UIs (my repeating script was used to check if the current user is logged and can see some itens inside the menu) will trigger this issue.

**Comment by nodefish** [comment]
Might be related: https://github.com/OnsenUI/OnsenUI/issues/1565#issuecomment-281993665
