### ISSUE TITLE
$material-select-input-* is not defined in onsen-css-comonents.css

### ISSUE THREAD

**Issue by puku0x** [OnsenUI/OnsenUI#1817]
[Core]
    Onsen UI 2.1.0

[Framework]
    None

[Additional libraries]
    None

These variables are not defined in `onsen-css-components.css` and `onsen-css-components-*.css`
`$material-select-input-text-color`
`$material-select-input-active-color`
`$material-select-input-inactive-color`

**Comment by puku0x** [comment]
Although this is not a solution, but you can ignore above error by setting `silent:true`.

```
/* postcss.config.js */
module.exports = {
  plugins: [
    require('postcss-import'),
    require('postcss-url'),
    require('postcss-cssnext'),
    require('postcss-simple-vars')({
      silent: true
    })
  ]
}
```

**Comment by misterjunio** [comment]
@puku0x Thanks for reporting, on it. Actually we're in the process of dropping Stylus for another styling tool and it will be fixed for that release 👍

**Comment by misterjunio** [comment]
@puku0x We fixed it so I'm closing this now. Thanks again
