### ISSUE TITLE
Cache for page templates in separate HTML-files

### ISSUE THREAD

**Issue by BusinessLoader** [OnsenUI/OnsenUI#1821]
I see performance degradation on the opening page when page templates saved in separate HTML-files.
For example if from page1 (index.html with `<ons-navigator>`) I execute `pushPage()` for new page2 and this page contains tabbar with 3 tabbed pages (tab1, tab2, tab3) and all of these pages stored in separate HTML-files page2.html, tab1.html, tab2.html, tab3.html - I see big time lag before the opening of the page.
If all page templates stored in index.html (with `<ons-template>`) - page2 and its tabs opened very fast.
As I understand Onsen UI load 4 pages (page2.html, tab1.html, tab2.html, tab3.html) each time when page2 should be displayed. After that these files readed and its content appended to DOM in index.html. When I execute `popPage()` for page2 - content of page2.html, tab1.html, tab2.html, tab3.html completely removed from the index.html and these operations (load 4 files, read, append to index.html) repeated when I want show page2 again.
It would be great if you can store loaded external templates in the internal cache to avoid multiple file loading, reading, parsing and appending to the DOM.

**Comment by frankdiox** [comment]
@BusinessLoader We'll do this and probably provide `ons.preload([...])` as well :+1:

**Comment by frandiox** [comment]
This is implemented in master branch. It does not "keep alive" the elements, but caches the template to avoid extra XHR requests.
