### ISSUE TITLE
Onsen UI CSS 

### ISSUE THREAD

**Issue by BusinessLoader** [OnsenUI/OnsenUI#1824]
Hello,

Onsen CSS contains a lot of conflicts - identical properties with different values in the one class. You can find it in the several classes. If you check Onsen CSS with any CSS validator you can see a lot of errors and warnings.

**Comment by frankdiox** [comment]
@BusinessLoader Thanks!
@anatoo Do you think we can do something with this now that we are refactoring the CSS?

**Comment by anatoo** [comment]
@frankdiox Yes, I will refactor CSS to remove conflict.

**Comment by anatoo** [comment]
Refactored css components. So I close this issue.
