### ISSUE TITLE
Bug with React AlertDialog not showing when initially isOpen (Safari only)

### ISSUE THREAD

**Issue by benny-medflyt** [OnsenUI/OnsenUI#1826]
Here is a minimal example that shows the problem:

```
        var rootNode = document.getElementById("app");
        ReactDOM.render(
            <Ons.AlertDialog
                isOpen={true}>
                <div className="alert-dialog-title">
                    Hello
                </div>
            </Ons.AlertDialog>,
            rootNode);
```

This works fine in Chrome. But in Safari, and mobile Safari, the "AlertDialog" does not appear.

It appears that in Safari, the dialogs "_compile" function is being called immediately after it is being created, thus setting the style.display to 'none'. (In Chrome, "_compile" is called at the beginning).

**Comment by mradbourne** [comment]
Workaround: Set the isOpen prop to false in the constructor, then to true in the componentDidMount lifecycle method.

**Comment by avalanche1** [comment]
Not stale IMO
