### ISSUE TITLE
"reveal" animation for Splitter

### ISSUE THREAD

**Issue by frandiox** [OnsenUI/OnsenUI#1830]
@anatoo Currently only "overlay" animation is implemented in the splitter but I remember we also had "reveal" animation for sliding menu. We are deprecating sliding menu soon and it would be nice to port that animation to the new splitter. Do you think it's fine? Also, there are some users asking for it on the forum.

**Comment by anatoo** [comment]
@frankdiox It's good to me.

**Comment by frandiox** [comment]
Implemented in #1916
