### ISSUE TITLE
Deprecate features/components

### ISSUE THREAD

**Issue by frandiox** [OnsenUI/OnsenUI#1831]
@anatoo @asial-matagawa @misterjunio 

We have talked about deprecating some stuff already and I just want to make a list so we don't forget for the next release:

- [x] Theme Roller.
- [x] Stylus-lang.
- [x] `ons-template`: use `template` instead.
- [x] `ons-sliding-menu` (Angular1): we have `ons-splitter`. -- _Added warning_.
- [x] `ons-split-view` (Angular1): we have `ons-splitter`. -- _Added warning_.
- [x] `loadPage` method of `ons-tabbar`.
- [x] `options.refresh` for `popPage`: Do you think we need this in Onsen UI v2? I think `ons-init` and `ons-show` handlers could be enough in Angular1 to refresh the previous page. -- _Added warning_.

Feel free to add or discuss anything else.

**Comment by anatoo** [comment]
👍

**Comment by sdmgeek** [comment]
How to refresh previous page when clicking ons-back-button if "options.refresh for popPage" is deprecated? Just using JavaScript Core v2.2.6.

**Comment by frandiox** [comment]
@sdmgeek What is your use case? Do you just want to run the previous page's controller (Angular controller) again? I think that can be done in a page lifecycle event such as `show`.

**Comment by sdmgeek** [comment]
Thanks for reply~
I'm not using Angular, just using JavaScript.
The use case is that the child page call the server API that may affect its parent page, so I want to refetch from the parent page url to get whole fresh content when clicking the back button.
Is there other way to achieve the refresh?

**Comment by frandiox** [comment]
@sdmgeek `options.refresh` is just removing the parent page and creating it again. I guess you are calling some function on `init` event, so you just need to call the same function on `show`, `hide`, `prepush` events or override the `ons-back-button` behavior (with `onClick` dom property) in order to pass a callback. I think it would be enough with any of these possibilities.

**Comment by sdmgeek** [comment]
Got it.
Is it suggested to use `navigator._pageLoader.unload` to unload the parent page and `insertPage` to insert the page again? 
In addition, are there any ways to check the content of page going to be pushed at the `prepush` event callback?

**Comment by frandiox** [comment]
@sdmgeek `pageElement._destroy(); pageElement.remove();` is probably enough. You can do that and then insert it again but the idea is that you update the parent page before popping. I think you mean `prepop` event. You can simply get the navigator and access to the previous page with `navigator.pages[navigator.pages.length - 2]` or something similar.

**Comment by sdmgeek** [comment]
@frandiox 
Really appreciate your help!
Would it be more constant if `navigator` also have method like `removePage` to remove page from navigator?

**Comment by asial-matagawa** [comment]
Related: #1814, #2053

**Comment by frandiox** [comment]
Even though `ons-template` is not deprecated, `template` is already supported and we can keep the other one for backward compatibility. Its implementation is quite small. Also, `navigator.removePage` is already implemented. Closing this.

**Comment by rgins16** [comment]
@frandiox I don't understand why refresh for popPage was removed. In my case, the user is on a page. They click the sign in button which pushes the login page. After signing in, the sign in popped. Then I would like for the original page to be refreshed.
