### ISSUE TITLE
Tappable and ripple effects

### ISSUE THREAD

**Issue by BusinessLoader** [OnsenUI/OnsenUI#1836]
Hello,

As I see - `tappable` attribute is exist only for some Onsen objects (`ons-list-item` and maybe some other) and have different visual effects for iOS (flash) and Android (ripple).
Also additional `ons-ripple` element is available but this effect works identically for iOS and Android.
IMO visual feedback for user interaction is a very important UX/UI pattern for mobile platforms and can be applied to several objects on the screen.
Maybe it would be more correct to have some universal element (`ons-tappable`) which can be used with any `div` (as `ons-ripple`) and which will be automaticaly styled for each platform (as `tappable` attribute)?

**Comment by frandiox** [comment]
@anatoo What do you think about this?

**Comment by anatoo** [comment]
It it good to have. 👍

**Comment by BusinessLoader** [comment]
Moreover, I hope you keep in mind [this my question](https://community.onsen.io/topic/1212/how-to-disable-tappable-effect).
Maybe some `nontappable` attribute for some sub-objects? :wink:

**Comment by nikitaMe1nikov** [comment]
It will be nice. For example, as in ReactNative there is Touchable a component. :+1:

**Comment by AndersSchultz** [comment]
Just wanted to add my vote for this suggestion. I am having a situation where this is much needed as well.
