### ISSUE TITLE
Angular 1 // No longer able to pass data in the options for navigator.pushPage

### ISSUE THREAD

**Issue by rgins16** [OnsenUI/OnsenUI#1854]
__Environment__ 

```
[Core]
    onsenui 2.0.5 ///// AFTER UPGRADING FROM 2.0.4

[Framework]
    angular1 1.5.11

[Browser]
    Mobile - Safari /// iPhone 5C
    Desktop - Chrome Latest Version
    I assume many more too
```

__Encountered problem__
After upgrading OnsenUI from 2.0.4 to 2.0.5, I am no longer able to pass data through the navigator. myNavigator.topPage is now empty in the receiving controller.

__How to reproduce__
See my comment below.

__Notes__
In all previous versions on OnsenUI, I had no problem with this. This problem has only occurred once I upgraded to OnsenUI v2.0.5.

**Comment by rgins16** [comment]
I am not able to get a codePen working, but I have gotten the following code to follow the behavior of the bug I have described above:

HTML:
```
<ons-navigator var="myNavigator" page="page1.html"></ons-navigator>

<ons-template id="page1.html">
  <ons-page ng-controller='FirstController'>
    <ons-toolbar>
      <div class="center">Page 1</div>
    </ons-toolbar>

    <p>This is the first page.</p>

    <ons-button ng-click="navigate();">Push page</ons-button>
  </ons-page>
</ons-template>

<ons-template id="page2.html">
  <ons-page ng-controller='FirstController'>
    <ons-toolbar>
      <div class="left"><ons-back-button>Back</ons-back-button></div>
      <div class="center">{{ myNavigator.topPage.data.title }}</div>
    </ons-toolbar>

    <p>This is the second page.</p>
    <p>This is the event: {{event}} </p>
  </ons-page>
</ons-template>
```

JavaScript:
```
ons.bootstrap()
.controller('FirstController', ['$scope', function($scope) {
  
  var object = {
    one: 'one',
    two: 'two',
    three: 'three'
  }
  
  var string = 'the string';

  $scope.navigate = function(){
    myNavigator.pushPage('page2.html', { 
      animation: 'lift', 
      data: {
        event: object
      }
    });
  };
}])
.controller('SecondController', ['$scope', function($scope) {

  $scope.event = theNavigator.topPage.data.event;
}]);
```

**Comment by frandiox** [comment]
@rgins16 Thanks for reporting. I'm curious, did you have any problem with the "Report an issue" button in the tutorial app? There's no need to create a Codepen.

About the issue itself, I'll check what changed in 2.0.5 to make this change, but in any case the correct way to do this in v2 is using page lifecycle events. You can easily wait for it with `ons-init` handler. Simply add `<ons-page ons-init="event = $event.target.data.event">` to your second page and it'll work normally.

**Comment by rgins16** [comment]
I didn't realize I could report an issue in the tutorial app. I basically translated my own code to the tutorial app to get a working version for you.

Thanks for the temp fix. I had previously decided to wait for a fix, but tinkered with 
`myNavigator.once('postpush', function(){
    $scope.event = myNavigator.topPage.data.event;
});`

My problem with this was the event scope variable didn't reflect it's changes in the DOM.

**Comment by frandiox** [comment]
@rgins16 The problem in the code is that Angular controller runs before the new page is ready. That means that, by the time you access to `myNavigator.topPage.data`, nothing exists yet. It would work by using a `$timeout` as well, but to make sure everything is ready you can just use [page lifecycle events](https://onsen.io/v2/docs/guide/angular1/#page-lifecycle) (check also the "event handling" section).

Therefore, instead of doing:

```
<ons page>

.controller(..., function($scope) {
  // init data

  // custom functionality
});
```

Just do:

```
<ons-page ons-init="initData($event)">

.controller(..., function($scope) {
  $scope.initData = function(event) {
    // init data (event.target is the new page)
  };

  // custom functionality
});
```

**Comment by rgins16** [comment]
@frandiox Thanks for the help.
