### ISSUE TITLE
Core | Fab && Speed-dial issue: position problem in iOS 8

### ISSUE THREAD

**Issue by misterjunio** [OnsenUI/OnsenUI#1857]
__Environment__ 

```
[Core]
    onsenui 2.1.0

[Framework]
    none

[Framework binding]
    none

[Additional libraries]
    none

[Platform]
    Mobile - iOS 8.4.1

[Browser]
    Mobile - iOS Safari
```

__Encountered problem__
`position="bottom"` not working properly on `fab` and `speed-dial` components.

__How to reproduce__
Open the respective core example in iOS 8 Safari. Bottom buttons appear cut.

**Comment by asial-matagawa** [comment]
@misterjunio 
It could not be reproduced in iPhone 5s Simulator (with iOS 8.4).
This might be a device-dependent bug.

![2017-03-09 13 34 35](https://cloud.githubusercontent.com/assets/19771915/23737323/a8f3dce6-04d5-11e7-8adf-34f0568e8520.png)

**Comment by misterjunio** [comment]
@asial-matagawa The worst kind 😬

**Comment by asial-matagawa** [comment]
@misterjunio 
Sorry, the screenshot I pasted above is based on [a recent revision](https://github.com/OnsenUI/OnsenUI/tree/9ba11077ce7c7cfe8d7778993b4f0bfbefd15c14). It is not based on 2.1.0.
It seems that this issue has been already fixed.

Closing this.
