### ISSUE TITLE
Core | Grid issue: mixed alignments problem in iOS 8

### ISSUE THREAD

**Issue by misterjunio** [OnsenUI/OnsenUI#1858]
__Environment__ 

```
[Core]
    onsenui 2.1.0

[Framework]
    none

[Framework binding]
    none

[Additional libraries]
    none

[Platform]
    Mobile - iOS 8.4.1

[Browser]
    Mobile - iOS Safari
```

__Encountered problem__
Mixed alignments not working properly on grid component.

__How to reproduce__
Open the core example in iOS 8 Safari. Last grid Mixed Vertical Alignment is broken.

**Comment by asial-matagawa** [comment]
@misterjunio 
This seems to be because the line below removes `display: -webkit-flex;` (which is required for iOS 8 and older) from the selector `ons-row`.

https://github.com/OnsenUI/OnsenUI/blob/9ba11077ce7c7cfe8d7778993b4f0bfbefd15c14/gulpfile.babel.js#L379
