### ISSUE TITLE
Core | Popover issue: fading animations not working

### ISSUE THREAD

**Issue by misterjunio** [OnsenUI/OnsenUI#1859]
__Environment__

```
[Core]
    onsenui 2.1.0

[Framework]
    none

[Framework binding]
    none

[Additional libraries]
    none

[Platform]
    Mobile - Android
    Mobile - iOS

[Browser]
    Mobile - Android Chrome
    Mobile - iOS Safari
```

__Encountered problem__
Fading animations don't change anything.

__How to reproduce__
Open the core example in any device. Add one of the fading animations to the popover. Nothing is changed.

**Comment by asial-matagawa** [comment]
@misterjunio 
I have checked them but `show` method and `animation` attribute of `ons-popover` worked correctly.
I guess you might have input wrong arguments to `show` method.

`show` method accepts two types of arguments:
- `show(target, [options])`
- `show(options)` <---- Undocumented!
Note that the example file of `ons-popover` uses `show(options)`:
https://github.com/OnsenUI/OnsenUI/blob/85c4e233af9c0eb42960a928ebb2272d77909e62/examples/popover/index.html#L19

If you use `show(options)`, you cannot pass 2nd argument.
For example:

```js
// works
app.popover.show(e, {animation: 'fade-ios', animationOptions: {duration: 3.0, delay: 0.4, timing: 'ease-in'}});

// works
app.popover.show({target: e, animation: 'fade-ios', animationOptions: {duration: 3.0, delay: 0.4, timing: 'ease-in'}});

// does not work
app.popover.show({target: e}, {animation: 'fade-ios', animationOptions: {duration: 3.0, delay: 0.4, timing: 'ease-in'}});
```

Closing this.
