### ISSUE TITLE
Core | Range issue: not sliding until the maximum

### ISSUE THREAD

**Issue by misterjunio** [OnsenUI/OnsenUI#1862]
__Environment__

```
[Core]
    onsenui 2.1.0

[Framework]
    none

[Framework binding]
    none

[Additional libraries]
    none

[Platform]
    Mobile - Android
    Mobile - iOS

[Browser]
    Mobile - Android Chrome
    Mobile - iOS Safari
```

__Encountered problem__
The element does not slide until the end (a few pixels missing).

__How to reproduce__
Open the core example in any device. Slide the range to the maximum. It does not go to the end (in iOS is not as noticeable because of its styling but I believe it happens as well).

**Comment by asial-matagawa** [comment]
@misterjunio 
I think this is not a bug but what should be improved.
@anatoo is improving CSS components now, so I will ask him to improve this style problem.

**Comment by asial-matagawa** [comment]
Here is a screenshot of the problem:
![2017-03-13 15 01 51](https://cloud.githubusercontent.com/assets/19771915/23843268/0950b994-07fe-11e7-9ad7-c91d4fa5d867.png)
