### ISSUE TITLE
Proposal: Adopt visual design spec.

### ISSUE THREAD

**Issue by anatoo** [OnsenUI/OnsenUI#1873]
Currently we don't have visual design spec for Onsen UI. So the components' visual design is broken from time to time and it is harder to improve it.

To fix this problem, I want to manage visual design spec for components. To be more specific, I would like to add [sketchapp](http://sketchapp.com) file that have each components' visual design in Onsen UI repository.

@frandiox @masahirotanaka @asial-matagawa @misterjunio Any thought?

**Comment by asial-matagawa** [comment]
@anatoo
I agree with your proposal 👍

**Comment by masahirotanaka** [comment]
@anatoo ありがとうございます。Onsen UIのデザインはiOSとAndroidの標準ガイドラインに従っているので、どちらかというと標準UIとの対比を行う資料が必要なのではないかなと思っています。実際に実装の際に使える公式ガイドラインというのは存在しないということですか？

**Comment by anatoo** [comment]
@masahirotanaka フィードバックありがとうございます。

Onsen UIのデザインについてですが、基本的にiOSとAndroidのガイドラインに従おうとしているのですが、実際にはその時コンポーネントを実装した人のデザインがそのまま使われていて、プラットフォーム標準のUIとは微妙に違うものが結構あります。 例えばselectコンポーネントのデザインはOSの標準のUIとはあまり合致していないように見えます。

Onsen UIのデザインが微妙に標準と違うのは意図通りなのかがよくわからないし、またコンポーネントのデザインが壊れていても元の意図通りのデザインがわからないので直したり改善したりしづらいと思っています。またコンポーネントのビジュアルデザインを改善するには直接コンポーネントをいじっていくのではなくまずSketchか何かでビジュアルデザインを作ってからコンポーネントの実装を直すほうがやりやすいのでこういう提案をしました。

**Comment by masahirotanaka** [comment]
返信遅くなりました。今作成段階のものを見ましたが、上手くまとめて頂いていると思います。
確かに細かい部分でのネイティブUIとの準拠違いがありますが、個人的には、それ以上にコンポーネントの量をむしろデベロッパーが期待していると考えており、現状のクオリティ（ons-select以外のanatoo作成のもの）は維持しつつも、工数は新規CSSスタイルに振り分ける方が望ましいと考えています。

**Comment by anatoo** [comment]
いや、ons-selectに限らず今はほとんどのコンポーネントが自分が作ったものではないです。また自分が作ったものでもiOSがバージョンアップしたせいで古くなったものがいくつかあります。Material Designのコンポーネントなんかはほとんど自分は触っていません。

https://twitter.com/clockmaker/status/778424104793681920

こういうフィードバックがありますが実際自分も同じような感想を持っています。Onsen UIのコンポーネントは見よう見真似感があるのでそれを直してから新しいコンポーネントを追加していきたいと思っていますがどうでしょうか？

**Comment by masahirotanaka** [comment]
ありがとうございます。

直接相談させて頂いたとおり、Sketchを使った既存コンポーネントに対してのビジュアル定義（アニメーションは原則として今回の作業スコープ外）をお願いいたします。同時に、今後追加するコンポーネントについても定義をよろしくお願い致します。

本件はクローズします。
