### ISSUE TITLE
Angular2 | Splitter issue: Error throw when collapse and swipeable

### ISSUE THREAD

**Issue by adamkozuch** [OnsenUI/OnsenUI#1876]
__Environment__

```
[Core]
  onsenui latest
  
[Framework]
  angular2 2.0.0

[Framework binding]
 angular2-onsenui latest

[Platform]
  Desktop - OS X 10.12.0 64-bit

[Browser]
  Desktop - Chrome 56.0.2924.87 on OS X 10.12.0 64-bit
```

__Encountered problem__
When using `collapse` and `swipeable` attributes the `splitter-side` throws a console error.

__How to reproduce__
See the tutorial link.

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<app></app>
```

- __JS__

```typescript
import {
  Component,
  OnsenModule,
  NgModule,
  CUSTOM_ELEMENTS_SCHEMA
} from 'angular2-onsenui';
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';

@Component({
  selector: 'ons-page',
  template: `
    <ons-toolbar>
      <div class="center">Content Page</div> 
    </ons-toolbar>
    <div class="content">
      
    </div>
  `
})
class ContentPageComponent {
}

@Component({
  selector: 'ons-page',
  template: `
    <ons-toolbar>
      <div class="center">Left Page</div> 
    </ons-toolbar>
    <div class="background"></div>
    <div class="content">
      
    </div>
  `
})
class SidePageComponent {
}

@Component({
  selector: 'app',
  template: `
  <ons-splitter>
    <ons-splitter-side [page]="sidePage" side="left" width="200px" style="border-right: 1px solid #ccc" collapse swipeable>
    </ons-splitter-side>

    <ons-splitter-content [page]="contentPage">
    </ons-splitter-content>
  `
})
export class AppComponent {
  sidePage = SidePageComponent;
  contentPage = ContentPageComponent;
}

@NgModule({
  imports: [OnsenModule],
  declarations: [AppComponent, SidePageComponent, ContentPageComponent],
  bootstrap: [AppComponent],
  entryComponents: [SidePageComponent, ContentPageComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
class AppModule { }

platformBrowserDynamic().bootstrapModule(AppModule);
```

**Comment by misterjunio** [comment]
I have traced down the problem to [these lines](https://github.com/OnsenUI/OnsenUI/blob/38aac734487f526f6fe2d993d368fe0adde340e8/core/src/elements/ons-splitter/index.js#L155-L157). For some reason in Angular2 when the `modechange` event is first detected on the `ons-splitter-side` the `e.target.parentNode` (i.e. the `ons-splitter`) is already initialized but it doesn't have `ons-splitter-content` yet. So when the `_layout()` function checks for `this.content` it gets `undefined`. In the other bindings the element is already fully loaded with content and mask. @anatoo @asial-matagawa can you figure out why is Angular2 calling this "too soon"? Also shouldn't it work anyway with the `contentReady()` call? I thought this method was supposed to wait until the component and its children were completely initialized.

**Comment by asial-matagawa** [comment]
@misterjunio 
It is due to the design of Angular and `attributeChangedCallback` of `ons-splitter-side`.

Angular compiles the following code
```html
  <ons-splitter>
    <ons-splitter-side [page]="sidePage" side="left" width="200px" style="border-right: 1px solid #ccc" collapse swipeable>
    </ons-splitter-side>

    <ons-splitter-content [page]="contentPage">
    </ons-splitter-content>
</ons-splitter>
```
into something like
```js
const splitter = document.createElement('ons-splitter');
const splitterSide = document.createElement('ons-splitter-side');
splitterSide.setAttribute('side', 'foo');
splitterSide.setAttribute('width', 'foo');
splitterSide.setAttribute('style', 'foo');
splitterSide.setAttribute('collapse', 'foo');
splitterSide.setAttribute('swipeable', 'foo');
const splitterContent = document.createElement('ons-splitter-content');
splitter.appendChild(splitterSide);
splitter.appendChild(splitterContent);
```
(maybe this is not accurate)

Each time `splitterSide.setAttribute` is called, `ons-splitter-side` runs `this._update()`:
https://github.com/OnsenUI/OnsenUI/blob/38aac734487f526f6fe2d993d368fe0adde340e8/core/src/elements/ons-splitter-side.js#L500

But at that time `splitterContent` is not yet appended to `splitter`, so `this._update()` leads to `undefined` on `this.content`.

We need MutationObserver or Shadow DOM for fixing this problem and I think it cannot be quickly fixed.
For the time being we have to use `[attr.collapse]="'collapse'"` and `[attr.swipeable]="'swipeable'"`.

**Comment by asial-matagawa** [comment]
@misterjunio 
Ah, maybe we can wrap `this._update(name, current);` in `attributeChangedCallback` with `contentReady`.
https://github.com/OnsenUI/OnsenUI/blob/38aac734487f526f6fe2d993d368fe0adde340e8/core/src/elements/ons-splitter-side.js#L500

This might be a possible workaround (but not sure)

**Comment by misterjunio** [comment]
@asial-matagawa That seems to fix it indeed. But I don't get it, doesn't that wait for `ons-splitter-side` to be ready and not `ons-splitter-content`?

**Comment by asial-matagawa** [comment]
@misterjunio 
`contentReady(this._content, () => { ~~~~ });` might wait for `ons-splitter-content` instead of `ons-splitter-side`. We can change the target of `contentReady`.
Sorry if it does not work.

**Comment by asial-matagawa** [comment]
Ah, `this._content` is `undefined` at that time... Maybe we can try `this.parentNode` (= `ons-splitter`) but anyway we need to thoroughly investigate the code to completely solve this problem.

**Comment by misterjunio** [comment]
@asial-matagawa When I said

> That seems to fix it

I actually tried it and it worked 😄

**Comment by asial-matagawa** [comment]
@misterjunio 
Oh, I see. Thank you!

**Comment by asial-matagawa** [comment]
@misterjunio 
>But I don't get it, doesn't that wait for ons-splitter-side to be ready and not ons-splitter-content?

Maybe waiting `ons-splitter-side` is equivalent to waiting `ons-splitter-content`.
What is important is delaying the evaluation of `this._content`.

**Comment by misterjunio** [comment]
@asial-matagawa Yes you're right. I will create a PR with the fix then 👍

**Comment by asial-matagawa** [comment]
@misterjunio 
If you create a PR for this issue, I would appreciate if you fork `production` branch.
Now we have `production` branch, so we can immediately release `angular2-onsenui@1.0.0-rc.7` for the Monaca templates which @adamkozuch maintains.

**Comment by sfstar** [comment]
So (not to be inpolite) can anybody tell me about the status of this issue?
Since I'm currently experiencing this while using:
    "angular2-onsenui": ">=1.0.0-rc.5",
    "core-js": "2.4.1",
    "onsenui": "2.2.x",

**Comment by asial-matagawa** [comment]
@sfstar 
We could fix this issue thanks to #1892 but the fix for this is delayed now.
Please be patient until some other tasks are completed.

**Comment by sfstar** [comment]
could it be possible that this issue also causes angular2 data binding to stop working?
I used Monaca Create to create the splitter template of Onsen-UI + Angular 2.
And the data binding appears to be broken while the exact same code works in default angular or after creating an minimalistic Onsen UI Angular template project.

CODE: 


@Component({
  selector: 'ons-page[home]',
  template: `
      <ons-page>
            <div> just testing the data bindings of angular 2 with onsen-UI </div>
           <div>{{msg.message_id}}</div>
     </ons-page>
  `,
  styles: [require('../../css/home.css')]
})
export class HomePage {

  bindingtest: string = 'testing data-binding';
  constructor(@Inject(forwardRef(() => MyApp)) private app : MyApp) {
  }
}


The first div content is shown while the divs content with the binding isn't present.

**Comment by asial-matagawa** [comment]
@sfstar 
>could it be possible that this issue also causes angular2 data binding to stop working?

Yes, it could happen.
We are planning to fix issues on Onsen UI with Angular and support Angular 4 for a month.

**Comment by sfstar** [comment]
@asial-matagawa 
I'm sorry but the meaning of the "for a month." part of your sentence gets lost in translation.
Did you mean that the issues will be fixed in one month (<month) or that it will be achieved after a month of time? (>month)

**Comment by asial-matagawa** [comment]
@sfstar 
Ah, what I meant is `the issues will be fixed in one month (<month)`.
Sorry for my bad English.

**Comment by sfstar** [comment]
@asial-matagawa 
It turns out that my initial assumption regarding the relation between this bug and Angular2 data-binding isn't correct.
The reason why the binding stopped working turned out to be the app.load(<page>) functions unability to load a specific page. Due to it being unable to resolve the pages DI (since no provider was specified in the page-class).
This resulted in the app.load() function to try to load a page which it wasn't capable of.
However, the function did not throw any error in this case, which might be a improvement that could be included in the upcoming Angular4 + Onsen-UI release.

In short:
if a page used a constructor like this:
`export class myPage
{
   constructor(@Inject(forwardRef(() => MyApp)) private app : MyApp, private otherClass: OtherClass) {}
}`
without specifying a provider like so:
`@Component({
    selector: 'ons-page[somePage]',
    template: require('../../html/somePage.html'),
    styles: [require('../../css/somePage.css')],
    providers: [OtherClass],
})`

It would throw no errors when trying to load this page, while the page isn't loaded.
Then when a you navigate (by a working link) to another page, it results in emptyness where the {{variables}} are located. (While they worked before an unloadable link was pressed).

**Comment by asial-matagawa** [comment]
@sfstar 
Thank you for the information!
Since we finished releasing `onsenui@2.3.0`, `react-onsenui@1.3.0` and `vue-onsenui@2.0.0-beta.6`, we will start dealing with `angular2-onsenui`.
