### ISSUE TITLE
why <ons-dialog id="xxxxxx" cancelable> on android(4.1.2) doesn't work

### ISSUE THREAD

**Issue by bailinlu** [OnsenUI/OnsenUI#1877]
code1:
   
```
<ons-dialog` id="xxxxxx" cancelable>
       <........>
</ons-dialog>
```
when I test on android(4.1.2)'s device ,
I touch a part other than dialog but it doesn't close dialog.
but there is no problem on ios and android(4.4) or higher version
why.........

code2:
```
<ons-splitter>
<ons-splitter-side id="menu" side="left" width="220px" collapse>
......
</ons-splitter-side>
<ons-splitter-content id="content" page="home.html"></ons-splitter-content>
</ons-splitter>

```
when I test on android(4.1.2)'s device ,
I touch menu but columns not display.
but there is no problem on android(4.4) or higher version
why.........

**Comment by asial-matagawa** [comment]
@bailinlu 
Thank you for reporting.
Onsen UI might not work in old Android Devices since Onsen UI supports only Android 4.4+:
https://github.com/OnsenUI/OnsenUI#browser-support

Closing this.

**Comment by bailinlu** [comment]
but 
`<ons-list>
<ons-list-header>
<ons-list-item>
<ons-scroller>`
and so on,they are can be worked on  android(4.1.2)'s device.

**Comment by asial-matagawa** [comment]
I'm glad to hear that. Thank you!
