### ISSUE TITLE
WARNING:./android/base/files/IniFile.cpp:155:Failed to process .ini file

### ISSUE THREAD

**Issue by fWd82** [OnsenUI/OnsenUI#1879]
Hello 
I am getting bellow errors and warning upon triggering: 
`monaca run android`
Whole log from CMD is: 

> D:\HybridApp>monaca run android
ANDROID_HOME=C:\Users\fWd82\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\Java\jdk1.8.0_60
No target specified and no devices found, deploying to emulator
No emulator specified, defaulting to Nexus_5X_API_23_x86
Waiting for emulator to start...
WARNING:./android/base/files/IniFile.cpp:155:Failed to process .ini
s\fWd82\.android\avd\Nexus_5X_API_23_x86.avd\config.ini for reading.
WARNING:./android/base/files/IniFile.cpp:155:Failed to process .ini
s\fWd82\.android\avd\Nexus_5X_API_23_x86.avd\config.ini for reading.
WARNING:./android/base/files/IniFile.cpp:155:Failed to process .ini
s\fWd82\.android\avd\Nexus_5X_API_23_x86.avd\config.ini for reading.
WARNING:./android/base/files/IniFile.cpp:155:Failed to process .ini
s\fWd82\.android\avd\Nexus_5X_API_23_x86.avd\config.ini for reading.
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
This application has requested the Runtime to terminate it in an unu
Please contact the application's support team for more information.

__Environment__ 
Windows 8.1
Android Huawei C3 Android 4.2.2.
Monaca 2.17

```
[Core]
    onsenui 2.1.0

[Additional libraries]
    jQuery 3.1.1

[Platform]
    Mobile - Android 4.2.2
    Desktop - Windows 8.1

[Browser]
    Desktop - Chrome 55.0.2883.75

```
Was busy developing and it sudden came out. I was debugging it with my Android Huawei C3. 
However
`monaca preview `
works great on Chrome browser.

**Comment by asial-matagawa** [comment]
@fWd82 
We have a repo for Monaca CLI, so I moved this issue to https://github.com/monaca/monaca-cli/issues/79 .

Closing this.
