### ISSUE TITLE
Angular 1 // Bug when trying to pop a pushed page that contains tabbars

### ISSUE THREAD

**Issue by rgins16** [OnsenUI/OnsenUI#1884]
[Core]
    after upgrading from onsenui 2.0.4 to 2.0.5

[Framework]
    angular1 1.5.11

[Additional libraries]
    jQuery 2.2.4

[Platform]
    Desktop - Windows 10

[Browser]
    Desktop - Chrome latest version

__Encountered problem__
After upgrading from 2.0.4 to 2.0.5, I experience a bug when popping a page (that was previously pushed) that has an ons-tabbar on it.

The error I encounter is:
![image](https://cloud.githubusercontent.com/assets/16677164/24211659/1ec8c760-0f03-11e7-9b7d-ba27cf84de85.png)

__How to reproduce__
Here is my 2.0.4 code:
```
ons-page(ng-controller='PurchaseController')
  ons-toolbar
    div.left
      ons-back-button.blue Back
    div.center
      span.blue Event Information

  div(ng-if='event !== null')

    ons-tabbar
      ons-tab(label='Event' page='eventInfo' active)
      ons-tab(label='Instructor' page='instructorInfo')
      ons-tab(label='Purchase' page='purchaseInfo')

    ons-template#eventInfo
      event-info(event='event')

    ons-template#instructorInfo
      instructor-info(event='event')

    ons-template#purchaseInfo
      purchase-info(event='event', user='user')

  ons-bottom-toolbar
    div.bottom-bar__line-height.textAlignCenter.blue XellNow

  ons-modal#loadingModal(var='loadingModal')
    p Loading Event Info...
    p
    ons-icon(icon='ion-load-c' spin)
```

After upgrading to 2.0.5, I had to move the tabbar templates with the components to index.jade directly under body. The tabbar and its tabs functioned correctly after the page was pushed, but the above error occured when I popped the page via the back button.

If I remove the components and leave nothing under the ons-template, I do not receive the error - I assume this is because I removed the ons-page.

Edit:
Just for reference, here is the jade code from the templateUrl file of one of the components:
```
ons-page

  div.textAlignCenter

    p Price: ${{ event.price }}

    p.blue(ng-show='purchaseStatus !== 200') {{ blockPurchaseDescription }}

    form#paymentForm(ng-show='purchaseStatus === 200')
      div#dropin-container
      button.button(type='submit') Purchase

      br
      br

      p Powered By:
      img.textAlignCenter(ng-src='/getBraintreeSticker?decache=' + Math.random() + '')

  ons-modal#paymentModal(var='paymentModal')
    p Processing Your Purchase...
    p
    ons-icon(icon='ion-load-c' spin)


```

**Comment by rgins16** [comment]
@frandiox was I too vague in the explanation of my problem?

**Comment by frandiox** [comment]
@rgins16 Oh, I think @misterjunio is already looking at this, don't worry :)
For the next time, if possible please do use https://tutorial.onsen.io/ and hit `Report an issue`. We will get a working example with the code.

**Comment by rgins16** [comment]
@frandiox I apologize, but I'm confused by your statement. I encountered the error in my own project. Do you want me to copy/paste my code from my project to the tutorial, and then hit 'Report an issue'?

**Comment by frandiox** [comment]
@rgins16 Yes, it's really useful to provide a **minimum** app where the issue is reproduced. In order to do that, you can choose a similar template in the tutorial app (navigator/tabbar/splitter/dialogs...) and modify it until the issue is visible. Then, you can report it directly from there and we will get a link to it.

**Comment by rgins16** [comment]
Got it. I will do that from now on. :)
