### ISSUE TITLE
icon size with 1g,1x,2x,3x.... not working

### ISSUE THREAD

**Issue by cyciopes** [OnsenUI/OnsenUI#1890]
```
[Core]
    onsenui 2.2.0

[Framework]
    none
```

ons-icon with size=lg, 2x, 3x, 4x, 5x can not working. Even in official tutorial. 
[icon tutorial](https://onsen.io/v2/docs/js/ons-icon.html#tutorial)

**Comment by cyciopes** [comment]
seems size=lg, 2x, 3x, 4x, 5x is only work for fa-icon.

**Comment by frandiox** [comment]
This only occurs with `md-` icons. I guess this was originally prepared for `fa-` and `ion-` ones. The `.zmdi` class ni material icons overwrites the `font-size` from this feature.
