### ISSUE TITLE
ons-fab is hidden by ons-tabbar

### ISSUE THREAD

**Issue by puku0x** [OnsenUI/OnsenUI#1896]
__Environment__ 

```
[Core]
    onsenui 2.2.1

[Framework]
    angular4

[Framework binding]
    angular2-onsenui 1.0.0-rc.6

[Additional libraries]
    none

[Platform]
    Mobile - iOS 10.1.1
    Desktop - macOS Sierra

[Browser]
    Mobile - Android WebView
    Mobile - iOS UIWebView
    Desktop - Chrome 55.0.2883.75
    Desktop - Safari 10.0 (12602.1.50.0.10)
```

__Encountered problem__

`ons-fab` is hidden by `ons-tabbar`.

![image](https://cloud.githubusercontent.com/assets/2607019/24416315/56074f78-141f-11e7-8e1f-0c4a74f55d93.png)

__How to reproduce__

Just put a `ons-fab` in  a tab page with `position="bottom"`.

I think this can be solved by changing from `position:fixed` to `position:absolute`.

```
/* EXAMPLE */
.fab--bottom__right {
  top: auto;
  bottom: 20px;
  right: 20px;
  left: auto;
  position: absolute;  /* HERE ! */
}
```

**Comment by frandiox** [comment]
@puku0x Just put it at the tabbar level, not inside its pages. [Example here](https://codepen.io/frankdiox/pen/evPrYN?editors=1000). I think `position: absolute` does not fix it in the desired way since it would be located inside the page content, not over the tabbar.

**Comment by puku0x** [comment]
@frandiox Thank you for your advice. 
The example is simple and easy to understand for me.

However, I would like to put a FAB in a tab page content like Hangouts app.
Is there any way to realize it without breaking Onsen UI's design phylosophy ?

![image](https://cloud.githubusercontent.com/assets/2607019/24438106/053e84b0-1480-11e7-9213-8120d9276e35.png)

**Comment by frandiox** [comment]
@puku0x Oh, I didn't know it was used like that in a native app. Let's see what @anatoo thinks about it. Perhaps is fine to use `absolute` then if it doesn't break anything.

**Comment by puku0x** [comment]
@frandiox Thank you !

**Comment by anatoo** [comment]
@frandiox I think it's fine to use `absolute`.
