### ISSUE TITLE
Angular1 | Lazy-repeat issue: list does not update correctly on delegate refresh with a dynamic countItems variable when the new value is lower than the previous value

### ISSUE THREAD

**Issue by rgins16** [OnsenUI/OnsenUI#1899]
__Environment__

  
```
[Core]
  onsenui latest
  
[Framework]
  angular1 1.5.5

[Framework binding]
 angular1-onsenui latest

[Platform]
  Desktop - Windows 10 64-bit

[Browser]
  Desktop - Chrome 56.0.2924.87 on Windows 10 64-bit
```

__Encountered problem__
  I've finally decided to upgrade my project from OnsenUI@2.0.4 to latest. It has fixed many of my issues but also created many more. Hence all my bug reports (-_-)

ons-lazy-repeat only updates correctly with a dynamic countItems variable when the variable is a greater value than it was previously. The ons-lazy-repeat does not update correctly when the new variable is less than it was previously. I've created a sample app which is very similar to my project. In my project, the number of items in the ons-lazy-repeat changes frequently. I have a calendar, and when a certain day is clicked, certain items show up in the ons-lazy-repeat. This worked perfectly before I upgraded from 2.0.4 to latest.

I'm using ons-lazy-repeat because there can potentially be thousands of items in the list

__How to reproduce__
See the sample app I provided. 

Click the refresh button _**a lot**_.

Don't forget to check the console.

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<ons-page ng-controller="ListController">
  <ons-toolbar>
    <div class="center">Lists</div>
    <div class="right">
      <ons-toolbar-button ng-click="refreshDelegate();">Refresh</ons-toolbar-button>
    </div>
  </ons-toolbar>

  <ons-list>
    <ons-list-item ons-lazy-repeat="delegate">{{ item }}</ons-list-item>
  </ons-list>
</ons-page>
```

- __JS__

```javascript
ons.bootstrap()
  .controller('ListController', ['$scope', function($scope) {
    
    $scope.randomNumber = 1;
    
    $scope.delegate = {
      configureItemScope: function(index, itemScope) {
        itemScope.item = 'Item ' + index;
      },
      countItems: function() {
        console.log('in countItems() ' + $scope.randomNumber);
        return $scope.randomNumber;
      }
    };
    
    $scope.refreshDelegate = function(){
      
      //random Number between 1 and 6
      $scope.randomNumber = Math.floor(Math.random() * 6) + 1;
      console.log('in refreshDelegate()' + $scope.randomNumber);
      $scope.delegate.refresh();
    };
  }]);
```

**Comment by frandiox** [comment]
@rgins16 Thanks for reporting! I believe this issue is the same as #1871 . To be honest, the new lazyRepeat refresh was made to update the currently rendered items when their content change. I see now that some developers also use it to remove rendered items so we'll try to support this use case :+1:
