### ISSUE TITLE
Feature Request: ons-lazy-repeat functionality similar to Angular 1  ng-repeat-start and ng-repeat-end

### ISSUE THREAD

**Issue by rgins16** [OnsenUI/OnsenUI#1900]
I am using an ons-lazy-repeat in my app. I would like to include a new line in between each item in the list to provide some visual separation for the user. I can do this in an Angular 1 list by using `ng-repeat-start` instead of `ng-repeat`, and at the end of the list using `<br ng-repeat-end/>`. Can this functionality be added to ons-lazy-repeat?

Here is a jade example of using ng-repeat-start and ng-repeat-end:
```
ons-list
  ons-list-item(modifier='nodivider' ng-repeat-start='event in events')

    div

      p {{ event.eventName }}
      p {{ event.description }}

  br(ng-repeat-end)
```

**Comment by frandiox** [comment]
@rgins16 Thanks for the input. We don't want to make an ngRepeat substitute with LazyRepeat. In fact, it is not supposed to be a simple looping tool and should be used only in few situations. That said, I think you can still achieve what you want by simply wrapping everything in a `div`. Check [this pen](https://codepen.io/frankdiox/pen/ryoMma?editors=1010). It could also be achieved with CSS, but right now LazyRepeat do not support margins so the scroll could break. Hope the example helps.

**Comment by rgins16** [comment]
@frandiox Thanks! I finally got around to implementing this. You pen was very helpful.
