### ISSUE TITLE
Angular1 | Switch issue: $scope.$watch does not successfully watch switch changes

### ISSUE THREAD

**Issue by rgins16** [OnsenUI/OnsenUI#1913]
__Environment__
```
[Core]
  onsenui 2.2.1
  
[Framework]
  angular1 1.5.5

[Framework binding]
 angular1-onsenui latest

[Platform]
  Desktop - Windows 10 64-bit

[Browser]
  Desktop - Chrome 56.0.2924.87 on Windows 10 64-bit
```

__Encountered problem__
I've defined three ons-switches using an ng-model object variable with three properties to represent the true/false of the three ons-switches. $scope.$watch does not catch changes of the ons-switch. 

__How to reproduce__
Flip the switches while looking at the console.

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<ons-page ng-controller='SwitchController'>
  <ons-toolbar>
    <div class="center">Switches</div>
  </ons-toolbar>

  <ons-list>
    <ons-list-header>Settings</ons-list-header>
    <ons-list-item>
      <div class="center">
        Enable cool feature: {{switchObject.cool}}
      </div>
      <div class="right">
        <ons-switch ng-model="switchObject.cool"></ons-switch>
      </div>
    </ons-list-item>
    <ons-list-item>
      <div class="center">
        Enable even cooler feature: {{switchObject.evenCooler}}
      </div>
      <div class="right">
        <ons-switch ng-model="switchObject.evenCooler"></ons-switch>
      </div>
    </ons-list-item>
    <ons-list-item>
      <div class="center">
        Enable amazing feature: {{switchObject.amazing}}
      </div>
      <div class="right">
        <ons-switch ng-model="switchObject.amazing"></ons-switch>
      </div>
    </ons-list-item>
  </ons-list>
</ons-page>
```

- __JS__

```javascript
ons.bootstrap()
  .controller('SwitchController', ['$scope', function($scope) {
    $scope.switchObject = {
      cool: false,
      evenCooler: true,
      amazing: false
    }
    
    $scope.$watch('switchObject', function(){
      console.log('switchObject changes have been noticed by $scope.$watch!!!');
    });
  }]);
```

**Comment by frandiox** [comment]
@rgins16 I believe this is not an Onsen UI issue. Angular's `$watch` by default only tracks the reference of complex data like `Object` or `Array`, not the properties. If you want to do a "deep watch", including object properties, pass a third argument to `$watch` with `true` value, as described in [their docs](https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watch), although it might not be very performant. Otherwise, have a look at `$watchGroup` or `$watchCollection`. Hope it helps!

**Comment by rgins16** [comment]
@frandiox  Ah, that's embarrassing. Sorry (>_<)
