### ISSUE TITLE
ons-screen replacement (login page to slide-menu implementation)

### ISSUE THREAD

**Issue by nokturnal** [OnsenUI/OnsenUI#192]
Hey,

This isn't really an issue (more of a general onsenui implementation practice question), but I have posted about it on SO and haven't received much interest :)

There is an example of the pattern (and solution) outlined here for onsenui versions that utilized ons-screen: http://stackoverflow.com/questions/22144654/add-a-login-page-in-my-onsenui-app

Basically, a single page for login that would route to a sliding menu pattern layout post auth (plus each "mainPage " having their own ons-navigators to maintain history).

My question is, what would be the proper (and recommended way) you would accomplish this in onsenui >= 1.1.1?

Can you have nested ons-navigators... one to handle the routing from the login page to the sliding menu template page then each "mainPage" having their own navigator to allow for history... is that the best way to tackle this?

Any help or direction would be appreciated

**Comment by sujeetqustn** [comment]
Its not working

**Comment by sujeetqustn** [comment]
@nokturnal, after clicking the login button it show error
"TypeError: Cannot read property 'setMainPage' of undefined", Is there anything I need to do more than your code ?

**Comment by nokturnal** [comment]
To be honest, I haven't looked at this for months. Pretty sure my code / hack is not relevant anymore

**Comment by sujeetqustn** [comment]
@nokturnal, Which JS framerwork are You using these days for your cordova project.

**Comment by nokturnal** [comment]
Well, since you asked... I am using ionic. That said, I was super intrigued with onsenui. I really identified with its structure and code style...but at the time it just wasn't robust enough for me. I am really looking forward to trying onsenui again for a future project.

**Comment by argelius** [comment]
@sujeetqustn I generally use `myNavigator.resetToPage('somepage.html')` for login screens.
