### ISSUE TITLE
Core | Progress issue: `<ons-progress-circular indeterminate>` always shows secondary-value circle.

### ISSUE THREAD

**Issue by asial-matagawa** [OnsenUI/OnsenUI#1921]
__Environment__

  
```
[Core]
  (onsenui 2.1.0 and older worked fine)
  onsenui 2.2.0
  onsenui 2.2.1
  onsenui 2.2.2 (latest)
  
[Platform]
  Desktop - OS X 10.12.0 64-bit

[Browser]
  Desktop - Chrome 56.0.2924.87 on OS X 10.12.0 64-bit
```

__Encountered problem__
`<ons-progress-circular indeterminate>` always shows secondary-value circle.

@anatoo 
Is this the correct behavior?

__How to reproduce__
  

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<ons-progress-circular indeterminate></ons-progress-circular>
```

- __JS__

```javascript

```

**Comment by anatoo** [comment]
@asial-matagawa It seem to be broken. I will take a look.

**Comment by asial-matagawa** [comment]
@anatoo
Thank you!
![](
![2017-04-07 20 49 16](https://cloud.githubusercontent.com/assets/19771915/24799021/14841844-1bd4-11e7-8519-b69ab368b6a0.png)
