### ISSUE TITLE
Style of ons-list-header is broken

### ISSUE THREAD

**Issue by puku0x** [OnsenUI/OnsenUI#1928]
__Environment__ 

```
[Core]
    onsenui 2.2.3
```

__Encountered problem__

I found the style of `ons-list-header` has been broken since v2.2.0.

- No `border-bottom`
- No `padding-top`
- Wrong `background-color`

>Onsen UI ~2.0.5
><img width="300px" src="https://cloud.githubusercontent.com/assets/2607019/24838738/0d739f78-1d89-11e7-8c47-74b3d04af566.png"/>

>Onsen UI 2.2.0
><img width="300px" src="https://cloud.githubusercontent.com/assets/2607019/24838753/51f5327e-1d89-11e7-83a6-3305b995a5df.png"/>

**Comment by asial-matagawa** [comment]
@puku0x 
Thank you for reporting!

@anatoo 
Is this a bug?
Or an expected behavior?

**Comment by anatoo** [comment]
@puku0x @asial-matagawa This is expected appearance. `ons-list-header` is originally implemented as a list category header.
In 2.0.x, `ons-list-header` is suddenly changed by other developers, so I just restored to original appearance in 2.2.0.

**Comment by puku0x** [comment]
@anatoo Thank you for your response.

However, I think the previous one also looks good because it is similar to iOS's list header 🙂 

If you have time, could you consider providing both styles of header ?
(Like Ionic's `ion-list-header` and `ion-item-divider`, for instance)

**Comment by anatoo** [comment]
Sorry for the delayed response because I am part-time developer for Onsen UI.

> If you have time, could you consider providing both styles of header ? (Like Ionic's ion-list-header and ion-item-divider, for instance)

Ok, it's should be fine. I will propose new components for that to Onsen UI team.

**Comment by puku0x** [comment]
@anatoo Thank you very much !
