### ISSUE TITLE
Spec: Action Sheet

### ISSUE THREAD

**Issue by frandiox** [OnsenUI/OnsenUI#1929]
@OnsenUI/members 
Let's discuss how to create a Custom Element for the existing Action Sheet/ Bottom Sheet CSS.

## DOM Structure

* Option 1:

```
<ons-action-sheet>
  <ons-action-sheet-item title>...</ons-action-sheet-item>
  <ons-action-sheet-item>...</ons-action-sheet-item>
  <ons-action-sheet-item>...</ons-action-sheet-item>
  <ons-action-sheet-item destructive></ons-action-sheet-item>
  <ons-action-sheet-item>...</ons-action-sheet-item>
</ons-action-sheet>
```

`ons-action-sheet` component provides the shape and animation whereas `ons-action-sheet-item` is independent and provides the style for its content. `ons-action-sheet-item` can actually be optional. This way, it would be possible to insert images or anything else in an action sheet. Or even layout the action sheet with two columns using `ons-col`.

* Option 2:

```
<ons-action-sheet>
  <div class="title">...</div>
  <div>...</div>
  <div>...</div>
  <div class="destructive">...</div>
  <div>...</div>
</ons-action-sheet>
```

`<ons-action-sheet>` does everything, from animation to adding CSS classes to the content. Adding something different from normal elements might be an issue.

* Option 3:

```
<ons-action-sheet>
  <ons-list>
    <ons-list-header modifier="action-sheet-title">...</ons-list-header>
    <ons-list-item modifier="action-sheet-item">...</ons-list-item>
    <ons-list-item modifier="action-sheet-item destructive">...</ons-list-item>
    <ons-list-item modifier="action-sheet-item">...</ons-list-item>
  </ons-list>
</ons-action-sheet>
```

This has the same advantages as #1 and we don't need to repeat components. However, this would require changing the current CSS a bit.

### Concerns

In Material Design, action sheet items are almost the same as `ons-list-item` component. They can be tappable, have "longdivider" or "nodivider", etc *(this is why I added option 3)*. Perhaps we could abstract them in an `ons-item` component and support everything via modifiers.

## API

I think this should be considered as a Dialog so the API will be similar: `show`-`hide` methods, `cancelable` attribute, `onDeviceBackButton` property, etc.

Speaking about this, I'd like to make some refactor to the dialogs and use inheritance. I think we could remove a bunch of code.

Apart from that, we will need `ons.createActionSheet` or similar. This is another thing I'd like to change. Maybe a simple `ons.createElement` is enough and then use `document.body.append` or `ons.portal`?

Also, we could provide a method for quick action sheets simliar to `ons.notification.alert`. Perhaps:

```
ons.actionSheet(['action1', 'action2']).then(index => doSomething(index));
ons.actionSheet({
  action1: () => doSomething(),
  action2: () => doSomethingElse()
});
```

----

Opinions?

**Comment by misterjunio** [comment]
@frandiox It would be cool to have an `ons-item` element that we can reuse in other components. That would make the action sheet a hybrid between the options you presented: the action sheet could control the item styling but allow the user to use other components inside as well. There would be no need for a list.

**Comment by frandiox** [comment]
`ons-list-item` has no real connection to `ons-list`, so it could be renamed to `ons-item` or just be used as `ons-list-item` inside anything else.

**Comment by asial-matagawa** [comment]
@frandiox @misterjunio 
I think Opinion 1 is easy to use for users although Opinion 3 gives us some advantages.

What about compiling `ons-action-sheet` and `ons-action-sheet-item` into `ons-list` and `ons-list-item` with modifiers?

**Comment by misterjunio** [comment]
@asial-matagawa I think the problem is like @frandiox said the default option since `ons-list-item`s get a short divider while inside an action sheet they should have no divider. The whole styling becomes harder due to the base styles of the `ons-list` and it would be less flexible for users as they might wish to use buttons or something else

**Comment by asial-matagawa** [comment]
We discussed this specification in the previous weekly meeting but we did not reached a conclusion.
Let's talk about this again soon.
