### ISSUE TITLE
Angular1 | Navigator issue: Page 'destroy' event does not get fired when navigating to another page

### ISSUE THREAD

**Issue by rgins16** [OnsenUI/OnsenUI#1936]
```
[Core]
  onsenui 2.2.2
  
[Framework]
  angular1 1.5.5

[Framework binding]
 angular1-onsenui latest

[Platform]
  Desktop - Windows 10 64-bit

[Browser]
  Desktop - Chrome 57.0.2987.133 on Windows 10 64-bit
```

__Encountered problem__
I am using a navigator, and specifically the resetToPage() method. When I use this method, the ‘destroy’ event for the page does not fire. This is an issue for me when I navigate to the same page that I am already on. I would like for the page to completely reset, but it does not. The page has not been destroyed.

I believe @misterjunio has already fixed this issue. I wanted to create an issue on Github so that there is an official record of this issue.

__How to reproduce__
Click the link I have provided, and use the navigator to navigate in between pages. If you change the destroy event to hide or show, you will see that it fires. The destroy event does not fire.

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<ons-splitter var="mySplitter" ng-controller="SplitterController as splitter">
  <ons-splitter-side id="menu" side="left" width="220px" collapse swipeable>
    <ons-page>
      <ons-list>
        <ons-list-item ng-click="splitter.load('home.html')" tappable>
          Home
        </ons-list-item>
        <ons-list-item ng-click="splitter.load('settings.html')" tappable>
          Settings
        </ons-list-item>
        <ons-list-item ng-click="splitter.load('about.html')" tappable>
          About
        </ons-list-item>
      </ons-list>
    </ons-page>
  </ons-splitter-side>
  <ons-splitter-content>
    <ons-navigator id='navi' var="navi" page="home.html"></ons-navigator>
  </ons-splitter-content>
</ons-splitter>

<ons-template id="home.html">
  <ons-page>
    <ons-toolbar>
      <div class="left">
        <ons-toolbar-button ng-click="mySplitter.left.open()">
          <ons-icon icon="md-menu"></ons-icon>
        </ons-toolbar-button>
      </div>
      <div class="center">
        Main
      </div>
    </ons-toolbar>
    <p style="text-align: center; opacity: 0.6; padding-top: 20px;">
      Swipe right to open the menu!
    </p>
  </ons-page>
</ons-template>

<ons-template id="settings.html">
  <ons-page>
    <ons-toolbar>
      <div class="left">
        <ons-toolbar-button ng-click="mySplitter.left.open()">
          <ons-icon icon="md-menu"></ons-icon>
        </ons-toolbar-button>
      </div>
      <div class="center">
        Settings
      </div>
    </ons-toolbar>
  </ons-page>
</ons-template>

<ons-template id="about.html">
  <ons-page>
    <ons-toolbar>
      <div class="left">
        <ons-toolbar-button ng-click="mySplitter.left.open()">
          <ons-icon icon="md-menu"></ons-icon>
        </ons-toolbar-button>
      </div>
      <div class="center">
        About
      </div>
    </ons-toolbar>
  </ons-page>
</ons-template>
```

- __JS__

```javascript
ons.bootstrap()
  .controller('SplitterController', ['$scope', function($scope) {
    
    this.load = function(page) {
      mySplitter.left.close();
      navi.resetToPage(page);
    };
    
    document.getElementById('navi').addEventListener('destroy', () => alert('askdjhas'));
  }]);
```

**Comment by misterjunio** [comment]
@rgins16 indeed with #1934 I have made the `ons-page` throw the `destroy` event when it is unloaded. However I still don't get what you mean by

> The page has not been destroyed.

Can you give an example that shows when that happens? My pages are completely reloaded, you can check by replacing the `destroy` listener in your example with an `init` one.

**Comment by rgins16** [comment]
@misterjunio Forgive me if what I'm saying doesn't make sense. I'm still learning as I go, maybe I said what I meant incorrectly. What I meant was that DOM elements weren't removed from the page after navigating to the same page I was currently on. I did a JavaScript check to see if elements were already existing. They did not exist the first time I navigated to a page. Then they already existed if I navigated to the same page I was currently on. If I navigated to a different page, then back to the first one, then the elements did not exist again - they were 'destroyed'. I apologize if I am conveying this incorrectly.

**Comment by rgins16** [comment]
@misterjunio I suppose the problem is on my end. After manually applying the fix, I'm still having the same issue. I have a jQuery datepicker. It loads correctly the first time I navigate to a page. If I navigate to the same page, then the datepicker does not load correctly. If I navigate to a different page, then navigate back to the first one, it loads correctly. I had assumed this was because the datepicker element was not being 'destroyed' when I navigated to the same page. However, after applying the fix in your commit, it still is not working.

**Comment by misterjunio** [comment]
@rgins16 I took the example you provided above, added `jQuery`, placed `<div id="datepicker"></div>` in the `home` page (also added an `id="myHome"` to it) and then on the controller:

```
document.getElementById('navi').addEventListener('init', (e) => {
  if (e.target.id === "myHome") {
    $("#datepicker").datepicker();
    $("#datepicker").datepicker("setDate", "10/12/2012");
  }
})
```

Now even if I navigate to the same page on the menu the date is always reset to "10/12/2012". Are you doing something more complicated or does this work for you?
Anyway I think we can close this issue and discuss any further questions in the community forum..

**Comment by rgins16** [comment]
@misterjunio I think I may have figured out the problem; what the real bug is. I can't provide code because you have not released the version with your fix to the 'destroy' event not being fired, but I manually updated my local version according to your commit. So when I navigate to the same page, the 'init' event fires before the 'destroy' event. I believe this is a bug. The 'destroy' event should fire before the 'init' event. Is this a wrong assumption?

**Comment by misterjunio** [comment]
@rgins16 I took the same code as I explained in my last comment and added the previous listener for `destroy` alongside the `init` one ([pen here](https://codepen.io/misterjunio/pen/zwrvzP?editors=1011) but you still need to manually add the fix though). Everything works as expected, destroy before init so I can't really reproduce your problem 😕

**Comment by misterjunio** [comment]
@rgins16 I updated the pen in my last comment to use the latest version and everything works as expected so I consider this fixed. Closing the issue.
