### ISSUE TITLE
Specs: ons.createElement

### ISSUE THREAD

**Issue by frandiox** [OnsenUI/OnsenUI#1941]
@OnsenUI/members 

We have `ons.createDialog`, `ons.createAlertDialog` and `ons.createPopover`, which basically do the same thing for 3 different elements. However, we don't have `ons.createModal` and we will need a `ons.createActionSheet` at some point. I'd suggest deprecating all of those methods and just add `ons.createElement`. This method, however, should just return the new element instead of attaching it to `document.body`. Thus, we would need something like `ons.portal(element)` ("portal" is used in React, Vue, etc. for this use case) in order to attach the new element to the body. AngularJS could also wrap this portal method and compile the element after it is attached.

```
//// current
ons.createDialog('path/to/dialog');

//// new
var myDialog = ons.createElement('path/to/dialog');
ons.portal(myDialog, destiny); // target defaults to document.body
 // This can also work
var myItem = ons.createElement('<ons-list-item>...</ons-list-item>');
```

**Comment by misterjunio** [comment]
I agree it's useful for users to have access to the `createElement` function. So using the portal to make all dialogs work in a similar fashion it's a great idea imo.

**Comment by asial-matagawa** [comment]
I think it is fine to deprecate `ons.createDialog`, `ons.createAlertDialog` and `ons.createPopover` because those are not that useful.

My only concern is its naming.
- `createElement` is associated with `Document#createElement`.
    - `Document#createElement` has no side effect but `ons.createElement` actually has a side effect which attaches the created element to somewhere. It's a bit confusing.
- In my point of view I think it would be better to use another name implies the existence of the side effect.
    - `ons.showElement`, `ons.showTemplate`, `ons.useTemplate`, `ons.show`, ...

**Comment by frandiox** [comment]
@asial-matagawa That's why I removed that side effect from `ons.createElement`. It returns the new element and does not attach it. For attaching the element I mentioned `ons.portal` instead.

**Comment by asial-matagawa** [comment]
@frandiox 
Sorry, I missed `instead of` before `attaching it to document.body`...
If so I have no concerns about `ons.createElement`. Thank you for suggestion!

**Comment by frandiox** [comment]
@misterjunio @asial-matagawa This use case could work without problems: `var myItem = ons.createElement('<ons-list-item>...</ons-list-item>');`. However, if we pass a path to an external file, it cannot be done synchronously. Therefore, we can return a promise is the first parameter is a path. What do you think? This is some kind of "overloaded" function.

**Comment by asial-matagawa** [comment]
@frandiox 
What about always returning a Promise?
If `ons.createElement('<ons-list-item>...</ons-list-item>')` returns an element, users expect that `ons.createElement('path/to/template')` also returns an element (even though that is impossible).

**Comment by frandiox** [comment]
I guess that would make `ons.createElement('<ons-list-item>...</ons-list-item>')` kind of useless since the good thing there is that it behaves like `document.createElement` and is synchronous. That's my opinion at least, but maybe it's better. Let's see what @misterjunio thinks about.

**Comment by misterjunio** [comment]
I think no developer will expect fetching from the external file to be synchronous so it should be fine to keep it synchronous for in-line and returning a promise if in an outside template.

**Comment by asial-matagawa** [comment]
@frandiox @misterjunio 
I see, in that case let's use your original suggestion 🙂 
I will write some note in onsen.io in case users get confused about the return value type of `ons.createElement`.
