### ISSUE TITLE
ons-splitter-side: Scroll lock does not work on iOS

### ISSUE THREAD

**Issue by puku0x** [OnsenUI/OnsenUI#1949]
__Environment__ 

```
[Core]
    onsenui 2.2.4

[Framework]
    angular 4.0.2

[Framework binding]
    angular2-onsenui 1.0.0-rc.6

[Additional libraries]
    none

[Platform]
    Mobile - iOS 10.1.1

[Browser]
    Mobile - iOS UIWebView
```

__Encountered problem__
Scroll lock does not work on iOS.
(The same problem is reported in https://teratail.com/questions/71231 by other user)

__How to reproduce__
1. Create a page which contains following components.
  - ons-splitter
- ons-splitter-content
- ons-splitter-side

2. Swipe the content page and display the side page.
3. Scroll in vertical direction.

**Comment by frandiox** [comment]
I've been checking this and looks like a bug in UIWebView. I've made a fix and now it should stop scrolling when touching the mask, which is enough for `push` and `reveal` animations.

However, with `overlay` animation and when the splitter side is not scrollable, `touchmove` events somehow passes through the splitter-side and go to the splitter-content. Side and content are sibling elements so the event is not exactly bubbling, it just ignores the top element (the side). I think there's no easy fix for this :sweat: 

This does not happen with the more recent [WKWebView](https://github.com/apache/cordova-plugin-wkwebview-engine).

**Comment by puku0x** [comment]
Thank you @frandiox for investigating this.
I will use `cordova-plugin-wkwebview-engine` !

**Comment by frandiox** [comment]
From v2.9.0, `ons.forceUIWebViewScrollFix()` should prevent this behavior with `overlay` animation but it might affect the momentum scroll. Another way to fix it:

```
document.querySelector('ons-splitter-side').addEventListener('touchmove', function(e) { e.cancelable && e.preventDefault(); });
```

This should only be applied if the splitter is not scrollable!

**Comment by puku0x** [comment]
@frandiox Thank you for the information. I will try it !
