### ISSUE TITLE
Feature request: expansion panels

### ISSUE THREAD

**Issue by mjessen** [OnsenUI/OnsenUI#1955]
Hi,

an expansion panel is an useful and often used component for material design but still missing in the library. 

https://material.io/guidelines/components/expansion-panels.html

Any plans to implement it?

**Comment by munsterlander** [comment]
@mjessen This is already accomplished with JS and CSS.  I guess it could be implemented, but it is pretty easy to do.  Here is how I did it:  https://github.com/munsterlander/Onsen-Examples/tree/master/Accordion-List

**Comment by mjessen** [comment]
@munsterlander Thank you for the good example. I think thats a good starting point to bring it closer to the material design specs for expansion panels i mentioned in the first post and/or bring it to an own component in onsen ui.

**Comment by pashute** [comment]
Also called an accordion. 

This is not just an enhancement. It is standard with all other UIs including Angular1, 2 and VUE. So it's a lacking feature.
