### ISSUE TITLE
Use webpack 2 to fix sourcemap of `onsenui.js`

### ISSUE THREAD

**Issue by asial-matagawa** [OnsenUI/OnsenUI#1958]
@frandiox @misterjunio @anatoo 

I would like to replace Rollup with webpack 2 in order to fix the sourcemap of `onsenui.js`.
(For example, in `onsenui@2.2.4`, we cannot set a breakpoint on L153, L156 and L161 in Chrome DevTools as illusrated below)
![2017-04-19 14 51 31](https://cloud.githubusercontent.com/assets/19771915/25165114/bec4a5c8-250f-11e7-950e-4510d13cb8bc.png)

What do you think?

### Detail

In onsenui@2.2.4, when we set a break point on some point of `onsenui.js` in Chrome DevTools, sometimes we are navigated to a wrong line of original file.

I found that this is caused by [a change](https://github.com/OnsenUI/OnsenUI/compare/2.0.3...2.0.4) committed between `onsenui@2.0.3` and `onsenui@2.0.4`.
This change replaces `rollup@0.26.7` with `rollup@0.36.3`, but `rollup` made [a breaking change](https://github.com/rollup/rollup/blob/master/CHANGELOG.md#0323) in `rollup@0.32.3` which makes sourcemaps incompatible with Chrome DevTools.

Before `rollup@0.32.3` (first letter of each line is mapped correctly):
![2017-04-19 13 59 19](https://cloud.githubusercontent.com/assets/19771915/25164774/1b9052fe-250e-11e7-8f33-c2495c0db424.png)

After `rollup@0.32.3` (first letter of each line is not mapped):
![2017-04-19 13 36 18](https://cloud.githubusercontent.com/assets/19771915/25164784/1f2d1168-250e-11e7-98f8-b5b42c04e7f0.png)

We can roll back `rollup` to an old version, but I think using webpack 2 is more decent decision.

This problem (= weird(?) behavior of Chrome DevTools) is recently discussed also in the official repos of [`rollup`](https://github.com/rollup/rollup/issues/1370) and [`webpack`](https://github.com/webpack/webpack/issues/2145#issuecomment-294361203).

**Comment by frandiox** [comment]
@asial-matagawa +100 to this. We should be consistent and use Webpack whenever possible. I think the test coverage was also failing due to a Rollup issue.
