### ISSUE TITLE
Materialize Icon dont work with same icons.

### ISSUE THREAD

**Issue by pandbsoftware** [OnsenUI/OnsenUI#1966]
Like,       `<ons-icon icon="md-library-music" size="40px"></ons-icon>`
what can do with this ?, also        `<ons-icon icon="md-library-music" size="40px"></ons-icon>`
 <ons-icon icon="md-supervisor-account" size="40px"></ons-icon>

thanks.

__Environment__ 

```
[Core]
    onsenui 2.1.0

[Framework]
    none
    angular1 1.5.9
    angular2 2.2.4
    react 15.4.1
    vue 2.1.10

[Framework binding]
    none
    angular-onsenui 2.1.0
    angular2-onsenui 1.0.0-rc.5
    react-onsenui 1.1.0
    vue-onsenui 2.0.0-alpha.0

[Additional libraries]
    none
    jQuery 3.1.1

[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1
    Desktop - Linux
    Desktop - macOS Sierra
    Desktop - Windows 10

[Browser]
    Mobile - Android WebView
    Mobile - Android Chrome 54.0.2840.85
    Mobile - iOS UIWebView
    Mobile - iOS Safari
    Desktop - Chrome 55.0.2883.75
    Desktop - Safari 10.0 (12602.1.50.0.10)
```

__Encountered problem__

__How to reproduce__

**Comment by frandiox** [comment]
Use icon names from here: https://zavoloklom.github.io/material-design-iconic-font/icons.html

I think you're looking for `md-collection-music`.
