### ISSUE TITLE
ReferenceError: Can't find variable Set

### ISSUE THREAD

**Issue by CrankedCode** [OnsenUI/OnsenUI#1967]
Safari on iOS and non-Chrome OEM Android browsers has this fatal error in console which breaks Onsen entirely:

onsenui.js:2231 ReferenceError: Can't find variable: Set

This issue is for v2.2.4.  If I revert back to v.2.1, this issue disappears.

**Comment by asial-matagawa** [comment]
@CrankedCode 
It seems that this issue occurs on old browsers because [some of them don't have `Set` and `Map`](http://kangax.github.io/compat-table/es6/#test-Set).
I have fixed this problem in #1968 and it will be released in `onsenui@2.2.5`.

Thank you for reporting!
