### ISSUE TITLE
Crash older Android (API 19) versions with 2.2.3 and 2.2.4

### ISSUE THREAD

**Issue by AnfiGroup** [OnsenUI/OnsenUI#1973]
I have a problem when I update to 2.2.4 version with Androids with API 19. Android over 22 and iOS, browser, etc. works ok, but with Android 19 I get this error:

**Uncaught ReferenceError: Set is not defined** onsenui.min.js:3
**Uncaught TypeError: Cannot call method 'lock' of undefined** onsen.js:38
**Uncaught TypeError: Object #<HTMLUnknownElement> has no method 'resetToPage'** app.js:66

When I downgrade to 2.2.2 it is working fine. It is a bug?

Thank you,

J. Carlos

**Comment by asial-matagawa** [comment]
@AnfiGroup 
Thank you for reporting.
That problem occurs on old Android environments.

It is already reported in #1967 and fixed in #1968.
We will release a fixed version of `onsenui` (2.2.5) soon, so please be patient until it is released.

Closing this.
