### ISSUE TITLE
Deprecate `*Factory` in `angular2-onsenui`.

### ISSUE THREAD

**Issue by asial-matagawa** [OnsenUI/OnsenUI#1976]
@frandiox (Cc: @misterjunio @anatoo)

I thought about the necessity of `*Factory` in `angular2-onsenui`.

Pros of `*Factory`
  - We can avoid polluting component templates with dialog definitions
  - We can pass parameters to dialog components as if we pass parameters to `ons-page`s with `pushPage`
  - We can provide ways which are equivalent to `ons.create*` in the core

Cons of `*Factory`
  - We have to inject `*Factory` to the component where we want to call `*Factory.create*(~~~~)`
  - We have to destroy dynamically created components in `ngOnDestroy` hook
  - We have to register all dialog component classes to `declarations` and `entryComponents` in NgModule
  - We have to use host bindings in order to attach @Input/@Output to dynamically created components
  - Dynamic component creation in JS frameworks essentially tends to cause complexity and should not be exposed to users

Conclusion
  - We should deprecate `*Factory` and use only in-template dialog definitions as the other bindings are doing so

Even without `*Factory`, we can write code as follows:
```ts
import {
  Component,
  ComponentRef,
  ViewChild,
  Params,
  AfterViewInit,
  OnDestroy,
  OnsenModule,
  NgModule,
  onsNotification,
  CUSTOM_ELEMENTS_SCHEMA
} from 'angular2-onsenui';
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';

@Component({
  selector: 'app',
  template: `
  <ons-page class="page">
    <ons-toolbar>
      <div class="center">Alert Dialog</div>
    </ons-toolbar>
    <div class="content">
      <ons-list>
        <ons-list-header>Custom dialogs</ons-list-header>
        <ons-list-item tappable (click)="alert.show()">Custom alert-dialog</ons-list-item>
        <ons-list-item tappable (click)="dialog.show()">Custom dialog</ons-list-item>

        <ons-list-header>Notification</ons-list-header>
        <ons-list-item tappable (click)="alert()" id="alert-button">Alert</ons-list-item>
        <ons-list-item tappable (click)="confirm()" id="confirm-button">Confirmation</ons-list-item>
        <ons-list-item tappable (click)="prompt()" id="prompt-button">Prompt</ons-list-item>
      </ons-list>
    </div>

    <ons-alert-dialog cancelable #alert>
      <div class="alert-dialog-title">Warning!</div>
      <div class="alert-dialog-content">
        {{'This is just an example.'}}
      </div>
      <div class="alert-dialog-footer">
        <button class="alert-dialog-button" (click)="alert.hide()">OK</button>
      </div>
    </ons-alert-dialog>

    <ons-dialog animation="default" cancelable #dialog>
      <div class="dialog-mask"></div>
      <div class="dialog">
        <div class="dialog-container" style="height: 200px;">
          <ons-page>
            <ons-toolbar>
              <div class="center">Name</div>
            </ons-toolbar>
            <div class="content">
              <div style="text-align: center">
                <p>{{'This is just an example.'}}</p>
                <br>
                <ons-button (click)="dialog.hide()">Close</ons-button>
              </div>
            </div>
          </ons-page>
        </div>
      </div>
    </ons-dialog>
  </ons-page>
  `
})
export class AppComponent implements AfterViewInit, OnDestroy {
  constructor() {
  }

  ngAfterViewInit() {
  }

  alert() {
    onsNotification.alert('Hello, world!');
  }

  confirm() {
    onsNotification.confirm({
      message: 'This dialog can be canceled by tapping the background or using the back button on your device.',
      cancelable: true,
      callback: i => {
        if (i == -1) {
          onsNotification.alert({message: 'You canceled it!'});
        }
      }
    });
  }

  prompt() {
    onsNotification.prompt({
      message: 'What is the meaning of Life, the Universe and Everything?',
      callback: answer => {
        if (answer === '42') {
          onsNotification.alert({message: 'That\'s the correct answer!'});
        } else {
          onsNotification.alert({message: 'Incorrect! Please try again!'});
        }
      }
    });
  }
}

@NgModule({
  imports: [OnsenModule],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
class AppModule { }

platformBrowserDynamic().bootstrapModule(AppModule);
```

What do you think?

If there is no critical problem, I will deprecate `*Factory` and update all the examples in `bindings/angular2/examples`, `onsen.io` and `tutorial.onsen.io`.

**Comment by frandiox** [comment]
@asial-matagawa Yes, I think it is better to use the components as they are, without factories. Now, there is a problem in doing it in this way: If the dialog is included in a page that is a child of another page that contains a toolbar (for example, in the case of a Tabbar where the inner pages don't have a toolbar, but the parent has), the mask won't be displayed over this toolbar.

There are two ways to deal with that. One is obviously placing the dialog at a high level so it always shows on top of the toolbars, but it might be hard some times to pass down a reference to show/hide the dialog from a deep place (not sure about this, perhaps it's easy in Angular2).

Another way is to implement some kind of "portal" functionality and automatically move the dialogs to the body. In React there is something called `ReactDOM.unstable_renderSubtreeIntoContainer` that basically allows it. React bindings are [using it](https://github.com/OnsenUI/OnsenUI/blob/master/bindings/react/src/components/BaseDialog.jsx#L92).
Same for Vue bindings. I just implemented a ["portal" mixin](https://github.com/OnsenUI/OnsenUI/blob/master/bindings/vue/src/mixins/common.js#L101) that all the dialogs use.
I'm not an expert but I guess Angular2 must have a way to deal with this as well.

Pinging @erisu here.

**Comment by asial-matagawa** [comment]
@frandiox 
>One is obviously placing the dialog at a high level so it always shows on top of the toolbars, but it might be hard some times to pass down a reference to show/hide the dialog from a deep place (not sure about this, perhaps it's easy in Angular2).

In Vue 2 we write `outerHML` of the component element in `template`, but in Angular 2+ we write `innerHTML` in `template`.
That is, in Angular 2+ we can write `template` as follows:
```ts
  template: `
    <ons-page class="page">
      <ons-toolbar>
        <div class="center">Alert Dialog</div>
      </ons-toolbar>
      <div class="content">
        <ons-list>
          <ons-list-header>Custom dialogs</ons-list-header>
          <ons-list-item tappable (click)="alert.show()">Custom alert-dialog</ons-list-item>
          <ons-list-item tappable (click)="dialog.show()">Custom dialog</ons-list-item>
  
          <ons-list-header>Notification</ons-list-header>
          <ons-list-item tappable (click)="alert()" id="alert-button">Alert</ons-list-item>
          <ons-list-item tappable (click)="confirm()" id="confirm-button">Confirmation</ons-list-item>
          <ons-list-item tappable (click)="prompt()" id="prompt-button">Prompt</ons-list-item>
        </ons-list>
      </div>
    </ons-page>
  
    <ons-alert-dialog cancelable #alert>
      <div class="alert-dialog-title">Warning!</div>
      <div class="alert-dialog-content">
        {{'This is just an example.'}}
      </div>
      <div class="alert-dialog-footer">
        <button class="alert-dialog-button" (click)="alert.hide()">OK</button>
      </div>
    </ons-alert-dialog>
  
    <ons-dialog animation="default" cancelable #dialog>
      <div class="dialog-mask"></div>
      <div class="dialog">
        <div class="dialog-container" style="height: 200px;">
          <ons-page>
            <ons-toolbar>
              <div class="center">Name</div>
            </ons-toolbar>
            <div class="content">
              <div style="text-align: center">
                <p>{{'This is just an example.'}}</p>
                <br>
                <ons-button (click)="dialog.hide()">Close</ons-button>
              </div>
            </div>
          </ons-page>
        </div>
      </div>
    </ons-dialog>
  `
```

Therefore the problem of the mask is not a problem in `angular2-onsenui`.

**Comment by asial-matagawa** [comment]
Ah, if we use `selector: 'ons-page[foo]'` to create a reusable page component, the problem appears again

**Comment by asial-matagawa** [comment]
I added deprecation warnings about `*Factory`.

![2017-06-07 13 15 13](https://user-images.githubusercontent.com/19771915/26862078-7c20e5d4-4b83-11e7-8ca4-57e0c222513f.png)

**Comment by frandiox** [comment]
@asial-matagawa :+1: 
Is `ons` object and `ons.notification` available to use?

**Comment by asial-matagawa** [comment]
@frandiox 
Yes, users can use `import * as ons from 'onsenui';` or `import ons = require('onsenui');` since `ngx-onsenui@4.0.0-rc.0`.

But I feel like we should provide `OnsenService` so that users can use `ons` in component templates, which corresponds to `$ons` in `vue-onsenui`.
In Angular, JavaScript code in component templates can access only component class members, so it would be better to enable users to write `constructor(private ons: OnsenService) {}` and then `(click)="ons.notification.toast('toast')"`.

**Comment by frandiox** [comment]
@asial-matagawa Yes, that makes sense :+1: :+1:
