### ISSUE TITLE
Select is undefined

### ISSUE THREAD

**Issue by elhoucine** [OnsenUI/OnsenUI#1989]
Hello,

- Versions:
```
"onsenui": "^2.0.0-rc.17",
"react": "^15.3.0",
````
- Issue: 

When I import the modules like:
```
import {
  Page, Toolbar, BackButton,
  List, ListHeader, ListItem,
  Icon, Button, Select, Input,
 Range,
} from 'react-onsenui';
````
All modules are working except `Select` is undefined. Am I missing something?

Reproduces on different projects.

**Comment by puku0x** [comment]
Why are you using RC.17 ?
Select (ons-select) is available on 2.1.0 or higher.

**Comment by munsterlander** [comment]
Onsen is currently at 2.2.6.  You definitely need to update and that will solve your issue.

**Comment by elhoucine** [comment]
Yes, older versions were the issue. `react-onsenui` was on an older version too `^0.7.5` upgraded to the latest.

Thank you
