### ISSUE TITLE
Very Slow After 20 pages more visit

### ISSUE THREAD

**Issue by ilmuwebsite** [OnsenUI/OnsenUI#1992]
__Environment__ 

```
[Core]
    onsenui 2.2.5

[Framework]
    none
    angular1 1.5.9

[Framework binding]
    angular-onsenui 2.2.5

[Additional libraries]
    jQuery 3.1.1

[Platform]
    Mobile - Android 7.1 - Cordova

```

__Encountered problem__
After i visit more than 20 pages back and forth the app comes very heavy, 
may i get the solution ?

**Comment by munsterlander** [comment]
Do you have a stripped down version of your code that demonstrates the issue? What onsen components are you using? Are there images?

**Comment by ilmuwebsite** [comment]
I wrote the code with standard codes by followed the Documentation of OnsenUI official website 

just using pushPage popPage  resetPage, and got the data from http.post angularjs

the image has been resized to 200 x 200px

**Comment by misterjunio** [comment]
@ilmuwebsite the latest Onsen UI provides `ons.preload(templatePaths)` so you can cache templates on app start, which should improve the performance a bit. Please try and let us know if it works better on your case

**Comment by frandiox** [comment]
@misterjunio Perhaps we should implement some caching in the Navigator in order to detach the first children automatically when they are not needed. It can be done by attaching/detaching pages accordingly on `prepop` and `postpush` I think.

**Comment by misterjunio** [comment]
@frandiox I'm not sure what you mean by detaching the first child when 'it's not needed'. How would we know if it's needed or not?

**Comment by frandiox** [comment]
If there are 7 pages for example, chances are that we don't need the first 4-5 pages since the normal action is popping 1 page. If `resetToPage` or anything like that is used, then it can reattach the pages.

**Comment by christophemarois** [comment]
I'm linking here to a very performant solution I've made with the Vue.JS bindings in [a gist](https://gist.github.com/christophemarois/ca81502ebd0bb893612916f4c5ec99f1).

Original [Onsen forum post](https://community.onsen.io/topic/1749/ons-navigator-performance-with-a-lot-of-ons-page-elements)

**Comment by sbusch** [comment]
Just my 2 cents: there are use cases where this navigation depth can be achieved easily, especially for navigating in folder structures (and other tree-like structures) where each visited node is a new page.
