### ISSUE TITLE
Provide ES Modules.

### ISSUE THREAD

**Issue by asial-matagawa** [OnsenUI/OnsenUI#2001]

**Comment by asial-matagawa** [comment]
@frandiox (Cc: @anatoo @misterjunio )
We have several options about how to provide a variety of modules.

----
**Option 1:** Provide UMD (bundled), [CommonJS2](https://github.com/webpack/webpack/issues/1114) (bundled) and ESM (bundled).
(Example: [Vue](https://unpkg.com/vue@2.3.3/))

This option is a straightforward solution.
In this option, we have a `package.json` like:

```js
unpkg: 'js/onsenui.js',
main: 'js/onsenui.common.js',
module: 'js/onsenui.esm.js',
```

Non-ES2015 users can use `onsenui.js` with `<script>`.
CommonJS2 users can use `onsenui.js` or `onsenui.common.js` as a CommonJS 2 module.
ES Modules users can use `onsenui.esm.js` as a ES Module.

Note: `unpkg` property prevents that https://unpkg.com/onsenui is resolved to `js/onsenui.common.js`.

----
**Option 2-a:** Provide UMD (bundled) and ESM (bundled) with the extention `.js`.

Maybe [CommonJS2](https://github.com/webpack/webpack/issues/1114) will be replaced by ES Modules in the future, so I think we should not stick to providing a CommonJS2 module.
In this option, we have a `package.json` like:

```js
main: 'js/onsenui.js',
module: 'js/onsenui.esm.js',
```

Non-ES2015 users can use `onsenui.js` with `<script>`.
CommonJS2 users can use `onsenui.js` as a CommonJS2 module.
ES Modules users can use `onsenui.esm.js` as a ES Module.

----
**Option 2-b:** Provide UMD (bundled) and ESM (bundled) with the extension `.mjs`.

According to [this doc by Node.js](https://github.com/nodejs/node-eps/blob/5dae5a537c2d56fbaf23aaf2ae9da15e74474021/002-es6-modules.md#5-semantics) and [this post](http://2ality.com/2017/05/es-module-specifiers.html), it seems that Node.js might use `.mjs` as a default extension for ES Modules in the future.
So it might be better to follow this new specification (but personally I think `.mjs` is not an ideal solution...).

In this option, we have a `package.json` like:

```js
main: 'js/onsenui.js',
module: 'js/onsenui.mjs',
```
or
```js
main: 'js/onsenui',
```

Non-ES2015 users can use `onsenui.js` with `<script>`.
CommonJS2 users can use `onsenui.js` as a CommonJS2 module.
ES Modules users can use `onsenui.mjs` as a ES Module.

----

Personally I like Option 2-a, but it has a critical problem I think we should go with Option 1.
Which one should we choose?
Any other possibilities?

**Comment by frandiox** [comment]
@asial-matagawa Thanks for all the information!
I like option 2-a as well but I don't see what's the critical problem :thinking:

**Comment by asial-matagawa** [comment]
@frandiox
Sorry, I made a critical mistake... 😅 

x  Personally I like Option 2-a, but it has a critical problem I think we should go with Option 1.
o  Personally I like Option 2-a, but if it has a critical problem I think we should go with Option 1.

**Comment by asial-matagawa** [comment]
@frandiox 
Unlike Rollup, currently webpack 2 does not provide a feature to bundle multiple ES Modules into one ES Module, so we have to include all the files in `core/src` into `onsenui` package in order to provide ES Module through `module` property in `package.json`.
Detail: http://stackoverflow.com/questions/41289200/output-an-es-module-using-webpack

Do you think it's acceptable?

**Comment by asial-matagawa** [comment]
I created a proposal: #2008
