### ISSUE TITLE
Core | Progress issue: 90 Degree Clockwise Rotation in Safari 10.0

### ISSUE THREAD

**Issue by asial-matagawa** [OnsenUI/OnsenUI#2015]
__Environment__

  
```
[Core]
  onsenui 2.2.6
  
[Platform]
  Desktop - OS X 10.12

[Browser]
  Desktop - Safari 10.0 on OS X 10.12
```

__Encountered problem__
  
@anatoo
As explained in the title.
![2017-05-18 17 26 13](https://cloud.githubusercontent.com/assets/19771915/26193180/639cec36-3bef-11e7-9062-3a53a3f20ac0.png)

This behavior can be seen only in macOS Safari.
(It works fine in iOS 9 Safari and iOS 10 Safari)

__How to reproduce__
  

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<ons-page>
  <ons-toolbar>
    <div class="center">Progress</div>
  </ons-toolbar>

  <ons-progress-bar value="10"></ons-progress-bar>

  <div style="margin: 20px auto; width: 320px;">
    <p>Loading stuff...</p>
    <ons-progress-bar value="20" secondary-value="50"></ons-progress-bar>
  </div>

  <ons-progress-bar indeterminate></ons-progress-bar>
  <ons-progress-circular value="10"></ons-progress-circular>
  <ons-progress-circular value="20" secondary-value="50"></ons-progress-circular>
  <ons-progress-circular indeterminate></ons-progress-circular>
</ons-page>
```

- __JS__

```javascript

```

**Comment by anatoo** [comment]
I can't reproduce this problem on my environment.

@asial-matagawa Could you fix demo link?

**Comment by asial-matagawa** [comment]
@anatoo
The demo link works fine on my environment...
Could you go to tutorial.onsen.io and choose `JavaScript > Progress Indicators`?

**Comment by anatoo** [comment]
OK. But it seem to be fine.
 
![image](https://cloud.githubusercontent.com/assets/59784/26195678/92965ff6-3bf7-11e7-83aa-6ac8c0bc7ceb.png)

My safari version: 10.1 (12603.1.30.0.34)

**Comment by asial-matagawa** [comment]
@anatoo
The version of my macOS Safari is `10.0 (12602.1.50.0.10)`.
OK, maybe this is a bug of macOS Safari and it seems already fixed.
Thank you for checking!

Closing this.
