### ISSUE TITLE
Docs offer incorrect info about ons-list

### ISSUE THREAD

**Issue by Leva7** [OnsenUI/OnsenUI#2029]
__Environment__

```
[Core]
  onsenui latest
  
[Platform]
  Desktop - Ubuntu 64-bit

[Browser]
  Desktop - Firefox 53.0 on Ubuntu 64-bit
```

__Encountered problem__
  The docs state that a chevron is not shown in Material Design lists, but there is one in the tutorial [here](https://onsen.io/v2/docs/js/ons-list-item.html).

**Comment by anatoo** [comment]
@Leva7 Thanks for the reporting. We will fix this problem.
