### ISSUE TITLE
webpack failed to compile for Vue.js monaca preview

### ISSUE THREAD

**Issue by Youdaman** [OnsenUI/OnsenUI#2037]
See https://github.com/monaca/monaca-cli/issues/83

Not sure whether to post here under OnsenUI or Monaca so posting to both.

Summary: the "Onsen UI and Vue.js" option fails to build with webpack.

**Comment by asial-matagawa** [comment]
@Youdaman 
Thank you for reporting!
It was not an problem of Onsen UI and has been fixed in monaca/monaca-lib#105.

Closing this.
