### ISSUE TITLE
Input type='search' doesn't work, it produces text input, not search input

### ISSUE THREAD

**Issue by Bundas** [OnsenUI/OnsenUI#2038]
__Environment__ 

```
[Core]
    onsenui 2.2.0

[Framework]
    react 15.4.1

[Framework binding]
    react-onsenui 1.1.0

[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1

[Browser]
    Mobile - Android WebView
    Mobile - Android Chrome 54.0.2840.85
    Mobile - iOS UIWebView
    Mobile - iOS Safari
    Desktop - Chrome 55.0.2883.75
    Desktop - Safari 10.0 (12602.1.50.0.10)
```

__Encountered problem__
Input type='search'  **does not** produce search input. It produces plain text input. It has worked in previous version

__How to reproduce__
Use latest onsen 2.2.x, and create Input type='search' 
Expected is 
![image](https://cloud.githubusercontent.com/assets/10119003/26514260/00a2cc9e-4271-11e7-8dbf-7eea591b5249.png)

but I got this
![image](https://cloud.githubusercontent.com/assets/10119003/26514276/18e99f3a-4271-11e7-96a3-ae44c5238363.png)

(Ignore the 'settings' icon - my bad)

**Comment by asial-matagawa** [comment]
Hi, @Bundas!
`type='search'` is only supported in Onsen UI 2.3.0 and later (described in [CHANGELOG](https://github.com/OnsenUI/OnsenUI/blob/master/CHANGELOG.md#v230)).
Could you try with `onsenui@2.3.1` and `react-onsenui@1.3.4`?
Thank you.

**Comment by Bundas** [comment]
Wow, it works now. Thanks
