### ISSUE TITLE
Enhancement:  Swipe to Delete on ons-list-item

### ISSUE THREAD

**Issue by tehg00se** [OnsenUI/OnsenUI#2039]
Would it be possible, or could someone point me in the right direction of a swipe-to-delete function on the ons-list-item element?

I've tried a few things to no avail, including <ons-gesture-detector> on top of the <ons-list-Item> coupled with Vue transitions and delete button, but the animation / transition would not activate on a swipeleft event.

**Comment by misterjunio** [comment]
@tehg00se this is not currently on the table but you can have a look at [this thread in the Community](https://community.onsen.io/topic/1478/swipe-on-ons-list-via-ons-gesturedetector) for some ideas.
