### ISSUE TITLE
Need the ability for "ons.notification.prompt" to resolve input as well as button index.

### ISSUE THREAD

**Issue by humblecoder** [OnsenUI/OnsenUI#2050]
[Core]
    onsenui 2.2.x

[Framework]
    vue 2.1.10

[Framework binding]
    vue-onsenui 2.0.0-alpha.0

[Additional libraries]
    none

[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1

[Browser]
    Mobile - iOS Safari
    Desktop - Chrome 55.0.2883.75
    Desktop - Safari 10.0 (12602.1.50.0.10)

__Encountered problem__
While "ons.notification.prompt" ostensibly extends "ons.notification.alert", it doesn't provide the ability to respond to unique button indexes (e.g. adding a "Cancel" button). 

__Feature request__

Please allow "ons.notification.prompt" to resolve both user input and button index.

**Comment by frandiox** [comment]
@humblecoder It's not possible to resolve to 2 different values, we have to choose one.

However, I'm thinking about a work around. The OK button must always be the last one in the `buttonLabels` array, so we can resolve to the input value only if that button index was pressed. Otherwise, `null` (it's canceled). This wouldn't modify the API and would allow having "Cancel" and "OK" buttons. @asial-matagawa @misterjunio What do you think about that? 601b00726ff47f7d7fb2c94ed8355ad18c88c315

**Comment by misterjunio** [comment]
@frandiox I know it changes the API a bit but why don't we return an object for prompts with a `value` and `index` fields? That line you changed in the commit would be something like

```
const resolveValue = options.isPrompt ? {value: el.input.value, index: index} : index;
```

**Comment by frandiox** [comment]
I'd personally prefer to return 1 single value to be consistent with the other notifications rather than returning objects or arrays :/
We can also leave it as is only with "OK" button since it is already possible to create custom `ons-alert-dialogs`.

**Comment by frandiox** [comment]
@misterjunio Actually, there is a `primaryButtonIndex` property, we can use that as well.

**Comment by misterjunio** [comment]
@frandiox I know we should be consistent but we weren't already by returning `null` when canceled and `-1` in the other dialogs. What's your idea with `primaryButtonIndex`? Making the first one the cancelling button?

**Comment by frandiox** [comment]
@misterjunio We cannot resolve to `-1` in a prompt when canceled because the user can also write `-1` :/
The primary button is the OK button. I guess other buttons won't need to resolve to the input content.

**Comment by misterjunio** [comment]
@frandiox yes I know that I was just saying that since it was already a bit different maybe an object would be the easiest solution but I admit that's quite a lot different. Your idea with `OK` as primary seems good to me
