### ISSUE TITLE
Unsual padding in the toolbar and button with Nexus 5 - using Android 5.5+

### ISSUE THREAD

**Issue by maverickpravin** [OnsenUI/OnsenUI#2058]
![screenshot_20170607-220954](https://user-images.githubusercontent.com/11708491/26890536-6e8f99aa-4bcf-11e7-8ff5-421ee7751919.png)

**Comment by frandiox** [comment]
@misterjunio Can you quickly test this on Android 5.5 or so when you have some time? Here I only have 5.1.1 :sweat_smile:

**Comment by maverickpravin** [comment]
@frandiox ... is there any update for the issue above ?

**Comment by maverickpravin** [comment]
@misterjunio any update ?

**Comment by misterjunio** [comment]
@maverickpravin sorry for the delay. In which version of Onsen UI does this happen to you?
@frandiox I don't have a 5.5 either. On Android 6 with the latest release it looks ok.

**Comment by asial-matagawa** [comment]
@misterjunio 
The latest version of Android 5.x.x is `5.1.1`.

@maverickpravin 
Could you tell us the correct Android version?

**Comment by maverickpravin** [comment]
![screenshot_20170613-121200](https://user-images.githubusercontent.com/11708491/27069672-80efc79c-5033-11e7-9a33-e396b9a8a8f4.png)
![screenshot_20170613-122132](https://user-images.githubusercontent.com/11708491/27069675-83989d16-5033-11e7-83e5-5f2202de87f1.png)

I am using latest version 6 and the device is NEXUS 5
Along with i am using Cloud IDE
Kindly tell me if i am doing something wrong !!!

**Comment by misterjunio** [comment]
@maverickpravin figured out the issue, it was due to the font size display on the phone being set to 'small', that was causing the `line-height` property to be changed in the WebView. Funny enough
