### ISSUE TITLE
More animation options for action sheets

### ISSUE THREAD

**Issue by Leva7** [OnsenUI/OnsenUI#2060]
The toasts have a lot of animation options, some of them are more performant than the other. Those options should be added to action sheets as well, because the current animation is giving low framerates on older devices.

**Comment by frandiox** [comment]
@Leva7 Toasts are more versatile and can be displayed in different positions. However, I think Action Sheet (iOS) and Bottom Sheet (Android) always look the same. Thus, the provided animations are only that. Perhaps it's better to improve the animation performance than creating extra animations. Could you please report the device where it has low framerate?

Also, creating a custom animation is very simple, there is a [guide here](https://onsen.io/v2/docs/guide/js/#extending-animations).

**Comment by Leva7** [comment]
The device I'm using and experiencing issues with is Alcatel One Touch Pixi 3, running custom Android 5.1.1
