### ISSUE TITLE
NPM: ENOENT: no such file or directory, rename 'C:\DivaApp\Diva\node_modules\onsenui' -> 'C:\DivaApp\Diva\node_modules\.onsenui.DELETE'

### ISSUE THREAD

**Issue by JCKodel** [OnsenUI/OnsenUI#2062]
__Environment__ 
Windows

```
[Core]
    onsenui 2.1.0

[Framework]
    Aurelia

[Framework binding]
    Aurelia

[Additional libraries]
    none

[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1
    Desktop - Linux
    Desktop - macOS Sierra
    Desktop - Windows 10

[Browser]
    Mobile - Android WebView
    Mobile - Android Chrome 54.0.2840.85
    Mobile - iOS UIWebView
    Mobile - iOS Safari
    Desktop - Chrome 55.0.2883.75
    Desktop - Safari 10.0 (12602.1.50.0.10)
```

__Encountered problem__
While trying to follow the tutorial:
```
C:\Folder>npm install onsenui --save
npm ERR! path C:\DivaApp\Diva\node_modules\onsenui
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall rename
npm ERR! enoent ENOENT: no such file or directory, rename 'C:\Folder\node_modules\onsenui' -> 'C:\Folder\node_modules\.onsenui.DELETE'
npm ERR! enoent This is related to npm not being able to find a file.
```

__How to reproduce__
npm install onsenui --save on Windows 10?

**Comment by asial-matagawa** [comment]
Hi, @JCKodel!
Thank you for reporting.

This issue was not reproduced on my Windows 10 environment and I guess this is not related to Onsen UI, but related to NPM.
Could you try with the latest version of Node.js and NPM?

Closing this.

**Comment by 47shubh** [comment]
Please stop sending the same mail again and again .

**Comment by pashute** [comment]
I'm on Windows 10 with same problem.  Seems there are many with this problem. 
Are you sure its nothing to do? On a different thread someone did: npm uninstall cordova then restarted PC and the reinstalled and it solved. (By me it did not)
