### ISSUE TITLE
Angular1 | Carousel issue: Carousel does not function properly when using a border

### ISSUE THREAD

**Issue by rgins16** [OnsenUI/OnsenUI#2065]
```
[Core]
  onsenui 2.3.3
  
[Framework]
  angular1 1.5.5

[Framework binding]
 angular1-onsenui latest

[Platform]
  Desktop - Windows 10 64-bit

[Browser]
  Desktop - Chrome 58.0.3029.110 on Windows 10 64-bit
```

__Encountered problem__
I am having issues implementing a carousel in my web app with ng-repeat. Every time I click the next button, the new carousel item is slightly to the left and off the screen. This effect stacks.

Here are screenshots:
![1](https://user-images.githubusercontent.com/16677164/27101267-10bd971c-504f-11e7-975c-f983f5101281.PNG)
![2](https://user-images.githubusercontent.com/16677164/27101270-10c305da-504f-11e7-9b6d-7fad072fdc3d.PNG)
![3](https://user-images.githubusercontent.com/16677164/27101268-10bfa9d0-504f-11e7-8833-27d496400a4c.PNG)
![4](https://user-images.githubusercontent.com/16677164/27101266-10bcf208-504f-11e7-801d-47602d960b5a.PNG)
![5](https://user-images.githubusercontent.com/16677164/27101269-10c0ef48-504f-11e7-8d2b-f2b6e7ebabfa.PNG)

Setting item-width and centered does not fix the problem.

**EDIT:**
When I click the demo link on this post, I experience the problem I describe. After I refresh it, it works as expected.

__How to reproduce__
  Click the arrows to scroll through the carousel.

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<ons-page ng-controller="CarouselController">
  <ons-toolbar>
    <div class="left">
      <ons-toolbar-button ng-click="carousel.prev()">
        <ons-icon icon="md-chevron-left"></ons-icon>
      </ons-toolbar-button>
    </div>
    <div class="center">Carousel</div>
    <div class="right">
      <ons-toolbar-button ng-click="carousel.next()">
        <ons-icon icon="md-chevron-right"></ons-icon>
      </ons-toolbar-button>
    </div>
  </ons-toolbar>

<ons-carousel var="carousel" style="margin: 0 auto; width: 250px !important; height: 100px !important; border-radius: 10px !important; border-color: #337ab7 !important; border-width: 2px !important; border-style: solid !important;" swipeable auto-scroll overscrollable>
    <ons-carousel-item ng-repeat="number in numbersArray">
      <p>
        {{number}}
      </p>
    </ons-carousel-item>tem>
  </ons-carousel>
</ons-page>
```

- __JS__

```javascript
ons.bootstrap()
  .controller('CarouselController', ['$scope', function($scope) {
    
    $scope.numbersArray = [11111, 22222, 33333, 44444, 55555, 66666, 77777, 88888, 99999, 00000];
  }]);
```

**Comment by misterjunio** [comment]
@rgins16 thanks for reporting. You're right, we weren't taking into account the borders when calculating the element's size, that's why the scroll was more than what it should be (in your case 254px = 250px width + 4px border). I just pushed a fix, should be out in the next release.
