### ISSUE TITLE
pushPage data not available in init event when <ons-page> is in  own HTML file

### ISSUE THREAD

**Issue by Wieltje** [OnsenUI/OnsenUI#2072]
Following [this tutorial][1], but with seperate HTML files for each page, produces errors when the html file starts with a comment line. This seems like a bug to me, because if I remove the comment line, it works like a charm.

Does anyone has a suggestion for this (other than 'dont add any comment in the start of your files')?

newPage.html:

    
    <ons-page>
        PAGE CONTENT
    </ons-page>

index.js

    ....
    navigator.pushPage(newPage.html', {
		data: {
			viewModel: {foo: "bar"}
		}
    }

    document.addEventListener('init', function (event) {
		var page = event.target;
        if (!page.data) {
            console.log("ERROR: NO DATA PASSED");
        }
    }
    ....

  [1]: https://tutorial.onsen.io/index.html?external=https://tutorial.onsen.io/tutorial/other/knockout_bindings.html

**Comment by frandiox** [comment]
@Wieltje Hi! Great to see somone using KO :)
Wow, that's super weird. Can you try with the latest 2.4.0 version of Onsen UI? It was released an hour ago and it changed a bit something related to separate files. Not sure if it will fix it but let's try that first. I could not reproduce this issue in vanilla JS but I'd be surprised if it's something KO-specific...

**Comment by Wieltje** [comment]
@frandiox Thanks for the hint; apparently this was already fixed in 2.3.0. Next time I'll update first before issuing an issue ;)
