### ISSUE TITLE
Error trying to find Dialog content on tests

### ISSUE THREAD

**Issue by renanbandeira** [OnsenUI/OnsenUI#2073]
__Environment__ 

```
[Core]
    onsenui 2.1.0

[Framework]
    react 15.4.1

[Framework binding]
    react-onsenui 1.1.0

[Additional libraries]
    enzyme 2.8.2
    jest 18.1.0

[Platform]
    Desktop - macOS Sierra

[Browser]
    Desktop - Chrome 55.0.2883.75
```

__Encountered problem__

I have a page with a Dialog that has a message and some buttons. I would like to test it using Enzyme things like: the Dialog should appear, the content of Dialog should be this and that, some action should be dispatched when clicked on Dialog button. As far as I understood, onsen puts dialogs in the beginning of the DOM and it confuses enzyme to find the dialog and its content.

__How to reproduce__
1- Create a simple React page with a button to show a Dialog and put a button inside the dialog.
2- Using enzyme, try to open the Dialog and click the button inside the Dialog. The button won't be found.

**Comment by frandiox** [comment]
@renanbandeira Hi! I'm not sure what's the issue that we need to fix here. Modals work in this way, they use a "portal" feature to be rendered on top of everything else. I think this is something that Enzyme should take care of:

https://github.com/airbnb/enzyme/issues/536
https://github.com/airbnb/enzyme/issues/252

**Comment by renanbandeira** [comment]
Hi @frandiox, thanks for answering me. To be honest I had this doubt and that's why I created the issue here.

**Comment by frandiox** [comment]
@renanbandeira Sure, no problem, just that we cannot fix this since it's related to how Enzyme works :sweat_smile:
