### ISSUE TITLE
Angular1 | Input issue: Can't check checkbox

### ISSUE THREAD

**Issue by rgins16** [OnsenUI/OnsenUI#2074]
__Environment__
```
[Core]
  onsenui latest
  
[Framework]
  angular1 1.5.5

[Framework binding]
 angular1-onsenui latest

[Platform]
  Desktop - Windows 10 64-bit

[Browser]
  Desktop - Chrome 58.0.3029.110 on Windows 10 64-bit
```

__Encountered problem__
  After updating to 2.4.0 and updating my checkboxes, I am unable to check them when I click on them. I have a touch screen computer. When I touch the checkbox, I am able to check and uncheck the checkbox. 

__How to reproduce__
  Unfortunately, I am unable to reproduce my issue on the tutorial app. My specs are above, maybe it is an issue with chrome? Or maybe fastclick?

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<ons-page>
  <ons-checkbox></ons-checkbox>
</ons-page>
```

- __JS__

```javascript
ons.bootstrap();
```

**Comment by asial-matagawa** [comment]
@rgins16 
It is probably related to #2000.
Could you run `ons.fastClick.destroy();` and add another library such as Hammer.js?

**Comment by rgins16** [comment]
@asial-matagawa I just updated my post. I actually don't have to click three times, just once. I have to touch exactly in the right spot or it won't work. Should I still try ons.fastClick.destroy(); and add another library such as Hammer.js?

**Comment by asial-matagawa** [comment]
@rgins16 
I just identified the cause of this issue.
`ng-model` supports only `input`, so we have to provide another way to synchronize a value with the state of radio/checkbox.
We will investigate this.

**Comment by rgins16** [comment]
ok, thanks.

**Comment by asial-matagawa** [comment]
@rgins16 
Sorry for the frequent replies, we just updated our tutorial for AngularJS 1 binding but it works on my Chrome 58.
Could you try with this code?
https://tutorial.onsen.io/?framework=angular1&category=reference&module=input

**Comment by rgins16** [comment]
@asial-matagawa Not a problem at all. I like helping you guys out.

So I was never able to replicate the issue in the tutorial. It works fine on the link you sent me. I only have this issue on my web app. I could give you the url, but I'd rather send it to you in a personal message.

**Comment by rgins16** [comment]
@asial-matagawa Also there is a new development in this issue. If I include text in the ons-checkbox element, then clicking that text checks and unchecks the checkbox. I still can not click the actual checkbox itself.

**Comment by asial-matagawa** [comment]
@rgins16 
Sorry for the delay!
I have some urgent tasks now, so I would like to see you web app after few days.
Thank you.
