### ISSUE TITLE
Angular1 | Input issue: ons-search-input // can't change width

### ISSUE THREAD

**Issue by rgins16** [OnsenUI/OnsenUI#2075]
__Environment__

  
```
[Core]
  onsenui 2.4.0
  
[Framework]
  angular1 1.5.5

[Framework binding]
 angular1-onsenui latest

[Platform]
  Desktop - Windows 10 64-bit

[Browser]
  Desktop - Chrome 58.0.3029.110 on Windows 10 64-bit
```

__Encountered problem__
  I can not change the width of an ons-search-input. When I use "style" in the html element to change he width, what happens instead is that the box gets shifted to the right the amount of pixels I wanted the width to be.

__How to reproduce__
Click on the demo link below.

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<ons-page>

  <p style="text-align: center; margin-top: 10px">
    <ons-search-input placeholder="Search" style="width: 500px !important;"></ons-search-input>
  </p>
  
</ons-page>
```

- __JS__

```javascript
ons.bootstrap();
```

**Comment by frandiox** [comment]
@rgins16 Thanks for reporting! It also happens to `ons-input`. The DOM changed a bit in 2.4.0 and looks like a specific CSS property is not applied.
For now you can do something like this:

```
ons-input > input, ons-search-input > input {
  width: 100%;
}
```

I think that should fix it.

**Comment by rgins16** [comment]
@frandiox That worked. Thanks!
