### ISSUE TITLE
vue.js range slider wont bind properly

### ISSUE THREAD

**Issue by ericbehughes** [OnsenUI/OnsenUI#2076]
__Environment__ 

```
[Core]
    onsenui 2.1.0

[Framework]
    vue 2.1.10

[Framework binding]
    non
    vue-onsenui 2.0.0-alpha.0

[Additional libraries]
    none

[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1


[Browser]
    Mobile - Android WebView
    Mobile - Android Chrome 54.0.2840.85
    Mobile - iOS UIWebView
    Mobile - iOS Safari
    Desktop - Chrome 55.0.2883.75
    Desktop - Safari 10.0 (12602.1.50.0.10)
```

__Encountered problem__
when you bind the value of a range slider it does not display the computed value properly for vue.js

__How to reproduce__
<v-ons-range v-model="volume" style="width: 100%;"></v-ons-range>

new Vue({
  el: '#app',
  template: '#main',
  data() {
    return {
      volume: 25
    };
  }
});

**Comment by misterjunio** [comment]
@ericbehughes I believe this has already been fixed. Could you try the latest `vue-onsenui@2.0.0-rc.0`?

**Comment by ericbehughes** [comment]
check your website 

Eric Hughes 
1+514-941-3224
e.hughes92@icloud.com

**Comment by frandiox** [comment]
@ericbehughes You were using alpha.0 there? We already have rc.0 and it is working. Check it here: http://tutorial.onsen.io/?framework=vue&category=reference&module=range
