### ISSUE TITLE
Angular 1 | Bug with ons-tabbar update in 2.4.0

### ISSUE THREAD

**Issue by rgins16** [OnsenUI/OnsenUI#2082]
__Environment__

  
```
[Core]
  onsenui 2.4.0
  
[Framework]
  angular1 1.5.11

[Framework binding]
 angular1-onsenui latest

[Browser]
  Latest version of Safari on my iPhone 6+
```

__Encountered problem__
I am using Braintree for e-commerce on my web app. The form that hosts the credit card information fields bleeds through to all other tabs since I updated onsenui in my web app to v2.4.0. I noticed that I do not experience the problem when I downgrade to v2.3.3.

Here are some screen shots to illustrate my point.

This is what the credit card fields look like on the tab they are supposed to be on:
![image](https://user-images.githubusercontent.com/16677164/27308062-c93f4888-551a-11e7-8fa9-d4c5e5fadb3d.png)

This is what the other tabs look like after updating to v2.4.0:
![image](https://user-images.githubusercontent.com/16677164/27308111-021bc35c-551b-11e7-989d-6f55d23b39fd.png)

As you can see, the credit card fields bleed through to the other tabs.

**Comment by frandiox** [comment]
@rgins16 Do you have any custom styles changing `opacity` and `visibility` applied to the pages? There is a change in 2.4.0 where the pages in tabbar use `visibility: hidden` instead of `display: none`, but that shouldn't break anything.

**Comment by rgins16** [comment]
@frandiox I am not using any custom style applied to those pages. I don't know if it matters, but each page in the tabbar is an anguar component. So each page in the tabbar points to the template which is in index.html, and each template only holds the component.

**Comment by frandiox** [comment]
@rgins16 Thanks for the input, I found a similar issue occurring with `ons-switch` because they apply some transition animations. I'll try to revert the `visibility: hidden` commit and release 2.4.2.

**Comment by frandiox** [comment]
@rgins16 This should be fixed in 2.4.2, already released :+1:

**Comment by rgins16** [comment]
@frandiox I can confirm the issue does not occur after updating to v2.4.2. Thank you! Also, I want to make sure you remember: I only experience this issue on mobile.

**Comment by rgins16** [comment]
@frandiox Now that I think about it, animations must be the issue. The credit card information form does an animation when it first appears on the screen.
