### ISSUE TITLE
Request feature: [React] PullHook support pullDistance

### ISSUE THREAD

**Issue by luatnd** [OnsenUI/OnsenUI#2083]
__Environment__ 

```
[Core]
    onsenui 2.3.2

[Framework]
    react 15.5.4

[Framework binding]
    react-onsenui 1.3.4
```

__Encountered problem__
As I can see ons-pull-hook (JS core) already provide the prop: `pullDistance` The current number of pixels the pull hook has moved.

But React doesn't have `pullDistance : https://onsen.io/v2/docs/react/PullHook.html

---
Why I need it, because:
```
 getContent: function() {
    switch (this.state.state) {
      case 'initial':
        return 'Pull to refresh';
      case 'preaction':
        return 'Release';
      case 'action':
        return 'Loading...';
    }
  },
```
support only text, it'll very nice if I can show to user `how many percent` that they pulled, it's useful for applying a ProgressCircular with %, instead of above boring getContent() text.

Thanks for your contributions.

**Comment by frandiox** [comment]
@luatnd For now I guess the only way is to grab the DOM element and access the `pullDistance` property. Perhaps we should implement a hook `onPull` that runs whenever the pull hook is dragged...
Also, you can have icons and other stuff there, not only text. Check for example the pull hook of [this app](https://frandiox.github.io/vue-onsenui-kitchensink/) (it's in Vue).

@asial-matagawa What do you think about that?

**Comment by luatnd** [comment]
>pull hook of [this app](https://frandiox.github.io/vue-onsenui-kitchensink/) (it's in Vue).

Wow that's nice idea 👍 

For me, I calculated pullDistance from `style` attr of a `div` (which is the container of `<ons-pull-hook />` html tag) - by watching the DOM.

![out](https://user-images.githubusercontent.com/1859127/27473515-b3ff1db0-5829-11e7-9a08-3eacc41d1938.gif)

But I know it's a trick, not an good solution !!
Anw, thank you @frandiox
