### ISSUE TITLE
Angular 1 | ons-navigator gives error when reloads the same page

### ISSUE THREAD

**Issue by ceskomira90** [OnsenUI/OnsenUI#2084]
I'm using the current version of onsen: 2.4.0.
When i try to reload the same page, onsen give me always the same error  "You must supply an 'ons-page' element to 'ons-navigator'".

My navigator is declared in this way:
```
<ons-navigator var="menuNavLogin" page="login.html">
    <ons-page ng-controller="loginController">
      ....
    </ons-page>
</ons-navigator>

```
This error becomes when i try to reload the same page.
For example  when the login fails i want that the page of login is replaced by itself.

in the controller the code is this:
```
 menuNavLogin.replacePage('login.html');

```
I tried to use resetToPage and pushPage too but it gives me always the same error.

**Comment by frandiox** [comment]
@ceskomira90 You are supplying `page` attribute to set an initial page, and at the same time you are including an inner page inside the navigator. Choose one of the two, not both. If you want to do replace it afterwards, you'll want to use `page` attribute and `<template>`.

**Comment by ceskomira90** [comment]
if i remove the `page` attribute, the error comes the same. So the only solution is treat login page as a `<template>`?
For example in this way:
`<ons-navigator var="navigator" page="page1.html">
</ons-navigator>
<ons-template id=page1.html ng-controller="controller">
</ons-template>`
and in the controller use the same code:
`navigator.replacePage('page1.html')`

**Comment by frandiox** [comment]
@ceskomira90 Yes, like it's shown in the [tutorial](http://tutorial.onsen.io/?framework=angular1&category=reference&module=navigator). Since 2.4.0 you can use `<template>`, which is native to the browser, instead of `<ons-template>`.

**Comment by ceskomira90** [comment]
@frandiox but if i use this in an `<ons-tabbar>` ? with more `<ons-navigator>`? Because if i remove the `<ons-tabbar>` all works perfectly, but if i add it with more navigator i have several issues.

**Comment by ceskomira90** [comment]
Sorry @frandiox but i continue to have other problems. If i treat as a `<template>` i have several issues  with the `<ons-tabbar>` 
In the **index.html** i declare this:
```
<body ng-app="myApp" >
    <ons-tabbar>
        <ons-tab label="Tab 1" page="login.html" active>
        </ons-tab>
      <ons-tab label="Tab 2" page="page.html">
        </ons-tab>
    </ons-tabbar>
</body>
```

When i try to call the  `<template>` in another page: in this case  **login.html**  with his own navigator like in this example:
```
  <ons-navigator var="menuNavLogin" page="login.html"></ons-navigator>
    <template id="login.html">
        <ons-page ng-controller="loginController">
            .....
        </ons-page>
     </template>
```


**Doesn't show the bottom tabbar.**

Where have I to collocate the `<ons-navigator>`? Naturally if i remove `<ons-tabbar>` all works perfectly.

**Comment by frandiox** [comment]
@ceskomira90 Well, if you don't put the tabbar inside `login.html` template, then of course it won't appear when you create an instance of `login.html` template.

I don't really understand the pattern you want to make. Do you always want to have a visible tabbar in your app? Or only when the login page is shown? I'd recommend you reading Onsen UI guide and checking examples. ToDo app [tutorial](https://onsen.io/blog/auto-style-app-onsen/) might help.

**Comment by ceskomira90** [comment]
Yes i check it. I red all of yout tutorial (GREAT WORK). This issue is new with onsen 2.4.0. 
I want to reload a page after an ajax call:
i have a `<tabbar>` and some pages called in the `<tab>` that have own specified navigator. 
I initialize the  **navigator** in the page that the `<tab>` calls. 

**index.html:**
```
<body ng-app="myApp" >
    <ons-tabbar>
        <ons-tab label="Tab 1" page="login.html" active>
        </ons-tab>
    </ons-tabbar>

   <ons-navigator var="menuNavLogin" page="login.html">
    </ons-navigator>
    <template id="no_login.html">
       .....
   </template>
</body>
```



**## A workaround that now fix the bug is this:**
**index.html:**
```
<body ng-app="myApp" >
    <ons-tabbar>
        <ons-tab label="Tab 1" page="login.html" active>
        </ons-tab>
    </ons-tabbar>
</body>
```
Then i create a **login.html** page that is structured in this way:
```
<ons-page>
    <ons-navigator var="menuNavLogin" page="no_login.html">
    </ons-navigator>
    <template id="no_login.html">
        </ons-page>
    </template>
</ons-page>
```
In the controller i recall:
` menuNavLogin.replacePage('login.html');
`

In this way works, but I don't know if is the correct one.

My goal is to update the same **login.html** so if the call ajax goes fine, the page will display the data captured from the call.

**Comment by frandiox** [comment]
@ceskomira90 In your first example, `ons-tabbar` and `ons-navigator` are siblings and that's not possible or, at least, we haven't made any example/test like that. They must have a parent-child relation like in your "workaround" (that's the right way of structuring the components).

By the way, `<template>` elements are meant to be in `index.html`. It might work like you did but we haven't tested it in that way :P

**Comment by ceskomira90** [comment]
Yes, I tried all the day :D, and at least it seems works ONLY with my "workaround". Thanks for the time @frandiox, Excellent work.

**Comment by misterjunio** [comment]
@ceskomira90 I believe there is a cleaner way to do this. If you put the tabbar in a template and set it as the first page of the navigator then you can reset to that page if the login fails and pass the desired data to reload. Take a look at [this pen](https://codepen.io/misterjunio/pen/LLyQBw?editors=1010).

**Comment by ceskomira90** [comment]
@misterjunio The example is clear, but if have another`<navigator>` in **settings.html** in your example the issue persists, beacuse if i want to reload another page recalling the `<template>` , onsen goes to the **active** page (in this case **home.html**). If exists a method to set dinamically the active page maybe your example fix the issue and naturally cleaner.

**Comment by misterjunio** [comment]
@ceskomira90 you don't need another navigator, you can do what you said by calling the tabbar's `setActiveTab()` on page init. Check out the updated pen 😉
