### ISSUE TITLE
Angular1 | Input issue: Allow enter key to close alert dialog if cancelable is set to true

### ISSUE THREAD

**Issue by shivavelingker** [OnsenUI/OnsenUI#2098]
__Environment__

  
```
[Core]
  onsenui 2.4.2
  
[Framework]
  angular1 1.5.5

[Framework binding]
 angular1-onsenui latest

[Platform]
  Desktop - Windows 8.1 64-bit

[Browser]
  Desktop - Chrome 58.0.3029.110 on Windows 8.1 64-bit
```

__Encountered problem__
  

__How to reproduce__
  

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<ons-page ng-controller="PageController" >
  <ons-toolbar>
    <div class="center">Input</div>
  </ons-toolbar>

  <div style="text-align: center; margin-top: 30px">
    <p>
      <ons-input ng-enter="login()" id="username" modifier="underbar" placeholder="Username" float ng-model="username"></ons-input>
    </p>
    <p>
      <ons-input ng-enter="login()" id="password" modifier="underbar" type="password" placeholder="Password" float ng-model="password"></ons-input>
    </p>
    <p style="margin-top: 30px;">
      <ons-button ng-click="login()">Sign in</ons-button>
    </p>
  </div>
</ons-page>
```

- __JS__

```javascript
ons.bootstrap()
  .controller('PageController', function($scope) {
    $scope.username = '';
    $scope.password = '';

    $scope.login = function() {
      if ($scope.username === 'bob' && $scope.password === 'secret') {
        ons.notification.alert({message: "Correct!", cancelable: true});
      }
      else {
        ons.notification.alert({message: "Incorrect form input", cancelable: true});
      }
    };

  })
  
.directive('ngEnter', function() {
  return function(scope, element, attrs) {
    element.bind("keydown keypress", function(event) {
      if(event.which === 13) {
        scope.$apply(function(){
          scope.$eval(attrs.ngEnter, {'event': event});
        });

        event.preventDefault();
      }
    });
  };
})
  
;
```
I'm not quite sure if this is a feature request or a bug (or something else), but I have a directive that allows users to use their Enter key to submit forms (mainly to be used on the web). When the user hits Enter in this example, the login function is called, which is expected. However, pressing enter again triggers the login function again because the input is still focused. Instead of the alert dialog closing (even though the cancelable attribute is enabled), another one is created on top of the previous one.

I could probably write in to blur the element in the directive, but the feature I'm looking for is for the alert box to disappear when the enter button is clicked. Like [this example](https://www.w3schools.com/js/tryit.asp?filename=tryjs_alert), when an alert dialog is called, pressing enter should remove the alert. Otherwise, the user experience doesn't quite feel right or consistent with other websites.

**Comment by misterjunio** [comment]
@shivavelingker why not in your login function, after showing the dialog, focusing its button? Maybe with a timeout to make sure it works like `setTimeout(function() { document.querySelector('.alert-dialog-button').focus(); },100);`

**Comment by shivavelingker** [comment]
@misterjunio Ah, thanks for that. It would be nice if the feature was automatically included in the `cancelable` attribute since that intuitively makes sense to me, but here's my simple wrapper function if anyone else ever needs it.

```
var notify = function(msg) {
	//Save focused input
	var focused = document.activeElement;

	ons.notification.alert({message: msg, cancelable: true})
	   .then(function(){
		//Return focus to input
		if(typeof focused.focus !== 'undefined')
		   focused.focus();
	   });

	//Set focus on button to allow easy cancellation
	setTimeout(function() { document.querySelector('.alert-dialog-button').focus(); });
}
```
