### ISSUE TITLE
Angular1 | List issue: Longdivider breaks Chevron

### ISSUE THREAD

**Issue by rgins16** [OnsenUI/OnsenUI#2100]
__Environment__

  
```
[Core]
  onsenui latest
  
[Framework]
  angular1 1.5.5

[Framework binding]
 angular1-onsenui latest

[Platform]
  Desktop - Windows 10 64-bit

[Browser]
  Desktop - Chrome 59.0.3071.115 on Windows 10 64-bit
```

__Encountered problem__
Using longdivider as a modifier breaks chevron.

I noticed this in the changelog for v2.0.0-beta.10:

> css-components: Fixed issue with list item using both "chevron" and "longdivider" modifiers.

It appears the problem was caused somewhere in between 2.3.3. and 2.4.0.

> css-components: Refined the appearance of list-item--chevron.

__How to reproduce__
click the link below

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<ons-page>
  <ons-toolbar>
    <div class="center">Chevron Bug</div>
  </ons-toolbar>

  <ons-list>
    <ons-list-header>Default</ons-list-header>
    <ons-list-item modifier="chevron">1 modifier - chevron</ons-list-item>
    <ons-list-item modifier="longdivider">1 modifier - longdivider</ons-list-item>
    <ons-list-item modifier="chevron longdivider">2 modifiers</ons-list-item>
  </ons-list>

  <br />
</ons-page>
```

- __JS__

```javascript
ons.bootstrap();
```

**Comment by frandiox** [comment]
@rgins16 Thanks for reporting!

@anatoo This CSS is causing the issue:

```
.list-item--longdivider.list-item--chevron:before {
    border: none;
    background-image: none;
}
```

I guess that's wrong or is there any reason to have that?

**Comment by anatoo** [comment]
@frandiox Oh sorry, I just made a mistake. I removed that css.

**Comment by frandiox** [comment]
@anatoo No problem, thanks! :smile:
