### ISSUE TITLE
iOS 11 and Statusbar

### ISSUE THREAD

**Issue by mapnia** [OnsenUI/OnsenUI#2101]
Did anyone has any problem with the toolbar with iOS 11 that goes aprox 20px under the top of the screen?

**Comment by Jaimet92** [comment]
Try ons.disableAutoStatusBarFill()

**Comment by jcesarmobile** [comment]
See https://issues.apache.org/jira/browse/CB-12886

You will have to wait to a future cordova-ios release or create a plugin that just do `[self.webView.scrollView setContentInsetAdjustmentBehavior:UIScrollViewContentInsetAdjustmentNever];`
