### ISSUE TITLE
Adding Vuex to default vuex template 

### ISSUE THREAD

**Issue by italomaia** [OnsenUI/OnsenUI#2102]
Folks, vuex is basically used to hold state with vue; it gives you a nice alternative to keeping variables in the root component and handling it through events. If there are no better suggestions, this would enforce quite a bit good practices with onsen.

**Comment by frandiox** [comment]
@italomaia Yep, I'm actually using it for the main version of the [kitchensink app](https://github.com/frandiox/vue-onsenui-kitchensink). What do you exactly mean with adding Vuex to default vuex template? What's the default vuex template? Do you mean Monaca CLI templates or [`vue-cordova-webpack`](https://github.com/OnsenUI/vue-cordova-webpack) for Vue CLI?

**Comment by italomaia** [comment]
@frandiox Yeap, that is what I mean.

**Comment by frandiox** [comment]
@italomaia I will add Vuex option when I have some time since it makes sense to be used with Onsen UI for UI state management. Otherwise, feel free to make a PR to the other repo :)

**Comment by frandiox** [comment]
@italomaia I added Vuex option to `vue-cordova-webpack` template in https://github.com/OnsenUI/vue-cordova-webpack/commit/02b11f39ddffb03dea1c1164578209d476250e0c :+1: 
I'll add it now to `vue-pwa-webpack`.
