### ISSUE TITLE
Input button refreshing page when clicked

### ISSUE THREAD

**Issue by scatman** [OnsenUI/OnsenUI#2113]
An input button does not refresh the page when clicked using  v1.3.6 onsenui.min.js
However when replacing onsen js with a newer version (example 2.4.2) the page refreshes.
[this code works](https://codepen.io/anon/pen/VWRMgb) since it uses  v1.3.6 
try to export the code, replace  v1.3.6 by the newest onsen js. You'll reproduce the issue and the page reloads whenever the button is clicked.

`<script src='https://cdn.rawgit.com/OnsenUI/OnsenUI/1.3.6/build/js/onsenui.min.js'></script>`

`ons.bootstrap();`
`ons.ready(function() {`
`  $('#indexform')`
   ` .submit(function(e) {`
     ` e.preventDefault();`
   ` alert('working');`
`    });`
`});`

   ` <form id="indexform" method="post">`
     ` <input class="login-button button--large button" id="submit" type="submit" name="submit" value="Login">`
 `   </form>`

**Comment by asialgearoid** [comment]
This does not appear to be happening anymore with onsenui@2.8.3.
