### ISSUE TITLE
fontawesome webfonts not found 

### ISSUE THREAD

**Issue by Lenndev** [OnsenUI/OnsenUI#2118]
__Environment__ 

```
[Core]
    onsenui 2.4.2


[Framework]
    vue ^2.2.1

[Framework binding]
    vue-onsenui 2.0.2

[Additional libraries]
    none

[Platform]
    Desktop - macOS Sierra

[Browser]
    Desktop - Chrome  59.0.3071.115
```
__Encountered problem__
orientation.js cannot find font_awesome webfonts.
GET http://localhost:1337/node_modules/onsenui/css/font_awesome/fonts/fontawesome-webfont.woff?v=4.7.0 
GET http://localhost:1337/node_modules/onsenui/css/font_awesome/fonts/fontawesome-webfont.ttf?v=4.7.0 
result: no font awesome icons shown in i.e. navbar left and right button.

![schermafbeelding 2017-07-20 om 13 21 05](https://user-images.githubusercontent.com/15671740/28415045-5d807044-6d4e-11e7-9003-4a571762532a.png)

__How to reproduce__
install onsenui and vue-onsenui via npm import css via gulp-css-importer 
and add @import path/to/css/files/of/onsenui into i.e. build.scss
run vue js via gulp live reload server.
open localhost:<portnr> in chrome and simulate any device within google dev tools

**Comment by frandiox** [comment]
@Lenndev I don't think we can fix this from Onsen UI side. It is likely an issue in your build system. You'll need to configure `gulp-css-importer` and all the rest to find the paths correctly. A template for Vue CLI with Webpack is provided [here](https://github.com/OnsenUI/vue-cordova-webpack) (run `vue init OnsenUI/vue-cordova-webpack`).
