### ISSUE TITLE
iOS ons-range bug

### ISSUE THREAD

**Issue by frandiox** [OnsenUI/OnsenUI#2120]
@anatoo After the last changes to `ons-range` structure, if you tap the track on iOS (tested v10.3.2) the range won't update its value. It works fine when you drag the thumb, though. On Android (v5.1.1) everything works well but sometimes, when tapping a bit above the track, the styles are activated but the value is not updated. I guess the tap event goes to the new second input instead of the main one?

**Comment by anatoo** [comment]
@frandiox Ok, I'm going to fix.

**Comment by anatoo** [comment]
@frandiox 

> if you tap the track on iOS (tested v10.3.2) the range won't update its value.

Do you think that range's value should be updated when you tap the track in iOS?

I tested default `<input type="range">` in iOS, but range's value doesn't be updated on tap the track.

**Comment by frandiox** [comment]
@anatoo To be honest I'm not sure what's the expected behavior on iOS, I just know how Chrome behaves :sweat_smile:
If native ranges only update on drag then there is nothing to fix on iOS. I guess the Android issue is a real bug but perhaps is not that important either.

**Comment by anatoo** [comment]
@frandiox I see. I confirmed that native slider UI doesn't update itself on tap the track, so I intent to fix the Android issue when have a time.
