### ISSUE TITLE
Specs: <ons-segment>

### ISSUE THREAD

**Issue by misterjunio** [OnsenUI/OnsenUI#2121]
@OnsenUI/members Here is my proposal for the `<ons-segment>` component.

### DOM structure
Current implementation expects the usage of buttons inside the segment like this:
```html
<ons-segment>
  <button class="button">Label 1</button>
  <button class="button">Label 2</button>
  <button class="button">Label 3</button>
</ons-segment>
```
which is compiled into:
```html
<ons-segment class="segment">
  <div class="segment__item">
    <input type="radio" class="segment__input" name="ons-segment-gen-1" checked id="ons-segment-gen-1-0">
    <button class="button segment__button">Label 1</button>
  </div>
  <div class="segment__item">
    <input type="radio" class="segment__input" name="ons-segment-gen-1" checked id="ons-segment-gen-1-1">
    <button class="button segment__button">Label 2</button>
  </div>
  <div class="segment__item">
    <input type="radio" class="segment__input" name="ons-segment-gen-1" checked id="ons-segment-gen-1-2">
    <button class="button segment__button">Label 3</button>
  </div>
</div>
```
Another option would be to have another component `<ons-segment-item>` inside `<ons-segment>` but it's such a simple component that I feel that's not necessary and this syntax seems to me intuitive and easy to use enough.

### Connection to `<ons-tabbar>`
Currently users can pass a `tabbar` attribute to `<ons-segment>` with the ID of the `<ons-tabbar>` they want to connect the segment. This automatically hides the tabbar and syncs the active button of the segment with the active tab of the tabbar.

Eventually the `<ons-tabbar>` could be found automatically in the DOM but since there may be more than one I think's it's better to just let users pass the ID.

Obviously this is expected to be used in a toolbar otherwise the tabbar pages would hide the segment. By default the styles already work in the `<ons-toolbar>`.

### Attributes
* `tabbar` - ID of the `<ons-tabbar>` to "connect" to the segment
* `active-button` - index of the first active button, only works if there is no connected tabbar (in which case the active tab sets the active button)

### Properties
* `tabbar` - to provide easier access to the connected tabbar

### Methods
* `setActiveButton((index, [options])` - makes button with the specified index active; if there is a connected tabbar it shows the corresponding tab page; in this case animations and other options can be specified by the second parameter
* `getActiveButtonIndex()` - returns button index of current active button; if active button is not found, returns -1

### Events
* `change` - thrown when the active button changes

The component code is in the [segment branch](https://github.com/OnsenUI/OnsenUI/tree/segment).
Any opinions are welcome.

**Comment by frandiox** [comment]
@misterjunio Thanks for sharing! A few thoughts:

* Perhaps only one of `<button>` or `class="button"` should be necessary. I think `ons-toast` accepts any of them.
* I'd prefer `tabbar-id` rather than `tabbar` attribute to make it more specific.
* In the tabbar we have an `active-index` attribute. Perhaps we should use the same name for the segment instead of `active-button`. It is also more specific since it expects an actual index.
* `change` is a native event for inputs so I think we should avoid using it. Tabbar and carousel fire `postchange` instead, perhaps we could use that.

**Comment by misterjunio** [comment]
@frandiox thanks for the feedback.
* Only `<button>` works, I left the `class` in the example by mistake.
* Agreed on the rest, `tabbar-id`, `active-index` and `postchange` it is.

**Comment by frandiox** [comment]
@anatoo @asial-matagawa Anything to add?

**Comment by asial-matagawa** [comment]
@misterjunio @frandiox 
I guess `setActiveButton` and `getActiveButtonIndex` should be `setActiveIndex` and `getActiveIndex` like [Carousel](https://onsen.io/v2/api/js/ons-carousel.html#methods-summary)?

**Comment by misterjunio** [comment]
@asial-matagawa I followed the [Tabbar](https://onsen.io/v2/api/js/ons-tabbar.html#methods-summary) but that also works, I don't mind changing if you think it's more intuitive.

**Comment by asial-matagawa** [comment]
@misterjunio 
Oh, I see.
Actually in the past `ons-carousel#getActiveCarouselItemIndex` was renamed to `ons-carousel#getActiveIndex` and I just remembered that.

I think following Tabbar is better in this case. Thank you for information!
