### ISSUE TITLE
[2.5.0]React | <Range> issue: material-design focus-ring position bug 

### ISSUE THREAD

**Issue by Songkeys** [OnsenUI/OnsenUI#2123]
Hey!
There is a little issue related to the` ons-range` happens with React `<Range>` in onsenui 2.5.0.
You can simply reproduce this [here](http://tutorial.onsen.io/?framework=react&category=reference&module=range). On Android View, the material-design style appears really strange (`.range--material__focus-ring`) while it works fine on every other framework.
And, I really appreciate your hard work on the new version. Love the iOS swipe-to-pop page animation best! XD
Thanks a lot

**Comment by frandiox** [comment]
@Songkeys Thanks for reporting! It's actually not a problem in React, but in the `ons-range` custom element. The focus doesn't consider `min` and `max` attributes. @anatoo Can you have a look at it? I guess the second input needs to get those attributes as well.
