### ISSUE TITLE
VUE support in Monaca online IDE?

### ISSUE THREAD

**Issue by pashute** [OnsenUI/OnsenUI#2130]
If I'm developing on the cloud Monaca IDE how do I start the development.

You sent a message that you finished developing Monaca-VUE but it is not clear if it's possible to run it on the cloud IDE, if so how, and if not, that knowledge is not clear. Thanks.

In your paper about Monaca-VUE just say that currently you cannot create an online VUE project yet.

**Comment by frandiox** [comment]
@pashute Hi! Please post these questions in the Monaca Tools section of the [forum](https://community.onsen.io/category/4/monaca-tools), it will be answered there :+1: 

I think the Cloud IDE does not support Webpack right now. The support probably refers to Monaca CLI and LocalKit.
