### ISSUE TITLE
Splitter side does not open with React 16.

### ISSUE THREAD

**Issue by airamrguez** [OnsenUI/OnsenUI#2131]
Now that [React Fiber is ready](http://isfiberreadyyet.com/) I've tested with my apps and everything seems to work ok except the SplitterSide.

__Environment__

```
[Core]
    onsenui 2.6.0

[Framework]
    react 16.0.0

[Framework binding]
    react-onsenui 1.6.0

[Additional libraries]
    none

[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1
    Desktop - Linux
    Desktop - macOS Sierra
    Desktop - Windows 10

[Browser]
    Mobile - Android WebView
    Mobile - Android Chrome 54.0.2840.85
    Mobile - iOS UIWebView
    Mobile - iOS Safari
    Desktop - Chrome 55.0.2883.75
    Desktop - Safari 10.0 (12602.1.50.0.10)
```

__Encountered problem__

Splitter side does not open with React 16.

__How to reproduce__

[Demo](https://codesandbox.io/s/xGg2rQv7l)

**Comment by airamrguez** [comment]
I've updated all the dependencies from the Demo now that React has been officially released. The error is still there.

**Comment by frandiox** [comment]
The error is just a small change in the latest version, just use `swipeable` instead of `isSwipeable`. Everything else is working (after adding a click handler to the toolbar button): https://codesandbox.io/s/x20wnr01mp

**Comment by airamrguez** [comment]
@frandiox Cool!!!
