### ISSUE TITLE
【Vue】autoScrollRatio dont's work!!!

### ISSUE THREAD

**Issue by baixiaoyu2997** [OnsenUI/OnsenUI#2136]
i  use autoScrollRatio in vue dont's work ,but auto-scroll-ratio is fine, this is bug???

onsenui:2.5.1,
vue-onsenui:2.1.0

**Comment by frandiox** [comment]
@baixiaoyu2997 Have a look at [Vue guide](https://vuejs.org/v2/guide/components.html#camelCase-vs-kebab-case). In a template, `auto-scroll-ratio` is the correct syntax.
