### ISSUE TITLE
Onsen-Vue: better v-ons-select component

### ISSUE THREAD

**Issue by marcusvbp** [OnsenUI/OnsenUI#2137]
Hi!

I want to make a suggestion for a better v-ons-select component:

![Better Select component](https://user-images.githubusercontent.com/4376611/28995211-798f79c0-79b9-11e7-8e82-50208fd8214c.png)

I make a gist with the code for this:

https://gist.github.com/marcusvbp/430c14469e497e1fab2b1473853fd9fd

Cheers.

**Comment by frandiox** [comment]
@marcusvbp Hi, thanks for sharing! The `v-ons-select` component simply relies on `ons-select` custom element and it must be like that. Therefore, if we implement or improve something like this, it must be done in a custom element, not in a Vue component.

That said, this element is actually a simple select that displays a native drop-down in iOS and Android. It might look too simple in desktop Chrome, for example, but looks fine on devices. Therefore, I think for now we'll stick to the current `ons-select` style, but thanks a lot for making this and sharing it.

We'll make a list of resources made by the community and we can probably add your gist :+1:
