### ISSUE TITLE
ons-pull-hook is showed after popPage()

### ISSUE THREAD

**Issue by puku0x** [OnsenUI/OnsenUI#2138]
__Environment__ 

```
[Core]
    onsenui 2.5.0

[Framework]
    angular1 1.6.5

[Framework binding]
    angular-onsenui 2.5.0

[Additional libraries]
    none

[Platform]
    Desktop - macOS Sierra

[Browser]
    Desktop - Chrome 59.0.3071.115
```

__Encountered problem__

The contents in &lt;ons-pull-hook&gt; is showed after popping a page since 2.5.0.

__How to reproduce__

1. Create a page which has an &lt;ons-pull-hook&gt;
2. Push a page
3. Pop the page

https://codepen.io/puku0x/pen/brgRwp

**Comment by misterjunio** [comment]
@puku0x thanks for reporting but that was already reported and fixed, will be out soon in the next release 👍
