### ISSUE TITLE
Core | Tabbar issue: Tabbar not rendering.

### ISSUE THREAD

**Issue by ableabhijeet** [OnsenUI/OnsenUI#2141]
__Environment__

  
```
[Core]
  onsenui latest
  
[Platform]
  Desktop - Windows 10 64-bit

[Browser]
  Desktop - Chrome 60.0.3112.90 on Windows 10 64-bit
```

__Encountered problem__
  Tabbar is not rendering. I expect it to show 2 tabs - Pending & Completed

__How to reproduce__
  https://codepen.io/abhijeets81/pen/eEgQJE

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<template id="main">
  <v-ons-page>
    <v-ons-tabbar :visible="true" :tabs="tabs" position="top">
    </v-ons-tabbar>
  </v-ons-page>
</template>

<template id="pendingPage">
  <v-ons-page>
    <p>pending items</p>
  </v-ons-page>
</template>

<template id="completedPage">
  <v-ons-page>
    <p>completed items</p>
  </v-ons-page>
</template>

<div id="app"></div>
```

- __JS__

```javascript
const pendingPage = {
  template: '#pending'
};

const completedPage = {
  template: '#completed'
};

new Vue({
  el: '#app',
  template: '#main',
  data() {
    return {
      tabs: [
        {
          icon: 'ion-home',
          label: 'Pending',
          page: pendingPage
        },
        {
          icon: 'ion-ios-bell',
          label: 'Completed',
          page: completedPage
        }
      ]
    };
  }
});
```

**Comment by frandiox** [comment]
@ableabhijeet I'm confused. You are reporting a bug using Vue and Onsen UI but you are not including Vue bindings (`vue-onsenui` package). On top of that, you have errors in the code such as using incorrect ids for your elements. [Here is your code fixed](https://codepen.io/frankdiox/pen/NvdEaR?editors=1010).

**Comment by ableabhijeet** [comment]
@frandiox sorry. I put wrong ids there. Could you please take a look at my original question posted here 
https://stackoverflow.com/questions/45540714/insert-tab-pages-inside-v-ons-tabbar. I expect my component to render two tabs - Pending & Completed. But, It only renders completedPage.

**Comment by frandiox** [comment]
@ableabhijeet You expect your component to render two tabs and indeed your component is rendering two tabs :sweat_smile: Check the link I gave you in my last comment.

**Comment by ableabhijeet** [comment]
```
   <template>
      <v-ons-page>
        <v-ons-tabbar :visible="true" :tabs="tabs" position="top">
        </v-ons-tabbar>
      </v-ons-page>
    </template>

    <template id="pendingPage">
      <v-ons-page>
      <p>pending items</p>
      </v-ons-page>
    </template>

    <template id="completedPage">
      <v-ons-page>
      <p>completed items</p>
      </v-ons-page>
    </template>
    <script>

    import Vue from 'vue';

    const pendingPage = {
      template: '#pendingPage'
    };

    const completedPage = {
      template: '#completedPage'
    };

    export default {
      data() {
        return {
          activeIndex: 0,
          tabs: [
            {
              label: 'Pending',
              page: pendingPage
            },
            {
              label: 'Completed',
              page: completedPage
            }
          ]
        };
      }
    };
```

**Comment by ableabhijeet** [comment]
Sorry about the confusion. Your solution works well with `app `component. I have above piece of code in different component. I include that component in some other component. That's when the problem occurs. It doesn't render two tabs.

**Comment by ableabhijeet** [comment]
It always renders completedPage only.

**Comment by frandiox** [comment]
@ableabhijeet Then the issue is in the other component or in the way you include one inside another, not in this code :sweat_smile:

**Comment by ableabhijeet** [comment]
I don't think so. After all, It renders completedPage but not pendingPage.

**Comment by ableabhijeet** [comment]
I added 

```
<template id="main">

&

export default {
  template: '#main',
```

But that didn't make any difference. 

I am wondering how come this component is working fine as App.

**Comment by ableabhijeet** [comment]
@frandiox I tried different approach. But then I get different error.

```
<template>
  <v-ons-page>
    <v-ons-tabbar position="top">
      <v-ons-tab label="Pending" active>
        <v-ons-page>
        </v-ons-page>
      </v-ons-tab>
      <v-ons-tab label="Completed">
        <v-ons-page>
        </v-ons-page>
      </v-ons-tab>
    </v-ons-tabbar>
  </v-ons-page>
</template>
```
Error - **Uncaught (in promise) Error: Page was not provided to index 0**

I am happy to take either approach but just want to make this component render two tabs.
Do you have any example to share with me? Example which shows how to include two` v-ons-page` templates inside `v-ons-tabbar`. I would like to see this done in a component other than `App `component.

**Comment by frandiox** [comment]
@ableabhijeet Sure, take a look at the [kitchensink app](https://github.com/OnsenUI/vue-onsenui-kitchensink). The tabbar is not the "top" component so I guess it works as an example.
This new approach that you took is a bit wrong, a page cannot be inside a tab. The tab is just a button. Have a look at the t[abbar tutorial](http://tutorial.onsen.io/?framework=vue&category=reference&module=tabbar) and check the last page of the explanation, there is an alternative syntax kind of similar to what you tried here.

**Comment by ableabhijeet** [comment]
@frandiox 

`<template slot="pages">did the trick.` That's exactly what I was missing in my component.

 Thanks.

**Comment by ableabhijeet** [comment]
Just last question regarding  :infinite-scroll,

`<v-ons-page :infinite-scroll="loadMore">`

From the documentation of   `:infinite-scroll`
`loadMore()` will be called when the scroll is near the bottom,

I wish to call `loadMore()` whenever user scrolls, no matter scroll is near the bottom or not. 

Is there any way I could achieve this?

**Comment by frandiox** [comment]
@ableabhijeet That's made with a plain `scroll` event listener in JavaScript. In Onsen UI, the scrollable elements are the page content elements. You can provide your own content element as explained in the [docs](https://onsen.io/v2/guide/vue/index.html#vonspage-compilation). After that, you can add a listener with `<div class="content" @scroll="doSomething()">`.
