### ISSUE TITLE
noshadow is applied when tabbar has position of "top"

### ISSUE THREAD

**Issue by ericbehughes** [OnsenUI/OnsenUI#2142]
onsenui 2.1.0

[Framework]
    vue 2.1.10

[Framework binding]
    vue-onsenui 2.0.0-alpha.0

[Additional libraries]
    none

[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1
    Desktop - Linux
    Desktop - macOS Sierra
    Desktop - Windows 10

[Browser]
    Mobile - Android WebView
    Mobile - Android Chrome 54.0.2840.85
    Mobile - iOS UIWebView
    Mobile - iOS Safari
    Desktop - Chrome 55.0.2883.75
    Desktop - Safari 10.0 (12602.1.50.0.10)
```

__Encountered problem__
noshadow is applied to toolbar when you move tabbar to position top
we would like the shadow to remain there even though tabbar is on position top
__How to reproduce__
https://codepen.io/anon/pen/wqJvGB

if pen doesnt work go to this link 
https://tutorial.onsen.io/?framework=vue&category=reference&module=tabbar

and change position of tabbar to top and should get same behavior

**Comment by frandiox** [comment]
@ericbehughes Well, we actually consider `noshadow` modifier to be a fix for the ugly shadow between toolbar and tab bar. There is no parameter to remove this "fix" so the only solution is to manually remove the modifier:

```html
<v-ons-toolbar ref="toolbar">
```

```javascript
  mounted() {
    const modifier = this.$refs.toolbar.$el.getAttribute('modifier');
    this.$refs.toolbar.$el.setAttribute('modifier', modifier.replace('noshadow', ''));
  }
```

I'd like to implement a new syntax for `modifier` prop similar to Vue classes: `:modifier="{noshadow: false, ...}"`, but that will take some time.
