### ISSUE TITLE
Navigator nested in a Tabbar contains flickr bug on pushPage - only on IOS - verified on IOS 10.3.2

### ISSUE THREAD

**Issue by barckq** [OnsenUI/OnsenUI#2143]
__Environment__ 

```
[Core]
    onsenui 2.4.2

[Framework]
    react 15.6.1

[Framework binding]
    react-onsenui 1.5.0

[Platform]
    Mobile - iOS 10.3.2

[Browser]
    Mobile - iOS UIWebView
```

__Encountered problem__
When a navigator inside a tab from tabbar run a slide animation created by a pushPage, randomly before the end of the animation, the previous page come back and is displayed very briefly.

__How to reproduce__
It happens only on IOS UIWebView and is caused by the fact to have multiple page in a tab, for example: 
```
<ons-tabbar>
	<div class="ons-tabbar__content tabbar__content">
		<ons-page class="myTab">/* Useless Page to wrap a navigator inside a Tab causing the bug */
			<ons-navigator>
				<ons-page>
					first page visible on first tab
				</ons-page>
			</ons-navigator>
		</ons-page>
		<ons-page class="myTab">/* Useless Page to wrap a navigator inside a Tab causing the bug */
			<ons-navigator>
				<ons-page>
					first page visible on second tab
				</ons-page>
			</ons-navigator>
		</ons-page>
	</div>
	<div class="tabbar ons-tabbar__footer ons-tabbar-inner"></div>
</ons-tabbar>
```
The Tabbar component force us to inject only a Page element in tab, we can't just say, accept a navigator as content for the tab, if we do, we got the error : 
```
Uncaught Error: Invalid state: page element must be a "ons-page" element.
    at HTMLElement._getCurrentPageElement (onsenui.js:8830)
    at HTMLElement.setActiveTab (onsenui.js:8923)
    at HTMLElement._onClick (onsenui.js:8222)
    at FastClick.sendClick (onsenui.js:33980)
    at FastClick.onTouchEnd (onsenui.js:34282)
    at HTMLBodyElement.<anonymous> (onsenui.js:33786)
```
But if we comment the lines 8829 to 8831 in the _getCurrentPageElement method of TabbarElement
```
if (page && page.nodeName.toLowerCase() !== 'ons-page') {
    throw new Error('Invalid state: page element must be a "ons-page" element.');
}
```
the tabbar works and the flickr bug disappeared caused by the delete of the first page use to wrap the navigator as below :
```
<ons-tabbar>
	<div class="ons-tabbar__content tabbar__content">
		<ons-navigator class="myTab">
			<ons-page>
				first page visible on first tab
			</ons-page>
		</ons-navigator>
		<ons-navigator class="myTab">
			<ons-page>
				first page visible on second tab
			</ons-page>
		</ons-navigator>
	</div>
	<div class="tabbar ons-tabbar__footer ons-tabbar-inner"></div>
</ons-tabbar>
```

**Comment by frandiox** [comment]
@barckq Thanks for reporting. I've spent quite a lot of time debugging this on the last development version but couldn't find any flickering. I tried iOS 10.3.2 and UIWebView as well :/

We enforce that "useless" page there just to normalize the structure and ensure that we can call internal APIs implemented in `ons-page` that might not be implemented in `ons-navigator`. You can of course remove it in your custom version if it works for you.

If you want to try out the latest development version, you can download it [here](https://circleci.com/api/v1/project/OnsenUI/OnsenUI/latest/artifacts/0/$CIRCLE_ARTIFACTS/onsenui.zip?branch=master&filter=successful). Make sure you also copy the CSS, not only the JS.
