### ISSUE TITLE
react example - TypeError: __WEBPACK_IMPORTED_MODULE_4_react_onsenui___default.a is undefined

### ISSUE THREAD

**Issue by ulf1** [OnsenUI/OnsenUI#2149]
i'm following your example at
```
https://onsen.io/v2/guide/react/index.html#setup-react-bindings
```

(1) importing the whole object crashes
```
import Ons from 'react-onsenui';
```
with the error msg
```
TypeError: __WEBPACK_IMPORTED_MODULE_4_react_onsenui___default.a is undefined
```
due to `<Ons.Page>` (the first occurence of `Ons`). 

(2) if you import each class it works
```
import {Page, Toolbar, Button} from 'react-onsenui';
```

(3) importing both
```
import Ons, {Page, Toolbar, Button} from 'react-onsenui';
```
still fails with error msg:
```
TypeError: Cannot read property 'Page' of undefined
```
still regarding `<Ons.Page>` (the first occurence of `Ons`).

**Comment by frandiox** [comment]
@ulf1 I think that syntax is actually not equivalent to the one used in the example:

1. `<script src="react-onsenui.js"></script>`, then use `window.Ons`
2. `var Ons = require('react-onsenui.js');`
3. `import * as Ons from 'react-onsenui.js`

**Comment by ulf1** [comment]
```
import * as Ons from 'react-onsenui';
```
worked
