### ISSUE TITLE
Unsynchronized `class` and `className` in React binding of OnsenUI

### ISSUE THREAD

**Issue by guywald1** [OnsenUI/OnsenUI#2158]
__Environment__ 

```
[Core]
    onsenui 2.1.0

[Framework]
    react 15.4.2

[Framework binding]
    react-onsenui 1.1.0

[Additional libraries]
    none

[Platform]
    Desktop - macOS Sierra

[Browser]
    Desktop - Chrome/60.0

[UserAgent]
    Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6)
    AppleWebKit/537.36 (KHTML, like Gecko)
    Chrome/60.0.3112.101 Safari/537.36
```

__Encountered problem__
When adding a dynamic `className` property to a `react-onsenui` component (specifically, `ListItem`), when the property changes, the `class` item on the DOM element itself doesn't change properly. For instance, when changing a component's `className` from `box black` to `box`, the `class` property on the DOM element won't remove the `black` class from itself.

__How to reproduce__
Change a `ListItem` component's class from `box black` to `box` -- the `class` property on the DOM element won't remove the `box` class from itself.

**Comment by frandiox** [comment]
@guywald1 Are you using `setState` to change the value? Otherwise, I think React won't update the component. I just tried with the latest version and looks like it works well. Please provide a small example reproducing this (you can start from [here](http://tutorial.onsen.io/?framework=react&category=reference&module=list)).

**Comment by burka** [comment]
@frandiox I have the same issue and created a codepen.
https://codepen.io/anon/pen/OQRKeW?editors=1111

**Comment by burka** [comment]
If you only add a className later on, it works for me :-) Just don't add it in the beginning.

`
  constructor(props) {
    super(props);
    this.state = {freshlyInitiliazied: true};
  }

  componentDidMount() {
    if (this.state.freshlyInitiliazied)
      setTimeout(() => this.setState({freshlyInitiliazied: false}), 1);
  }

  getClassName() {
    const {selected} = this.props;
    if (this.state.freshlyInitiliazied)
      return '';

    const selectedClassName = selected ? 'selected' : '';
    return 'FormIndexItem ' + selectedClassName;
  }

  render() {
    const {label, groupId} = this.props;
    return (<ListItem className={this.getClassName()}>
      <Link replace to={'/editor/' + groupId}
            className={'FormIndexItem__Link'}>
        {label}
      </Link>
    </ListItem>);
  }
`

But I still don't get it why react-onsenui acts directly on the DOM node and always changes all classNames, whether they have changed or not. That can surely impact performance badly and negates the advantage of using a virtual dom....
