### ISSUE TITLE
Pull to refresh

### ISSUE THREAD

**Issue by khoshrou** [OnsenUI/OnsenUI#216]
Hi
Can you provide a pull to refresh component.
Or give list such a feature.

**Comment by mmfarahat** [comment]
+1111111111

**Comment by eecsxielu** [comment]
+1

**Comment by RezaRahmati** [comment]
+1
I have tried to apply ng-iscroll to onsen ui but it doesn't work on ons-list

**Comment by RezaRahmati** [comment]
Would you let us know about the estimated release date?

**Comment by Hirbod** [comment]
Can't wait for it. This and slide-left to popPage() are the most important missing features in OnsenUI.

**Comment by argelius** [comment]
Implemented in https://github.com/OnsenUI/OnsenUI/commit/db75011f0b39d44a0d0d08d6230f8d3a1f21192a.

**Comment by RezaRahmati** [comment]
@argelius it is a great news, how could we get this version?

**Comment by argelius** [comment]
It will be released pretty soon. If you want to try it now you can check out the `pull-to-refresh` branch and build from source.

To build the library you can do

```bash
npm install
npm install -g gulp # If you don't have gulp installed.
gulp build
```

**Comment by khoshrou** [comment]
Thanks, can you believe how much joy you have brought to onsenui community

**Comment by hyyan** [comment]
@argelius Thanks for the great work .

**Comment by mmfarahat** [comment]
This is awesome , thank you

**Comment by eecsxielu** [comment]
@argelius Thank you! Would it be possible to implement this on <ons-scroller> ?

**Comment by eecsxielu** [comment]
@argelius Thank you! Would it be possible to implement this on ons-scroller?

**Comment by argelius** [comment]
@eecsxielu It's designed to be used with an `<ons-page>` element.

**Comment by Hirbod** [comment]
:(. So I can't use it without modifying everything :(. I was sure this will be an ons scroll directive. I'll try how I can achieve it :). Thank you @argelius

**Comment by elieldinaully** [comment]
Hi, just tried it and works fine on chrome or firefox. But when i try it on android with cordova, i can't pull to refresh.

**Comment by errlogb** [comment]
Hi, just tried it and works fine on chrome or firefox. But when i try it on android with cordova, i can't pull to refresh.

**Comment by argelius** [comment]
Thanks @errlogb!

I'll debug that.

**Comment by argelius** [comment]
@errlogb 
Works well on Android 4.4 with Cordova. What Android version are you using? Are you using Crosswalk?

**Comment by errlogb** [comment]
@argelius 
I have an Android 4.4.2 (Galaxy S5) . And not using crosswalk.

I'm using a sliding menu on my main page. When i change page with that sliding menu to a defined template with a page in it with the ons-pull-hook inside it, it works fine on chrome/firefox, but not on Android. I haven't tried it yet on iOs.

Main : 

  <ons-navigator var="myNav">
    <ons-page>	
			<ons-sliding-menu
							  main-page="events.html"
							  menu-page="menu.html"       
							  side="left"
							  max-slide-distance="250px"
							  var="menu"
							  ng-show="!isLandscape">
			</ons-sliding-menu>
			
			<ons-split-view
				secondary-page="menu.html"
				main-page="events.html"
				main-page-width="70%"
				collapse="portrait"
				var="menu2"
				ng-show="isLandscape">
			</ons-split-view>
			
			<ons-toolbar>
					<div class="left">
						<ons-toolbar-button ng-click="menu.toggleMenu()" ng-show="!isLandscape"><ons-icon icon="ion-navicon" style="font-size: 32px; width: 1em;"></ons-icon></ons-toolbar-button>
					</div>
					<div class="center"><img src="public/img/logo.png" height="30px" style="margin-top:10px;"></div>
			</ons-toolbar>
    </ons-page>
  </ons-navigator>

Template : 

		<ons-template id="events.html">  
			 <ons-page  ng-controller="EventsController">
				   <ons-pull-hook ng-action="load($done)" var="loader">
					  <span ng-switch="loader.getCurrentState()">
						<span ng-switch-when="preaction"><ons-icon size="35px" icon="ion-arrow-up-a"></ons-icon> Release to refresh</span>
						<span ng-switch-when="action"><ons-icon size="35px" spin="true" icon="ion-load-d"></ons-icon> Loading data...</span>
					  </span>
					</ons-pull-hook>
				
				
					<ons-list>
						<ons-list-header>{{nom}}</ons-list-header>
						<ons-list-item modifier="chevron" class="item" ng-repeat="event in events | filter :  {idType : byIdType}" ng-click="showDetail(event.id)">
							<ons-row>
								<ons-col width="60px">
								  <img src="http://www.bernardlazare.org/wp-content/uploads/2014/09/conference.jpg" class="item-thum">
								</ons-col>
								<ons-col>
								<header>
									<span class="item-title">{{event.date | date : "d MMMM yyyy"}}</span>
								</header>
								<p class="item-desc">{{event.title | uppercase}}</p>
								</ons-col>
							</ons-row>                          
						</ons-list-item>
					</ons-list>
			</ons-page>
		</ons-template>


If i put the ons-pull-hook inside the ons-page of the main page (inside the ons-navigator). It works on Android. What is weird, is when i try it on chrome before building the app with cordova and trying it on android, it works fine.

Thanks for your help.

**Comment by errlogb** [comment]
Alright, my bad, i've just updated all the files from the beginning including all the js/css files, all is working perfectly. Sorry for that. And thanks for that feature!

**Comment by argelius** [comment]
Great :)
