### ISSUE TITLE
Check boxes and segments are not displayed correctly in firefox

### ISSUE THREAD

**Issue by pinpikokun** [OnsenUI/OnsenUI#2161]
```
[Core]
    onsenui 2.5.3

[Platform]
    android 4, 6, 7

[Browser]
    firefox 55
```

Reproducing when you display the official page of onsenui on firefox of android

[segment](https://twitter.com/pinpikokun/status/902742645407023104)

[checkbox](https://twitter.com/pinpikokun/status/902742512342769664)

**Comment by asial-matagawa** [comment]
@pinpikokun 
Thank you for reporting!

Currently Firefox is not included in officially supported browsers of Onsen UI due to resource-related reasons. Thank you for understanding.
https://onsen.io/v2/guide/#browser-and-device-support
