### ISSUE TITLE
[iOS] `<script>` in `<ons-page>` does not work if the page is defined in a external file

### ISSUE THREAD

**Issue by asial-matagawa** [OnsenUI/OnsenUI#2163]
@frandiox 

__Environment__ 

```
[Core]
    onsenui 2.5.3

[Framework]
    none

[Framework binding]
    none
[Additional libraries]
    none

[Platform]
    Mobile - iOS 9
    Mobile - iOS 10

[Browser]
    Mobile - iOS UIWebView
```

__Encountered problem__

`<script>` in `<ons-page>` does not work if the page is defined in a external file.
This problem occurs only on iOS UIWebView (I am not sure about iOS Safari).
On Android WebView, it works fine.

__How to reproduce__

```html
<!-- index.html -->
<ons-navigator page="page1.html"></ons-navigator>
```

```html
<!-- page.1.html -->
<ons-page>
  <script>
    ons.getScriptPage().onInit = function() {
      alert(1);
    };
  </script>
</ons-page>
```

**Comment by asial-matagawa** [comment]
Fixed in 13f55f90ab71f330412021cb7071959d8a01d81b and will be released in `onsenui@2.6.0`.

Closing.

**Comment by frandiox** [comment]
@asial-matagawa Did you test that this is fixed? The bug I fixed was actually different and I'm not completely sure it works for this.

**Comment by asial-matagawa** [comment]
@frandiox 
Oh, I see. Then I will reopen this issue and test it again
