### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by vunnysher** [OnsenUI/OnsenUI#2164]
I just found the a little typo in docs. Under the 
https://onsen.io/v2/guide/vue/index.html#the-usdons-object
there is:
"through Vue’s protoytpe"

**Comment by frandiox** [comment]
@vunnysher You can hit the `Improve this` button at the top of the page and fix it if you want :)

**Comment by vunnysher** [comment]
Oh sorry, i totally didnt see that. Sorry for unnecessary issue ;-;

**Comment by frandiox** [comment]
@vunnysher No problem, thanks!
