### ISSUE TITLE
Children not destroyed

### ISSUE THREAD

**Issue by ableabhijeet** [OnsenUI/OnsenUI#2168]
__Environment__ 

```
[Core]
    onsenui 2.1.1

[Framework]
    vue 2.4.2

[Framework binding]
    vue-onsenui 2.1.1

[Additional libraries]
    none

[Platform]
    Desktop - Windows 10

[Browser]
    Desktop - Chrome 55.0.2883.75
```

__Encountered problem__

```
<template>
    <v-ons-page>
        <div class="content">
            <v-ons-tabbar position="top">
                <template slot="pages">
                    <v-ons-page>
                        <Pending></Pending>
                    </v-ons-page>
                    <v-ons-page>
                        <Completed></Completed>
                    </v-ons-page>
                </template>
            </v-ons-tabbar>
        </div>
    </v-ons-page>
</template>

<script>

    import Vue from 'vue';
    import Pending from './Pending.vue';
    import Completed from './Completed.vue';

    export default {
        name: 'HomePage',
        components: {Pending, Completed},
        destroyed() {
            console.log("destroyed") //prints destroyed
        }
    };
</script>
```

I added destroyed() function …

```
destroyed() {
    console.log("destroyed") //prints destroyed
}
```
in HomePage, Pending and Completed components. Only HomePage prints “destroyed”

Pending, Completed components are actually rendering v-ons-list of v-ons-card and I am also using v-for.

```
    <v-ons-list>
        <v-ons-card v-for="item in list" :key="item.id" ...
```
and in beforeMount() of Pending and Completed components I fetch list of items. My observation is, everytime I log out of application and login back two new component instances of Pending and Completed are created. It looks like behind the scene multiple Pending and Completed components are running. They are not getting destroyed. I see multiple requests going out in Chrome browser’s Network tab.

**Comment by frandiox** [comment]
@ableabhijeet Hi, thanks for reporting! How are you triggering the first destroy? I'm running `this.$destroy()` on Home page and looks like all the tabs are correctly destroyed even when using `keep-alive` for the tabs. Could you provide a small example in tutorial.onsen.io , codepen, fiddle or a GitHub repo?

**Comment by ableabhijeet** [comment]
Thanks Fran. Actually, It was a problem in my code, I have fixed it.

**Comment by frandiox** [comment]
@ableabhijeet Glad to read that. We can close this I guess :)
