### ISSUE TITLE
React | Button issue: modifier not applied on Android View

### ISSUE THREAD

**Issue by aspick** [OnsenUI/OnsenUI#2171]
__Environment__

  
```
[Core]
  onsenui 2.5.3
  
[Framework]
  react 15.4.2

[Framework binding]
 react-onsenui 1.5.0

[Platform]
  Desktop - OS X 10.11.6

[Browser]
  Desktop - Safari 10.1.1 on OS X 10.11.6
```

__Encountered problem__
On Android View, modifier applied button is not rendered as quiet style.

__How to reproduce__
You can also check Vue binding comparing below links.
https://onsen.io/v2/api/js/ons-button.html
https://onsen.io/v2/api/vue/v-ons-button.html
https://onsen.io/v2/api/react/Button.html

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<div id="app"></div>
```

- __JS__

```jsx
var MyPage = React.createClass({
  render: function() {
    return (
      <Ons.Page>
        <Ons.Button>Default</Ons.Button>
        <Ons.Button modifier="quiet">Quiet</Ons.Button>
      </Ons.Page>
    );
  }
});

ons.ready(function() {
  ReactDOM.render(<MyPage />, document.getElementById('app'));
});
```

**Comment by frandiox** [comment]
@aspick Thanks for reporting! I noticed this in Vue and made a fix yesterday. It's in a PR already and will be released next week. I'll make sure it also works in React.

**Comment by aspick** [comment]
Thank you for your replay.
I'm looking forward to get that release.
