### ISSUE TITLE
The parameters in options object of pushPage and replacePage functions  are not optional

### ISSUE THREAD

**Issue by jimmy-frank** [OnsenUI/OnsenUI#2172]
__Environment__ 

```
[Core]
    onsenui 2.0.0

[Framework]
    angular1 1.6.6

[Framework binding]
    angular-onsenui 2.1.0

[Additional libraries]
    jQuery 3.2.1

[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1
    Desktop - Linux
    Desktop - macOS Sierra
    Desktop - Windows 10

[Browser]
    Mobile - Android WebView
    Mobile - iOS UIWebView
    Desktop - Chrome 55.0.2883.75
    Desktop - Safari 10.0 (12602.1.50.0.10)
```

__Encountered problem__
There are some questions about functions pushPage and replacePage, their parameters in options object are not optional, so I needed code all parameters when called them

__How to reproduce__

**Comment by frandiox** [comment]
@jimmy-frank I'm not sure I understand what you mean, please elaborate a bit more. Also, please try to use the latest version of Onsen UI, 2.0.0 is quite old already.

**Comment by jimmy-frank** [comment]
I use typescript + angular1 + onsen2, the definition in onsenui.d.ts file：
interface PushPageOptions {
  page?: any;
  options?: {
    page: any,
    pageHTML: any,
    animation: any,
    animationOptions: any,
    callback: any,
    data: any
  }
}

interface ReplacePageOptions {
  page?: any;
  options?: {
    animation: any,
    animationOptions: any,
    callback: any,
    data: any
  }
}
I have already updated onsen ui to 2.5.3
