### ISSUE TITLE
Double curly brace don't work after updating from onsen ui 1 to onsen ui 2 about <ons-dialog>

### ISSUE THREAD

**Issue by jimmy-frank** [OnsenUI/OnsenUI#2179]
__Environment__ 

```
[Core]
    onsenui 2.5.3

[Framework]
    angular1 1.6.6

[Framework binding]
    angular-onsenui 2.1.0

[Additional libraries]
    none
    jQuery 3.2.1

[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1
    Desktop - macOS Sierra
    Desktop - Windows 10

[Browser]
    Mobile - Android WebView
    Mobile - Android Chrome 54.0.2840.85
    Mobile - iOS UIWebView
    Mobile - iOS Safari
    Desktop - Chrome 55.0.2883.75
    Desktop - Safari 10.0 (12602.1.50.0.10)
```

__Encountered problem__
Double curly brace don't work after updating from onsen ui 1 to onsen ui 2, code is below.
html:
<ons-dialog id="toastDialog" style="background: rgba(0,0,0,0.5); min-height: 40px;">
    <div style="color: #fff;line-height: 30px;text-align: center;padding: 30px;">{{message}}</div>
</ons-dialog>
js:
window.commonComponents = angular.module('commonComponents', []);

window.hons = (function(){});

window.hons.toast = (function () {
    var createToast = function (message, animation, hidePeriod, callback) {
        ons.createDialog('pages/common-components/toast.html', {animation:animation}).then(function (dialog) {
            dialog._scope.message = message;
            dialog.show();
            setTimeout(function () {
                dialog.hide();
                callback();
            }, hidePeriod);
        });
    };

    return {
        /**
         * @param {Object} options
         * @param {String} [options.message]
         * @param {String} [options.animation]
         * @param {Function} [options.callback]
         * @param {Function} [options.callback]
         */
        show: function (options) {
            var defaults = {
                animation: 'default',
                hidePeriod: 2000,
                callback: function () {}
            };

            options = angular.extend({}, defaults, options);
            if (!options.message) {
                throw new Error('toast must contain a message.');
            }
            createToast(
                    options.message,
                    options.animation,
                    options.hidePeriod,
                    options.callback
                    );
        }
    };
})();
__How to reproduce__

dialog._scope.message can achieve some value, but {{message}} don't work.

**Comment by puku0x** [comment]
How about setting `parentScope` to the dialog ?

```js
ons.createDialog('dialog.html', { parentScope: $scope })
  .then(function(dialog) {
    dialog._scope.message = 'hello !'; // should work
    dialog.show();
  });
```

https://codepen.io/puku0x/pen/yzYRxJ

**Comment by jimmy-frank** [comment]
That's great, it's work for me, thanks for your time @puku0x
