### ISSUE TITLE
Examples Not Working / Build Directory Missing

### ISSUE THREAD

**Issue by recoilnetworks** [OnsenUI/OnsenUI#2181]
After downloading the latest release (https://github.com/OnsenUI/OnsenUI-dist/releases/latest) and unzipping the file, I went to look at the examples only to notice they are broken. After reviewing the source, they are referencing files that do not exist. There is no build directory at the top of the directory structure and thus, the files needed are missing. In fact, there is no "onsenui.css" file at all in the entire directory structure. Am I missing something?

**Comment by frandiox** [comment]
@recoilnetworks Where is the `examples` folder in that repo? I think it is not provided in the releases. The examples are in the main repo and they work well when running `gulp serve`.

**Comment by recoilnetworks** [comment]
Yeah, so I must be an idiot, which wouldn't surprise me. A lot of this gulp and bower shit is new to me. So the `examples` directory is at the top of the directory structure. According to the download link `Compiled and minified JavaScript, CSS and resources. Web Components version.` which are not contained in the file that the download is linked to.

**Comment by frandiox** [comment]
@recoilnetworks Oh, I've found the link you said. Looks like it has a weird behavior, it links to a place but downloads something wrong. Please go to this link https://github.com/OnsenUI/OnsenUI-dist/releases/latest  and hit `Source code (zip)` at the end. That will download the real Onsen UI release. It does not contains examples so you can check the interactive tutorial I mentioned before instead.

**Comment by frandiox** [comment]
@recoilnetworks If you want to run the examples in the main repo, you can check the dev guide here: https://github.com/OnsenUI/OnsenUI/blob/master/.github/CONTRIBUTING.md#development-setup
Hope it helps!
