### ISSUE TITLE
OnsenUI React: Difference between `Navigator` and `RouterNavigator`?

### ISSUE THREAD

**Issue by benny-medflyt** [OnsenUI/OnsenUI#2184]
The components `Navigator` and `RouterNavigator` seem to be nearly identical! Which one should be used?

https://onsen.io/v2/api/react/Navigator.html
https://onsen.io/v2/api/react/RouterNavigator.html

**Comment by frandiox** [comment]
@benny-medflyt Hi! The example that you see in both components is the same and correspond the `Navigator`. The other one, `RouterNavigator`, does the same thing but with a different API. You can see an example [here](https://github.com/OnsenUI/OnsenUI/blob/master/bindings/react/demo/examples/RouterNavigator.js).

**Comment by untsamphan** [comment]
The above link (for example) is broken. Here is the new one.
https://github.com/OnsenUI/OnsenUI/blob/master/bindings/react/examples/components/RouterNavigator.js

**Comment by LucNaterop** [comment]
@untsamphan How can I use different animations with `RouterNavigator`? I am a bit lost here, but it is important that we have RouterNavigator as it doesn't unmount components lower in the stack and therefore keeps the state when routing around. I don't understand the example that you linked to, is there a clean implementation that is easy to use?
