### ISSUE TITLE
React | Navigator in Tab results in strange error

### ISSUE THREAD

**Issue by LucNaterop** [OnsenUI/OnsenUI#2186]
__Environment__

  
```
[Core]
  onsenui latest
  
[Framework]
  react 15.4.2

[Framework binding]
 react-onsenui latest

[Platform]
  Desktop - OS X 10.12.6 64-bit

[Browser]
  Desktop - Chrome 60.0.3112.113 on OS X 10.12.6 64-bit
```

__Encountered problem__
As soon as the navigator is added to the tab, the user is stuck in the tab. The error is
`Uncaught Error: Invalid state: page element must be a "ons-page" element.`
I've tried with more than two tabs and noticed that one can navigate all tabs that do not include the navigator. As soon as one visits the tab that contains the navigator, one is stuck in that tab. I've also tried to do it the other way around, that is, putting the Tab inside of the Navigator, but then I've had strange problems as well. The route stack flushed all the time. 

__How to reproduce__
  

  
  [__Demo link__](https://codepen.io/LucNaterop/pen/QqbBwp?&editors=101)

  

- __HTML__

```html
<div id="app"></div>
```

- __JS__

```jsx

class FirstTab extends React.Component {
	render() {
		return (
			<Ons.Page>
				<h1>First Tab</h1>
			</Ons.Page>
		);
	}
}

class Navigator extends React.Component {
	renderPage(route, navigator) {
		return <FirstTab key={0}/>
	}
	render() {
		return (
			<Ons.Navigator
				initialRoute={{ 'name': 'firstTab' }}
				renderPage={this.renderPage.bind(this)}
			/>
		);
	}
}

class SecondPage extends React.Component {
	render() {
		return (
			<Ons.Page>
				<h1>Second Tab</h1>
			</Ons.Page>
		);
	}
}

class Tabs extends React.Component {
	constructor(props){
		super(props);
		this.state = {index: 0};
	}
	renderTabs() {
		return [
			{ tab: <Ons.Tab label='First Tab' key={0} />, content: <Navigator key={0}/>},
			{ tab: <Ons.Tab label='Second Tab' key={1} />,content: <SecondPage key={1} />}
		];
	}
	render() {
		return (
			<Ons.Tabbar
				position='auto'
				index={this.state.index}
				onPreChange={(event) => {
					if (event.index != this.state.index) {
						this.setState({index: event.index});
					}
				}}
				renderTabs={this.renderTabs.bind(this)}
			/>
		);
	}
}

ons.ready(function() {
  ReactDOM.render(<Tabs />, document.getElementById('app'));
});
```

**Comment by frandiox** [comment]
@LucNaterop I answered you on Gitter and SO. You just need to wrap the navigator inside a page and it will work.

By the way, when you report an issue from tutorial.onsen.io you don't need to manually modify the "Demo link", it will work once you submit the issue :)

**Comment by LucNaterop** [comment]
@frandiox Thank you very much, that solved it.
