### ISSUE TITLE
There is a problem when I add 'position' attribution with <ons-tabbar> on my iphone.

### ISSUE THREAD

**Issue by jimmy-frank** [OnsenUI/OnsenUI#2189]
__Environment__ 

```
[Core]
    onsenui 2.5.3 

[Framework]
    angular1 1.6.6

[Framework binding]
    angular-onsenui 2.5.3

[Additional libraries]
    none
    jQuery 3.2.1

[Platform]
    Mobile - iOS 10.1.1

[Browser]
    Mobile - iOS UIWebView
```

__Encountered problem__
The error information is below:
Unhandled Promise Rejection: TypeError: e.hasAttribute is not a function. (In 'e.hasAttribute('status-bar-fill')', 'e.hasAttribute' is undefined)--------onsenui.js:8785

__How to reproduce__
I have a hybrid app, There is a problem when I add 'position' attribution with <ons-tabbar> on my iphone. I jump to the page via 'pushPage()' function.

**Comment by frandiox** [comment]
@jimmy-frank Thanks for reporting! For now, you can use `ons-template` instead of `template` in that specific page (move it to `index.html` and use `ons-template` if you have it now in a separate file). This will be fixed in the next minor version :+1:

**Comment by jimmy-frank** [comment]
ok! thanks@frandiox
