### ISSUE TITLE
SplitterContent does not set 'left' style attribute correctly

### ISSUE THREAD

**Issue by sbaechler** [OnsenUI/OnsenUI#2205]
__Environment__ 

```
[Core]
    onsenui 2.6.1

[Framework]
    react 15.6.2

[Framework binding]
    react-onsenui 1.6.1

[Additional libraries]
    none

[Platform]
    Desktop - macOS Sierra

[Browser]
    Desktop - Chrome current
```

__Encountered problem__
I just updated OnsenUI from 2.1 to 2.6 and now the Splitter component does not behave correctly anymore. The `SplitterSide` has a width of 320. No matter what I set for 'collapse' or 'mode' the `ons-splitter-content` element always has a style of 'left: 0px'. 

When the mode is 'split' I expect the attribute to be 'left: 320px'. 

__How to reproduce__
Create a Splitter component and make sure the mode is 'split' so the sidebar and content are next to each other.

![bildschirmfoto 2017-10-06 um 10 59 00](https://user-images.githubusercontent.com/288516/31270623-68a81cdc-aa85-11e7-8829-b6b88ff7b7b7.png)

**Comment by frandiox** [comment]
@sbaechler Hi! Please try to reproduce the issue as specified in the issue template. You can start from here: http://tutorial.onsen.io/?framework=react&category=reference&module=splitter

I just tried quickly removing `collapse` and it looks like working well :/

**Comment by sbaechler** [comment]
Hi

I created a pen and it is working there. https://codepen.io/sbaechler/pen/QqQbBr?&editors=101

I noticed that in my project the value is not set only on initial rendering. Once you close and reopen the menu it is correct. This error only happened since the update from 2.1 to 2.6.1.

It looks like the width is calculated before the element is rendered.
