### ISSUE TITLE
IPV6 disapproved by Apple

### ISSUE THREAD

**Issue by wanderarce** [OnsenUI/OnsenUI#2207]
Please can help with Apple by Apple below:

"**We still discovered one or more bugs in your app when reviewed on iPhone and iPad running iOS 11.0.2 on Wi-Fi connected to an IPv6 network.**

**Specifically, no action occurred when we tapped on the Enter button.** "

Note: We do not work with IPV6 only IPV4.

**Comment by frandiox** [comment]
No idea about this, perhaps you can try asking on the forum or, maybe better, on Stackoverflow.
GitHub issues are specifically for bugs on Onsen UI, and this doesn't look like it :confused:
