### ISSUE TITLE
vue-onsenui v-ons-segment not showing correctly

### ISSUE THREAD

**Issue by pashute** [OnsenUI/OnsenUI#2210]
Monaca cli minimal vue template doesn't show `v-ons-segment` correctly. (And I couldn't find it in the vue-onsenui code on github or in my project at all). This is opposed to the documentation. 

See my detailed question on [Stack-Overflow](https://stackoverflow.com/questions/46657276/onsenui-with-vue-vue-onsenui-v-ons-segment-not-working-why#46657276)

**Comment by frandiox** [comment]
@pashute Just update `onsenui` and `vue-onsenui` dependencies :+1:
