### ISSUE TITLE
toolbar._getToolbarLeftItemsElement is not a function

### ISSUE THREAD

**Issue by baixiaoyu2997** [OnsenUI/OnsenUI#2211]
vue:2.4.4
vue-onsenui:2.2.1
onsenui:2.6.1

when i use 
`this.$store.commit("navigator/push", page)`
i have `<v-ons-toolbar> ` in my page,but still show me the "toolbar._getToolbarLeftItemsElement is not a function", 
what i miss? (sorry for my english)

**Comment by frandiox** [comment]
@baixiaoyu2997 As suggested in the issue template, can you please make a small example reproducing this problem?

**Comment by baixiaoyu2997** [comment]
children item indexHeader trigger  'push'。
```
<template>
  <v-ons-page>
    <index-header v-on:push="push"></index-header>
  </v-ons-page>
</template>

<script>
import indexHeader from './indexHeader';
export default {
  name: 'HitMoviePage',
  data() {
    return {
    }
  },
  methods: {
    push(page) {
      this.$store.commit("navigator/push", page)
    },
  },

  components: {
    indexHeader
  }
}
</script>
```
store.js
```
export default {
  modules: {
    navigator: {
      strict: true,
      namespaced: true,
      state: {
        stack: [],
        options: {}
      },
      mutations: {
        push(state, page) {
          state.stack.push(page)
        },
        pop(state) {
          if (state.stack.length > 1) {
            state.stack.pop()
          }
        },
        replace(state, page) {
          state.stack.pop()
          state.stack.push(page)
        },
        reset(state, page) {
          state.stack = [page || state.stack[0]]
        }
      }
    }
  }
}
```

In vue-onsenui-kitchensink can also reproduce this bug,just remove the `<custom-toolbar v-bind="toolbarInfo"></custom-toolbar>` from the PullHook.vue,But I'm not sure it's related to my question。

**Comment by frandiox** [comment]
@baixiaoyu2997 I just tried removing `<custom-toolbar>` in the kitchensink app and couldn't see any error.
Also, you said 
>i have `<v-ons-toolbar>` in my page,but still show me the "toolbar._getToolbarLeftItemsElement is not a function",

But I can't see any toolbar in your code. Is it inside `<index-header>`? It must be the root component if that's the case (`<template><v-ons-toolbar>...</v-ons-toolbar></template>`).

**Comment by baixiaoyu2997** [comment]
indexHeader.vue
```
<template>
  <div class="header">
    <div class="selectItem" @click="push(selectCityPage)">
      <span class="selectCity">{{city}}</span>
      <v-ons-icon icon="ion-ios-arrow-down,material:md-chevron-down" class="icon--down"></v-ons-icon>
    </div>
    <input type="search" placeholder="电影 / 电视剧 / 影人" readonly class="search-input" @click="push(searchPage)" />
  </div>
</template>

<script>
import searchPage from "./searchPage.vue"
import selectCityPage from "./selectCityPage.vue"

export default {
  name: 'indexHeader',
  props: ["city"],
  data() {
    return {
      searchPage,
      selectCityPage
    }
  },
  methods: {
    push(page) {
      this.$emit('push', page)
    }
  }
}
</script>
<style lang="scss" scoped>
.header {
  display: flex;
  align-items: center;
  padding: 5px 17px 0;
  text-align: center;
  background-color: #fff !important;
  a {
    flex: 1;
  }
  .selectItem {
    display: flex;
    flex-shrink: 0;
    align-items: center;
  }
  .icon--down {
    color: #9b9b9b;
    margin: 0 5px;
  }
  .selectCity {
    color: #3d3d3d;
    font-size: 15px;
  }
}

.search-input {
  background-position: 24% center;
  width: 100%;
}

input::-webkit-input-placeholder {
  text-align: center;
  font-size: 16px;
}
</style>
```

**Comment by baixiaoyu2997** [comment]
ok ,Could you please come to my github? i just push many bugs, hahaha,  u can click top search-input, can find bug message. thank you  very much~~~~~~

[https://baixiaoyu2997.github.io/vue-onsen/](url)

**Comment by frandiox** [comment]
@baixiaoyu2997 I'm a bit confused, I can't see that error but I see others related to `vuex` and `vue-router`. They are not included in the app source so I cannot debug it further :/

**Comment by moicirk** [comment]
Faced with the same issue.
Found out that error shows only for 'slide' animation and iOS

`Uncaught (in promise) TypeError: toolbar._getToolbarLeftItemsElement is not a function
at IOSSlideNavigatorTransitionAnimator._decompose (Node.js:181)
    at Node.js:5
    at ons-toolbar-button.js:90
    at Array.forEach (<anonymous>)
    at consumeQueue (ons-toolbar-button.js:90)
    at contentReady (ons-toolbar-button.js:109)
    at IOSSlideNavigatorTransitionAnimator.push (Node.js:5)
`

**Comment by baixiaoyu2997** [comment]
i test vue-onsenui-kitchensink v0.0.1,like i say,just remove `<custom-toolbar v-bind="toolbarInfo"></custom-toolbar>`
![](http://wx3.sinaimg.cn/mw690/59ab4c9fly1fkhkc4bb1rj20zf0gkdia.jpg)

is must have a `<v-ons-toolbar>` ?
when i code like this,it's fine,but i don't need `<v-ons-toolbar>`
![](http://wx1.sinaimg.cn/mw690/59ab4c9fly1fkhkiglgw4j20rg0e8dhm.jpg)

**Comment by frandiox** [comment]
No, a `v-ons-toolbar` shouldn't be necessary. I've checked once again and I'm still unable to get that error. I know it only happens with iOS slide animation since that's the only place where these functions are used but still, I'm not able to see the error. That `toolbar` variable becomes a dummy toolbar element when your page doesn't contain an actual toolbar, so all the functions should exist...

**Comment by frandiox** [comment]
@baixiaoyu2997 Can you try with the [latest development version](https://circleci.com/api/v1/project/OnsenUI/OnsenUI/latest/artifacts/0/$CIRCLE_ARTIFACTS/onsenui.zip?branch=master&filter=successful) (`onsenui.js`)? I made a small change that might fix the issue.

**Comment by baixiaoyu2997** [comment]
@frandiox  @moicirk  hi,buddy,  i think i found a solution to the bug.can u believe it? 
The problem appears on the chrome plugin:LastPass
troubled me for a long time，just disable lastpass,it's work now。LOL

**Comment by frandiox** [comment]
:frowning: 
I guess using incognito mode without plugins is actually good for developing :sweat_smile:

**Comment by baixiaoyu2997** [comment]
@frandiox thanks for you time and advice 👍

**Comment by moicirk** [comment]
@baixiaoyu2997 Owww!! Thanks a lot buddy

**Comment by andrey-tsaplin** [comment]
Hi! I've also faced with this problem using LastPass. 
In the deep it is the conflict between CustomElements library (https://github.com/webcomponents/custom-elements) and LastPass extension. 
LastPass dirty overrides document.createElement by saving current reference (at the moment the page just start loading) to native method as base method inside a closure, but a moment later CustomElements library replaces Document.prototype.createElement. But it is never called, because document.createElement references to LastPass overrided method that call saved initial method inside. 

So this bug should be fixed anyway by LastPass team, because any website that uses WebComponents/CustomElements is affected.

**Comment by frandiox** [comment]
@andrey-tsaplin Thanks a lot for the explanation! That makes sense indeed. It's weird that an extension is overriding `document.createElement`, that can obviously create unexpected behavior hard to debug...

**Comment by Orlandster1998** [comment]
@baixiaoyu2997 Thanks a lot man! saved me from a lot of troubles :)
