### ISSUE TITLE
iOS scrolling under modal views / masks

### ISSUE THREAD

**Issue by Ralpharoo** [OnsenUI/OnsenUI#2220]
__Environment__

```
[Core]
    onsenui 2.6.1

[Framework]
    angular1 1.5.9

[Framework binding]
    angular-onsenui 2.6.1 (2017-09-28)

[Additional libraries]
    jQuery 3.1.1

[Platform]
    Mobile - iOS 10.3.1
    Mobile - iOS 11.0.2
    Mobile - iOS ~9

[Browser]
    Mobile - iOS UIWebView
    Mobile - iOS WKWebView
    Mobile - iOS Safari
```

__Encountered problem__
Ability to scroll pages underneath any modal dialog, popover, etc.

__How to reproduce__
On iOS the touch event seems to be caught by scrollable page__contents underneath modal masks. When you touch and move over both the mask and dialogs themselves, the page below can still be scrolled.

You can also achieve this in here but I can also provide another example if needed;
https://frandiox.github.io/OnsenUI-YouTube/

I suspected that this may be related to an iOS bug here;
https://github.com/scottjehl/Device-Bugs/issues/14

I managed to patch fix this before migrating from OnsenUI v1.3 with a hack. I tested the above mentioned addition of '-webkit-overflow-scrolling: auto;' when a dialog is in view, however, this caused flickering on the pages. The only way I could stop this behavior without a flicker was to create a new hammer touchmove watcher on the window, and check the target's fastClickScrollParent. fastClickScrollParent would always tell me which element was about to scroll and I could prevent the default action if it was not my modal / dialog / popover.

This fastClickScrollParent does not seem to get updated in the same way in the latest 2.6.1 version and I am unable to check which element is going to receive the touches.

Any ideas are welcome! 

Thanks.

**Comment by frandiox** [comment]
@Ralpharoo Thanks for reporting it with so much information, it was easy to debug thanks to that :) Looks like 898536e is enough.
This indeed looks like a bug on iOS, I saw something similar in #1949

**Comment by Ralpharoo** [comment]
Thanks for the speedy patch on this @frandiox  

I've just started testing this and it's almost there but still not perfect. iOS still transfers the touches when they begin on the modal and the modal itself is not scrollable.

On the same Youtube example you will see that you can tap and drag on the model video and it scrolls the background. Before I was able to check which node type was the 'fastClickScrollParent' and determine if I wanted this scroll or not. Not sure how this might apply in your current touchmove event on the mask though.

I currently have a swipable element in a dialog and if the user swipes anything but perfectly horizontally, it scrolls the background.  This makes this issue a lot more obvious for my users.

Let me know if you need anymore info.

Cheers,

**Comment by frandiox** [comment]
@Ralpharoo Same as in [the splitter side](https://github.com/OnsenUI/OnsenUI/issues/1949#issuecomment-329060000), then. The only solution I can think right now is making the modal scrollable somehow (maybe by 1 pixel, or have another transparent scrollable element behind), so it takes the scroll and does not pass it magically to another random element. However, I'm quite busy right now with other stuff so this might take some time.

**Comment by Ralpharoo** [comment]
Thanks @frandiox for the pointers. 

As you suggested, I've tried making larger scrollable views however when the view is scrolled to it's top/bottom extremity, the scroll transfers again to the page in the background. I tried to quickly adjust the view back to it's middle point but this leaves a pretty clunky finish.

I've also tried to make the background mask bigger and scrollable, however, I cannot find any relationship between which element will scroll under the modal. It seems to completely ignore the z-index / hierarchy of the views and almost always scrolls the page in the background skipping the mask entirely anyway. 

As mentioned before only thing that has worked is to adding "-webkit-overflow-scrolling: auto;" to all  .page__content's whenever a modal is visible. This works perfectly, however, causes flickering on iOS UIWebView and WKWebView. This flickering is almost worse the initial problem.

So it's no good news I am afraid. Let me know if you have any other thoughts to try out.

Cheers,

**Comment by frandiox** [comment]
@Ralpharoo I've checked this for a while and I think there is no definite fix. After the last patch, it should be fine in iOS Safari and WKWebView. In UIWebView, however, it only prevents scrolling on dialog masks. I had to remove the fix for `ons-modal` because it would prevent scrolling modals that should have a scrollable content as well.

There is a new `ons.forceUIWebViewScrollFix()` that applies the same patches for WKWebView to UIWebView but you will need to check if this works for your app. It could stop momentum scroll if a dialog is displayed before the scroll finished.
Also, now Onsen UI adds `.ons-ios-scroll` class to `document.body` whenever a dialog or splitter are open so you can apply custom CSS fixes if necessary. :+1:

**Comment by Ralpharoo** [comment]
Awesome - Thanks for that @frandiox. We are using WKWebView across our applications so I'll update and give everything a test. Thanks again for your efforts, much appreciated 👍
