### ISSUE TITLE
Core | Tabbar issue: Uncaught TypeError: Cannot read property 'setActive' of undefined

### ISSUE THREAD

**Issue by rancor1223** [OnsenUI/OnsenUI#2223]
__Environment__

  
```
[Core]
  onsenui latest
  
[Platform]
  Desktop - Windows 10 64-bit

[Browser]
  Desktop - Opera 48.0.2685.39 32-bit (like Chrome 61.0.3163.100) on Windows 10 64-bit
```

__Encountered problem__
  `Uncaught TypeError: Cannot read property 'setActive' of undefined` when tabbar is empty. 
I ran into this issue, because I generate my the tabs dynamically after the pagehas loaded. This error didn't occur on 2.4.2. 

__How to reproduce__
  

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<ons-page>
  <ons-toolbar>
    <div class="center">Test Page</div>
  </ons-toolbar>

  <ons-tabbar>
    
  </ons-tabbar>
</ons-page>

```

- __JS__

```javascript

```

**Comment by frandiox** [comment]
@rancor1223 This is not really tested in `ons-tabbar` but I just fixed the issue I saw when doing this anyway. However, beware that `ons-tabbar` DOM structure changed in 2.6.0. If you are going to attach new tabs asynchronously, make sure you grab the real `.tabbar` element (`var tabbar = document.querySelector('ons-tabbar .tabbar')` and append the tabs before the last element (which is the material design border): `tabbar.insertBefore(tab, tabbar.lastElementChild);`.
