### ISSUE TITLE
ons-carousel and ons-tabbar 'postchange' event was fired at same time

### ISSUE THREAD

**Issue by otak1222** [OnsenUI/OnsenUI#2224]
__Environment__ 

```
[Core]
    onsenui 2.6.1

[Framework]
    angular1 1.6.6

[Framework binding]
    angular-onsenui 2.6.1
```

__Encountered problem__

**ons-carousel** and **ons-tabbar** 'postchange' event was fired at same time.

__How to reproduce__

Swipeable carousel.

[DEMO](https://codepen.io/oTak/pen/ZXqqgW)

**Comment by frandiox** [comment]
@otak1222 Hi! This is not a bug. Carousel's event is bubbling so the Tabbar's handler is also called. Maybe you can try something like this:

```
function(event) {
  if (event.target === event.currentTarget) {
    // run code
  }
}
```

That ensures the event target is the same element that has the listener :+1:
