### ISSUE TITLE
Go easy on the user-select property

### ISSUE THREAD

**Issue by sbaechler** [OnsenUI/OnsenUI#2227]
It is basically impossible to override the `user-select` property.

It is set in the onsenui.css: 
```
* {
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0) !important;
}
```

and again in global.css: 
```
html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center, dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td,
article, aside, canvas, details, embed,
figure, figcaption, footer, header, hgroup,
menu, nav, output, ruby, section, summary,
time, mark, audio, video {
  user-select: none;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}
```
Is this really necessary? If an app need selectable text then currently the only reasonable way to achieve this is to copy those two files and remove those rules. 

In Sass I would suggest to use an if function. Is there something similar in PostCSS?
The `tap-highlight-color` could be a css variable.

**Comment by frandiox** [comment]
@anatoo What do you think?

**Comment by anatoo** [comment]
@frandiox @sbaechler Ok, I will make easier to override these css properties.
