### ISSUE TITLE
Latest Development Build

### ISSUE THREAD

**Issue by Ralpharoo** [OnsenUI/OnsenUI#2229]
I an unable to download the latest development build of Onsen via link on Github homepage; 
[https://circleci.com/api/v1/project/OnsenUI/OnsenUI/latest/artifacts/0/$CIRCLE_ARTIFACTS/onsenui.zip?branch=master&filter=successful](https://circleci.com/api/v1/project/OnsenUI/OnsenUI/latest/artifacts/0/$CIRCLE_ARTIFACTS/onsenui.zip?branch=master&filter=successful)

Returns a 500 error: 'Something very bad happened! We're sorry!'

Is this still supported?

Thanks.

**Comment by frandiox** [comment]
@Ralpharoo Oh, we changed to CircleCI v2 recently, I guess the link must be changed...

**Comment by frandiox** [comment]
479a5587840d3e748c7b84abb9ef39c5636260cf
