### ISSUE TITLE
Core | Lazy-repeat issue: Doesn't render if filter is removed

### ISSUE THREAD

**Issue by KrewKracer** [OnsenUI/OnsenUI#2232]
__Environment__

  
```
[Core]
  onsenui latest
  
[Platform]
  Desktop - Ubuntu 64-bit - also Android 6.0.1

[Browser]
  Desktop - Firefox 54.0 on Ubuntu 64-bit
```

__Encountered problem__
  
I have a lazy-repeat list. The data can be filtered with a text input field.
If the data has been filtered so that no item is rendered, the lazy-repeat list won't render items anymore after the filter has been removed.

__How to reproduce__
Take the demo below...

- Enter "a" in the search bar
- Item "A" is rendered
- Clear the search bar
- All items are rendered
- Enter "x" in the search bar
- No item is rendered
- Clear the search bar
- ...no item is rendered. Expected: All items are rendered

Seem like the issue is in `LazyRepeatProvider`:

```javascript
  _lastItemRendered() {
    return Math.max(...Object.keys(this._renderedItems))
  }

  _firstItemRendered() {
    return Math.min(...Object.keys(this._renderedItems))
}
```

Those methods return `-Infinity` and `Infinity` when you call `refresh()` and `_renderedItems`is empty.

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<ons-page>
  <ons-toolbar>
    <div class="center">
      <ons-input id="search-input" placeholder="Search..." ></ons-input>
    </div>
  </ons-toolbar>

  <ons-list>
    <ons-lazy-repeat id="infinite-list"></ons-lazy-repeat>
  </ons-list>
</ons-page>
```

- __JS__

```javascript
ons.ready(function() {
  var allData = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"];
  var filteredData = allData;
  var infiniteList = document.getElementById('infinite-list');

  var searchInput = document.getElementById('search-input');
  searchInput.oninput = function () {
    let currentValue = this.value;

    if(!currentValue) {
        filteredData = allData;
    } else {
        filteredData = allData.filter(function (entry) {
            return (entry.toLowerCase().includes(currentValue.toLowerCase()));
        })
    }
    infiniteList.refresh();
  }

  infiniteList.delegate = {
    createItemContent: function(i) {
      return ons.createElement('<ons-list-item>' + filteredData[i] + '</ons-list-item>');
    },
    countItems: function() {
      return filteredData.length;
    }
  };

  infiniteList.refresh();
});
```

**Comment by frandiox** [comment]
@KrewKracer Lazy repeat wasn't really made for filtering lists and allowing empty lists but I guess we can easily fix that. Thanks for the report, I'll check it soon.

**Comment by KrewKracer** [comment]
Thanks. I really think it's common scenario to filter such a list - which might end up in an empty list.

As a quick workaround I did override those methods with

```javascript
        lazyList._lazyRepeatProvider._firstItemRendered = function () {
            if (!this._renderedItems.length) {
                return;
            }
            return Math.min(...Object.keys(this._renderedItems))
        };


        lazyList._lazyRepeatProvider._lastItemRendered = function () {
            if (!this._renderedItems.length) {
                return;
            }
            return Math.max(...Object.keys(this._renderedItems))
        }
```

This doesn't seem to be the optimal solution because `lastItemIndex` in `refresh` becomes `NaN`... but it works for now.
