### ISSUE TITLE
Is this onsenui2 

### ISSUE THREAD

**Issue by pashute** [OnsenUI/OnsenUI#2234]
Is this onsenui2?

If yes mark so in the description and readme.

If not tell us where the onsenui2 repository is.

**Comment by frandiox** [comment]
@pashute This is the only repository of Onsen UI so I think there is no need to change anything in the readme. Check changelog, released versions or Git tags to see any specific Onsen UI version.

**Comment by pashute** [comment]
OK the answer is yes. according to the [https://github.com/OnsenUI/OnsenUI-dist](change log). 

It's a major release different from onsenui1 to 2, so please put this information with a link to the distribution log at the top of the readme.
