### ISSUE TITLE
 No content is displayed.(onsenui 2.7.0 & angular1 @ Firefox)

### ISSUE THREAD

**Issue by uk-taniyama** [OnsenUI/OnsenUI#2238]
__Environment__ 

```
[Core]
    onsenui 2.7.0

[Framework]
    angular1 1.5.9

[Framework binding]
    angular-onsenui 2.7.0

[Additional libraries]
    none

[Platform]
    Desktop - Windows 10

[Browser]
    Desktop - Firefox
```

__Encountered problem__

ver 2.7.0 (no content)
https://codepen.io/uk-taniyama/pen/VrLzGR

ver 2.5.3 (show content)
https://codepen.io/uk-taniyama/pen/zPGdjR

**Comment by frandiox** [comment]
@uk-taniyama Looks like it works well when the libs are included after all the content (Codepen puts them at the end). If you place them in `<head>` or at the beginning of `<body>` it works also in Firefox.
