### ISSUE TITLE
Request - using `@webcomponents/custom-elements`

### ISSUE THREAD

**Issue by btpka3** [OnsenUI/OnsenUI#2242]
__Environment__  

```
[Core]
    onsenui 2.7.0

[Framework]
    angular 4.2.4

[Framework binding]
    ngx-onsenui 4.1.0

[Additional libraries]
    none

[Platform]
    Desktop - macOS Sierra

[Browser]
    Desktop - Chrome 61.0.3163.100 (Official Build) (64-bit)
```

__Encountered problem__

Can not using OnsenUI with some other custom-elements base UI frameworks in angular lazy loading routing module .

__How to reproduce__

New to study angular4 with angular-cli, trying to using OnsenUI and [clarity-ui](https://vmware.github.io/clarity/get-started) `@angular/router` in angular lazy loading sub router module  :

```
// .angular-cli.json
{
  "apps" : [{
     "scripts" : [
          // Following clarity setup instruction
          "../node_modules/@webcomponents/custom-elements/src/custom-elements.min.js",     
     ]
  }]
}

// src/app/app-routing.module.ts
const routes: Routes = [
  // ...
  // a simple `<clr-icon shape="info-circle" size="36"></clr-icon>`
  {path: 'clarity', loadChildren: './clarity/clarity.module#ClModule'},   // lazy loading
  {path: 'ons', loadChildren: './ons/ons.module#OnsModule'},            // lazy loading
];
// ...
```
1. first visit "/clarity",  clarity icon display ok.
1. then visist "/ons",  Onsen UI components display OK
1. visit "/clarity" again, throw errors:

    ```
    scripts.bundle.js:1 Uncaught Error: The custom element being constructed was not registered with `customElements`.
        at new HTMLElement (onsenui.js:35743)
        at ClarityIconElement.parentConstructor (scripts.bundle.js:296)
        at new ClarityIconElement (scripts.bundle.js:301)
        at HTMLDocument.createElement (onsenui.js:35362)
        at EmulatedEncapsulationDomRenderer2.webpackJsonp.../../../platform-browser/@angular/platform-browser.es5.js.DefaultDomRenderer2.createElement (platform-browser.es5.js:2740)
        at EmulatedEncapsulationDomRenderer2.webpackJsonp.../../../platform-browser/@angular/platform-browser.es5.js.EmulatedEncapsulationDomRenderer2.createElement (platform-browser.es5.js:2956)
        at BaseAnimationRenderer.webpackJsonp.../../../platform-browser/@angular/platform-browser/animations.es5.js.BaseAnimationRenderer.createElement (animations.es5.js:360)
        at DebugRenderer2.webpackJsonp.../../../core/@angular/core.es5.js.DebugRenderer2.createElement (core.es5.js:13563)
        at createElement (core.es5.js:9177)
        at createViewNodes (core.es5.js:12153)
    ```

The reason is OnsenUI embeded a forked `@webcomponents/custom-elements` ( `@onsenui/custom-elements` ) , following clarity setup instruction, I installed `@webcomponents/custom-elements` again and loaded in global. When visit "/ons", `custom-elements` is re-newed. 

What's difference between  `@onsenui/custom-elements` and `@webcomponents/custom-elements` ?
Can Onsen UI be updated to use the last one instead?

If can't. How can  import `@onsenui/custom-elements` and `onsenui` seperately ? `node_modules/onsenui/core-src/setup.js` did some extra logic more than importing. 

-----------
PS: In order to using Onsen UI in angular 4 lazy loaded routing modules, I had to using modified custom [ngx-onsenui.ts](https://github.com/OnsenUI/OnsenUI/blob/2.7.0/bindings/angular2/src/ngx-onsenui.ts) (disabling re-export BrowserModule).

**Comment by asial-matagawa** [comment]
@btpka3 
Thank you for the suggestion.

>I not know what's difference between `@onsenui/custom-elements` and `@webcomponents/custom-elements`, Could Onsen UI using the last one instead?

`@onsenui/custom-elements` has a patch for `@webcomponents/custom-elements`.
Onsen UI depends on "custom element reactions stack" which is defined in the spec of Custom elements v1, but `@webcomponents/custom-elements` has not yet implemented it.
For more details, please refer to this PR: https://github.com/webcomponents/custom-elements/pull/91

Thank you for understanding.
