### ISSUE TITLE
ons-switch: moveend event

### ISSUE THREAD

**Issue by treecon** [OnsenUI/OnsenUI#2243]
In addition to the 'change' event, is it possible to catch the 'moveend' (or 'dragend') event? From what I can tell, the 'change' event is triggered when the switch starts moving. Could we trigger the event when the switch settles?

**Comment by frandiox** [comment]
@treecon The appearance of the switch depends on its actual value, so it is not possible to modify its appearance before the value is updated -- unless we add a bunch of JavaScript to do something that CSS does in 1 line (`input:checked` CSS selector).

Also, I think there is no change event at all while you are dragging, only when releasing on the opposite side. If we delay the event then it would not be synchronous with the actual value and things like double clicking on the switch would become weird. Is there any specific scenario where you need this?
