### ISSUE TITLE
v-if problem

### ISSUE THREAD

**Issue by baixiaoyu2997** [OnsenUI/OnsenUI#2246]
```
[Core]
    onsenui 2.7.0

[Framework]
    vue 2.5.0

[Framework binding]
    vue-onsenui 2.3.0

[Platform]
    Desktop - Windows 10

[Browser]
    Desktop - Chrome 62.0.3202.62
```

__Encountered problem__
when i put v-if in v-ons-page ,like this:
```vue
<template>
  <v-ons-page :infinite-scroll="loadMore" v-if="items.length>0">
      <v-ons-list>
          <v-ons-list-item v-for="item in items"></v-ons-list-item>
      </v-ons-list>
  </v-ons-page>
  <loading v-else></loading>
</template>            
```
loading.vue:
```vue
<template>
    <div>
        <img src="../assets/loading_green.c0f9be0.gif" />
    </div>
</template>
```
Show error in chrome `el._show is not a function`，
ok,i think maybe must have a `v-ons-page`,so,i change code like this:
```vue
<template>
  <v-ons-page :infinite-scroll="loadMore" v-if="items.length>0">
      <v-ons-list>
          <v-ons-list-item v-for="item in items"></v-ons-list-item>
      </v-ons-list>
  </v-ons-page>
  <v-ons-page v-else>
      <loading></loading>
  </v-ons-page>
</template>
```
this time there is no error,but,the one with the list
page no rendering,see this img:
![default](https://user-images.githubusercontent.com/9149999/32593389-ab15561e-c562-11e7-96fd-fbce3a1503c3.png)

I know my description is not detailed enough，so,  You can take a look at my github:
https://github.com/baixiaoyu2997/vue-onsen/blob/master/src/pages/HitMovieList.vue
and  online page:
https://baixiaoyu2997.github.io/vue-onsen/

**Comment by frandiox** [comment]
@baixiaoyu2997 Hi! I think it's easier if you just toggle the content with `v-show`. [Have a look at this first](https://onsen.io/v2/guide/vue/#vonspage-compilation).
Then, you can probably do:

```html
<v-ons-page>
  <div class="content" v-show="items.length > 0">
    <!-- Content here -->
  </div>

  <div v-show="items.length === 0" style="position: absolute; top: 100px">
    Placeholder
  </div>
</v-ons-page>
```

**Comment by baixiaoyu2997** [comment]
@frandiox  hi,u save me again ：)   thank you very much,I think I will always add `<div class="content">`  in my `v-ons-page` to avoid any possible issue
