### ISSUE TITLE
How to enable BrowserHistory push

### ISSUE THREAD

**Issue by anuragnagarkota** [OnsenUI/OnsenUI#2248]
How can we push the urls in browser history? Currently the navigations are quite simple. We cannot give a direct link of any page. Please guide.

__Environment__ 

```
[Core]
    onsenui 2.1.0

[Framework]
    none
    angular1 1.5.9
    angular2 2.2.4
    react 15.4.1
    vue 2.1.10

[Framework binding]
    none
    angular-onsenui 2.1.0
    angular2-onsenui 1.0.0-rc.5
    react-onsenui 1.1.0
    vue-onsenui 2.0.0-alpha.0

[Additional libraries]
    none
    jQuery 3.1.1

[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1
    Desktop - Linux
    Desktop - macOS Sierra
    Desktop - Windows 10

[Browser]
    Mobile - Android WebView
    Mobile - Android Chrome 54.0.2840.85
    Mobile - iOS UIWebView
    Mobile - iOS Safari
    Desktop - Chrome 55.0.2883.75
    Desktop - Safari 10.0 (12602.1.50.0.10)
```

__Encountered problem__

__How to reproduce__

**Comment by frandiox** [comment]
@anuragnagarkota `ons-navigator` is completely independent of URLs, therefore there is nothing that connects it with browser history. You can read the URL at the beginning of the app and set the current stack with [`resetToPage`](https://onsen.io/v2/api/js/ons-navigator.html#method-resetToPage) and [`insertPage`](https://onsen.io/v2/api/js/ons-navigator.html#method-insertPage) methods. Unfortunately, there is no declarative way to do this.
