### ISSUE TITLE
Use passive event listeners for touch events

### ISSUE THREAD

**Issue by sbaechler** [OnsenUI/OnsenUI#2249]
__Environment__ 

```
[Core]
    onsenui 2.6.1

[Framework]
    react 15.6.2

[Framework binding]
    react-onsenui 1.6.1

[Browser]
    Desktop - Chrome 62
```

__Encountered problem__
Chrome prints out a debug warning that the ListItem component uses a scroll blocking event:

> onsenui.js:3223 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

(You have to select 'Verbose' in the console to see them).

From what I can see in the code the event handlers never cancel the event so Onsen can easily use passive listeners. Maybe with a check if passive listeners are supported on the current browser.

I could submit a pull request, although it would be for 1.6 since I currently cannot upgrade to 1.7 on my project.

__How to reproduce__
Create a list with ListItems in it.

**Comment by jmigual** [comment]
+1

**Comment by frandiox** [comment]
Added in https://github.com/OnsenUI/OnsenUI/pull/2315 :+1:

**Comment by jmigual** [comment]
Thank you!
