### ISSUE TITLE
ngx-onsenui: ons-select shows error (with Onsen UI 2.8.0)

### ISSUE THREAD

**Issue by puku0x** [OnsenUI/OnsenUI#2251]
__Environment__ 

```
[Core]
    onsenui 2.8.0

[Framework]
    angular 5.0.1

[Framework binding]
    ngx-onsenui 4.1.0

[Additional libraries]
    none

[Platform]
    Desktop - macOS Sierra

[Browser]
    Desktop - Chrome  62.0.3202.89
```

__Encountered problem__

Following error message was showed when I used `ons-select` after I updated Onsen UI to v2.8.0.

<img width="605" alt="2017-11-15 10 40 12" src="https://user-images.githubusercontent.com/2607019/32814230-6f2b96ac-c9f1-11e7-86b4-b2ca60e8c83e.png">

I think this problem is already known by Onsen UI team and will be solved in next release of `ngx-onsenui`, but please keep in mind.

__How to reproduce__
Add `ons-select` into a page. 
https://ja.onsen.io/v2/api/angular2/ons-select.html

**Comment by asial-matagawa** [comment]
@puku0x 
Thank you for reporting!
I will fix this issue with some other issues which prevent us from releasing a new version of `ngx-onsenui`.

----
@frandiox 
This issue is not a problem of the core and can be fixed by adding the following statement in `ons-select.ts`.

```js
import _contentReady from 'onsenui/esm/ons/content-ready';
```

**Comment by puku0x** [comment]
@asial-matagawa
Thank you for your

**Comment by puku0x** [comment]
@asial-matagawa
Thank you for your reply.
I’m looking forward to the next release.
