### ISSUE TITLE
iOS Native Text Selection

### ISSUE THREAD

**Issue by Ralpharoo** [OnsenUI/OnsenUI#2254]
__Encountered problem__
I've struggled for a long time with unresponsive and non-native text selection and editing within OnsenUI. Text areas and inputs do not react as would normally within websites or apps and do not easily allow you to tap to select, tap to drop cursor, easily move the cursor, etc.

__How to reproduce__
 - Go to any text input or text area
 - Enter some text i.e. 'testing text selection'
 - Now try;
      - Try tapping twice to select 'text' - it's unreliable and will not select the text
      - Tap at the end of the field to move the cursor - again unreliable
      - Leave text field and tap press (shortly) at the end of the word 'text' - iOS would naively drop the cursor here as it focuses on the field. It instead just positions the cursor where it was before

Thankfully, I found a fix for this recently and have been manually patching it after each update. No credit to me! [Link](https://github.com/ftlabs/fastclick/pull/249/files)

Once you apply this, you get a native experience and the above examples will work as they would normally 👍  One of my apps has had this patch in for a few months without any known / reported side affects.

Is this something you can consider updating?

Cheers

**Comment by frandiox** [comment]
@Ralpharoo Definitely! We'll have a look at it. Lately, Fastclick is giving us some issues. Related #2000

**Comment by asialgearoid** [comment]
@Ralpharoo Thanks for the detailed report! I tested out your steps, and you are right. Using input fields on iOS is not a great experience.

I have updated our fork of FastClick with the code from the PR you linked. So it will be fixed in the next release of Onsen UI. Thanks for your help!
