### ISSUE TITLE
iOS Page Flickering

### ISSUE THREAD

**Issue by Ralpharoo** [OnsenUI/OnsenUI#2255]
__Environment__ 

```
[Core]
    onsenui 2.8.1

[Browser]
    Mobile - iOS UIWebView
    Mobile - iOS Safari
```

__Encountered problem__
Pages now flicker when content is scrollable.

Seems to be due to the addition of;

`
.page__content--suppress-layer-creation {
  -webkit-overflow-scrolling: auto;
}
`

Others have reported this before as a bug on iOS when changing the overflow-scrolling from touch to auto; [Link](https://github.com/scottjehl/Device-Bugs/issues/14)

__How to reproduce__
On iOS load any page with content long enough that the page will need to scroll.

**Comment by frandiox** [comment]
@asial-matagawa You are more familiar with that PR, can you please have a look at it?

**Comment by asial-matagawa** [comment]
Hi, @Ralpharoo!

Can you tell us what iOS version you are using now?
I think this problem strongly depends on it.

**Comment by Ralpharoo** [comment]
Hi @asial-matagawa 

I've experienced flickering when switching -webkit-overflow-scrolling through iOS 9, 10 and now 11 as I have been using it as a patch to fix scrolling under modal views (ref https://github.com/OnsenUI/OnsenUI/issues/2220).

I tested the latest version of OnsenUI this weekend on 11.1.2 and 10.3.2 and both flicker. Whilst I have not tested it within the WKWebView yet, this still flickered on iOS 9 and 10 (with my above fix).

Cheers,

**Comment by jiangbophd** [comment]
Dear,

I test this issue still exist in latest version.

**Comment by asialgearoid** [comment]
It looks like this was caused by the fix for #2231. In that situation, there was a flicker when switching between tabs inside a dialog. Ironically this fix appears to have caused other things to flicker instead.

For now I'm going to revert that fix, as it is a more obscure use case.

In the mean time, you can add this to your CSS as a workaround:
```
.page__content--suppress-layer-creation {
  -webkit-overflow-scrolling: touch !important;
}
```

**Comment by airamrguez** [comment]
@frandiox After merging this revert now it's flickering on my app. Versions greater than 2.9 flickers. Versions lower than 2.8.3 doesn't 🙃

**Comment by frandiox** [comment]
@airamrguez That's unfortunate :/ Under what conditions do you see the flickering? The original issue was with a tabbar inside a small dialog...

**Comment by airamrguez** [comment]
@frandiox the flickering occurs right after a page is pushed (when the page slide animation is completed). I revert this revert (apply the original code) and it works fine in 2.9.1 release.
