### ISSUE TITLE
Documentation for RouterNavigator?

### ISSUE THREAD

**Issue by zabojad** [OnsenUI/OnsenUI#2256]
The documentation for the [RouterNavigator](https://onsen.io/v2/api/react/RouterNavigator.html) react component is actually the one for the [Navigator](https://onsen.io/v2/api/react/Navigator.html) component so that we cannot see the difference between those two...

**Comment by uehaj** [comment]
I have same question. Where is the the RouterNavigator document?

**Comment by asialgearoid** [comment]
Thanks to @sbaechler's above PR, these docs have been fixed. This will be reflected in the online docs with the next release of the React bindings in the next week or two.
