### ISSUE TITLE
Warning about react missing when using react 16?

### ISSUE THREAD

**Issue by zabojad** [OnsenUI/OnsenUI#2257]
I get:
```
npm WARN react-onsenui@1.9.0 requires a peer of react@^15.5.3 but none was installed.
npm WARN react-onsenui@1.9.0 requires a peer of react-dom@^15.5.3 but none was installed.
```

While I have react 16 installed:
```
  "dependencies": {
    "onsenui": "^2.8.1",
    "react": "^16.1.1",
    "react-dom": "^16.1.1",
    "react-onsenui": "^1.9.0",
```

**Comment by frandiox** [comment]
@zabojad This is just due to the peer dependency in `react-onsenui`. It "requires" `react@15` because it mostly tested with that version. However, it should work well with `react@16` as well so you can ignore that for now.
