### ISSUE TITLE
pop multiple pages along with state

### ISSUE THREAD

**Issue by crosscourt** [OnsenUI/OnsenUI#226]
can you add a popPage(numberOfPages, state) to navigator?

the scenario is:
in an form entry page, if I pushed 2 pages to display lists to make a selection, I need to pop back to the form entry page with the selected value.

**Comment by zeroliu** [comment]
What's the equivalent for React?

**Comment by madhermit** [comment]
For anyone finding this through google:

this.props.navigator.routes.pop(); //repeat for however many pages you want to skip
this.props.navigator.popPage({animation: 'none'});

**Comment by mghayour** [comment]
@madhermit thank you, but this code bring up an white screen !
