### ISSUE TITLE
Reactive Forms NOT WORKING ON ANGULAR 2+

### ISSUE THREAD

**Issue by SebasG22** [OnsenUI/OnsenUI#2261]
## Update: HAVE PASSED 5 MONTHS WITHOUT ANSWER 

**Create at:** 26/11/2017
**Update at:** 17/05/2018

Hello everyone,

I started using OnsenUI finding that it is not possible to perform reactive forms that by default are the new feature of the new versions of angular (Angular + 2). This is a big problem since most applications use Forms for different functionalities. Currently it is possible to make "Template Driven Forms" but these involve much more code and process when making validations that with less code can be done with "Reactive Forms".

[Core]
    onsenui 2.8.2

[Framework]
    angular5 5.0.1

__Encountered problem__

Angular Compiler says: 
`LoginEmailComponent.html:3 ERROR Error: No value accessor for form control with name: 'email
![captura de pantalla 2017-11-26 a la s 7 37 06 a m](https://user-images.githubusercontent.com/17608169/33240039-13859e8a-d27d-11e7-8ffb-b5786bd599c5.png)`
```js
    at _throwError (forms.js:2385)
    at setUpControl (forms.js:2257)
    at FormGroupDirective.addControl (forms.js:6606)
    at FormControlName._setUpControl (forms.js:7256)
    at FormControlName.ngOnChanges (forms.js:7169)
    at checkAndUpdateDirectiveInline (core.js:12092)
    at checkAndUpdateNodeInline (core.js:13598)
    at checkAndUpdateNode (core.js:13541)
    at debugCheckAndUpdateNode (core.js:14413)
    at debugCheckDirectivesFn (core.js:14354)
View_LoginEmailComponent_0 @ LoginEmailComponent.html:3
```

__How to reproduce__

1. Create a component that contains a basic reactive form 

login-email.component.ts
```js
`this.form = new FormGroup({
      email: new FormControl('', Validators.required && Validators.email),
      password: new FormControl('', Validators.required)
    });
```
login-email.component.html
```html
<div style="padding-top: 10px">
      <form [formGroup]='form' (ngSubmit)="onSubmit(form)">
          <ons-input float placeholder="email" type="email" [formControlName]='email'></ons-input>
          <ons-input float placeholder="password" type="password" formControlName='password'></ons-input>
          <div style="text-align: center; margin: 10px;">
              <ons-button type="submit"> Sign in </ons-button>
            </div>
        </form>
</div>
```

See also :
[Reactive Forms Official Docs](https://angular.io/guide/reactive-forms)
[Template Driven vs Reactive Forms ](https://blog.angular-university.io/introduction-to-angular-2-forms-template-driven-vs-model-driven)

**Comment by SebasG22** [comment]
@frandiox Do you have a road map to fix this bug ?

**Comment by asialgearoid** [comment]
@SebasG22 Apologies for the very long delay in replying to you. There has been a lot of change in the Onsen UI team over the past few months, so some issues have gone ignored, including this one.

Right now the team is focused on other tasks, so this is not on the immediate roadmap I'm afraid. As always, pull requests are more than welcome!
