### ISSUE TITLE
Building OnsenUI

### ISSUE THREAD

**Issue by zabojad** [OnsenUI/OnsenUI#2264]
The [doc about building OnsenUI](https://onsen.io/v2/guide/build.html#building-onsen-ui) is outdated: there is no CircleCI Recipe...

I've found the gulp task that we can run with the shortcut `npm run build` but a lot of dependencies are missing and running `npm install` for each of them is not helping as we do not know what exact versions of those dependencies is required (it's crashing if we just take the latest versions).

Can you please at least push an updated package.json for OnsenUI with the exact required dependencies needed to build the project?

**Comment by asial-matagawa** [comment]
@zabojad 
Thank you for reporting!

The latest CircleCI Recipe is here:
https://github.com/OnsenUI/OnsenUI/blob/master/.circleci/config.yml

>a lot of dependencies are missing and running npm install for each of them is not helping
You have to run `yarn install` instead of `npm install` since the exact versions of those dependencies are saved in `yarn.lock`. (`npm install` ignores `yarn.lock`)

**Comment by asial-matagawa** [comment]
I fixed the link and it will be deployed later:
https://github.com/OnsenUI/onsen.io/commit/53b4e8a6f5e3fd57df1fe15f4702adf7bbb24df4

**Comment by zabojad** [comment]
@asial-matagawa OK thanks. Why doesn't the `package.json` contain all necessary dependencies so that we can run `npm run build` right after a `npm install`? Wouldn't it be the easiest way to test contributions before PR them?

**Comment by asial-matagawa** [comment]
@zabojad 
We were providing that way with `npm-shrinkwrap.json` but it was a bit crucial for us, so we decided to use Yarn instead of NPM.
I think that Yarn is now accepted by the JavaScript community well and we are not going to switch back to NPM.

**Comment by zabojad** [comment]
@asial-matagawa I don't understand. Yarn uses the `package.json` anyway and this files lacks about a dozen dependencies to make the `gulp build` command succeed... What does Yarn bring here that npm would not?

**Comment by asial-matagawa** [comment]
@zabojad 
Yarn uses `yarn.lock` and it contains all dependencies required for building Onsen UI.
`yarn.lock` in this repository is:
https://github.com/OnsenUI/OnsenUI/blob/baaa682bbf50da077e10650af1561e6b9c3e940d/yarn.lock

NPM 5+ has `package-lock.json` which is similar to `yarn.lock` but NPM <5 did not have the feature. That is why we have been using Yarn until now.

**Comment by zabojad** [comment]
@asial-matagawa Sorry to insist but these are the libs I had to install to get a successful build:
```
"ancss": "^0.1.5",
    "eco": "^1.1.0-rc-3",
    "gulp-plumber": "^1.1.0",
    "gulp-postcss": "^7.0.0",
    "gulp-stylelint": "^3.9.0",
    "postcss-base64": "^0.7.1",
    "postcss-cssnext": "^3.0.2",
    "postcss-import": "^11.0.0",
    "postcss-reporter": "^5.0.0"
```
And I see none of them in the yarn.lock file...

**Comment by asial-matagawa** [comment]
@zabojad 
You need to run `yarn install` in the `css-components` directory as well.
I think the current installation way is a bit complicated, yes...

**Comment by zabojad** [comment]
@asial-matagawa OK, thanks for the explanations. I close the issue as you have corrected the documentation. Thanks!
