### ISSUE TITLE
WeakMap is not defined

### ISSUE THREAD

**Issue by acrixl** [OnsenUI/OnsenUI#2266]
[Core]
    onsenui 2.8.2

[Framework]
    none

[Framework binding]
    none

[Additional libraries]
    none

[Platform]
    Mobile - Android 4.4.4

__Encountered problem__

Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) 

Uncaught ReferenceError: WeakMap is not defined onsenui.min.js:2

Uncaught ReferenceError: ons is not defined index.js:1

__How to reproduce__

cordova debug build for android, run simple example

**Comment by frandiox** [comment]
The WeakMap issue was already fixed in #2263
