### ISSUE TITLE
Support alibaba/weex framework.

### ISSUE THREAD

**Issue by foubei** [OnsenUI/OnsenUI#2269]
Hello, asking if you have a plan to support this awesome mobile cross-platform framework?

**Comment by frandiox** [comment]
@foubei Hi! Do you mean you want to run Onsen UI inside a webview in Weex?

**Comment by foubei** [comment]
Exactly

**Comment by Ray-Eldath** [comment]
Inside a WebView? Weex provides an instruction for extending render, I think it's better then use a WebView.
See: [Extend Web Render](http://weex-project.io/guide/extend-web-render.html)
But I think it's extreme complicate.

**Comment by asialgearoid** [comment]
Thanks for the link, @Ray-Eldath. As you say, this would introduce significant complexity into Onsen UI.

We have no plans to provide Weex integration at any point in the near future, so I am going to close this issue.
