### ISSUE TITLE
Splitter collapse="portrait" not working correctly

### ISSUE THREAD

**Issue by mishoboss** [OnsenUI/OnsenUI#2271]
When splitter is set to collapse="portrait", "landscape" or a media query, the first time it renders is not correct. The `ons-splitter-content` style is always set `left: 80%` and this makes the splitter content be thin and stick to right.
![image](https://user-images.githubusercontent.com/1629929/33517494-e4de47b0-d78d-11e7-8dab-21e29c18acea.png)

When orientation or screen size is changed, all is good. The issue is only at initial render.

```
[Core]
    onsenui 2.8.2

[Framework]
    react 16.2.0

[Framework binding]
    react-onsenui 1.9.0

[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1
    Desktop - macOS Sierra
```

**Comment by frandiox** [comment]
@mishoboss I think I've seen this before. You can try leaving it blank and setting the attribute later with JavaScript as a workaround.

**Comment by mishoboss** [comment]
Thanks, it works when its set later on `componentDidMount` and additional `setTimeout` of at least 2 seconds... I wonder what could be the reason and how to fix it properly? :(

**Comment by frandiox** [comment]
@mishoboss Not sure, but it's probably fixable somewhere in https://github.com/OnsenUI/OnsenUI/blob/master/core/src/elements/ons-splitter-side.js
I'm now busy with another task so I don't have much time for debugging. PRs welcome!
