### ISSUE TITLE
Error ng-repeat ons-tab + cordova +  angular v1

### ISSUE THREAD

**Issue by medianeclick** [OnsenUI/OnsenUI#2272]
![screen shot 2017-12-03 at 00 15 27](https://user-images.githubusercontent.com/1304398/33521080-b09d1a1c-d7bf-11e7-8720-1b538646b1ef.jpg)

```
<ons-page ng-controller="TabsController">
    <ons-tabbar id="tabbarfooter" var="tabbarfooter" ons-prechange="setFilter($event)">
	    <ons-tab page="views/home/cases.html" label="Mi Taxi" active icon="fa-taxi"></ons-tab>
	    <!--<ons-tab ng-repeat="taby in tabs track by $index" page="{{taby.page}}" icon="{{taby.icon}}" label="{{taby.plural}}" >
	    </ons-tab>-->
	    <ons-tab ng-repeat="taby in tabs track by $index" page="{{taby.page}}">
		  <input type="radio" style="display: none">
		  <button class="tabbar__button">
		    <div class="tabbar__icon">
		      <ons-icon icon="{{taby.icon}}"></ons-icon>
		    </div>
		    <div class="tabbar__label">{{taby.plural}}</div>
		    <div class="tabbar__badge notification"></div>
		  </button>
		</ons-tab>
	    <!--<ons-tab page="views/cases/calendar.html" label="Calendario" icon="fa-calendar"></ons-tab>
	    <ons-tab page="views/settings/settings.html" label="Configuración" icon="fa-cog"></ons-tab>-->
    </ons-tabbar>
</ons-page>
```

**Comment by medianeclick** [comment]
[https://codepen.io/mediane/pen/OOdzgp](url)

**Comment by medianeclick** [comment]
this error when using in index.html

<script src='https://cdnjs.cloudflare.com/ajax/libs/onsen/2.8.2/js/onsenui.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/onsen/2.8.2/js/angular-onsenui.js'></script>

![screen shot 2017-12-03 at 01 19 13](https://user-images.githubusercontent.com/1304398/33521375-40f1c8da-d7c8-11e7-9d29-f40120113415.jpg)

**Comment by frandiox** [comment]
@medianeclick This is not an actual bug. Tabs were not prepared to be dynamic and contain `{{ }}` in `page` attribute. You can try `ng-attr-page` instead to fix the errors but it will probably not load the page correctly. Maybe we can give support to `ng-attr-page` by allowing lazy loading of `page` attribute... I'll have a look at it.
