### ISSUE TITLE
iOS Unable to Scroll Menu - Scrolling Hidden Tabbar Pages

### ISSUE THREAD

**Issue by Ralpharoo** [OnsenUI/OnsenUI#2274]
__Environment__ 

```
[Core]
    onsenui latest

[Framework]
    angular1 1.5.5

[Framework binding]
    angular-onsenui 2.1.0

[Additional libraries]
    none

[Platform]
    Mobile - iOS 11.1.2 and iOS 10.3.1 (and in Phonegap Developer App)

[Browser]
   none
```

__Encountered problem__
Hi - me again with similar iOS problems. It would appear that you are unable to scroll the menu when using a tabbar with pages with scrollable content. When these are hidden to be next, they catch the scroll event.

__How to reproduce__
I have put a simple example together in Codepen. Seems related to the other issue #2220 except, this one is scrolling non visible views and stopping expected functionality (navigating the menu).

I've been using the PhoneGap developer app on iOS;
1) On the first view, click the menu icon to open the menu - you will not be able to scroll the menu
2) Now close the menu and go to the second tab, it will have caught the touches and scrolled
3) Try and open the menu when on page 2, works fine. Add a third page, the outcome is the same until the last page (or you move the menu to the left etc.).

Code; [https://codepen.io/anon/pen/zPQOMO](https://codepen.io/anon/pen/zPQOMO)

_P.s. the 'Report an issue' button on [here](http://tutorial.onsen.io/?framework=angular1&category=common%20patterns&module=splitter_navigator) gave me a "414 Request-URI Too Large" with the example in the pen._

**Comment by Ralpharoo** [comment]
Note; only seems to occur with animation as "reveal". The others do not react in the same way. For now, I can patch with a box-shadow on Push! 👍

**Comment by frandiox** [comment]
@Ralpharoo For the `reveal` animation, you can add something like this to your app (>= 2.9.0):

```css
.ons-ios-scroll ons-tabbar .page:not([shown]) > .page__content {
  overflow-y: hidden;
}

```

That will prevent hidden pages in ons-tabbar to scroll when the splitter is open :+1:
