### ISSUE TITLE
i do not know how to get and add a Properties to ons-page

### ISSUE THREAD

**Issue by zhaoshiming** [OnsenUI/OnsenUI#2275]
__Environment__ 

```
[Core]
    onsenui 2.1.0

[Framework]
    angular2 2.2.4

[Framework binding]
    angular2-onsenui 1.0.0-rc.5

[Browser]
    Desktop - Chrome 55.0.2883.75
```

__Encountered problem__
hello, i am sorry to bother you, but i can not set a topic in your web.

here is my question.

down here is my code in root component 
<ons-navigator [page]="initialPage" id=""></ons-navigator>  

in my another component 'news', i want to load more data when the page is scroll to the bottom ,
but i can not get the page.

how can i get the page ,down here is the ts of the news component 
import { Component, OnInit } from '@angular/core';
import { PersonComponent } from '../person/person.component';
import {
  ViewChild,
  OnsNavigator,
  Params
} from 'ngx-onsenui';
import { localService } from '../../app.service';
import { URLSearchParams } from '@angular/http';
import { PageNotFoundComponent } from '../page-not-found/page-not-found.component';

interface param {
  pageSize: string
}

@Component({
  selector: 'ons-page[one]',
  templateUrl: './news.component.html',
  styleUrls: ['./news.component.css'],
  // providers: [OnsNavigator] sb 不要加这个句代码
  providers: [localService]
})
export class NewsComponent implements OnInit {
  title :any;
  data: any;
  labelIdList: any;
  infoList:any;
  labelId: any;
  demo : any = {};
  pageNum : any = 1;
  message: string = '下拉刷新...';
  tab1 = PageNotFoundComponent;
  tab2 = PersonComponent;
  @ViewChild ('fuck')  fuck;
  // tab3 = Tab3Component
  constructor(private _navigator: OnsNavigator, public _localService: localService) {
    for (var a in this._navigator) {
      // console.log(a);
    }
    console.log(this._navigator.element.topPage);
    // this._navigator.topP
    this._navigator.element.topPage.onInfiniteScroll = function (){
      console.log('1212121212121212121');
    }
  }

  ngOnInit() {
    this.getColumn ();
    this.title = "资讯列表";
    
  }

  push() {
    this._navigator.element.pushPage(PersonComponent);
  }

  onAction($event) {
    setTimeout(() => {
      // this.pageNum = 1;
      this.getNewsList($event); 
    }, 1000);
    
  }

  onChangeState($event) {
    switch ($event.state) {
      case 'initial':
      this.message = '下拉刷新..';
      break;
      case 'preaction':
      this.message = '松手更新...';
      break;
      case 'action':
      this.message = '加载中...';
      break;
    }
  }

  getNewsList(d){
    let params = new URLSearchParams();
    params.set('pageSize', '8');
    params.set('pageNum', this.pageNum);
    params.set('sort', '0');
    params.set('columnId', this.labelId);
    this._localService.get('article/getFArticlelist.show', params).subscribe(res => {
      this.infoList = res.data.list;
      if(d!=1)  d.done();     
    })
  }

  //活动栏目
  getColumn () {
    let params = new URLSearchParams();
    params.set('menuId', '12');
    this._localService.get('menu/getFColumns.show',params).subscribe(res => {
      this.labelIdList = res.data.list;
      this.labelId = this.labelIdList[0].labelId;
      this.getNewsList(1);
    })
  }

  checkColumn(id) {
    this.labelId = id;
  }

}

**Comment by puku0x** [comment]
How about injecting `ElementRef` of the page and hooking `onInfiniteScroll` like this ?

```ts
@component({
  selector: 'ons-page[one]',
  ...
})
export class NewsComponent implements OnInit {
  constructor(private element: ElementRef) { }

  // Infinite scroll
  this.element.nativeElement.onInfiniteScroll = (done) => {
    // this.loadMoreNews(done);
  };
}
```

https://github.com/puku0x/ngx-onsenui-kitchensink/blob/master/src/app/pages/infinite-scroll/load-more/load-more.component.ts#L31-L33

**Comment by zhaoshiming** [comment]
i solved it by using onsNavigator , get the top page by it. what upset me is that i can not get the page by <code>this._navigator.nativeElement.topPage</code> but the code <code>this._navigator.element.topPage</code>, and i found no recommend on the website.
anyway, thanks for your time, my english is terrible... thanks for the read again.

**Comment by zhaoshiming** [comment]
@puku0x
