### ISSUE TITLE
Behavior of carousel in the latest version OnsenUI (2.8.2) + AngularJS

### ISSUE THREAD

**Issue by randnetdd** [OnsenUI/OnsenUI#2282]
I am thinking about updating from Onsen UI 2.3 series to the latest version (2.8 series),
The behavior of carousel is different from what I thought.

ons-carousel is initially displayed in a hidden state with ng-hide, and ons-carousel does not work if displayed after a few seconds.
It works with 2.3.3

latest
https://codepen.io/anon/pen/wPbQRO

2.3.3
https://codepen.io/anon/pen/rYgoMm

Also, if there is only one ons-carousel-item, only the direction in overscroll will be output left.
In 2.3.3 right is also output

latest
https://codepen.io/anon/pen/ypBaMB

2.3.3
https://codepen.io/anon/pen/xpKEXg

[Core]
    onsenui 2.8.2

[Framework]
    angular1 1.5.5

[Framework binding]
    angular-onsenui 2.8.2

[Additional libraries]
    none

[Platform]
    Desktop - Windows 7

[Browser]
    Desktop - Chrome 62

https://community.onsen.io/topic/1842/%E6%9C%80%E6%96%B0%E7%89%88onsenui-angularjs%E3%81%A7%E3%81%AEcarousel%E3%81%AE%E6%8C%99%E5%8B%95

**Comment by frandiox** [comment]
@randnetdd I think this is the same issue as #2278 but using Angular.js instead of Vue. For now, you can try with `ng-if` instead of `ng-hide`. I'll try to check what has changed between these versions and see if we can make it work like before.

**Comment by randnetdd** [comment]
The problem with direction was _normalizeScroll would be 0 if itemCount was 1.
In this state dM.dir will always return left

var scroll = this._scroll - this._getDelta(event);

    key: '_killOverScroll',
    value: function _killOverScroll(normalizedScroll, scroll) {
      var _this6 = this;

      this._scroll = normalizedScroll;
      var direction;
      if (this.itemCount === 1) {
        direction = this.dM.dir[Number(scroll > 0)];
      } else {
        direction = this.dM.dir[Number(normalizedScroll > 0)];
      }
      var killOverScroll = function killOverScroll() {
        return _this6._changeTo(normalizedScroll, { animationOptions: { duration: .4, timing: 'cubic-bezier(.1, .4, .1, 1)' } });
      };
      this.overScrollHook({ direction: direction, killOverScroll: killOverScroll }) || killOverScroll();
    }

**Comment by pjriordan** [comment]
The carousel overscroll direction with only one ons-carousel-item is still broken as of onsenui 2.10.1. Any ideas @frandiox ?
