### ISSUE TITLE
Tappable animation not working 2.8.3

### ISSUE THREAD

**Issue by msolovyov** [OnsenUI/OnsenUI#2292]
Tappable animation stopped working when updated to 2.8.3

Before versions -> updated version:
onsenui                     ^2.8.2  →    ^2.8.3
vue                            ^2.5.13
vue-onsenui                    ^2.4.3

Ripple animation still works but the tappable (ios) animation doesn't animate. Nothing changed except module update. 

Example item:

      <v-ons-list modifier="inset">
        <v-ons-list-item tappable modifier="longdivider" tap-background-color="#FDB813">
          <v-ons-row class="center-content">
            <div class="partner">
            </div>
          </v-ons-row>
        </v-ons-list-item>

**Comment by frandiox** [comment]
@msolovyov That's visual fix in 2.8.3. Tappable is not triggered by `ons-*` elements inside `ons-list-item` anymore. To be honest, we didn't think about `ons-col` and `ons-row`. Perhaps we should allow those 2. In any case, do you really need `ons-row` there? List items are already split into left, center and right parts.

**Comment by msolovyov** [comment]
@frandiox I have multiple rows inside the item so it makes it easy to layout. How do I turn tappable back on for ons elements?

**Comment by frandiox** [comment]
@msolovyov I don't think it's possible in `2.8.3` but I guess we will change it for the next release. Until then, you can apply a quick patch in your root Vue component:

```
  beforeCreate() {
    this.$ons.elements.ListItem.prototype.isExcludedTarget = () => false;
  }
```
