### ISSUE TITLE
PullHook will cause scroll issue in react binding.

### ISSUE THREAD

**Issue by jiangbophd** [OnsenUI/OnsenUI#2293]
Dear, 

If I use the pull hook component, the scroll list is not good, do not have good experience.

Is any solution for it, I use react binding.

Thanks!

**Comment by frandiox** [comment]
@jiangbophd I'd need to debug this but I think it is possible to improve scrolling performance when the list is not at the top. It will take some time, though.

**Comment by frandiox** [comment]
This should have somewhat improved in the lastest core release 2.9.0 :+1:
