### ISSUE TITLE
tabs displayed vertically

### ISSUE THREAD

**Issue by bdedardel** [OnsenUI/OnsenUI#2296]
__Environment__ 

```
[Core]
    onsenui v2.8.3

[Framework]
    angular1 1.6.8

[Framework binding]
    angular-onsenui v2.8.3

[Platform]
    Mobile - Android 6 + 7
    Desktop - Linux
```

__Encountered problem__
I used tabbar with previous onsenui version, to get **horizontal** tabs.
The exemple above was displayed on the same line, each with 50% width. 

| TAB1 | TAB2 |

```
<ons-tabbar position="top">
<ons-tab label="TAB1" page="tab1.html" active="true">
</ons-tab>
<ons-tab label="TAB2" page="tab2.html">
</ons-tab>
</ons-tabbar>
```
Since I upgraded onsenui, it appears that tabs are displayed vertically.

|       TAB1        |
|       TAB2        |

Is there a way to keep the previous behavior ?

Best regards,
Benjamin

**Comment by bdedardel** [comment]
It should be some other dependancies that create the issue.
I'm investigating...

**Comment by frandiox** [comment]
@bdedardel It must be something else, yes. The tabs are still and will be horizontal. You can have a look at [this example](http://tutorial.onsen.io/?framework=angular1&category=reference&module=tabbar).
