### ISSUE TITLE
<SplitterSide /> with React giving this error: TypeError: this.node.close is not a function on Chrome

### ISSUE THREAD

**Issue by paulossm** [OnsenUI/OnsenUI#2299]
Hello,
I am experiencing this issue when trying to render a component with Splitter.
The error happens with the minimum content for SplitterContent and SplitterSide.

Error Description:
SplitterSide.componentWillReceiveProps
  5725 |     if (newProps.isOpen) {
  5726 |       this.node.open();
  5727 |     } else {
> 5728 |       this.node.close();
  5729 |     }
  5730 |   }
  5731 | }, {

__Environment__ 

```
[Core]
    onsenui ^2.8.3
[Framework]
    react ^16.1.1

[Framework binding]
    react-onsenui ^1.9.0

[Additional libraries]
    none

[Platform]
    Desktop - Windows 10

[Browser]
    Desktop - Chrome 63.0.3239.108 (64-bit)
```
Also tested on Firefox, Opera, Edge and works well on them.

__Encountered problem__

__How to reproduce__

**Comment by frandiox** [comment]
@paulossm I could not reproduce this issue so please make a small example in http://tutorial.onsen.io/?framework=react&category=reference&module=splitter and hit `Report an issue` button :+1:

**Comment by aryraditya** [comment]
@frandiox please take a look at this, this is the code that showing the same error above

https://codesandbox.io/s/13zp50kjl7

**Comment by jacobweber** [comment]
Just ran into the same issue, also using React.
