### ISSUE TITLE
Button Outline

### ISSUE THREAD

**Issue by johnkmzhou** [OnsenUI/OnsenUI#2300]
__Environment__

  
```
[Core]
  onsenui latest
  
[Framework]
  react 15.4.2

[Framework binding]
 react-onsenui latest

[Platform]
  Desktop - OS X 10.12.6 64-bit

[Browser]
  Desktop - Chrome 63.0.3239.108 on OS X 10.12.6 64-bit
```

__Encountered problem__
  When using modifier='outline', the outline for the button doesn't show up in Android. This also affects other frameworks besides React.

  
  [__Demo link__](https://tutorial.onsen.io/?issue)

  

- __HTML__

```html
<div id="app"></div>
```

- __JS__

```jsx
var MyPage = React.createClass({
  handleClick: function() {
    ons.notification.alert('Hello world!');
  },

  renderToolbar() {
    return (
      <Ons.Toolbar>
        <div className='center'>Buttons</div>
      </Ons.Toolbar>
    );
  },

  render: function() {
    return (
      <Ons.Page renderToolbar={this.renderToolbar}>
        <Ons.Button style={{margin: '6px'}} modifier='outline'>Outline</Ons.Button>
      </Ons.Page>
    );
  }
});

ons.ready(function() {
  ReactDOM.render(<MyPage />, document.getElementById('app'));
});
```

**Comment by frandiox** [comment]
@johnkmzhou Hi! I think there is no `outline` modifier in the material design specs. Therefore, autostyling is removing `outline` automatically for Android. This could be avoided by adding `disable-auto-styling` attribute but looks like it doesn't work properly with React/Vue bindings. I'll leave this open as a reminder for this bug :+1:

**Comment by frandiox** [comment]
@johnkmzhou It actually works well when adding `disable-auto-styling` before `modifier` attribute: `<Ons.Button disable-auto-styling style={{margin: '6px'}} modifier='outline'>Outline</Ons.Button>`.
