### ISSUE TITLE
In React, add ref property to form components

### ISSUE THREAD

**Issue by lucnat** [OnsenUI/OnsenUI#2301]
In React when using `<Input />`, it would be nice if we could set the `ref` property of the underlying `<input />`. This would give a nice and simple way to get the form data when using uncontrolled components. Form elements that would need ref are 

- Input
- Checkbox
- Radio
- Range
- Searchinput
- Select
- Switch

**Comment by frandiox** [comment]
@LucNaterop Maybe we can add some kind of `elementRef` prop to set the ref in the actual Custom Element and expose it. From there, you could access the inner input by using a DOM property like `element.input` or `element.select`. @zabojad Thoughts?

**Comment by zabojad** [comment]
@frandiox yes, there could be some kind of `elementRef` or `domInputRef` property to get the inner input ref.

@LucNaterop But if this is just to get the value of uncontrolled inputs, you can do like this:
* give a name attribute to each of your form element,
* wrap them in a `<form>` HTML element,
* get the values of your inputs with a a FormData like this (below is Haxe js syntax but it almost the same as js except it is typed):
```
      // ...

      function getFormData() : LoginFormShape {

		var fd : js.html.FormData = new js.html.FormData(_form); // _form being the ref of your form element

		var ret : LoginFormShape = 

			{
				login: fd.get("login"),
				password: fd.get("password")
			};

		return ret;
	}

       // ...
```
