### ISSUE TITLE
When use input type='number' come up problem.

### ISSUE THREAD

**Issue by MarsZone** [OnsenUI/OnsenUI#2304]
Actually it's not onsenui problem but It's about fastclick on chrome.
I found the same question at https://github.com/ftlabs/fastclick/issues/358.

[Core]
 "onsenui": "^2.8.3",

[Framework]
   "vue": "^2.5.9",

[Framework binding]
    "axios": "^0.17.1",
    "onsenui": "^2.8.3",
    "vue": "^2.5.9",
    "vue-onsenui": "^2.4.3",
    "vue-simple-calendar": "^1.8.2",
    "vuex": "^3.0.1"

[Platform]
    Desktop - macOS High Sierra 10.13.2

[Browser]
   
    Desktop - Chrome  63.0.3239.132
    Desktop - Safari 11.0.2 --->This is works fine.

__Encountered problem__
When I touch the input which type was number.
Come up with error like this.
Uncaught DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('number') does not support selection.
    at FastClick../node_modules/onsenui/js/onsenui.js.FastClick.focus 
<img width="819" alt="bug" src="https://user-images.githubusercontent.com/3784198/34718841-3d888152-f573-11e7-9c80-6d63fc65a23f.png">

__How to reproduce__
On mac use chrome and touch the input which type is number.

**Comment by asialgearoid** [comment]
@MarsZone You don't need to worry much about it, as it only happens in Chrome if you are previewing as an iOS device. So, you will only see it in development. It no longer happens on an iOS device.

In any case, this is annoying to have happen while developing, so I have fixed this in our fork of the FastClick library. It will be include in the next Onsen UI release.

**Comment by MarsZone** [comment]
@asialgearoid Thank you for reply 👍.
I got it, it's not a big problem and nice work.
