### ISSUE TITLE
Uncaught TypeError: el.dialog.show is not a function - notification.js

### ISSUE THREAD

**Issue by ymoreiratiti** [OnsenUI/OnsenUI#2305]
**Core** - onsenui 2.8.2
**Framework** - vue 2.5.2
**Framework binding** - vue-onsenui 2.4.2
**Additional libraries** - none
**Platform** -  Windows 10 Desktop
**Browser** Chrome 63.0.3239.84

__Encountered problem__
When i'm trying to use the _notification.alert()_, the console returns:
`Uncaught TypeError: el.dialog.show is not a function
    at eval (notification.js?83ac:168)
    at run (setImmediate.js?9b2a:40)
    at runIfPresent (setImmediate.js?9b2a:69)
    at onGlobalMessage (setImmediate.js?9b2a:109)`

__How to reproduce__

1. Create a new project using _vue init OnsenUI/vue-pwa-webpack my-project_
2. Change _src/pages/MenuPage.vue:L28_, to `<v-ons-card @click="$ons.notification.alert('Hi there!')">vue-router</v-ons-card>`
3. npm run dev
4. click on "vue-router"

Using the Vue Cordova template, i can't reproduce the error.

Print Screen of the error:
![image](https://user-images.githubusercontent.com/5731429/34877843-d93a66de-f78e-11e7-90fc-12ba5dfe5c09.png)

src folder: [src.zip](https://github.com/OnsenUI/OnsenUI/files/1626197/src.zip)

**Comment by ymoreiratiti** [comment]
Print Screen of the error:
![image](https://user-images.githubusercontent.com/5731429/34877843-d93a66de-f78e-11e7-90fc-12ba5dfe5c09.png)

src folder: [src.zip](https://github.com/OnsenUI/OnsenUI/files/1626197/src.zip)

**Comment by emccorson** [comment]
You need to import `v-ons-alert-dialog` and `v-ons-alert-dialog-button` by uncommenting lines 5 and 6 in _vue-onsen-components.js_:

```javascript
export { default as VOnsAlertDialog } from 'vue-onsenui/esm/components/VOnsAlertDialog'
export { default as VOnsAlertDialogButton } from 'vue-onsenui/esm/components/VOnsAlertDialogButton'
```

There is more explanation about this in the docs: https://onsen.io/v2/guide/appsize.html#es-modules

This seems like a common problem so I think in the future we will add an error message for when you try to use an alert without importing `ons-alert-dialog`.
