### ISSUE TITLE
Angular2 | Page issue: ons.notification.toast with modifier in ts code doesn't work

### ISSUE THREAD

**Issue by cmcampione** [OnsenUI/OnsenUI#2320]
__Environment__

  
```
[Core]
  onsenui latest
  
[Framework]
  angular2 4.3.6

[Framework binding]
 angular2-onsenui latest

[Platform]
  Desktop - Windows 10 64-bit

[Browser]
  Desktop - Chrome 63.0.3239.132 on Windows 10 64-bit
```

__Encountered problem__
Hello all,
from https://medium.com/the-web-tub/creating-custom-modifiers-dffc3490309f i try to implement a modifier for  ons.notification.toast but when I use in ts code:

 ons.notification.toast('Hello, world!', {
      timeout: 2000,
      modifier: 'danger'
    });

it doesn't work.

Thanks

__How to reproduce__
  

  
  [__Demo link__](https://codepen.io/anon/pen/YYRzKN?&editors=100)

  

- __HTML__

```html
<app></app>
```

- __JS__

```typescript
import {
  Component,
  ComponentRef,
  ViewChild,
  Params,
  OnsenModule,
  NgModule,
  CUSTOM_ELEMENTS_SCHEMA
} from 'ngx-onsenui';
import {platformBrowserDynamic} from '@angular/platform-browser-dynamic';
import * as ons from 'onsenui';

@Component({
  selector: 'app',
  styles: [`
    .toast--danger { 
    left: auto; 
    background-color: hsl(348, 100%, 61%); 
  }`],
  template: `
  <ons-page class="page">
    <div class="content">
      <ons-list>
        <ons-list-header>Notifications</ons-list-header>
        
        <ons-list-item tappable (click)="toast()">Toast</ons-list-item>

      </ons-list>
    </div>
  </ons-page>
  `
})
export class AppComponent {
  constructor() {
  }

  toast() {
    ons.notification.toast('Hello, world!', {
      timeout: 2000,
      modifier: 'danger'
    });
  }
}

@NgModule({
  imports: [OnsenModule],
  declarations: [AppComponent],
  bootstrap: [AppComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA]
})
class AppModule { }

platformBrowserDynamic().bootstrapModule(AppModule);
```

**Comment by frandiox** [comment]
@cmcampione Hi! Angular2 styles prop is scoped CSS, whereas modifiers are meant to be global (so they can be reused in every toast element). This is not something we need to fix on our side, it's just how scoped CSS is supposed to work. You can inline CSS with `<style>` tag in your component like they explain [here](https://angular.io/guide/component-styles#template-inline-styles) and it will work.

Nothing to fix :+1:
