### ISSUE TITLE
react Splitter

### ISSUE THREAD

**Issue by Eyrum** [OnsenUI/OnsenUI#2327]
I got some trouble with react Splitter

when my first page set Splitter, that will work.  if I push the page to the second page with Splitter, my second page doesn't show, and page back to the first page, and got a err ' flattenChildren(...): Encountered two children with the same key'.

I think I need your guy's help if somebody got the same problem, thanks.

```
[Core]
    onsenui 2.1.0

[Framework]
    
    react 15.4.1
   

[Framework binding]
   
    react-onsenui 1.1.0
    

[Additional libraries]
    none
    

[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1
    Desktop - Linux
    Desktop - macOS Sierra
    Desktop - Windows 10

[Browser]
    Mobile - Android WebView
    Mobile - Android Chrome 54.0.2840.85
    Mobile - iOS UIWebView
    Mobile - iOS Safari
    Desktop - Chrome 55.0.2883.75
    Desktop - Safari 10.0 (12602.1.50.0.10)
```

__Encountered problem__

__How to reproduce__

**Comment by Eyrum** [comment]
here is my demo code https://github.com/Eyrum/onsen-test

**Comment by frandiox** [comment]
@Eyrum Hi! Your Splitter is a child of Navigator so whenever you change Navigator's content, the Splitter will be affected. If you always want a Splitter in your app, the you should move it to your root component and make it a parent of the Navigator. There's an example in the tutorial app: http://tutorial.onsen.io/?framework=react&category=common%20patterns&module=splitter_navigator
