### ISSUE TITLE
Bug: Swipe to pop with animation "lift" -> page stays at 0.4 opacity

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#2333]
- Newest Onsen, with ons-splitter and a navigator inside. AngularJS 1.
Added "swipeable" Attribute to navigator.

When I swipe to pop a page which was animated with "lift", the page behind stays at opacity 0.4 after the animation has finished. On usual slide animations, swipe to pop works as expected. @frandiox

**Comment by frandiox** [comment]
@Hirbod Well, swipe-to-pop is only meant to be used with slide animation. You would need to remove `swipeable` attribute if you sometimes push a page with a different animation. Something like this could work:

```js
myNavigator.addEventListener('postpush', function(event) {
  if (event.enterPage.pushedOptions.animation === 'lift') {
    myNavigator.removeAttribute('swipeable');
  }
});
myNavigator.addEventListener('postpop', function(event) {
  if (event.enterPage.pushedOptions.animation !== 'lift') {
    myNavigator.setAttribute('swipeable', '');
  }
});
```

I guess we could add some code to the core to avoid this situation

**Comment by Hirbod** [comment]
Well, this is either documented and I disagree. Of course the core (onsen) should prevent a swipe to pop on anything else then "slide" oder "slide-md", but imho, it should add a "flick 2 dismiss" (flick down/slideup if on scrollTop 0 or scrollEnd).

This is a known UX on iOS and pretty easy to implement, as you guys have a fully working pull 2 refresh which technically could be used to achieve this kind of behaviour). I already hacked something together with ons-gesture-detection, but I would love to see that feature inside of the core.

**Comment by Hirbod** [comment]
If you disagree to implement a core prevention and to add a "flick 2 dismiss" option, please just fix that 0.4 opacity bug, so people can decided themselves to use swipe-to-pop on lifted animations.

**Comment by frandiox** [comment]
@Hirbod 
>I guess we could add some code to the core to avoid this situation

Means that I actually agree. Until anything like "flick to dismiss" is implemented we can just prevent it.

**Comment by Hirbod** [comment]
Sorry, misread that. Yeah, sorry! Would be nice to have this feature :)
