### ISSUE TITLE
Swipe to pop on pushPage "lift"

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#2334]
A lifted page should not swipe to pop from the left edge, it should "flick to dismiss" when pulling down from top to bottom (but respecting scroll if there is longer content, like pull-to-refresh).

Currently, the integrated behaviour is not an correct UX and also pretty buggy, as the background stays at 0.4 opacity after pop.

**Comment by frandiox** [comment]
As said in #2333, it is not meant to work with other animations. We can continue the discussion there since I think this issue does not add anything new :+1:
