### ISSUE TITLE
Angular 5.2.2 CSS import path Error

### ISSUE THREAD

**Issue by Thibaud-M** [OnsenUI/OnsenUI#2336]
Hello folks,

I've some issue with my last package update:
**Can't resolve 'ionicons/css/ionicons.min.css' in '/Users/Thibaud/\*\*\*/node_modules/onsenui/css'**

Here's my Configuration package.json
```
"@angular/core": "^5.2.2",
"ngx-onsenui": "^4.1.0",
"onsenui": "^2.9.1",
```

To fix the issue: 
it's in ./node_modules/onsenui/css/onsenui.css (at beginning of the file)

Before:
```
/*! onsenui - v2.9.1 - 2018-01-26 */
@import url('ionicons/css/ionicons.min.css');
@import url('material-design-iconic-font/css/material-design-iconic-font.min.css');
@import url('font_awesome/css/font-awesome.min.css');
```

After
```
/*! onsenui - v2.9.1 - 2018-01-26 */
@import url('./ionicons/css/ionicons.min.css');
@import url('./material-design-iconic-font/css/material-design-iconic-font.min.css');
@import url('./font_awesome/css/font-awesome.min.css');
```

Did I miss something setting up the project or is it a bug?

Best,

Thibaud

**Comment by frandiox** [comment]
@Thibaud-M I guess there is something in the project setup breaking this because we didn't make any change to the CSS recently :thinking:
You could also use `onsenui-core.css` instead (doesn't include fonts) and import the fonts you need manually in your project.

**Comment by chunxchun** [comment]
I have the same issue, and using onsenui-core.css didn't solve the issue.

**Comment by frandiox** [comment]
@asial-matagawa Any idea?

**Comment by JAGFin1** [comment]
I can confirm I was getting this issue as well with version 2.9.2 of onsenui. Using @Thibaud-M's technique of changing the node_module worked, but I feel like this should probably be updated upstream.

**Comment by puku0x** [comment]
I could not reproduce the issue.

This is my procedure
1. `npm install -g @angular/cli`
2. `ng new ngx-onsenui-sample --style=scss`
3. `cd ngx-onsenui-sample`
4. `npm install onsenui ngx-onsenui`
5. Import css files into `style.scss`
```scss
/* You can add global styles to this file, and also import other style files */
@import "~onsenui/css/onsenui.css";
@import "~onsenui/css/onsen-css-components.min.css";
```
6. Make a page with `ons-icon`

It works with no error.
