### ISSUE TITLE
Webview on Android 8 shows white screen

### ISSUE THREAD

**Issue by AntonGame** [OnsenUI/OnsenUI#2350]
We are looking at if we should use Onsen UI in our app. what we need is the ablity to run a website inside a webview on android.

https://onsenui.github.io/vue-onsenui-kitchensink/main.html?platform=android.

this app works fine on the chrome browser on android but it just displays a white screen in the webview.

we are not using monoca or anything like that.

we have tested on android 8.1 and android 7.1 with no luck.

everthing should be up to date.

**Comment by frandiox** [comment]
@AntonGame Hi! I just tried it on my Android 8.0 and it still works as usual. Are you forking/downloading master branch, running `yarn`, running `npm run build` and then generating your app? You will also need to include `<script src="cordova.js"></script>` in your `index.html`, although this shouldn't be the source of your issue...

For quick development, I highly recommend using Monaca CLI with Monaca Debugger in their free versions. You can get the preview on your phone in a matter of seconds.

**Comment by AntonGame** [comment]
Have you tried it in a webview, like in a normal Android app with a webview. We am not using cordova, we are creating a normal Android app and we are using a webview to show some user created content and for that we want to use onsen ui, but your ons page shows a blank screen each time

**Comment by frandiox** [comment]
@AntonGame Cordova and Monaca use the device's webview, so it should be the same unless you are importing a different webview somehow. Do you get any error? Perhaps some files are not included or something else. I'd suggest starting with more basic examples and see if they work in your environment.

**Comment by AntonGame** [comment]
It is very simple, i have created a basic Android app with a webview. Linking to to a page with Onsen ui, everthing works if i dont use ons-page or ons-navigator, as soon as i use ons-page everthing inside the ons-page shows as white on the screen. soo please try with a simple webview and give me a sample off it working

**Comment by AntonGame** [comment]
okay so it works inside a iframe? if i navigate on a webview to https://onsenui.github.io/vue-onsenui-kitchensink/. everthing shows but when i click on full view nothing shows, just blank page.
