### ISSUE TITLE
iOS scroll problem

### ISSUE THREAD

**Issue by mapnia** [OnsenUI/OnsenUI#2353]
Hi, 

I have a page with the last version (2.9.2) with an infinity scroll and a pull-hook. In Android is working fine. But with iOS when the user scroll sometimes blind and jump to different positions. Does anyone know why?

Thanks!

J. Carlos

**Comment by Orlandster1998** [comment]
@mapnia This could maybe help you: https://onsen.io/v2/api/vue/$ons.html#method-forceUIWebViewScrollFix

**Comment by mapnia** [comment]
Thanks for your help, but the problem continues when I add  ons.forceUIWebViewScrollFix();

**Comment by ccloveaa** [comment]
when onsen will release next build?
