### ISSUE TITLE
Add mask-color to ons.notification.prompt etc.

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#2358]
While ActionSheet and Alert have it, I am missing it for prompt.

Tried on newest OnsenUI version with

```js
ons.notification
	.prompt({
	    title: "Werbecode",
	    cancelable: true,
	    maskColor: "rgba(0,0,0,0.7)",
	    message:
	        "XXXXXX."
	})
```

but wasn't successful.

**Comment by Hirbod** [comment]
+ missing an optional "cancel" button on prompt()..

**Comment by asialgearoid** [comment]
@Hirbod Thanks for the feedback! This is indeed a missing feature. I will look into implementing it for the next release.

**Comment by Hirbod** [comment]
thx @asialgearoid
