### ISSUE TITLE
setImmediate not defined when using require 

### ISSUE THREAD

**Issue by markhats** [OnsenUI/OnsenUI#2360]
When using require to load onsenui.js, it is possible that ```setImmediate``` is not defined before it is used. This happens in ```waitDOMContentLoaded``` which uses  ```setImmediate``` and is called before it is defined here: https://github.com/OnsenUI/OnsenUI/blob/1ca33c2a713c2e93ae3c8fce58ff9c008153194d/core/src/polyfills/MutationObserver%400.7.22/MutationObserver.js#L34

**Comment by frandiox** [comment]
@markhats Can you provide a repro? Otherwise, it's hard for us to debug.

**Comment by markhats** [comment]
I will try to get some time to produce a simple repo. However, the situation is basically this.

**Loading onsenui.js via a ```<script>``` tag in index.html (working)**
This code is hit first:
```
internal$1.waitDOMContentLoaded(function () {
            register('script[type="text/ons-template"]');
            register('script[type="text/template"]');
            register('script[type="text/ng-template"]');
            register('template');
            ....
```
Inside ```internal$1.waitDOMContentLoaded```, ```window.document.readyState``` is equal to "loading", so ```setImmediate```, which is undefined, is not called.
Later, ```setImmediate``` then gets defined as shown in my original post.

**Loading onsenui.js via require (not working)**
This code is hit first:
```
internal$1.waitDOMContentLoaded(function () {
            register('script[type="text/ons-template"]');
            register('script[type="text/template"]');
            register('script[type="text/ng-template"]');
            register('template');
            ....
```
Inside ```internal$1.waitDOMContentLoaded```, ```window.document.readyState``` is equal to "complete", so ```setImmediate```, which is undefined, is called.
Error generated:
```
require.js:143 Uncaught ReferenceError: setImmediate is not defined
    at Object.internal$1.waitDOMContentLoaded (onsenui.js:984)
    at onsenui.js:1036
    at Object.execCb (require.js:1696)
    at Module.check (require.js:878)
    at Module.enable (require.js:1176)
    at Module.init (require.js:788)
    at callGetModule (require.js:1203)
    at Object.completeLoad (require.js:1590)
    at HTMLScriptElement.onScriptLoad (require.js:1717)
```

Hope this helps.

**Comment by pierredavidbelanger** [comment]
In my app (built with parcel), when `internal$1.waitDOMContentLoaded` is called, `window.document.readyState` is equals to `'interactive'`, and `window.setImmediate` is `undefined`.

**Comment by pierredavidbelanger** [comment]
Here is my smelly workaround:

```
require('onsenui/css/onsenui-core.css');
require('onsenui/css/onsen-css-components.css');
window.setImmediate = window.setTimeout;
const ons = require('onsenui/js/onsenui');
```

**Comment by jgauna** [comment]
I can't figure out what to do to get the 'init' event fired using requirejs. Can someone help me?

```
define(['jquery', 'backbone', 'marionette', 'underscore',
  'layouts/RootLayout'
], function($, Backbone, Marionette, _, RootLayout) {

  var app = new Backbone.Marionette.Application();

ons.ready(function() {
      // Working
      document.addEventListener('init', function(event) {
        // Not working
      });
});

```

**Comment by marchy** [comment]
This happens to us on Angular production builds. Works fine in debug, but page load fails with

**Comment by narangkishore98** [comment]
I found a Solution on at [Onsen Community](https://community.onsen.io/topic/3575/angular8-load-error/2)

Just have to add

`<script>
window.setImmediate = window.setTimeout;
</script>`

in head of `index.html`
