### ISSUE TITLE
Discussion before PR on ons-back-button / ons-navigator behavior

### ISSUE THREAD

**Issue by zabojad** [OnsenUI/OnsenUI#2368]
Hey @frandiox :)!

I'd like to start a little chat before submitting a PR about this: I think `ons-back-button` should be allowed to be outside of the `ons-navigator` children...

Now I've check the current implementation and see well how the current behavior is implemented:

- `ons-back-button` query select the first `ons-navigator` they find in their parents to call the `popPage()` method.

- `ons-navigator` updates the potential `ons-back-button` by calling a `updateBackButton(v)` method in `ons-page`.

- Note that `ons-back-button` have a `onClick`property allowing to override this behavior (and it's what I basically do in my app for now...).

What we just need here is a way to "link" a `ons-back-button` and a `ons-navigator` in a bi-directional way. That could be achieved by giving both a css selector string to allow them to find each others. Or... give a selector string only to the `ons-back-button` and give `ons-navigator` a mecanism to "register" all `ons-back-button` that would like to get updated on navigation stack changes...

In order to not waste time in submitting a PR that would not meet your requirements, what would you recommend / prefer here @frandiox?

**Comment by asialgearoid** [comment]
Hey @zabojad. Fran is taking a break from working on Onsen UI, so I'll be replying to Github issues from now on.

My instinct is that what you've outlined is a relatively obscure use case, as most people will keep everything inside their `ons-navigator`. I think that the `onClick` override you have mentioned is the easiest way to implement this. Is there a particular reason you feel this should be part of the library rather than a per-app override?

**Comment by zabojad** [comment]
@asialgearoid thanks for answering.

Well, I'm not sure it is such an edge case.

I'm having this situation because I have the following imbrication of ons components:
```
<ons.Page renderToolbar={renderToolbar}>
  <ons.Splitter>
      <ons.SplitterSide>
        // some side menu content
      </ons.SplitterSide>
      <ons.SplitterContent>
        <ons.Navigator>
          // .. navigator content (ons.Page components basically)
        </ons.Navigator>
      </ons.SplitterContent>
  </ons.Splitter>
</ons.Page>
```

You see the `renderToolbar` in the root Page component. There I have a ons.BackButton. And this has to control the inner Navigator. I have this structure because the header cannot "change" when the inner navigator stack changes...

I'm not sure it is such an edge case ?

**Comment by asialgearoid** [comment]
Ah, I understand. It does seem like a use case that is probably not totally uncommon. I suppose the simplest solution is to add an `id` to the `ons-navigator`. Then the `ons-back-button` would have an attribute, maybe `navigator`, where you specify the `id` of the navigator which it could control.

If you would still like to submit a PR, it would be very welcome!

**Comment by zabojad** [comment]
@asialgearoid OK, I'll PR that in the coming days...
