### ISSUE TITLE
Vue: methods missing from $ons object

### ISSUE THREAD

**Issue by kswedberg** [OnsenUI/OnsenUI#2371]
__Environment__ 

```
[Core]
    onsenui 2.9.2

[Framework]
    vue 2.5.3

[Framework binding]
    vue-onsenui 2.5.1

[Additional libraries]
    none
```

__Encountered problem__

A number of methods that are supposed to be available on the `$ons` object (as referenced at https://onsen.io/v2/api/vue/$ons.html) aren't there. Therefore, calling any of them produces an error.

__How to reproduce__

Try to call any of the following methods of the global `$ons` object:

* createAlertDialog()
* createDialog()
* createElement()
* createPopover()
* forcePlatformStyling()
* forceUIWebViewScrollFix()
* getScriptPage()
* preload()
* resolveLoadingPlaceholder()

__Possible solution__

It looks like the array of regular expressions in https://github.com/OnsenUI/OnsenUI/blob/master/bindings/vue/src/setup.js could use the addition of something like the following: 

`/^create/, /^force/, /^get/, /^preload$/, /^resolve/`

**Comment by frandiox** [comment]
@kswedberg This is just an issue in the docs, the methods shouldn't be there since they don't make sense in Vue. Perhaps we could add `forceUIWebViewScrollFix`, which was added in the last core release, but that's it :sweat_smile:

**Comment by kswedberg** [comment]
Ah, ok, that makes sense. I was wondering what the use case for some of those methods would be. I actually stumbled across the issue when trying to use `forceUIWebViewScrollFix`. I patched my local copy, but unfortunately it didn't solve my problem. Wish I could come up with a reduced test case to demonstrate the issue I'm having, because it's been vexing me for such a long time now. If I can't figure out a workaround, I'll try to post an issue soon. Thanks a lot for the quick reply.

**Comment by frandiox** [comment]
You can still use `$ons._ons.forceUIWebViewScrollFix()` but I guess it doesn't help either. UIWebView has scrolling issues hard to debug :/

**Comment by kswedberg** [comment]
Just out of curiosity, do you know if switching to WKWebView (using https://github.com/apache/cordova-plugin-wkwebview-engine) would make a difference with the scrolling problems?

**Comment by frandiox** [comment]
You can test on iOS Safari browser since it already uses WKWebView. Overall it should be better but it might add other issues related to XHR requests or something else.

**Comment by kswedberg** [comment]
good idea. thanks!

**Comment by kswedberg** [comment]
WKWebView fixed it. Thanks for nudging me in that direction!
