### ISSUE TITLE
Close speed dial menu

### ISSUE THREAD

**Issue by snazzypants** [OnsenUI/OnsenUI#2373]
__Environment__ 

```
[Core]
    onsenui 2.8.2

[Framework]
    react 16.2.0

[Framework binding]
     react-onsenui 1.9.0

[Additional libraries]
    none
   
[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1
    Desktop - Linux
    Desktop - macOS Sierra
    Desktop - Windows 10

[Browser]
    Mobile - Android WebView
    Mobile - Android Chrome 54.0.2840.85
    Mobile - iOS UIWebView
    Mobile - iOS Safari
    Desktop - Chrome 55.0.2883.75
    Desktop - Safari 10.0 (12602.1.50.0.10)
```

Is there a way to close the speed dial menu, outside of clicking again on the main Fab element?  For example, I want to close the speed dial menu when a user clicks on one of the speed dial items, or clicks/cancels away.

**Comment by frandiox** [comment]
@snazzypants Looks like there are no props for that in React bindings. You can simply use the core methods: `document.querySelector('ons-speed-dial').hideItems()` :+1:
