### ISSUE TITLE
Uncaught TypeError: Cannot read property 'attach' of undefined

### ISSUE THREAD

**Issue by zabojad** [OnsenUI/OnsenUI#2374]
__Environment__ 
```
[Core]
onsenui github master branch commit caeeb35d50ef4bf28a0a2582b712011540f46344

[Framework]
react 16.

[Additional libraries]
    none

[Platform]
    Desktop - macOS Sierra v10.12.6

[Browser]
Desktop - Chrome Version 63.0.3239.132 (Official Build) (64-bit)
```

__Encountered problem__

Error in console at startup: 
```
onsenui.js:11200 Uncaught TypeError: Cannot read property 'attach' of undefined
    at onsenui.js:11200
(anonymous) @ onsenui.js:11200
```

Checking the source, it seems to come from:
```
  // fastclick
  window.addEventListener('load', function () {
    ons.fastClick = fastclick.FastClick.attach(document.body); // that line!
```

__How to reproduce__

Install onsenUI from github master branch and implement any project with it. Issue happens at very startup...

**Comment by asialgearoid** [comment]
We recently separated FastClick into a separate repository to make it a bit easier to maintain. I think the issue here could be that it now needs to be installed in your local repo. Try running `yarn install` and see if that works.

**Comment by zabojad** [comment]
@asialgearoid if I run `npm install` it's the same right?

The onsenui npm package references `"@onsenui/fastclick": "1.1.1",` as a dependency by there is no `fastclick` in the onsenui folder so how can this work?

**Comment by asialgearoid** [comment]
@zabojad `npm install` is pretty much the same, but with we have a `yarn.lock` file which will get used if you use `yarn`. This file ensures that you're getting the exact same versions that we build with.

The `@` is important in the package name. It specifies a namespace on npm, so we can publish packages but still have them related to Onsen UI. You can see our FastClick package at https://www.npmjs.com/package/@onsenui/fastclick.

**Comment by zabojad** [comment]
`npm install` in my onsenui local repo solved the issue. Thanks @asialgearoid !
