### ISSUE TITLE
Ons-page not scrolling after button press or tapping into input

### ISSUE THREAD

**Issue by kelifine** [OnsenUI/OnsenUI#2375]
I've got a page where I have a couple text inputs, a couple buttons, and multiple checkboxes. If I click either the inputs or the buttons and then try to click away (anywhere else on the page) the page scrolls to the top then refuse to scroll anymore. I've tried e.preventDefault() and return false in the functions attached to the inputs and buttons but nothing seems to work, it doesn't even prevent the page scrolling to the top nevermind allow me to scroll again. I have not been able to reproduce this in a browser. 

__Environment__ 

[Core]
    onsenui 2.1.0

[Framework]
    none

[Framework binding]
    none

[Additional libraries]
    none
    jQuery 3.1.1

[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1
    Desktop - macOS Sierra

[Browser]
    Desktop - Chrome 55.0.2883.75

**Comment by asialgearoid** [comment]
@kelifine Does this also happen with the latest version of Onsen UI (2.9.2)?

**Comment by asialgearoid** [comment]
I am closing this issue due to a lack of a reply.
