### ISSUE TITLE
ons.notification.alert is not showing on android 6.0

### ISSUE THREAD

**Issue by GreyBlade** [OnsenUI/OnsenUI#2379]
__Environment__

Onsen UI Version:

-  2.4.0

Framework:

-  AngularJS

Framework binding:

-  1.5.8

Platform:

- Android 6.0 with Cordova 

__Encountered problem__

ons.notification.alert is not showing

__How to reproduce__
`$scope.login=function(){ons.notification.alert("Test");}`
This is not showing anything when start `cordova run android` and click on the button that calls for login

**Comment by asialgearoid** [comment]
That should work fine. Are you sure that the `login` function itself is being called? Try putting a `console.log('Test')` in there to see if it is being called.

**Comment by GreyBlade** [comment]
It's working fine on browser, but I think its not OnsenUI problem, AngularJS is not working on mobile, thats the problem.

**Comment by asialgearoid** [comment]
Ah, OK! I'll close the issue, but if it turns out to be related to Onsen UI, feel free to re-open it.
