### ISSUE TITLE
Onsen-carousel-cover for Onsen v.2?

### ISSUE THREAD

**Issue by rashearth** [OnsenUI/OnsenUI#2385]
Hi 
Thank you for the Wonderful software you have made!!
I really love this!

By the way, I have one question for the onsen-carousel function.
Is "onsen-carousel-cover "only for Onsen v.1?
I really need this function for Onsen v.2 , but could not activate it correctly.
If yes, could you please tell me how I could insert some words or image above the carousel page?

Thank you & Regards,
noguchi

**Comment by puku0x** [comment]
Hi

You can use a `<div>` with `position: absolute` instead of `onsen-carousel-cover` in Onsen UI 2 like https://github.com/OnsenUI/vue-onsenui-kitchensink/blob/master/src/pages/Carousel.vue#L57-L65

Cheers,
puku

**Comment by rashearth** [comment]
puku-san

woww!!! it worked!!!!
Thank you very much!
I spent like 30h working on <ons-carousel-cover> , I'm happy:)

Best Regards,
rash earth
