### ISSUE TITLE
Wrong placement of ons-popover

### ISSUE THREAD

**Issue by rcpinheiro** [OnsenUI/OnsenUI#2386]
__Environment__

Onsen UI Version: 2.9.2
Framework: Javascript
Additional libraries: jQuery 3.3.1

Platform:
Window 7 Chrome

__Encountered problem__
The horizontal placement of ons-popover is wrong if the target is inside a page that doesn't fill all the of window horizontal space.
It seems ons-popover doesn't take this into account:
.page {
	width:100%;
	**max-width: 1080px;**
}

__How to reproduce__
If the page width is less than max-width value, all is good:
![image](https://user-images.githubusercontent.com/3802348/38265586-387f5e1e-376e-11e8-9c54-bc47f9d60cdc.png)

If the page width is greater then popover is placed wrongly:
![image](https://user-images.githubusercontent.com/3802348/38265568-2dc82c26-376e-11e8-9f95-d74bd14f315c.png)

**Comment by asialgearoid** [comment]
Thanks for the report, @rcpinheiro. There is actually a waiting pull request to fix this (https://github.com/OnsenUI/OnsenUI/pull/2348), but it has not yet been tested. I will take a look at it over the next few days.
