### ISSUE TITLE
Getting sNavigator error on declaring variable on both app.js and index.html How can I resolve this error

### ISSUE THREAD

**Issue by swanandj91** [OnsenUI/OnsenUI#2387]
This is my app.js file

  case "MenuCategory1":
				  
						       
			       setTrackView("sss");
			       
			       setStorage("item_count",data.details.total)			       
			       var options = {
				      animation: 'none',
				      onTransitionEnd: function(){				      	  
				      	 showCartNosOrder();
				      } 
				   };
				   console.log(options);
				//   alert("scan element");
**getting error**	-->			   sNavigator.pushPage("menuItem1.html", options);	
				  // sNavigator.pushPage("menuItem.html", options);
				 //sNavigator.pushPage("menuItem1.html", options);*/
				break;
My **Index.html**
<script type="text/ons-template" id="menuItem1.html" var="sNavigator">
 <ons-navigator id="menu_tm" page="menuItem1.html" var="sNavigator">
<ons-page id="page-menubycategoryitem">
   <ons-toolbar>        
     <div class="left"><ons-back-button id="menuitem-back-button"></ons-back-button></div>     
     <div class="center white"><span id="search-text"></span></div>           
      <div class="right">       
        <ons-toolbar-button>
        <span class="notification cart-num" onclick="showCart();" >0</span>
        <ons-icon icon="fa-shopping-cart" onclick="showCart();" class="cart"></ons-toolbar-button>
     </div>
   </ons-toolbar>     
   <div class="orange-header">
      <ons-row >
        <ons-col width="40%">
           <div class="logo-wrap logo-non-auto" >           
           </div>
        </ons-col>
        <ons-col class="text-right">
           <div class="rating-stars" data-score=""></div>           
           <p class="restauran-title concat-text white"></p>           
        </ons-col>
      </ons-row>
   </div> 
   <ons-scroller id="menu-list1">      
        <ons-list id="lazy-parent" >
	      <ons-list-item ons-lazy-repeat="lazyItem1" style="padding:0;" modifier="tappable" class="list-item-container lazy-list restaurant-list">      
	      </ons-list-item>
	    </ons-list>     
   </ons-scroller>
   
</ons-page>
</ons-navigator> 
</script>

**sNavigator** error I am facing since long time what's wrong in my code Please help me on this Angular js error

**Comment by puku0x** [comment]
Hi

Do you mean you have an `one-navigator` named `sNavigator`, and you want push the page `menuItem1.html` ?

I think you already have "sNavigator" variable in your 'index.html', like this.

```
<one-navigator page="<your-root-page.html>" var="sNavigator"></ons-navigator>
```

Therefore, you faced the error.
(I don’t recommend using `var` in `script` tags, though)

Here, you have three solutions.

1. Remove `var` from your "text/one-template"

2. Use `one-template` tag instead of `script` tag

3. Make a `menuItem1.html` in the same directry of `index.html`

In any case, I strongly recommend reading official Onsen UI reference  and starting from a minimal sample.

Regards,
puku

**Comment by swanandj91** [comment]
Thank You Puku for your quick response but I tried this options still no effect
My Error:
app.js?ver=1.0:1122 Uncaught ReferenceError: sNavigator is not defined
    at Object.success (app.js?ver=1.0:1122)
    at j (jquery-1.11.3.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.11.3.min.js:2)
    at x (jquery-1.11.3.min.js:5)
    at HTMLScriptElement.b.onload.b.onreadystatechange (jquery-1.11.3.min.js:5)

**Comment by swanandj91** [comment]
Hi Puku ,
**how to create dynamic list on onsen ui from database on button click**
Please reply soon

**Comment by puku0x** [comment]
@swanandj91

You can use `ng-repeat` to create dynamic list if you are using Onsen UI with AngularJS.

**Comment by swanandj91** [comment]
Can You please send me the code for that , I tried this option

**Comment by puku0x** [comment]
@swanandj91
Here’s a sample of `ng-repeat`.
https://codepen.io/puku0x/pen/eMQXgj

**Comment by asialgearoid** [comment]
@swanandj91 For help with using Onsen UI, try posting on the [Onsen UI Community Forum](https://community.onsen.io/). The Github issues are mainly for bugs in the library itself. Thanks for using Onsen UI!
