### ISSUE TITLE
Add ons-segment for Angular 2 binding

### ISSUE THREAD

**Issue by asialgearoid** [OnsenUI/OnsenUI#2390]
Work for this is already partially complete at https://github.com/OnsenUI/OnsenUI/tree/ngx-onsenui-420

**Comment by asialgearoid** [comment]
@puku0x Do you think this is something you would be able to do? I think you have a much better understanding of Angular than the rest of us. Obviously there is no real rush with it, but it would be good for the binding to have the same features as the core.

**Comment by puku0x** [comment]
@asialgearoid Sure! I will take a look.

**Comment by asialgearoid** [comment]
It might be easier to start from scratch, rather than looking at the partially completed branch. I'm not sure if that branch will be very useful.
