### ISSUE TITLE
<ons-input id="username" placeholder="Username" float> unable to change the floated placeholder color and underbar  color

### ISSUE THREAD

**Issue by VinodkumarPachimadla** [OnsenUI/OnsenUI#2393]
__Environment__

Onsen UI Version:

- 

Framework:

- 

Framework binding:

- 

Additional libraries:

- 

Platform:

- 

__Encountered problem__

__How to reproduce__

**Comment by asialgearoid** [comment]
Hi @VinodkumarPachimadla, could you reproduce this on the [Onsen UI Playground](https://onsen.io/playground/) and export it to Codepen?
