### ISSUE TITLE
Blank area is shown in bottom of page when using WKWebView

### ISSUE THREAD

**Issue by puku0x** [OnsenUI/OnsenUI#2399]
__Environment__

Onsen UI Version:

- 2.9.2

Framework:

- Vue 2.5.16

Framework binding:

- vue-onsenui 2.5.1

Additional libraries:

- vuex 3.0.1

Platform:

- iOS 11.3

__Encountered problem__

Blank white area is shown in bottom of page when using WKWebView with `viewport-fit=cover`.
However, the blank area is disappeared after rotating display.

<img src="https://user-images.githubusercontent.com/2607019/38778385-e29c7740-40f3-11e8-9b8c-742bd69ef00e.png" width="250"> <img src="https://user-images.githubusercontent.com/2607019/38778395-14baaaf8-40f4-11e8-8670-931847a54827.png" width="250">

__How to reproduce__

1. Create a Onsen UI + Cordova for iPhone X project
   You can clone https://github.com/asial-matagawa/vue-onsenui-cordova-iphonex
2. `cordova plugin add cordova-plugin-wkwebview-engine`
3. Add `<preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />` to `config.xml`
4. `cordova platform add ios`
5. `cordova run ios`

**Comment by asialgearoid** [comment]
@puku0x This is actually a bug with the plugin, where it is not setting the window height correctly. It can be reproduced without OnsenUI:

1. `cordova create test`
2. `cordova plugin add cordova-plugin-wkwebview-engine`
3. `cordova platform add ios`
4. Add a storyboard splash screen to config.xml for iOS, and add `viewport-fit=cover` to the viewport meta tag
5. `cordova run ios`

Try inspecting it from Safari. As you hover over the name of the device in Safari's menu, you will see it outline the document size, showing the empty space at the bottom. You can also check `window.innerHeight` in the developer console, and it will be `734`. After rotating twice, you can check it again and see it is now correct at `812`.

There is already [a bug report on the Cordova issue tracker](https://issues.apache.org/jira/browse/CB-13987). I suggest commenting there to add your voice to the issue.
