### ISSUE TITLE
[Violation] Handling of 'touchmove' input event was delayed for 1524227035145 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responsive.

### ISSUE THREAD

**Issue by GreyBlade** [OnsenUI/OnsenUI#2402]
__Environment__

Onsen UI Version:

- 2.4.0

Framework:

- angular@1.5.8

Framework binding:

- angular-onsenui.js for onsenui - v2.4.0

Additional libraries:

- Loading Spinner (for charts)

Platform:

- Android 6.1 Cordova

__Encountered problem__

I have a splitter side with some items on it, when I try to scroll down sometimes it does with out a problem, but sometimes i try to scroll down or up but nothing happens

__How to reproduce__

Don't know how to reproduce, but this is the error i get `[Violation] Handling of 'touchmove' input event was delayed for 1524227035145 ms due to main thread being busy. Consider marking event handler as 'passive' to make the page more responsive.`

**Comment by asialgearoid** [comment]
@GreyBlade Could you try this with the latest Onsen UI? Recently we changed most of the touch listeners to be passive, so it may fix this issue for you.

**Comment by asialgearoid** [comment]
Closing due to lack of a reply. Please re-open if this is still an issue.
