### ISSUE TITLE
 Make ons-toast multline-capable

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#2405]
Currently, the Toast is extremley limited in it's function. On small devices, there is only space for a fraction of text. This has very limited use cases and the "length" of text varies from device to device, so I really can't rely on it showing important notes to the user.

Could you please provide at least an option "multiline: true" so I could deactivate ellipsis and just expand on auto height? Thanks! @frandiox

**Comment by Hirbod** [comment]
For now, I changed the CSS and it's working for me. I don't see any reason for limiting toasts to 1-line.

**Comment by asialgearoid** [comment]
I'm not sure either why we limit toasts to one line. The [Material spec](https://material.io/guidelines/components/snackbars-toasts.html#snackbars-toasts-usage) shows multiline in use too, so we should support that. I'll test your CSS and see if that is sufficient. Thanks for the example!

By the way, Fran is no longer working on Onsen UI. @emccorson and I are maintaining it in his place now.

**Comment by Hirbod** [comment]
@asialgearoid thanks for keeping up. Sad to hear that Fran isn't on board, was a good and fast guy :)
But I am sure you guys doing great also. Thanks!
