### ISSUE TITLE
waiting for a new release, is there an expected date?

### ISSUE THREAD

**Issue by ccloveaa** [OnsenUI/OnsenUI#2411]
__Environment__

Onsen UI Version:

- 

Framework:

- 

Framework binding:

- 

Additional libraries:

- 

Platform:

- 

__Encountered problem__

__How to reproduce__

**Comment by asialgearoid** [comment]
Hey @ccloveaa, we have a few more fixes we want to get in the next release, but we're aiming to get 2.10.0 out in the next 2 or 3 weeks.
