### ISSUE TITLE
'Button' component doesn't apply "disabled" attribute

### ISSUE THREAD

**Issue by champunes** [OnsenUI/OnsenUI#2412]
__Environment__

- onsenui@2.9.2

Framework:

- react@16.3.2

Framework binding:

- react-onsenui@1.10.0

Platform:

- Debian Jessie Chrome Version 64.0.3282.140
- Node v8.9.4
- Webpack v4.6.0

__Encountered problem__

I'm trying to set the "disabled" attribute using a state's property. But when I pass a boolean 'true' value, even when I can see with Chrome Dev Tools that the <ons-button> component in react has a disabled=''" assigned, the compiled DOM <ons-button> element has not. And of course, the button element is not disabled.

__How to reproduce__

If I set the disabled attribute using a boolean value,
```
<Button
    modifier="large"
    onClick={ this.send }
    disabled >
    Send
</Button>
```

the React component generated as I see in Chrome Dev Tools is:
```
<Button modifier="large" onClick=fn() disabled=true> == $r
    <ons-button modifier="large" onClick=fn() disabled="">Send</ons-button>
</Button>
```

the compiled HTML element generated is:
`<ons-button modifier="large" class="button--large button">Send</ons-button>`

---------------------------------------------------------------------------------------------------------------------------

I've tried setting a string 'true' value to disabled, and it works fine, 
```
<Button
    modifier="large"
    onClick={ this.send }
    disabled='true' >
    Send
</Button>
```

the React component generated as I see in Chrome Dev Tools is:
```
<Button modifier="large" onClick=fn() disabled="true">
    <ons-button modifier="large" onClick=fn() disabled="true">Send</ons-button>
</Button>
```
the compiled HTML element generated is:

`<ons-button modifier="large" class="button--large button" disabled="true">Enviar</ons-button>`

but I receive this warning:
```
Warning: Failed prop type: Invalid prop `disabled` of type `string` supplied to `Button`, expected `boolean`.
    in Button (at SuggestionMailbox.jsx:70)
```

**Comment by asialgearoid** [comment]
I believe this is actually a bug in React, not Onsen UI. A similar issue was reported in https://github.com/OnsenUI/OnsenUI/issues/2403. This user ended up reporting the issue to the React team at https://github.com/facebook/react/issues/12694, and fixed it there. A new version of React has not been released since, so I recommend rolling back your version until then.
