### ISSUE TITLE
Angular1 | Tabbar issue: Using ng-repeat breaks page templates

### ISSUE THREAD

**Issue by JstnPwll** [OnsenUI/OnsenUI#2413]
__Environment__

  
```
[Core]
  onsenui latest
  
[Framework]
  angular1 1.5.5

[Framework binding]
 angular1-onsenui latest

[Platform]
  Desktop - Windows 10 64-bit

[Browser]
  Desktop - Chrome 66.0.3359.139 on Windows 10 64-bit
```

__Encountered problem__
Using `ng-repeat` on an `<ons-tab>` element breaks angular template parsing on the tab pages.
I noted that there is an error on the console, which comes from [Line 277 of ons-tab.js](https://github.com/OnsenUI/OnsenUI/blob/13ba1b046d8cc6fa4a7b4f419a63a0d4e322dff6/core/src/elements/ons-tab.js#L277). I think [Tabbar.rewritables.ready](https://github.com/OnsenUI/OnsenUI/blob/13ba1b046d8cc6fa4a7b4f419a63a0d4e322dff6/bindings/angular1/directives/tabbar.js#L124) is being called before the repeated `<ons-tab>` children are attached to the DOM.

__How to reproduce__
Add `ng-repeat` to `<ons-tab>` and try using {{ template markup }} in the tab page template.

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<ons-page ng-controller="TabbarController">
  <ons-toolbar>
    <div class="center">{{title}}</div>
  </ons-toolbar>

  <ons-tabbar swipeable position="auto" ons-prechange="updateTitle($event)">
    <ons-tab ng-repeat="tab in tabs track by $index" page="tab.html" label="Tab {{ tab }}" icon="ion-home, material:md-home" badge="7"></ons-tab>
  </ons-tabbar>
</ons-page>

<template id="tab.html">
  <ons-page id="Tab{{ tab }}">
    <p style="text-align: center;">
      This is page {{ tab }}.
    </p>
  </ons-page>
</template>
```

- __JS__

```javascript
ons.bootstrap()
  .controller('TabbarController', function($scope) {
    $scope.title = 'Tab 1';
    $scope.tabs = [1, 2];
    $scope.updateTitle = function($event) {
      $scope.title = angular.element($event.tabItem).attr('label');
    };
  });
```

**Comment by JstnPwll** [comment]
For the moment I've worked around this by modifying [Tabbar.rewritables.ready](https://github.com/OnsenUI/OnsenUI/blob/13ba1b046d8cc6fa4a7b4f419a63a0d4e322dff6/core/src/elements/ons-tab.js#L333) in ons-tab.js to the following:

        TabbarElement.rewritables.ready(tabbar, function () {
            if(tabbar.tabs.length){ //Don't attempt to load a page if there are no tabs
              var pageTarget = _this4.page || _this4.getAttribute('page');
              if (!_this4.pageElement && pageTarget) {
                var parentTarget = tabbar._targetElement;
                var dummyPage = util$1.create('div', { height: '100%', width: '100%', visibility: 'hidden' });
                parentTarget.insertBefore(dummyPage, parentTarget.children[index]); // Ensure position
                setTimeout(function(){ _this4._loadPageElement(parentTarget, pageTarget).then(deferred.resolve); }) //Fix ng-repeat tab issue
                return;
              }
              return deferred.resolve(_this4.pageElement);
            }
          });

Obviously using `setTimeout` is a hack, but this is what I'll be using until there's a legitimate fix.

**Comment by asialgearoid** [comment]
@JstnPwll This looks to be related to https://github.com/OnsenUI/OnsenUI/issues/2272. As Fran mentioned in that issue, ons-tab isn't designed to be dynamically generated using a directive like ng-repeat, so it can cause unexpected behaviour. I will see if this is something we can change easily.

**Comment by JstnPwll** [comment]
@asialgearoid Interesting. The reason I found this issue is that I'd used ng-repeat on tabs with a prior version of OnsenUI; when I migrated to the newer version it broke.

**Comment by asialgearoid** [comment]
Oh that's interesting. What version were you using before? Maybe I can take a look through the commit history and see if I can track down what changed the behaviour.

**Comment by JstnPwll** [comment]
Looks like it was 2.0.3.

**Comment by asialgearoid** [comment]
Hmm, that is a pretty old version - a whole lot has changed since then, so it's probably not possible to track down when the old behaviour changed.

The issue is that the Tabbar is not designed to have its number of tabs changed after it is set up. In this case, I think that the Angular binding probably calls the `TabbarElement.rewritables.ready` too early. We would need to wait until after the tabs have been generated by `ng-repeat`.

Unfortunately we don't have time at the moment to do this, but PRs are very welcome.
