### ISSUE TITLE
React - LazyList - why 'calculateItemHeight' prop is required?

### ISSUE THREAD

**Issue by avalanche1** [OnsenUI/OnsenUI#2414]
__Environment__

Onsen UI Version:

- 2.9.2

Framework:

- React 16

Framework binding:

- react-onsenui 1.10.0

__Question__
I dont understand - why 'calculateItemHeight' prop is a required prop? Can't I just set row height with css?

**Comment by asialgearoid** [comment]
@avalanche1 The purpose of a lazy list is to allow fast scrolling of thousands of items. The way we keep it high performance, we don't put thousands of elements in the DOM at once, but only the ones that are visible on screen right now (maybe about ten).

To help keep the scrolling feel normal, and to size the scrollbar correctly, we need to know the height of each item. Setting the height in CSS will work for the ten items that are visible (and thus actually in the DOM), but not all the others that are not on screen. They don't exist in the DOM, so there is no CSS height to calculate. This is why `calculateItemHeight` is required - it lets you specify the height of the items without them needing to be in the DOM. If you don't want to use this, you will need to use [List](https://onsen.io/v2/api/react/List.html) instead, where all the elements are in the DOM, and you can use CSS heights. Unless you have thousands of items, this will be perfectly fine.
