### ISSUE TITLE
ons Input Value document.getElementById

### ISSUE THREAD

**Issue by GuilhermeLessa** [OnsenUI/OnsenUI#2417]
`<p><ons-input id="senha" modifier="underbar" placeholder="senha" float type="password"></ons-input></p>`

`document.getElementById('senha').value` dont return value in android (cordova), but in browser works!

Can you help me please?

**Comment by GuilhermeLessa** [comment]
Last Code:
`<p><ons-input input-id="senha" modifier="underbar" placeholder="senha" float type="password"></ons-input></p>`

CONSOLE ERRO: https://ibb.co/b7GpES
Dont have 2 id=senha, wtf?

**Comment by emccorson** [comment]
I tried to replicate this but it works fine for me, so I'm not sure this is a problem with Onsen.

If you are still having problems, you can make post at [the Onsen UI forum](https://community.onsen.io/category/2/onsen-ui) with a code sample that reproduces the problem, or if you think it's a cordova problem try at [the cordova slack](https://cordova.slack.com).

**Comment by GuilhermeLessa** [comment]
Clean input with js test:

`<input type="text" id="senha"><button onclick="logout()"></button>`
```
function logout() {
    document.getElementById('senha').value = '';
}
```

that works if input into body, but dont work if input into body > into  `<ons-page>`
As if document.getElementById  was lost in DOM?

**Comment by GuilhermeLessa** [comment]
I tested .load only with native input and it worked! page.load is not the problem.
The problem is input into `<ons-splitter-content> <ons-page>`. document.getElementById can not get the input into "ons" elements.

**Comment by GuilhermeLessa** [comment]
RESOLVED!

You need page = "initialPage.html" on `<ons-splitter-content>` for a correct DOM init, and document.getElementById to work.

I wanted to make this control with page.load (), but the first page should be placed in the content tag to work fine.
