### ISSUE TITLE
Toolbar modifier = transparent appears white in iPhone X

### ISSUE THREAD

**Issue by snazzypants** [OnsenUI/OnsenUI#2422]
__Environment__

Onsen UI Version:

- 2.9.2

Framework:

- React 16.2

Framework binding:

- React 1.10.0

Additional libraries:

- 

Platform:

- iPhone X

__Encountered problem__

Toolbar and notch area are white (instead of the background color of the page) when toolbar modifier="transparent"

__How to reproduce__

**Comment by asialgearoid** [comment]
@snazzypants It is possible that when you are setting the toolbar to be transparent, it is then showing the body, which would be white by default. The page colour will only apply to the page content, which does not go underneath the toolbar.

If this is not the case, could you reproduce it on the [Playground](https://onsen.io/playground/?framework=vanilla&category=reference&module=toolbar) so I can take a look?

**Comment by snazzypants** [comment]
@asialgearoid  I've been setting the page background using the `.page__background` class.  I also override the toolbar color using the `.toolbar `class, so in order to use the transparent modifier, I also have to set` .toolbar--transparent` background color to transparent as well.  These 3 rules are reflected in the pen:

https://codepen.io/thecrusher/pen/BxXrRX

This works fine for everything, except when using the iPhoneX mode. In Chrome, you can inspect the above pen and switch to mobile view and see the behavior.

**Comment by asialgearoid** [comment]
@snazzypants Thanks for the example. The white you're seeing is the body colour, which you can see by changing the body's colour and seeing it through the toolbar. Looking into the code, it appears that the iPhone X mode is the only one actually behaving as it should. The toolbar should not overlay the page unless you specifically tell it to. So, the toolbar should always be white in this case, not just in iPhone X mode. I'll need to check exactly why this behaviour is inconsistent.

Anyway, to get the toolbar working as you expect it, you need to add the modifier `cover-content`, as below. It is in [the ons-toolbar docs](https://onsen.io/v2/api/js/ons-toolbar.html#modifiers), but not very obvious.

```html
<ons-toolbar modifier="transparent cover-content">
```

**Comment by snazzypants** [comment]
Thanks! I do remember seeing that modifier. I had tried using it in conjunction with the transparent modifier, but it didn't seem to make any difference, so I stopped using it. I guess I was wrong :)  Thanks again.

**Comment by snazzypants** [comment]
I remember now another (more important reason) why I didn't end up using the cover-content option. If you have a page that needs to scroll, transparent + cover-content really does make the toolbar transparent, and overlay content. I suppose that sounds obvious, but I was using the transparent modifier to just match the color of the toolbar to the color of the page.  In many cases I still have text in the "center" of the toolbar, which makes the true transparent + cover-content option undesirable (causes overlapping content).

**Comment by asialgearoid** [comment]
Ah I understand what you mean. Fixing this is a bit awkward since the current default behaviour isn't quite what might be expected. I'll take a look and see if there is a workable solution. The actual CSS that causes it is in this file: https://github.com/OnsenUI/OnsenUI/blob/b9aa43af710ed2afaeca2bd96a2d64ae19ab6ce4/css-components/src/iphonex-support/combination.css. 

In the meantime I would suggest overriding this in your app's CSS based on the CSS rules in the file above.
