### ISSUE TITLE
popPage() on swipe-left instead of opening sliding menu

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#243]
Hi,

I have a sliding menu and everything is working fine for now. But there is one behavior I can't find out. Is it possible to get to the last page with a swipe? Of course I could bind a swipe event on the body to popPage(), but that would be a fake (cause it does not follow the finger like when it opens the sliding box).

Is this feature available?

**Comment by Hirbod** [comment]
@argelius @anatoo will this come anytime?
It's the last little part from making iOS feel real native.

**Comment by alshdavid** [comment]
I am currently facing the same issue. What I am doing is using an onsen carousel and using the on-overflow event to trigger a popPage(). The problem I am facing right now is how to do it after a certain distance. Looking at combining it with Angular's ng-swiperight function

**Comment by Hirbod** [comment]
nice @argelius - closed without any Information?

**Comment by Hirbod** [comment]
@argelius @frandiox is swipe to pop implemented in OnsenUI 2? Could not find any documents about this

**Comment by frandiox** [comment]
@Hirbod No, but swiping tab bar and swipe to pop are the next features we will target if nothing comes up :+1:

**Comment by Hirbod** [comment]
Thanks, can't wait for this feature. Was about to switch to Ionic but came back as I just realized how much I do love Onsen :)

**Comment by frandiox** [comment]
@Hirbod Try 2.5.0 :+1: :tada:
