### ISSUE TITLE
ons-tab-bar  not  work well such as click 

### ISSUE THREAD

**Issue by happyi** [OnsenUI/OnsenUI#2438]
__Environment__

Onsen UI Version:
2.10.1

Framework:
angularjs1.4.9

such as the official demo。the click doesn't work.
`<html ng-app="app">`
`<head>`
`    <link rel="stylesheet" href="css/onsenui-core.min.css"/>`
`    <link rel="stylesheet" href="css/onsen-css-components.min.css"/>`
`    <script src="lib/angular.min.js" type="text/javascript"></script>`
`    <script src="lib/onsenui.min.js" type="text/javascript"></script>`
 `   <script src="lib/angular-onsenui.min.js" type="text/javascript"></script>`
 `   <script>`
`      var app= angular.module('app', ['onsen']);`
`    </script>`
`</head>`
`<body>`

`<ons-page >`
`    <ons-tabbar >`
 `       <ons-tab page="tab1.html" label="Tab 1" icon="ion-home, material:md-home" badge="7" active>`
`        </ons-tab>`
 `       <ons-tab page="tab2.html" label="Tab 2" icon="md-settings" active-icon="md-face">`
 `       </ons-tab>`
`    </ons-tabbar>`
`</ons-page>`

`<template id="tab1.html">`
`    <ons-page id="Tab1">`
``
`        <ons-button ng-click="alert('aaaa')">Click</ons-button>`
``
`    </ons-page>`
`</template>`
``
`<template id="tab2.html">`
`    <ons-page id="Tab2">`
`<ons-button ng-click="alert('bbb')">Click2</ons-button>`
``
`   </ons-page>`
`</template>`
`</body>`
`</html>`

**Comment by puku0x** [comment]
@happyi 
You need a controller when you use `ng-click`.
https://codepen.io/puku0x/pen/WyQVdW

Moreover, I recommend using `ons.notification.alert()` instead of `alert()`.

Cheers,
puku

**Comment by happyi** [comment]
it  works when boot like  
`var app = ons.bootstrap('app', ['onsen'])` 
will not work when boot like
`var app = angular.module('app', ['onsen']);`
