### ISSUE TITLE
I am working on Angular5 and using Tabbar from OnsenUI all the pages are attached properly but the tabbar click is not working.and throwing the error

### ISSUE THREAD

**Issue by NeerajKumar31** [OnsenUI/OnsenUI#2439]
__Environment__

Onsen UI Version:

- 

Framework:

- 

Framework binding:

- 

Additional libraries:

- 

Platform:

- 

__Encountered problem__

__How to reproduce__

**Comment by NeerajKumar31** [comment]
I am working on Angular5 and using Tabbar from OnsenUI all the pages are attached properly but the tabbar click is not working.and throwing the error 
Error: Uncaught (in promise): TypeError: prevTab.pageElement._hide is not a function
_onPreChange@webpack-internal:///./node_modules/onsenui/js/onsenui.js:30125:34
_changeTo@webpack-internal:///./node_modules/onsenui/js/onsenui.js:15248:31
setActiveIndex@webpack-internal:///./node_modules/onsenui/js/onsenui.js:15067:16
setActiveTab/<@webpack-internal:///./node_modules/onsenui/js/onsenui.js:30298:16
ZoneDelegate.prototype.invoke@webpack-internal:///./node_modules/zone.js/dist/zone.js:388:17
onInvoke@webpack-internal:///./node_modules/@angular/core/esm5/core.js:4965:24
ZoneDelegate.prototype.invoke@webpack-internal:///./node_modules/zone.js/dist/zone.js:387:17
Zone.prototype.run@webpack-internal:///./node_modules/zone.js/dist/zone.js:138:24
scheduleResolveOrReject/<@webpack-internal:///./node_modules/zone.js/dist/zone.js:872:29
ZoneDelegate.prototype.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:421:17
onInvokeTask@webpack-internal:///./node_modules/@angular/core/esm5/core.js:4956:24
ZoneDelegate.prototype.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:420:17
Zone.prototype.runTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:188:28
drainMicroTaskQueue@webpack-internal:///./node_modules/zone.js/dist/zone.js:595:25
ZoneTask.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:500:21
invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:1540:9
globalZoneAwareCallback@webpack-internal:///./node_modules/zone.js/dist/zone.js:1566:17

Stack trace:
resolvePromise@webpack-internal:///./node_modules/zone.js/dist/zone.js:814:31
scheduleResolveOrReject/<@webpack-internal:///./node_modules/zone.js/dist/zone.js:877:17
ZoneDelegate.prototype.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:421:17
onInvokeTask@webpack-internal:///./node_modules/@angular/core/esm5/core.js:4956:24
ZoneDelegate.prototype.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:420:17
Zone.prototype.runTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:188:28
drainMicroTaskQueue@webpack-internal:///./node_modules/zone.js/dist/zone.js:595:25
ZoneTask.invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:500:21
invokeTask@webpack-internal:///./node_modules/zone.js/dist/zone.js:1540:9
globalZoneAwareCallback@webpack-internal:///./node_modules/zone.js/dist/zone.js:1566:17
core.js:1448

**Comment by NeerajKumar31** [comment]
Please give me a solution ASAP

**Comment by NeerajKumar31** [comment]
my mail id is prabhusri51@gmail.com

**Comment by asialgearoid** [comment]
@NeerajKumar31 Please fill out the template as in the original post so I can have a better idea of what's going on (Onsen UI version, binding version etc.)
