### ISSUE TITLE
angular 1 ng-true-value and ng-false-values not working

### ISSUE THREAD

**Issue by J261** [OnsenUI/OnsenUI#2440]
ons-checkbox not works with ng-true-value or ng-false-values and ng-model, just set true or false.

onsenui v2.9.2 - 2018-02-16
AngularJS v1.6.9

**Comment by asialgearoid** [comment]
@J261 Thanks for the report. I suspect we have never supported these attributes. Unfortunately I won't have time to fix this at the moment, but PRs are very welcome!
