### ISSUE TITLE
Updating ionicons

### ISSUE THREAD

**Issue by brunobg** [OnsenUI/OnsenUI#2441]
Any chance to update IonIcons? It is up to version 4.1.2 already. If there is any workaround to easily override it, it would be interesting to document. Thanks!

__Environment__

Onsen UI Version:
- 2.10.1

**Comment by brunobg** [comment]
For reference to other people, add `ionicons` to your package.json and add this postinstall script to copy it over onsen's:

``    "postinstall": "cp node_modules/ionicons/dist/css/* node_modules/onsenui/css/ionicons/css/; cp node_modules/ionicons/dist/fonts/* node_modules/onsenui/css/ionicons/fonts/;"
``

**Comment by clemens** [comment]
Actually, there's a much easier way to do this. All you need to do is manually import ionicons into your webpack and then import onsenui-core instead of onsenui like so:

``` js
import 'ionicons/dist/css/ionicons.css';
import 'onsenui/css/onsenui-core.css';
```
