### ISSUE TITLE
Core | Lazy-repeat issue: Items not added to DOM under various conditions

### ISSUE THREAD

**Issue by mrphuzz** [OnsenUI/OnsenUI#2443]
__Environment__

  
```
[Core]
  onsenui latest
  
[Platform]
  Desktop - Windows 8.1 64-bit

[Browser]
  Desktop - Chrome 66.0.3359.181 on Windows 8.1 64-bit
```

__Encountered problem__
  I expect that when using a lazy repeat and I add an item to the data set, and refresh the list, the new item, if it should be visible, will be added to the DOM.  This does not work as expected, and there appears to be multiple behavioral issues.

__How to reproduce__
  There are several ways to cause errors to occur.

- Case 1: Create a lazy repeat with a data set of 5 items.  Ensure the view port is tall enough that scroll bar is not visible.  Add an item to the data set (in my case, increment the `count` variable), then `.refresh()` the list.  You can observe in the console log that delegation is processed and it knows there are 6 items, but `createItemContent` is executed only 5 times and nothing is added to the DOM.  Then resize (shrink) the playground view port so that the scrollbar appears.  Then scroll down.  The newly added item is now added to the DOM at the end and is visible.  Expected: the newly added item would be added to the DOM, at the end, without having to shrink the view port and scrolling down (assuming, of course, that the item should be inserted within the visible DOM range).

- Case 2: Change the initial count to 25 so that a scrollbar is visible.  Scroll to the bottom and you will see "Item 24".  Add an item to the data set, as in Case 1, and delegation is processed.  The item doesn't appear to be added to the DOM (as seen in F12).  Scroll up the lazy list just a little bit, either by mouse wheel or clicking and dragging the scrollbar.  The view port jumps far up into an area of white space.  Scroll down a little bit until you see list items and you'll notice that Item 25 is at the top.  Expected: The delegation would cause the newly added item to be placed in the DOM at the end of the list and there not be a huge chunk of white space above the first list item.  It is expected that scrolling up after adding an item to the data set wouldn't cause white space to occur and the item placed at the top of the list.

- Case 2b: Perform steps as in Case 2, but instead of remaining scrolled all the way at the bottom, scroll up a little bit before adding the new item.  You can then observe two possible scenarios.  If you scroll down after adding the item, it will then appear at the bottom of the list.  If you instead scroll up after adding the item, the "white space" issue will occur as in Case 2. Expected: The item should be added to the DOM without having to scroll down to see it, assuming it would be within the range of items that are calculated to be in the DOM.  No "white space" issues should occur.

- Case 3: Change initial count to 0 (zero).  Resize the view port to be tall enough that 2 items will not cause a scrollbar to appear.  Add an item to the data set as in Case 1.  The item appears.  Add another item as in Case 1.  The item appears.  Add 5 more items.  They do NOT appear and are not inserted into the DOM.  Shrink the view port so that a scrollbar appears.  Scroll down and you then see the newly added 5 items.  You can then manipulate the scroll position and observe the behavior as in Case 2 when you add more items.  Expected: Adding items to a list with no items would add the items to the DOM when the delegation is processed.

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<ons-page>
	<ons-toolbar>
		<div class="center">Lists</div>
	</ons-toolbar>

	<ons-list>
		<ons-lazy-repeat id="infinite-list"></ons-lazy-repeat>
	</ons-list>
  
	<ons-fab position='bottom right' onclick="add();">
		<ons-icon icon='md-plus'></ons-icon>
	</ons-fab>
</ons-page>
```

- __JS__

```javascript
var count = 5;
var infiniteList;

console.clear();

ons.ready(function () {
	infiniteList = document.getElementById('infinite-list');

	infiniteList.delegate = {
		createItemContent: function (i) {
			console.log("createItemContent: "+i);
			return ons.createElement('<ons-list-item>Item ' + i + '</ons-list-item>');
		},
		countItems: function () {
			console.log("countItems: " + count);
			return count;
		}
	};

	infiniteList.refresh();
});

function add() {
	count++;
	console.log("added: " + count);
	infiniteList.refresh();
}

```

**Comment by asialgearoid** [comment]
Thanks for the detailed report! I am able to reproduce the issue you are describing. I haven't worked much with `ons-lazy-repeat`, but as far as I know, it was not really originally developed to handle dynamic content. However, a lot of users do want to use it that way, so we should improve that functionality. I will take a look and see what I can do here.

**Comment by asialgearoid** [comment]
I have fixed this, and it works now for all your cases. I have added some more unit test cases so that hopefully this will be more resilient in the future.

**Comment by mrphuzz** [comment]
Thanks for the prompt work!  This is my first time reporting a bug like this, and I'm not really fimiliar with the cast capabilities of github... so I'm not sure... now what?  Do I wait for the next release of onsen?  Or is there another way I can update what I have in order to have this modified ability?  Thanks again!

**Comment by asialgearoid** [comment]
Most users only provide a fraction of the detail you did, so it was a very easy bug to track down and fix. Thank you for the great report!

Normally you would wait for the next release to get the fix, but at the moment I'm not sure when that will be. It is possible to download a zip of the latest build from https://onsenui.github.io/latest-build/. There have been no major changes since the last release, so you shouldn't find any big surprises.
