### ISSUE TITLE
CSSnext is deprecated.

### ISSUE THREAD

**Issue by sbaechler** [OnsenUI/OnsenUI#2449]
Cssnext is no longer being maintained. You might want to look for another solution for the future.

The author recommends [postcss-preset-env](https://preset-env.cssdb.org/)

https://moox.io/blog/deprecating-cssnext/

**Comment by asialgearoid** [comment]
Thanks for the heads up, I hadn't realised that. I guess there is no immediate rush to change, but we should get on this in the next few weeks.
