### ISSUE TITLE
Core |  issue: (GestureDetector) single-click fires doubletap in chrome dev emulation mode

### ISSUE THREAD

**Issue by mrphuzz** [OnsenUI/OnsenUI#2455]
__Environment__

  
```
[Core]
  onsenui latest
  
[Platform]
  Desktop - Windows 8.1 64-bit

[Browser]
  Desktop - Chrome 67.0.3396.87 on Windows 8.1 64-bit
```

__Encountered problem__
  
When using `GestureDetector` to capture a `doubletap` event while using the latest Chrome in dev mode while emulating a device, a single mouse click will cause the `doubletap` event to fire.

__How to reproduce__
  
Open provided demo link.  Ensure this is in Chrome.  Press F12 to open dev tools, then click on the "Toggle device" icon in the upper left area of the dev tools.  In the playground, click Run (using iOS or Android gives same result).  Single click in the white space and an alert will pop up indicating that a `doubletap` event was received.  Note: this behavior is not observed when compiled and running on an actual device, nor in Chrome when dev tools is NOT open, nor in Chrome when when dev tools IS open, but NOT in device emulation mode.  Only observed in Chrome when dev tools is open and running in device emulation mode.

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<ons-gesture-detector>
  <div id="detect-area" style="width: 1000px; height: 1000px; border:1px solid red;">
    Swipe Here
  </div>
</ons-gesture-detector>
```

- __JS__

```javascript
  document.addEventListener('swipeleft', function(event) {
    if (event.target.matches('#detect-area')) {
      alert("swiped left");
    }
  });
  
  document.addEventListener('doubletap', function(event) {
    if (event.target.matches('#detect-area')) {
      alert("doubletap");
    }
  });
  
  
  
```

**Comment by asialgearoid** [comment]
Thanks for the report and example. This seems to be caused by the `GestureDetector` receiving both `touchend` and `mouseup` events one after another. I guess that would explain why it only happens in dev tools, because a browser would not normally fire both. I wonder if this is a regression in Chrome. Did this only start with Chrome 67?

**Comment by mrphuzz** [comment]
I think this is a relatively new thing, but not strictly 67, only because I
would expect that I would have noticed it before now, as I user the
emulation feature a lot. Also, right before I posted this bug report, I was
noticing the issue and I looked at the version of Chrome, and it was the
last 66 version. I updated to 67 just to see if the issue would go away. It
did not.  That is when I made the bug report.

**Comment by asialgearoid** [comment]
Looking into this a bit more, it definitely feels like an issue with Chrome. This incorrectly-fired `doubletap` only happens for me when I open the device mode _after_ opening the page. If I reload with device mode already opened, then `doubletap` works as expected. Is this the same for you, @mrphuzz?

**Comment by mrphuzz** [comment]
Thanks for responding.  Just to make sure I understand what you mean, I
tried what I think you said.  I go to my webapp, and press F12 and change
to device mode.  I click on a list item and a double-tap event fires.  If I
press F5 to refresh the website, the behavior is the same for me.  Single
clicking still causes double-tap event to fire.  If I long-click the
refresh button in Chrome and choose any of the three reload options,
single-click in dev mode in gesture detector still causes double-tap event
to fire.  If this is not what you mean, can you please clarify?  Thanks!

**Comment by asialgearoid** [comment]
It might depend on the kind of device that you're emulating in Chrome. When the GestureDetector detects that it can use touch events on a mobile device, it doesn't add mouse events. But if it does not detect this, then the mouse events will be added along with touch events, which would cause this, and also explain the behaviour I was seeing.

Can you check `ons.GestureDetector.NO_MOUSEEVENTS` in the console? It should be `true`. Changing it won't make a difference, as it it only used on first load, but I expect that it must be `false` for you.
