### ISSUE TITLE
Onsen UI + PhoneGap not working after second time opening app

### ISSUE THREAD

**Issue by Merlin04** [OnsenUI/OnsenUI#2466]
__Environment__

Onsen UI Version:
2.10.1
- 

Framework:
None
- 

Framework binding:
None
- 

Additional libraries:
PubNub API
- 

Platform:
Android (all versions) with PhoneGap Build
- 

__Encountered problem__

When I package my app for Android with PhoneGap, the app works the first time I open it, but when I open multitasking and close the app out and open it again, all navigation in the app (the slider menu and the "Done" button in first time setup) doesn't work. In addition, the button doesn't pull up the toast.

Another unrelated issue I have is that the link buttons don't pull up the webpage in a browser window. I'm pretty sure I'm doing it wrong.

Thanks for the help!

Here's a codepen:
https://codepen.io/merlin04/pen/WyyryQ
^ If you want the automatic setup screen to work properly, you need a 1*1px transparent image called `b.png`

__How to reproduce__

1. Build app with PhoneGap Build using local Onsen UI and b.png
2. Open app on Android
3. Put random values in the setup screen
4. Click the button labeled something like "OK"
5. Open the slider menu and close it
6. Open multitasking and close the app
7. Reopen the app

**Comment by asialgearoid** [comment]
This may just be a problem with your Javascript. Looking at it with the Chrome Developer Tools, I can see an error, which could prevent the app from loading completely.

```
else if (page.id === 'feed') {
    page.querySelector('#enter-setup').onclick = function () {
        document.querySelector('#myNavigator').pushPage('setup-return.html', { data: { title: 'Auto' } });
    };
}
```

There is no element with the ID `enter-setup` in your example. So when you try to set `onclick`, the browser gives an error. This may be the reason it does not load correctly.

As this is not an issue with Onsen UI itself, I will close this issue. I recommend checking out the [Onsen UI Discord](https://discordapp.com/channels/415288814475542540/415288814911619084) if you have more questions.

**Comment by Merlin04** [comment]
When I try to join the discord, I get an "Invite Invalid" message.

**Comment by asialgearoid** [comment]
Apologies, I put in the wrong link. I have edited my comment with the correct invite link.

**Comment by Merlin04** [comment]
Removing that part of the code didn't fix it, I'm asking in the discord.
