### ISSUE TITLE
Tabs not resizing in Navigator+Tabbar pattern (React)

### ISSUE THREAD

**Issue by lilyannh** [OnsenUI/OnsenUI#2467]
__Environment__

Onsen UI Version:

- Latest

Framework:

- React 16.x

Platform:

- all (iOS, Android, browsers)

__Encountered problem__

When using Navigator+Tabbar, tab window widths don't update properly after the window width changes (browser), or on mobile, if the device changes from portrait to landscape. This seems to be React binding specific; this behavior could not be reproduced using the same methods below, but starting from the vanilla JS demo.

__How to reproduce__

Start with the [demo](https://onsen.io/playground/?framework=react&category=common%20patterns&module=navigator_tabbar) from the documentation, then Export To Codepen.  Adjust your browser width and try changing a tab.

**Comment by asialgearoid** [comment]
Thanks for the report. I'm not sure exactly what is happening here, but it appears to be some sort of race condition, causing the `onResize` handler for the tabs to never be attached. In the example you linked, if you tap `Push Page` and then go back, causing the tabs to be re-initialised, the resize works as expected. So I think it is some timing issue when the app first loads. I'll see if I can track it down.

**Comment by aguingand** [comment]
I guess the problem is here:

https://github.com/OnsenUI/OnsenUI/blob/2417fdb55f8b49db1f3f9224bf8390a5e23938c0/core/src/elements/ons-tabbar/index.js#L241-L243

Since the the tabbar have a page parent in this context, `_show` is never called.

**Comment by webmasterdragon** [comment]
@aguingand @asialgearoid I have same issue tabbar navigation when orientation change.
Do we have solution?
