### ISSUE TITLE
Vue | v-ons-tabber causes duplicate keys

### ISSUE THREAD

**Issue by Ray-Eldath** [OnsenUI/OnsenUI#2471]
**Environment**

Onsen UI Version: 2.10.2

Framework: Vue.js 2.5.2

Framework binding: vue-onsenui 2.6.1

Platform: Browser and Cordova (Android)

**Problem**

When dealing with `v-ons-tabbar`, I  provide a `tabs` object and set page in it all the same, then... Vue.js warns me with `Duplicate keys detected`:

![snipaste_2018-07-10_21-56-12](https://user-images.githubusercontent.com/7938763/42519606-fac33c00-8496-11e8-9f88-d084ca046860.png)
![snipaste_2018-07-10_21-56-51](https://user-images.githubusercontent.com/7938763/42519616-ff5566bc-8496-11e8-88fb-7824eba89c34.png)

Maybe `key` of tabs should be configurable.

---

**Another feature request**
How to make `v-ons-tabber` **scrollable** ? When there are too many tabs, the tab bar looks too crowded...
Just like:
![snipaste_2018-07-10_23-17-45](https://user-images.githubusercontent.com/7938763/42520135-1ea0024c-8498-11e8-9ab1-b44866cedd57.png)
On [MDUI - Scrollable tab bar demo](https://www.mdui.org/docs/tab/demo2)
And how to make button thinner... I mean, lower height.

**Comment by asialgearoid** [comment]
It is possible to set a `key` for tabs, as in [this example](https://onsen.io/playground/?framework=vue&category=reference&module=tabbar). Is it not working for you?

As for scrolling tabs, it is not currently supported, though it is a good idea. We will look into it!

**Comment by Ray-Eldath** [comment]
Thx!
As for the `duplicate keys`, now works fine.
And now I am looking forward to your scrollable tabs. 😆

**Comment by Ray-Eldath** [comment]
Sorry... Now I found that `key` in `tabs` not works...
![snipaste_2018-07-11_12-27-18](https://user-images.githubusercontent.com/7938763/42550814-769dcaec-8506-11e8-8901-bef1f953939c.png)
![snipaste_2018-07-11_12-29-21](https://user-images.githubusercontent.com/7938763/42550815-76cb20fa-8506-11e8-8158-c8fe5c3f0ed4.png)
`duplicate keys` still thrown.

**Comment by asialgearoid** [comment]
That does look like it should work. I'm not sure why it wouldn't. Can you reproduce the issue on the [Playground](https://onsen.io/playground/?framework=vue)?

As for customising the button, take a look at the [Onsen UI Theme Roller](https://onsen.io/theme-roller/). It is the best way to change the styles of Onsen UI components.

**Comment by Ray-Eldath** [comment]
I think it's difficult to reproduce on the Playground... for I am using Vue single file component. But I've posted the code on [GitHub Gist](https://gist.github.com/Ray-Eldath/78783f2d12c8503bcdc8b507ec60f96f).

---

I've tried Onsen UI Theme Roller, but not works... When I click `Generate and Download` button, it will **loading unstop**... And console error with:
![snipaste_2018-07-11_13-10-58](https://user-images.githubusercontent.com/7938763/42551907-4075b1e0-850c-11e8-92c8-db3b56e762e4.png)

**Comment by asialgearoid** [comment]
Your gist is missing `../js/utils.js` so `kaomojis` is undefined. Are you able to reproduce the issue without that library? It would help to track down the problem.

There seems to be an issue with the Theme Roller for Onsen UI 2.10.2 and 2.10.3. It has been fixed for the next release, but that is not out yet. For now, please select 2.10.1 from the dropdown. It will be OK even though your app uses 2.10.2.

**Comment by Ray-Eldath** [comment]
All right. I had reproduced this bug on [CodeSandbox](https://codesandbox.io/s/q7092m7929).

---

As for the theme, is there any way to edit the color **dynamically**? I want to change the color during run time...

**Comment by asialgearoid** [comment]
Thanks for the demo. There are a few things factoring into this. The reason I could not reproduce it originally is because this warning was only introduced in Vue 2.5.10 (see https://github.com/vuejs/vue/issues/7323).

It is being caused by `name: "KaomojiList",` in `KaomojiList.vue`. Vue ends up using this name as a key for `v-ons-page`. Since the tab bar creates multiple `v-ons-page`s, the app ends up with multiple pages using the same key, `KaomojiList`. If you remove that name, then the warning goes away.

**Comment by Ray-Eldath** [comment]
Thx. Now works fine.
