### ISSUE TITLE
tabbar does not recompute slider width after orientation change

### ISSUE THREAD

**Issue by brunobg** [OnsenUI/OnsenUI#2472]
__Environment__

Onsen UI Version:
- 2.10.3

Framework:
- Vue 2.5.16

Framework binding:
- vue-onsenui 2.6.1

Additional libraries:
- vue-router 3.0.1.

Platform:
- Any browser

__Encountered problem__

Tabbar does not recalculate the width when an orientation change happens on a specific case. 

__How to reproduce__

The reproduction is a bit involved and I couldn't make a separate codepen, but hopefully the information will be enough to pinpoint the problem.

1. User is on a ons-page A which contains a tabbar. We're using vue-router and A has a keep-alive. 
2. User navigates, using vue-router, to another whole new page B.
3. User clicks on the back button of the browser, and is returned to page A.
4. User changes orientation of the device. The tabs do not recompute the width and slide becomes wrong. It seems that _onRefresh on https://github.com/OnsenUI/OnsenUI/blob/68f73ca901d34f9f1245cd36e118f273d4b6d08d/core/src/elements/ons-tabbar/index.js is not called.
5. If user goes to B and returns to A again, the layout fixes itself. 

Meanwhile, is there someway to emit an event to force calling _onRefresh()? forceUpdate() did nothing, a this.$emit('refresh') on A did nothing either.

**Comment by asialgearoid** [comment]
This seems to be a similar issue to #2467. Though I thought I tested that with the Vue bindings, and it worked fine. In that case, it's a timing issue, which causes the resize event handler not to be added in the first place. It could be the same here.

For a workaround, you could try manually forcing the refresh event handler to be added. It is done in the tabbar's `_show` method. So, inside `ons.ready`, add:
```javascript
document.querySelector('ons-tabbar')._show();
```

**Comment by brunobg** [comment]
Thank you for the reply. I added your code at a orientation change event like this and now it works as expected:

```js
this.$ons.orientation.on('change', () => { document.querySelector('ons-tabbar')._show(); });
```
