### ISSUE TITLE
ons.platform.isAndroid and ons.platform.isIOS take into account selected platform

### ISSUE THREAD

**Issue by emccorson** [OnsenUI/OnsenUI#2475]
Onsen UI Version: 2.10.3

The functions `ons.platform.isAndroid` and `ons.platform.isIOS` take into account any values set using `ons.platform.select`.

For example, if you are using iOS but have set the platform to `android`, `ons.platform.isAndroid` will return `true`.

```javascript
// on iOS
ons.platform.isAndroid(); //false
ons.platform.select('android');
ons.platform.isAndroid(); //true
```

This seems like unexpected behaviour to me. Maybe we could have separate functions like `ons.platform.isReallyAndroid` and `ons.platform.isReallyIOS`, or change the behaviour of the existing functions to ignore selected platform.

Also the documentation at https://onsen.io/v2/api/js/ons.platform.html#methods-summary should mention that the selected platform is not ignored.

**Comment by asialgearoid** [comment]
It's hard to say what this behaviour should be. When the user specifically selects a platform, they may expect it to return true in this case. Perhaps we could offer a way of toggling the boolean `_ignorePlatformSelect` in `platform.js`, which is currently what controls whether these functions factor in the user's `select` setting. This would allow us to keep the current behaviour, but give the option for an override.

An update to the documentation is probably the most important part of this though, to make it clear to users exactly how this works.
