### ISSUE TITLE
Proposal: Separate AngularJS binding into its own package

### ISSUE THREAD

**Issue by asialgearoid** [OnsenUI/OnsenUI#2476]
**Rationale**
Currently, the AngularJS binding is included as part of the core `onsenui` npm package. This means that when we need to make changes to this binding, we need to do a core release. Most recently, this limitation presented itself in https://github.com/OnsenUI/OnsenUI/issues/2468, when we needed a core release due to the AngularJS binding having an issue.

Originally I believe this binding was included in the core package of Onsen UI 2 because Onsen UI 1 was based on AngularJS, and it made the migration path easier for most users. However, it has been several years since then, and having it as part of the core is now a limitation, not a help.

In the future, I see us doing less work on the AngularJS bindings, only fixing bugs but not adding support for new features. The AngularJS project [is now in LTS maintenance mode](https://blog.angular.io/stable-angularjs-and-long-term-support-7e077635ee9c), as of July 1st. Moving the binding into its own package will additionally help with this transition.

**Proposal**
My proposal is that we release `onsenui@2.11.0` without Angular in the core. We could possibly justify a `3.0.0` release for this, but I think it would probably give the impression of huge new changes that do not exist. At the same time, we would publish `angularjs-onsenui@1.0.0`.

The point of most concern here is of course the migration path for users. The documentation should cover this with clear instructions, and details also in the changelog. We could possibly detect errors in 2.11.0 caused by the core no longer containing AngularJS, and log a message in the browser's console telling the user to install the new package.

@emccorson @puku0x Thoughts?

**Comment by emccorson** [comment]
I think moving the AngularJS bindings to their own package is definitely something we should do. Besides historical reasons, there's not much sense now in giving AngularJS special treatment compared to the other supported frameworks.

Just to confirm, you are thinking we should essentially put the AngularJS bindings in LTS mode to coincide with the AngularJS project going into LTS? Meaning any new features wouldn't be supported in the AngularJS bindings. I'm slightly concerned that anyone using the AngularJS bindings will still expect the new features since AngularJS is technically still supported by Angular.

Would there be any way to move the AngularJS bindings to their own package without breaking existing applications? (Although if it's a minor release then breaking changes should be fine.)

We should probably put an npm warning in the new package to let the users know AngularJS bindings are getting phased out.

**Comment by emccorson** [comment]
**Tasks involved**

- create new npm package
- remove `'angular-bindings'` from `buildTasks` in gulpfile.babel.js
- remove angular from rollup.config.js
- remove angular as dev dependency in package.json
- add package.json and other config files to bindings/angular1
- update AngularJS installation instructions in onsen.io Guide
- update release instructions in CONTRIBUTING.md
- announce in discord and forum
- remove angular keyword from package.json and bower.json ???

Please update this list if anything is wrong/missing.

**Comment by puku0x** [comment]
@asialgearoid I agree with the idea.
We can focus on the core functionality of Onsen UI by separating AngularJS binding.
I think putting an npm message is useful for migration too!

**Comment by asialgearoid** [comment]
Thanks for your feedback. @emccorson The long term plan will be to eventually put the AngularJS bindings into LTS mode (maybe towards the end of this year). For now, I want to just move the binding into its own npm package, to make that transition easier down the line.

I think there are a few ways we can notify users about the change if they have upgraded and not realised that Angular is no longer in the core, and they need to install the new package. I have a few ideas. 

- Add a `postinstall` script to the `package.json` which will warn users about the change
  - How long should we keep this there? I expect some AngularJS users may not upgrade for a long time. Is it possible to detect which version it has been upgraded from?
- Replace `angular-onsenui.js` in the distribution package with a simple file which simply logs an error in the console explaining how to upgrade.
  - I think this could be quite a simple solution, and does not affect non-AngularJS users, unlike the warning above

On the version numbering, I think 2.11.0 will be OK. Looking at the changelog, whenever a breaking change has been made, the minor version has been increased. So this numbering is in keeping with what has been historically done.

**Comment by asialgearoid** [comment]
I have created a PR to do this, which I would appreciate a review of if either of you have time, @emccorson and @puku0x. It is at https://github.com/OnsenUI/OnsenUI/pull/2483.
