### ISSUE TITLE
Remove UNSAFE functions in React

### ISSUE THREAD

**Issue by emccorson** [OnsenUI/OnsenUI#2482]
There are some functions in the React bindings which have been deprecated and prefixed with `UNSAFE_`. As of React 17, calling these functions without the `UNSAFE_` prefix will not work.

One example is `componentWillRecieveProps` which should now be called as `UNSAFE_componentWillReceiveProps`.

A quick fix would be to run this https://github.com/reactjs/react-codemod#rename-unsafe-lifecycles which will rename all unsafe functions.

The proper solution is to replace usage of these functions with whatever React recommends instead.

Currently, Onsen UI uses React 16 so this isn't a problem, but it will break if we upgrade to React 17. We should probably remove these functions anyway since React recommends not to use them.

**Comment by asialgearoid** [comment]
This more generally seems to be related to [React's move to asynchronous rendering](https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html), which could require big changes within our bindings.

For now though, I agree we should just use the renamed versions. I can't find any release date for React 17, so I presume it is not imminent.

For maximum compatibility, I would like to keep both functions (both `componentWillRecieveProps` and `UNSAFE_componentWillRecieveProps`). I think we should be able to do this easily inside the components' constructors by setting `this.UNSAFE_componentWillRecieveProps = componentWillRecieveProps`.

**Comment by emccorson** [comment]
bump
