### ISSUE TITLE
Expandable list doesn't work correctly in case of lists inside expandable content

### ISSUE THREAD

**Issue by gulzaibAmjed** [OnsenUI/OnsenUI#2485]
An expandable list shows the last item from expandable content if there are divs having different classes such as right or left. It shows the last item on top as the main string. Plese see the code that I placed.

How to Generate:
Have multiple list items in an expandable item having the right, left classes.

```
<ons-list-header>Expandable</ons-list-header>
<ons-list-item expandable>
  Tap to expand
  <div class="expandable-content">
    <ons-list-item>
      <div class="left">Start Date:</div>
      <div class="right">1.12.2019</div>
    </ons-list-item>
    
    <ons-list-item>
      <div class="left">End Date:</div>
      <div class="right">1.01.2015</div>
    </ons-list-item>
    
    <ons-list-item>
      <div class="left">Aktiv</div>
      <div class="right"><ons-switch checked></ons-switch></div>
    </ons-list-item>
  </div>
</ons-list-item>
```

**Comment by emccorson** [comment]
I confirmed that this bug is reproducible from the playground.

If no one else has picked this ticket up, I'll take a look once I've
finished the bugs I'm currently working on.

**Comment by gulzaibAmjed** [comment]
This issue is still there.

**Comment by emccorson** [comment]
It's working for me. How are you checking it? The fix is in master but not released yet, so it won't show up in the playground.

**Comment by fajarali1** [comment]
is the fix has been released yet? i'm still having the issue
Thanks

**Comment by martindederer** [comment]
It would be really helpful to have this feature. Any plans on when the next version is going to be released?
