### ISSUE TITLE
ons-select does not set selectedIndex when changing selected value from v-model (vue)

### ISSUE THREAD

**Issue by adriankeenan** [OnsenUI/OnsenUI#2486]
__Environment__

  
```
[Core]
  onsenui latest
  
[Framework]
  vue 2.4.1

[Framework binding]
 vue-onsenui latest

[Platform]
  Desktop - Ubuntu 64-bit

[Browser]
  Desktop - Firefox 61.0 on Ubuntu 64-bit
```

__Encountered problem__

After changing the array of data used to populate a `<ons-select/>`, changing the v-model value that the select is bound to does not set the selectedIndex property of the `<select/>` wrapped by the `<ons-select/>` component.

__How to reproduce__
  

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<template id="main">
  <v-ons-page>
    <h3>Current value native: {{ selectedValueNative }}</h3>
    <select v-model="selectedValueNative">
      <option v-for="option in options" v-bind:value="option.value">{{ option.label }}</option>
    </select>
    <br>
    <h3>Current value Onsen UI: {{ selectedValueOnsen }}</h3>
    <v-ons-select v-model="selectedValueOnsen">
      <option v-for="option in options" v-bind:value="option.value">{{ option.label }}</option>
    </v-ons-select>
    <br>
    <button @click="populate">Change values</button>
  </v-ons-page>
</template>

<div id="app"></div>
```

- __JS__

```javascript
new Vue({
  el: "#app",
  template: '#main',
  data: {
    selectedValueNative: 3,
    selectedValueOnsen: 3,
    options: [
      {
        label: 'number ' + 1,
        value: 1,
      },
      {
        label: 'number ' + 2,
        value: 2,
      },
      {
        label: 'number ' + 3,
        value: 3,
      },
      {
        label: 'number ' + 4,
        value: 4,
      },
      {
        label: 'number ' + 5,
        value: 5,
      },
    ],
  },
  mounted(){

  },
  methods: {
    populate(){
      // Set options
      const data = [];
      for (let i = 0; i < 10; i++){
        const value = this.randInt(100);
        data.push({ label: 'number ' + value, value });
      }
      this.options = data;

      // Select an option at random
      const selectedIndex = this.randInt(9);
      const selectedValue = this.options[selectedIndex].value;

      this.selectedValueNative = selectedValue;
      this.selectedValueOnsen = selectedValue;
    },
    randInt(max){
      return Math.floor((Math.random() * max) + 1);
    }
  }
})
```

**Comment by emccorson** [comment]
Just to confirm, you are expecting that:

- when you first run the app, the value displayed by the
`v-ons-select` should be the same as `selectedValueOnsen`
- when you click the 'Change values' button, the value displayed by
the `v-ons-select` should also be the same as `selectedValueOnsen`

Is that correct?

I also noticed that usually when you click 'Change values', there is
no string displayed by `v-ons-select`, but occasionally it will
display a number from `options` that is different from
`selectedValueOnsen`.

**Comment by emccorson** [comment]
Just to confirm, you are expecting that:

- when you first run the app, the value displayed by the`v-ons-select` should be the same as `selectedValueOnsen`
- when you click the 'Change values' button, the value displayed by the `v-ons-select` should also be the same as `selectedValueOnsen`

Is that correct?

I also noticed that usually when you click 'Change values', there is no string displayed by `v-ons-select`, but occasionally it will display a number from `options` that is different from `selectedValueOnsen`.

**Comment by adriankeenan** [comment]
> Just to confirm, you are expecting that:
> 
>     when you first run the app, the value displayed by thev-ons-select should be the same as selectedValueOnsen
>     when you click the 'Change values' button, the value displayed by the v-ons-select should also be the same as selectedValueOnsen
> 
> Is that correct?


Yes - exactly. The native `<select>`, which is bound to the model in the same way, does this as expected but `<v-ons-select>` does not.

 I've updated the example above to show that if `options` is populated when the component is created, the selectedIndex in `<v-ons-select>` is set correctly. As soon as you bind `options` to a new array, the selectedIndex in `<v-ons-select>` no longer updates, but native `<select>` is fine.

> I also noticed that usually when you click 'Change values', there is no string displayed by v-ons-select, but occasionally it will display a number from options that is different from selectedValueOnsen.


I noticed this too. I have no idea what's causing that.
