### ISSUE TITLE
Incorrect data value.

### ISSUE THREAD

**Issue by laelbe** [OnsenUI/OnsenUI#2487]
Data variables are working incorrectly in the navigation stack.
This may cause serious problems in WebApp Environment.

See this demo : https://codepen.io/anon/pen/wxJeQG?editors=1011

Open console window,
Push -> Push -> Push -> Pop -> Pop

**Comment by emccorson** [comment]
I can't see the behaviour demonstrating a problem in the demo.

When you call `pushPage` and set the attribute to the value of `globalNum`, the attribute value won't update when the value of `globalNum` changes (which I think is what you are expecting to happen).

I'm closing this for now. If someone can point out where there is a problem I'll reopen this.
