### ISSUE TITLE
React | ListItem issue: expanded prop ignored when ListItem is mounted

### ISSUE THREAD

**Issue by emccorson** [OnsenUI/OnsenUI#2499]
__Environment__

  
```
[Core]
  onsenui latest
  
[Framework]
  react 15.4.2

[Framework binding]
 react-onsenui latest

[Platform]
  Desktop - OS X 10.13.5 64-bit

[Browser]
  Desktop - Chrome 67.0.3396.99 on OS X 10.13.5 64-bit
```

__Encountered problem__
When an expandable ListItem is rendered with `expandable` prop set to `true`, the expandable content should be visible, but it is not.

Updating `expandable` does seem to work though, so this is just an issue when ListItem is mounted.

__How to reproduce__
1. Notice when app first starts that list item is not expanded but `isExpanded` is true.
2. Click 'Toggle expand' button.
2. Notice list item quickly open then close again. `isExpanded` is now false.

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<div id="app"></div>
```

- __JS__

```jsx
const App = class extends React.Component {
  constructor(props) {
    super(props);
    
    this.state = { isExpanded: true };
    
    this.toggle = this.toggle.bind(this);
  }
  
  toggle() {
    this.setState({ isExpanded: !this.state.isExpanded });
  }
  
  render() {
    return (
      <div>
        <Ons.List>
          <Ons.ListItem expandable expanded={this.state.isExpanded}>
            top
            <div className="expandable-content">expandable content</div>
          </Ons.ListItem>
        </Ons.List>
        
        <Ons.Button onClick={this.toggle}>Toggle expand</Ons.Button>
      </div>
    );
  }
};

ReactDOM.render(<App />, document.getElementById('app'));
```

**Comment by rj-david** [comment]
Just encountered this bug

**Comment by gittysam** [comment]
Hi,

Thanks emccorson finding out the issue !
Like you said, the web component 'expanded' property is not initialized (its value is undefined when the component is created).

As a workaround before the bug is resolved in a future release, I am using a subclass of ListItem :

import { ListItem } from 'react-onsenui'

export default class MyListItem extends ListItem {
  componentDidMount () {
    super.componentDidMount()
    this.node.expanded = this.props.expanded === true
  }
}
