### ISSUE TITLE
Vue | Page issue: 

### ISSUE THREAD

**Issue by berndfuhrmann** [OnsenUI/OnsenUI#2512]
__Environment__

  
```
[Core]
  onsenui latest
  
[Framework]
  vue 2.4.1

[Framework binding]
 vue-onsenui legacy

[Platform]
  Desktop - Windows 10 64-bit

[Browser]
  Desktop - Chrome 68.0.3440.84 on Windows 10 64-bit
```

__Encountered problem__
Elements added via the button to the vue array do not show up.
Interestingly, if you put the `<div v-for="x in stuff" :key="x">{{x}}</div>` into another `<div>` element, everything will work as expected.

__How to reproduce__
Click "Add stuff". The array will grow (length increases), but the v-for loop does not show any new elements.

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<template id="main">
  <v-ons-page>
		<h1>Stuff</h1>
		<v-ons-button modifier="large" style="margin: 6px 0" @click="addElement">Add Stuff</v-ons-button>
		<div>{{stuff.length}}</div>
	  <div v-for="x in stuff" :key="x">{{x}}</div>
		<p>Ende</p>
  </v-ons-page>
</template>

<div id="app"></div>
```

- __JS__

```javascript
new Vue({
  el: '#app',
  template: '#main',
  methods: {
		addElement: function() {
			this.stuff.push("gamma");
		}
	},
	data () {
		return {
			stuff: ["alpha", "beta"]
		}
	}
});
```

**Comment by emccorson** [comment]
Thanks for the bug report.

I confirmed this works as expected in normal Vue, so this is definitely an Onsen UI bug: https://codepen.io/emccorson/pen/WKgxgV

**Comment by jpriebe** [comment]
I encountered a similar problem when I built a list of <v-ons-card> objects directly underneath the <v-ons-page>.  The Vue debugger showed them in the page structure, but the DOM elements were not being added to the page__content <div>.  They were being added as siblings of that <div>, and were thus obscured by the page__background <div>.

And if I initialized the data variable that was driving the list of <v-ons-card> components, I would see the initialized values, but I had all kinds of problems replacing the array.  Any objects whose keys matched the original init values would show up, but all others would be hidden.  And if *none* of the objects matched the init values, the visible cards would disappear.  It was maddening.  I thought it had something to do with the way I was handling the data variable. 

The workaround of wrapping the objects with a single <div> fixed the problem.  I suspect that in the case where the <v-ons-page> component has more than one child, it gets confused when it tries to assign them to the content slot.

**Comment by emccorson** [comment]
I've just come back to this issue as part of the upgrade to support Vue 3.

The bug seems not to be present in vue-onsenui for Vue 3, but I am not sure why. I have updated the Vue 3 CHANGELOG to reflect this in eda7cfc52.

vue-onsenui for Vue 2 still needs a fix for this. I will do it after the Vue 3 release.

**Comment by yong-asial** [comment]
@berndfuhrmann Please refer to this guideline - https://onsen.io/v2/guide/vue/#vonspage-compilation.

If you wrap the content with `<div class="content">` it should be working fine.

```
<template id="main">
  <v-ons-page>
    <div class="content">
      <h1>Stuff</h1>
      <v-ons-button modifier="large" style="margin: 6px 0" @click="addElement">Add Stuff</v-ons-button>
      <div>{{stuff.length}}</div>
      <div v-for="x in stuff" :key="x">{{x}}</div>
      <p>Ende</p>      
    </div>
  </v-ons-page>
</template>

<div id="app"></div>
```
