### ISSUE TITLE
Accessor with side effect

### ISSUE THREAD

**Issue by natsuki14** [OnsenUI/OnsenUI#2513]
Hello,

This function looks just an accessor but has a side effect. Is it expected behavior?

https://github.com/OnsenUI/OnsenUI/blob/8996d785e35fb467a5d3d36e53f78c67226fcff5/core/src/elements/ons-splitter-side.js#L357-L361

**Comment by emccorson** [comment]
You're right that is probably a badly named function. But I think it's probably better to leave it for now unless it breaks something.
