### ISSUE TITLE
The isCancelable problem of modal

### ISSUE THREAD

**Issue by zongyuan-vale** [OnsenUI/OnsenUI#2514]
__Environment__

Onsen UI Version:

- @~2.10.0

Framework:

- react @^15.4.2

Framework binding:

- react-onsenui@~1.11.0

Additional libraries:

- 

Platform:

- Windows 10 Chrome

__Encountered problem__

Modal Component adding properties is invalid(isCancelable, onCancel),Looking at source Modal is inheriting BaseDialog,It still doesn't have this feature? How do I click on mask to shut down modal? thank.

__How to reproduce__

```
<Modal isOpen={this.state.isLoading} onCancel={() => { this.setState({isLoading:false}); }}>
      Loading ...
</Modal>
```

**Comment by emccorson** [comment]
You can add a click event listener to the mask and call `hide` in the callback.
