### ISSUE TITLE
How to check the deice type in onsen ui angular flovar?

### ISSUE THREAD

**Issue by digish777** [OnsenUI/OnsenUI#2515]
How to check the deice type in onsen ui angular flovar?

Thanks in advance

**Comment by puku0x** [comment]
You can use `onsPlatform` to check the device type.
https://ja.onsen.io/v2/api/angular2/ons.platform.html

```ts
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { onsPlatform } from 'ngx-onsenui';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';

if (environment.production) {
  enableProdMode();
}

// iPhone X fix !!!!
if (onsPlatform.isIPhoneX()) {
  const html = document.documentElement;
  html.setAttribute('onsflag-iphonex-portrait', '');
  html.setAttribute('onsflag-iphonex-landscape', '');
}

platformBrowserDynamic().bootstrapModule(AppModule)
  .catch(err => console.log(err));

```

**Comment by digish777** [comment]
onsPlatform.isAndroid(), gave the error. onsPlatform is not defined is not defined. I have imported using:
import { onsPlatform } from 'ngx-onsenui';

**Comment by emccorson** [comment]
@digish777 I'm closing this because it's a question, not an issue. If you have a question about Onsen UI, please post it at https://community.onsen.io/ or https://discord.gg/NEMSxUF.
