### ISSUE TITLE
how to call cordova plugin notification inside angular onsen flavor?

### ISSUE THREAD

**Issue by digish777** [OnsenUI/OnsenUI#2522]
how to call cordova notification  plugin inside angular 2 onsen flavor?

thanks in advance

**Comment by puku0x** [comment]
Which kind of `notification` ?

- Dialogs
- Local notifications
- Push notificaions

Fortunately, you can use [@ionic/native](https://ionicframework.com/docs/native) . It is easy to use for Angular users.

**Comment by digish777** [comment]
Dialog.

**Comment by puku0x** [comment]
Here this is it!
https://ionicframework.com/docs/native/dialogs/

However I recommend to use `onsNotification` which is better for debug.

```ts
import { onsNotification } from 'ngx-onsenui';
onsNotification.alert('Hello World!');
```
