### ISSUE TITLE
how to  quit / exit app on button click on angular onsen flavor?

### ISSUE THREAD

**Issue by digish777** [OnsenUI/OnsenUI#2523]
how to  quit / exit app on button click on angular onsen flavor?

**Comment by puku0x** [comment]
You have  three options for solving the problem.

- Don't implement it
- Use `navigator.app.exitApp()` for Android
- Create a Cordova plugin for it

I recommend you to ask https://community.onsen.io/ and I would like you to use the GitHub Issues for a bug report or a feature request.

**Comment by digish777** [comment]
navigator.app.exitApp() is not available in Angular onsen flavor. When I am trying to add navigator.app.exitApp(), typescript wont compile saying: app does not exist in navigator.

**Comment by puku0x** [comment]
You can write it `navigator['app'].exitApp()`, alternatively.
