### ISSUE TITLE
ons-button goes not trigger when ons-input is on focus with keyboard

### ISSUE THREAD

**Issue by onlyspike** [OnsenUI/OnsenUI#2528]
__Environment__

Onsen UI Version:
2.9.2
- 

Framework:
javascript core
- 

Platform:
Android 8.1
Android 6.0.1
Android 8.0
Cordova 7.0.0
- 

__Encountered problem__
ons-button goes not trigger when ons-input is on focus with keyboard

__How to reproduce__

I have a form with various fields and a button at the bottom.
When i focus on a ons-input with type="text" the keyboard shows like expected and type some text.
I then scroll down the page to my ons-button to button (keyboard is still showing).
When I tap the ons-button the keyboard hides but the button does not action. I have to then tap the button again to action.
When I do the same but from a ons-input with type password, email, tel, number it works.
It also works from a standard html input.

I have tried on 3 different android devices including an android emulator. Each device running a different version of android.

**Comment by onlyspike** [comment]
I have managed to resolve the issue.
It turned out to be an issue with the soft keyboard.
link below.
https://stackoverflow.com/questions/23327080/cant-click-button-when-soft-keyboard-is-visible

**Comment by masahirotanaka** [comment]
Cool! Closing the issue.
