### ISSUE TITLE
tab-border does not active on Vue Binding by Android Style

### ISSUE THREAD

**Issue by masakura** [OnsenUI/OnsenUI#2531]
__Environment__

Onsen UI Version:

- 2.10.4

Framework:

- 2.5.17

Framework binding:

- vue-onsenui 2.6.1

Platform:

- Android

__Encountered problem__
Switching pages with v-ons-tabbar does not activate tab-border.

![image](https://user-images.githubusercontent.com/6840413/45067295-7c189380-b0fd-11e8-8896-b4b91aaec119.png)

__How to reproduce__

I made a page with reference to [What about vue-router?](https://onsen.io/v2/guide/vue/#what-about-vue-router). Source code is [here](https://gitlab.com/snippets/1751132).

In this case, it seems that `TabbarElement._onScroll()` is not called.

**Comment by masahirotanaka** [comment]
Thanks! I can't access to your gitlab snippets. Can you give us access to it?

**Comment by emccorson** [comment]
Closing as no response.
