### ISSUE TITLE
バグ報告：vueのv-forでmounted以降で追加したリストレンダリングが反映されない

### ISSUE THREAD

**Issue by garchomp-game** [OnsenUI/OnsenUI#2533]
![_2018-09-06_22-34-19](https://user-images.githubusercontent.com/28251886/45160872-76b66880-b225-11e8-858e-c123eb06fd60.png)
上記のように書いてみたのですが、

普通のvue.jsの場合↓
![_2018-09-06_22-34-26](https://user-images.githubusercontent.com/28251886/45160907-96e62780-b225-11e8-9eb0-6f01290fc803.png)
このようにうまく行くのですが、

onsen uiの場合↓
![_2018-09-06_22-34-34](https://user-images.githubusercontent.com/28251886/45160896-89c93880-b225-11e8-9fc0-b46fee3e70af.png)

このように、mountedでpushしたものがうまく反映されません。
おそらく何らかのバグだと思うので、早急に対処をお願いいたします。

**Comment by puku0x** [comment]
@garchomp-game ご報告ありがとうございます。

Chromeの開発者ツールで見ると↓のように展開されているかと思います。

```html
<ons-page>
  <div class="page__background"></div>
  <div class="page__content">
    <div v-key="1">hoge</div>
  </div>
  <div v-key="2">hogehoge</div>  <!-- データ上は追加されている -->
</ons-page>
```

`page__content`に収まるようにdivで囲んでみてください。

```html
<v-ons-page>
  <div>
    <div v-for="hoge in hogelist" :v-key="hoge.id">{{hoge.title}}</div>
  </div>
</v-ons-page>
```

ご確認よろしくおねがいします。

**Comment by garchomp-game** [comment]
@puku0x 回答ありがとうございます！
試してみたところ解決しました！！！！ありがとうございますm(_ _)m
