### ISSUE TITLE
Is minimum css available?

### ISSUE THREAD

**Issue by internalG** [OnsenUI/OnsenUI#2535]
Your library is cool for native UI. If I want to use some native UI css for static html, how to trim them out? Thanks.

**Comment by masahirotanaka** [comment]
Thanks!

If you want to compress CSS, you could either

- Manually compress CSS: https://csscompressor.com/
- Use Grunt or Gulp to automate the job: https://www.npmjs.com/package/uglifycss
- Use Webpack, Parcel and the like to import CSS

Hope some of the solutions above works out for you.
