### ISSUE TITLE
Cannot use VueOnsen in unit tests due to use of DOM APIs

### ISSUE THREAD

**Issue by hmillison** [OnsenUI/OnsenUI#2536]
__Environment__
Node @ v10.10

Onsen UI Version:
2.10.4 

Framework:
Vue @ 2.5.16 

Framework binding:
Vue Onsenui @ 2.6.1

Additional libraries:
TS-Jest @ 23.14 

__Encountered problem__
- When i try to import VueOnsen into a unit test so I can register onsen's components with Vue, I get an error due to use of browser apis: 
```js
onsenui.js:1127
    var templates = window.document.querySelectorAll(query);

TypeError: Cannot read property 'querySelectorAll' of null
    at querySelectorAll (/Users/henrymillison/work/pesto/app/web/node_modules/core/src/ons/internal/internal.js:110:39)
    at Immediate.<anonymous> (/Users/henrymillison/work/pesto/app/web/node_modules/onsenui/js/onsenui.js:1121:3)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
```
- I want to be able to use VueOnsen directly instead of stubs so I can fully test my component's functionality

__How to reproduce__
- Create project with Vue CLI that includes unit tests
- In unit test file, import `vue-onsenui`
- Run unit tests, aforementioned onsenui error will be thrown

**Comment by drazewski** [comment]
Hi! I have a similar issue. When I try to write a tests for my react app (CRA) that uses React Onsenui @1.11.1 and Onsen @2.10.4 I get an error:

```
TypeError: Cannot read property 'querySelectorAll' of undefined
    at querySelectorAll (/Users/.../rejestrapp/node_modules/core/src/ons/internal/internal.js:110:39).
```

Thanks for help.

**Comment by akshay-daffodil-93** [comment]
Hi, I am getting the same issue with React.

**Comment by emccorson** [comment]
Closing as not planned for now. However, as we move more functionality to the core and away from the framework bindings, unit testing should become easier.
