### ISSUE TITLE
$ons.platform.isIPhoneX() returned false if iPhone XR and iPhone XS Max

### ISSUE THREAD

**Issue by tomopy03** [OnsenUI/OnsenUI#2540]
__Environment__

Onsen UI Version:

- 2.10.4

Framework:

- Vue 2.5.17

Framework binding:

- vue-onsenui 2.6.1

Additional libraries:

- 

Platform:

- iPhone XR, Cordova, iOS Simulator
- iPhone XS Max, Cordova, iOS Simulator

__Encountered problem__

$ons.platform.isIPhoneX() returned false.
If iPhone XS, returned true.

__How to reproduce__

**Comment by masahirotanaka** [comment]
Update. We're working on this, so should be ready soon.

**Comment by asial-matagawa** [comment]
@tomopy03 
This problem has been fixed by #2545 and we will the new version of Onsen UI soon.
Thank you for reporting!
