### ISSUE TITLE
Feature request: sticky header

### ISSUE THREAD

**Issue by andrewvmail** [OnsenUI/OnsenUI#2542]
Just a suggestion for a closer native like feel.

https://www.youtube.com/watch?time_continue=10&v=B5onEKYgMZ4
Another example is the iOS contact app.

**Comment by emccorson** [comment]
Thanks for the suggestion. Sticky headers are not something we're planning at the moment, but we'll keep it in mind for the future.

If you do need to implement something like sticky elements yourself, you might be able to use this: https://community.onsen.io/topic/3490/position-sticky-on-ons-list-item
