### ISSUE TITLE
How to enable pull to refresh in mobile chrome?

### ISSUE THREAD

**Issue by maxzhou0** [OnsenUI/OnsenUI#2543]
I noticed the pages made in onsen ui  can not use pull down to refresh in mobile chrome as others can do.this is default option in mobile chrome. i want to know how to enable it. thx

**Comment by masahirotanaka** [comment]
I think you're referring to Overscroll Behavior.
Please check this page: https://developers.google.com/web/updates/2017/11/overscroll-behavior

If you want a pull-to-refresh component, <ons-pull-hook> component should be what you want: https://onsen.io/v2/api/js/ons-pull-hook.html

**Comment by maxzhou0** [comment]
i already checked the google's document before the issue, sorry for i didn't mention that.
the google's feature is the default option for all pages. so i guess onsen ui must did something to prevent the feature, i want to know how to enable it from onsen webpage project.
