### ISSUE TITLE
Vue | List issue:  v-if not working properly on v-ons-list

### ISSUE THREAD

**Issue by maxzhou0** [OnsenUI/OnsenUI#2544]
__Environment__

  
```
[Core]
  onsenui latest
  
[Framework]
  vue 2.4.1

[Framework binding]
 vue-onsenui latest

[Platform]
  Desktop - Windows Server 2008 R2 / 7 64-bit

[Browser]
  Desktop - Chrome 69.0.3497.100 on Windows Server 2008 R2 / 7 64-bit
```

__Encountered problem__
  
change v-if value to true will not show the list.

v-show works in this case ,but will cause more problems,suggest the code need render obj.a but that time obj is null. thus i have to add v-if on every item.

__How to reproduce__
  

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<template id="main">
  <v-ons-page>
    <v-ons-list v-if="show">
      <v-ons-list-item>{{obj.a}}</v-ons-list-item>
    </v-ons-list>
    <br />

  </v-ons-page>
</template>

<div id="app"></div>
```

- __JS__

```javascript
new Vue({
  el: '#app',
  template: '#main',
  data() {
    return {
      show: 1==11,
      obj: null
    }
  },
  mounted(){
    var comp = this
    setTimeout(function(){
      comp.obj = {a:'item a'}
      comp.show = true
    },3000)
  }
});
```

**update: the bug is not only on v-ons-list but on every child of v-ons-page. so this is a v-ons-page's bug**

**Comment by 4lyn** [comment]
Same kind of dirty fix as in #2512 seems to work for info

> Interestingly, if you put the `<div v-for="x in stuff" :key="x">{{x}}</div>` into another `<div>` element, everything will work as expected.
