### ISSUE TITLE
IOS12 Tabbar bottom panel get stuck

### ISSUE THREAD

**Issue by Warlone** [OnsenUI/OnsenUI#2546]
__Environment__
iPhone6, IOS.12, Cordova

Onsen UI Version:

-2.10.4

Framework:

React 16.4.1

Framework binding:

- 

Additional libraries:

Redux

Platform:

IOS.12 

__Encountered problem__

Inside Page with the Tabbar (top+bottom panels): after focus on input (keyboard sliding to view) and changing focus (keyboard sliding to hide) top panel stays at the same position. Sometimes it goes back (down), but not to the 0 bottom position, looks like a slow CPU of iPhone6 can finish some transitions.

__How to reproduce__

**Comment by zabojad** [comment]
@Warlone I'm experiencing the same issue. Did you solve it?
