### ISSUE TITLE
splitView.toggle() Deprecated

### ISSUE THREAD

**Issue by GalawynRM** [OnsenUI/OnsenUI#255]
Good morning,
You marked splitView.toggle() as deprecated, will this functionality be replaced?
When I'm in collapsed mode, how I can via code expand the secondary page, currently I'm using splitView.toggle() on a toolbar button (mimic a sliding menu).

**Comment by ekiyanov** [comment]
any chance to see how to use ng-if to switch to sliding menu ?

**Comment by aks0020** [comment]
:+1:
