### ISSUE TITLE
ons-gesture-detector for React availability

### ISSUE THREAD

**Issue by fondberg** [OnsenUI/OnsenUI#2556]
Is it possible to use the ons-gesture-detector for React somehow or is this not implemented yet?

**Comment by fondberg** [comment]
anyone?

**Comment by emccorson** [comment]
This appears not to have been implemented yet.

**Comment by anthoviso** [comment]
up

**Comment by emccorson** [comment]
I've had a bit more time to look into this now...

I can't figure out why a React binding was never implemented for `ons-gesture-detector`. I'm hoping it's just that nobody ever got round to it, not that there's some hidden difficulty in the implementation.

As far as I can tell, to implement this all that is needed is to:

1. Create a new component `GestureDetector` that extends `SimpleWrapper`.
2. In the `componentDidMount` hook, add event listeners to the `ons-gesture-detector` DOM node that bind the gesture events to the React class's props e.g. `onTap` gets bound to the `tap` event.
3. In the `componentDidUnmount` hook, remove the event listeners.

The [Carousel](https://github.com/OnsenUI/OnsenUI/blob/master/bindings/react/src/components/Carousel.jsx) component does the same thing so it should be straightforward to copy that.

I'll try to implement this when I can. Probably by the end of next month if there aren't any major hidden snags.
