### ISSUE TITLE
changing left-center-right component sort direction

### ISSUE THREAD

**Issue by rezaerami** [OnsenUI/OnsenUI#2557]
hi there,
I'm making a CSS overwrite to add it to this awesome UI framework to make it RTL,
but it seems the framework itself, sorts components by their class names from left to right;
is there any way to change the sort?
like adding a class name to the component parent or prop like isRTL={true} then component decide to sort children in direction.

also, I think the best way to sort is child nodes of a parent component is to sort them by children order itself, so if there were any way to disable auto sort, please tell me

if is there anything for this I'll write CSS overwrites and send it to you
best regards.

**Comment by emccorson** [comment]
Sorry, I'm not sure I understand the question. Which components are being sorted by class name? Can you give an example?

**Comment by emccorson** [comment]
Closing as no response.
