### ISSUE TITLE
Core | Top Toolbar disappears on iOS 12

### ISSUE THREAD

**Issue by JamalAPI** [OnsenUI/OnsenUI#2559]
__Environment__

Onsen UI Version:
2.10.5
- 

Framework:
JavaScript
- 

Framework binding:

Additional libraries:

- 

Platform:
iOS 12.0
- 

__Encountered problem__

When an input is selected that pushes the page up, the top Toolbar disappears and and iOS native text of time and cellular signal info is overlaid by text from the page.
Tried https://github.com/cjpearson/cordova-plugin-keyboard but it did not resolve issue.

__How to reproduce__
Create a page with toolbar.
Add 10 several input text of type text, so page scrolls on keyboard display.
Build and run on actual iOS device like iPhone 7 with iOS.
Open page.
Focus on an input field at bottom page, keyboard is displayed; toolbar disappears, iOS top text is overlaid by text from page producing somewhat of a corrupted display.

**Comment by jamalassaf** [comment]
Used **cordova-plugin-keyboard** plugin to resolve issue.

document.addEventListener("deviceready", onDeviceReady, false);

function onDeviceReady() {
	Keyboard.shrinkView(true);
	Keyboard.hideFormAccessoryBar(false);
}

**Comment by jamalassaf** [comment]
Using the above options have side effects. The (tapped) focused element before iOS keyboard is shown loses focus and caret on input elements is not shown within the input area.
For now, I removed the cordova-plugin-keyboard plugin and let iOS handle the input in the UIWebView.

Hopefully, the Onsen team can take a look at this and provide a fix!
