### ISSUE TITLE
React | First option get lost when the <Select> component are a direct child of <ListItem>

### ISSUE THREAD

**Issue by cillajelf** [OnsenUI/OnsenUI#2560]
**Environment**

```
[Core]
  onsenui version 2.10.5
  
[Framework]
  react 16.5.0

[Framework binding]
 react-onsenui latest

[Browser]
  Desktop - Chrome
  Android
  IOS

```
**Encountered problem**
 The first option in the Select-dropdown got lost in version 2.10.5.
When the Select component is a direct child of the ListItem component, the first option will not be displayed.
Workaround: My workaround is wrapping the Select component in a div. But it causes other problems (read: testing).

**Link to the code in Stackblitz**
  https://stackblitz.com/edit/react-dnbyti

**Code Problem** 
```
<List>
  <ListItem>
    <Select>
      {users.map(user => (
      <option key={user.id} value={user.id}>
        {user.name}
      </option>
        ))}
    </Select>
  </ListItem>
</List>

```
**Code Workaround** 
 
 ```
<List>
 <ListItem>
  <div>
    <Select>
      {users.map(user => (
      <option key={user.id} value={user.id}>
        {user.name}
      </option>
        ))}
    </Select>
    </div>
  </ListItem>
</List>

```

**Comment by aterjung** [comment]
are there any updates to this? I encounter the same problem which took hours to track down to the ListItem.
