### ISSUE TITLE
Vue | KeepAliveTabbar is not shown

### ISSUE THREAD

**Issue by sin-tanaka** [OnsenUI/OnsenUI#2563]
__Environment__

Onsen UI Version:

- 2.10.0

Framework:

- vue.2.5.0

Framework binding:

- VueOnsenUI

__Encountered problem__

[vue's example KeepAliveTabbar](https://github.com/OnsenUI/OnsenUI/blob/master/bindings/vue/examples/components/TabbarKeepAlive.vue) is not working

__How to reproduce__

1. cd bindng/vue && yarn run dev --> it's worked.
2. click MainList > KeepAliveTabbar.
3. shown header & footer tab , but tabbar-content is not shown.

![2018-10-17 15 43 26](https://user-images.githubusercontent.com/22007979/47067390-2ff45f00-d224-11e8-9f0c-195d34eefa0d.png)

**Comment by emccorson** [comment]
I'm looking back at this issue as part of the upgrade to support Vue 3, as I am currently fixing different bugs in TabbarKeepVisible that only appear when using Vue 3. I will get to this bug for Vue 2 once the Vue 3 upgrade is finished.

For reference, the bug only seems to appear when the tabbar is wrapped in a page:

```
<v-ons-page>                            // <----- this causes the problem
  <v-ons-tabbar>
    <template v-slot:pages>
      <keep-alive>
       ...
```

If the tabbar does not have a parent page, then the content is displayed.

My guess is that the page's `show` is not being called at the right or not being called at all.

I'll investigate further when I come to fix this bug.

**Comment by emccorson** [comment]
Appears to have been broken by 00ab4ccdedffffbbe6b1abb3789760c89859da1a.

**Comment by emccorson** [comment]
This was broken by the commit mentioned in my previous comment. That commit fixes some flickering which I am reluctant to touch since this has proved to be difficult in the past. As a workaround, you just need to set the `shown` attribute on your component. I have updated the examples to show this.

````vue
<template slot="pages">
  <keep-alive>
    <div shown :is="currentPage"></div>
  </keep-alive>
</template>
````
