### ISSUE TITLE
Core |  issue: Outline Icons do not work anymore with Font Awesome 5.2

### ISSUE THREAD

**Issue by salim7** [OnsenUI/OnsenUI#2568]
__Environment__

  
```
[Core]
  onsenui latest
  
[Platform]
  Desktop - Ubuntu 64-bit

[Browser]
  Desktop - Firefox 62.0 on Ubuntu 64-bit
```

__Encountered problem__
  

__How to reproduce__
  

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<p><ons-icon icon="fa-star"></ons-icon> Everything fine here</p>
<p><ons-icon icon="fa-star-o"></ons-icon> This star should be outlined (worked in a previous version)</p>
<p><div class="ons-icon fa-star fas"></div> This is probably what we want for the new Font Awesome Version 5.2</p>
```

- __JS__

```javascript
```

**Comment by emccorson** [comment]
In FontAwesome v5, `fa-star-o` was [merged](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4#name-changes) with `fa-star` so now they are both called `fa-star`. To get an outlined star you need to use the `far` class.

```html
<ons-icon icon="fa-star"></ons-icon>                       <!-- solid star -->
<ons-icon class="far" icon="fa-star"></ons-icon>      <!-- outlined star -->
```

This doesn't actually work for the current release of OnsenUI but it has been fixed (#2595) and will be included in the next release. If you need the fix now, clone this repo and build from master.
