### ISSUE TITLE
Vue | expandable v-ons-list | isExpanded property not properly synced

### ISSUE THREAD

**Issue by bassiebulk** [OnsenUI/OnsenUI#2576]
The problem marked as solved in https://github.com/OnsenUI/OnsenUI/issues/2493 is still occuring in 2.10.5.

__Onsen UI Version:__
2.10.5

__How to reproduce:__
In this example when expanding the Expandable ListItem with the Button it works oke.
The ListItem expands when isExpanded is synced.
When expanding by tapping/clicking on the ListItem itself the isExpanded-property is not updated properly.

__How to reproduce:__
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<template id="main">
  <v-ons-page>
    <center>
      <br><br>The isExpanded-property is {{ isExpanded }}!<br><br>
      <v-ons-button @click="isExpanded = !isExpanded">Toggle expansion</v-ons-button>
      <br><br><br>
    </center>

    <v-ons-list>
      <v-ons-list-item expandable :expanded.sync="isExpanded">
        Tap to expand
        <div class="expandable-content">Expandable content</div>
      </v-ons-list-item>
    </v-ons-list>
    
  </v-ons-page>
</template>

<div id="app"></div>
```

- __JS__

```javascript
new Vue({
  el: '#app',
  template: '#main',
  data() {
    return {
      isExpanded: false
    }
  }
});
```

**Comment by emccorson** [comment]
This fix is now released in vue-onsenui 2.6.2.
