### ISSUE TITLE
When I quickly pop page from pageStack, a white screen appears.

### ISSUE THREAD

**Issue by lsc949982212** [OnsenUI/OnsenUI#2578]
onsenui v2.8.3
cordova 6.4.0
webview in android(all versions)
When I quickly pop page from pageStack, a white screen appears,and there are no javascript errors in console

**Comment by wcmhc** [comment]
Do you have a code sample that recreates this issue, preferably on the OnsenUI Playground (https://onsen.io/playground/) or your code?
If not, what is the timing/flow of the popping? Are you doing it inside pre/post events, in the page that was pushed, etc?

**Comment by lsc949982212** [comment]
<template>
    <div style="height: 100%;">
        <v-ons-navigator id="app" swipeable
                         :page-stack="$store.state.pageStack"
                         @push-page="$store.state.pageStack.push($event)">
        </v-ons-navigator>
        <v-ons-alert-dialog v-if="listLog[0]" modifier="rowfooter"
                            :visible.sync="alertDialog1Visible">
            <span slot="title">{{$t('l.app.updateApp')}}({{listLog[0].version}})</span>
            <ul>
                <li style="text-align:left" v-for="item in listLog[0].list">{{item}}</li>
            </ul>
            <template slot="footer">
                <v-ons-alert-dialog-button style="color: #a8a8a8" @click="alertDialog1Visible = false">{{$t('l.app.updateLater')}}
                </v-ons-alert-dialog-button>
                <v-ons-alert-dialog-button @click="updateAppVersion">{{$t('l.app.updateAppNow')}}</v-ons-alert-dialog-button>
            </template>
        </v-ons-alert-dialog>
        <v-ons-modal :visible="downloading">
            <p style="text-align: center">
                {{$t('l.app.downloadProgress')}} {{downloadProgress}}%
                <v-ons-icon icon="fa-spinner" spin></v-ons-icon>
            </p>
        </v-ons-modal>
    </div>
</template>
-------> App.vue

<template>
    <v-ons-page @show="load()">
        <div>
           
        </div>
    </v-ons-page>
</template>
---------> all pages use this component
then i push every page to a Array by The following methods
['push'](state, data) {
            if (data.wallet) {
                state.currentWallet = data.wallet;
            }
            state.pageStack.push({
                extends: data.page,
                onsNavigatorProps: data.props,
            })
            
        }
--------------> vuex
then i go back by using The following methods
['pop'](state) {
            state.pageStack.pop();
        },
------------------> vuex
If I'm slow, there's no problem, and if I press the return button quickly,the white screen will appear

**Comment by wcmhc** [comment]
I cant recreate it on the playground and I won't be of much further use as I only work with the Core/Plain JS version of the framework

**Comment by lsc949982212** [comment]
I have found the cause of the problem;
![image](https://user-images.githubusercontent.com/26805810/48409571-21dc2480-e777-11e8-880a-2928d140255c.png)
if i change animation fade to none, the problem will be solved, but i need an animation...
