### ISSUE TITLE
Template parse errors when using *onsLazyRepeat

### ISSUE THREAD

**Issue by jcfrane** [OnsenUI/OnsenUI#2579]
Environment:

Onsen UI Version:
**^2.10.5**

Framework:
**Angular 6**

Framework binding:
**ngx-onsenui ^4.2.2**

**Problem Encountered**

Im using OnsLazyRepeat inside template likeso:

`<ons-list *ngIf="transactionHistory$ | async as transactionHistory">
            <ons-list-item *onsLazyRepeat="let item of items; let i = index">
                <div class="center">
                  HAHA
                </div>
              </ons-list-item>
          </ons-list>`

But when I run it it throws an error:

compiler.js:1021 Uncaught Error: Template parse errors:
Binding to event property 'onsLazyRepeatOf' is disallowed for security reasons, please use (sLazyRepeatOf)=...
If 'onsLazyRepeatOf' is a directive input, make sure the directive is imported by the current module. ("    <ons-list *ngIf="transactionHistory$ | async as transactionHistory">
            <ons-list-item [ERROR ->]*onsLazyRepeat="let item of items; let i = index">
                <div class="center">
             "): ng:///PagesModule/TransactionHistoryPage.html@141:27
Property binding onsLazyRepeatOf not used by any directive on an embedded template. Make sure that the property name is spelled correctly and all directives are listed in the "@NgModule.declarations". ("

          <ons-list *ngIf="transactionHistory$ | async as transactionHistory">
            [ERROR ->]<ons-list-item *onsLazyRepeat="let item of items; let i = index">
                <div class="center""): ng:///PagesModule/TransactionHistoryPage.html@141:12
    at syntaxError (compiler.js:1021)
    at TemplateParser.push../node_modules/@angular/compiler/fesm5/compiler.js.TemplateParser.parse (compiler.js:14830)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._parseTemplate (compiler.js:24018)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileTemplate (compiler.js:24005)
    at compiler.js:23948
    at Set.forEach (<anonymous>)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileComponents (compiler.js:23948)
    at compiler.js:23858
    at Object.then (compiler.js:1012)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (compiler.js:23857)

I really don't know if this is a bug or that I did something wrong. But I think its related to this issue:
https://github.com/500tech/angular-tree-component/issues/223

Thanks!

**Comment by puku0x** [comment]
@jcfrane 
Thank you for your report!
I will investigate the problem later.

**Comment by puku0x** [comment]
@jcfrane 

The error message said Angular compiler misunderstood that `onsLazyRepeatOf` was a some kind of events like `onclick` then it suggested `(sLazyRepeatOf)`, which could be written `on-sLazyRepeatOf` (of course no! 🤣no way! )

I think you forgot importing `OnsenModule` to your `AppModule`.
https://stackblitz.com/edit/ngx-onsenui-issues-2579

```ts
@NgModule({
  imports:         [ BrowserModule, CommonModule, OnsenModule ], // <- this is it!
  declarations:    [ AppComponent, Page1Component ],
  entryComponents: [ Page1Component ],
  schemas:         [ CUSTOM_ELEMENTS_SCHEMA ],
  bootstrap:       [ AppComponent ]
})
export class AppModule { }
```

Hope it helps.

**Comment by jcfrane** [comment]
HI you are right.

Can I ask question? This is totally not related but I can't really found answer on the internet and I really need it now. Can I send you an email for it? Thanks!

**Comment by puku0x** [comment]
@jcfrane  Sure! Please do not hesitate to ask me.
