### ISSUE TITLE
ons-tabbar is not working on android 2.3.x

### ISSUE THREAD

**Issue by casuns** [OnsenUI/OnsenUI#258]
While I tried to use the "Tab bar" template on android 2.3.x, As if there is an Bug:

I changed the "IScroll for Android2" settings: Set the "preventDefault" To "true", it's OK. But when I touch the ons-tabbar is not working.

```javascript
// IScroll for Android2
var scroller = new IScroll(content[0], {
	momentum: true,
	bounce: true,
	hScrollbar: false,
	vScrollbar: false,
	preventDefault: true
});
```

![0-1](https://cloud.githubusercontent.com/assets/6754870/4605417/dc1333c4-51e0-11e4-92ca-f840a73f8c53.png)

![0-2](https://cloud.githubusercontent.com/assets/6754870/4605425/0b4aa3f2-51e1-11e4-8408-45f78a1835ba.png)

![0-3](https://cloud.githubusercontent.com/assets/6754870/4605427/10c4d550-51e1-11e4-8dce-76e4402d6522.png)

**Comment by WEREMSOFT** [comment]
I have the same problem, This bug was fixed for android 2.3.x? Thanks
