### ISSUE TITLE
bug: docs link error - layout guide

### ISSUE THREAD

**Issue by pashute** [OnsenUI/OnsenUI#2586]
Problem with docs: https://onsen.io/v2/api/js/ons-row.html 

Link to Layout Guide takes me to the Themes page.

**Comment by MetalDent** [comment]
Hi, anyone working on this?

**Comment by emccorson** [comment]
Nobody is working on this right now, so feel free to assign yourself if you
want to submit a fix!

**Comment by MetalDent** [comment]
Okay, can you please give some more information about the issue?

**Comment by MetalDent** [comment]
Okay I found the problem. In above mentioned link when you click on "Layouting guide" we are directed to the "Theme Customization" page.
