### ISSUE TITLE
React | Navigator docs

### ISSUE THREAD

**Issue by aiba** [OnsenUI/OnsenUI#2587]
The [`Navigator.replacePage`](https://github.com/OnsenUI/OnsenUI/blob/master/bindings/react/src/components/Navigator.jsx#L177) method does not appear on the  [documentation for React Navigator](https://onsen.io/v2/api/react/Navigator.html).  I had to read the source code to find it.

Does the web site need an update?

**Comment by emccorson** [comment]
@aiba Thank you for the bug report

This is probably an issue with OnsenUI/onsen.io but I'll leave the issue in this repo for now until further investigation.

**Comment by andrewlorenz** [comment]
I've been using onsen/react for about 6months and can confirm the react documentation is very patchy! I typically check the native is docs and/or read the source code. When I find time I'm intending to update some docs and submit a PR

**Comment by MetalDent** [comment]
Hey @andrewlorenz, have you solved this issue?
