### ISSUE TITLE
Urgent: Malicious package inside OnsenUI

### ISSUE THREAD

**Issue by dsignr** [OnsenUI/OnsenUI#2592]
__Environment__

Onsen UI Version:
2.10.5
- 

Framework:
Vue 2.5.16
- 

Framework binding:
None
- 

Additional libraries:
N/A
- 

Platform:
Web, Chrome
- 

__Encountered problem__
Malicious package installed along with Onsen UI

__How to reproduce__
Simply install OnsenUI and run `npm audit`

![image](https://user-images.githubusercontent.com/5097028/49281023-806b0780-f4c6-11e8-8dcb-9547111d343f.png)

I found this a few days ago, but never really paid close attention until now. It's coming from the `flatmap-stream` package, which is used by `event-stream` used by OnsenUI.
Sincerely urge you to fix this asap to prevent other users from being infected.

More details on this issue here:
https://github.com/dominictarr/event-stream/issues/116

Cheers.

**Comment by emccorson** [comment]
This should be fixed by #2590 which is now released in v2.10.6.

**Comment by dsignr** [comment]
Thank you for the super fast response on fixing this. <3
