### ISSUE TITLE
React | Navigator issue: resetPage causes screen to go blank

### ISSUE THREAD

**Issue by emccorson** [OnsenUI/OnsenUI#2594]
__Environment__

  
```
[Core]
  onsenui latest
  
[Framework]
  react 15.4.2

[Framework binding]
 react-onsenui latest

[Platform]
  Desktop - Ubuntu 64-bit

[Browser]
  Desktop - Firefox 63.0 on Ubuntu 64-bit
```

__Encountered problem__
`resetPage` method of `Navigator` causes screen to go blank rendering the app unusable.

__How to reproduce__
1. Click 'Reset page'.
2. Notice the screen go blank.

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<div id="app"></div>
```

- __JS__

```jsx
const App = () => {
  
  const page = {
    buttonFunction: navigator => navigator.resetPage(page),
    buttonText: 'Reset page'
  }
  
  const renderPage = (page, navigator) =>
    <Ons.Page>
      <Ons.Button onClick={() => page.buttonFunction(navigator)}>{page.buttonText}</Ons.Button>
    </Ons.Page>
  
  return (
    <Ons.Navigator
      renderPage={renderPage}
      initialRoute={page}
    />
  );
}

ons.ready(function() {
  ReactDOM.render(<App />, document.getElementById('app'));
});
```

**Comment by cgruca** [comment]
Hi @emccorson, sorry for necroing old thread...

I'm new to onsen and react and am having the exact same issue with the blank page appearing after resetpage is called.
How exactly does one set a key in renderPage?

This is how I have my project setup
in App.js

`renderPage(route, navigator) {
    const props = route.props || {};
    props.navigator = navigator;
    const key = route.key;

    return React.createElement(route.component, key, props);
  }

render() {
    if(this.state.isLoading){
      return (
        <Navigator animation="lift" 
          initialRoute={{
            component: Loading, 
            key: 'loading-screen',
            props: {
              onboardedUser: this.state.onboardedUser, 
              password: this.state.password
            }}} 
          renderPage={this.renderPage} 
        />
      )
    }
`
  

then in my other components I would add in a new page by doing
`this.props.navigator.pushPage({component: Saved, key: 'saved-screen'});`

But that doesn't seem to work.
Also tried passing it via props like so, but no luck:
`this.props.navigator.pushPage({component: Saved, props: {key: 'saved-screen'}});`

Any help would be appreciated!
"onsenui": "^2.11.2",
"react": "^17.0.2",

**Comment by emccorson** [comment]
It might be easier to do this with JSX instead of `React.createElement`. Also,
instead of setting a key manually, you might use variable that incremements
whenever a key is set to ensure you always get a unique key (I ran into problems
with duplicate keys when trying to pass the key as a prop).

Here is an example:

```javascript
const Page1 = ({navigator}) => (
  <Page>
    <Button
      onClick={() => navigator.pushPage({component: Page2})}
    >
      Push page 2
    </Button>
  </Page>
);

const Page2 = ({navigator}) => (
  <Page>
    <Button
      onClick={() => navigator.resetPage({component: Page1})}
    >
      Reset to page 1
    </Button>
  </Page>
);

let keyIndex = 0;

class App extends React.Component {

  renderPage(route, navigator) {
    const Component = route.component; // make sure Component is capitalized
    const key = keyIndex++; // get a unique key and increment key index

    return <Component key={key} navigator={navigator} {...route.props} />
  }

  render() {
    return (
      <Navigator
        renderPage={this.renderPage}
        initialRoute={{component: Page1}}
      />
    );
  }
}
```
@cgruca

**Comment by cgruca** [comment]
Oh sweet, the keyIndex strategy worked!
Thank you so much @emccorson!
