### ISSUE TITLE
Add the name of the page about to be pushed in the prepush event

### ISSUE THREAD

**Issue by rallyemobile** [OnsenUI/OnsenUI#2600]
Hello,

Prepush event without the name of the page about to be pushed is not very useful. For example say that a list of pages is displayed to the user, but some pages are not allowed, according to the state of the application. I cannot know whether I must cancel the event, if I dont know the page to come. 

Thanks in advance for your help.

**Comment by emccorson** [comment]
I think this is a good idea.

`postpush` has `event.enterPage` so a solution would be to add `event.enterPage` to `prepush` as well.

**Comment by jfbouzereau** [comment]
postpush has event.enterPage because the page is already loaded. In the case of prepush, the page is not already there. We cannot have a reference to it, but we can have the name of the page.
