### ISSUE TITLE
Improve documentation for animation-options

### ISSUE THREAD

**Issue by emccorson** [OnsenUI/OnsenUI#2601]
The animation-options documentation doesn't properly explain what options there are and what values those options can have.

From a preliminary search of the code base, these appear to be the available options:

```
It looks like there are three options: duration, delay and timing.

duration specifies the total time the animation takes from beginning to end.

delay specifies the time to wait before starting the animation.

timing specifies how intermediate values are calculated i.e. how the animation gets from the beginning to the end. I found occurrences in the codebase of three values for this: linear, ease-in and cubic-bezier. I believe these correspond to values for the CSS transition-timing-function (https://developer.mozilla.org/en-US/docs/Web/CSS/transition-timing-function).
```
(originally posted at https://community.onsen.io/topic/3422/ons-carousel-swipe)

**Comment by MetalDent** [comment]
Hi, is anyone working on this?

**Comment by emccorson** [comment]
@MetalDent No one is working on this at the moment. Please feel free to assign yourself if you would like to work on it.

**Comment by MetalDent** [comment]
@emccorson okay, where do you think this info will go?

**Comment by emccorson** [comment]
@MetalDent The documentation should go here: https://github.com/OnsenUI/OnsenUI/blob/13782fdde37915c477d5e125bd7d9bef4a76ecf1/core/src/elements/ons-carousel.js#L208

Before adding the options as documentation, please verify which options work and what they do by setting the `animation-options` attribute of `ons-carousel` in this example: https://onsen.io/playground/?framework=vanilla&category=reference&module=carousel

**Comment by MetalDent** [comment]
@emccorson I added `animation-options={duration: 0.2, delay: 1, timing: ease-in}` in the `<ons-carousel>` but there is no change in the behaviour so I think these options don't work.
