### ISSUE TITLE
Core | Notification issue: submitOnEnter = false failure

### ISSUE THREAD

**Issue by rtsawyer5** [OnsenUI/OnsenUI#2618]
__Environment__

  
```
[Core]
  onsenui latest
  
[Platform]
  Desktop - Windows 10 64-bit

[Browser]
  Desktop - Chrome 71.0.3578.98 on Windows 10 64-bit
```

__Encountered problem__
  When using the ons.notification.prompt option submitOnEnter, if set to false, an error is produced and the callback is not launched.

__How to reproduce__
  set submitOnEnter = false in ons.notification.prompt options

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<ons-page>
  <ons-button onclick="showAlert()">Alert</ons-button>
  <ons-button onclick="showConfirm()">Confirm</ons-button>
  <ons-button onclick="showPrompt()">Prompt</ons-button>
  <ons-button onclick="showToast()">Toast</ons-button>
</ons-page>
```

- __JS__

```javascript
var showAlert = function() {
  ons.notification.alert('Alert!');
};

var showConfirm = function() {
  ons.notification.confirm('Confirm!')
};

var showPrompt = function() {
  ons.notification.prompt('Prompt!',{
    submitOnEnter : false
  })
    .then(function(input) {
      var message = input ? 'Entered: ' + input : 'Entered nothing!';
      ons.notification.alert(message);
    });
};

var showToast = function() {
  ons.notification.toast('Toast!', {
    timeout: 2000
  });
};
```

**Comment by emccorson** [comment]
Thanks for the bug report.

I confirmed that this bug is showing up on the playground. I also noticed that the cursor doesn't go into the input automatically if `false` is set.

I'm not seeing any error though. What was the error you were getting @rtsawyer5 ?

**Comment by rtsawyer5** [comment]
In the console, when the prompt is submitted the following error pops for me:
﻿﻿﻿﻿```
Uncaught (in promise) TypeError: Cannot read property 'value' of undefined at notification.js.195
```
