### ISSUE TITLE
Poor written patterns

### ISSUE THREAD

**Issue by GoGross** [OnsenUI/OnsenUI#2619]
Why don't you drop several patterns such as navigation and data binding and let developers choose from a Vanilla approach how they want to integrate, its a fantastic UI but your implementation of both angulars, and react leave a lot to be desired, just when you thought you could jump to the JS version, you too try too much DOM manipulation, suggestion: let JS version be a component library, drop navigation, data binding etc, thats the path IONIC and the rest are taking now, then this would become the best framework. VANILLA.

![image](https://user-images.githubusercontent.com/1701383/51441825-76070600-1cde-11e9-9761-d318274452ab.png)

**Comment by emccorson** [comment]
@GoGross Why did you close this?
