### ISSUE TITLE
isIPad() / IPad Pro

### ISSUE THREAD

**Issue by reydajp** [OnsenUI/OnsenUI#2621]
Hi
I have an issue with methods to detect current platform.

`isIPad()` returns `false`  
 `isPhone()`  returns `true`  

with the last IPad Pro 3rd generation but not with the 2nd generation.

I'm using the last vue-onsen version (2.6.2), onsen (2.10.6) and build with xcode 10. 

Thanks

**Comment by emccorson** [comment]
I don't have an iPad (2nd or 3rd generation) so to help fix this could you send the following information please?

I'm looking for the user agent string from your browser on both 2nd and 3rd generation iPads. You can get it in a browser by running `navigator.userAgent` in the console.

The way `isIPad` currently works is by search the user agent string for `"iPad"`. I'm guessing the 2nd generation user string contains it but the 3rd generation one doesn't.
