### ISSUE TITLE
Download issue on Firefox: "This file os not commonly downloaded"

### ISSUE THREAD

**Issue by leolux** [OnsenUI/OnsenUI#2622]
I customized the theme on https://onsen.io/theme-roller/ and then clicked on the download button. Firefox blocks the download of the file "onsen-css-theme.zip" because of the security issue.

I don't know what lets Firefox think that this download is a security risk.

**Comment by emccorson** [comment]
I'm not able to reproduce this on Firefox 65 so I think it's probably not an Onsen error.

I'll close this for now, but if it is still a problem, please comment and I'll re-open it.
