### ISSUE TITLE
Guide for the theme roller

### ISSUE THREAD

**Issue by leolux** [OnsenUI/OnsenUI#2623]
How to use apply the files downloaded from https://onsen.io/theme-roller/?

Currently my main.js file contains these lines:
```
import 'onsenui/css/onsenui.css';
import 'onsenui/css/onsen-css-components.css';
```
How should the files onsen-css-components.min.css and theme.css be added to a project?

**Comment by emccorson** [comment]
Sorry for the delay in replying.

When you want to use a theme created in the theme roller, you should
keep the original onsenui.css file:

import 'onsenui/css/onsenui.css';

However you should delete the old onsen-css-components.css line.Sorry
for the delay in replying.

When you want to use a theme created in the theme roller, you should
keep the original onsenui.css file:

import 'onsenui/css/onsenui.css';

However you should delete the old onsen-css-components.css line.

Then from the new downloaded theme, you should import theme.css and
the new onsen-css-components.css file.

Then from the new downloaded theme, you should import theme.css and
the new onsen-css-components.css file.

So all in all, you end up with three files: onsenui.css, theme.css,
and onsen-css-components.css (the new one).
