### ISSUE TITLE
Scroll issue / iPad Pro 

### ISSUE THREAD

**Issue by reydajp** [OnsenUI/OnsenUI#2624]
Onsen UI Version:
the latest (2.10.2)

 Framework:
Vue 2.5.22

 Framework binding:
vue-onsenui 2.6.2
 
 Platform:
iOS 12.1.3  ( iPad 3rd gen 12.9 inch)

 Encountered problem

I have a page with with splitter. Inside `splitter-content` I have an infinity scroll and a pull-hook.
The problem is when I launch the app on portrait, the scroll is working but when I switch on 
landscape, the scroll not working anymore, even If I return on portrait.

I have not this problem on simulator, iPhone or Android device. I don't know about older iPad.

Any ideas?

Thanks

**Comment by emccorson** [comment]
Can you make an example that replicates the problem? https://onsen.io/playground/

I tested the lazy scroll example from the examples directory using a 3rd gen iPad Air (iPadOS 13.1.2) but everything seemed to be working fine.
