### ISSUE TITLE
cordova windows 8 visual studio - dont get call property of null or undefined

### ISSUE THREAD

**Issue by GuilhermeLessa** [OnsenUI/OnsenUI#2627]
Building succeeded but OnsenUi error on open and run app:

### Dont get call property of null or undefined reference.

I dont have experience with builds for windows. Some idea?

**_OnsenUi doc says that the browser support is only to Android 4.4.4+, iOS 9+, Chrome and Safari. Cordova Windows platform is a internet explorer or edge webview rigth? Maybe this is problem?_**

Monaca 3.1.0
OnsenUi 2.10.6
Cordova 8.1.2  with Cordova Windows platform 6.0.1
Run Windows 8.1 (Debug x64 local machine) on Visual Studio 2015 installed on Windows 10

```
SCRIPT5007: Unhandled exception at line 11195, column 5 in ms-appx://br.com.tiempresarial.ticorporativo/www/lib/onsenui/js/onsenui.js
0x800a138f - Erro em tempo de execução do JavaScript: Não é possível obter a propriedade 'call' de referência indefinida ou nula
```

Visual Studio Output:
```
WWAHost.exe' (Script): Loaded 'Script Code (MSAppHost/2.0)'. 
Invalid sourcemap url data:application/json;charset=utf-8;base64,
0x800a01b6 - Erro em tempo de execução do JavaScript: O objeto não oferece suporte à propriedade ou método 'entries'
Exception was thrown at line 9293, column 5 in ms-appx://br.com.tiempresarial.ticorporativo/www/lib/onsenui/js/onsenui.js
0x800a01b6 - Erro em tempo de execução do JavaScript: O objeto não oferece suporte à propriedade ou método 'entries'
Unhandled exception at line 11195, column 5 in ms-appx://br.com.tiempresarial.ticorporativo/www/lib/onsenui/js/onsenui.js
0x800a138f - Erro em tempo de execução do JavaScript: Não é possível obter a propriedade 'call' de referência indefinida ou nula
```

<img src="https://i.ibb.co/7XTm7Z1/onsenui-error.png">

### On debug see all builtIn propertys are undefined:
<img src="https://i.ibb.co/k3WP9Dw/onsenui-error2.png">

### builtIn.remove is loaded with Native object, where are window object:
`Element_remove: window.Element.prototype['remove']`

**Comment by emccorson** [comment]
I think this probably isn't a bug, and the question has already been asked [here](https://community.onsen.io/topic/3473/cordova-windows-8-visual-studio-builtin-remove-dont-get-call-property-of-null-or-undefined) so I'll close this issue.
