### ISSUE TITLE
Memory leak in Navigator

### ISSUE THREAD

**Issue by rj-david** [OnsenUI/OnsenUI#2628]
__Environment__

Onsen UI Version:
2.10.6
- 

Framework:
React 16.8.1
- 

Framework binding:
react-onsenui 1.11.2
- 

- 

Platform:
Chrome (Ubuntu and Mac)
- 

__Encountered problem__
We are getting this error message when loading our Navigator
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in Navigator (created by AppNavigator)
    in AppNavigator (created by Tabbar)
    in div (created by Tabbar)
    in div (created by Tabbar)
    in ons-tabbar (created by Tabbar)
    in Tabbar (created by TabNavigation)
    in div (created by Page)
    in ons-page (created by Page)
    in Page (created by TabNavigation)
    in TabNavigation (created by ComponentWithMemoizeCache)
    in ComponentWithMemoizeCache (created by ComponentWithProcessing)
    in ComponentWithProcessing (created by ReactMeteorDataComponent)
    in ReactMeteorDataComponent (created by Navigator)

```

**Comment by emccorson** [comment]
Can you please reproduce this in the playground? https://onsen.io/playground/

Or if it can't be done in the playground because it's a local setup thing, please link to a repo that reproduces the problem.

**Comment by rj-david** [comment]
@emccorson, there were changes in our app now and I am no longer seeing the error in console when running our tests. I'll find some time to replicate to a sample repo
