### ISSUE TITLE
Cordova and tabbar and separate HTML files

### ISSUE THREAD

**Issue by ryanjanderson** [OnsenUI/OnsenUI#2629]
I've encountered an issue with using cordova, tabbar, and pages in separate HTML files. I am able to workaround the issue, but I am hoping my observations will help the team or other developers doing the same thing.

__Encountered problem__
Pages not being loaded, CORS errors in console. This is on iOS simulator in application wrapped by cordova.  Pages do exist and are local. Everything works outside of cordova.

__How to reproduce__
1. Root HTML page of application contains a tabbar
2. Each tab contains separate HTML files (./pages/home.html, ./pages/help.html, etc)
3. Wrap in cordova, run in iOS Simulator.

__How to work around__
1. Use cordova-plugin-wkwebview-file-xhr plugin.
2. Don't try to load HTML files until after cordova deviceready event.

Essentially on ready() use a navigator to push the page that contains the tabbar that contains other pages.

--
What I see happening is that the tabbar is using XHR to load page.  The page URL is resolved to the file:// protocol, which is not allowed on iOS in the wkwebview.  The plugin cordova-plugin-wkwebview-file-xhr polyfills XHR to intercept file:// protocol and switch to a file reader. 

However this polyfill is not in place until after the cordova deviceready event has been issued. My assumption is that the tabbar web component is utilizing XHR before this plugin is in place.

I think the ask would be to not use XHR for loading "file://" urls or to delay the web component until after the ready() event.

**Comment by emccorson** [comment]
If you use cordova-ios@6 you can work around this now with WKURLSchemeHandler:

```
<preference name="scheme" value="app" />
<preference name="hostname" value="localhost" />
```

https://cordova.apache.org/howto/2020/07/18/uiwebview-warning.html

So if you use cordova-ios@6, you don't need cordova-plugin-wkwebview-file-xhr; you can just add the above lines (after defining your own custom URL scheme) and it will work fine.

I'll close this now since we can keep using XHR for the time being.
