### ISSUE TITLE
Bug: ons-icon fa-spinner, fa-spin doesnt work

### ISSUE THREAD

**Issue by devWaleed** [OnsenUI/OnsenUI#2633]
I am using ons-icon in Vue cli version of the framework.

if I change icon to spinner, spin i.e fa-spinner, fa-spin. It shows the spinner, but doesn't rotate it.

**Comment by emccorson** [comment]
I confirmed this bug is reproducible.

It looks like `ons-icon` has some code where even if `class="fa-spin"` the class is getting removed during compilation.

**Comment by emccorson** [comment]
I just realised that we already have a spin attribute that can be added to
ons-icon to make any icon spin:

<ons-icon
  icon="md-face"
  spin>
</ons-icon>

It looks the same as fa-spin so unless you think there is a specific reason
we should add fa-spin, I think we can get away with leaving it out for now.

What do you think? @devWaleed

**Comment by devWaleed** [comment]
@emccorson I just missed that attribute while reading docs. It works perfectly!
