### ISSUE TITLE
[2.10.7] Cannot find module 'onsenui'

### ISSUE THREAD

**Issue by rj-david** [OnsenUI/OnsenUI#2641]
New version release 2.10.7 is missing the main onsenui.js file

**Comment by adeoy** [comment]
Same problem :c
I think we can use the 2.10.6 js version.

**Comment by ubrt** [comment]
Same here. Version 2.10.6 is also not working for me.

**Comment by perkinsjr** [comment]
@ubrt and @rj-david  and @adeoy 

Using 2.10.6 works fine the reason 2.10.7 is broken is the onsenui.min.js and onsenui.js are missing from the repo.

 <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/onsenui@2.10.6/css/onsenui.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/onsenui@2.10.6/css/onsen-css-components.min.css">
    <script src="https://cdn.jsdelivr.net/npm/onsenui@2.10.6/js/onsenui.min.js"></script>

@MonacaCI you are missing the js files for V 2.10.7 released.

**Comment by asial-matagawa** [comment]
@rj-david @adeoy @ubrt @perkinsjr 
Thank you for reporting, I reverted `onsenui@latest` to `2.10.6` now.
```
$ npm dist-tag ls onsenui
latest: 2.10.7

$ npm dist-tag add onsenui@2.10.6 latest
+latest: onsenui@2.10.6

$ npm dist-tag ls onsenui
latest: 2.10.6
```

We will release `2.10.8` later.
