### ISSUE TITLE
https://community.onsen.io/ is not reachable -insecure 

### ISSUE THREAD

**Issue by jamalassaf** [OnsenUI/OnsenUI#2644]
I know this is not a bug report in Onsen code, but for the past 4 days, I am getting the following when trying to open **community.onsen.io** website. 

Here what I get in Chrome. Other browsers display similar messages.

**Your connection is not private
Attackers might be trying to steal your information from community.onsen.io (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_DATE_INVALID**
 
Help improve Safe Browsing by sending some system information and page content to Google. Privacy policy
community.onsen.io normally uses encryption to protect your information. When Google Chrome tried to connect to community.onsen.io this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be community.onsen.io, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

**You cannot visit community.onsen.io right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.**

**Comment by emccorson** [comment]
Thanks for the report. The site should be back up tomorrow.
