### ISSUE TITLE
v-ons-input number type bug

### ISSUE THREAD

**Issue by devWaleed** [OnsenUI/OnsenUI#2649]
You can check this here: https://onsen.io/v2/api/vue/v-ons-input.html#

If you give input a type parameter with value "number", i.e:

<v-ons-input type="number" placeholder="Input your name" float v-model="name">
</v-ons-input>

It will still allow you to enter character 'e' LOL!

![eee](https://user-images.githubusercontent.com/4759525/58241798-16416a00-7d67-11e9-8710-f6d9a1b5e6e9.PNG)

**Comment by emccorson** [comment]
Thanks for the bug report @devWaleed. This is a weird one...

First of all, the bug appears in the plain JS version of Onsen UI as well so it isn't a problem with vue-onsenui specifically.

To the actual bug: `ons-input` just wraps a regular `input` so you are actually typing into an `<input type="number" />`. It looks like the regular input should stop anything that isn't a number, but it depends on the browser. I tested it on Firefox 68 and I can still type non-number characters in a non-Onsen UI input.

I will test on a few more browsers to see what's going on. More to follow soon...

**Comment by devWaleed** [comment]
I think this is not a bug. I just discovered this issue when working on an app in browser. 

If we use type=number, then alphanumeric keyboard will not appear on a mobile device so it should not be possible to enter non numeric chars.
