### ISSUE TITLE
ons-pull-hook: content flicker bug again on iOS

### ISSUE THREAD

**Issue by lethe2211** [OnsenUI/OnsenUI#2653]
__Environment__

Onsen UI Version:

- 2.10.8

Framework:

- None

Framework binding:

- None

Additional libraries:

- (Monaca Core FW)

Platform:

- Cordova 7.1.0, iOS 12.2

__Encountered problem__

ons-pull-hook starts shaking up and down when we pull it and keep it for a while.

I think it's a similar (or maybe the same) issue to #1990 and #485.

__How to reproduce__

1. Run [this Monaca project](https://github.com/OnsenUI/OnsenUI/files/3244476/project.zip) in an iOS device 

    Ref: Source code is [here](https://github.com/lethe2211/ons-pull-hook-issue/pull/1/files)

2. In the first screen, swipe the ons-pull-hook slowly and keep it for a while

__Note__

* I tried to reduce the num of list elements so that user cannot scroll ons-page, then ons-pull-hook worked nicely (without any flicker). I guess it's related to Safari's scroll issue or something.
* I also tried to build an Android version with the same source code, but I think it had no issue.

Sorry to disturb, but could you investigate it?
Thanks for your continuous support!

**Comment by fjaeger** [comment]
We experience the same issue.

**Comment by UnKnoWn-Consortium** [comment]
I can confirm this issue still exists in onsenui 2.10.10 on iPhone 6S running iOS 13.3.1 and 13.4. 

https://youtu.be/-w5tvI82Q-8

**Comment by codecat** [comment]
Confirming here as well, looks exactly the same as on the video above. Here's another small example that demonstrates the issue:

- __HTML__

```html
<template id="main">
  <v-ons-page>
    <v-ons-toolbar>
      <div class="center">Issue 2653</div>
    </v-ons-toolbar>
    
    <v-ons-pull-hook :action="refresh" @changestate="state = $event.state">
      <span v-if="state == 'initial'">Pull to refresh</span>
      <span v-if="state == 'preaction'">Release</span>
      <span v-if="state == 'action'">Loading...</span>
    </v-ons-pull-hook>

    <v-ons-list>
      <v-ons-list-item v-for="item in items">{{ item }}</v-ons-list-item>
    </v-ons-list>
  </v-ons-page>
</template>

<div id="app"></div>
```

- __JS__

```javascript
new Vue({
  el: '#app',
  template: '#main',
  data() {
    var items = [];
    for (var i = 0; i < 100; i++) {
      items.push("Item " + i);
    }
    return {
      state: "initial",
      items,
    };
  },
  methods: {
    refresh: function(done) {
      setTimeout(done, 1000);
    },
  }
});
```

**Comment by dibydrams** [comment]
I can confirm this issue still exists in onsenui 2.11.2 on iPhone 12 running iOS 14.2.

I searched a lot and maybe the closest solution to what we would need is this one, even if it looks very old it seems to work well on iPhone, at least better than the current solution:

http://damien.antipa.at/demo/pull-to-refresh/example/

This problem follows us through the years:
- https://github.com/OnsenUI/OnsenUI/issues/994
- https://github.com/OnsenUI/OnsenUI/issues/1990
