### ISSUE TITLE
install only OnsenUI distribution version files

### ISSUE THREAD

**Issue by GuilhermeLessa** [OnsenUI/OnsenUI#2654]
The directory lib/onsenui on Cordova has 9MB.
Unminifyed files and unutilizabe files like a angular-onsenui.js (incrediable 541kb) are includes on my cordova app after build distribution and turn my app size  desnecessaryable.

Has a option to install onsenui distribution version? With just minifyed files and extremally necessary to my application in acord of my app requisits? 

onsenui.min.js -> 316kb
onsenui.js -> almost 3MB 
its so wrong

thanks

**Comment by emccorson** [comment]
You can safely delete whatever you don't need from the `lib` directory of any of the Monaca templates.
