### ISSUE TITLE
active-icon doesn't work at startup

### ISSUE THREAD

**Issue by emccorson** [OnsenUI/OnsenUI#2656]
I set "active-icon" to "app.html" of "Onsen UI V2 Angular Tabbar", but it did not work at app startup."Active-icon" works by tapping the tab.Do you need any settings?If it is a bug, please tell me the workaround.

```
app.html

<ons-page>
  <ons-toolbar [attr.modifier]="modifier">
    <div class="center">Tabbar</div>
  </ons-toolbar>

  <div class="content">
    <ons-tabbar [attr.animation]="animation" position="auto">
      <div class="tabbar__content"></div>
      <div class="tabbar">
        <ons-tab icon="square" label="Tab 1" [page]="first" active-icon="fa-times-circle" active></ons-tab>
        <ons-tab icon="square" label="Tab 2" [page]="second" active-icon="fa-times-circle"></ons-tab>
      </div>
    </ons-tabbar>
  </div>
</ons-page>
```

**Comment by emccorson** [comment]
The bug is being caused by Angular calling `ons-tab`'s `attributeChangedCallback` _after_ the icon has been changed to `active-icon`, thus setting the icon back to the original `icon` setting. Explanation is as follows:

---

`ons-tab#constructor` is broken by Angular. It is a bit complex...........----
The problem is caused by the following lines in `ons-tab.js`

```javascript
  constructor() {
    super();

    if (['label', 'icon', 'badge'].some(this.hasAttribute.bind(this))) {
      // In other bindings
      this._compile();
    } else {
      // In Angular
      contentReady(this, () => this._compile());
    }

    this._pageLoader = defaultPageLoader;
    this._onClick = this._onClick.bind(this);
  }
```

1. [createElement for the new ons-tab element (by Angular)]
2. [ons-tab#constructor]
   - Pushes 9 into contentReady queue
3. [appendChild to parent element (by Angular)]
4. [ons-tab#connectedCallback]
   - Pushes 10 into contentReady queue
5. [setAttribute to the new ons-tab element (by Angular)]
6. [ons-tab#attributeChangedCallback (for icon attribute)
   - Pushes 11 into contentReady queue
7. [setAttribute to the new ons-tab element (by Angular)]
8. [ons-tab#attributeChangedCallback (for label attribute)]
   - Pushes 12 into contentReady queue// ↓ Start consuming contentReady queue
9. [ons-tab#constructor > contentReady > ons-tab#_compile > ons-tab#_updateButtonContent]
   - ons-icon element is created
   - ons-icon's icon attribute is set to ons-tab's icon attribute value
       - null -> ion-icon-home
10. [ons-tab#connectedCallback > contentReady > ons-tab#setActive]
   - ons-icon's icon attribute is changed to ons-tab's active-icon attribute value:
       - ion-icon-home -> ion-icon-square
11. [ons-tab#attributeChangedCallback > case 'icon': > contentReady > ons-tab#_updateButtonContent]
   - ons-icon's icon attribute is changed to ons-tab's icon attribute value:
       - ion-icon-square -> ion-icon-home
12. [ons-tab#attributeChangedCallback > case 'label': > contentReady > ons-tab#_updateButtonContent]
   - ons-icon's icon attribute is changed to ons-tab's icon attribute value
       - ion-icon-home -> ion-icon-home

**Comment by jkon** [comment]
So, i am using the ngx-onsenui package and it hasn't been republished since 2018. How can I get this fix into my project? Is there another way to load the onsenui libraries into angular? (I'm on angular 8, but would like to move to more recent versions soon)
