### ISSUE TITLE
type error of undefined on dataTransfer property of event object

### ISSUE THREAD

**Issue by ghost** [OnsenUI/OnsenUI#2658]
Hello there!

when i try to use onsenui on my vue project, i get undefined on my dataTransfer propery in the event object.
event.dataTransfer will through TypeError of undefined.
worth notice that without using the Onsen on my Vue instance it works fine.
-----------------------------------------------------------
Vue -> 2.6.10
vue-onsen -> 2.6.2
onsen -> 2.10.8

**Comment by emccorson** [comment]
Can you make a working example in the [playground](https://onsen.io/playground/) please?
