### ISSUE TITLE
vue-onsenui does not support typescript

### ISSUE THREAD

**Issue by Ftrybe** [OnsenUI/OnsenUI#2659]
__Environment__

Onsen UI Version:

- 2.10.8

Framework:

- Vue 3.8.2

Framework binding:

- vue-onsenui 2.6.2

Platform:

- 

__Encountered problem__

'Cannot find module' with declaration file

__How to reproduce__

npm install vue-onsenui --save

**Comment by Symorp** [comment]
I think vue-onsenui don't have types .

If you wanna to use it you can create some `d.ts` file like `onsen-types.d.ts` in your src folder.

And here you can write `declare module 'vue-onsenui';`

I know it is not the best way, but you will not see this error. Some one would write some type declaration specific for `vue-onsen`

**Comment by jilenloa** [comment]
For me, I created onsen-types.d.ts and added this content:
```

declare module 'vue-onsenui' {
    export function VueOnsen (): any
}
```

**Comment by emccorson** [comment]
@Ftrybe Yes, vue-onsenui doesn't support typescript currently. We don't have any plans to add support. However, it should be straightforward to add types to vue-onsenui for your own projects.

**Comment by Ftrybe** [comment]
I 

> For me, I created onsen-types.d.ts and added this content:
> 
> ```
> declare module 'vue-onsenui' {
>     export function VueOnsen (): any
> }
> ```

thanks，I modify onsui.d.ts of angular.  [https://github.com/Ftrybe/note-vue-onensui/blob/ts/src/types/onsen-types.d.ts](url)

**Comment by Ftrybe** [comment]
my declared file.
link -> [https://github.com/Ftrybe/note-vue-onensui/blob/ts/src/types/onsen-types.d.ts](url)

**Comment by michaelsogos** [comment]
Dear @emccorson 

Did you think about it again maybe?
I guess that TypeScript support is a small but great enhancement.
Also i saw that you talk about Visual Studio 20xx, but never mentioned VSCode; again i guess you should support the way developers are going.

In last 5 years VSCode become the reference IDE for any JS based project.
What do you think about it?

**Comment by emccorson** [comment]
@michaelsogos I'm doing some work on the Vue bindings at the moment so I will add it to the milestone for reconsideration. I will investigate whether we should do this for the next release.

**Comment by michaelsogos** [comment]
Great, thanks!

**Comment by michaelsogos** [comment]
Dear @emccorson 

Just to help you i found this working
```javascript
import Vue from 'vue';
import OnsenUI from 'onsenui';

// 2. Specify a file with the types you want to augment
//    Vue has the constructor type in types/vue.d.ts
declare module 'vue/types/vue' {
	// 3. Declare augmentation for Vue
	interface Vue {
		$ons: typeof OnsenUI;
	}
}
```
in order to have VUE file support and using $ons ...
![image](https://user-images.githubusercontent.com/971120/109416644-d2f63f80-79bf-11eb-8b0e-eff85d7fb983.png)

and better ...
![image](https://user-images.githubusercontent.com/971120/109416672-f7521c00-79bf-11eb-8104-500d0a30fd89.png)
