### ISSUE TITLE
setImmediate is not defined from result of ng build

### ISSUE THREAD

**Issue by wallasfmorais** [OnsenUI/OnsenUI#2660]
First of all, this exact error only occur when try to deploy the *ng build* result.
While development, using *ng serve* the error is:

> TypeError: this._content._show is not a function --> onsenui.js:29494 <from now called ER1>
> TypeError: this._content._show is not a function --> onsenui.js:27940 <from now called ER2>

Looking onto the code about this lines we can refer to:
ER1 is all about "createClass(**SplitterSideElement**, [{" array item with _show  key.
ER2 is all about "createClass(**SplitterContentElement**, [{" array item with _show  key.

--------------------------------------------------------------------------------------------

ps1: I have tried to investigate about a solution (on internet and on my own) and couldn't found.
Not even a clue, just a unanswered question on community.onsen (https://community.onsen.io/topic/1109/onsen-ui-angular-2-giving-this-_content_-show-is-not-a-function-error/1) 

ps2: As far i can see this isn't something new, just not so explored (reason: the primary focus isn't web portals)

ps3: [small new clue] on chrome i could see better the stacktrace and found that the problem is on the method internal$1.waitDOMContentLoaded in the onsenui.js line 1073 (at least on the console) [ReferenceError: setImmediate is not defined ---> line 1073].

ps4: from ps3 someone could think that is a duplicated topic from #2360, BUT ISN´T. Arguments: [
1: isn't about require
2: isn't about build with parcel (I even don't know this parcel)
3: isn't about react
]

--------------------------------------------------------------------------------------------

repro steps: 
[onsen-angular8-sample steps to reproduce.txt](https://github.com/OnsenUI/OnsenUI/files/3317459/onsen-angular8-sample.steps.to.reproduce.txt)

dist sample build repro zip:
[onsen-angular8-sample.zip](https://github.com/OnsenUI/OnsenUI/files/3317460/onsen-angular8-sample.zip)

versions:
@angular-devkit/architect            0.800.3
@angular-devkit/build-angular    0.800.3
@angular-devkit/build-optimizer  0.800.3
@angular-devkit/build-webpack   0.800.3
@angular-devkit/core                   8.0.3
@angular-devkit/schematics         8.0.3
@angular/cli                                 8.0.3
@ngtools/webpack                       8.0.3
@schematics/angular                    8.0.3
@schematics/update                     0.800.3
rxjs                                                6.4.0
typescript                                      3.4.5
webpack                                        4.30.0

ngx-onsenui                                  ^7.0.0
onsenui                                          2.10.8

Platform:
WPA - firefox e chrome

**Comment by Pouja** [comment]
setimmediate is only implemented by Microsoft (edge and IE). So you would require an polyfill. I just used https://github.com/YuzuJS/setImmediate polyfill and I can compile again with `ng serve`.
