### ISSUE TITLE
alert callback function?

### ISSUE THREAD

**Issue by tak40548798** [OnsenUI/OnsenUI#2661]
"cancelable" is set to "true"

How to click on the background or press the Android back button
Do not call the "callback function"

Click "OK" to trigger the "callback function"

![unknown](https://user-images.githubusercontent.com/35030964/59979044-0f7f6e80-9615-11e9-89f8-f9921daf336c.png)

**Comment by emccorson** [comment]
It is expected behaviour for the callback to be run even when the dialog is cancelled.

You could check in your callback function whether the OK button in the dialog was pressed, or whatever. Use `options.id` to get a reference to the dialog.
