### ISSUE TITLE
How to listen to page lifecycle events in Angular 2+?

### ISSUE THREAD

**Issue by imeszaros** [OnsenUI/OnsenUI#2666]
I cannot find any examples. I'd like to execute code on page `show` event.

**Comment by emccorson** [comment]
The easiest way is:
```html
<ons-navigator (show)="doSomething()"></ons-navigator>
```

More examples and different techniques for listening to DOM events in Angular are [here](https://medium.com/claritydesignsystem/four-ways-of-listening-to-dom-events-in-angular-part-1-event-binding-3ec7e9f51a1d).

If you have further questions, please ask at the community forum or the discord channel. Both are linked in the README.
