### ISSUE TITLE
Fonts are not removed from onsenui-core.css

### ISSUE THREAD

**Issue by tobia** [OnsenUI/OnsenUI#2668]
__Environment__

Onsen UI Version:

- 2.10.8

__Encountered problem__

The fonts are not excluded from `onsenui-core.css`, they are just moved to a different place in the file.

__How to reproduce__

Compare the following:
- https://unpkg.com/onsenui@2.10.8/css/onsenui.css
- https://unpkg.com/onsenui@2.10.8/css/onsenui-core.css 

If you search (Ctrl-F) for `@import` you will find the same font imports in both files, just in different places.

By looking through the revisions, it seems to be a **regression introduced in 2.10.7** (2.10.6 was ok)

**Comment by emccorson** [comment]
@tobia Thanks for the detailed report, and especially for pointing out the version in which the bug was introduced.

My initial guess is that the problem was caused by the upgrade to Gulp 4. I am looking at the issue now.
