### ISSUE TITLE
React OnsenUI onDeviceBackButton not working on web

### ISSUE THREAD

**Issue by lai5203** [OnsenUI/OnsenUI#2671]
__Environment__

Onsen UI Version:

- 2.10.8

Framework:

- React 16.7.0

Framework binding:

- react-onsenui 1.11.2

Additional libraries:

- No

Platform:

- Web

__Encountered problem__

The onDeviceBack button in web is not working. When I click the browser back button it will redirect to the previous page that is in my history. Same results goes to android device also, I tested in Android device Google Chrome and when I click device back button it will close the browser.

__How to reproduce__

1. View the page.
2. Click a button that have a pushPage function to go to another page stack.
3. Click back button.
4. It will close the app. (If previous have some history in browser it will redirect back to the back).

Anything I missed up? or it's actually doesn't work in web platform? Hopefully get someone to help on this issue due to it actually affect the user experience on viewing the page.

**Comment by emccorson** [comment]
The browser back button behaviour isn't overridden by Onsen UI so the behaviour you are seeing is expected.

However, it might be worth adding this feature in the future. I will have a think about it.

By the way, pressing the Escape key is the equivalent in the browser of pressing the device back button.

**Comment by lai5203** [comment]
Hi @emccorson, thanks for replying my issue.

Currently, I temporarily found a solution to solve this issue which are using RouterNavigator (https://onsen.io/v2/api/react/RouterNavigator.html) and window.onpopstate event.

I am using [React Router](https://reacttraining.com/react-router/web/guides/quick-start) with [BrowserHistory](https://reacttraining.com/react-router/web/api/BrowserRouter)(BrowserRouter) but this method doesn't work in BrowserHistory.
After that I changed [BrowserHistory](https://reacttraining.com/react-router/web/api/BrowserRouter) to [HashHistory](https://reacttraining.com/react-router/web/api/HashRouter)(HashRouter) this method able to work and the device back button able to popPage from onsenui page stack without exit the browser.

First, I will bind a function to onpopstate event in componentDidMount.

```
componentDidMount(){
    window.onpopstate = this.handlePopState;
}
```

This is my handlePopState function to handle popPage

```
handlePopState(){
     const { routeConfig: { routeStack } } = this.state;

      if(routeStack.length > 1){
        this.popPage();
      }
}
```

Pushpage function here always pushes an **empty state** to history so that user click back button won't exit the browser.

```
  pushPage(page, key, props) {
    const route = {
      component: page,
      props: {
        key: key,
        popPage: () => this.popPage(),
        pushPage: (...args) => this.pushPage(...args)
      }
    };

    let routeConfig = this.state.routeConfig;

    routeConfig = RouterUtil.push({
      routeConfig,
      route
    });

    window.history.pushState(null, null, "");

    this.setState({routeConfig});
  }
```
