### ISSUE TITLE
<ons-icon> cannot display any icon

### ISSUE THREAD

**Issue by mc-y-saito** [OnsenUI/OnsenUI#2674]
__Environment__

Onsen UI Version:

-  /* onsenui v2.10.9 - 2019-07-26 */

Framework:

-  no framework. raw JavaScript

Platform:

- Android 8.1 Cordova

__Encountered problem__

`<ons-icon>` doesn't display anyicons.
e.g. `<ons-icon icon="fa-user"></ons-icon>`
I checked onsen UI playground and it's not working also.
https://ja.onsen.io/v2/api/js/ons-icon.html

**Comment by munsterlander** [comment]
I am having the same issue.  Using unpkg to load the CSS also does not generate icons in apps.

`<link rel="stylesheet" href="https://unpkg.com/onsenui/css/onsenui.css" type="text/css" media="all" />
    <link rel="stylesheet" href="https://unpkg.com/onsenui/css/onsen-css-components.css">`

**Comment by mc-y-saito** [comment]
I checked the version and found out Onsen UI has been updated to v2.10.9 Today (26. July).
Maybe it caused this issue. 
FYI, I downloaded v2.10.8 and installed locally. It works.

**Comment by jamalassaf** [comment]
Same problem here!!! Please fix ASAP. Our productions apps are showing squares instead of actual icons.

**Comment by asial-matagawa** [comment]
@munsterlander @mc-y-saito @jamalassaf (Cc: @emccorson )
Thank you for reporting.
I set `onsenui@latest` to `2.10.8` temporarily:
```
$ npm dist-tag ls onsenui
latest: 2.10.9

$ npm dist-tag add onsenui@2.10.8 latest
+latest: onsenui@2.10.8

$ npm dist-tag ls onsenui
latest: 2.10.8
```

@emccorson 
Can you check this problem?
I think we can release `2.10.10` after fixing it.

**Comment by emccorson** [comment]
Thanks for reporting this. Eventually I'm going to get a release right the first time :roll_eyes: 

@asial-matagawa I will have a look today to see what's going on.

**Comment by andrewstec** [comment]
I believe the 2.10.10 CDN is still breaking, even though the font imports are included at the top of the CSS file now.

I had to lock down the CDN to version 2.10.8 to fix the changes, just as @mc-y-saito had done.

Even when I upgrade the NPM package of Onsen to 2.10.10, the 2.10.10 CDN still breaks. Only a couple icons appear in the app I am working with. Most icons disappear, similar to the problem @jamalassaf described.

I'd really appreciate Onsen double-checking this :) 

Thanks!
