### ISSUE TITLE
Navigator.resetPageStack() throws duplicate key warning [React]

### ISSUE THREAD

**Issue by TomTirapani** [OnsenUI/OnsenUI#2682]
**Onsen UI Version**:
2.10.10

**Framework**:
React 16.8.0

__Encountered problem__:
When using the Navigator with React bindings, you have to assign each route a unique `key`. In accordance with React best practices, we are using stable keys to help React identify each route. As such, route `A` has `key={A}`, `B` has `key={B}`, etc.

We have a scenario where tapping a home button should navigate back to the first route in a stack. We want to go from a stack of `[A, B, C]` to `[A]`. Since the distance is more than one route, we can't use `popPage()`, and instead must use `resetPageStack([A])`.

However, if we attempt `resetPageStack()`, React throws badly with a duplicate key warning. The error occurs when navigating from one stack to another where the last route of the new stack is present in the previous stack.

I believe this is due to the following line (https://github.com/OnsenUI/OnsenUI/blob/master/bindings/react/src/components/Navigator.jsx#L105), which adds `A` to end of the route stack, resulting in a transient stack of `[A, B, C, A]`.

Since we are using stable keys, the two entries of `A` causes the renderer on https://github.com/OnsenUI/OnsenUI/blob/master/bindings/react/src/components/Navigator.jsx#L331 to throw with a duplicate key warning.

We would expect `resetPageStack()` to respect stable keys and not add duplicate routes onto the stack. Is there another preferred method of navigating back to "home" from a deep stack (i.e. going from `[A, B, C]` to `[A]`)?

**Comment by Newbie012** [comment]
Did you find a solution for this?
