### ISSUE TITLE
icon (css) is missing in onsenui 2.10.10.

### ISSUE THREAD

**Issue by emccorson** [OnsenUI/OnsenUI#2686]
icon (css) is missing in onsenui 2.10.10.
To reproduce the problem:
1) git clone git@github.com:monaca-templates/onsenui-v2-vue-tabbar.git
2) run npm install; monaca preview;
The page displaying correctly.
3) change onsenui in package.json to 2.10.10. and run npm install; monaca preview.
The icon is missing as in the attached files.
(In some templates, when we switch between android and ios, the page seems to display incorrectly)

(Reported by @yong-asial )

---

It looks like this might be limited to ionicons not displaying. FontAwesome and material icons seem OK on first inspection.

**Comment by apiaget** [comment]
Hello !

I am also encountering the problem on ons-tab elements. The ionicons (ion-heart, ion-search, ...) seems affected.

The icons were loading fine before an onsen update in my app, however I could not pinpoint the exact moment when the icons started to break.

-apiaget

**Comment by emccorson** [comment]
I don't think this is a bug with Onsen UI after all; it is a problem in the monaca templates.

1. Some icons no longer exist in the version of ionicons we use e.g. `ion-ios-bell`
2. The icon name must now start with `ion-ios` or `ion-md` to specify the platform. For example, `ion-home` no longer works but `ion-ios-home` does.
