### ISSUE TITLE
Core | Search-input issue: ONSEARCH event

### ISSUE THREAD

**Issue by maico910** [OnsenUI/OnsenUI#2700]
__Environment__

  
```
[Core]
  onsenui latest
  
[Platform]
  Desktop - Windows 10 64-bit

[Browser]
  Desktop - Chrome 77.0.3865.90 on Windows 10 64-bit
```

__Encountered problem__
  
the better way to work with **input type="search"** in mobile is using **onsearch** event (call something function when enter is pressed [_the search button on keyboard_]), but it's not working (don't add onsearch event on the input inside the **ons-search-input**

(I tried to fix this issue by myself, but I'm starting in web development and I can't understand very well how to do that)

__How to reproduce__
  
1- type some text
2- press ENTER (will do nothing)

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<ons-page>
  <p style="text-align: center; margin-top: 10px;">
    <ons-search-input
      placeholder="Search"
      onsearch="ons.notification.alert('Searched for: ' + this.value)"
    ></ons-search-input>
  </p>
</ons-page>
```

- __JS__

```javascript

```

**Comment by emccorson** [comment]
The search event is a non-standard feature, so we don't have any plans to add support for it at the moment.

https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/search_event
