### ISSUE TITLE
Update for new iPadOS segment design

### ISSUE THREAD

**Issue by samuelkitson** [OnsenUI/OnsenUI#2702]
In the recently launched iPadOS, Apple have changed the design of the ‘segment’ component. (See the attached photo). It would be nice if the Onsen UI segment component was updated to match - web apps using this feature will start to feel outdated soon.

_This example image is from the iPadOS calendar app_
![A0F1E748-3237-4A7B-A136-BFF3E8C81D10](https://user-images.githubusercontent.com/32879754/66546651-5eee9980-eb35-11e9-96dd-0a32b683fd4b.jpeg)

**Comment by emccorson** [comment]
Thanks for pointing this out. We are doing testing on iPadOS and will be working on an update soon.

Related: #2689

**Comment by penguin-k** [comment]
Still looks like it's using the old segment design - it would be great if it could be updated at some point (though I appreciate it's a completely different style to the old one!)
