### ISSUE TITLE
Onsen, React, Cordova: Touch Sensitivity for Input Focus 

### ISSUE THREAD

**Issue by vinnichase** [OnsenUI/OnsenUI#2719]
__Environment__

Onsen UI Version:
- 2.10.10

Framework:

- react 16.8.6

Framework binding:

- react-onsenui 1.11.2

Additional libraries:

- 

Platform:

- cordova-ios 5.1.1

__Encountered problem__

I build a smartphone app with onsen, react on cordova for iOS and Android. On all iOS devices I encounter very bad touch sensitivity when tapping on any HTML `<input>` or `<textarea>` element.  Meaning you need to tap multiple times (3-6 times) on the inputs to focus them in order to type.

On Android it works like charm. When calling my app via iOS Safari (not in the cordova container) it also works nice and smooth.

As a workaround I added touch handlers on the inputs parent elements to extend the hitbox of the inputs. This works OK but has horrible side effects on certain devices (also new iPhone 11 on iOS 13.3)

I didn't find any similar issue and also nothing in the docs how to use inputs properly for a touch device.

__How to reproduce__

 1. Setup a sample app with the library versions from above
 2. Insert an input field
 3. open the app on mobile safari or better build a cordova app and run it on an iOS device

**Comment by joshuakaleb0424** [comment]
I had this problem before. Try destroying fast click `ons.fastClick.destroy();` inside `ons.ready`

**Comment by vinnichase** [comment]
Thx! Works like charm. Had to wait for the AppStore review to confirm your solution. But now i encounter the 300ms delay. Thats for me the better alternative right now, so I will go without fastclick but I'm happy if someone comes up with a solution that allows keeping fastclick.

**Comment by JamalAPI** [comment]
With WKWebView, which will be required starting April 2020, FastClick is no longer needed and there there will be no 300ms delay.

**Comment by vinnichase** [comment]
I tried to migrate to WKWebView and failed hard. White screen and no logged errors.

**Comment by emccorson** [comment]
FastClick was removed in v2.11.0 and shouldn't be needed with WKWebView as JamalAPI stated. Closing this for now.
