### ISSUE TITLE
This project has been added to the react-ui-roundup

### ISSUE THREAD

**Issue by dimitropoulos** [OnsenUI/OnsenUI#2728]
Hi!

I am making this issue just to let you know that I've included your amazing project in the [react-ui-roundup](https://github.com/dimitropoulos/react-ui-roundup).

For more information see https://github.com/dimitropoulos/react-ui-roundup/issues/2.

Please feel free to close this issue at will - I just wanted to let you know :smile:.

Thanks!

**Comment by emccorson** [comment]
Thanks! This looks useful. I'll have a closer look at your checklists when I have a chance and file an issue if there's anything incorrect in the Onsen UI part.

**Comment by dimitropoulos** [comment]
Fantastic! No rush at all, just wanted to let you know.  The project is by no means finished anyway, plenty more components to add over time :)
