### ISSUE TITLE
Onsen ui problems

### ISSUE THREAD

**Issue by cppprog** [OnsenUI/OnsenUI#2748]
Hi
I had a problem with onsenui many years age when using phonegap. The page and elements not shows correctly and nobody help me on Twitter even onsen page.
After years again i am using vue and for ui use onsen vue. But again v ons page not show full height on viewport and act like a normal flow html and if i have content that is tall as content. V ons fab show on toolbar component ans css are imported and no error found. Is onsen ui is a dead project ?

**Comment by emccorson** [comment]
If you are reporting a bug, please provide a description and a code sample that reproduces the problem. You can do this at https://onsen.io/playground/ and then click Report an Issue.

If you just need help using Onsen UI, feel free to ask at the community forum: community.onsen.io/
