### ISSUE TITLE
Vulnerable yargs-parser dependency

### ISSUE THREAD

**Issue by Rudloff** [OnsenUI/OnsenUI#2749]
__Environment__

Onsen UI Version:

-  2.10.10

__Encountered problem__

onsenui depends on a version of yargs-parser that is [vulnerable](https://www.npmjs.com/advisories/1500).

The dependency path is:
```
onsenui > gulp-protractor > protractor > yargs > yargs-parser
```

__How to reproduce__

```bash
yarn add onsenui
yarn audit
```

**Comment by emccorson** [comment]
I believe this is fixed as we are now using `yargs-parser@5.0.1`. In any case, I don't think we are using gulp for almost anything now. Will close for now.
