### ISSUE TITLE
How to select text?

### ISSUE THREAD

**Issue by ranouf** [OnsenUI/OnsenUI#2759]
Hi,

I'm new to Onsen UI, I'm interested to find an easy way to be able to select text in my website like a css hack or even better, an option to configure with onsen.

Thanks,
Cedric

**Comment by JamalAPI** [comment]
This is not Onsen related.  

A simple Javascipt will do:

`document.getElementById("YourElement").select();`

**Comment by Andrew67** [comment]
Yeah, by default OnsenUI applies the following which disables text selection for most things (to be app-like):
```
a, abbr, acronym, address, applet, article, aside, audio,
b, big, blockquote, body,
canvas, caption, center, cite, code,
dd, del, details, dfn, div, dl, dt,
em, embed,
fieldset, figcaption, figure, footer, form,
h1, h2, h3, h4, h5, h6, header, hgroup, html,
i, iframe, img, ins,
kbd, label, legend, li, mark, menu, nav,
object, ol, output, p, pre, q, ruby,
s, samp, section, small, span, strike, strong, sub, summary, sup,
table, tbody, td, tfoot, th, thead, time, tr, tt, u, ul, var, video {
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    -webkit-tap-highlight-color: transparent;
    -webkit-touch-callout: none;
}
```

I did this on my own project:
```
.selectable {
    -webkit-user-select: text;
    -moz-user-select: text;
    -ms-user-select: text;
    user-select: text;
}
```

This re-enables text selection for any elements with the `selectable` class, but you could use your own selectors as long as they're more specific.
