### ISSUE TITLE
Monaca Preview not previewing !

### ISSUE THREAD

**Issue by arcubalino** [OnsenUI/OnsenUI#2767]
After updating to the newest version, I created a new project, used the js splitter template, and after running “monaca preview”, it does nothing just goes to a new line!

![image](https://user-images.githubusercontent.com/5410049/87312332-fd8ba900-c552-11ea-8500-a46528e3ee68.png)

**Comment by yong-asial** [comment]
@arcubalino I've just checked it and everything seems to be working fine from our side. Could you give us more detail information?

- monaca-cli version, you are using?
- how did you created the template?
- what is your node and npm version?

Anyway, `monaca preview` is just a wrapper functional call of `monaca:preview` script. If you created the project using the template, the package.json should have something as the following:
```
    "scripts": {
        "monaca:preview": "npm run dev",
        "dev": "browser-sync start -s www/ --watch --port 8080 --ui-port 8081"
    },
```

If `monaca preview` doesn't work, maybe you could first try running `npm install` and then run `npm run dev`. 

Maybe it was the problem of `npm` in the first place. Please also be aware that today, Github experienced their server down. So maybe some files got corrupted during the download templates from Github (running `monaca create`).
