### ISSUE TITLE
VOnsNavigator page stack update error: Error in callback for watcher "pageStack": "TypeError: Cannot read property '$el' of undefined"

### ISSUE THREAD

**Issue by tomsaleeba** [OnsenUI/OnsenUI#2775]
__Environment__

Onsen UI Version:

- 2.10.10

Framework:

- Vue 2.6.11

Framework binding:

- vue-onsenui 2.6.2

Additional libraries:

- none

Platform:

- tested on Linux Chrome 84, but should affect all platforms

__Encountered problem__

Using a `v-ons-navigator`, update the page stack during or after `mounted`. I would expect that the top of the new stack is the component that is displayed and without error. The actual behaviour is the component is displayed but this error, from the pageStack watcher, is thrown:
```
vue.js:634 [Vue warn]: Error in callback for watcher "pageStack": "TypeError: Cannot read property '$el' of undefined"

found in

---> <VOnsNavigator>
       <Root>

TypeError: Cannot read property '$el' of undefined
    at VueComponent.pageStack (vue-onsenui.js:1163)
    at Watcher.run (vue.js:4567)
    at flushSchedulerQueue (vue.js:4311)
    at Array.<anonymous> (vue.js:1989)
    at flushCallbacks (vue.js:1915)
```

The problem is that the watcher is triggered when there are no `$children` but [the code](https://github.com/OnsenUI/OnsenUI/blob/2.10.10/bindings/vue/src/components/VOnsNavigator.vue#L127) expects that there is at least one child.

I don't know why there aren't any children, I guess they haven't been mounted yet? I'm also open to the fact that I might be using the component incorrectly.

__How to reproduce__

See my minimal reproduction here: https://github.com/tomsaleeba/onsen-vue-navigator-error-demo. I've written more about the issue in the README.

**Comment by souravm84** [comment]
facing same issue. when push page in v-ons-navigator pageStack. 
Platform:
tested on Windows 10 Chrome 84.
