### ISSUE TITLE
expandable arrow do not update correctly in multiple level ons-list-item expandable tappable

### ISSUE THREAD

**Issue by aihuawu** [OnsenUI/OnsenUI#2796]
expandable arrow do not update correctly in multiple level ons-list-item 

When you have 2 level list, one list inside another list, the inner list item does not
show correct expandable arrow.  Basically, it always show expandable even the item is collapsed.

George wu

**Comment by emccorson** [comment]
Nested list items are currently not a supported feature in Onsen UI. We may add this in the future, but for the moment I will close this as not planned.
