### ISSUE TITLE
notification.prompt inputType='email' throws exception

### ISSUE THREAD

**Issue by ekstepj** [OnsenUI/OnsenUI#2803]
__Environment__

Onsen UI Version: 2.10.10
Framework: none - vanilla javascript
Framework binding: none
Additional libraries: none of consequence
Platform: MacOS Chrome Version 85.0.4183.121 (Official Build) (64-bit)
 (does not occur on MacOS Safari Version 14.0 (15610.1.28.1.9, 15610)

__Encountered problem__

When using the code:

    // get the email address
    ctrl = document.getElementById('r_client_email');
    var clientEmail = ctrl.value;

    ons.notification.prompt('Email Address', {title : "Send receipt to", defaultValue : clientEmail, inputType : 'email', buttonLabels : ["Cancel","Send"]  })
    .then(function(input) {

I get the following in Javascript console:

onsenui.min.js:2 Uncaught (in promise) DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('email') does not support selection.
    at http://localhost:8888/client/js/lib/onsenui.min.js:2:56813

__How to reproduce__
It appears - on this platform - that simply include the inputType: 'email' is enough. It is occurring everywhere in my application I use notification.prompt asking for an email address.

**Comment by emccorson** [comment]
Thanks for the report.

The problem was we use setSelectionRange to move the cursor to the end of the input, but that is not supported for input type email.
