### ISSUE TITLE
Repeated CSS attributes in 2.11.1

### ISSUE THREAD

**Issue by nickredding** [OnsenUI/OnsenUI#2805]
There are numerous repeated CSS attributes in onsen-css-components.css, for example (one of many instances) line 3750:

:disabled + .radio-button--material__checkmark:before {
  border-color: #afafaf;
  border-color: #afafaf;
}

It's harmless, but why?

**Comment by emccorson** [comment]
Basically we use postcss to transform the CSS and sometimes when the CSS variables are inlined we end up with duplicate rules.

If anyone has suggestions of a postcss plugin or other tool we could use to remove the duplicate rules, that would be good.
