### ISSUE TITLE
ons-tababr in darkmode is broken

### ISSUE THREAD

**Issue by DerGoogler** [OnsenUI/OnsenUI#2813]
its in the title.

**Comment by emccorson** [comment]
I tested the tabbar example using dark-onsen-css-components.css and it seems to be working fine.

Can you provide more detail and a minimal example that shows the problem?

**Comment by DerGoogler** [comment]
![image](https://user-images.githubusercontent.com/54764558/99459821-00e2d700-292f-11eb-8ab8-377611a1e3ad.png)
button, text and i can see the thr tabbar buttons border.
