### ISSUE TITLE
Mainpage with Slide-Menu disapears in Android 4.4.4 version

### ISSUE THREAD

**Issue by alangularte** [OnsenUI/OnsenUI#282]
I'm building an app, and I'm facing the following error with Slide-Menu.

This issue was discovered during http://stackoverflow.com/questions/26487885/onsen-ui-using-slide-menu-just-for-specifics-pages solution.

Screen:
![screen](https://cloud.githubusercontent.com/assets/3098082/4729557/2947aa6c-5989-11e4-9383-329ac0880a2a.png)

LG Optimus G - Android 4.1.2
![lg-optimusg-4 1 2](https://cloud.githubusercontent.com/assets/3098082/4729558/34dbe0a0-5989-11e4-8e18-dac887f7f9c2.png)

Moto E - Android 4.4.4
![motoe-4 4 4](https://cloud.githubusercontent.com/assets/3098082/4729559/3a78f7e6-5989-11e4-93c2-e9965d297f8b.png)

**Comment by Viras-** [comment]
I can confirm this issue. I'm using a navigator and inside that navigator a sliding-menu. Between the page-div and the sliding-menu element is another div created (by I guess onsen). This div has some webkit transformations which do not seem to work. When manually assigning that div a size I can see the content.

Here is the CSS I use (page-menu is the ID of the page containing the sliding-menu) as a workaround:

> #page-menu > div.page__content > div {
right: 0px;
left: 0px;
bottom: 0px;
top: 0px;
position: absolute;
}

Can I help you with any more information?
