### ISSUE TITLE
None of the icon is showing :: Simple example file included.

### ISSUE THREAD

**Issue by BracerJack** [OnsenUI/OnsenUI#2820]
[test.zip](https://github.com/OnsenUI/OnsenUI/files/5716858/test.zip)

None of the icon is showing, example file included.
```<ion-icon name="archive-outline"></ion-icon>``` is simply not working.

**Comment by emccorson** [comment]
That's not the correct syntax for using icons in Onsen UI. You need to the `ons-icon` component e.g.:

```
<ons-icon icon="ion-ios-hammer"></ons-icon>
```

See here for details:
https://onsen.io/v2/api/js/ons-icon.html#

Please note that the documentation there for Ionicons is out of date. Contrary to what it says there, you need to use `ion-ios-<name of icon>`, not just `ion-<name of icon`.
