### ISSUE TITLE
Cordova + Onsen + Vue very slow and graphic glitches

### ISSUE THREAD

**Issue by guestisp** [OnsenUI/OnsenUI#2821]
I'm having a strnage behaviour with cordova + onsen + vue.
Everything is very slow and laggy, with some weird graphical issues (div rendered in wrong positions, strange graphics and so on)

![image](https://user-images.githubusercontent.com/3944655/103700493-ce577100-4fa4-11eb-91ae-ddd0ea8cbbe5.png)

Any idea ? Do you see the "noise" at the center ?

**Comment by emccorson** [comment]
Can you please send a minimum sample that shows the problem?

Also please let us know what device and OS version you are using, and any other useful information.

**Comment by guestisp** [comment]
"solved" . it's related to a webview upgrade. Anything higher than 62 (the stock version I have in this Sunmi device) makes glitches

**Comment by emccorson** [comment]
Thank you for confirming. I'll close this now.
