### ISSUE TITLE
example code for ons-preload(templatepaths)

### ISSUE THREAD

**Issue by skyfox87** [OnsenUI/OnsenUI#2824]
Can someone give me example of ons-preload(templatepaths) my app is slow at start up

**Comment by emccorson** [comment]
You just need to pass the paths to the template as an argument and then use `then` to do some action when the templates have loaded.
See here for more information:
https://community.onsen.io/topic/4176/onsnavigator-pushpage-page-options-loads-page-with-a-significant-delay-angular
https://onsen.io/v2/api/js/ons.html#method-preload
