### ISSUE TITLE
Can't disable swipe for menu

### ISSUE THREAD

**Issue by guestisp** [OnsenUI/OnsenUI#2835]
I'm trying to disable the swipe from screen border in side menu on android, but is still sliding even without "swipable" set

Also, how can I disable the swipable via code ? I have a page that need to scroll right and left (it's a leaflet map) but the menu swipe is interfering with the map

**Comment by emccorson** [comment]
Removing `swipeable` from `ons-splitter-side` should be enough. You can try that [here](https://onsen.io/playground/?framework=vanilla&category=reference&module=splitter). If you are still having problems, please post a minimal sample that reproduces the problem using the Playground that I linked.

**Comment by guestisp** [comment]
Removing is ok as long the page is created without swipable

If i create the page with a swipeable menù, then even removing the attribute wont stop the swipe. Looks like the event connected to the swipe are not removed properly when the attribute is removed

**Comment by guestisp** [comment]
Anything else to try ?

**Comment by guestisp** [comment]
@emccorson any update on this ?

**Comment by emccorson** [comment]
How are you removing the attribute? I just tested using the `removeAttribute` method, and the `attributeChangedCallback` is called and `swipeable` is removed as expected.

**Comment by guestisp** [comment]
I'm removing it by setting `:swipeable="isSwipeable"`

**Comment by guestisp** [comment]
As workaround for my need, i've also tried to remove the whole sidebar component with v-if and adding a second router-view in a v-else for the page that doesnt needs a sidebar but this doesnt work at all. Pronsbly i cant have two router-view in the same template because the page is not rendered at all

**Comment by guestisp** [comment]
Workaround 3: how can i prevent the sidebar swipe on pages with draggable components like google maps or leaflet?

**Comment by emccorson** [comment]
Ah right, so this is a problem with the Vue bindings, not with the plain JS version of Onsen UI?

In that case, I will add it to the Vue 3 milestone which I'm working on right now.

As a workaround, you could create two menus - one non-swipeable just for your google maps page and one swipeable on the other pages. Then navigate to the new page when you want to open google maps.

Until then, if there is a minimal sample exported from the playground that reproduces this that would be helpful in investigating the bug when the time comes.
https://onsen.io/playground/

**Comment by guestisp** [comment]
> Ah right, so this is a problem with the Vue bindings, not with the plain JS version of Onsen UI?

I'm using the Vue binding, don't know if plain onsen works

> In that case, I will add it to the Vue 3 milestone which I'm working on right now.

can't you release an hot-fix for the current stable Vue that is v2 ?

> As a workaround, you could create two menus - one non-swipeable just for your google maps page and one swipeable on the other pages. Then navigate to the new page when you want to open google maps.

It's not so easy

**Comment by emccorson** [comment]
Actually, the better workaround looks like just using `:swipeable="isSwipeable"` as mentioned.

I'm not going to release a hot fix right now since the Vue environment is currently broken and would need fixed first. The next release will support Vue 3 so it makes more sense to upgrade the environment to Vue 3 and then fix this issue instead of fixing the Vue 2 environment just for one bug. There's a reasonable workaround so I think this is OK.

**Comment by guestisp** [comment]
Sure, but Vue3 is not production ready.

`:swipeable="isSwipeable"` doesn't work that's because i've opened this issue

**Comment by emccorson** [comment]
I created this example to show that `:swipeable="isSwipeable"` does work.

You can paste it into the [playground](https://onsen.io/playground/) to test it.

HTML
```html
<template id="main">
  <v-ons-splitter>
    <v-ons-splitter-side
      :swipeable="isSwipeable"
      collapse
    >
      <v-ons-page>
        Side menu
      </v-ons-page>
    </v-ons-splitter-side>

    <v-ons-splitter-content>
      <v-ons-page>
        <p>isSwipeable? {{ isSwipeable }}</p>
        <v-ons-button @click="toggleSwipeable">Toggle swipeable</v-ons-button>
      </v-ons-page>
    </v-ons-splitter-content>
  </v-ons-splitter>
</template>

<div id="app"></div>
```

JS
```javascript
new Vue({
  el: '#app',
  template: '#main',
  data() {
    return {
      isSwipeable: true
    };
  },
  methods: {
    toggleSwipeable() {
      this.isSwipeable = !this.isSwipeable;
    }
  }
});
```

**Comment by guestisp** [comment]
```
<template>
  <v-ons-page id="app">
      <v-ons-splitter>
        <v-ons-splitter-side
          :swipeable="isSwipeable"
          collapse
          width="250px"
          animation="overlay"
          :open.sync="menuIsOpen">

            <menu-page></menu-page>
        </v-ons-splitter-side>

        <v-ons-splitter-content>
          <router-view></router-view>
        </v-ons-splitter-content>
      </v-ons-splitter>
  </v-ons-page>
</template>
```
```
computed: {
    isSwipeable() {
      return this.$route.name != 'map'
              && this.$route.name != 'login'
              && this.$route.name != 'settings'
    }
  },
```

Doesn't work.
The `swipeable` argument is propery removed from DOM, but the events seems to be retained, as I can still swipe.

"normal page":
```
<ons-splitter-side data-v-ef20f55c="" collapse="" mode="collapse" width="250px" animation="overlay" side="left" style="width: 250px; transform: translate3d(0px, 0px, 0px); transition: all 0.3s cubic-bezier(0.1, 0.7, 0.1, 1);" swipeable="true">
```

"no swipe page":
```
<ons-splitter-side data-v-ef20f55c="" collapse="" mode="collapse" width="250px" animation="overlay" side="left" style="width: 250px; transform: translate3d(0px, 0px, 0px); transition: all 0.3s cubic-bezier(0.1, 0.7, 0.1, 1);">
```

as you can see, the attribute is removed.

**Comment by emccorson** [comment]
Did you try running the example in the playground like I suggested? It does work there.
I have also exported it to codepen so you can see that it is working: https://codepen.io/emccorson/pen/OJbbrVd

I can't run the code you sent as it is not a complete example, but since this method does work in the example I posted, I don't think it is a problem with Onsen UI.
