### ISSUE TITLE
Cannot read property 'remove' of undefined

### ISSUE THREAD

**Issue by Ermak1243** [OnsenUI/OnsenUI#2843]
Hi! Split the application into two .html files as shown in the example in the documentation, but when the code reaches the navigator.resetToPage ('home.html') line, an error is thrown. 

![Error](https://user-images.githubusercontent.com/54016965/105987459-1fe4ae80-60c0-11eb-9189-d9abc26232c2.png)

**Comment by emccorson** [comment]
Can you make a minimal sample that shows this problem in the playground please?
https://onsen.io/playground/

**Comment by Ermak1243** [comment]
> Can you make a minimal sample that shows this problem in the playground please?
> https://onsen.io/playground/

![Error](https://user-images.githubusercontent.com/54016965/106131735-df9b3400-6184-11eb-8115-1b12118480c5.png)

**Comment by munsterlander** [comment]
@Ermak1243 Didn't we solve this in the Discord?  If so, can you please close this issue?

**Comment by Ermak1243** [comment]
> @Ermak1243 Didn't we solve this in the Discord? If so, can you please close this issue?

Thank you for help!
