### ISSUE TITLE
Javascript error occurs when clicking "ons-button" after updating Chrome to the latest

### ISSUE THREAD

**Issue by yknnnnft** [OnsenUI/OnsenUI#2847]
__Environment__

Onsen UI Version:

- 2.0.4

Framework:

- AngularJS 1.5.5

Framework binding:

- none

Additional libraries:

- angular 1.5.5
- angular-i18n 1.6.4
- angular-local-storage 0.5.2
- angular-mocks 1.6.1
- angular-route 1.6.1
- angular-sanitize 1.6.1
- angular-touch 1.5.11
- angular-ui-bootstrap 2.5.0
- angular-ui-router 0.4.2
- cordova-android ^8.1.0
- cordova-common ^4.0.0
- cordova-custom-config ^5.1.0
- cordova-plugin-camera ^4.1.0
- cordova-plugin-file ^6.0.2
- cordova-plugin-geolocation ^4.0.2
- cordova-plugin-inappbrowser ^3.2.0
- crypto-js 3.1.9-1
- gulp-util 3.0.8
- jquery 1.11.0
- moment 2.17.1
- onsenui ^2.0.4
- underscore 1.8.3
- webpack-dev-server 2.4.2
- x2js 3.1.0

Platform:

- Platform 1 (os: Android 8.0.0 / Webview: Chrome 88.0.4324.93)
- Platform 2 (os: Android 10 / Webview: Android System WebView 88.0.4324.93)

__Encountered problem__

After the latest update of Chrome on Jan. 27th, the following Javascript error occurs when clicking a ons-button component.
```
Uncaught TypeError: Cannot read property 'stopAll' of undefined
```

The detail of the error is as following.
![image](https://user-images.githubusercontent.com/18159871/106277707-dee5c900-627c-11eb-8773-8aa1b53a0b17.png)
![image](https://user-images.githubusercontent.com/18159871/106274664-eeaede80-6277-11eb-9d5f-0a940bdb903e.png)
It seems that the RippleElement class is not initialized successfully so that the property "_animator" keeps undefined when calling its "stopAll" function.

I made a try to minimize the codes as following but the error remains.
```html
<ons-button><span>login</ons-button>
```

Furthermore, it is confirmed that the error does not occur until webview is updated to Chrome 88.

It is appreciated if you could give me an idea about whether there is any solution to the error without updating OnsenUI.

__How to reproduce__

**Comment by emccorson** [comment]
I think the first thing to try is to use a newer version of Onsen UI. 2.0.4 is very old - the current version is 2.11.2.

If the bug still shows up for the latest version then we can look into it, but we can't support older versions.
