### ISSUE TITLE
The doc of ons-icon does not show Ionicons icons

### ISSUE THREAD

**Issue by lethe2211** [OnsenUI/OnsenUI#2867]
__Environment__

Onsen UI Version:

- 2.11.2

Framework:

- N/A

Framework binding:

- N/A

Additional libraries:

- N/A

Platform:

- N/A

__Encountered problem__

* https://onsen.io/v2/api/js/ons-icon.html
* https://onsen.io/v2/api/angular1/ons-icon.html
* https://onsen.io/v2/api/vue/v-ons-icon.html

do not show the icons from Ionicons anymore.

![image](https://user-images.githubusercontent.com/1718146/108677546-2df5e580-752d-11eb-8153-faf61dc4ac40.png)

They needed to be updated according to the version change of Ionicons which was introduced in 2.10.9 https://github.com/OnsenUI/OnsenUI/compare/2.10.9...master

__How to reproduce__

Open 

* https://onsen.io/v2/api/js/ons-icon.html
* https://onsen.io/v2/api/angular1/ons-icon.html
* https://onsen.io/v2/api/vue/v-ons-icon.html

with your browser.

**Comment by lethe2211** [comment]
https://onsen.io/v2/api/react/ons-icon.html
React does not have a doc for ons-icon by the way.

**Comment by emccorson** [comment]
Thanks for the report. Fixed in OnsenUI/playground#69.

The React API pages do not currently have the tutorials embedded, but you can find them here:
http://onsen.io/playground/?framework=react&category=reference&module=icon
