### ISSUE TITLE
Add support for iPads without home button like for iPhoneX+ (iPad Air 4, iPad Pro, ...)

### ISSUE THREAD

**Issue by magynhard** [OnsenUI/OnsenUI#2880]
__Environment__

Onsen UI Version:

- 2.11.2

Framework:
- none / JS

Framework binding:

- none

Additional libraries:

- non relevant

Platform:

- iOS (Cordova) on latest iPads without hardware home button
- Devices
  - iPad Air 4
  - iPad Pro 2020
  - iPad Pro 2018

__Encountered problem__

The latest iPad have like the iPhoneX no more hardware home button, but a software bar at the bottom.
For the iPhoneX and later, there is a patch available, to increase the space at the bottom so that the software bar does not overlap the content (and the same for the notch at the top): https://onsen.io/v2/guide/iphonex.html

On the latest iPads (Air 4, Pro 2020, Pro 2018) the home button has also been replaced with the same software bar.

Especially when using a tabbed OnsenUI page, you can experience the problem most self-explanatory:

![image](https://user-images.githubusercontent.com/14541962/112644933-3ef48800-8e46-11eb-8bd4-981023f92247.png)

__How to reproduce__

Take an iPad of your choice without home button and open the OnsenUI demo page with tabbed menus:
https://onsen.io/demo/

![image](https://user-images.githubusercontent.com/14541962/112645054-6186a100-8e46-11eb-9f3c-bf5dd6525cdc.png)

**Comment by stonjohnsson** [comment]
Has anyone already solved this problem? I experience the same..

**Comment by magynhard** [comment]
Is the OnsenUI project as good as dead by now?
