### ISSUE TITLE
[Bug] Many props missing

### ISSUE THREAD

**Issue by DerGoogler** [OnsenUI/OnsenUI#2959]
__Environment__

Onsen UI Version:

- 2.11.2

Framework:

- React 17.0.2

Framework binding:

- react-onsenui 2.9.16

Additional libraries:

- 

Platform:

- All platforms

__Encountered problem__

Some elements doesn't have correct typings 

__How to reproduce__

Get the value from search input is impossible 

```ts
  private triggerSearch = () => {
    tools.ref(this.searchBar, (ref: OnsSearchInputElement) => { 
      ref.value; // Throws no error  /=> return undefined
    });
  };

  private triggerSearch = () => {
    tools.ref(this.searchBar, (ref: SearchInput) => { 
      ref.value; // Throws error => Property 'value' does not exist on type 'SearchInput'.ts(2339)
    });
  };
```
### A look inside `tools.ref`
```ts
  /**
   * @param id
   * @param callback HTMLElement
   *
   * @description
   * Usage
   * ```ts
   * // Id's
   * tools.ref("element", (element: HTMLElement) => { element.style.display = "none" })
   *
   * // Refs
   * tools.ref(this.myRef, (ref: HTMLElement) => { ref.style.display = "none" })
   * ```
   */
  public static ref(id: string | React.RefObject<any>, callback: (...props: any) => void) {
    if (typeof id == "string") {
      var element: HTMLElement | null;
      if ((element = document.getElementById(id))) {
        if (typeof callback == "function") {
          callback(element);
        }
      }
    } else {
      var reff: React.RefObject<any>;
      if ((reff = id)) {
        if (reff && reff.current) {
          if (typeof callback == "function") {
            const ref: typeof reff = reff.current;
            callback(ref);
          }
        }
      }
    }
  }
```

## Missings props

![](https://cdn.discordapp.com/attachments/415288814911619084/946030220845133824/unknown.png)

does not exist

![](https://cdn.discordapp.com/attachments/415288814911619084/946030440765075526/unknown.png)

**Comment by DerGoogler** [comment]
Keyup taking no effects

```tsx
            <SearchInput
              // @ts-ignore
              placeholder={`${string.search} ${this.props.name}`}
              ref={this.searchBar}
              style={{
                borderRadius: "8px",
                width: "100%",
                marginRight: "4px",
                backgroundColor: native.getPref("enableDarkmode") === "true" ? "#1F1F1F" : "transparent",
              }}
              onChange={this.filter}
              onKeyup={(event: KeyboardEvent) => {
                if (event.keyCode === 13) {
                  console.log("Enter")
                }
              }}
            />
```

**Comment by DerGoogler** [comment]
addEventListener also dont exist
![image](https://user-images.githubusercontent.com/54764558/155571840-45298eb3-4c07-469e-95dd-0e2b8b5b9387.png)

**Comment by DerGoogler** [comment]
Some more error

## `<Tabbar />`
![image](https://user-images.githubusercontent.com/54764558/155584454-de60d520-6da7-4093-8ace-256135cc7b61.png)

## `<RouterNavigator />`
![image](https://user-images.githubusercontent.com/54764558/155584730-896028a9-13d8-4602-9c98-e6a4369eef4b.png)

**Comment by emccorson** [comment]
Concerning the SearchInput, it does not forward a ref so you can't get access to the ref, but you can use the `value` prop to set the initial value and the `onInput` prop to get the value when the input changes:

```jsx
class MyPage extends React.Component {
  
  constructor() {
    super();
    this.log = this.log.bind(this);
  }
  
  log(e) {
    console.log(e.target.value);
  }
  
  render() {
    return (
      <Ons.SearchInput value="value" onInput={this.log} />
    );
  }
}
```

**Comment by DerGoogler** [comment]
> Concerning the SearchInput, it does not forward a ref so you can't get access to the ref, but you can use the `value` prop to set the initial value and the `onInput` prop to get the value when the input changes:
> 
> ```js
> class MyPage extends React.Component {
>   
>   constructor() {
>     super();
>     this.log = this.log.bind(this);
>   }
>   
>   log(e) {
>     console.log(e.target.value);
>   }
>   
>   render() {
>     return (
>       <Ons.SearchInput value="value" onInput={this.log} />
>     );
>   }
> }
> ```

@emccorson,

i found an solution, i just build my own component

like this
```tsx
import { SearchInput } from "react-onsenui";
import BasicComponent from "./BasicComponent";

interface Props {
    modifier?: string | undefined,
    disabled?: boolean | undefined,
    placeholder?: string | undefined,
    value?: string | undefined,
    inputId?: string | undefined,
}

class CustomSearchbar extends BasicComponent<Props, any> {
    public constructor(props: any) {
        super(props)

        this.state = {
            value: ""
        }
    }

    /**
     * Changes on every keypress
     * @param e 
     */
    public onChange = (e: any): void => {
        this.setState({ value: e.target.value })
    }

    /**
     * Gets the current value
     */
    public get value(): string {
        return this.state.value
    }

    /**
     * Change the current value
     */
    public set value(text: string) {
        this.setState({ value: text }) // Throws currently an error
    }

    public render() {
        const { modifier, disabled, value, inputId, placeholder, style, className, } = this.props
        return (<>
            <SearchInput
                // @ts-ignore
                placeholder={placeholder}
                className={className}
                style={style}
                onChange={this.onChange}
                modifier={modifier}
                disabled={disabled}
                value={value}
                inputId={inputId}
            />
        </>)
    }
}

export default CustomSearchbar
```

**Comment by emccorson** [comment]
These issues should be fixed by the linked PR.

1. Arbitrary events can be listened for by using the prop `on<EventName>` e.g. `onKeyup` even if the prop is not listed in the component's prop types or documentation.
2. Components now forward refs properly so you can put a ref on SearchInput and it will get you the inner ons-search-input.
3. Many undocumented props have been documented.
