### ISSUE TITLE
vue-onsenui package.json peer dependencies refers "onsenui": "~2.11.0",

### ISSUE THREAD

**Issue by sakdeniz** [OnsenUI/OnsenUI#2969]
Hi,

vue-onsenui package.json peer dependencies refers to old version "onsenui": "~2.11.0",

I think you need to update it to 2.12.0

Thanks.

**Comment by sakdeniz** [comment]
Thanks, i will wait for update.

**Comment by emccorson** [comment]
Fixed now in vue-onsenui@2.7.0.

**Comment by emccorson** [comment]
Thanks for the report. Yes, currently vue-onsenui has not been updated to
use onsenui 2.12.0, but we will be doing that soon. For now you can still
use 2.11.2.
