### ISSUE TITLE
Progress-circular rotation is choppy in Safari.

### ISSUE THREAD

**Issue by GussieTech** [OnsenUI/OnsenUI#2971]
https://user-images.githubusercontent.com/2344057/165872670-b0dda5fe-0102-4ea6-b1f5-c92338de9e2e.mov

The following hack worked for me. (add %)

https://github.com/OnsenUI/OnsenUI/blob/6e1541809aef17e772dde75b8759f7f6a56df3c8/onsenui/css/css-components-src/components/progress-circular.css#L84
↓

```css
stroke-dashoffset: 0%;
```

**Comment by emccorson** [comment]
Thank you for the report. Why was this issue closed?

**Comment by emccorson** [comment]
Thank you for the report. Why was this issue closed?

**Comment by GussieTech** [comment]
@emccorson Oh, I made a mistake while editing. I will reopen it.

**Comment by takuyaW** [comment]
Hello @GussieTech.
We like your proposal/feedback and would appreciate it if you could create a Pull Request in this repository.
We thank you in advance for your contribution and are looking forward to reviewing it!

**Comment by GussieTech** [comment]
Hello @takuyaW. I created it! This is my first pull request, so sorry if it's wrong. Please check it out!

**Comment by GussieTech** [comment]
PR #3031
