### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by vit1251** [OnsenUI/OnsenUI#2975]
Good news everyone, we have React 18 version is out. How about Onsen UI make it compatible?
Do you knew any trouble on way to do that?

**Comment by emccorson** [comment]
I have not looked into this yet but this is something we will be doing at
some point.

If you are interested would you like to try the current version of Onsen UI
with React 18 and report if you find any problems? You can set your React
version to 18 and then install with npm install --force to ignore the
dependency error. That would be helpful to us to get some feedback.
