### ISSUE TITLE
React | Input not rerendering after manual input

### ISSUE THREAD

**Issue by igorbga** [OnsenUI/OnsenUI#2996]
__Environment__

  
```
[Core]
  onsenui latest
  
[Framework]
  react 17.0.2

[Framework binding]
 react-onsenui latest

[Platform]
  Desktop - Linux 64-bit

[Browser]
  Desktop - Firefox 102.0 on Linux 64-bit
```

__Encountered problem__
  
When using Ons.Input as a controlled component everything works fine as long as the user does not touch the input itself.

__How to reproduce__
  
You can reproduce it in the playground with the provided snippet.
Pressing the button will change the state from "A" to "B". 

That works as expected until you click on the input and write "C" or whatever you want.

After that pressing the button does nothing. Well in fact the button does work an if you inspect the HTML you'll see that the value for "ons-inpu" and even for the internal "input" has changed, but the user does not see it.

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html
<div id="app"></div>
```

- __JS__

```jsx
const { useState } = React

function MyPage() {
  const [currentValue, setCurrentValue] = useState("A");
  return (
    <Ons.Page>
       <Ons.Input value={currentValue} />
       <Ons.Button onClick={() => { setCurrentValue("B"); }} />
    </Ons.Page>
  )
}
ons.ready(function() {
  ReactDOM.render(<MyPage />, document.getElementById('app'));
});
```

**Comment by igorbga** [comment]
Just in case it is useful here a workaround that seems to work:

```javascript
const { useState, useEffect } = React

function MyPage() {
  const [currentValue, setCurrentValue] = useState("A");
  const [id] = useState("randomly-generated-id-for-example-with-an-uuid");
  useEffect(() => {
      const onsInput = document.getElementById(id);
      if (onsInput.value != currentValue) {
          onsInput.value = currentValue;
      }
  }, [currentValue]);

  return (
    <Ons.Page>
       <Ons.Input id={id} value={currentValue} />
       <Ons.Button onClick={() => { setCurrentValue("B"); }} />
    </Ons.Page>
  )
}
ons.ready(function() {
  ReactDOM.render(<MyPage />, document.getElementById('app'));
});
```

**Comment by emccorson** [comment]
Thanks for the bug report. I checked and was able to reproduce what you reported.

It looks like the problem is that React is setting the value _attribute_ instead of the value _property_. For most components, this shouldn't be a problem, but for an input, the value attribute is it's initial value whereas the value property is its current value.

Your workaround seems like the correct way to do things. I think the fix will be that we have to add a special exception in Input.jsx to make sure value is applied as a property and not as an attribute.

**Comment by igorbga** [comment]
Ok great emccorson, thanks.
I'll look forward for the fix.

Thanks a lot.
