### ISSUE TITLE
Core | Navigator issue: How can I use combine pages with stack navigation and pages and pages with a standard footer

### ISSUE THREAD

**Issue by lammie1971** [OnsenUI/OnsenUI#3021]
How can I combine stack navigation with pages prior that  are not in a stack and has a standard footer. 

I am not sure the way I have coded it is the best example is the ideal way;  Also on the example when the page is pushed can I stop the tab bar showing one of the tabs being active (I.e the Home tab) as it is going to one of the pages included in the stack;

Thanks. 

__Environment__

  
```
[Core]
  onsenui latest
  
[Platform]
  Desktop - OS X 10.15.6

[Browser]
  Desktop - Safari 15.6.1 on OS X 10.15.6
```

__Encountered problem__
  

__How to reproduce__
  

  
  [__Demo link__](https://onsen.io/playground/?issue)

  

- __HTML__

```html

<ons-navigator swipeable id="myNavigator" page="page1.html" animation="none"></ons-navigator>

<template id="page1.html">
  <ons-page id="page1">
    <ons-toolbar>
      <div class="center">Page 1</div>
    </ons-toolbar>

    <p>This is the first page.</p>

    <ons-button id="push-button">Push page</ons-button>
    <ons-bottom-toolbar>
      <div><p align="center">Copyright Information</p></div>
    </ons-bottom-toolbar>
  </ons-page>
</template>

<template id="page2.html">
  <ons-page id="page2">
    <ons-toolbar>
      <div class="left">
          <ons-toolbar-button id="bungle">Button 2</ons-toolbar-button>
        </div>
      <div class="center"></div>
    </ons-toolbar>

    <p>This is the second page.</p>
    <ons-tabbar swipeable id="appTabbar" position="auto">
      <ons-tab label="Home" icon="ion-ios-home" page="home.html"></ons-tab><!-- active -->
      <ons-tab label="Forms" icon="ion-ios-create" page="forms.html"></ons-tab>
      <ons-tab label="Animations" icon="ion-ios-film" page="animations.html"></ons-tab>
    </ons-tabbar>
  </ons-page>
</template>

```

- __JS__

```javascript

document.addEventListener('init', function(event) {
  var page = event.target;
   
  if (page.id === 'page1') {
    page.querySelector('#push-button').onclick = function() {
      document.querySelector('#myNavigator').pushPage('page2.html', {data: {title: 'Page 2'}});
    };
  } else if (page.id === 'page2') {
    page.querySelector('ons-toolbar .center').innerHTML = page.data.title;
    
    page.querySelector('#bungle').onclick = function() {
      document.querySelector('#myNavigator').pushPage('page1.html', {data: {title: 'Page 2'}});
   
    };
    
   
  }
});

```

**Comment by lammie1971** [comment]
Apologies, I can’t get the demo link to represent the code implemented above.

**Comment by emccorson** [comment]
Thanks for your question.

I'm not sure I entirely understand what you're trying to do. Can you explain the part about not showing the Home tab as active?

If you are trying to get a standard footer that applies to all pages, maybe something like [this example](https://onsen.io/playground/?framework=vanilla&category=reference&module=tabbar) will work. Notice how there is only one toolbar, and it is outside the tabbar, and we just update the toolbar text when the page changes.

**Comment by lammie1971** [comment]
Many thanks for the reply.

On the first page I want to have a footer that just contains a copyright notice (no links) just text and no tab_bar;

On subsequent pages I then want a tab_bar as a footer with the four links to other pages as in the original example.

Many thanks;
Paul Lamacraft
