### ISSUE TITLE
Inappbrowser cordova with vue3?

### ISSUE THREAD

**Issue by rizqisrijal** [OnsenUI/OnsenUI#3029]
Im using Vue3 with cordova, ive been looking around how to use in app browser inside the app. Does anyone know how to solve this?

**Comment by yong-asial** [comment]
@rizqisrijal  This is a general question and not related to the OnsenUI issue. For the general questions, please refer to [stackoverflow](https://stackoverflow.com/questions/tagged/onsen-ui).

Anyway, i think for this specific question, it is better to ask in [InAppBrowser](https://github.com/apache/cordova-plugin-inappbrowser) Github repository.
