### ISSUE TITLE
Error in onsenui.min.css in v2.12.3

### ISSUE THREAD

**Issue by nickredding** [OnsenUI/OnsenUI#3032]
The file onsenui.min.css contains imports which fail:

`@import url(css/ionicons/css/ionicons.min.css);
@import url(css/material-design-iconic-font/css/material-design-iconic-font.min.css);
@import url(css/font_awesome/css/all.min.css);
@import url(css/font_awesome/css/v4-shims.min.css)`

They should be (as they are in onsenui.css)

`@import url("./ionicons/css/ionicons.min.css");
@import url("./material-design-iconic-font/css/material-design-iconic-font.min.css");
@import url("./font_awesome/css/all.min.css");
@import url("./font_awesome/css/v4-shims.min.css");`

**Comment by takuyaW** [comment]
We found this issue happend from v2.12.x. We will handle this issue. Thank you.
