### ISSUE TITLE
$ons.notification.toast，center display

### ISSUE THREAD

**Issue by garymd233** [OnsenUI/OnsenUI#3034]
use ： $ons.notification.toast

How to configure display in the page center

**Comment by yong-asial** [comment]
@garymd233 The Toast notification doesn't support displaying in the page center. At the moment, it only support displaying/animating fall from the top or rise from the bottom. See this document for more detail https://onsen.io/v2/api/js/ons-toast.html#attributes

If you just want to display something in the page center, i think you can try Ons dialog - https://onsen.io/v2/api/js/ons-dialog.html
