### ISSUE TITLE
Imposible to use as library

### ISSUE THREAD

**Issue by DerGoogler** [OnsenUI/OnsenUI#3035]
![image](https://user-images.githubusercontent.com/54764558/196470691-77437f71-327e-4f95-b53d-90cf43dadb8e.png)

**Comment by takuyaW** [comment]
Cloud you share source code which reproduce the issue? Thank you. @DerGoogler

**Comment by DerGoogler** [comment]
> Cloud you share source code which reproduce the issue? Thank you. @DerGoogler 

I'm that when I home. But it's not useable as external library, because the elements gets double declared
