### ISSUE TITLE
ons-progress-bar in JS

### ISSUE THREAD

**Issue by MelvinG24** [OnsenUI/OnsenUI#3036]
__Environment__

Onsen UI Version:

- 2.11.2

Framework:

- JavaScript

Framework binding:

- none

Additional libraries:

- apache Cordova

Platform:

- browser

__Encountered problem__

I am creating my app with OnsenUI, and I am using the **<ons-progress-bar>** tag but it does not work, any suggestions? here is the code:

The problem that I have is my code never gets inside **myFunction()** function; Additionally, *document.body.scrollTop* always give 0 (zero) as a value

On my HTML file I have it like this:
```
<ons-progress-bar id="pBar" value="10"></ons-progress-bar>
```

and, on my JS file I have it like this:
```
document.addEventListener("scroll", myFunction)

function myFunction() {
    console.log('inside')
    let winScroll = document.body.scrollTop || document.documentElement.scrollTop;
    let height = document.documentElement.scrollHeight - document.documentElement.clientHeight;
    let scrolled = (winScroll / height) * 100;
    console.log(winScroll, height, scrolled)
    if (pg != 'home') {
        document.querySelector("#pBar").value = scrolled;
    }
}

```

__How to reproduce__

**Comment by takuyaW** [comment]
@MelvinG24 
I created test code in codepen. It work find.
Cloud you check it ?
https://codepen.io/takuyaW/pen/LYrEPpp

**Comment by MelvinG24** [comment]
@takuyaW I believe that it works, but for some reason, it does not work for me; I do not know if apache Cordova has something to do with it or if is the way I have onsen UI set up; I really don't know.

**Comment by MelvinG24** [comment]
If you see my code, you will notice that I add multiple time `document.addEventListener("scroll", myFunction)` a couple of times, because I was trying to find if in different steps of the loading process it would catch it up

Here is a gif image of my code:
![onsenui-problem](https://user-images.githubusercontent.com/23342477/198035618-b028fada-49cf-4317-9dcd-caa6e9daf7d5.gif)

**Comment by MelvinG24** [comment]
I have recently found out that in the onsen UI `document.body.clientHeight` refers to the **main/home** page but not to the **child/ons-page** (the one is showing after nav.pushPage is loaded). I believe if I can find a way to add the eventListener to the child page it may work

**Comment by MelvinG24** [comment]
I finally made it work!!

After realise onseUI use `document.body.clientHeight` to refers to the **main/home** page, but not the **child/ons-page** (the one after `nav.pushPage` is loaded), I found out the best approuche is by using `page.children.item(index).addEventListener()`

Here is the JS code in case there is anyone with the same issue as me:

```
document.addEventListener('init', (event) => {
    const page  = event.target

    if (page.id === 'myPage') {
        page.children.item(2).addEventListener('scroll', myFunction)
    }

    function myFunction() {
        let winScroll   = page.children.item(2).scrollTop;
        let winHeight   = page.children.item(2).scrollHeight - page.children.item(2).clientHeight;
        let scrolled    = (winScroll / winHeight) * 100;
        page.querySelector("#pBar").value = scrolled;
    }
})
```
