### ISSUE TITLE
Issue compiling with SASSC, rgba with 3 parameters instead of 4

### ISSUE THREAD

**Issue by pierre-alain-b** [OnsenUI/OnsenUI#3037]
I had issues compiling the CSS from Onsen UI with SASSC claiming that rgba cannot be with 3 arguments only. I have the feeling that it is safer to always precise the alpha parameter in the rgba function. So here:
https://github.com/OnsenUI/OnsenUI/blob/6e1541809aef17e772dde75b8759f7f6a56df3c8/onsenui/css/css-components-src/theme.css#L7
wouldn't it make sense to add the alpha = 1 parameter?

**Comment by as-hirose** [comment]
@pierre-alain-b Hi. We have released v2.12.8 and fixed this issue.
Thank you for your contributions.
