### ISSUE TITLE
Vue | peer dependency for vue 2 is only ~2.6.0

### ISSUE THREAD

**Issue by jvjvjv** [OnsenUI/OnsenUI#3041]
__Environment__

Onsen UI Version:

- ~2.12.0

Framework:

- Vue ~2.7.0

Framework binding:

- vue-onsenui 2.7.1

Additional libraries:

- n/a

Platform:

- n/a

__Encountered problem__

Attempting to install Vue Onsen UI onto the final Vue 2, version 2.7.14, cannot be done as Vue Onsen UI __requires__ 2.6.x

__How to reproduce__

```bash
npm init
# and go through the steps to initialise your project
npm install -D vue@^2.7.0
npm install -D vue-onsenui@^2.7.0
```

**Comment by Sevyls** [comment]
any update on this?

**Comment by jvjvjv** [comment]
> any update on this?



Yeah. They didn't do a good job of updating the package file. I'm opening a new issue.
