### ISSUE TITLE
Warning "Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform"

### ISSUE THREAD

**Issue by wimZ** [OnsenUI/OnsenUI#3049]
In my Capacitor app I am getting this warning using vscode Ionic extension:

Warning "Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform"

It is not a problem for me at this moment.

A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. 
Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.

Affected resources:
onsenui.min.js:1

__Environment__

Onsen UI Version: latest

Framework:
Capacitor / OnsenUI 

Framework binding:

Additional libraries:
- 

Platform:
Google PIXEL 6 emulator with Android 13/API 33

**Comment by yong-asial** [comment]
@wimZ Thank you for reporting. Could you a bit more specific especially how to re-produce this warning? For example, you could send us the sample project. Or you could tell us which "method" of onsenui that were producing the warnings. Thank you.

**Comment by wimZ** [comment]
I can no longer reproduce this issue.  

I was in migration from cordova / bootstrap to capacitor / onsen. 

Most likely it was old- and since removed- code that caused this. 

I am closing now.
