### ISSUE TITLE
500 Origin Error

### ISSUE THREAD

**Issue by sancho1952007** [OnsenUI/OnsenUI#3065]
I get a 500 Origin error almost on every page of the docs.
One of the page includes: https://onsen.io/v2/guide/fundamentals.html#fundamentals-onsen-ui-101

**Comment by takuyaW** [comment]
@sancho1952007  I've just fixed the issue you reported. Please try accessing the pages again, including https://onsen.io/v2/guide/fundamentals.html#fundamentals-onsen-ui-101. If you encounter any further issues, feel free to let me know.

**Comment by sancho1952007** [comment]
Yeah, it's fixed. Thanks 👍
