### ISSUE TITLE
ons-popover non-functional in Chrome since April 23, 2023

### ISSUE THREAD

**Issue by kartnip** [OnsenUI/OnsenUI#3070]
reproducible using the latest version of chrome:
https://onsen.io/v2/api/js/ons-popover.html

**Comment by kartnip** [comment]
RESOLVED: this is a namespace conflict, no core changes are required. simply change the function named showPopover() to showOnsenPopover() or similar (the latest version of Chrome uses showPopover() namespace for the new popover api)

**Comment by takuyaW** [comment]
@kartnip 
Thank you for bringing the issue regarding the ons-popover to our attention. Following your proposed solution, we have renamed the function from showPopover() to showOnsPopover() and have resolved the problem. Now it should work correctly with the latest version of Chrome.

Please feel free to let us know if there are any other concerns or suggestions. We always welcome feedback to improve this project.
