### ISSUE TITLE
Sponsoring OnsenUI?

### ISSUE THREAD

**Issue by scottward** [OnsenUI/OnsenUI#3074]
I couldn't figure out how to contact you all, but I'm interested in being a sponsor of this project.

Are you taking on sponsors?

**Comment by tacman** [comment]
@scottward did you ever find another solution?  I've searched everywhere, and this is the best open-source library for hybrid/mobile apps that I can find.

**Comment by franklynsd** [comment]
@tacman I also think this project is great. I have not been able to find something to replace it.  Somebody with some info about this?

**Comment by pauloferoz** [comment]
framework7.io , This is a valid option

**Comment by tacman** [comment]
wow, that looks great.  Active development.
