### ISSUE TITLE
Sliding Menu 'swipeable' attribute Typo

### ISSUE THREAD

**Issue by sanbornhilland** [OnsenUI/OnsenUI#312]
The sliding menu has a swipeable attribute but it appears to be mispelled as 'swipable' both in the docs and the actual implementation. This had us tripped up for a little while and I expect it will trip up other people too.

Cheers.

**Comment by zumbrunnen** [comment]
Hi there! It would be marvelous if the documentation/guides/demos were updated.

I've spent more than an hour to sort out why my menu didn't respond to swiping. :confounded:

**Comment by argelius** [comment]
Thanks! I saw that it was incorrect in the sliding menu template so I've changed it. Are there any other places where it still says "swipeable"?

**Comment by zumbrunnen** [comment]
Thanks! I've got my `swipable` from the sliding menu template indeed. But I've seen it also here: http://onsenui.github.io/demo/sliding_menu_swipable_demo.html

BTW: We're switching over from a "mobile web"-focused framework to Onsen. Onsen UI rocks! :+1:

**Comment by argelius** [comment]
Oh, I see!

The GitHub pages are not up-to-date. We'll add a redirect to [the website](http://onsen.io).
