### ISSUE TITLE
1.2.0 beta issues with <ons-toolbar> trim and center

### ISSUE THREAD

**Issue by gtsopour** [OnsenUI/OnsenUI#315]
Hello, I am using the following code with the 1.2.0 beta release and it seems that after the build (not in the BROWSER as in the browser all seems ok) in iOS and Android devices the title is not trimmed in both of them and it is not also centered in Android devices.

Thanks for all
George

**Comment by Hirbod** [comment]
imho, ellipsis should definitely be a default option!

**Comment by argelius** [comment]
I understand what you mean, but without `overflow: hidden` you can have longer titles. That's the reason why I'm reluctant to add it. :)

With `overflow: hidden` it will cut every title at 50% toolbar width.
