### ISSUE TITLE
ons-popover not in the component guide :(

### ISSUE THREAD

**Issue by samaphp** [OnsenUI/OnsenUI#322]
Just a heads up that this tiny issue which it takes my time, because there is no guide for ons-popover on this URL: http://s.onsen.io/guide/components.html

How can I hide the popover after push the page?

Here what I did is a quick use of it:

``` javascript
$scope.ons.ready(function() {
  $scope.ons.createPopover('foobar.html').then(function(popover) {
    $scope.popover = popover;
  });
});
$scope.showPopOver = function(e) {
  $scope.popover.show(e);
}
```

Since the popover here will be in another template I added this code in the same page I want to show that popover in:

``` javascript
<ons-template id="foobar.html">
  <ons-popover direction="down" cancelable>
    <ul class="list">
      <li class="list__item list__item--tappable">
        Tappable Item
      </li>
      <li class="list__item list__item--tappable">
        <a onclick="appNavigator.pushPage('settings.html',{title: 'Settings', animation: 'slide'})">Settings</a>
      </li>
    </ul>
  </ons-popover>
</ons-template>
```

And here is the trigger:

``` javascript
<ons-button id="popOverButton" ng-click="showPopOver('#popOverButton')"><ons-icon icon="ion-more" class="rotate90"></ons-button>
```

After googleing I found this example in this file:
https://github.com/OnsenUI/OnsenUI/blob/master/test/manual-testcases/popover/00-popover.html
I just added `$scope.` to make it work on my `app.js` file.

**_But now I can't found a solution to hide the popover after push page to another page while the popover is still opened.**_
:camel:

Kindly see the issue here:
http://codepen.io/anon/pen/dPPPGe

Many thanks for this wonderful framework <3

**Comment by kountouretis** [comment]
hi i have the same issue.. i am new with onsen framework and i don't know how to use the popover.hide() i found a working example on http://codepen.io/andipavllo/pen/pJzPqE but when i try it to my project is not work.. Can anybody hepl? thanks.

**Comment by argelius** [comment]
@kountouretis Can you please paste the code that isn't working?

**Comment by kountouretis** [comment]
![1](https://cloud.githubusercontent.com/assets/9192697/11620818/d820d65c-9cbe-11e5-87f0-c7ee2c6a69ec.jpg)
![2](https://cloud.githubusercontent.com/assets/9192697/11620820/d824296a-9cbe-11e5-9f03-f6b9cf1a700a.jpg)
![3](https://cloud.githubusercontent.com/assets/9192697/11620819/d8235e40-9cbe-11e5-8277-47dd0c05383a.jpg)
