### ISSUE TITLE
iOS 8 error with radio/input + overflow:touch

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#328]
Hi,

having a tabbar with some checkboxes inside a ons-list, I receive 

```
[WebActionDisablingCALayerDelegate setBeingRemoved:]: unrecognized selector sent to instance 0x18aebbd0
2014-11-20 04:19:21.728 Nachbarschaft[576:101950] *** WebKit discarded an uncaught exception in the webView:willRemoveScrollingLayer:withContentsLayer:forNode: delegate: <NSInvalidArgumentException> -[WebActionDisablingCALayerDelegate setBeingRemoved:]: unrecognized selector sent to instance 0x18aebbd0
```

on iOS 8.1. The real device does not crash, simulator does. It happens due to multiple -webkit-overflow-scroll: touch; attributes. If I remove <ons-list> the error is gone. I'm sure this is a iOS bug, but actually, page_content already has -scroll:touch - I'm not sure if this important. (It also happens when I use a ```<ons-scroller>``` directive.

http://servercoredump.com/question/25894173/uiwebview-throwing-exception-webactiondisablingcalayerdelegate-setbeingremoved

http://stackoverflow.com/questions/25894173/uiwebview-throwing-exception-for-webactiondisablingcalayerdelegate-setbeingremo

Maybe there is a translateZ workaround or something else. The bug does not occur on iOS 7.

**Comment by Hirbod** [comment]
This is an iOS bug. You can't really fix it. There a many ways (translateZ hack).
It happens with calculation width/height on input/textarea and with webkit-overflow touch.

So I'm closing this one here..

**Comment by leandro-shifteight** [comment]
I am having this problem now, what did you do @Hirbod ?

**Comment by pulimento** [comment]
+1

**Comment by Hirbod** [comment]
You can ignore this "bug". It's just an message inside of XCode, it does not break anything nor crash the app

**Comment by Harryteja** [comment]
Can any one tell, how it is  solved..it is throwing an exception like [WebActionDisablingCALayerDelegate willBeRemoved]: .. I am using UIWebVIew
