### ISSUE TITLE
<ons-screen> not working in android 4.4

### ISSUE THREAD

**Issue by disruptiveP** [OnsenUI/OnsenUI#348]
I am using Monaca IDE to develop an app, Well, I get a white screen on using a ons-screen tag. Here is my code Can anyone help with a ons-screen example

All pages are separate .

```
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link rel="stylesheet" href="components/loader.css">
<script src="components/loader.js"></script>
</head>
<body>
<ons-screen page="home_navigator.html"></ons-screen>
</body>
</html>

<!--home_navigator--!>
<ons-navigator page="page1.html"></ons-navigator>

<!--page1.html--!>
<ons-page>
<ons-toolbar>
<div class="center">
    Page 1
</div>
</ons-toolbar>
 <ons-button ng-click="ons.navigator.PushPage('page2.html')">Page 2</ons-button>
</ons-page>
```

**Comment by rahilwazir** [comment]
@argelius Whats the replacement of `<ons-screen>` then?

**Comment by argelius** [comment]
Just replace it with the code it was loading. For a navigator you can use the `page` attribute if you want to load from a template.

**Comment by alenb** [comment]
Are there any examples that showcase this? I can't seem to find any on the Onsen Guide about it.

**Comment by argelius** [comment]
@alenb You can use the `page` attribute of the `<ons-navigator>` component.

```html
<ons-navigator title="Navigator" var="myNavigator" page="main.html"></ons-navigator>
```
