### ISSUE TITLE
Recustomizing a customized theme

### ISSUE THREAD

**Issue by RezaRahmati** [OnsenUI/OnsenUI#354]
I know this is not a bug and is a change request.
As a user I expect to be able to re-customize a customized them, I have created a custom theme and after a while I need to change a color, but I should start from scratch or go directly into the css file.
I think it would be better if there was an upload option in theme customizer page, so I could upload my downloaded css file and then I could continue customizing the old one.

**Comment by yamatee** [comment]
+1  I want to just  import custom-theme.stylus(color values) to theme roller.
