### ISSUE TITLE
on pagepush error Fail to fetch PageView from ons-page element

### ISSUE THREAD

**Issue by iRealNirmal** [OnsenUI/OnsenUI#366]
Hi,

I have written below function on ng-click
$scope.ons.navigator.pushPage('pagename.html');

but on response getting the error

Uncaught Error: Fail to fetch PageView from ons-page element.
onsenui.js line number 7707
 using
/*! onsenui - v1.2.0 - 2014-11-10 */

**Comment by Someguy123** [comment]
Note for anyone googling this error: this happens if you try to use `navigator.pushPage('something.html')` instead of `menu.setMainPage('something.html')` when you have a sliding menu set up.

**Comment by newmesiss** [comment]
nil4you tengo el mismo problema, lo solucionaste?

**Comment by nil4you** [comment]
Yup, I solved it better to give var attribute to the ons navigator like
**HTML**
<ons-navigator  var="app.navi">
**Javascript**
<script>
var options = {
  animation: 'slide', // What animation to use
  onTransitionEnd: function() {} // Called when finishing transition animation
};
app.navi.pushPage("pagename.html", options);
</script>

**Comment by nil4you** [comment]
Yup, I solved it better to give var attribute to the ons navigator like
**HTML**

    <ons-navigator  var="app.navi">

**Javascript**
    var options = {
    animation: 'slide', // What animation to use
    onTransitionEnd: function() {} // Called when finishing transition animation
    };
    app.navi.pushPage("pagename.html", options);

**Comment by murliatdure** [comment]
Can we use the app.navi.pushPage and ons-sliding-menu together?

I tried the given approiach, what I observed the pushPage with slide animation fails.. Whereas Fade, life and none animation wo't give this problem.

Please assist

**Comment by argelius** [comment]
@murliatdure 

Yes, you can use them together. Could you make a Codepen example that shows the issue?

**Comment by blarney2000** [comment]
@murliatdure , I also get the "Fail to fetch PageView" error with slide and not fade transitions. I can just used fades but I feel that sliding is more intuitive for navigation.

**Comment by blarney2000** [comment]
@argelius Here is the Codepen example: http://codepen.io/blarney2000/pen/ONvOzR?editors=1111

If you click on a list item on the start page, app's script stops due to the "Fail to fetch PageView" error
