### ISSUE TITLE
Carousel and Vertical Scrolling

### ISSUE THREAD

**Issue by khoshrou** [OnsenUI/OnsenUI#380]
Hi
I searched and I couldn't find any thing. Does carousel have a problem with vertical scrolling.
I have a list in a carousel item and it does not scroll vertically is this on purpose or its a bug?

**Comment by khoshrou** [comment]
Hi I did something about this, it seems working, I hope it helps (I am not sure about all the scenarios)
Css: 

ons-carousel-item {
  overflow-y: auto;
  overflow-x: hidden; }

JavaScript:
_onDragStart: function (event) {
          this._start = event.gesture.direction;
      },
      _onDrag: function (event) {
          if (this._start == 'left' || this._start == 'right') {
              this._lastDragEvent = event;

              var scroll = this._scroll - this._getScrollDelta(event);
              this._scrollTo(scroll);
              event.gesture.preventDefault();

              this._tryFirePostChangeEvent();
          }
      },

      _onDragEnd: function (event) {
          if (this._start == 'left' || this._start == 'right') {
              this._scroll = this._scroll - this._getScrollDelta(event);
              this._tryFirePostChangeEvent();

              if (this._isOverScroll(this._scroll)) {
                  this._scrollToKillOverScroll();
              } else if (this._lastDragEvent !== null) {
                  this._startMomemtumScroll(event);
              }
              this._lastDragEvent = null;
              event.gesture.preventDefault();
          }
          this._start = undefined;
      },

**Comment by argelius** [comment]
Added `overflow-x: auto` (or overflow-y depending on if it's a vertical or horizontal carousel).

Thanks, @khoshrou !

**Comment by khoshrou** [comment]
Yes, I used a horizontal carousel

**Comment by ramingar** [comment]
I'm trying with this code:

```html
<article ng-repeat="feed in results._embedded.feeds">
    <ons-carousel style="height: 100px; width:100%" initial-index="1"
    auto-refresh overscrollable swipeable auto-scroll auto-scroll-ratio="0.2">
        <ons-carousel-item>
            <div>SORPREEEEESA1!!!</div>
        </ons-carousel-item>
        <ons-carousel-item>
            <ng-include src="'templates/feeds/feed-list.html'"></ng-include>
        </ons-carousel-item>
        <ons-carousel-item>
            <div>SORPREEEEESA2!!!</div>
        </ons-carousel-item>
    </ons-carousel>
</article>
```

I can only swipe, but not vertical scrolling.

In this example http://codepen.io/onsen/live/emmKpV/ happens too.

Is it my fault? Or is a bug?

**Comment by rahul100885** [comment]
Is it vertical scrolling still have an issue?
