### ISSUE TITLE
ons-sliding-menu bug

### ISSUE THREAD

**Issue by longZ** [OnsenUI/OnsenUI#382]
I use ons-sliding-menu  in ons-split-view, when postcollapse,  a error happened.
the error is "Uncaught TypeError: Cannot read property 'maxSlideDistance' of null"  onsenui.js:11172
"this._attrs.maxSlideDistance"  cannot read.

**Comment by frankdiox** [comment]
This also happens after doing a 'popPage' from an 'ons-page' with a sliding-menu and opening the keyboard, so perhaps it's not related to 'ons-split-view'.

**Comment by argelius** [comment]
Thanks @frankdiox !

**Comment by argelius** [comment]
Solving this bug also solved a memory leak which is nice. :+1:
