### ISSUE TITLE
ons-popover does not work inside tab-bar and no auto $destroy

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#383]
Hi,

the popover does not work inside of a tabbar. z-index seems to be wrong and the bubble position arrow is not showing.

I've also seen, that ons-popover stays in DOM even when you change the page and gets recreated every time the controller inits. ons-popover should bind on $destroy and remove itself from the DOM.

![bildschirmfoto 2014-12-23 um 10 23 47](https://cloud.githubusercontent.com/assets/504909/5536218/fb05f54c-8a8d-11e4-9c90-570d0d07834b.png)

**Comment by argelius** [comment]
Hi, since `ons.createPopover` is a global function the popover is not attached to the DOM of the controller. You need to create an event handler for the `$destroy' event:

```javacript
angular.module('myApp').controller('MyController', function($scope) {
  ons.ready(function() {
    ons.createPopover('popover.html').then(function(popover) {
      $scope.popover = popover;
    });
  });

  $scope.$on('$destroy', $scope.popover.destroy);
});
```

**Comment by Hirbod** [comment]
And what about that bug? Did you fix this?

**Comment by Hirbod** [comment]
@argelius what about the display glitch?
