### ISSUE TITLE
Event handlers as attributes, e.g. ng-postchange

### ISSUE THREAD

**Issue by jonasfj** [OnsenUI/OnsenUI#387]
It's very hard to bind to custom events offered by onsen.

Couldn't carousel, navigator, sliding-menu, tabbar, ie. all components that offer events have an attribute for the event like `ng-click`.. So that the `postchange` event on caruosel can be hooked as follows:
```html
<ons-carousel swipeable overscrollable auto-scroll fullscreen ng-postchange="myHandler()">
  <ons-carousel-item style="background-color: gray;">
    <div class="item-label">GRAY</div>
  </ons-carousel-item>
</ons-carousel>
```

Same thing could be done for the all the events offered by other components. I'm new to angularjs, but it's seems very hard (near impossible) to reliably hook events. As the `var="myVarName"` isn't always set on `ons.ready`. For carousel, you seem to be left listening for `ons-carousel:init` (see #365), which means you're in bug trouble if your app needs two carousels (Also it pollutes).

**Comment by argelius** [comment]
Thanks for reporting, @jonasfj !

We'll consider adding this feature.

**Comment by ksornberger** [comment]
This would be a great addition!

**Comment by frankdiox** [comment]
This feature was added in [v1.3.0].(https://github.com/OnsenUI/OnsenUI/blob/master/CHANGELOG.md#v130)
