### ISSUE TITLE
Dialogs on each other

### ISSUE THREAD

**Issue by khoshrou** [OnsenUI/OnsenUI#388]
Hi
I used new dialog component to show error message and i come to a situation where two erros happend and I got two dialogs on eah other I have made dialogs not cancelable. this lands in a situation where the first dialogs buttons stop working. I dont know if its a bug or I am doing something wrong. 
hope it helps.
PS. can you give a speific css to change dialogs header backgrounnd color

**Comment by argelius** [comment]
Hello @khoshrou !

I'm unable to reproduce this. How do you show the alert dialogs?

It works well in this example:
http://codepen.io/argelius/pen/VYmQJz

**Comment by khoshrou** [comment]
Hi
use http://codepen.io/onsen/pen/zxxaGa
for the navigator sample remove cancelable and replace ng-click with this
show('navigator.html');show('navigator.html')
just calling the show method twice.

**Comment by argelius** [comment]
Oh I see, it's because they both share the same variable name since it's the same dialog. Can you make them into two different dialogs? Or maybe use the `ons.notification` methods?

**Comment by khoshrou** [comment]
I have a method like this sample to show error messages and some times more than one error happens and also I need some special buttons that's why i cant use notification.so..
isn't it a bug? or how can we have a single 'show' function like this and not having this problem?

**Comment by argelius** [comment]
I don't think it's a bug. We haven't intended the same dialog to be showed multiple times. 

Maybe you can write your own `show()` function that keeps track if it's already displayed or maybe an "Error queue" that displays the errors in turn after they've been confirmed.

**Comment by khoshrou** [comment]
ok, Its kind of strange coz I dupliated every thing and its still has the problem

**Comment by argelius** [comment]
Did you change the `var` attribute? If so, I believe it's a bug.

**Comment by khoshrou** [comment]
Sorry I forgot to change var attribute. You are right thats the single variable problem.
