### ISSUE TITLE
Content inside of ons-scroller is whiped if placed inside of an ons-dialog

### ISSUE THREAD

**Issue by prodigga** [OnsenUI/OnsenUI#389]
Hey guys. Just started out with OnsenUI and loving it! Good work so far :)

In my app, I am trying to create something similar to a facebook 'select friend' popup dialog. Inside this dialog, I have a toolbar with a heading, an ons-scroller and an ons-list populated with qualifying friends for the current request.

The problem is that when I put anything inside of the ons-scroller, the content is whiped. You can inspect the HTML of the page and see the HTML elements are actually gone, not hidden in any way.

**Comment by prodigga** [comment]
Here is a jsfiddle, I don't know how to embed here, sorry!

http://codepen.io/anon/pen/GgNQyv

**Comment by argelius** [comment]
Thanks @prodigga, we'll keep making Onsen UI better.

We'll take a look at this.

**Comment by argelius** [comment]
Fixed.
