### ISSUE TITLE
when I was using  ons-tabbar

### ISSUE THREAD

**Issue by 87260280** [OnsenUI/OnsenUI#390]
dear all:

my index.html and page1.html is located in seperate pagefile, but when i click the tab page1 in index.html, the script part was not evaled, and the tap page1 still show "This content will be replaced." but its not be replaced! 

i dont understand how to seperate file and not write all the html and javascript in Only one source file!
```
my index.html file:
#<ons-tabbar>
  #  <ons-tab page="page1.html" label="Page 1" icon="square" active="true"></ons-tab>
    #<ons-tab page="page2.html" label="Page 2" icon="square"></ons-tab>
    #<ons-tab page="map.html" label="Page 3" icon="square"></ons-tab>
    #<ons-tab page="page4.html" label="Page 4" icon="square"></ons-tab>
    #<ons-tab page="page5.html" label="Page 5" icon="square"></ons-tab>
#</ons-tabbar>

my page1 file:

#<ons-page id="my-page">
  # <script>
    #       document.getElementById("my-content").innerHTML = "I am fine!";
   #</script>
    #<div id="my-content">This content will be replaced.</div>
#</ons-page>
```

**Comment by woyehenni** [comment]
Hi,

I think you should put the "id selector" behind the DOM which id is "my-content".
```html
<ons-page id="my-page">
    <div id="my-content">This content will be replaced.</div>
    <script>
    document.getElementById("my-content").innerHTML = "I am fine!";
   </script>
</ons-page>
```

**Comment by 87260280** [comment]
i think it was possibly not the cause! i saw non a line javascript on the page1.html file was loaded either executed! when i place a <script src="http//..."><script> on page1.html, it was not query from server! even none a http connect to this js file.

**Comment by argelius** [comment]
@87260280 

Hi, `<script>` tags in templates will not be evaluated. The browser doesn't evaluate scripts when they are added to the DOM and OnsenUI doesn't run `eval` on it.

I don't think there is any situation where you need to put script tags in your template tags. Just write your JavaScript in a `js` file and import it in your index.html.
