### ISSUE TITLE
pushPage causes tabbar to disappear

### ISSUE THREAD

**Issue by jpshaver** [OnsenUI/OnsenUI#391]
As the title says, when using pushPage on ng-click the app navigates to the page but without the tabbar..

Any suggestions?

Thanks...

**Comment by woyehenni** [comment]
Hi

Could you provide your live demo please.

Do you mean like the following code?
```html
<ons-navigator title="Navigator" var="myNavigator">
  <ons-page>
    <ons-toolbar>
      <div class="center">Simple Navigation</div>
    </ons-toolbar>
    <div style="text-align: center">
      <br>
      <ons-button modifier="light" onclick="myNavigator.pushPage('page1.html', { animation : 'slide' } )">
        Push Page
      </ons-button>
    </div>
  </ons-page>
</ons-navigator>

<ons-template id="page1.html">
  <ons-page>
<ons-tabbar>
	<ons-tab page="home.html" label="Home" icon="ion-home" active="true"></ons-tab>
  <ons-tab page="comments.html" label="Comments" icon="ion-chatbox-working"></ons-tab>
  <ons-tab page="tags.html" label="Tags" icon="ion-ios7-pricetag"></ons-tab>
  <ons-tab page="settings.html" label="Settings" icon="ion-ios7-cog"></ons-tab>
</ons-tabbar>

  </ons-page>
</ons-template>

<ons-template id="home.html">
  <ons-toolbar>
    <div class="center">Home</div>
  </ons-toolbar>
  
  <p style="padding-top: 100px; color: #999; text-align: center">Page Contents</p>
</ons-template>

<ons-template id="comments.html">
  <ons-toolbar>
    <div class="center">Comments</div>
  </ons-toolbar>
  
  <p style="padding-top: 100px; color: #999; text-align: center">Page Contents</p>
</ons-template>

<ons-template id="tags.html">
  <ons-toolbar>
    <div class="center">Tags</div>
  </ons-toolbar>
  
  <p style="padding-top: 100px; color: #999; text-align: center">Page Contents</p>
</ons-template>

<ons-template id="feed.html">
  <ons-toolbar>
    <div class="center">Feed</div>
  </ons-toolbar>
  
  <p style="padding-top: 100px; color: #999; text-align: center">Page Contents</p>
</ons-template>

<ons-template id="settings.html">
  <ons-toolbar>
    <div class="center">Settings</div>
  </ons-toolbar>
  
  <p style="padding-top: 100px; color: #999; text-align: center">Page Contents</p>
</ons-template>

```

**Comment by jpshaver** [comment]
Cannot do live demo... here's some of the code. the node.html does a pushpage back to it's self (loops).. 

<ons-navigator var="appNavigator">
        <ons-page>
            <ons-tabbar>
                <ons-tab page="decision.html" active="true">
                    <div class="tab">
                        <ons-icon icon="ion-social-buffer" class="tab-icon"></ons-icon>
                        <div class="tab-label">Decisions</div>
                    </div>
                </ons-tab>
                <ons-tab page="downloads.html">
                    <div class="tab">
                        <ons-icon icon="ion-cloud" class="tab-icon"></ons-icon>
                        <div class="tab-label">Downloads</div>
                     </div>
                </ons-tab>
                <ons-tab page="contact.html">
                    <div class="tab">
                        <ons-icon icon="ion-email" class="tab-icon"></ons-icon>
                        <div class="tab-label">Contact</div>
                    </div>
                </ons-tab>
                <ons-tab page="about.html">
                    <div class="tab">
                        <ons-icon icon="ion-information-circled" class="tab-icon"></ons-icon>
                        <div class="tab-label">About</div>
                     </div>
                </ons-tab>
            </ons-tabbar>
        </ons-page>
    </ons-navigator>

    <ons-template id="decision.html">        
            <ons-page>
                <ons-toolbar>
                    <div class="center">Decision</div>
                </ons-toolbar>
                <div class="page-container">
                    <ons-row style="margin-top: 10px;">
                        <ons-col align="left">
                            <img src="img/logo.png" class="logo" />
                        </ons-col>
                    </ons-row>
                    <ons-row style="margin-top: 10px;">
                        <ons-col align="center">
                            <ons-icon icon="ion-social-buffer" class="page-icon"></ons-icon>
                            <div class="page-heading">Decisions</div> 
                        </ons-col>
                    </ons-row>
                    <ons-row style="margin-top: 10px;">
                        <ons-col align="left">                    
                            <div ng-controller="DecisionCtrl as decision">
                                <ons-list-header>Decisions</ons-list-header>  
                                <ons-list>
                                  <ons-list-item class="item" modifier="chevron" ng-repeat="item in decision.items">
                                    <ons-row>                                  
                                      <ons-col>
                                          <ons-list-item ng-click="appNavigator.pushPage('node.html', { animation : 'slide', decisionid: item.DecisionId, start: true } )">{{item.Name}}</ons-list-item>
                                      </ons-col>
                                    </ons-row>                          
                                  </ons-list-item>
                                </ons-list>
                            </div>
                        </ons-col>
                    </ons-row>
                 </div>
             </ons-page>            
    </ons-template>


    <ons-template id="node.html">
        <ons-page>
            <ons-toolbar>
                <div class="left"><ons-back-button>Back</ons-back-button></div>
                <div class="center">Decision</div>
            </ons-toolbar>
            <div class="page-container">
                <div ng-controller="NodeCtrl as node" ng-init="node.getNode()" >
                    <ons-row style="margin-top: 10px;">
                        <ons-col align="left">
                            <img src="img/logo.png" class="logo" />
                        </ons-col>
                    </ons-row>
                    <ons-row style="margin-top: 10px;">
                        <ons-col align="center" ng-init="node.getDecisionName()">                            
                                <ons-icon icon="ion-social-buffer" class="page-icon"></ons-icon>
                                <div class="page-heading">{{node.decisionName}}</div>                            
                        </ons-col>
                    </ons-row>
                    <ons-row style="margin-top: 10px;">
                        <ons-col align="left">
                            <div>
                                <ons-list-header>{{node.question}}</ons-list-header>  
                                <ons-list>
                                  <ons-list-item class="item" modifier="chevron" ng-repeat="branch in node.branches">
                                    <ons-row>                                  
                                      <ons-col>
                                          <ons-list-item ng-click="appNavigator.pushPage('node.html', { animation : 'slide', decisionid: branch.DecisionId, guid: branch.Target, nodeTypeId: node.nodeTypeId } )">{{branch.Text}}</ons-list-item>
                                      </ons-col>
                                    </ons-row> 
                                  </ons-list-item>
                                </ons-list>
                            </div>
                            <div class="end-node-content"><p ng-bind-html="node.endNodeContent"></p></div>
                        </ons-col>
                    </ons-row>
                </div>
             </div>
         </ons-page>
    </ons-template>

**Comment by jpshaver** [comment]
<p>Cannot do live demo... here's some of the code. the node.html does a pushpage back to it's self (loops).. </p>

```html
  <ons-navigator title="Navigator" var="appNavigator">
        <ons-page>
            <ons-tabbar>
                <ons-tab page="decision.html" active="true">
                    <div class="tab">
                        <ons-icon icon="ion-social-buffer" class="tab-icon"></ons-icon>
                        <div class="tab-label">Decisions</div>
                    </div>
                </ons-tab>
                <ons-tab page="downloads.html">
                    <div class="tab">
                        <ons-icon icon="ion-cloud" class="tab-icon"></ons-icon>
                        <div class="tab-label">Downloads</div>
                     </div>
                </ons-tab>
                <ons-tab page="contact.html">
                    <div class="tab">
                        <ons-icon icon="ion-email" class="tab-icon"></ons-icon>
                        <div class="tab-label">Contact</div>
                    </div>
                </ons-tab>
                <ons-tab page="about.html">
                    <div class="tab">
                        <ons-icon icon="ion-information-circled" class="tab-icon"></ons-icon>
                        <div class="tab-label">About</div>
                     </div>
                </ons-tab>
            </ons-tabbar>
        </ons-page>
    </ons-navigator>

    <ons-template id="decision.html">        
            <ons-page>
                <ons-toolbar>
                    <div class="center">Decision</div>
                </ons-toolbar>
                <div class="page-container">
                    <ons-row style="margin-top: 10px;">
                        <ons-col align="left">
                            <img src="img/logo.png" class="logo" />
                        </ons-col>
                    </ons-row>
                    <ons-row style="margin-top: 10px;">
                        <ons-col align="center">
                            <ons-icon icon="ion-social-buffer" class="page-icon"></ons-icon>
                            <div class="page-heading">Decisions</div> 
                        </ons-col>
                    </ons-row>
                    <ons-row style="margin-top: 10px;">
                        <ons-col align="left">                    
                            <div ng-controller="DecisionCtrl as decision">
                                <ons-list-header>Decisions</ons-list-header>  
                                <ons-list>
                                  <ons-list-item class="item" modifier="chevron" ng-repeat="item in decision.items">
                                    <ons-row>                                  
                                      <ons-col>
                                          <ons-list-item ng-click="appNavigator.pushPage('node.html', { animation : 'slide', decisionid: item.DecisionId, start: true } )">{{item.Name}}</ons-list-item>
                                      </ons-col>
                                    </ons-row>                          
                                  </ons-list-item>
                                </ons-list>
                            </div>
                        </ons-col>
                    </ons-row>
                 </div>
             </ons-page>            
    </ons-template>


    <ons-template id="node.html">
        <ons-page>
            <ons-toolbar>
                <div class="left"><ons-back-button>Back</ons-back-button></div>
                <div class="center">Decision</div>
            </ons-toolbar>
            <div class="page-container">
                <div ng-controller="NodeCtrl as node" ng-init="node.getNode()" >
                    <ons-row style="margin-top: 10px;">
                        <ons-col align="left">
                            <img src="img/logo.png" class="logo" />
                        </ons-col>
                    </ons-row>
                    <ons-row style="margin-top: 10px;">
                        <ons-col align="center" ng-init="node.getDecisionName()">                            
                                <ons-icon icon="ion-social-buffer" class="page-icon"></ons-icon>
                                <div class="page-heading">{{node.decisionName}}</div>                            
                        </ons-col>
                    </ons-row>
                    <ons-row style="margin-top: 10px;">
                        <ons-col align="left">
                            <div>
                                <ons-list-header>{{node.question}}</ons-list-header>  
                                <ons-list>
                                  <ons-list-item class="item" modifier="chevron" ng-repeat="branch in node.branches">
                                    <ons-row>                                  
                                      <ons-col>
                                          <ons-list-item ng-click="appNavigator.pushPage('node.html', { animation : 'slide', decisionid: branch.DecisionId, guid: branch.Target, nodeTypeId: node.nodeTypeId } )">{{branch.Text}}</ons-list-item>
                                      </ons-col>
                                    </ons-row> 
                                  </ons-list-item>
                                </ons-list>
                            </div>
                            <div class="end-node-content"><p ng-bind-html="node.endNodeContent"></p></div>
                        </ons-col>
                    </ons-row>
                </div>
             </div>
         </ons-page>
    </ons-template>

```

**Comment by argelius** [comment]
I haven't looked through all the code, but you have a tab bar inside a navigator. Everything inside the navigator will be removed when you push a page to it. You should put the tab bar on the higher lever and use navigators for the tab pages.

**Comment by jpshaver** [comment]
That worked... Thanks!
