### ISSUE TITLE
ons-split-view. Template error "Page not found"

### ISSUE THREAD

**Issue by wshark6** [OnsenUI/OnsenUI#392]
I have a Split View defined as:

    <ons-split-view
        var="noticies_split"
        secondary-page="secundaria"
        main-page="principal"
        main-page-width="70%"
        collapse="portrait">
    </ons-split-view>

I get a "Page is not found: principal" if I define both templates consecutively, i.e.:

    <ons-template id="secundaria">
    </ons-template>
    <ons-template id="principal">
    </ons-template>
If I define a third template between them, it works fine, i.e:

    <ons-template id="secundaria">
    </ons-template>
    <ons-template id="aux">
    </ons-template>
    <ons-template id="principal">
    </ons-template>

When defining more than 2/3 templates, I get the same error for those in even positions, but not for the odd ones.

I'm using onsenui - v1.2.1 - 2014-12-01

**Comment by argelius** [comment]
Hi @wshark6!

I tried your code but didn't get the error message. Is it possible for you to upload your failing code somewhere so I can have a look at it? 

It may be some other reason why it doesn't parse the second template.

**Comment by wshark6** [comment]
If you give me an email address, I can send it to you.

**Comment by argelius** [comment]
Sure, please send it to

```javascript
console.log('andreas.argeli.us'.replace(/\./, '@'));
```

**Comment by wshark6** [comment]
Hello,

this solution worked fine.

http://stackoverflow.com/a/28291754/4452681
