### ISSUE TITLE
ons-button with ng-click and disabled

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#395]
Hi,

when I use ons-button with ng-click and change attribute ```buttonVar.setDisabled( true / false )```, ng-click don't work anymore. This is something important and the directive should handle this correctly as it doesn't provide an own click event.

Could you please fix this asap?

**Comment by argelius** [comment]
Work's fine when I try it. When the button is disabled it doesn't listen to pointer events. Do you feel this is incorrect behavior?

**Comment by Hirbod** [comment]
It is correct but when I enable again ngclick does not work

**Comment by argelius** [comment]
That's strange. What browser are you using?

It just adds a `disabled` attribute to the button which has CSS like this:

```css
ons-button[disabled] {
  pointer-events: none;
}
```

so it sounds like some kind of browser bug.

**Comment by Hirbod** [comment]
iOS 

Von meinem iPhone gesendet

**Comment by argelius** [comment]
I tried it in iOS8 and didn't have any trouble. 

```html
<!doctype html>
<html lang="en" ng-app="app">
<head>
  <meta charset="utf-8">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <title>My App</title>  
  
  <link rel="stylesheet" href="lib/onsen/css/onsenui.css">  
  <link rel="stylesheet" href="styles/onsen-css-components-blue-basic-theme.css">  
  <link rel="stylesheet" href="styles/app.css"/>

  <script src="lib/onsen/js/angular/angular.js"></script>    
  <script src="lib/onsen/js/onsenui.js"></script>    

  <script src="cordova.js"></script>

  <script>
    var module = angular.module('app', ['onsen'])

    .controller('DisabledController', function($scope) {
      $scope.$watch('disabled', function(value) {
        $scope.button.setDisabled(value);
      });

      $scope.doSomething = function() {
        alert("something");
      };
    });
  </script>

  <style>
 </style>
  
</head>

<body>

  <ons-page ng-controller="DisabledController">
    <ons-toolbar>
      <div class="center">Disabled button test</div>
    </ons-toolbar>
 
    <p style="text-align: center; color: #999; font-size: 14px;">
      <ons-button var="button" ng-click="doSomething()">Do something</ons-button>
    </p>

    <p style="text-align: center;">
      <input type="checkbox" ng-model="disabled">
    </p>
  </ons-page>

</body>
</html>
```

**Comment by Hirbod** [comment]
To be honest, just tried on the simulator.

I did something like this

```html
<ons-button ng-click="myFunction()" var="myButton" disabled="true">Button</ons-button>
```

```javascript
if(condition) {
   myButton.setDisabled(false);
}
```

The disabled styles gets removed but when I click/touch the button, nothing happens. Seems to be some focus problem, cause when I touch around a bit, it works (sometimes) - could not reproduce this 100%

**Comment by argelius** [comment]
This is very strange. I'm unable to reproduce this behavior in the simulator.

**Comment by Hirbod** [comment]
By the way. It was a button in the toolbar (maybe this produce the problem?)
