### ISSUE TITLE
Scrolling with angular-scroll not working

### ISSUE THREAD

**Issue by paulhovey** [OnsenUI/OnsenUI#396]
Hi there -

Want to preface by saying I'm liking Onsen so far and appreciate all the work put into it!

I'm having trouble with scrolling.  I've tried every way I can think of, but it seems to be that Onsen is breaking something with the $document element from what I can find so far.  I've made two jsfiddles to demonstrate:

Onsen:  http://jsfiddle.net/tjte6cr9/1/
Without Onsen:  http://jsfiddle.net/w1Lymhha/1/

The one without Onsen elements scrolls to the last element correctly, and the log shows that $document.scrollTop() gets updated as it should.  With Onsen, however, $document.scrollTop() is always 0 and never updated.  Any help with this issue would be appreciated.  Thanks!

**Comment by michaeleparkour** [comment]
It is becouse in Onsen scroll element is not document or body - .page__content has overflow: scroll. So you need to track this element and better to keep scrolling elements in some position: fixed container.

**Comment by paulhovey** [comment]
Thank you for the tip!  I didn't find any documentation about the .page__content .

I updated the jsfiddle with working code for reference:  http://jsfiddle.net/tjte6cr9/2/

**Comment by paulhovey** [comment]
One more update for those using ons-navigator like I am -

http://jsfiddle.net/tjte6cr9/3/

The key is to get the nested .page__content, `var fixedList = angular.element(document.getElementsByClassName('page__content')[document.getElementsByClassName('page__content').length-1]);`
