### ISSUE TITLE
Globally Disable Animations

### ISSUE THREAD

**Issue by 0505gonzalez** [OnsenUI/OnsenUI#399]
This is a feature request to provide a way of disabling all animations in an application.

Use case: Automated ui tests. Runtime for these tests can be significantly cut down. Currently, we have to add sleeps in the tests to allow animations to complete.

**Comment by Hirbod** [comment]
You could write your own AnimationFactory for that.

**Comment by argelius** [comment]
We've had requests about this previously and I agree it would be a nice feature.

**Comment by frankdiox** [comment]
This was addressed in 657a5b753f8980b135d61eaa77edbe706f3c2498

**Comment by 0505gonzalez** [comment]
Was this addressed in release 1.3.2? I'm unable to get this working with the latest version (and don't see `animationDisabled` in ons config).

**Comment by frankdiox** [comment]
@0505gonzalez No, it's been added to 1.3.3-dev: https://github.com/OnsenUI/OnsenUI/blob/master/CHANGELOG.md
