### ISSUE TITLE
ons-toolbar-button should have same options as ons-button

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#400]
Hi,

im missing the features that ons-button has (like disabled="true").
ons-toolbar-button should inherit from ons-button.

**Comment by argelius** [comment]
I agree it should have the same features as `<ons-button>`.

**Comment by argelius** [comment]
`<ons-toolbar-button>` now supports `disabled` attribute as well as `ngDisabled` directive.
