### ISSUE TITLE
ons-carousel swiped right after popPage

### ISSUE THREAD

**Issue by frankdiox** [OnsenUI/OnsenUI#401]
In an swipe list using 'ons-list' + 'ons-carousel':
When doing `myNavigator.pushPage('page.html')` and **opening the mobile keyboard** in this new page, if you go back to the first page using  `myNavigator.popPage()` the elements in the mentioned list are now all swiped right.

This is a minimun project to test it (developed with Monaca):
https://www.dropbox.com/s/pvifw4x38x6jh7x/OnsenUI-carousel-bug.zip?dl=0

**Comment by argelius** [comment]
Thanks @frankdiox ,

I'll check it out!

**Comment by argelius** [comment]
Opening the keyboard triggered a `resize` event while the carousel was hidden (no width), so there were some calculations that were incorrect so it always scrolled to the left-most position.
