### ISSUE TITLE
Support for native swiping between views

### ISSUE THREAD

**Issue by samelliott89** [OnsenUI/OnsenUI#402]

**Comment by argelius** [comment]
Could you please elaborate?

**Comment by Hirbod** [comment]
I guess he means swipe-left should popPage and swipe-right should bring the last view (at least swipe-right isn't possible with onsen, as popPage() will destory the last view

**Comment by argelius** [comment]
I see, that'd be a nice nice feature.

**Comment by Hirbod** [comment]
#243

**Comment by samelliott89** [comment]
Yep that's exactly what I mean 

—

**Comment by samelliott89** [comment]
Sam Elliott has invited you to Canva, so you can easily create and share your own designs.

Take a look by clicking the link below or copying it directly into your web browser

https://www.canva.com/signup?reservationToken=XyYGEEx_Ut3EurHC3UhSYFqYxq7j0Xr32kboxtv4ZrjZ5bZpL2TjjJELCIRGlp6JKN3Nn1ODNQlTJa-ZZbvUd4amHAY09bGXL7nlI5mYhDE25W134j4mbNE8z9sA4MqPxqQ-lGDiYujXY2m00Ze7vVf3X9kbufeTAK4B_qSvoRxa_Iljv5BszP2tkGlcRKnjxMCPPJMrk8d7B6ZQC5NSH2QOSKc&utm_source=canva-server&utm_medium=email&utm_campaign=server_201411&utm_content=invite-social

You’re receiving this email because samelliottsam@hotmail.com asked us to send you an invitation to Canva. If you'd like to know more about what Canva is you should visit canva.com
