### ISSUE TITLE
コントローラーのインスタンスが何回も作成されてしまう

### ISSUE THREAD

**Issue by senju** [OnsenUI/OnsenUI#403]
ページXとYで
`<ons-page ng-controller="MainController" `
のように同じコントローラーを使用する場合、
XからYにpushPage()で遷移したタイミングでサイドMainControllerのインスタンス化が行われてしまうようです。
このため、ページYで$scopeのモデルを操作し、XにpopPage()で戻っても、変更結果が反映されていません。(違うインスタンスなので。)

anglarもonsen uiも初心者なので仕様なのかバグなのか分かりかねますが、少なくとも私の期待した動作と違いました。

Y画面はXの子画面で、完全に別の画面というわけではないので、可能ならば同じコントローラーを使用したいです。スマホは画面が狭いので、単純な項目選択ですら、セレクトボックスではなく子画面に分割というのは発生しますし、その度にサービスを作成するというのは効率が悪いです。

優先度は低いと思いますが、他の変更のついてでにでも、対応をお願いします。

**Comment by argelius** [comment]
Hello,

What about using `ng-controller` on the `<ons-navigator>` tag?

<ons-navigator ng-controller"MainController">
</ons-navigator>

If you do that the model will be shared among the navigator pages.

@senju　さん

`<ons-navigator>`に`ng-controller="MainController"`を付ければいかがでしょうか？そうすると、ナビゲーターのページは同じモデルを共有できます。

下手な日本語で申し訳ありません。

**Comment by senju** [comment]
Thank you for your advice. 
I tried it and delete ng-controller attribute at <ons-page> on sub page, it works.

Sorry for bad English.
Thank you.

**Comment by argelius** [comment]
No problem. Glad you solved it :)
