### ISSUE TITLE
New page-click-close-menu function breaks everything

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#404]
Hi @argelius 

I know this new feature isn't out yet, but still, it's marked as fixed / done - and this is why I want to tell you that it's not. More details in issue #319 

http://youtu.be/HXOa7FFd_1U

**Comment by argelius** [comment]
Thanks!

I reopened the other issue so I'll close this one. I'll do some extensive testing of this so the behavior is as expected.
