### ISSUE TITLE
Too small on my Android Tablet

### ISSUE THREAD

**Issue by khoshrou** [OnsenUI/OnsenUI#405]
Hi
I again searched for this and I think no body mentioned this. I have used ONSENUI on ipad, iphone, android phone and my Asus MemoPad HD7 which is an android tablet. Its fine on all devices exept Android tablet. It seems every thing is a little bit small like list items, tabs, i am talking about onsen ui default components. I think they should be a liitle more bigger coz for example its hard to click on a list item or a tab item.

**Comment by argelius** [comment]
Thanks, @khoshrou !

We will try with some Android tablets and see how it can be improved.
