### ISSUE TITLE
The version of hammer.js included in onsenui.js

### ISSUE THREAD

**Issue by zhuangperola** [OnsenUI/OnsenUI#407]
onsenui v1.2.1 has use hammer v1.1.3 included.

when I want to be complex gesture, I prefer to use hammer v2.0.1.

Could onsenui team update the version of hammer included in onsenui.js. The version of hammer is too old.

**Comment by zhuangperola** [comment]
@argelius さん

お疲れ様です。

　　複雑なジェスチャを利用するために、onseui.jsと最新のhammer.jsを同時インクルードされて開発しています。

　　ons-carouselではswipeableを追加したのに、swipeできない障害が発生しました。同時hammer.jsの二つのバージョンをインクルードされるのは理由だと思います。

そして、onsenui.jsの中のhammer.jsのバージョンを更新してほしいです。

英語と日本語は第二言語と第三言語で、うまくなく、苦手だと思いますが、申し訳ございません。

**Comment by argelius** [comment]
@zhuangperola 

Thanks for the request. We've had some requests previously about upgrading to Hammer 2 and we'll do it in an upcoming version.

Unfortunately, the features for 1.2.2 are frozen right now, but we'll definitely try to add it for 1.2.3.

**Comment by zhuangperola** [comment]
@argelius 

Thank you for the information share about version upgrading.

 I am looking forward to using lastest hammer which is included in onsen.

**Comment by argelius** [comment]
No problem. Closing this since there already is an issue about this.
