### ISSUE TITLE
Failed to use ons-dialog/ons-alert-dialog to show list (ons-scroller)

### ISSUE THREAD

**Issue by zhuangperola** [OnsenUI/OnsenUI#409]
@argelius 

I am using ons-dialog to show a ons-list which does not work.

My source is like this.

`<ons-dialog class="dialog-mask" animation="none">`
`    <ons-toolbar inline modifier = "android">`
`    </ons-toolbar>`
`    <ons-list>`
`        <ons-scroller>`
`            <div>`
`                <ons-list-item>`
`                </ons-list-item>`
`            </div>`
`        </ons-scroller>`
`    </ons-list>`
`</ons-dialog>`

I changed the source of onsenui.js to fix this bug (I consider it is a bug)

in onsenui.js 14694 line has codes like so.

`transclude(scope.$parent, function(cloned) {`
`            wrapper.append(cloned);`
`           wrapper = null;`
`          });`

I change the `wrapper.append(cloned);` to `element.children().append(cloned);`

@argelius 

Could you have a check of this bug which confuses me such a long time?

**Comment by argelius** [comment]
Thanks @zhuangperola !

Actually I think this is the same as this issue:
https://github.com/OnsenUI/OnsenUI/issues/389

That bug has been fixed and in the next version it will work as expected so I'm closing this issue.

**Comment by zhuangperola** [comment]
@argelius 

I follow the commit and it works fine. Think you very much.

**Comment by argelius** [comment]
No problem. Glad it helped! :)
