### ISSUE TITLE
pushPage animation for sliding from right to left

### ISSUE THREAD

**Issue by khoshrou** [OnsenUI/OnsenUI#410]
Hi
Please add an animation for pushPage that slides from right to left (for RTL languages)

**Comment by argelius** [comment]
Thanks for reporting!

You can actually register animators for your navigator. There is a service called `NavigatorView`.

If you inject the service you can do:

```javascript
NavigatorView.registerTransitionAnimator('myAnimator', MyVeryOwnAnimator);
```

And to create your own animator you can do

```javascript
module.factory('MyVeryOwnAnimator', function(NavigatorTransitionAnimator) {
  var MyVeryOwnAnimator = NavigatorTransitionAnimator.extend({
    // write your animation code here.
  });

  return MyVeryOwnAnimator;
});
```

To do a RTL animator you could look at the following code and just change it so the animation is mirrored:
https://github.com/OnsenUI/OnsenUI/blob/master/framework/views/simpleSlideTransitionAnimator.js

**Comment by khoshrou** [comment]
Hi argelius
as always thanks for your help.

**Comment by Hirbod** [comment]
@khoshrou 

would you be so kind to publish your code when you've done that? :)

**Comment by khoshrou** [comment]
of course
