### ISSUE TITLE
Sliding Menu Bug

### ISSUE THREAD

**Issue by franckChev** [OnsenUI/OnsenUI#411]
Hi,

There is an important bug in the last version , when i  toggle the slide menu then i close the menu, no more clicks are working also the scrolling bar. 

Problem with Hammer maybe ?

Thanks

**Comment by franckChev** [comment]
Problem with Hammer maybe  ?

**Comment by argelius** [comment]
That sounds like a bug. Could you give an example that reproduces this behavior?

**Comment by franckChev** [comment]
Yes it's in the master branch, in the demo version for exemple, because of that i checkout my version waiting for new version, thanks !

**Comment by argelius** [comment]
Ok, I managed to break something when I added a feature to the sliding menu. If you go back a couple of commits or checkout the 1.2.1 tag it should work.

**Comment by franckChev** [comment]
Yes, so if somone has trouble with the master version, go back to the previous version. 

It's real pleasure to work with your framework thanks for everything !

**Comment by argelius** [comment]
Thank you! That's really nice to hear :)
