### ISSUE TITLE
Hybrid web app - browser back button does not influence OnsenUI routing

### ISSUE THREAD

**Issue by ConcurrentHashMap** [OnsenUI/OnsenUI#412]
Hi there,

I'm developing mobile (so called "hybrid") apps that should (at first) work in the mobile browser and then - if the user wants to - download the app and use it as this. As the Ionic framework seemed to have various bugs, I took more days to compare all the available mobile UI frameworks and decided to work with OnsenUI.

One thing, that I found very good on the one hand is your routing behavior with the navigator and push/pop. One thing that makes me cry on the other hand is the fact, that this routing isn't working in normal web and mobile browsers as there is no pushState change. So the back button of the browser stays disabled (on iOS) or will result in closing the tab in mobile Chrome for example.

Is there any working solution to make `navi.pushPage(...)` work to create a browser history and a history.back result in a `navi.popPage()`?

That's really a huge missing thing for Onsen! Does anyone have an idea how to implement this? Creating a history isn't a problem, as there is the `postpush` event, on which I can fire a `history.pushState(...)`. The bigger problem is the way back when the browser back button is clicked - as far as I know there is no native function or event to notice this. So maybe there is an Angular workaround for this?

**Comment by Hirbod** [comment]
Hi @ConcurrentHashMap,

your guess is correct. You need to trigger pushState / popState by yourself. Please do yourself a favor and don't write this by yourself. There are ton of plugins outhere with good support for all browsers and even old browsers with hash or hash-bang support (# and #!).

But you're wrong, there are native functions to listen for the backbutton. There is onstatechange or onanchorchange (polyfill for hashChanged listener).

You can do everything with: https://github.com/browserstate/history.js/

With a little effort you should not take longer then 1-2 hours!

**Comment by ConcurrentHashMap** [comment]
Hi,

thanks for your comment on that. I've had a quick look onto history.js before, but didn't notice there was this event. I've made it working now for me. Thanks for the inspiration.

**Comment by Hirbod** [comment]
:+1: 

glad I could help
