### ISSUE TITLE
Statusbar and bottom (AdMob) issues on IOS

### ISSUE THREAD

**Issue by bheijns** [OnsenUI/OnsenUI#414]
Hi!

Yesterday we launched our app within the Google Play store after some big tests. The app works very well and fast thanks to Onsen UI and Phonegap (Build).

As of today (or ASAP) we want to submit the app to the Apple App Store. Thing is we ran into some problems:

![image1](https://cloud.githubusercontent.com/assets/878651/5957679/c3d35b9a-a7bc-11e4-9301-04b03238cf2e.PNG)

At starting the app this is the login screen (ons-caroussel). As you can see at the bottom: The bottom bar is not totally visible. Conclusion: Probably there is something wrong with calculating the height of the statusbar. Currently we have the following specific lines in our config.xml:

```
<preference name="StatusBarOverlaysWebView" value="true" />
<preference name="StatusBarBackgroundColor" value="#000000"/>
<preference name="StatusBarStyle" value="lightcontent" />
<preference name="DisallowOverscroll" value="true" />
```

Besides we have the Cordova Statusbar plugin:

```
<gap:plugin name="org.apache.cordova.statusbar" version="0.1.4" />
```

The other issue we have is the following:

When opening a specific location page:
![image3](https://cloud.githubusercontent.com/assets/878651/5957729/433ea65a-a7bd-11e4-97fb-f956f5ddb10c.PNG)

After the page is loaded:
![image4](https://cloud.githubusercontent.com/assets/878651/5957730/46054d30-a7bd-11e4-8c41-7f5af46b6f91.PNG)

As you can see the bottom bar becomes invisible. Only after some scrolling I can get it visible again.

Besides; the logo on top is also not as it should be.

I guess all this problems can be solved by correcting the statusbar usage en maybe some other IOS preferences. But; which ones? As said; On Android (Lollipop and Kitkat) this works just fine.

NB. We use the AdMob Pro Plugin for getting and showing our ads. (https://github.com/floatinghotpot/cordova-admob-pro)

<b>Thanks in advance for helping!</b>

**Comment by argelius** [comment]
Hello @bheijns !

Looks like the logo should be pushed 20px (height of the status bar) down on iOS 7 and iOS8. Onsen UI does this by default but maybe there's some conflict.

Unfortunately I don't know about the ads on the bottom. Do they just cover the WebView at the bottom? In that case I guess you could use "margin-bottom: {AD_HEIGHT}px" and push up the tabbar.

**Comment by bheijns** [comment]
Hi @argelius !

Thank you for your fast reply!!
I investigated this problem furthermore after creating this incident (I think you know the 'deal') and I guess your right with the conflict.
The DIV tho 'logo' (which is plain text) had a padding top of -15px and we never taught about the fact that Onsen UI has integrated functionality for this. So I removed the padding top value.

I guess the problem will be definitely solved by tweaking the components.css a bit:
.navigation-bar__item,
.navigation-bar__left,
.navigation-bar__right,
.navigation-bar__center {
 -webkit-box-sizing: border-box;
 -moz-box-sizing: border-box;
 box-sizing: border-box;
 -webkit-background-clip: padding-box;
 background-clip: padding-box;
 padding: 0;
 margin: 0;
 font: inherit;
 color: inherit;
 background: transparent;
 border: none;
 line-height: normal;
 height: 44px;
 vertical-align: top;
 overflow: visible;
 display: block;
 vertical-align: middle;
 float: left;
}

Where I you can see there is a duplicate for 'vertical align'. I will play around with this but I guess we did not adjust this by ourselves so it's from the Onsen UI core and thus it's a bug (I believe).


For the AdMob problem:
I guess your solution will work (document.body.style.padding/margin Bottom: -50px;) and we tried and tested this but it doesn't work smooth and at the way we want it.

We will change our ads to the system of 'Leadbolt' (can I name this here?) from which you can include the ads inline by javascript. Since AdMob works outside the webview more incidents are expected in the future so we don't want to take this risk.

<b>Again, thank you for your answers.</b>

**Comment by bheijns** [comment]
Problem with the AdMob ads is still going on...

When I try to modify margin bottom of the page or specific onsen elements (such like the ons-tabbar) it actually looks great. Till I scroll down; the margin space on the bottom is shown (in our case a black bar).

Does anybody know how to fix this?

Thanks in advance.
