### ISSUE TITLE
<ons-popover> cannot work well with ng-repeat

### ISSUE THREAD

**Issue by bristolfairy** [OnsenUI/OnsenUI#416]
When I use ng-repeat in popover,the position of popover is not correct,It seems that the positon of popover does not refresh with the change of DOM tree.How can I fix this problem?

**Comment by argelius** [comment]
Thanks for reporting @bristolfairy !

Looks like we need to recalculate position for DOM tree changes.

**Comment by argelius** [comment]
Popover will now listen for DOM tree changes.
