### ISSUE TITLE
Fix for autoComplete plugins / google places plugins / ngAutocomplete

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#420]
Hi everybody,

if anybody ever stuck on "ngAutocomplete" or even the native autocomplete provided by google, it won't work inside of OnsenUI (searching yes, but tapping on the result not). This error is caused trough "FastClick" implemented into Onsen.

This is the global fix for this (and every other lib which stuck on some click/tab) problem (in this case you need to set the right selectors. The selector below will only work for places... as long as they won't change their markup.) 

``` JS
        // this workaround is needed because of "fastclick"
        $(document).on({
            'DOMNodeInserted': function () {
                $('.pac-item, .pac-item span', this).addClass('needsclick');
            }
        }, '.pac-container');
        // end google maps places autocomplete workaround
```

**Comment by eecsxielu** [comment]
Excellent! Seems like you have already asked or resolved many of my questions. We should be developing apps with very similar functionalities...

**Comment by Hirbod** [comment]
:) :+1: 

I've learned a lot since september. Thought I will finish after 1-1,5 monts, but as you can see, I was totally wrong :D. But yes, maybe we should :)
