### ISSUE TITLE
Overscroll bounce issue

### ISSUE THREAD

**Issue by eecsxielu** [OnsenUI/OnsenUI#421]
Hi,

Does anyone have an idea how to make page bounce vertically even if the content does not exceed the screen boundary?

I have a page that contains a list of objects. When the list length is small and the list does not cover the full screen, the page cannot bounce on overscroll. However, if the list is long enough and exceed the visible area, the page can bounce when you scroll over the top or scroll over the bottom. I don't think this is a good user experience.

I guess this also has something to do with pull to refresh and infinite scroll...

Thanks!

**Comment by Hirbod** [comment]
Ha... @eecsxielu 

you should have asked me before. I did face the same problem sometimes. Just used a ```<ons-scroller class="something>``` and set the height of ```.something```inside of my controller to ```window.height - ons-toolbar-height```(and - tabbar when you have one)

**Comment by Hirbod** [comment]
// edited

**Comment by eecsxielu** [comment]
Thank you @Hirbod. I tried your method but if the content in ons-scroller is not long enough, the scroller does not bounce on overscroll either. Did I miss anything?

**Comment by Hirbod** [comment]
Hi,

height: 101% will do the trick.

**Comment by eecsxielu** [comment]
True, though not so elegant... Thank you!

**Comment by Hirbod** [comment]
But actually I don't know how to manage this without that sort of "hack".
You can just set the whole webview overscroll inside the plist - but who wants this.
I guess the only method is mine - or a bigger innerContainer.
