### ISSUE TITLE
ons-modal shouldn't propagate scroll to background

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#422]
Hi @argelius,

ons-modal propagate scroll/touch to background and it is not possible to add a scrollable content inside of it. Tried with ons-scroller and some own elements/styling - no chance.

**Comment by argelius** [comment]
Thanks @Hirbod ,

We'll look at this. It shouldn't be possible to touch elements behind the modal so it sounds like a bug.

**Comment by eecsxielu** [comment]
Hi @argelius, same thing for ons.notification.alert. Currently you can scroll your background content when a notification is shown.

**Comment by argelius** [comment]
Actually I'm unable to scroll background both when using `ons-modal` and `ons.notification`. Is this for a specific device or do you always get this behavior?

**Comment by Hirbod** [comment]
Had the bug on iOS 8 (device) + simulator

**Comment by Hirbod** [comment]
Just to give some more informations:

Hade the ```<ons-modal>```directly after ```<ons-page>```and activated after a ng-click

**Comment by argelius** [comment]
Thanks, actually tried in Android. Will try iOS as well.

iOS  simulator takes  so long to boot :)

**Comment by Hirbod** [comment]
What? :D
iOS Simulator is up in 10 seconds, Android takes (even with Intel Hax) over 3 minutes (on my 3,7 Quad Core MacBook Pro Retina with SSD and 24GB RAM)

**Comment by argelius** [comment]
Managed to reproduce it on iOS. Thanks!

Yeah, Android emulator is even slower. I have a Mac Mini so it takes more than one minute to start the iOS simulator while Android sim takes 5 minutes. ><

**Comment by Hirbod** [comment]
Ok :D 
:+1: 
Glad you found the bug.

**Comment by argelius** [comment]
Scrolling content inside modal seems to work fine on all devices I tried. Both using `<ons-scroller>` and a normal block element. What kind of content did you put in the scroller?

Scrolling the background is a bug though so we'll fix that.

**Comment by argelius** [comment]
Fixed for sliding menu and modal. Dialog and alert dialog will require some refactoring.
