### ISSUE TITLE
Bower file improvement

### ISSUE THREAD

**Issue by hyyan** [OnsenUI/OnsenUI#424]
Hi , thanks for the great work

I have been using onsenui framework for a while now and I found it very difficult to integrated  to other build tool like brunch build tool for example. and this because the OnsenUI file does not declare all its dependency like ``font-awesome , angular-animate, ... , ionic icons`  in its bower file . plus the main style file `onsenui.css` declare an import for font-awesome and ionic icons files which I might not use at all .

Any idea ?

**Comment by argelius** [comment]
Thanks @hyyan ,

We will consider this. It will probably not be resolved in the next version but we will definitely look at it in an upcoming version.

**Comment by hyyan** [comment]
@argelius It is OK , it does not matter when , but it is important to mention that , Thanks for replay
