### ISSUE TITLE
More Direcrives

### ISSUE THREAD

**Issue by hyyan** [OnsenUI/OnsenUI#426]
It would be just great if new helpful directive could be included ?

Some idea about new dirctives ?
*  close-menu
* push-page
* pop-page

I mean implementing this directives is pretty easy and I am ready to send PR if this idea is good

**Comment by argelius** [comment]
Do you mean to handle events? 

Like this:

```html
<ons-navigator pop-page="doSomething()">
</ons-navigator>
```

**Comment by hyyan** [comment]
@argelius  No execaly like that , let me explains this more .

Imagine that we want to use the sliding menu pattern with navigator pattern and I want to make each menu item responsible of closing the menu and pushing another page to navigator 

something like that : 
```
<ons-list class="menu-list">
    <ons-list-item ng-click="nav.pushPage('templates/posts.html',{/*options*/});menu.toggle({/*options*/})">
      <ons-icon icon="fa-coffee"></ons-icon>
          Posts
    </ons-list-item>
</ons-list>
````

Would it be better if we used like this :  

```
<ons-list class="menu-list">
    <ons-list-item close-menu push-page="templates/posts.html">
      <ons-icon icon="fa-coffee"></ons-icon>
          Posts
    </ons-list-item>
</ons-list>

```

I am not trying to compare here , cause every framework has its own spririt but (Ionic Framework[http://ionicframework.com/docs/api/directive/menuClose/] has something similar

I mean this what one expects when he use a a framework with angular support ? Am I write here or I am missing something?

**Comment by argelius** [comment]
Oh, I see. 

I agree that this would be quite nice. We'll consider implementing this. :+1:

**Comment by hyyan** [comment]
@argelius Great , I can not wait untill I see this feature In OnsenUI :+1:  , Thanks for replay

**Comment by Hirbod** [comment]
:+1: 

Would also make code more readable and cleaner - too many ng-clicks just to push a page..
