### ISSUE TITLE
Google Material Design

### ISSUE THREAD

**Issue by ram-you** [OnsenUI/OnsenUI#427]
Is there a chance to integrate Google Material Design in Onsen UI. It could be a huge benefit for all apps in android.

There is already some web implementations with Polymer : 
https://www.polymer-project.org/docs/elements/material.html

Thanks for your answer

**Comment by argelius** [comment]
Hi @ram-you !

Thanks for the suggestion. Actually we discussed this recently and will probably implement a subset of the material design spec.

There is already an issue about this so I'm closing this one.

**Comment by DILEEP-YADAV** [comment]
I love to work with OnsenUI. I am request to asial corporation Developer team That We have to one step ahead about Google Material Design with onsen ui. all most UI Framework started work on Materiel UI. That is very popular India and across World. Thanks
