### ISSUE TITLE
Virtual Lists

### ISSUE THREAD

**Issue by Wouter33** [OnsenUI/OnsenUI#430]
It would be nice to have virtual lists for long lists. Currently i have an app with a few lists of thousands of list items. They are all loaded into the DOM. It would be great if only the items in the view (and some buffer items) are loaded into the DOM and more on scrolling. Framework 7 (http://www.idangero.us/framework7/) has a nice implementation of this.

**Comment by argelius** [comment]
Hi @Wouter33 !

Thanks for the suggestion. 
Actually we've just implemented this so it will be available in the next version.
It will only load a handful of items into the DOM at a time. 

I believe there's already an issue about this so I'm closing this.

**Comment by Wouter33** [comment]
That's great! Which commit is it? Any ETA on 1.2.2, roughly?

**Comment by argelius** [comment]
@Wouter33 We have not decided on a date yet but I believe it will take between one and two weeks from today.

We have to test on several devices before releases so it takes some time.

**Comment by argelius** [comment]
@Wouter33 It's on this branch: https://github.com/OnsenUI/OnsenUI/tree/lazy-repeat

It's not merged yet so there might be some bugs. Also, there's an issue with iOS where it won't render until the intertial scroll has come to a complete stop, so even if the elements are added to the DOM it takes some time for them to show up.

**Comment by Wouter33** [comment]
@argelius Thanks, i'll play a bit with it.

Framework 7 found a way to implement it working on iOs: http://www.idangero.us/framework7/docs/virtual-list.html#.VNR7FlXF-Ig

A solution they are bringing up here is to disable native scrolling and simulate it: http://stackoverflow.com/questions/10482227/javascript-dom-changes-in-touchmove-delayed-until-scroll-ends-on-mobile-safari

**Comment by Wouter33** [comment]
@argelius The lazy-list works fine on my iPhone 6. Even if i scroll really fast it keeps up with new items.

Any idea how i can combine this with list headers in an alphabetized list? It will cause problems with calculating the heights.

**Comment by argelius** [comment]
Thanks for trying it. :)

Great that it's working well. Please report if you have any issues.

One way to solve your problem is to use `<ons-list-item>` for the headers as well but add some class to them so you can style them.

I'll try to think of a nicer way.
