### ISSUE TITLE
Tap navigation bar to scroll to top

### ISSUE THREAD

**Issue by Wouter33** [OnsenUI/OnsenUI#431]
It would be nice to have an option to enable scrolling to the top of the content when tapping on the navigation bar / status bar just like in iOS.

**Comment by argelius** [comment]
Thanks @Wouter33 !

That sounds like a nice feature. We'll consider adding it.

In the meanwhile if you want that behavior you can easily implement it yourself. I made a small example:
http://codepen.io/argelius/pen/zxPowB

**Comment by Wouter33** [comment]
Thanks for your snippet! I'll use that for now, but in general it would be nice to have this globally available in Onsen.

**Comment by Hirbod** [comment]
Actually, native would be scrollToTop when touching the clock, not the toolbar.
As Onsen determines the native statusbar by itself and also provide a spacer for it, a spacer tap should scroll-to-top.

**Comment by Wouter33** [comment]
You are right! @argelius it would be perfect if you could combine it with this plugin: http://www.tricedesigns.com/2013/10/08/status-tapscroll-to-top-in-phonegap-apps-on-ios/

**Comment by Hirbod** [comment]
Just to mention @Wouter33,

I know the plugin statusTap and it does not work with iOS8

**Comment by Wouter33** [comment]
@Hirbod @argelius The "statusTap" event of org.apache.cordova.statusbar seems to work fine for iOS8 as found in: http://forum.ionicframework.com/t/touch-top-of-ios-status-bar-to-scroll-back-to-top/5647/4 

Tested it myself and the event works. Together with @argelius his snippet i created a global method for this. The only problem is that when a list is being scrolled and the statusbar is tapped when the scrolling isn't yet finished, it finishes after the scroll to top is completed, causing the list not to be scrolled to the top. 

Any idea if i can "cancel" the current scroll in some way?

**Comment by eecsxielu** [comment]
@Wouter33 Same problem here.

**Comment by Ralpharoo** [comment]
@Wouter33 @eecsxielu Same problem here. You guys ever work this one out?

I've tried the jQuery .stop() method but it still flickers / seems glitchy

**Comment by Hirbod** [comment]
To everybody: it has finally landed officially to the status bar plugin 

https://github.com/apache/cordova-plugin-statusbar/blob/master/README.md

StatusBarDefaultScrollTop

**Comment by Hirbod** [comment]
@argelius this can be closed

**Comment by masahirotanaka** [comment]
Thanks @Hirbod! We'll put somewhere about this in the doc.
