### ISSUE TITLE
ons-toolbar - documentation and feature request

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#433]
Hi @argelius ,
http://onsen.io/guide/components.html#ons-toolbar documentation is missing to tell the available modifiers. And there is something more. I'd like to have a reversed "fixed-style" attribute, to force iOS to look like android.

Cause in my community app, I'll have some long titles and sometimes it is important to align the text left. On iOS (see Facebook app) - this is also something normal. Currently, I'm fixed with 46% width and centered. 

My real world recommendation:
1) Provide reversed fixed-style directive for ons-toolbar
2) Provide an option "dynamic width" (left aligned with max-width 80-90%?) for long titles. Maybe with ellepsis overflowing (optional, also as modifier)
That would be awesome.

Thanks

**Comment by argelius** [comment]
Thanks @Hirbod,

There has been some confusion about the text alignment of the toolbar title. We'll improve this to make it more intuitive.

Btw, I believe you can `add modifier="android"` to get left-aligned titles in the current version.
