### ISSUE TITLE
Web link problem

### ISSUE THREAD

**Issue by mahedicse** [OnsenUI/OnsenUI#434]
I have a problem on web link  in my apps. If use a link used <a herf=" "> </a> in a page after clicking it's appeared a large screen and works fine but device back doesn't work and there is not any option without prevent this used device home button. if stop used coordova.js it's fine but device back button not work on child page just the apps.

**Comment by argelius** [comment]
Could you clarify and give a code example?

It sounds like you're having trouble with Cordova rather than Onsen UI.
