### ISSUE TITLE
Android sliding animation slow

### ISSUE THREAD

**Issue by JcDenton86** [OnsenUI/OnsenUI#436]
Hi, I am having a sliding menu which set a page depending on users' selection. In these pages i use ons-navigator to create relationship with child pages using push and pop with slide animation. I' ve noticed that the sliding animation between pages (mostly on pushPage) is slow (lags) on my android device (nexus 5). The same issue does not happens on iOS. 

Thanks in advance.

**Comment by argelius** [comment]
Thanks @JcDenton86 !

Is it lagging if you use Crosswalk as your WebView?

**Comment by JcDenton86** [comment]
Hi @argelius thanks for your reply, 
I am not using crosswalk on the Android version.

**Comment by argelius** [comment]
Ok, 

Is the DOM on the page you're pushing very large? Can you estimate how many items are being animated?

If the DOM on the animated page is very complex it might be possible to display some of the elements after the animation has been finished.

**Comment by JcDenton86** [comment]
Imagine this, one of my pages holds a listview with at least 60 items. Selecting that page from the menu page is ok. That page has a navigator and selecting an item from the list pushes the child page with option values (title, image and description). This information is rendered to the child page which is similar to the 'shop details' page (http://components.onsen.io/patterns). I don't think that the DOM is large, however you think that I should put a timeout for a few milliseconds in order to perform the animation and then show the information passed?

**Comment by argelius** [comment]
I don't think passing the object would be a problem. The DOM doesn't seem to be large either. The image could be the problem. Is the animation still slow if you skip the hirez image? 

Maybe you can load that a bit later. Actually you don't need a timeout, you can listen for the postpush/postpop events:

```javascript
$scope.navi.on('postpush', function() {
  // Do something cool here.
});
```

**Comment by JcDenton86** [comment]
Trying with timeout indeed made it work better. Trying it with 'postpush' event, the image doesn't get rendered on the child page maybe because angular is not notified about the change on the $scope variable? while on $timeout it does.

**Comment by JcDenton86** [comment]
Ok, calling $scope.$apply() on postpush showed the image. Maybe this should be done automatically from Onsen. Either way thank you @argelius.

**Comment by argelius** [comment]
Thanks,

Yeah. The event handler will not start a new $digest cycle. Maybe we can change it so that the digest cycle is started automatically after the callbacks are executed.

**Comment by JcDenton86** [comment]
@argelius I would like to share this because it might help others. Even the fixes provided above made the animations run smoother, still there were a few lags. Building the application using Intel XDK (https://software.intel.com/en-us/html5/tools) made it run even better and more smooth.

**Comment by argelius** [comment]
Great! But this is Crosswalk, right?

**Comment by JcDenton86** [comment]
It gives you options and yes one of them is Crosswalk but i didn't built it using that option. I selected just Android. I don't know if they build it differently (because the size was reduced to 4 MB). Today I used that tool just from curiosity. I will check it more.
