### ISSUE TITLE
Style problems when using an user-agent-faker

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#437]
Hi @argelius,

as android and (jailbroken) iPhones can install a global user-agent-faker, (and browsers of course) there are some ugly problems (as you rely on browser sniffing methods) with the toolbar. The spacer won't be initied when faking a browser and even a few other bugs with the layout.

Relying on browser names is something really bad - instead, you should do feature-detection like Modernizr does, to prevent problems like this.

**Comment by argelius** [comment]
Thanks @Hirbod,

I'll change the iOS version detection. It can be done without user agent.
I think we can detect Android without user agent as well.
