### ISSUE TITLE
<ons-sliding-menu> helper functions not firing when swiped

### ISSUE THREAD

**Issue by DirtyRed5789** [OnsenUI/OnsenUI#438]
angular clicks, JS clicks, and programmatically, all the helper functions work properly:

$scope.sidemenu.on('postclose', function(){ });
$scope.sidemenu.on('preopen', function(){ });
etc...

but swipe events fail to fire any of the events. Even adding a watcher with isMenuOpened() doesnt work.

$scope.$watch(function($scope) { return $scope.sidemenu.isMenuOpened(); }, function() { alert('hi'); });

AGAIN - when attaching to a click or even programmatically, the functions work great - so AngularJS is working properly and listening to the variables and binding everything great, the only problem is SWIPING the side menu open or closed.

**Comment by hyyan** [comment]
Hey @DirtyRed5789  , you have to enable the swipe option like this  :

```
      <ons-sliding-menu
        menu-page="templates/menu.html"
        main-page="navigator.html"
        side="right"
        var="menu"
        type="push"
        max-slide-distance="260px"
        swipable="true">
      </ons-sliding-menu>
```

**Comment by DirtyRed5789** [comment]
i have it swiping already, otherwise how would i know that the helper functions do not fire?

**Comment by hyyan** [comment]
@DirtyRed5789 I have just tried this code in a menu and the event is fired with no errors :

```
      <script>
      ons.ready(function() {
        menu.on('preopen', function() {
          console.log("Menu page is going to open");
        });
      });
      </script>
```

Could please share a little of your code to see what is going one

**Comment by DirtyRed5789** [comment]
are you swiping it or attacking it to a button or click? swipe the menu open or closed.... and see if your console logs your message....

**Comment by hyyan** [comment]
@dotrikun I am swiping of course , I just working perfectly

**Comment by hyyan** [comment]
@DirtyRed5789 I could recommend one thing here try to use the menu variable name directly without assiging it to angular $scope .

for example if your menu name is `SlideMenu` use this name directly and don't use `$scope.sidemenu= SlideMenu` or something simmilar

**Comment by DirtyRed5789** [comment]
got it - needed to tell angular that variable were changing with $scope.$apply() 

thanks for the quick help

**Comment by hyyan** [comment]
@DirtyRed5789  You are more than welcome , glade I could help in this :smile:
