### ISSUE TITLE
Lazy repeat ordering 

### ISSUE THREAD

**Issue by JcDenton86** [OnsenUI/OnsenUI#441]
Hi,
ons-lazy-repeat is a great feature of the upcoming version(1.2.2). I already tried it on my app. 

Before that i was making use of the traditional ng-repeat method and I was able to order my list by title and/or category depending on two button and what user selects. Will that be possible somehow if I replace it with ons-lazy-repeat? There should be a way of achieving the same behavior.

**Comment by argelius** [comment]
It doesn't support the normal `ngRepeat` syntax with filters, but you should be able to achieve sorting by writing a delegate object that supports it.

**Comment by JcDenton86** [comment]
Thanks for your reply,
I am able to sort my list with objects by a specific property. My problem is that the sorted list doesn't get updated in the view. While using $filter and orderBy the view updated when tapping on the button.

You are welcome

**Comment by argelius** [comment]
I see,

Actually I just made a change so it will re-render the list on every $digest loop. Maybe it works better now.

Please see this example:
http://codepen.io/argelius/pen/radBRB

Of course if the list is super big it might be a bit slow but if the list is not too big you should be able to sort it in JavaScript.

**Comment by JcDenton86** [comment]
Wrapping my sorting code in a $watch updated the view, but only for the elements that hadn't been rendered yet or have been destroyed previously, which is normal because this is how lazy loading of content works. What I mean is that when I select to sort the list, the items that are in the view at the moment are not updated, while when I start scrolling the items that are getting in the view are sorted. When I scroll back the items that have not been updated previously, are sorted too (because they have been destroyed once they got out of view).

**Comment by JcDenton86** [comment]
Any way I replaced the code with the previous version. My list has at most 200 items (each item has image, title & description - is a bit heavy), so loading part of the list (just a few items) and load more (with lazy loading images) as the user scrolls has better performance than lazy loading the whole list. Any better approach or advice is welcome :)

**Comment by salztorte** [comment]
i use the Array.sort from JavaScript before fill the LazyRepeat

**Comment by aniketnt** [comment]
hi how to use json array with lazy repeat the url they are calling with is only for 1 array at a time on random but i the json array return from the url with the 1000 of record how they will get iterate and fast
