### ISSUE TITLE
ons-carousel-item visibility

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#443]
Dear @argelius,

do you have any clue, why my ons-carousel-item has visibility:hidden and will stay hidden?

```
      <ons-carousel class="fb-friends" style="height: 70px" swipeable overscrollable auto-scroll item-width="70px">
        <ons-carousel-item ng-repeat="friend in facebookFriends">
        <div>
          <img class="animation-fade" ng-src="https://graph.facebook.com/{{friend.id}}/picture?width=200" data-imageloaded data-loadedclass="animation-faded">

        </div>
        </ons-carousel-item>
      </ons-carousel>
```

![bildschirmfoto 2015-02-12 um 03 25 06](https://cloud.githubusercontent.com/assets/504909/6160692/c80f2748-b266-11e4-8565-18858bf7b779.png)

**Comment by Hirbod** [comment]
Seems like it does not get inited...

**Comment by argelius** [comment]
Are you using the dev version of Onsen UI?

Please try adding the attribute `auto-refresh` to your carousel.

**Comment by Hirbod** [comment]
I'm using the last version where you fixed the sliding menu issues

**Comment by Hirbod** [comment]
Hi @argelius ,

thanks, auto-refresh fixed it. Actually I don't know why this is import (imho this should be done automatically) but at least for now, this fixed my problems :)

Thanks as always!

:+1:

**Comment by argelius** [comment]
Great!

We'll make some tests. If it's not too performance demanding we might put it on by default.

**Comment by Hirbod** [comment]
There is also something I really don't like: specifiying item-width.
I've already specified in the css... You should be able to get the right values out of css / computed styles.

**Comment by Hirbod** [comment]
And I can't understand, why the elements why ons-carousel-item get's position absolute. This makes it impossible for the use of display: inline-block;

And when I do it like in your demo (display: table), as soon as I swipe, the whole slideshow get's centered. Just look at your own demo folder (example 3)

**Comment by Hirbod** [comment]
and item-width should also understand integer values (50) and not only "50px"
sorry for spam, just writing down everything that seems messy to me

**Comment by Hirbod** [comment]
can't specify margin-right or margin-left due to position absolute on ons-item

![bildschirmfoto 2015-02-12 um 12 36 47](https://cloud.githubusercontent.com/assets/504909/6166790/d5b40f10-b2b3-11e4-8b68-adaa4eedf1fd.png)

**Comment by Hirbod** [comment]
@argelius 
after hours of trial and error I've managed to get this work with a lot of tricks and hacks (making item-width larger as it should be and just making the image smaller to get a "workaround" for that non-working margin)

But there are still bugs and actually, the carousel is far away from beeing table. Just managed to get this work right with the "noslidingmenu" directive hack also.. before, nothing happened as I had disabled sliding menu in "page"

But when there are few elements, the carousel will always ( and also in your demo) be right aligened after swipe-right) (guess this has something to do with overscrollable)

https://www.youtube.com/watch?v=U9pQSMokUi0

**Comment by Hirbod** [comment]
@argelius 

and I cant scroll vertical... the carousel blocks it. Damn :D
Should have stick with slick-slider ;D

**Comment by argelius** [comment]
Thanks @Hirbod,

I'll try to address these points next week. 
Of course, you're always welcome to make a pull request :)

**Comment by argelius** [comment]
Thanks for all the testing @Hirbod,

Issue with small carousel has been fixed in:
https://github.com/OnsenUI/OnsenUI/commit/c1b5ecd1ce99b0bcf0d9e131e6ff0842deff9323

There was a bug where it wrapped around when the total width of all the items was smaller than the width of the carousel container.

**Comment by Hirbod** [comment]
I can confirmed that the "small carousel" issue has been fixed.
