### ISSUE TITLE
Including HTML Templates in Single HTML

### ISSUE THREAD

**Issue by samaphp** [OnsenUI/OnsenUI#447]
I don't know if this will be enhancement feature or is already there because I'm looking to include another HTML template inside my template so I can get clean code, and I've read the guide in ons-template it's just to define HTML template without file!
My case that I need to include HTML file in my template, and also if this template has controller it should be working also.

I've read the "Defining Multiple Pages in Single HTML" in overview page:
http://onsen.io/guide/overview.html#DefiningMultiplePagesinSingleHTML
I also tried ng-include but nothing from these help me.

So please can you help me guys if this is possible by ons tags? or it will be a (feature request) in the future OnSenUI releases?

Many Thanks

**Comment by argelius** [comment]
You can use `ngInclude`, since Onsen UI is built on top of AngularJS all Angular features are available:

https://docs.angularjs.org/api/ng/directive/ngInclude

**Comment by samaphp** [comment]
Hello @argelius Thanks for your time.

I already tried the `ngInclude` like this:
`<ng-include src="home-NearBy.html"></ng-include>`
and also like this:
`<div ng-include="home-NearBy.html"></div>`

but it's not working :(
I'm just wondering to know the OnSenUI way.

Your time is highly appreciated.
Many Thanks.

**Comment by argelius** [comment]
In what way doesn't it work? Is the HTML not included at all?

**Comment by samaphp** [comment]
Thank you @argelius 
Yes the HTML not included at all.

I'm trying to perform this issue on codepen:
http://codepen.io/samaphp/pen/bNLOYw

But I don't know if this is the best perform or the template should be on real separate file, but in my machine it's on separate files.

Your time is really appreciated.
Thanks,

**Comment by argelius** [comment]
Oh, you should do

```html
<div ng-include="'main.html'"></div>
```

It's an Anglular expression, so it will be evaluated.

**Comment by samaphp** [comment]
@argelius I love you :heart: .. You're a lifesaver!

At first .. all my page disappear after I did what you said .. but it works after I remove this tag:
`<ons-page>`
from the included template!

Thank you very much again for your time, and I'm so sorry because this problem is not related to onsenui.
Thanks Thanks Thanks :heart:
