### ISSUE TITLE
ng-click inside of dialog

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#450]
Hi @argelius,

seems like the dialog directive creates an isolated scope. How can I access the parent scope to invoke some click actions? (for example, I've created a login dialog and all my controller related stuff is in my LoginController, e.g. Facebook-Login, but my functions don't trigger in the dialog.

Any fast solution for me?

**Comment by argelius** [comment]
Thanks @Hirbod,

You mean that the dialog should be attached to the DOM of the controller that created it? I'll consider how to implement this. Maybe we will need to add an extra argument to `createDialog()` to implement this behavior.

Or maybe we'll add another method that's works better when calling from inside a controller.

**Comment by Hirbod** [comment]
Hi @argelius,

if you ask me, the dialog is useless when it creates an isolated scope. You could handle this like other directives do it, and pass an "mother" or "parent" to it, that could be accessed via ```mother.scopefunction``` or ```parent.scopefunction```

**Comment by Hirbod** [comment]
@argelius 

I'm sure you know it, but maybe this is a good point:
http://angular-tips.com/blog/2014/03/transclusion-and-scopes/

**Comment by argelius** [comment]
Yes, passing the scope as an argument would probably be the best option. 

Another option would be to allow putting the `<ons-dialog>` tag inside the tag with the controller that controls it. A problem with this is that you maybe want to be able to show the same dialog in several different places.

**Comment by Hirbod** [comment]
I tried to modify the directive but I guess it won't work like I guessed (because of createDialog)

**Comment by argelius** [comment]
By the way,

Have you considered putting your authentication code in a service instead of using scope methods? In that case you can just inject it in the dialog's controller.

I tend to avoid using the scope for complex operations like this.

**Comment by Hirbod** [comment]
I considered it. As of the starting, I wasn't so familiar with angular and did many things "not the angular way", but my timeline is very small right now - so I don't have time to refactor everything.

Guess I need to move the code into a new controller if you don't know any fast way to make ng-click available on buttons inside of that dialog.

**Comment by argelius** [comment]
No, sorry. Since it isn't attached as a child in the DOM I think there's no nice way to do that.

You can always to something like this to get the "parent" scope:
```javascript
$scope.parentScope = angular.element(document.querySelector('.element-with-controller')).scope();
```

Not very nice though :)

**Comment by Hirbod** [comment]
Indeed, not nice... but I've already did some ugly stuff.. maybe this is ok :D 
But I guess it is not that hard to move my controller code. But I still feel, that this is an "error".

The dialog need to have access to the creating page. This is my understanding of real usage. I don't think that this current behaviour is good as it complicates stuff. Currently, it is easier to create my own dialog instead of relying to the existing one.

**Comment by Hirbod** [comment]
Maybe a parameter? Default isolated scope, with param the creating controller scope?

**Comment by Hirbod** [comment]
![bildschirmfoto 2015-02-17 um 10 13 09](https://cloud.githubusercontent.com/assets/504909/6225658/9895ea4e-b68d-11e4-951d-d6abd6af77f9.png)

Holy shrimp. Really? I just copied your example

```
        $scope.show = function(dlg) {
            ons.createDialog(dlg).then(function(dialog) {
                dialog.show();
            });
        };
```

but it really creates an dialog every call? Not nice. Thought there is an internal check if the dialog already exist

**Comment by argelius** [comment]
Yes, you should only run `createDialog` once. Did I write an example like that? If so, I will fix it.

In the demo it's like this:
```javascript
app.controller('MyCtrl', function($scope) { 
  $scope.data = { 
    name: '', 
    description: '', 
  }; 
 
  ons.createDialog('dialog.html').then(function(dialog) { 
    $scope.dialog = dialog; 
  }); 
 
  $scope.show = function() { 
    $scope.dialog.show(); 
  }; 

});
```

**Comment by Hirbod** [comment]
used your example on #383 for popover to fix this but 

```
$scope.$on('$destroy', $scope.loginDialog.destroy);
```

ends in 
```
TypeError: undefined is not an object (evaluating '$scope.loginDialog.destroy')
```

**Comment by Hirbod** [comment]
Yes, here is your example:
http://onsen.io/guide/components.html#ons-dialog

See the JS (I don't know if you did that example, but it is in the documentations example)

**Comment by Hirbod** [comment]
Ah... () is missing at destroy()

**Comment by Hirbod** [comment]
Thought this is a timing issue caused trough the promise, moved it inside of createDialog but destroy won't fire / destroy

**Comment by argelius** [comment]
Thanks! I've fixed the example. Will take a look at the `destroy()` method as well.

**Comment by Hirbod** [comment]
If I call destroy() trough the var-name dialog.destroy() in safari webinspector, it works, but I can't register it on destroy

**Comment by Hirbod** [comment]
Wrapped everything inside a service now. I guess, this is the most clean solution and I guess you're right, everything else is a mess.

Still, destroy() don't work as I showed you in my example. But when I call it trough the global var, it works. But I call var.destory() on login now, so this is ok for me.

**Comment by argelius** [comment]
Great!

Thanks for all the feedback! The examples I make are often a bit simple compared to real use cases so it's good to see how it works in a bigger app.

**Comment by argelius** [comment]
`ons.createDialog` now accepts an `options` object where you can specify `options.parentScope`.
