### ISSUE TITLE
feature request for dialog

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#451]
- some more animations then just a slide up (fadeIn, slideIn, slideLeft, slideRight, growIn, growInWithBounce, shrinkOut)
- some interaction animations (like a wiggle, when some entered wrong user credentials)

**Comment by Hirbod** [comment]
Ok, fade and slide is available as I can see inside of the code.

**Comment by Hirbod** [comment]
And another suggestions:
passing own easing properties instead of creating an own AnimationFactory

Duration, and easing type (dialog with 0.3 duration is to fast for me and I like to have a cubic-bezier instead of ease-in-out.)

**Comment by argelius** [comment]
Yes, that would be nice. 

We will refactor the animation classes so it will be easier to tweak duration and timing.

**Comment by Hirbod** [comment]
Documentation say:

Animation: none or default

Code says:
default -> will call slide up
fade -> will call slide up
slide (not documented) but will call slide down

But I would suggest to increase the default animation time. 0.3 is to short

**Comment by Hirbod** [comment]
It would be nice if we could use animate.css classes for that.
