### ISSUE TITLE
push page not pushing page with animation and all other angular functionality stops working on iOS 8.1.3

### ISSUE THREAD

**Issue by ankurvr7003** [OnsenUI/OnsenUI#452]
I am using ons-list and ons-list-item in my app.
In ons-list all items are created dynamically and compiled with ons.compile().
But when i click on ons-list-item there is push page code is written.
That code executes but page is not displaying on front, when i swipe from right to left that page will be showed and coming in front with my finger swipe.
After this issue my side bar is also stops working.

Here below you can see the problems in screen shots.
![img_0227 copy1](https://cloud.githubusercontent.com/assets/3338156/6228980/20f259fa-b6d8-11e4-801d-339a66b9113f.PNG)
![img_0228](https://cloud.githubusercontent.com/assets/3338156/6228985/39c36c4e-b6d8-11e4-8023-d8fa177ac137.PNG)
![img_0229](https://cloud.githubusercontent.com/assets/3338156/6228986/39d63338-b6d8-11e4-9bcf-1253594e0479.PNG)

Please help.
Thanks in advance

**Comment by argelius** [comment]
Hi @ankurvr7003 !

Could you please provide code that reproduces this issue?

**Comment by ankurvr7003** [comment]
Hi @argelius  Thanks for reply.
Our code is confidential so i can't send you code here. Is there any way to send you code directly or in secure way?
Please let me know the way to send code.

**Comment by argelius** [comment]
Sure,

Please send the code to: 
```javascript
console.log('andreas.argeli.us'.replace('.', '@'));
```

**Comment by ankurvr7003** [comment]
Sent. Thanks

**Comment by ankurvr7003** [comment]
Hi @argelius ,

This issue is not resolved yet. Please help.

Thanks in advance

**Comment by argelius** [comment]
Hi @ankurvr7003 !

Sorry, we haven't been able to reproduce this bug yet.

**Comment by ankurvr7003** [comment]
Hi @argelius ,

I am facing that bug everytime. And also reproduced with another page which have form with 15 components (textbox, textarea, select, radio, checkbox, dialogbox).

**Comment by argelius** [comment]
Did you notice which component caused it?

**Comment by ankurvr7003** [comment]
I have used a dropdown box for country selection in which countries are coming from a function from javascript file.
If i comment country dropdown then page is pushed with animation other wise not animating on iPad2 (iOS 8.3).

Another problem is with ons-dialog. If i request for ons dialog then it is not coming directly to front of screen. after 2-4 second it is coming on front and sometimes not showing in front of screen. After scroll to bottom of page i can see that dialog box created at bottom and sucked there. After dialog box request all other click functionality stops working and also not able to hide dialog box from screen.

**Comment by argelius** [comment]
That's interesting.

So, it's just a normal `<select>` tag and without it it works fine?

**Comment by ankurvr7003** [comment]
Yes, without select tag page push works fine.
