### ISSUE TITLE
two ons.createDialog cause problem

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#453]
Hi,

when I do this

```
            ons.createDialog('templates/login_dialog.html').then(function(dialog) {
                $scope.loginDialog = dialog;
                //$scope.$on('$destroy', $scope.loginDialog.destroy);
            });

            ons.createDialog('templates/registration_dialog.html').then(function(dialog) {
                $scope.registerDialog = dialog;
                //$scope.$on('$destroy', $scope.loginDialog.destroy);
            });
```

I get this error:
![bildschirmfoto 2015-02-17 um 19 25 14](https://cloud.githubusercontent.com/assets/504909/6234375/bd619736-b6da-11e4-8290-70d87d100135.png)

But if I have only one, it works perfectly.

**Comment by Hirbod** [comment]
And when I have two ```<ons-template id="name1.html">``` and ```<ons-template id="two.html">```
it will always fail with the second:

```
Failed to load resource: The requested URL was not found on this server.
```

**Comment by argelius** [comment]
Looks like it's related to this: https://github.com/angular/angular.js/issues/9128

**Comment by argelius** [comment]
Also, for the second issue I'd like some more information. Does this happen with all templates or only when you use `createDialog`?

**Comment by Hirbod** [comment]
Hi @argelius,

The second one seem to happen only with createDialog. Ng repeat with template does not fail. The only way for me was to mix between static template and inline template (to generate two dialogs). Weird, as your example contains three without problem.

**Comment by argelius** [comment]
Yes, there was another user that had a similar problem. He said that if he made several templates only every second template worked. So if he had three templates the first and the third worked while the second one didn't.

Can you confirm if this is the same issue? Do they work if you put a dummy template between them?

**Comment by Hirbod** [comment]
I'm not in the office right know, could try to confirm this in a couple of hours.

**Comment by Hirbod** [comment]
I can confirm the same issue @argelius

**Comment by argelius** [comment]
Thanks! It would be nice to see exactly what triggers this bug. 

The user with a similar bug had a quite complicated app so it was hard to identify the cause.

**Comment by Hirbod** [comment]
My project is also very complex, I don't really know how to help you to fix this.
I could give you access to my Mac trough TeamViewer if you want to check this here.

**Comment by kylewelsby** [comment]
How is this not fixed?

**Comment by munsterlander** [comment]
This bug may not have been updated, but in 2.0 this is obviously fixed.  I do not know about 1.0 though.
