### ISSUE TITLE
<ons-icon> spinning + text layout bug in android 4.1.2

### ISSUE THREAD

**Issue by andipavllo** [OnsenUI/OnsenUI#454]
<ons-icon> layout is bugged when is displayed together with a text and with the spinning effect enabled. No issue if there is no spinning effect.

Device: Samsung GT-I8190N - Android 4.1.2 - Screen resolution 800x480 px

![screenshot_2015-02-18-15-17-11](https://cloud.githubusercontent.com/assets/10593912/6243365/0e133c2c-b783-11e4-9927-133226db3216.png)
![screenshot_2015-02-18-15-28-01](https://cloud.githubusercontent.com/assets/10593912/6243364/0e11a1b4-b783-11e4-8fc5-15307b8cf136.png)

**Comment by argelius** [comment]
Thanks @andipavllo !

I'll take a look at this and see if I can fix it.
