### ISSUE TITLE
White screen on android mobile device

### ISSUE THREAD

**Issue by rahilwazir** [OnsenUI/OnsenUI#456]
I have this html contained inside the `body` element

    <ons-navigator title="Navigator" var="myNavigator">
      <ons-page>
        <section ng-if="!logged" ng-controller="SigninCtrl">
          <ons-toolbar>
            <div class="center">Sign In</div>
            <div class="right">
              <ons-toolbar-button onclick="myNavigator.pushPage('partials/signup.html', { animation : 'slide' } )">Sign up
              </ons-toolbar-button>
            </div>
          </ons-toolbar>
          <div class="login-form">
            <input class="text-input--underbar" ng-model="username" placeholder="Email" type="email" value=""/>
            <input class="text-input--underbar" ng-model="password" placeholder="Password" type="password" value=""/>
            <br/>
            <br/>
            <ons-button class="login-button" modifier="large" ng-click="submit()">Sign In</ons-button>
            <br>OR<br>
            <br>
            <ons-button ng-click="authenticate('facebook')" class="facebookbtn">
              <ons-icon icon="fa-facebook" size="48px" fixed-width="false"></ons-icon>
            </ons-button>
            <br/>
            <ons-button class="forgot-password ng-hide" modifier="quiet">
              Forgot password?
            </ons-button>
          </div>
          <ons-modal ng-click="modal.hide()" var="modal">
            <div class="alert-dialog-mask">
            </div>
            <div class="alert-dialog">
              <div class="alert-dialog-content">
                Invalid Username or Password.
              </div>
              <div class="alert-dialog-footer">
                <button class="alert-dialog-button alert-dialog-button--primal">OK</button>
              </div>
            </div>
          </ons-modal>
        </section>
  
        <ons-tabbar ng-if="logged" animation="fade">
          <ons-tab icon="ion-ios7-chatboxes" active="true" label="Chat groups" page="partials/group-chat.html"></ons-tab>
          <ons-tab icon="ion-person-stalker" label="Friends" page="partials/friends.html"></ons-tab>
          <ons-tab icon="ion-chatbox-working" label="Messages" page="partials/messages.html"></ons-tab>
          <ons-tab icon="ion-ios7-settings" label="Settings" page="partials/settings.html"></ons-tab>
        </ons-tabbar>
      </ons-page>
    </ons-navigator>

This work fine on browsers but when creating the `.apk` build and running in an emulator it always shows white screen. So removing the `ons-navigator` element and type some random text will display the body on the emulator.

Whats the problem with the above template file? Why does it shows white screen of death?

**Comment by argelius** [comment]
Have you confirmed that all JavaScript files are loaded correctly and there are no JavaScript errors? Does it show fine if you use a simple page like:

```
<ons-page>
  <ons-toolbar>
    <div class="center">Title</div>
  </ons-toolbar>

  <p>Some text</p>
</ons-page>
```

**Comment by rahilwazir** [comment]
Yes above code displays the view. And yes I can confirm there are no JavaScript errors.

**Comment by argelius** [comment]
I think you want to have the tab bar outside the page element.

**Comment by rahilwazir** [comment]
Moving/Removing the `tab-bar` element outside to the `page` element doesn't affect anything.

**Comment by argelius** [comment]
Could you try to make a minimal example by removing stuff until the bug doesn't occur anymore?

**Comment by rahilwazir** [comment]
Hmm removing the websocket factory solves the problem. Now I have to find websocket plugin for cordova :unamused:

**Comment by argelius** [comment]
I'm happy you were able to find the problem! :+1:
