### ISSUE TITLE
Keyboard pushing up navigator bar in iOS 8

### ISSUE THREAD

**Issue by mmok1234** [OnsenUI/OnsenUI#458]
When the keyboard appeared, the navigator bar will pushing up. How to fixed the navigator bar? I found "Keyboard.shrinkView" not working.

![123](https://cloud.githubusercontent.com/assets/3435090/6267429/db974caa-b87e-11e4-86a2-e1dc36d4aa5e.jpg)

**Comment by Hirbod** [comment]
This is the biggest problem on phonegap development. You need to install the Ionic Keyboard Plugin 
https://github.com/driftyco/ionic-plugins-keyboard

and call
```
cordova.plugins.Keyboard.disableScroll(true);
```

**Comment by mmok1234** [comment]
Your are right. But I found the keyboard will cover the text input. Can I use javascript to let the text input pushing up?

 windows.scrollto(x,x) is work??

**Comment by Hirbod** [comment]
No, it won't work (as far as I could try)
I used the keyboard event and the keyboardHeight value, added the value to my container and scrolled this one up. This worked then for me.

**Comment by mmok1234** [comment]
Can you give me a sample code about you case?  (currentHeight + keyboardHeight......etc)

**Comment by Hirbod** [comment]
Learning by doing :)
And I'm out of the office now 

Von meinem iPhone gesendet

**Comment by mmok1234** [comment]
Thanks for your help.
And I just do not understand your way about (currentHeight + keyboardHeight......etc)

**Comment by mmok1234** [comment]
Hay
I got the currentHeight + keyboardHeight. How can I scrolled this one up?
