### ISSUE TITLE
ons-dialog height bug when navigator inside

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#459]
Ons-Dialog fail to have a correct height when there is a navigator inside. Without navigator, the height is determined correct.

**Comment by argelius** [comment]
Thanks @Hirbod !

**Comment by argelius** [comment]
I've looked at this and I think it's better to just define a height of the dialog. 

If we change the height of the dialog based on what's in the navigator the dialog will change height when a page is pushed which I don't think is very nice.

**Comment by Hirbod** [comment]
When the height change would be animated it would be very nice. A fixed height is not that cool right now
