### ISSUE TITLE
1.2.1 issues with <ons-toolbar> trim and center in iOS

### ISSUE THREAD

**Issue by DennisXH** [OnsenUI/OnsenUI#460]
the content of class="center" in <ons-toolbar>  is cutted it in a half in iOS platform? is it a bug? I tried the following solutions, but it doesn't work.

1. Override it by using the fixed-style attribute:

\<ons-toolbar fixed-style>
  \<div class="center">Center\</div>
\<ons-toolbar>

2. http://onsen.io/blog/onsen-ui-and-phonegapcordova-on-ios-7/

I'm using 1.2.1 onsen. thanks

![screen shot 2015-02-20 at 3 39 12 pm](https://cloud.githubusercontent.com/assets/6447062/6311548/21cff7cc-b919-11e4-94c2-ca586d645f98.png)
![screen shot 2015-02-20 at 3 38 06 pm](https://cloud.githubusercontent.com/assets/6447062/6311549/21d312b8-b919-11e4-9e01-a70fab8d89f0.png)

**Comment by argelius** [comment]
Thanks for reporting @DennisXH !

We will take a look at this. Could you please paste the whole code that reproduces this? Does it happen on all iOS devices or only on iPhone 5?

**Comment by DennisXH** [comment]
Here are the code:
    <ons-toolbar>
        <div class="left">
          <ons-back-button>Back</ons-back-button>
        </div>
        <div class="center">Title222</div>
        <div class="right">
          <ons-toolbar-button>
            <ons-icon icon="fa-bars"></ons-icon>
          </ons-toolbar-button>
        </div>
      </ons-toolbar>
It happen on all iOS devices. Thanks

**Comment by DennisXH** [comment]
<ons-toolbar>
        <div class="left">
          <ons-back-button>Back</ons-back-button>
        </div>
        <div class="center">Title222</div>
        <div class="right">
          <ons-toolbar-button>
            <ons-icon icon="fa-bars"></ons-icon>
          </ons-toolbar-button>
        </div>
      </ons-toolbar>
It happen on all iOS devices. Thanks

**Comment by DennisXH** [comment]
I fixed it finally. It is not about the framework itself. I put "overflow:hidden" somewhere in .css file so that the content of class="center" is cut into a half.  @argelius please close this issue discussion, thanks.

**Comment by argelius** [comment]
Happy you solved it! :)
