### ISSUE TITLE
android slower than iphone 

### ISSUE THREAD

**Issue by syrakozz** [OnsenUI/OnsenUI#461]
the project in android is slower than iphone,
is there any recomendattion about android minimum device specification that i must support, 
or is there any tips for making the android perform fast like ios does

**Comment by argelius** [comment]
Are you using Crosswalk as your WebView?

If not, I would recommend trying that. Crosswalk only supports Android 4.0
and later though.
2015/02/24 1:08 "syrakozz" <notifications@github.com>:
