### ISSUE TITLE
Material Design on Android

### ISSUE THREAD

**Issue by JcDenton86** [OnsenUI/OnsenUI#462]
Hello,
It would be great if Onsen could support some of the features of the Material design on the Android devices. Maybe using a modifier or a similar approach. Right now I am using waves (http://fian.my.id/Waves/) in order to implement ripple effect on my buttons and list items.

**Comment by argelius** [comment]
Thanks @JcDenton86 !

We're actually planning on implementing some parts of the Material Design spec.

**Comment by shaulhadar** [comment]
Argelius that would be great!
