### ISSUE TITLE
Usage of .off() & .once()

### ISSUE THREAD

**Issue by JcDenton86** [OnsenUI/OnsenUI#463]
Hello,
Please help me understand this. I am using event handlers (`postpush`, `postclose` and `preclose`) in my application to handle different things. When I leave the page the ondestroy function of the controller is called. There I remove the event handler using the off() function, but the callback never get called. Firstly, should I remove those event handlers or Onsen removes them automatically (I've went through the code and seen that many handlers are removed on destroy but what is happening for the custom ones)? and secondly maybe the documentation should give some examples or better explanation on how are those functions working during the life-cycle of the application (like jQuery's docs).

Thanks in advance.

**Comment by argelius** [comment]
Hi,

We remove event handlers when elements are destroyed.

**Comment by JcDenton86** [comment]
Ok, I' ll keep them on the `$scope.on('$destroy')`, but why the callback does not get called? 
`$scope.navigator.off('postpush',function(){console.log('it will now show up on log')});`

**Comment by argelius** [comment]
`off(eventName, callback)` will remove a callback so that callback will never execute.

Example:

```javascript
var cb = function() {
  console.log('Hi, there!');
};

// Add event handler.
$scope.navigator.on('postpush', cb);

$scope.$on('$destroy', function() {
  // Remove the event handler.
  $scope.navigator.off('postpush', cb);
});
```

**Comment by JcDenton86** [comment]
Thanks for the clarification! I am closing this now..
