### ISSUE TITLE
The swipe-target-width of the ons-sliding-menu control affects also the ons-pull-hook control

### ISSUE THREAD

**Issue by gtsopour** [OnsenUI/OnsenUI#464]
It seems that the swipe-target-width of the ons-sliding-menu affects also the ons-pull-hook control. If I set the swipe-target-width to 100, then the ons-pull-hook control is usable only at the first 100px

**Comment by argelius** [comment]
Thanks for reporting @gtsopour ! We will look into this.

**Comment by argelius** [comment]
@gtsopour 

I've made a change that fixes this bug. If you like to try it you can use the latest build version:
http://onsen.io/download.html#latest-build
