### ISSUE TITLE
opening collapsed ons split view 

### ISSUE THREAD

**Issue by bricous** [OnsenUI/OnsenUI#465]
Hi,

Docs says ons-split-view  has capability to transform to a sliding menu pattern on smaller devices or displayed vertically. But How ? when split view is collapsed on small device, how make it open (like a sliding menu) ?

thank you for your help.

**Comment by bricous** [comment]
May be a solution
It seems to be possible to put an ons-sliding-menu in the main-page of an ons-split-view. The sliding menu is magically inhibited when  ons-split-view is opened and become activated when ons-split-view is collapsed. If they share the same menu-page, the illusion is perfect.

**Comment by argelius** [comment]
Yes, I think this is the best way to do it. There will however be two menus in DOM so if you make any DOM changes you will have to make them to both.

We're planning on adding a component that works both like a split view and a sliding menu.

**Comment by c58** [comment]
Hi, @argelius . There is any progress about mentioned component (split-sliding)?

**Comment by argelius** [comment]
Hi!

It has already been created and merged into master. 

It's called `<ons-splitter>` and will be released with Onsen UI 2.0.

**Comment by c58** [comment]
Cool! Thanks.

**Comment by amir-s** [comment]
@argelius 
Thanks.
Is there any documentation about this?

**Comment by argelius** [comment]
Hi @amir-s !

Yes, it's documented in this file:
https://github.com/OnsenUI/OnsenUI/blob/master/framework/directives/splitter.js

**Comment by amir-s** [comment]
Thanks @argelius!
Please keep up the good work :+1: 
So excited to see this. I just have couple of questions regarding this `ons-splitter`.

1. How to include the splitter side from external file? like we could do in `split-view` with `secondary-page="path/to/file.html"`? Is it possible? I currently use `ng-include` for that.

2. I saw the blog post on this. I tried it myself and it works fine. But the nice thing about `ons-sliding-menu` was the menu actually shifts the main content aside to appear, but the `split-view`'s splitter side overlays the content. It would be great if we could have control over this behavior. Is it possible?
