### ISSUE TITLE
Viewport issue on iOS 7+

### ISSUE THREAD

**Issue by tunacoder** [OnsenUI/OnsenUI#468]
Onsenui 1.2.2 introduced Viewport.js to support meta[viewport] tag  on iOS 7+.

in landscape mode of iPad + cordova, the app screen overflow the screen.
I found for example, in portrait mode Width x Height = 320 x 480, but in landscape mode Width x Height  = 480 x 480.
so I commented the line - new Viewport().setup(), my app it works correctly.

I don't think viewport meta tag is error. What do you think about this issue ?

**Comment by argelius** [comment]
Thanks for reporting @tunacoder !

We'll look into this.

**Comment by tunacoder** [comment]
if you want, I can take a screencast about that issue.

**Comment by argelius** [comment]
Yes, please add a screenshot here if it's not too much trouble.

**Comment by tunacoder** [comment]
https://www.dropbox.com/s/g1frh86ldngqrkp/onsenui-issue-1.mov?dl=0

please have a look the screencast.

**Comment by argelius** [comment]
Thanks a lot @tunacoder!

This has been fixed now.
