### ISSUE TITLE
ons-lazy-repeat feature with absolute position

### ISSUE THREAD

**Issue by nakomi** [OnsenUI/OnsenUI#470]
I really like this feature but I just figure out they are positioning with absolute position, so it can only be placed on very top of the page and without some flexibility.

Is there anyway to add padding or container height like ons-scroller did so it can be greater function and maximise the flexibility of UI Design.

Thanks!

**Comment by argelius** [comment]
Right now there's no good way to do this because of the absolute positioning. You can try using `position: relative` for the container though if you want some content above the list.

**Comment by nakomi** [comment]
Thanks!! @argelius 

I will try find some css trick to solve it, but it will be good if we can have it in future.

**Comment by argelius** [comment]
Thanks! We'll try to think of some way to make it easier to use.

I'm reopening this if that's OK.

**Comment by nakomi** [comment]
Thanks a lot!
