### ISSUE TITLE
Javascript Error on Android 5.0 browser

### ISSUE THREAD

**Issue by sandeep-agarwal** [OnsenUI/OnsenUI#471]
Device : LG G3
Android Version: 5.0.1

OnsenUI (1.2.1) : http://onsen.io/patterns/lib/onsen/js/onsenui.js
Angular JS (1.3.14) : https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js

Repo Steps : 
1. Open http://jsbin.com/hijutu/1 on android 5.0.1 browser (not google chrome for mobile)
2. In the address bar type about:debug
3. Open the Javascript console 

It'll show the error Uncaught Illegal Access at line 16909. 

![onsenui-js-error](https://cloud.githubusercontent.com/assets/7799605/6491551/cf7a2bac-c262-11e4-8430-3f8c6e4ce040.png)

**Comment by argelius** [comment]
Thanks @sandeep-agarwal !

We'll take a look at this issue.
Do you get this issue when you run it as a Cordova app as well?

**Comment by sandeep-agarwal** [comment]
No the Cordova app works fine on android 5.0.1.
