### ISSUE TITLE
i have one request for team

### ISSUE THREAD

**Issue by tormahiri** [OnsenUI/OnsenUI#476]
i'm discovered this library one week ago,i'm testing i''m debugging,this is nice framework,but lack of this framework is does not support rtl layout ,i mean right-to-left layout,please guy add some support for right-to-left layout,becuase i'm always using right-to-left layout on my own production
thanks

**Comment by argelius** [comment]
Thanks @tormahiri !

Yes, we've been getting a lot of requests for RTL support lately. We'll consider adding it. 

However, we don't have anyone on the team that speaks a language with RTL writing so we would need someone to test it.

I'm closing this issue since there is already one on this topic.
