### ISSUE TITLE
Replacement for action sheet

### ISSUE THREAD

**Issue by joshhunt** [OnsenUI/OnsenUI#479]
It would be handy if Onsen had a possible replacement or option for iOS Action Sheets - basically when you just want a list of buttons for the user to select.

![actionsheet_simulator](https://cloud.githubusercontent.com/assets/46142/6587222/b17db8a8-c7d5-11e4-9289-1dcdca363e37.png)

I use the native component through cordova, but for web which doesn't support this, I made this wrapper which creates <ons-dialog> elements on demand, by passing a hash:

``` coffee
dialog = null
            dialogID = Math.random().toString(36).substr(2, 5)
            dialogName = "fakeDialog_#{dialogID}"
            confName = "#{dialogName}_config"
            templateName = "#{dialogName}.html"

            $rootScope[confName] = config

            _cleanup = ->
                console.info 'Performing cleanup'
                delete $rootScope[confName]
                delete $rootScope[dialogName]
                window.jQuery("ons-dialog[var='#{dialogName}']").remove()

            config._tapped = (selectedRow) ->
                selectedRow.action()
                dialog.hide()
                setTimeout _cleanup, 3 * 1000

            template = """
                <ons-dialog var="#{dialogName}" cancelable>

                    <ons-list class="text-center">
                        <ons-list-item modifier="tappable" ng-repeat="row in #{confName}.actions" ng-click="#{confName}._tapped(row)">
                            {{row.label}}
                        </ons-list-item>

                        <ons-list-item modifier="tappable" ng-if="#{confName}.cancel" ng-click="#{confName}._tapped(#{confName}.cancel)">
                            <span class="semi-bold">{{#{confName}.cancel.label}}</span>
                        </ons-list-item>
                    </ons-list>

                </ons-dialog>
            """

            $templateCache.put templateName, template

            ons.createDialog(templateName).then ->
                dialog = window[dialogName]
                dialog.show()
```

It would be handy to have some sort of UI component within Onsen, like `ons.notification.confirm`, but with more than just two options.

**Comment by argelius** [comment]
Hi @joshhunt !

Thanks for the feedback! We'd like to add something like the iOS action sheet at some point.

Actually `ons.notification.confirm` supports more than two options:
```javascript
ons.notification.confirm({
  message: "What do you want to do?",
  buttonLabels: [
    'Action 1',
    'Action 2',
    'Cancel'
  ],
  primaryButtonIndex: 2
});
```

http://codepen.io/argelius/pen/PwyPvp

Maybe it's not clear enough in the docs.

**Comment by joshhunt** [comment]
Wow. That is much better than my attempt. Thanks for clearing that up.

**Comment by argelius** [comment]
No problem!

But it seems like the docs never mention that it's possible to use more than two buttons so we'll make it clearer in the next release. Thanks! :)

**Comment by asial-matagawa** [comment]
Onsen UI provides [`ons-action-sheet`](https://onsen.io/v2/docs/js/ons-action-sheet.html) since Onsen UI 2.3.0.

Closing this.
