### ISSUE TITLE
ons-pull-hook makes content flicker

### ISSUE THREAD

**Issue by MikaelLind** [OnsenUI/OnsenUI#485]
Hi,

When I add a <ons-pull-hook> tag to my page the content start to flicker when I scroll the page really slowly in iOS. It doesn't seem to be a problem in Android.

Best regards

**Comment by argelius** [comment]
Thanks for reporting @MikaelLind !

We'll try to solve the flickering.

**Comment by MikaelLind** [comment]
You're welcome @argelius 
Do you have any release date for 1.2.3?

**Comment by argelius** [comment]
Unfortunately not at the moment but I think we'll release it pretty soon.

**Comment by argelius** [comment]
@MikaelLind 

I've tried it both on an iOS device and in the simulator without any issues.
What device and iOS version were you using? Also, what kind of content were you displaying on the page?

**Comment by MikaelLind** [comment]
@argelius 

I'm using an iPhone 6 with the latest iOS version (8.2 I think?).
The content on the page is a list of posts. But I'm not using ons-list, instead I'm using regular div's. Can that be the issue?

**Comment by argelius** [comment]
Tack @MikaelLind !

No, I don't think that should be an issue. I'll make some more tests this week.
Is the list just text or are there images? Are you using any 3d (or non-3d) transforms on the content?

**Comment by MikaelLind** [comment]
No images or transforms. I have only added some custom fonts.

**Comment by argelius** [comment]
Thanks!

**Comment by MikaelLind** [comment]
Have you found the problem yet @argelius ?

**Comment by MikaelLind** [comment]
@argelius - Still not solved in 1.3.1

**Comment by DanielKalbasi** [comment]
@argelius I have the same issue, but instead in Android. in iOS is works pretty smooth.

**Comment by erwinyu888** [comment]
Still not solved

**Comment by asial-matagawa** [comment]
@erwinyu888 
Oh, really?
If so, could you fill this? We need some information for reproducing the problem.

```
Environment

[Core]
    Onsen UI 2.0.4

[Framework]
    None
    Angular 1.5.9
    Angular 2.2.4
    React 15.4.1
    Vue.js 1.0.28
    Vue.js 2.1.4

[Framework binding]
    None
    angular-onsenui 2.0.4
    angular2-onsenui 1.0.0-rc.3
    react-onsenui 1.0.4
    vue-onsenui 1.0.0

[Additional libraries]
    None
    jQuery 3.1.1

[Platform]
    Mobile - Android 7.1
    Mobile - iOS 10.1.1
    Desktop - Linux
    Desktop - macOS Sierra
    Desktop - Windows 10

[Browser]
    Mobile - Android WebView
    Mobile - Android Chrome 54.0.2840.85
    Mobile - iOS UIWebView
    Mobile - iOS Safari
    Desktop - Chrome 55.0.2883.75
    Desktop - Safari 10.0 (12602.1.50.0.10)
```

**Comment by puku0x** [comment]
This still not solved.
I faced the same issue with 2.2.6.
