### ISSUE TITLE
Click event firing twice for child elements of ons-lazy-repeat

### ISSUE THREAD

**Issue by WaseemSiddiqui** [OnsenUI/OnsenUI#498]
Hi,

I attached a click event using ng-click to a child element of ons-lazy-repeat and noticed that the click event is getting fired twice.

Here is the codepen link for the same: http://codepen.io/anon/pen/xbypJZ

What could be the issue?

**Comment by argelius** [comment]
Thanks @WaseemSiddiqui !

This looks like a bug so we'll fix it. Seems like the exact same event is triggered twice.

**Comment by argelius** [comment]
Looks like the inner elements were compiled twice. 

It's been fixed now.
