### ISSUE TITLE
Font Awesome icons displaying as square Windows Phone 8

### ISSUE THREAD

**Issue by FragCoder** [OnsenUI/OnsenUI#507]
All icons displaying as square in WP8.
I found partial solution:
http://stackoverflow.com/questions/25329784/fontawesome-displaying-as-squares-on-wp8-using-cordova-phonegap

**Comment by frankdiox** [comment]
This should be fixed after the windows-support we added last week, but we will test it more in this week.

**Comment by FragCoder** [comment]
I've tested with latest build...
Work when compiled with profile Windows Phone Universal not with profile Windows Phone 8 (Visual Studio 2013)

**Comment by frankdiox** [comment]
Sorry but we are not testing Windows Phone 8.0, only Windows Universal (8.1). If you are still interested in W8.0, maybe this will be helpfull: https://github.com/OnsenUI/OnsenUI/pull/247

**Comment by tdiddi** [comment]
I still got this issue with Intel XDK, Phonegap and Visual Studio. If needed, i can give more Information tomorrow. Tried with WP 8.1

**Comment by asial-matagawa** [comment]
This issue can be closed since this conversation seems to have been done already. Closing this.
