### ISSUE TITLE
PullHookView _destroyEventListeners error

### ISSUE THREAD

**Issue by rettier** [OnsenUI/OnsenUI#508]
in _destroyEventListeners the last line 
element.off('scroll', ...) 
causes an error when i switch the page with my tabbar.

possible fix:
change var element = this._scrollElement[0].parentNode to
var element = this._scrollElement.parent();

**Comment by argelius** [comment]
Thanks @rettier!

This bug was already fixed in https://github.com/OnsenUI/OnsenUI/commit/93613dbd64272df9ed4d72c75b24b838863b9618

We will make a new release shortly with this fix.
