### ISSUE TITLE
Windows 8 - Unable to add dynamic content

### ISSUE THREAD

**Issue by FragCoder** [OnsenUI/OnsenUI#509]
JavaScript runtime error: Unable to add dynamic content. A script attempted to inject     
dynamic content or elements previously modified dynamically that might be unsafe. For 
example, using the innerHTML property to add script or malformed HTML will generate this 
exception. Use the toStaticHTML method to filter dynamic content or explicitly create 
elements and attributes with a method such as createElement.

Including script before AngularJS fix this issue.
https://github.com/MSOpenTech/winstore-jscompat/blob/master/winstore-jscompat.js

**Comment by frankdiox** [comment]
There is already a "win-support" branch for this. Thank you.

**Comment by masahirotanaka** [comment]
@frankdiox We have merged `win-support` branch to `master` branch. Can you try running on the latest **mater** branch?

**Comment by FragCoder** [comment]
still not working in latest build...

**Comment by frankdiox** [comment]
Have you downloaded the latest build from the link provided in the readme?
http://onsen.io/download.html#latest-build

The directory "build" on Github is not updated every day. Please tell me if your problems continue with the version of that link.

**Comment by FragCoder** [comment]
Hi Frank,
yes I've downloaded the latest version from the same link.
I must add   <script src="scripts/winstore.js"></script> before angular...otherwise app exit after launch (got exception).

part of my head tag:
  <link rel="stylesheet" href="lib/onsen/css/onsenui.css">
    <link rel="stylesheet" href="styles/app.css" />
    <link rel="stylesheet" href="styles/onsen-css-components-blue-basic-theme.css">
    <script src="scripts/winstore.js"></script>
    <script src="lib/onsen/js/angular/angular.js"></script>
    <script src="lib/onsen/js/onsenui.js"></script>
      <script src="cordova.js"></script>
    <script src="js/app.js"></script>

**Comment by frankdiox** [comment]
Well, the problem of the dynamic content is not actually related to OnsenUI. Windows Phone adds some security to the DOM manipulation so you need to add that shim (winstore-jscompat.js) before doing anything in order to develop your app. I thought it was enough to add it before you initialize your angular app, but perhaps it's necessary to include it before angular library as well.
Anyway, Windows 8.1 support is not finished yet, so you may find some other problems :/
