### ISSUE TITLE
TabbarView.registerAnimator doesn't work

### ISSUE THREAD

**Issue by marcel-dancak** [OnsenUI/OnsenUI#512]
There is a (copy/paste) bug in TabbarView.registerAnimator function. There should be

this._animatorDict[name] = animator;

instead of

this._transitionAnimatorDict[name] = animator;

**Comment by argelius** [comment]
Thanks a lot @marcel-dancak !

We will take a look at this. Feel free to open a pull request if you like.

**Comment by marcel-dancak** [comment]
Okey, I will prepare pull requests to all bugs that I'll find

**Comment by argelius** [comment]
That's really appreciated, thanks! :+1:
