### ISSUE TITLE
Unstable ons-if-orientation

### ISSUE THREAD

**Issue by Cadmos** [OnsenUI/OnsenUI#520]
When it comes to display different images or entire div blocks it becomes very unstable;

1. It shows the alternative image after you rotate orientation 3-4 times, meanwhile it shows only the initial  image

2. It shows the alternative div blocks after many orientations, meanwhile it shows empty content on second orientation, for example if in your code you have the portrait orientation div blocks first, it will show empty the landscape div blocks in the first orientation rotations.

It happens on various android devices I have (tablets & smartphones). 

I compile with Cordova 4.3.0 (Android 4.4.2 - API 19 - Build Tools 19.1.0 - Android SDK Tools Revision 22.6.3)

**Comment by argelius** [comment]
Thanks @Cadmos !

We will address this issue as soon as we can.

**Comment by argelius** [comment]
@Cadmos What is the value of your `collapse` property?

**Comment by argelius** [comment]
This should be fixed now.
