### ISSUE TITLE
ons-button 's active css animation not work when destroy ons-dialog

### ISSUE THREAD

**Issue by zhuangperola** [OnsenUI/OnsenUI#522]
I have created an ons-dialog which has an ons-button.

The ons-button has registered an event to destroy the ons-dialog.

when the button is clicked, the ":active" css animation is not work.

I have checked ons.notification.alert which has the same problem.

Is a solution to solve this problem?

**Comment by zhuangperola** [comment]
In normal html pages, when ons-button is clicked, it changes its background-color and opacity to show a click event's animation.

**Comment by argelius** [comment]
Hi @zhuangperola !

Could you please provide some code that reproduces this? Does it happen on all devices or just some?

In this example it works fine: http://codepen.io/onsen/pen/jEWBGJ

**Comment by zhuangperola** [comment]
Hi @argelius 

Thank you for you example code which works fine at PC.(not check at Android)

I will provide my example codes later.

**Comment by zhuangperola** [comment]
Hi @argelius 

I have checked your example code and it works fine at Android.

My example has the same problem, when i hide the dialog, the ":active" animation works. but when I destroy the dialog, it doesn't.

Could you have a check of your example code by "dialog.destroy()" at Android Phone.

Thank you for your support.

**Comment by zhuangperola** [comment]
When click quickly, it happens 100%, but when click slowly, it doesn't.

**Comment by zhuangperola** [comment]
@argelius 

like code like this, which makes ":active" works again.

`$timeout(function () {
                dialog.destroy();
            },100);`

I guess ":active" works, but its parent DOM view is being destroying, so we could not see it.

Do you have any idea to improve this problem?

**Comment by argelius** [comment]
Thanks for the info! I think I'll be able to reproduce it now.

**Comment by argelius** [comment]
I think I misunderstood what you meant. Could you please describe the problem again and supply an example. Screenshots would also be helpful.

**Comment by zhuangperola** [comment]
![screen](https://cloud.githubusercontent.com/assets/4699836/7979115/1a80f6da-0acf-11e5-8720-ffd5be40d1d9.png)
![phone_pressed](https://cloud.githubusercontent.com/assets/4699836/7979116/1b240f82-0acf-11e5-9298-5ef2748fcc0e.png)
![phone_click](https://cloud.githubusercontent.com/assets/4699836/7979118/1d496802-0acf-11e5-851e-bbe5eced034b.png)

**Comment by zhuangperola** [comment]
capture is attached.

The problem is like this. 

First, the button is in onsDialog and click it will destroy dialog.

Then, I test it in computer, before dialog is dismissed, color change will happens to show it is pressed.

But if I test in phone, before dialog is dismissed, color change will not happen.

If I touch down it in phone, color change will happen. (not touch up)

**Comment by zhuangperola** [comment]
![phone_click](https://cloud.githubusercontent.com/assets/4699836/7979401/6cd861dc-0ad1-11e5-9096-4b51b19695c0.png)

**Comment by zhuangperola** [comment]
![screen](https://cloud.githubusercontent.com/assets/4699836/7979432/b837889c-0ad1-11e5-85af-0552e6e7e814.png)

**Comment by zhuangperola** [comment]
![phone_down_not_up](https://cloud.githubusercontent.com/assets/4699836/7979498/3b0b28dc-0ad2-11e5-9092-8115d08bc257.png)

**Comment by andipavllo** [comment]
@zhuangperola which version of android are you using?

**Comment by zhuangperola** [comment]
I build it with Android 5.0 and run it in Android 4.4 phone

**Comment by zhuangperola** [comment]
@andipavllo 

Is it really smart phone's css bug?
