### ISSUE TITLE
Sliding Menu documentation is missing 'type' attribute

### ISSUE THREAD

**Issue by danjarvis** [OnsenUI/OnsenUI#523]
In the sliding menu directive, at around [line 151](https://github.com/OnsenUI/OnsenUI/blob/master/framework/directives/slidingMenu.js#L151) the menu 'type' attribute should be documented.

Something like:

```javascript
ngdoc attribute
name type
type {String}
description
  [en]The animation effect applied when the menu is opening or closing The available values are reveal(default), push and overlay.[/en]
  [jp]...[/jp]
```
This is documented in the [OnsenUI Guide](http://onsen.io/guide/overview.html#Animationtype), but it should be explicitly mentioned in the directive.

**Comment by argelius** [comment]
Thanks @danjarvis ! We'll fix this
