### ISSUE TITLE
lazy-repeat go to first Element

### ISSUE THREAD

**Issue by salztorte** [OnsenUI/OnsenUI#527]
Is there a way to reset the scrolling point and jump to the first element of the lazy-repeat?

**Comment by argelius** [comment]
Sure, you can use JavaScript to scroll to the top by setting `scrollTop = 0` for the element. For a more Angular way you can check out the `$anchorScroll` service.

**Comment by salztorte** [comment]
Hey,
i tried your solution but in my project every scrollTop is 0.

**Comment by salztorte** [comment]
Hey,
i tried your solution but in my project every scrollTop is 0.

**Comment by d3orn** [comment]
any update on this? I have the exact same issue

**Comment by d3orn** [comment]
$(.'page__content').scrollTop = 0 works, but you have to be careful to select the actual page__content and not the page__content element of the menu (if you have one).
Try adding a class to the correct page__content from within chrome developer tools and then try the scrollTop.
But there should probably be a way to tell LazyRepeat to reset the offset

**Comment by argelius** [comment]
What about using the `$anchorScroll` service and putting an invisible element at the top of the list?

In controller:
```javascript
$scope.scrollToTop = function() {
  $location.hash('top');
  $anchorScroll();
};
```

Example:
http://codepen.io/argelius/pen/jERZwa

**Comment by salztorte** [comment]
Thanks. Its worked.
