### ISSUE TITLE
ons-tab with persistent, white screen after clicking on the same tab

### ISSUE THREAD

**Issue by Trexology** [OnsenUI/OnsenUI#530]
For some reason, adding "persistent" to ons-tab will get a white screen by click onto the same tab twice.

Using the example provided at: http://onsen.io/reference/ons-tab.html

<ons-tab page="home.html" label="Home" icon="ion-home" active="true" persistent></ons-tab>

add "persistent" to home tab, re-run the code, try clicking on home tab twice.

works fine after switching to other tab and coming back again.

**Comment by argelius** [comment]
Thanks @Trexology !

I'm sorry for letting a stupid bug like that slip through :)
We will fix this. In the meanwhile, please also add the `no-reload` attribute.
