### ISSUE TITLE
ons-list Windows Phone 8

### ISSUE THREAD

**Issue by d3orn** [OnsenUI/OnsenUI#532]
I cannot scroll down within a ons-list on Windows Phone. The only thing that happens, is I see where I touched first and where I stopped dragging.

I figured it has something to do with -ms-touch-action: none which is set for *

My solution included flexboxes and removing this css property

**Comment by d3orn** [comment]
ah I figured if I wrap the ons-list with an ons-scroller it works on windows as well

**Comment by argelius** [comment]
Great you were able to solve it @d3orn !

If you don't mind I will actually open this again since I think it should be possible to scroll even in an `<ons-page>` element.

**Comment by d3orn** [comment]
BTW what about ons-lazy-repeat scrolling those not work there either on WP (should I create a new issue?)
