### ISSUE TITLE
is possible OnsenUI with react.js?

### ISSUE THREAD

**Issue by wozzup** [OnsenUI/OnsenUI#538]
we know angularjs 1.x is dead, angularjs 2 is under-developing,
so is possible OnsenUI look forward for react.js?
https://facebook.github.io/react/index.html

**Comment by argelius** [comment]
Hi @wozzup !

I don't think Angular 1.x is dead just yet. :)
Angular 2 is still in Alpha and currently only Chrome supports the Web Components API (that I know of).

We're actively discussing the future of Onsen UI and one of the paths we might take is making it available for react.js . We haven't decided yet but you might see an announcement in the coming weeks.

**Comment by ankushu** [comment]
Hi @argelius 

Has the team made any decision about react?
