### ISSUE TITLE
ons-sliding-menu Windows Phone 8.1 

### ISSUE THREAD

**Issue by d3orn** [OnsenUI/OnsenUI#544]
Closing and opening the menu breaks the header (it loads after a split second) 
The following screenshot is taken from a Lumia 535 (WP 8.1) and the project is the one in templates (master) with the onsen_all.min.js.

![image](https://cloud.githubusercontent.com/assets/411479/6870703/ee9a26f2-d49d-11e4-9e25-25aa98a49f4e.png)

I currently have no idea how to fix it, but it would be awesome if the menu would work on Windows Phone as well

**Comment by argelius** [comment]
Thanks for reporting, @d3orn ! We've fixed the issue

**Comment by argelius** [comment]
Actually this fix broke the behavior on iOS so I'm opening this again.
