### ISSUE TITLE
Popoverposition

### ISSUE THREAD

**Issue by salztorte** [OnsenUI/OnsenUI#551]
Hello.
I have make a App with a Split-View and a Popover.
The Problem is that the positioning of the Popover not work correct if the Split-View is open (in a tablet view).

**Comment by argelius** [comment]
Thanks @salztorte !

Could you create a simple example that reproduces this issue?

**Comment by salztorte** [comment]
I resolved the problem.
Was my fault. I use the SlidingMenu / SlitView - Workaround  and ng-show instead of ng-if.
After I changed that everything work.
