### ISSUE TITLE
Sliding menu preclose event triggered when the menu is closed

### ISSUE THREAD

**Issue by andipavllo** [OnsenUI/OnsenUI#563]
The preclose event can be triggered even if the sliding menu is closed by swipe touch event. Works fine with drag touch event. Tested on android 4.1.2 native browser.

See  https://github.com/OnsenUI/OnsenUI/blob/master/test/manual-testcases/slidingMenu/04-events.html

**Comment by argelius** [comment]
Thanks @andipavllo !
