### ISSUE TITLE
ons-dialog with scope does not play well with navigation pattern(s)

### ISSUE THREAD

**Issue by zumbrunnen** [OnsenUI/OnsenUI#570]
We had strange errors when using `<ons-dialog>` together with the new ability to pass the scope (e.g. `ons.createDialog(dlg, {parentScope: $scope})`):

![screen shot 2015-04-02 at 15 24 29](https://cloud.githubusercontent.com/assets/3499909/6964734/64df0956-d94c-11e4-9300-761cf5d31b44.png)

To trace down this issue, I modified the example Codepen from the reference pages and extended it:
  * to pass the scope and
  * so that the dialog is shown within a `ons-navigator`.

My demo Codepen is here: http://codepen.io/anon/pen/EaJLjm
 1. Click "Switch to list page"
 2. Open "List" dialog, close it again
 3. Use back button.

The dialog is displayed well, but at the latest when using the back button, I get those 4 errors (`TypeError: Cannot read property 'data' of null`) thrown by some cleanup/destroy method that's triggered from the back action or a `popPage()`.

I've noticed, that the `<ons-dialog>` is written at the bottom of the page, mostly just before the closing `</html>` tag. Maybe this does not play well with the passed scope.

**Comment by zumbrunnen** [comment]
I went through this situation again and created a more accurate Codepen: http://codepen.io/anon/pen/VYNBWb

Just follow the steps :wink: 

Funnily, I get a different error here. And please note, that I'm using an `ons-sliding-menu` here. The error I get now is:

``` 
TypeError: Cannot read property '$$nextSibling' of null
```
![image](https://cloud.githubusercontent.com/assets/3499909/6970501/2d2edc64-d976-11e4-8742-1f8bddbd6d3b.png)

**Comment by zumbrunnen** [comment]
Thank you very much, @argelius. That fixed it! :+1:

**Comment by argelius** [comment]
That's great! :)
