### ISSUE TITLE
ons-lazy repeat list is blank / empty on pressing android device back button

### ISSUE THREAD

**Issue by WaseemSiddiqui** [OnsenUI/OnsenUI#571]
Hello,

Steps to reproduce :

1) Create an ons-lazy-repeat list with a lot of elements say 100 (page 1).
2) Scroll down and click on any element say 50th element.
3) On click, navigate to a new page using pushPage method of the navigator (page 2).
4) Do some scrolling on page 2.
4) **When you navigate back by pressing the android device's back button, the lazy repeat list seems to be hidden or empty.** If you come back by pressing the toolbar's back button, the list is displayed properly.

What could be the issue?

Also, on the page 2 when you scroll up/down the page, it seems that the lazy repeat functions like calculateItemHeight and countItems are still running in background which should not happen.

**Comment by argelius** [comment]
Thanks for reporting @WaseemSiddiqui !

We will investigate this. Definitely sounds like unwanted behavior.

**Comment by argelius** [comment]
@WaseemSiddiqui 

These two issues have been addressed now. Scrolling the detail page will not trigger render on the infinite list and now we cause a $digest loop when the page is popped event if it's popped with the hardware back button.
