### ISSUE TITLE
You can not supply no "ons-page" element to "ons-navigator

### ISSUE THREAD

**Issue by dojoVader** [OnsenUI/OnsenUI#572]
label:question
Hi guys I am building an large application, I use different structure similar to this
app--
        |__ components
                                |__ login
                                             |__ login.html

However in the login.html i am making use of an ons-tab
```
<ons-page class="transfer-to-self bgui">
<ons-tab page="new_beneficiary.html">
            <span style="font-size: 14px">New Beneficiary</span>
        </ons-tab>
</ons-page>
<ons-template id="new_beneficiary.html">

</div>
```

However this throws an error and says I didn't specify an ons-page which is quite wrong, but i found out it throws this code because of this line

```
var pageElement = angular.element(div), hasPage = 1 === div.childElementCount && "ons-page" === div.childNodes[0].nodeName.toLowerCase();
```
in the method _createPageElementAndLinkFunction

Must there be only one element in a page ? is this the Onsen Ui recommended way or a bug ?

Thanks guys

**Comment by argelius** [comment]
Hi! You need to create an `ons-tabbar` as well for your tabs.

This is a simple example:
http://codepen.io/onsen/pen/pGuDL
