### ISSUE TITLE
Cursor moves to the end of contents when focus on textarea/input

### ISSUE THREAD

**Issue by nutti** [OnsenUI/OnsenUI#578]
When I tapped textarea/text(type=input), cursor moves to the end of contents.
If someone want to use textarea as editor, this problem is critical.
I researched this problem , and realized that this problem comes from library 'fastclick'.
https://github.com/ftlabs/fastclick/issues/338
If this problem is fixed, library should be replaced.

If someone want to fix this problem temporarily, you can use my patch.
https://github.com/ftlabs/fastclick/pull/384

**Comment by argelius** [comment]
Thanks @nutti!

**Comment by asialgearoid** [comment]
This was re-filed recently as #2254. We have fixed it by forking FastClick and fixing it ourselves.
