### ISSUE TITLE
Using tab bars in the middle of content

### ISSUE THREAD

**Issue by marvoh** [OnsenUI/OnsenUI#579]
Hi,

I am creating a page with conference speaker information and would like to have his picture below the main tool bar then have profile, rating and contact information below the picture in tabs format so as not to have long pages on the mobile app.

The examples have seen so far only place the tabs top or bottom which is not always the only way to use them in real life applications. 

How would I implement this in a clean way if there's one already provided by the framework?

**Comment by argelius** [comment]
So you want several tab bars on every page?

The custom element is manly for page navigation so this won't work, but you can of course use just the CSS.

Please see the component page for information:
http://onsen.io/…images/index/feature-custom-elements.png
