### ISSUE TITLE
window.devicePixelRatio on iPhone 6 Plus is incorrect! 

### ISSUE THREAD

**Issue by iVanPan** [OnsenUI/OnsenUI#581]
window.devicePixelRatio is incorrect on my iPhone 6 Plus with onsenui.it return 2. I test window.devicePixelRatio with Framwork7  and other pages on mobile Safari ,they all return 3! Please help me

**Comment by argelius** [comment]
Thanks @iVanPan ! We'll investigate this

**Comment by Hirbod** [comment]
http://stackoverflow.com/a/25757310/3297914

**Comment by iVanPan** [comment]
on iPhone 6 Plus window.innerWidth = 320 and window.innerHeight = 568, devicePixelRatio  is 2. it's iPhone 5s 's value.so it can't adpater iPhone 6 and iPhone 6 Plus. I am a frash man on web app, so what should i do ?

**Comment by zack24q** [comment]
i have the same problem. i build my app with cordova, and when it runs in iphone6 plus, every thing looks larger than other apps.

**Comment by Hirbod** [comment]
Are you in zoomed mode on your iPhone 6 plus? This would cause the wrong ratios. And be sure you've set the meta tag no scalable and initial width etc

**Comment by Hirbod** [comment]
I've onsen running on iPhone 6 plus, everything looks great. Be sure to check that you are not in zoomed mode and you have set correct meta tags. Be careful: if you do not provide correct splash screens and app icons inside of your config.xml, iPhone 6 plus support won't be applied

**Comment by iVanPan** [comment]
I am in stand mode,and alert(window.innerWidth);alert(window.devicePixelRatio);,The value is 320 and 2.not 414 and 3 or 375 and 3.

**Comment by Hirbod** [comment]
What about your config.xml? Remember, when you don't provide @3 dpi icons for iPhone, the plus 6 support won't get applied

**Comment by iVanPan** [comment]
@Hirbod  tks, i find that it's launch images problem,it's ok now
