### ISSUE TITLE
Sliding menu: swipe-target-width is being ignored.

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#584]
An issue with v1.3 seems to have been introduced. The swipe-target-width property is being ignored.

**Comment by Hirbod** [comment]
Do you have a fast fix for this?

**Comment by argelius** [comment]
@Hirbod 

It's been fixed by this commit:
https://github.com/OnsenUI/OnsenUI/commit/c3e54adc124fe4797b2044d279ea7444edea2738
