### ISSUE TITLE
ons-sliding-menu + tabbar on specific page combination

### ISSUE THREAD

**Issue by JcDenton86** [OnsenUI/OnsenUI#587]
Hello, 
I am trying to combine sliding menu and tabbar. I am using as main navigation pattern the sliding menu component but in one of my pages (only on this page), I need to show a tabbar navigation at the bottom. In that page i've added the tabbar, but when I select this page from the sliding menu, onsen repeats rendering the page. This is how I am trying to do this:
http://codepen.io/anon/pen/zxQeVe (go to page 2)

In the link above it works fine (it renders only once) but on android similar code renders repeatedly the tabbar and the layout.. am I doing something wrong or it's onsen related issue? 
Thanks in advance

**Comment by JcDenton86** [comment]
Tried to add the tabbar outside of the `<ons-page>` element. Now it repeats rendering only the tabbar (not the rest of the layout - toolbar and content).

**Comment by JcDenton86** [comment]
Oh..! This is happening if I set `active="true"` for a tabbar item.

**Comment by argelius** [comment]
I cleaned up your code:
http://codepen.io/argelius/pen/jEoRKP

You need to put the tabbar inside the sliding menu main page and the reason why you got a lot of tab bars was that you were opening the page with the tab bar with one of your tabs.

**Comment by JcDenton86** [comment]
I see. Thank you
