### ISSUE TITLE
Optimization for masks and dialogs

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#589]
Hi @argelius 

since my app finally runs on Crosswalk, I've faced some ugly rendering issues, but they are fixed very quickly.

The dialog is often cutted or only rendered half. (sometimes the edges are missing).
The fix is very simple and  works also fine for non crosswalk projects.

Just change .dialog-mask and add these lines:

``` css

   -webkit-backface-visibility: hidden;
   -webkit-transform: translateZ(0);
   backface-visibility: hidden;
   transform: translateZ(0);

```

translateZ forces hardware accelarated rendering, backface-visibility fix the rendering issues (it will also work without translateZ, I guess it should be better to avoid translateZ as 4.3 has some ugly bugs with translateZ)

**Comment by argelius** [comment]
Thanks for these fixes, @Hirbod !

**Comment by Hirbod** [comment]
Actually, on crosswalk, this is a bug, not an enhancement. But you're welcome. (not on simulator, but real device)

**Comment by argelius** [comment]
Sorry, it's been relabelled as a bug now :)
Will take a look at it soon.
