### ISSUE TITLE
Android device back button instantly closes app, no history support

### ISSUE THREAD

**Issue by OpenNoob** [OnsenUI/OnsenUI#591]
Hi,

Before 1.3.0, in 1.1.4, I had no problem with the device back button. Working fine going back to previous pages /screens and only closes the app when it's the main page.

Now, in 1.3.0, hitting the device back button closes the app no matter which screen it's invoked.

Any fix?

Thanks!

**Comment by salztorte** [comment]
a fix for your Probelm:

            ons.setDefaultDeviceBackButtonListener(function(){
                    window.history.back();
            });


use this in ons.ready and this the default for your whole project.

I think that is no bug but only a change of the default functionality.

**Comment by michaeleparkour** [comment]
I didn't dive into the problem - just disable default handler. myNavigator is top ons.navigator, menu - slidingMenu variable.
<pre>
ons.ready(function(){
    ons.disableDeviceBackButtonHandler();
    window.document.addEventListener('backbutton', function() {
        console.log('back');
       if (myNavigator.pages.length > 1) {
           myNavigator.popPage();
       } else {
           menu.toggle();
       }
    }, false);
});
</pre>

**Comment by gtsopour** [comment]
The following code is working for me in 1.3.17.

```
        ons.disableDeviceBackButtonHandler();
        window.document.addEventListener('backbutton', function() {

           if (appNavigator.pages.length > 1) {
               appNavigator.popPage();
           } else {
                if (navigator.notification.confirm("Are you sure to close the app?",
                    function(index) {
                        if (index == 1) { // OK button
                            navigator.app.exitApp(); // Close the app
                        }
                    }
                ));
            }

        }, false);
```

Best
George

**Comment by mehdi-1514** [comment]
gtsopour and michaelparkour, I have tried both of your codes but it doesn't work for me

**Comment by mehdi-1514** [comment]
i have included in my onsenui.js:

ons.ready(function () {
    ons.disableDeviceBackButtonHandler();
    window.document.addEventListener('backbutton', function() {

           if (appNavigator.pages.length > 1) {
               appNavigator.popPage();
           } else {
                if (navigator.notification.confirm("Are you sure to close the app?",
                    function(index) {
                        if (index == 1) { // OK button
                            navigator.app.exitApp(); // Close the app
                        }
                    }
                ));
            }

        }, false);
