### ISSUE TITLE
ons-pull-hook and ons-if-platform problem

### ISSUE THREAD

**Issue by Sakura777** [OnsenUI/OnsenUI#593]
I would like to use ons-pull-hook only iOS in Phonegap.
What works well if I do ?

This code is not display content in ons-pull-hook (like span), but can pull and call action on all other than iOS. (on iOS, display content in ons-pull-hook.)

```
<ons-page>
<ons-pull-hook ons-if-platform="ios" ng-action="hoge($done)" var="loader">
    <span>...</span>
</ons-pull-hook>
...
</ons-page>
```

This code is can't pull and doesn't call action on all other than iOS.
But can't pull on iOS too, and make error log "ons-pull-hook must be a direct descendant of an ons-page or an ons-scroller element".

```
<ons-page>
<div ons-if-platform="ios">
<ons-pull-hook ng-action="hoge($done)" var="loader">
    <span>...</span>
</ons-pull-hook>
</div>
...
</ons-page>
```

**Comment by anatoo** [comment]
Hi @Sakura777,

Use `ng-disabled` directive like following code:
```
<ons-pull-hook ng-disabled="!ons.platform.isIOS()">
   ...
</ons-pull-hook>
```

**Comment by asial-matagawa** [comment]
This issue seems to have been solved.  Closing this.
