### ISSUE TITLE
GulpFile

### ISSUE THREAD

**Issue by d3orn** [OnsenUI/OnsenUI#596]
If I am building from the current master I only get a white screen on iOS. I believe the problem is in the build order. https://github.com/OnsenUI/OnsenUI/commit/831f67726a0a66f8270daf5d0e293a04d3b769cb this commit moved around a lot of files from lib to core (for example the winstore file still should be at the first place I think?)
I believe core.js should have the winstore at first place.
If I compare onsen_all.js from master with the one I built myself they look different. 
If I check out the console from iOS I get the following errors:
[Error] TypeError: Super expression must either be null or a function, not object
	_inherits (libs.js, line 3)
	(anonymous function) (libs.js, line 3)
	(anonymous function) (libs.js, line 3)
	global code (libs.js, line 3)
[Error] ReferenceError: Can't find variable: angular
	global code (app.js, line 1)

But only with the self build onsen_all.js, if I download the one from github everything works fine. 
I just saw the master has not been built for 12 days, that would explain the difference. Still I think the build process is somehow broken.

**Comment by anatoo** [comment]
Hi @d3orn,

I realized that the error is raised from code that [babel](https://babeljs.io) generated.
In safari, HTMLElement is not callable constructor. And babel raise an exception if super class is a function.
Thanks for your reporting. I'm going to fix this problem.
