### ISSUE TITLE
The `var` attribute should assign to the correct scope.

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#597]
```
<ons-list-item ng-controller="ItemController" ng-repeat="item in items">
  <ons-carousel var="carousel">
    ...
  </ons-carousel>
</ons-list-item>
```

`$scope.carousel` inside the `ItemController` will always be the final carousel.

**Comment by anatoo** [comment]
How about introducing "ons-scope" attribute?
If "ons-scope" attribute is presented, the children components is assigned on DOM's scope that have "ons-scope" attribute.
```
<div ons-scope>
  <ons-carousel var="carousel">
    ...
  </ons-carousel>
</div>
```

**Comment by argelius** [comment]
That's a good idea! This won't break compatibility and still can write code like this.

I also think you should be able to use `ons-scope` directive directly on the element:

```
<ons-carousel ons-scope var="carousel">
 ...
</ons-carousel>
```

**Comment by asial-matagawa** [comment]
`onsScope` directive is already implemented. Closing this.
