### ISSUE TITLE
New MutationObserver fails in WP

### ISSUE THREAD

**Issue by FragCoder** [OnsenUI/OnsenUI#599]
Hi, I'm working with latest (dev 1.3.1) release.
In windows phone I get the following error:
Unhandled exception at line 465, column 9 in onsenui.js
0x800a1391 - run-time error JavaScript: 'MutationObserver' not defined.

Including this js https://raw.githubusercontent.com/megawac/MutationObserver.js/master/dist/mutationobserver.min.js
seems fix the issue
Thanks

**Comment by anatoo** [comment]
Hi @FragCoder,

Thank you for your reporting.
We will fix this problem.

**Comment by anatoo** [comment]
@FragCoder 
I tested on Windows Phone 8.1 but can't reproduce. And browser has MutationObserver.
What version of Windows Phone are you using?

**Comment by FragCoder** [comment]
Windows Phone 10 Preview

**Comment by argelius** [comment]
That's interesting. Do you know what browser it's running? If it's IE11 it should have MutationObserver already. We will investigate this.

**Comment by argelius** [comment]
@FragCoder I will close this. Please open again if you feel this is a bug.
