### ISSUE TITLE
replace the angularjs to react native

### ISSUE THREAD

**Issue by wozzup** [OnsenUI/OnsenUI#600]
`OnsenUI` awesome!
but `angularjs` is sucks and meaningless. poor performance make developer pain.
replace the `angularjs` go forward to `react native` 
get better performance, make users and developers happy! winwin

**Comment by anatoo** [comment]
Hi @wozzup,

We are developing Onsen UI for Cordova/PhoneGap app. 
And React Native can't run on Cordova.
Thus we will never replace Angular to React Native.

If you mean that Onsen UI should be on not only Angular but also React.js, we will examine about it.

**Comment by wozzup** [comment]
Thanks Mr.@anatoo 
i knew currently react native can't run on cordova.
and monaca need phonegap/cordova.
but whatever the react native will need a UI framework like OnsenUI in future
https://facebook.github.io/react-native/docs/style.html#content
