### ISSUE TITLE
PullHook animation freezes for a moment when dragging back

### ISSUE THREAD

**Issue by frandiox** [OnsenUI/OnsenUI#604]
Drag PullHook down  and then up slowly again without releasing it:
http://codepen.io/onsen/pen/WbJogM

Tested in Chrome and Firefox.

Edit: Doing it several times in a row without releasing PullHook increase the error.

**Comment by argelius** [comment]
Thanks @frankdiox !

**Comment by misterjunio** [comment]
Fixed in v2 😄
