### ISSUE TITLE
ons-list isn't work on WP8

### ISSUE THREAD

**Issue by viniciusvelasco** [OnsenUI/OnsenUI#618]
Hi,
The list component is shown, but the scroll touch feature isn't responding on WP8. On IOS and Android works fine.

![image](https://cloud.githubusercontent.com/assets/2370740/7282105/c09cfe2e-e8fb-11e4-8aad-0974cc0bfc9b.png)

**Comment by argelius** [comment]
Thanks @viniciusvelasco ! We'll take a look at this.

In the meanwhile, could you try using the following rule?

```
touch-action: 'pan-y';
```

**Comment by viniciusvelasco** [comment]
Thanks @argelius !

isn't working. I will wait you solution

**Comment by digitsinmotion** [comment]
I'm experiencing this as well.

**Comment by argelius** [comment]
@viniciusvelasco @digitsinmotion 

This has been fixed in the latest development version. If you like please verify that it works now.
