### ISSUE TITLE
Unable to Use ons-navigator in multiple times in a page

### ISSUE THREAD

**Issue by nehulagr** [OnsenUI/OnsenUI#622]
Hello,

I have using OnsenUI from some days. I must say its pretty attractive and very light weight. I just love being as a developer to work on this. The best part is proper documentation. 

But there are certain issues which i am facing. Please have a look at this link for the reference. http://stackoverflow.com/questions/29861875/ons-navigator-multiple-navigator-in-one-page-template

and let me know is there any of my mistake or that is a bug?

**Comment by argelius** [comment]
Thanks!

Looks like you solved it so I'm closing this!
