### ISSUE TITLE
Any update on the GUI tool?

### ISSUE THREAD

**Issue by shaulhadar** [OnsenUI/OnsenUI#623]
Hi Argelius, how are you?

I wanted to know if there is any update on your upcoming GUI tool?

I really can't wait for it!!

Thanks :)

**Comment by argelius** [comment]
Hi @shaulhadar !

We're prioritizing some other things right now, so I'm not sure if and when we will make it.

**Comment by shaulhadar** [comment]
Thanks for the update Argelius!

**Comment by asial-matagawa** [comment]
The discussion seems to be done. Closing this.

**Comment by asial-matagawa** [comment]
Sorry, this is a feature request. I wlil reopen this.
