### ISSUE TITLE
"ons.notification.confirm" don't set cancelable variable , application close when push android back button key.

### ISSUE THREAD

**Issue by kuniakisuzuki** [OnsenUI/OnsenUI#624]
message: 'xxxx',
title: 'xxxxxx',
buttonLabels: ['cancel', 'yes'],
animation: 'default',
primaryButtonIndex: 1,

---
display confirm dialog , and application close when push android back button key.

---
message: 'xxxx',
title: 'xxxxxx',
buttonLabels: ['cancel', 'yes'],
animation: 'default',
primaryButtonIndex: 1,
cancelable: true,

---
set 'cancelable:true' is work fine.
but , 'cancelable:false' still close app.

**Comment by argelius** [comment]
Hi @kuniakisuzuki !

The `cancelable` parameter works as intended when I tried it on Android.

We'll consider changing the behavior when `cancelable` is `false`.
