### ISSUE TITLE
fontawesome icon twice issue.

### ISSUE THREAD

**Issue by teddie121** [OnsenUI/OnsenUI#625]
When i use font-awesome icons, it appears twice.

```
<i  class="fa fa-twitter"><i>
```

Anybody ever had something similar?

**Comment by argelius** [comment]
That's strange. With just the code above it displays two icons?
The tag in your code is not closed but I don't think that's the problem.

On what device and what browser is this happening?

**Comment by teddie121** [comment]
sorry. that's my mistake.

when i add style="font-weight:bold" , i can see twice issue.
