### ISSUE TITLE
I am finding issue with ons.enableAutoStatusBarFill()

### ISSUE THREAD

**Issue by nehulagr** [OnsenUI/OnsenUI#626]
Hello,

I am trying to use a controller normally. I am new to this onsen UI.

I have my custom.js file where i write all the angular code which i needed 

here is how i started it. 

var mod = ons.bootstrap('app', ['onsen']);
mod.controller('MyControler', function($scope) {
ons.ready(function() {
            // code inside...
    });           
});

I want to enableAutoStatusBarFill. How can i do that? I tried so many sources but couldn't get through it. And i looked all over that it comes a default but i can not see that in my application! 

Can you please help with this ? http://stackoverflow.com/questions/29905343/use-ons-enableautostatusbarfill-in-in-onsen-ui-with-angularjs  here is generated my issue also. But seems like no one else find this issue earlier. Am i doing something wrong!! 

Looking forward to hear from you. 
Thank you!

**Comment by argelius** [comment]
Hi it should be enabled by default on iOS 7 and iOS 8. What device are you using?

**Comment by nehulagr** [comment]
OK i got it solved. As i was making some mistake in cordova.js file calling. The file should be called before starting the other angular custom code.

 Now i am so happy! Lots of research made me do this. and now

**Comment by argelius** [comment]
I'm glad you were able to solve it! :)
