### ISSUE TITLE
Access navigator.pushPage from plain javascript

### ISSUE THREAD

**Issue by hipsterpercaso** [OnsenUI/OnsenUI#627]
Hi, I'm trying to open a page from plain javascript but it seems i can't make this work
I'm outside angular and outside the template script, because I'm receiving data from a third party plugin
somewhere in the documentation is written that i can access "var" element from the window object. I tried both 
my navigator is var="navi"
both this doesn't work
window.navi.pushPage
window.ons.navigator.pushPage

Here's my code. Any help?

var pushNotification = window.plugins.pushNotification;
    
    // Set push notification callback before we initialize the plugin
    document.addEventListener('push-notification',
        function(event) {
            var pushNotification = window.plugins.pushNotification;

            // Get the notification
            var notification = event.notification;

            // Display the notification
          //  navigator.notification.alert(notification.aps.alert,function() {console.log("Notification success")},"Notification","Close");

            // View full push payload
            alert(JSON.stringify(notification));
            window.ons.navigator.pushPage('detailpush.html', { eventid: "553f514286e060985bc1a601"});
            // Clear the App badge
            pushNotification.setApplicationIconBadgeNumber(0);
        }
    );

**Comment by argelius** [comment]
Hi!

`ons.navigator` has been deprecated but if you use the `var` attribute you should be able to use the `window.navi` object.

**Comment by hipsterpercaso** [comment]
You are right, I can access it, thanks, we can mark this as solved :)
