### ISSUE TITLE
navigator and tabbar issue

### ISSUE THREAD

**Issue by JcDenton86** [OnsenUI/OnsenUI#631]
Trying to do the following but I get "Page not found error" for only one tab item. Is this a bug or something else?

http://codepen.io/anon/pen/aOOpQq

The concept is that i am trying to navigate to a page that has a tab bar with 3 items but i am getting the exact error. The navigator pushes the page but if you try to go to `Comments` tab then the error is thrown (this is happening for just one tab).

Thanks in advance

**Comment by argelius** [comment]
Hi @JcDenton86 !

You've missed closing a `<ons-template>` tag and an `<ons-page>` tag. It works fine when they're closed:
http://codepen.io/argelius/pen/JddEzZ

**Comment by JcDenton86** [comment]
Sorry wrong URL. I' ve seen that error and fixed it but I am having the same issue.
See this URL please.. http://codepen.io/anon/pen/aOOpQq

**Comment by argelius** [comment]
This had some unclosed tags as well.
http://codepen.io/argelius/pen/GJJWKV

**Comment by JcDenton86** [comment]
I was adding the closing tags at the end rather than after the tabbar declaration. One more thing, can you please tell me how the same can be done, if the files are separated (the page with the navigator is different than the page with the tabbar)?.. (because I am getting the same error for the Videos tab no matter what I've been trying..)

**Comment by argelius** [comment]
It shouldn't be any difference using separate files from using templates. Just name the files the same as the templates in the example above and it should work.

http://plnkr.co/ supports separate files so you can make an example there if it doesn't work out.

**Comment by JcDenton86** [comment]
Thanks Argelius. I' ll try an example on Plunker and post back

**Comment by JcDenton86** [comment]
Hi Argelius. I' ve created a Plunker, but it seems that something is wrong and doesn't work as expected. The Plunker URL is http://plnkr.co/edit/S5pRTTRsUHGJSOVv3tOL?p=preview. I've loaded Onsen UI packet and created two files that have the same code from Codepen but I get "navigator is not defined" error.

**Comment by JcDenton86** [comment]
I managed to make it work. I should have wrapped the whole html file in a `ons-template` tag and the tabbar decleration in a `ons-page` tag. Thanks anyway for your support!

**Comment by argelius** [comment]
No problem! If you have any other questions don't hesitate to ask! :)
