### ISSUE TITLE
Unable to scroll page over ons-carousel ( Horizontal carousel )

### ISSUE THREAD

**Issue by aneesv** [OnsenUI/OnsenUI#632]
Unable to scroll page over ons-carousel ( Horizontal carousel ) , i have multiple small carousel(Horizontal) on a page  and scroll page up or down above carousel is not working

**Comment by argelius** [comment]
@aneesv 

Sorry for the late reply. I was on vacation until yesterday. We will investigate this.

**Comment by MateuszWilk** [comment]
Simillar here, although the ons-list (with ons-carousels, horizontal once) scrolls up and down flawless on iOS but is impossible to scroll on android (5.1.1). Got the same behavior without carousels but with ng-hold on ons-list-items.

**Comment by ramingar** [comment]
Same behaviour here. When you use a ons-carousel (horizontal), vertical scroll doesn't work in any version of android. It seems ons-carousel prevents other touch event.

**Comment by andipavllo** [comment]
I tried on Android 5.0 and 5.1 and it works. I guess it will be the same i 5.1.1

@MateuszWilk can you please provide an example?

**Comment by ramingar** [comment]
For my part, I'm trying with this code:

```html
<article ng-repeat="feed in results._embedded.feeds">
    <ons-carousel style="height: 100px; width:100%" initial-index="1"
    auto-refresh overscrollable swipeable auto-scroll auto-scroll-ratio="0.2">
        <ons-carousel-item>
            <div>SURPRISE!!!</div>
        </ons-carousel-item>
        <ons-carousel-item>
            <ng-include src="'templates/feeds/feed-list.html'"></ng-include>
        </ons-carousel-item>
    </ons-carousel>
</article>
```
 In this example: http://codepen.io/onsen/live/emmKpV/ happens too.

Test on Chrome, Android 4.2.2, Android 4.4.2, Android 5.1.1
Works on Android 4.4.2

**Comment by argelius** [comment]
@ramingar Are you using Crosswalk or native WebView?

**Comment by ramingar** [comment]
Native WebView.

Devices:
Android 4.2.2 = Samsung Galaxy S1, Wiko Rainbow
Android 4.4.2 = BQ Aquaris E5 (it works in this device)
Android 5.0.1 = AVD
Android 5.0.2 = MOTO G
Android 5.1.1 = OnePlus ONE

**Comment by argelius** [comment]
Thanks @ramingar ! We will investigate this.

**Comment by ramingar** [comment]
Don't mention it. Actually, I have the greatest interest in seeing this functionality works XDD

**Comment by argelius** [comment]
@ramingar: This has been fixed in the master branch. We will also release a new patch version with this fix (1.3.7).

Could you try it out and see if it works as expected?

**Comment by ramingar** [comment]
Tested [c2fbb68](https://github.com/OnsenUI/OnsenUI/commit/c2fbb6848e638a87524a5e13a66a9ad36b84d27f) on Chrome, Android 4.2.2, Android 4.4.2, Android 5.0.1, Android 5.1.1 using native webview and Crosswalk. I can confirm it works perfectly on all tests.

Thanks a lot for such a fast fix.

**Comment by andipavllo** [comment]
@ramingar you are welcome, let us know if you have any other issue :)
