### ISSUE TITLE
Dialog's parentScope issue

### ISSUE THREAD

**Issue by zhipeng-jia** [OnsenUI/OnsenUI#634]
I create a dialog using `ons.createDialog` and assign `parentScope` in options with current `$scope`.
I have a variable that I want to use with `ng-model` in the dialog, and the variable exists in the current `$scope`. However, I find that I should use `$parent.$parent.varaible` to refer to my variable in `ng-model`. I expect `$parent.variable` works since this meets the meaning of parentScope.

To illustrate the issue more clearly, I will give parts of my code.
This is my dialog `change-nickname.html` (just omit the Chinese characters in it)
~~~HTML
<ons-dialog class="change-nickname-dialog">
  <ons-toolbar inline>
    <div class="center">修改昵称</div>
  </ons-toolbar>

  <div class="nickname-input">
    <!-- It seems that $parent.$parent is the parentScope that we specify in createDialog's options  -->
    <input type="text" class="text-input text-input--underbar" placeholder="新昵称" ng-model="$parent.$parent.newNickname">
  </div>

  <ons-bottom-toolbar>
    <div class="buttons">
      <button class="button button--quiet" ng-click="changeNickname()" ng-disabled="waitingSubmit">确定</button>
      <button class="button button--quiet" ng-click="changeNicknameDialog.hide()" ng-disabled="waitingSubmit">取消</button>
    </div>
  </ons-bottom-toolbar>
</ons-dialog>
~~~

and this is part of my controller
~~~JavaScript
  var changeNicknameDialog;
  $scope.showChangeNicknameDialog = function () {
    $scope.newNickname = AV.User.current().get('nickname');
    if (changeNicknameDialog) {
      changeNicknameDialog.show();
    } else {
      ons.createDialog('user/change-nickname.html', {
        parentScope: $scope
      }).then(function (dialog) {
        changeNicknameDialog = dialog;
        $scope.changeNicknameDialog = dialog;
        dialog.show();
      });
    }
  };
~~~

Forget to say, I'm using OnsenUI 1.3.1.

**Comment by argelius** [comment]
Hi @zhipeng-jia ! Thanks for the feedback.

I think this works as expected. If you have `ng-model="somevar"` in a ancestor scope it will change all its descendant scopes as well. However, if you use `ng-model="somevar"` in a descendant scope it will not change its ancestor scopes.

If you want it to change please use an object instead. You can do something like `ng-model="data.newNickname"` and it will work.

If you still think there is a problem  please create a codepen example that reproduces the issue.

**Comment by zhipeng-jia** [comment]
Here is a demo on Codepen: http://codepen.io/zhipeng-jia/pen/MwazNj.

Change text in the input and click show button to see the value (in the context of DialogController). I expect Dialog1 works.

**Comment by argelius** [comment]
I've updated your example:
http://codepen.io/argelius/pen/mJeada

If you use an object and bind the parameters to it it will work fine.

**Comment by zhipeng-jia** [comment]
I see. I think I have some misunderstanding with Angular's scope chain.
Thanks very much.

**Comment by argelius** [comment]
No problem! I think it can be confusing as well :)
