### ISSUE TITLE
[iOS] Bug for input tag with placehoder - unable to view other pieces

### ISSUE THREAD

**Issue by yujilow1220** [OnsenUI/OnsenUI#635]
Hello. 

I found a bug. 

I wrote this html using OnsenUI. The html is here:

```
<ons-page ng-controller="PageController" style="background-color: #1d5f9f;">
    <!-- Page content -->
    <h2 class="title">Title</h2>
    <p><input type="text" class="text-input" placeholder="Name" /></p>
    <ons-button modifier="outline" style="background-color: #44aa44;">Create</ons-button>
          <div id="footer">
      <ons-button><ons-icon icon="fa-bars"></ons-button>
  </div>
  </ons-page>
```

Then, I watched this page on iPhone 5s (iOS 8.3).
When I typed within input, Title and input and "create" button went out of sight.
This issue was disappear when I deleted placeholder or changed input tag to textarea tag.
And, this issue did not occur on Android and PC.

I hope this bug will be fixed.

**Comment by argelius** [comment]
Thanks @yujilow1220 !

We will investigate this.

**Comment by zack24q** [comment]
@argelius i think i fixed this bug, i add this style `.page__content {
  -webkit-overflow-scrolling: auto;
}` to override that style `.page__content {
  -webkit-overflow-scrolling: touch;
}` of onsenui.css, and this bug has not reproduce again.
But in ios, this change will make system do not use UIScrollView to render.
