### ISSUE TITLE
[WP 8.1] Vertical swipe and scroll touch event bug

### ISSUE THREAD

**Issue by andipavllo** [OnsenUI/OnsenUI#639]
The vertical swipe and scroll touch events seem not being recognised, but the functionalities seem working fine.

**Comment by argelius** [comment]
@andipavllo Can you explain this and give an example?

**Comment by andipavllo** [comment]
I added a listener on the touch events, all the events are recognised, except the vertical touch events, like scrolling and swiping. Despite that, the vertical touch actions seem working.

**Comment by argelius** [comment]
I need  an example that reproduces the issue.

**Comment by asial-matagawa** [comment]
Now we are no longer supporting Windows Phone 8.1 and older devices.
Closing this.
