### ISSUE TITLE
Push directly the page that hosts the parent navigator

### ISSUE THREAD

**Issue by gtsopour** [OnsenUI/OnsenUI#647]
Is there any way to push directly the home page that hosts the parent navigator directly from an other page?

**Comment by argelius** [comment]
Hi! Do you mean popping to the first page?

You can use `navigator.resetToPage('page.html')` to reset to a specific page. The page stack will be removed.

**Comment by gtsopour** [comment]
Hello @argelius 
thank you for contacting me. When I am doing that, I am receiving this error:

Error: You can not supply no "ons-page" element to "ons-navigator".
    at Class.module.factory.Class.extend._createPageElementAndLinkFunction (onsenui_all.js:35126)
    at Class.<anonymous> (onsenui_all.js:35256)

Best
George

**Comment by gtsopour** [comment]
The only workaround that I found, as I am using the sliding menu pattern, is the following 
menu.setMainPage('home.html', {animation: 'slide'});

**Comment by frankdiox** [comment]
Hey George, how is it going :)

That's the normal way to do it with the sliding menu pattern. Do you have any problem with that?
Regarding the navigator error, <ons-navigator> always needs an <ons-page> as a child, otherwise it will throw that error.

**Comment by gtsopour** [comment]
Hello Fran,
nice to hear from you and thanks for everything you have done for me.

I got it. So, Fran is there any way to use any animation during menu.setMainPage('home.html', {animation: 'slide'}) because the slide animation in my case does not work.

Best 
George

**Comment by frankdiox** [comment]
Let's continue this conversation in #648  since it seems to be the same issue.
