### ISSUE TITLE
Carousel Bug - Changing items with ng-repeat issue

### ISSUE THREAD

**Issue by oransel** [OnsenUI/OnsenUI#651]
It seems like the carousel caches the items it has. After changing the children, it still applies layout to the old children.

https://github.com/OnsenUI/OnsenUI/blob/a7e9bc7e863061b7d431f6d39d0c1934fd2eaad3/framework/views/carousel.js#L606

**Comment by argelius** [comment]
Thanks! We'll look into this.

@oransel Could you make an example on Codepen and describe the expected behavior?

**Comment by oransel** [comment]
http://codepen.io/anon/pen/bdpaMb

Click the switch it button and all the items disappear. If you were to comment out the 3 lines starting from 606, then the cache is disabled and it works.

**Comment by argelius** [comment]
@oransel This has been fixed now. Thanks for the bug report.
