### ISSUE TITLE
ons platform for android tablet

### ISSUE THREAD

**Issue by JcDenton86** [OnsenUI/OnsenUI#653]
`ons.platform` is useful to identify a device. It would be nice if there was an extra method to check if it's android phone or tablet (like you have for iPhone and iPad).

**Comment by argelius** [comment]
@JcDenton86 That's a good idea! We'll consider this.

**Comment by JcDenton86** [comment]
Based on the assumption that an Android mobile device has the word `Mobile` in the user agent string while an Android tablet doesn't, I created two functions that return true or false accordingly.
```
isAndroidPhone: function isAndroidPhone() {
      return /Mobile/i.test(navigator.userAgent);
   },

isAndroidTablet: function isAndroidTablet() {
     return !/Mobile/i.test(navigator.userAgent);
   },
```
That's how I am doing it right now (until you add it in Onsen)

**Comment by argelius** [comment]
Since you already wrote the code, please feel free to submit a pull request
:)
2015/05/14 20:14 "JcDenton86" <notifications@github.com>:
