### ISSUE TITLE
Rendering on amazon-fireos device not correct

### ISSUE THREAD

**Issue by paulhovey** [OnsenUI/OnsenUI#656]
I may be one of the crazy few with an Amazon Fire phone, but nonetheless, I have one.  Here is an example of a login screen with an `ons-toolbar` at the top:

On Android:  ![android](http://i.imgur.com/5adeY6B.png)
On Amazon-fireos: ![amazon-fireos](http://i.imgur.com/egTzyZh.png)

As you can see, the `ons-toolbar` isn't rendering properly on amazon-fireos devices.  That's just one example, it seems the view structure gets messed up somehow on the amazon-fireos platform when it works fine on android platform.  I know it's not a high-priority issue, but wanted to make the issue known.

**Comment by argelius** [comment]
Thanks @paulhovey !

Actually we have no plans to support FireOS right now. Right now we are focusing on iOS, Android and Windows Phones.

Of course we would appreciate pull requests that fix issues on FireOS.
