### ISSUE TITLE
ons-page and directives

### ISSUE THREAD

**Issue by rlloyd2001** [OnsenUI/OnsenUI#658]
What I'm finding is that if I place a directive in an ons-page, it cannot be the first child element of the ons-page.  The only directive that works as the first element of an ons-page is the ons-toolbar. Using version 1.3.0.

For example, this works:
\<ons-page\>\<ons-toolbar /\>\<all elements here OK\>\</ons-page\>.

This does not work:
\<ons-page\>\<some-other-directive /\>\<all elements here lost\>\</ons-page\>

**Comment by frankdiox** [comment]
I cannot reproduce the problem. It's working as usual: http://codepen.io/frankdiox/pen/QbEgwO

Could you please provide an example where it does not work? Thanks!
