### ISSUE TITLE
typeof selectedTabItem.isPersistent() is always 'true'

### ISSUE THREAD

**Issue by dsuket** [OnsenUI/OnsenUI#661]
https://github.com/OnsenUI/OnsenUI/blob/master/framework%2Fviews%2FtabbarView.js#L247
`typeof selectedTabItem.isPersistent()`  seems to be always `true`, so `selectedTabItem.isPersistent()` returns `boolean`.
https://github.com/OnsenUI/OnsenUI/blob/master/framework%2Fdirectives%2Ftab.js#L218
maybe, typeof is duplicated?

**Comment by argelius** [comment]
Thank you @dsuket ! I will fix this.

**Comment by argelius** [comment]
@dsuket This has been fixed now. Thanks for reporting!
