### ISSUE TITLE
Android back button

### ISSUE THREAD

**Issue by PrabhdeepSingh** [OnsenUI/OnsenUI#669]
Running latest build onsenui - v1.3.3-dev-build.537 2015-05-21 and having issues with the back button on Android running on Lollipop
![screen shot 2015-05-22 at 1 43 13 am](https://cloud.githubusercontent.com/assets/5160454/7764774/23f6c9ca-0024-11e5-994a-4c68992d2889.png)

Was able to fix the above error by changing isIOS7above: function isIOS7above() to isIOS7Above: function isIOS7Above() on line 3850 in onsenui.js. But ended up getting this error:
![screen shot 2015-05-22 at 11 31 55 am](https://cloud.githubusercontent.com/assets/5160454/7774026/3d86935a-0076-11e5-9437-c9b973339ea9.png)

**Comment by PrabhdeepSingh** [comment]
After doing some debugging, I was able to fix the issue by removing the following code from framework/views/page.js

````javascript
if (this._element[0].getDeviceBackButtonHandler()) {
    this._element[0].getDeviceBackButtonHandler().destroy();
}

**Comment by PrabhdeepSingh** [comment]
That's not a true fix but does make the back button functional again.

**Comment by argelius** [comment]
Thanks @PrabhdeepSingh ! We will fix this bug.

**Comment by PrabhdeepSingh** [comment]
No worries! Also by removing the code I said above causes issues on iOS devices. Added code back and iOS device work perfect but the back button stops functioning.

**Comment by frankdiox** [comment]
Thanks @PrabhdeepSingh ! It was actually a spelling error in `isIOS7above` method. "Above" should be lowercase!
