### ISSUE TITLE
Onsen UI 1.3.0 App not working on Windows Phone at all using Phonegap developer app

### ISSUE THREAD

**Issue by danish-jamil** [OnsenUI/OnsenUI#672]
Build is also not working. I tried to install .xap in widows device but was unable to install.

**Comment by frankdiox** [comment]
@danish-jamil Could you please provide code, error logs or anything where we can see the problem?  Thanks.

**Comment by danish-jamil** [comment]
Using phonegap developer app lists were not scrolling. I was unable to debug and log the errors. But After a successful build, It's working. But the UI is too small windows phone.

**Comment by andipavllo** [comment]
@danish-jamil this issue has been fixed with Onsen UI 1.3.1, as you can see from the [changelog](https://github.com/OnsenUI/OnsenUI/blob/master/CHANGELOG.md).
