### ISSUE TITLE
Flickering issues when transitioning pages with textarea

### ISSUE THREAD

**Issue by andreupifarre** [OnsenUI/OnsenUI#674]
If I delete all the textarea fields in a page, the transition is smooth, otherwise it flickers at the end of the transition. I am using Monaca IDE.

**Comment by argelius** [comment]
Thanks for reporting @andreupifarre. We will investigate this.

**Comment by andipavllo** [comment]
More info in [this](http://stackoverflow.com/questions/30415088/flickering-issues-when-transitioning-pages-with-textarea-fields-in-onsen-ui-ph) Stackoverflow post

**Comment by frankdiox** [comment]
@andreupifarre I am not able to reproduce this error. Could you provide a full example where this happens and the platform that you use? I've tried with the information provided in SOF but still I cannot see it.

**Comment by andreupifarre** [comment]
My bad sorry, I got confused about spreading templates into different .html files, I included the <body> tag in all of them as I couldn't find any example of how to do so. I removed the tags and transitions now are incredibly smooth. Thank you.
