### ISSUE TITLE
Upgrading onsen ui to 1.3.2 casusing Multiple directives issue

### ISSUE THREAD

**Issue by manishparakhiya** [OnsenUI/OnsenUI#675]
Hi,
i had upgraded onsen ui to 1.3.2 and since i am getting following error.

Error: [$compile:multidir] Multiple directives [ngController, onsPage] asking for new/isolated scope on: <ons-page ng-controller="appController">
http://errors.angularjs.org/1.3.0/$compile/multidir?p0=ngController&p1=onsPage&p2=new%2Fisolated<ons-navigator class="ng-scope" var="appNavigator" animation="slide">cope&p3=%3Cons-page%20ng-controller%3D%22appController%22%3E

Here is my Html

```
<html lang="en" ng-app="app">
  <head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="lib/onsen/css/onsenui.css"/>
    <link rel="stylesheet" href="lib/onsen/css/onsen-css-components.css"/>
    <script src="lib/onsen/js/angular/angular.js"></script>
    <script src="lib/onsen/js/onsenui.js"></script>
    <script>
      var application= ons.bootstrap('app', ['onsen']);
application.controller('appController', function () {        
        if (window.localStorage.getItem("LoggedUser"))
            appNavigator.pushPage("home.html");
        else
            appNavigator.pushPage("login.html");
    });
</script>
<body >
    <ons-navigator var="appNavigator" animation="slide">
        <ons-page ng-controller="appController"></ons-page>
    </ons-navigator>    
</body>
</html>
```

**Comment by argelius** [comment]
Hi @manishparakhiya !

Could you please make an example on Codepen that reproduces this bug?
