### ISSUE TITLE
The delegate function calculateItemHeight() of ons-lazy-repeat not correct, the argument mostly undefined

### ISSUE THREAD

**Issue by zack24q** [OnsenUI/OnsenUI#678]
when I use ons-lazy-repeat, I found the argument of the function calculateItemHeight() mostly undefined. I look at the source code and I found [onsenui.js#L10920](https://github.com/OnsenUI/OnsenUI/blob/master/build/js/onsenui.js#L10920) is `var h = this._getItemHeight();`Is this code missing argument i? I think `var h = this._getItemHeight(i);` is correct.

**Comment by argelius** [comment]
Hi @zack24q !

You need to define function in your delegate object.

**Comment by zack24q** [comment]
Hi @argelius !
I have define function in my delegate object. Can you see the console of my [codepen](http://codepen.io/zack24qq/pen/mJOVPm)? It is onsen docs 's code.

**Comment by argelius** [comment]
Thanks! This looks like a bug. I will fix it.
