### ISSUE TITLE
<ons-screen , is not supporting with v1.3.2

### ISSUE THREAD

**Issue by DILEEP-YADAV** [OnsenUI/OnsenUI#681]
<ons-screen , is not supporting with latest version of onsen ui, This tag working with old version perfect, How to implement Login , Registration , Home according to #http api call auth. Angular js Routing is not supporting. Please help us for further use Onsen ui.

**Comment by argelius** [comment]
Hi! 

@DILEEP-YADAV You can use `<ons-navigator>` instead to get the same effect. Please check the docs.

**Comment by DILEEP-YADAV** [comment]
I have done with   https://github.com/DILEEP-YADAV/OnsenUI-Memo-App.
Thanks  @argelius
