### ISSUE TITLE
"title" property of ons-navigator doesn't support responsive/multi-lined title

### ISSUE THREAD

**Issue by Asit1989** [OnsenUI/OnsenUI#683]
I am using the following code for title in my mobile app.
< ons-navigator 
	title={{myTitle}}
	left-button-icon="fa fa-bars fa-lg fa-lg"
	on-left-button-click="ons.slidingMenu.toggleMenu()"
	page="abc/page.html">	
</ons-navigator>

But when I get larger text for title, it is rendering ellipsis instead of full text. I am unable to get a multi-lined title in my app, whatever css changes I do. Onsen-css-library contains:
.onsen_navigator-title {
  width: 70%;
  left: 15%;
  text-overflow: ellipsis;
  white-space: nowrap;
  overflow: hidden;
}

[ Example: 
Say 'Testing There my Title' is the title(myTitle).
It is displayed in iPhone as 'Testing There m...'. It would be better if i could get a double lined title instead.

Is it an issue with onsen ui or is there any solution?

**Comment by argelius** [comment]
Hi @Asit1989 !

I don't really understand what you are trying to do. Do you want the text size to automatically decrease if the content is more than one line? This is not supported so you would need to write some code if you want to do this.
