### ISSUE TITLE
Disabled attribute not working as intended after upgrading to onsen 1.3.2

### ISSUE THREAD

**Issue by 0505gonzalez** [OnsenUI/OnsenUI#692]
We just upgraded onsen from 1.2.x to 1.3.2. 

Before, disabled="true" and disabled="false" used to work fine on ons-button, but that's no longer the case. Now, the button is disabled regardless of the boolean value. The online example uses disabled in the same way we do. 

Is this a bug or is there a change we need to make to get this working? Is there a migration guide if this is intended behaviour?

Note that we're using this with angular in the following way:

```
<ons-button modifier="quiet" disabled="{{ isFormFilledIn }}" ng-click="submitLoginCredentials()">Sign In</ons-button>
```

**Comment by argelius** [comment]
Hi @0505gonzalez !

The previous behavior was a bit strange so now it will be disabled if it has the `disabled` attribute regardless of its value. So now you can use `ng-disabled` instead:

```
<ons-button ng-disabled="!isFormFilledIn">Sign in</ons-button>
```

Sorry about the breakage but I believe this is a more consistent behavior. If you have any other questions don't hesitate to ask.
