### ISSUE TITLE
getActiveCarouselItemIndex() not updating when swiping through carousel

### ISSUE THREAD

**Issue by boxbag** [OnsenUI/OnsenUI#697]
I made a codepen to demonstrate this behavior. When a user swipes, I thought that the code below should update the item index but it does not.

```
<ons-carousel-item style="background-color: #085078;">
        <div class="item-label">{{carousel.getActiveCarouselItemIndex()}}</div>
</ons-carousel-item>
```

http://codepen.io/anon/pen/xGgVXd

Am I missing something here?

**Comment by frankdiox** [comment]
I think the only problem there is that Angular does not detect the value changes. Perhaps this could be useful to understand why: http://stackoverflow.com/a/15424144/4468962
Anyway, you can simply use <a href="http://onsen.io/reference/ons-carousel.html#attributes">Carousel's `postchange` event</a> to make a change in the scope and Angular will update it: http://codepen.io/frankdiox/pen/WvRxww

**Comment by boxbag** [comment]
Thanks for the help
