### ISSUE TITLE
Button in ons-carousel-cover not Clickable

### ISSUE THREAD

**Issue by boxbag** [OnsenUI/OnsenUI#699]
I'm experiencing an issue getting a button in the `<ons-carousel-cover>` element to be clickable.

http://codepen.io/anon/pen/WvROxw

**Comment by argelius** [comment]
Hi @boxbag !

Sorry for the late reply. Did you change the codepen? The button is clickable for me.

**Comment by boxbag** [comment]
Yes I changed it, I'm not using the `ons-carousel-cover` anymore. I'm just using a fixed div to the bottom
