### ISSUE TITLE
iOS tryToFillStatusBar issue

### ISSUE THREAD

**Issue by PrabhdeepSingh** [OnsenUI/OnsenUI#701]
Running the latest dev build on iOS 8.3 and get the following error when launching the application.
![screen shot 2015-05-30 at 3 22 36 pm](https://cloud.githubusercontent.com/assets/5160454/7898978/d332d714-06df-11e5-9501-b9ac9c7655c4.png)

**Comment by frankdiox** [comment]
@PrabhdeepSingh Thanks for reporting! We will investigate this.

**Comment by PrabhdeepSingh** [comment]
Sweet! I wasn't sure if you guys fully implemented those functions in the new 1.3.3 or not so submitted an issue.

**Comment by frankdiox** [comment]
The functions were just moved to CustomElements and looks like for some reason it is loaded after Angular so the functions are not created on time :(
This has been fixed in <a href="https://github.com/OnsenUI/OnsenUI/tree/fix-custom-elements-timing">this branch</a>. 
Thanks @PrabhdeepSingh !
