### ISSUE TITLE
<ons-pull-hook> as a direct descendant of <ons-scroller> seem not correct

### ISSUE THREAD

**Issue by zack24q** [OnsenUI/OnsenUI#707]
I put "ons-pull-hook" as a direct descendant of "ons-page", it works fine. But when i need to put "ons-pull-hook" in "ons-scroller", it seem not correct. Here is my operation,first i scroll the list to the bottom, so the list's postion is bottom, then i scroll the list up with mouse(not wheel), the “pull-to-refresh” behavior has been triggered. I think the “pull-to-refresh” behavior should be triggered only the list's postion is top. please see my [codepen](http://codepen.io/zack24qq/pen/QbpWEj). Thanks!

**Comment by zack24q** [comment]
I add the style `ons-scroller {
  height: 100%;
}
.ons-scroller__content {
  height: 100%;
  overflow: scroll;
}` and solve this problem temporally. I hope this code will help you to fixed that problem.

**Comment by argelius** [comment]
Thanks @zack24q ! We will check this out. 

If this solves the bug, don't hesitate to create a PR with the changes.

**Comment by zack24q** [comment]
OK, I will.
