### ISSUE TITLE
ons-lazy-repeat fails to get the first component of JSON

### ISSUE THREAD

**Issue by AndikaR** [OnsenUI/OnsenUI#709]
I was trying to create a custom list using JSON and notice that the first component was missing on first row. Here is my code:
http://codepen.io/AndikaR/pen/NqpGZd
Could you help me with this issue? 

Thank you

**Comment by frankdiox** [comment]
Hello @AndikaR ! Your first row is actually displayed under the search bar. You are using the CSS for the toolbar and search bar but you are not reducing the space of the page content. This will make it: https://stackoverflow.com/questions/29673755/onsen-multiline-toolbar/29689371#29689371

Hope it helps!
