### ISSUE TITLE
ons-pull-hook does not play well with ons-tabbar/templates

### ISSUE THREAD

**Issue by zumbrunnen** [OnsenUI/OnsenUI#715]
Please have a look at this Codepen: http://codepen.io/anon/pen/gpmGoz (it's a fork from Onsen's Pull Hook demo: http://codepen.io/onsen/pen/WbJogM ). I've added a tab bar and thus the content is in the templates defined outside the `ons-page`.

The issue is: When using `ons-pull-hook` together with templates (for example via `ons-tabbar`), the reloaded content vanishes/gets invisible.

Cause for the invisibility is a CSS transition that get's attached to the `div#scroll`:

```html
<div class="scroll" data-animit-orig-style="" style="-webkit-transition: all 0.3s cubic-bezier(0.1, 0.7, 0.1, 1); transition: all 0.3s cubic-bezier(0.1, 0.7, 0.1, 1); transform: translate3d(0px, 0px, 0px);">
....
</div>
```

**Comment by argelius** [comment]
Thanks @zumbrunnen ! I'm really sorry for the late reply.

Yes, it looks like the element isn't displayed because of the translation. I will try to fix this.

**Comment by argelius** [comment]
Hi again @zumbrunnen !

Actually I don't think this is an issue. You should put the pull hook inside the tabbar page and it will work fine.

I forked the example and made a simple change:
http://codepen.io/argelius/pen/VLyQmG

**Comment by zumbrunnen** [comment]
Thanks @argelius! Repositioning the pull hook is OK for us. So this can be seen as "no issue".
