### ISSUE TITLE
Prevent scrolling while swiping on ons-list-item

### ISSUE THREAD

**Issue by andreupifarre** [OnsenUI/OnsenUI#724]
Currently, if you are swiping to the left on an onsen-item-list using a ons-gesture-detector, the list scrolls vertically. This behavior is really annoying it reduces the usability.

Is there a way to prevent scrolling the content/list while the user swipes on an onsen-item-list?

ionic framework does this: http://forum.ionicframework.com/t/prevent-scrolling-while-swiping-on-ion-item/14708

**Comment by salztorte** [comment]
I dont have the problem.
If you only swiping left or right the list dont move but if you swipe diagonal the list move.

i think this is a normal behavior.

**Comment by argelius** [comment]
@salztorte @andreupifarre 

It seems like this behavior is only present on Mobile Safari. @andreupifarre are you using iOS?

I've added an `lock-on-drag` attribute to `<ons-list-item>`. Please check it out. If there's no problem we will merge it shortly.

**Comment by andreupifarre** [comment]
Yes I am using iOS.

Could you please let me know how to test this new "lock-on-drag" attribute? Do I have to update any files in order to make it work? I have already added <ons-list-item lock-on-drag="true" >

Thank you.

**Comment by frankdiox** [comment]
@andreupifarre You can clone this branch with:
`git clone https://github.com/OnsenUI/OnsenUI.git -b lock-on-drag-attribute`
And then follow the rest of the guide: https://github.com/OnsenUI/OnsenUI#how-to-build
