### ISSUE TITLE
Tabbar sliding animation bugged in dev 1.3.3

### ISSUE THREAD

**Issue by andipavllo** [OnsenUI/OnsenUI#732]
The tabbar sliding animation doesn't work on dev 1.3.3. It also bugs the tabbar, adding a new page to the stack everytime the tab will be changed.

**Comment by anatoo** [comment]
Ok, I'm going to investigate and fix this issue.

**Comment by andipavllo** [comment]
Thank you @anatoo ! I teste it on last chrome release and `demo/tabbar/index.html` demo.

**Comment by anatoo** [comment]
Fixed on https://github.com/OnsenUI/OnsenUI/commit/9476878e0af8d533fd8a9b195b40a86dfbe225a0.
