### ISSUE TITLE
Tapping a list with checkboxes is causing the handler function to be called twice

### ISSUE THREAD

**Issue by filipefreitas82** [OnsenUI/OnsenUI#733]
Here is a code sample:

HTML:
>ons-list>
>     ons-list-item ons-lazy-repeat="AccountDelegate" ng-click="selectAccount(item)">
>       label class="checkbox checkbox--list-item">
>            input type="checkbox">
>            div class="checkbox__checkmark checkbox--list-item__checkmark"></div>
>            {{item.name}}
>        /label>
>    /ons-list-item>
>/ons-list>

JS controller:
>$scope.selectAccount = function(account) {
>       console.log('In');
>}

Is it a know bug?

**Comment by argelius** [comment]
Hi @filipefreitas82 ! Thanks for reporting.

I just tried with the latest build and wasn't able to reproduce this issue. Could you please create an example on Codepen?

**Comment by filipefreitas82** [comment]
@argelius 
I changed the codepen code for lazy repeat and added a checkbox:

http://codepen.io/anon/pen/qdpyWL

If I comment out the input tag of the checkbox everything works as expected.

**Comment by argelius** [comment]
Thanks @filipefreitas82 !

Looks like it isn't related to `<ons-lazy-repeat>`. This would happen for a normal list item as well.

The problem is that two click events are generated, one for the checkbox and one for the label. You can fix it by catching and stopping propagation for the checkbox event:

```html
<input ng-click="$event.stopPropagation()" ...
```

**Comment by filipefreitas82** [comment]
that's it. Thanks :)
