### ISSUE TITLE
Dose $new() cause memory leak?

### ISSUE THREAD

**Issue by zhuangperola** [OnsenUI/OnsenUI#735]
@andipavllo @argelius 

When I create and show ons-dialog in my app, the destroy is finished. bug by Chrome Profiling, a closure of ChildScope is leak.

I debug the onsenui.js and found that this source probablily caused.

`ons.$compile(dialog)(options.parentScope.$new());`

I change these source and it don't happen anymore

`ons.$compile(dialog)(options.parentScope);`

The "$new" and "$compile" when create child scope and son' son scope, the son' son scope is used for dialog, and child scope is not released.

**Comment by zhuangperola** [comment]
ons-popover has the same problem too.

**Comment by argelius** [comment]
Thanks @zhuangperola ! We'll take a look at this.

**Comment by zhuangperola** [comment]
Hi @argelius 

Hi @frankdiox 

I don't understand compile well but I change the code to 

`ons.$compile(dialog)(options.parentScope);`

and it works well, Could you have a check of this code? Thanks.

**Comment by frankdiox** [comment]
@zhuangperola Thanks! Which version of Onsen UI are you using?

**Comment by zhuangperola** [comment]
@frankdiox 

/*! onsenui - v1.3.2 - 2015-06-03 */

**Comment by frankdiox** [comment]
@zhuangperola After several tests I haven't been able to find any memory leak related to ons-dialog. Perhaps you had something in your code that was affecting? Thanks anyway!

**Comment by argelius** [comment]
I will close this now. @zhuangperola If you can create a small example that reproduces this please send a link and reopen the issue.

**Comment by zhuangperola** [comment]
![snapshot](https://cloud.githubusercontent.com/assets/4699836/8445494/81d62dd0-1fd0-11e5-8eca-5a36f904282d.png)

**Comment by zhuangperola** [comment]
Hi @argelius 
Hi @frankdiox 

I am sorry for my late replay. 

I created the sample with cordova-cli, but I don't know how to send it to you. Could you offer you an email address, and then I could share it to you.

I found the memory leak in android phone. 

The version of lib I used is listed below

- onsen.min.js v1.3.2 2015-05-12
- angular.min.js v1.4.0
- cordova.js v3.6.4

The dialog's code is like this.

`<ons-dialog animation="none" var="messageAlertDialog">
    <ons-row align="left" class="alert-dialog-title" style="height: 50px">
        <ons-col>
            {{messageBox}}
        </ons-col>
    </ons-row>
    <ons-row style="padding: 5px 5px 5px 5px">
        <ons-button modifier="large"
                    ng-click="messageAlertDialog.destroy();">
            {{'OK'}}
        </ons-button>
    </ons-row>
</ons-dialog>`

The index.html is like this.

`<!DOCTYPE html>
<html ng-app="myApp">
    <head>
        <meta charset="utf-8" />
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="mobile-web-app-capable" content="yes">
        <link rel="stylesheet" href="lib/onsenui/css/onsenui.css">
        <link rel="stylesheet" href="lib/onsenui/css/onsen-css-components-blue-basic-theme.css"/>
        <script type="text/javascript" src="cordova.js"></script>
        <script type="text/javascript" src="lib/angular/angular.min.js"></script>
        <script type="text/javascript" src="lib/onsenui/js/onsenui.min.js"></script>
        <script type="text/javascript" src="index.js"></script>
        <title>Onsen Memory Test</title>
    </head>
    <body ng-controller="myCtrl">
    <ons-row style="height: 50px;padding: 5px">
        <ons-col>
            <ons-button modifier="large" ng-click="openDialog()">
                Open Dialog
            </ons-button>
        </ons-col>
    </ons-row>
    </body>
</html>`

The index.js is like this.

`(function () {
    'use strict';
    var myApp = angular.module("myApp", ['onsen']);
    myApp.controller('myCtrl', ['$scope', function ($scope) {
        $scope.openDialog = function () {
            $scope.messageBox = new Date();
            ons.createDialog("dialog.html", {parentScope: $scope}).then(function (dialog) {
                dialog.show()
            });
        };
    }]);
})();`

**Comment by zhuangperola** [comment]
Hi @argelius 

I have no permission to reopen this issue, could you reopen this for me?

**Comment by zhuangperola** [comment]
Hi @frankdiox 

I run my app in PC and I found it leaks too.

**Comment by frankdiox** [comment]
@zhuangperola Thanks for that code, I am trying with this now. I think I tried with a different configuration before so it's possible that I find the leak now!

**Comment by zhuangperola** [comment]
Hi @frankdiox  Thank you for your help.

**Comment by frankdiox** [comment]
@zhuangperola Finally it appeared! Thank you very much for you help! We have released a new version with this fix: https://github.com/OnsenUI/OnsenUI/blob/1.3.4/CHANGELOG.md

Closing things now, thanks!
