### ISSUE TITLE
Feature Request - SlidingMenu setSide()

### ISSUE THREAD

**Issue by filipefreitas82** [OnsenUI/OnsenUI#738]
I have a use case where I want to change the sliding menu, from one side of the screen to the other, based on the device orientation.

Currently there is no setSide() function available.

**Comment by frankdiox** [comment]
Hello @filipefreitas82 !

It's true that there is no `setSide()` function available but you can emulate that functionality with two different menus. You just need to set "swipeable = true" in one of them at a time. I made a quick example here:

http://codepen.io/frankdiox/pen/Ejbvem

Tell me if that works for you :)

**Comment by filipefreitas82** [comment]
@frankdiox it worked.

Thanks for the help
