### ISSUE TITLE
Ons-list active state while scrolling

### ISSUE THREAD

**Issue by Wouter33** [OnsenUI/OnsenUI#740]
If you scroll an ons-list on iOS every item where you start scrolling is being highlighted. Confuses users because they are not actually tapping the item. I know this is probably hard to do because of fastclick and tap delays etc, but is there any way we can highlight the item only on a real tap?

**Comment by salztorte** [comment]
I know this Problem with tabable Lists.
As workaround i used this lib https://github.com/ilmente/mnTouch and when the user click on a Item i highlighted on my own and not over the Framework.

**Comment by Wouter33** [comment]
Thanks @salztorte. Since Onsen already has a touch library included i prefer to do it with that one. Anybody an idea? 

p.s.: I think we should have a fix for this and disable it by default, it's not really diserable behavior.

**Comment by argelius** [comment]
@Wouter33 @salztorte 

We agree that this is not desirable behavior. We will change it so they will be highlighten on "tap" instead of just when you touch them.

**Comment by Hirbod** [comment]
Can't wait to see this been fixed

**Comment by Hirbod** [comment]
Will that be also inside of the 1.3 version!

**Comment by Hirbod** [comment]
?
