### ISSUE TITLE
ons-scroller don't get scrollTop value .

### ISSUE THREAD

**Issue by ablegao** [OnsenUI/OnsenUI#748]
I want keep the ons-scroller of bottom . but , i  can't get scrollTop value , is a zero . 
What should i do ?

    <ons-page>
    <ons-scroller id="scroll_msg">

    </ons-scroller>

    </ons-page>

    <script>
    $("#scroll_msg").scrollTop() == 0;

     </script>

**Comment by argelius** [comment]
Hi @ablegao !

There is an internal element called `.ons-scroller__content`. Try getting the scroll value from that one instead.

var scroll = document.querySelector('#scroll_msg > .ons-scroller__content').scrollTop;

I made a simple example: http://codepen.io/argelius/pen/gpvGvE

**Comment by zilinxueyue** [comment]
Hi， Thanks for your sharing. Now I am try to use ons-scroller with AngularJS. I try add ng-model to get the scroller element but not working. Did you have some suggestion or some demo to share.....
 Thanks very  much

**Comment by firomero** [comment]
you should try with a directive, that's i think.
