### ISSUE TITLE
ons-sliding-menu box-shadow issues

### ISSUE THREAD

**Issue by condorman** [OnsenUI/OnsenUI#749]
Hi, 
![windows 8](https://cloud.githubusercontent.com/assets/1047377/8432702/e9a03774-1f41-11e5-8ea5-14f00d6afc1a.JPG)

In windows 8.1 the ons-sliding-menu have a vertical black line.
I fix the problem in onsenui.js:

menuPage.css('box-shadow', '0px 0 10px 0px rgba(0, 0, 0, 0.2)');
to
menuPage.css('box-shadow', '0px 0px 0px 0px rgba(0, 0, 0, 0.2)');

'box-shadow': distance === 0 ? 'none' : '0px 0 10px 0px rgba(0, 0, 0, 0.2)'
to
'box-shadow': distance === 0 ? 'none' : '0px 0px 0px 0px rgba(0, 0, 0, 0.2)'

**Comment by argelius** [comment]
Thanks @condorman !

We'll take a look at this.

**Comment by andipavllo** [comment]
Hi @condorman,
that issue appears only on the emulator and we are already aware of it.
Nevertheless, we have tested it on physical devices (Lumia 630 and 930) and this problem doesn't occur.

**Comment by argelius** [comment]
@condorman 

I'm closing this since it looks like it's only an issue in the emulator. If it occurs in physical devices as well please reopen it.

**Comment by condorman** [comment]
Thanks , I installed the sdk windows phone 8.1 update 1 and everything works fine!

**Comment by argelius** [comment]
Glad you were able to solve it! (:
