### ISSUE TITLE
Sliding menu on Windows Phone : Using gesture to open the menu is not working

### ISSUE THREAD

**Issue by leoxy520** [OnsenUI/OnsenUI#758]
I am using a template from visual studio gallery to create the sliding menu project, and on a lumia 920 running WP 8.1. The swiping gesture doesn't work.

**Comment by argelius** [comment]
Thanks @leoxy520 ! We'll check this out.

**Comment by frankdiox** [comment]
@leoxy520 Thanks for reporting! Visual Studio Gallery contains Onsen UI 1.3.0 right now and that bug was fixed in v1.3.2. We will update VSG asap!

**Comment by frankdiox** [comment]
@leoxy520 We updated yesterday the Onsen UI version of Visual Studio Gallery to 1.3.4, so it should be fixed now!
