### ISSUE TITLE
Bower file improvement

### ISSUE THREAD

**Issue by Dreampassport** [OnsenUI/OnsenUI#760]
I want you to use the difference is "main" recommended in the bower. Because you are using the "styles", it can not be properly imported the file build tool.

main would be
"main": [
    "build/js/onsenui.js",
    "build/css/onsenui.css",
    "build/css/onsen-css-components.css"
]

Other, I want also to correspondence dependency of "font_awesome" and "ionicons".
Now I have copy manually.

**Comment by frankdiox** [comment]
We just modified `bower.json` to support tag-based releases. You can check this PR for more information: #736

If you want to check the old `bower.json` file, you can find it in the last release: https://github.com/OnsenUI/OnsenUI/tree/1.3.4

**Comment by Dreampassport** [comment]
Thanks! Works great!

But why is to use the "styles"?
"main" I think that it is better to use only.
Because it as a common specification, can be read from the other.
https://github.com/bower/bower.json-spec#main

Better specifications, such as:
```javascript
   "main": [
     "js/onsenui.js",
     "css/onsenui.css",
     "css/onsen-css-components.css"
   ]
```
Now this:
```javascript
  "main": [
    "js/onsenui.js"
  ],
  "styles": [
    "css/onsenui.css",
    "css/onsen-css-components.css"
  ]
```
