### ISSUE TITLE
ons-sliding-menu Flickering

### ISSUE THREAD

**Issue by PrabhdeepSingh** [OnsenUI/OnsenUI#765]
I'm using the stable build v1.3.4 and when the user clicks the button to toggle the menu the entire menu flickers but when using swipe to open the menu it doesn't flicker. Not sure if the way I'm implementing it is causing it to flicker or not. I can try reproducing the flickering on codepen if needed.

**Comment by PrabhdeepSingh** [comment]
Also in the menu is there an easy way of highlighting a menu item for the current page they're on rather then checking which page it's on every time the menu is open?

**Comment by frankdiox** [comment]
@PrabhdeepSingh I don't see any flickering in the Sliding Menu with 1.3.4. This is the last example I made and looks right to me: http://codepen.io/frankdiox/pen/Ejbvem

About selecting the item, well, if you don't want to check the current page with Onsen UI methods just save the current sate in a variable and change CSS depending on that.

**Comment by PrabhdeepSingh** [comment]
I did a screen record of the app I'm working on right now and here's the link: https://drive.google.com/file/d/0B_5psNAaZllpaWVSM3ZhUjZOaEE/view?usp=sharing The first half is when the button is clicked. You will see flickering / rendering issue on the left and side, after the pause in the middle I show how it doesn't flicker when opening it via swipe. The menu just contains ons-list with some icons, but that's about it.

**Comment by frankdiox** [comment]
Does it only happen with 1.3.4? It would be very helpful if you can reproduce it on Codepen as you said in the original comment.

**Comment by PrabhdeepSingh** [comment]
That I'm not sure, I'll try pushing 1.3.3 and the latest dev build to it, to see if anything changes. I can try reproducing the code on codepen.

**Comment by frankdiox** [comment]
1.3.3 should be the same, try with 1.3.2 or 1.3.0 better if you can :)

**Comment by PrabhdeepSingh** [comment]
Okay, I'll push those instead :)

**Comment by PrabhdeepSingh** [comment]
On both 1.3.0 and 1.3.2 getting the same thing but now when swiping I get the flickering / rendering glitch. I'll see if I can reproduce the issue on codepen but not idea if it will flicker on there or not.

**Comment by PrabhdeepSingh** [comment]
I couldn't reproduce it on Codepen because it kept opening normally. So what I did was I downloaded the Sliding menu from http://onsen.io/download.html to see if it happens with that. Turns out it does but only happens when type="overlay". Here is another video of the menu flickering: https://drive.google.com/file/d/0B_5psNAaZllpVUhKYkhTUGVjZjQ/view?usp=sharing

**Comment by frankdiox** [comment]
OK @PrabhdeepSingh ! We will investigate this. Thanks!

**Comment by PrabhdeepSingh** [comment]
Sounds good! If I figure out what is causing the menu to flicker I'll let you guys know!

**Comment by asial-matagawa** [comment]
`ons-sliding-menu` has been removed in Onsen UI 2.3.0.
You can use `ons-splitter` instead.

Closing this.
