### ISSUE TITLE
ons.bootstrap() gives exception in Windows

### ISSUE THREAD

**Issue by knight9999** [OnsenUI/OnsenUI#777]
In windows app, ons.bootstrap() does not work.
I found that the doc.readyState is 'interactive' when error is occurred.
In such case, angular.bootstrap should be called after DOMContentLoaded event is fired
same as the case doc.readyState is 'loading' or 'uninitialized'.

Please modify
        if (doc.readyState == 'loading' || doc.readyState == 'uninitialized') { ...
 in ons.bootstrap method by
        if (doc.readyState == 'loading' || doc.readyState == 'uninitialized' || doc.readyState == 'interactive') { ...
.

**Comment by argelius** [comment]
Thanks @knight9999!

We will fix this.
