### ISSUE TITLE
add Android back button support for Navigator

### ISSUE THREAD

**Issue by kruyvanna** [OnsenUI/OnsenUI#78]
Navigator should popPage by default when back button is clicked.

To prevent that behavior, user can use the **event.stopPropagation()**

**Things to confirm:**

-The order of the event registration could affect the propagation.
-The event propagation is for element, in this case, we are dealing with physical back button which doesn't have parent/child relationship

**Comment by Kianp** [comment]
event.stopPropagation() won't stop the popPage () . 
i'm using document.addEventListener("backbutton", onBackKeyDown, false);
any difference in using navigator.getBackButtonHandler() ?

**Comment by Kianp** [comment]
Navigator.getDeviceBackButtonHandler().disable() ; 
and overriding document.addEventListener("backbutton", onBackKeyDown, false);
worked .

**Comment by ArronYR** [comment]
![image](https://cloud.githubusercontent.com/assets/7171192/7215186/bc47d778-e5fd-11e4-8b2d-0057bae6aa0c.png)
![image](https://cloud.githubusercontent.com/assets/7171192/7215182/8ec49606-e5fd-11e4-97fd-daccd33b7d1f.png)
![image](https://cloud.githubusercontent.com/assets/7171192/7215183/9cd18d3a-e5fd-11e4-8313-cbe104805c49.png)
这个地方的错误怎么解决？

**Comment by murliatdure** [comment]
Similar issue - 

module.run(function($rootScope) {
        alert("RUN");
        
        ons.ready(function() {
            alert("READY");
        });
        
        document.addEventListener("backbutton", function (e) {
            alert("THE BACK BUTTON WAS HIT!");
            alert($rootScope.ons.navigator.getPages());
            if ($rootScope.ons.navigator.getPages().length > 1) {
                e.preventDefault();
                $rootScope.ons.navigator.popPage();
            } else {
                navigator.app.exitApp();
            }
        }, false);
    });


The code works till - THE BACK BUTTON WAS HIT!

**Comment by rohitjain-rj** [comment]
Can someone please post a proper working example for android backbutton handler? The above code doesn't work. I've set the `var` attribute for `ons-navigator`. And when I do `myNavigator.app.exitApp();`, it says, the `exitApp` cannot be invoked on undefined.

And what does `e.preventDefault()` do? Is it necessary to have that, if I want to exit the app on back button, hit on currentPage say - `page3.html`?

**Comment by michaeleparkour** [comment]
Offcourse you will have myNavigator.app.exitApp() undefined, because this is not OnsenUI function of onsenNavigator. 
navigator is a global object of WebView (browser), so if you wanna close the app do:
navigator.app.exitApp()

**Comment by rohitjain-rj** [comment]
Ah! Yes, it worked. Didn't know navigator and ons-navigator is different thing here.

**Comment by saravanans-arch** [comment]
Let me know, how it is work for Onsen Angular 2+?
