### ISSUE TITLE
Issues with the Page pop

### ISSUE THREAD

**Issue by murliatdure** [OnsenUI/OnsenUI#780]
Firstly I tried the pages Push/Pop with all animations - Everything was working well.
then I tried to insert the Menu along with Push/Pop again the things are perfectly working only LIFTed Page popuping tends to the issue.

Please find the following snaps - 
1. Push -with life animation

<img width="314" alt="12" src="https://cloud.githubusercontent.com/assets/7137859/8674720/56489b20-2a5d-11e5-90d7-d811ecc86c73.PNG">

When I tried to POP the same page - then output is something - 

<img width="316" alt="11" src="https://cloud.githubusercontent.com/assets/7137859/8674733/64c1843c-2a5d-11e5-826c-0f60022eb0b6.PNG">

Please assist me on the same

**Comment by argelius** [comment]
Hi @murliatdure !

Could you please a Codepen example reproducing this issue?
You can fork one of our examples here: http://codepen.io/onsen/
