### ISSUE TITLE
Refreshing a lazy-repeat list

### ISSUE THREAD

**Issue by Wouter33** [OnsenUI/OnsenUI#782]
Hey guys,

We're having some issues with the lazy-repeat list. We have a list of contacts which works fine. Problems occur when we want to select some filters on a new page, dismiss the filters page and afterwards want to "refresh" the lazy-repeat ons-list on the original page with a new data array.

What's the way to go here? We tried all kinds of things like replacing the "repeater" variable in the scope etc. But the old items stay visible. 

How can we destroy the delegate and replace it or refresh the current instance?

Thanks!

**Comment by argelius** [comment]
Hi!

Right now there is no way to replace the delegate object. However, I think you can modify your delegate to account for the filtering.

I made a super simple example:
http://codepen.io/argelius/pen/VLdGxZ

**Comment by Wouter33** [comment]
Thanks @argelius. Makes sense for a search indeed. 

For some other filters we can't always filter the available variables in the scope and we would like to "rebuild" the data array. That goes well in your example if we replace the scope array. 

Only thing is that we're using the height calculation to insert headers into the list. When we replace the data array the heights don't get updated and the heights from the headers are wrong and vice versa. 

Any idea on that?

**Comment by filipefreitas82** [comment]
This is great. I had the same issues.

I have a requirement to have the search input always visible on top even when scrolling instead of on the bottom.
I modified your code pen to demonstrate:
http://codepen.io/anon/pen/MwXZJO

It works on the browser, but when I test run it on a device (iphone) it's not working correctly. I can't figure this out.

**Comment by Wouter33** [comment]
@filipefreitas82 iOS does not fully support position: fixed. What you can do is put the search box at the beginning of the page and under that an ons-scroll element that contains the list. Now you can set the height of the ons-scroll element to the remaining height which causes the search bar to be always visible.

**Comment by filipefreitas82** [comment]
@Wouter33 thanks. I will try that.

**Comment by Wouter33** [comment]
@argelius, any idea on replacing the data entry and keeping the heights correct for the new items?

**Comment by argelius** [comment]
@Wouter33 We'll add a way to recalculate the height since currently it's hard to use with dynamic lists that have variable height items like headers.

**Comment by Wouter33** [comment]
Thanks @argelius! Looking forward to it!

**Comment by argelius** [comment]
@Wouter33 @filipefreitas82 

I made some tests with recalculating the heights when the number of items change. I did some profiling and realized that as long as the method that calculates the heights is reasonably simple there won't be any performance issue.

The user would have to scroll pretty far down in order for it to be slow.

It's implemented in this branch:
https://github.com/OnsenUI/OnsenUI/tree/release-1.3.8

An example with dynamic list and variable height elements:
http://codepen.io/argelius/pen/OVBdmM

I will run some more tests and if I don't find any big performance issues I will release this tomorrow.

One caveat: This will only work if the number of items change is changed.

**Comment by marianoarga** [comment]
I enter any codepen.io examples you wrote but none seems to work, could any give and update on how to achieve the lazy-repeat filter?

Thanks you.

**Comment by argelius** [comment]
@marianoarga 

The branch does not exist anymore so the example stopped working. I have updated to the latest version now:
http://codepen.io/argelius/pen/OVBdmM

In this example lazy repeat is used with variable height and dynamic updates.

**Comment by marianoarga** [comment]
@argelius 
Thank you, the same happend to this example you wrote?
http://codepen.io/anon/pen/MwXZJO
That was the one I'm more interested on, since I want to make an instant **search filter** over an **ons-lazy-repeat** list, a Whatsapp contacts search like.

**Comment by marianoarga** [comment]
@argelius
Do you have any update?
Thank you very much.
