### ISSUE TITLE
OnsenUI with Angular Material

### ISSUE THREAD

**Issue by DILEEP-YADAV** [OnsenUI/OnsenUI#784]
If OnsenUI support to Angular, Than OnsenUI have to support  Angular Material. Is this possible or not ? 

I think that is right track for OnsenUI https://material.angularjs.org

**Comment by argelius** [comment]
Hi @DILEEP-YADAV !

We're currently implementing Material Design for Onsen UI. Please keep an eye on the `master` branch. We will also announce it on our blog.

**Comment by DILEEP-YADAV** [comment]
ok ! thanks
