### ISSUE TITLE
Tabs & auto detect OS

### ISSUE THREAD

**Issue by ThatoMokhomong** [OnsenUI/OnsenUI#786]
Please make that if the platform is android, tabs must be under navigation bar not on top of the bar.
Onsen UI should also detect the platform if it is Android and iOS to follow design rules for a specific platform like ionic.
Please add Material Design on android for ver 2.0
I love this framework

**Comment by argelius** [comment]
Hi @ThatoMokhomong !

Thanks. We're actually currently implementing Material Design.

For the tabs, you can put them on top with the `position="top"` attribute. If you use that attribute only on Android devices you should get the desired effect.

**Comment by ThatoMokhomong** [comment]
OK thanks
