### ISSUE TITLE
[WP8.1][IE] ons-pull-hook not working

### ISSUE THREAD

**Issue by agustinsaldias** [OnsenUI/OnsenUI#810]
I've been trying to make it work for the past few days without a result. IE11 on WP8.1 won't work, can't understand why. 

I'm using a Lumia 620, WP8.1 v8.10.14234.375 with Lumia Denim. This is my user-agent if needed:

**Mozilla/5.0 (Windows NT 6.2; ARM; Trident/7.0; Touch; rv:11.0; WPDesktop; Lumia 620) like Gecko**

Simply using the official pull-hook example that can be found here: http://codepen.io/onsen/full/WbJogM you can reproduce the issue.

With Cordova, and deploying the app as a Universal App, it works just fine, but directly on the browser it doesn't. Important note is that IE11 on my desktop works just fine, emulating WP8.1 and IE11 as well, even on my Surface Pro 3, the error is only happening on the device browser itself.

I'm thinking it's an issue with how IE11 is triggering the events (and the information available for them) and how Cordova/deploying as an App, can use a few extra tools not available in the browser itself to determine coordinates.

is this a bug? Or simply unsupported because of how IE11 works on mobile?

Thanks!

**Comment by frankdiox** [comment]
The problem was using wp8 platform instead of windows universal  as explained here: http://stackoverflow.com/a/31596226/4468962

**Comment by agustinsaldias** [comment]
No...it isn't...I'm the author of the stackoverflow question (and answer). The issue is with IE11 by itself, no cordova, no phonegap, no platform, just plain IE browser on the device.

**Comment by frankdiox** [comment]
Oh yes, I thought it was the same than in SOF. Anyway, Onsen UI does not support IE11like that, only Windows Universal Apps. Probably this is not the only problem that happens on IE11.

**Comment by agustinsaldias** [comment]
Oh, ok :( That was my suspicion...too bad. Any plans on supporting IE11 more ?

**Comment by frankdiox** [comment]
@agustinsaldias Sorry, right now we are focusing in supporting more common platforms and adding new features to the framework. There is no plan to test IE11 so far since it already works as Windows Universal App. However, if you do further research and find fixes for IE11 that are compatible with the rest we will be happy to accept a PR. In that case, feel free to ask any doubt that comes up!
Thanks!
