### ISSUE TITLE
Keyboard attach directive

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#827]
Hi,

Ionic provides a nice feature called "keyboard attach"
http://ionicframework.com/docs/api/directive/keyboardAttach/

This is something very important for app usage, especially when you try to achieve a messaging app. Currently, it's very tough to do this manually (need to find out the keyboard height and do a lot of manipulation on container height etc.)

Would love to see such a feature

**Comment by argelius** [comment]
I agree. This feature is very important for all apps with an input element at the bottom bar.

We will definitely add it :)

**Comment by Hirbod** [comment]
:+1:

**Comment by Hirbod** [comment]
@argelius just wan't to send out a small reminder... I'm waiting so badly on this feature.
https://github.com/driftyco/ionic/blob/master/js/angular/directive/keyboardAttach.js#L1

It should not be so much work.. Of course it would need some keyboard listeners and Onsen adjustments.
