### ISSUE TITLE
Official support for Meteor.JS

### ISSUE THREAD

**Issue by dalerka** [OnsenUI/OnsenUI#829]
Hey guys, thank you for such a great mobile UI framework and documentation. 
Do you think it would be possible to support [Meteor.JS](http://meteor.com) framework by publishing an official package to [Atmosphere](http://atmospherejs.com)? 

There are few packages for _OnsenUI_'s direct competitor [Framework7](https://atmospherejs.com/?q=framework7), and I believe playing together will bring even more attention to _OnsenUI_, because _Meteor_ is a great full-stack framework too :)

**Comment by dalerka** [comment]
BTW, [this resource may be helpful](https://autopublish.meteor.com) for you guys to publish OnsenUI package for meteor and keep it up to date, although the name is confusing as there's nothing to do with Meteor's [Autopublish](https://github.com/meteor/meteor/tree/devel/packages/autopublish) package.

**Comment by boustanihani** [comment]
:+1:

**Comment by arseniosiani** [comment]
+1

**Comment by gtorodelvalle** [comment]
+1

**Comment by argelius** [comment]
We would love to support Meteor but none of us has any experience with it. Right now we are focusing on React and Angular2 but it might happen in the future :)
