### ISSUE TITLE
1.2.1 android back button key

### ISSUE THREAD

**Issue by mateusjatenee** [OnsenUI/OnsenUI#835]
Hello everyone!  
I need to change some stuff in an app I didn't develop. First, android back button closes the app.  I've read somewhere it was 1.2.1's bug and I should simply update - sadly, whenever I change OnsenUI's version I get many errors in my console log. 
This app uses setMainPage to switch between app pages. If I could somehow make the back button key works, It'd work fine. I've thought about storing an array of pages and them using popPage to go back (actually I think I read this somewhere here.)  
Anyway, sorry for asking this here. I'm kinda lost - some say it's 1.2.1 bug, others say it isnt.  
Thanks in advance!

**Comment by andipavllo** [comment]
@mateusjatenee I guess you are using a sliding menu. In the sliding menu, the back button, once pressed, just closes the menu so it should not be considered a bug.
