### ISSUE TITLE
Galaxy S6: ugly slide transition animations on page push

### ISSUE THREAD

**Issue by mork80** [OnsenUI/OnsenUI#836]
Hi all,
i've elected ONSEN UI my favorite Cordova HTML5 framework. I’m developing apps both on iOS and Android since the 1.2.\* version.
I’m very happy for UI speed and especially the jQuery integration (I’ve switched from JQM).
My first issue I’ve noticed is on almost all animations on page transition using ons-navigator.
My test were performed with following environment set:
      - Cordova 4.2.\* and Cordova 5.*
      - Onsen UI 1.3.2 and 1.3.8
      - jQuery 2.1.*
I’ve built a very simple app using a couple of screens in a single html file.
The navigator used is only ons-navigator, using push and pop functions to go forward and back from an “home” screen.
I’ve tested the app on 3 different devices, 2 android and 1 iOS
Problem : CSS3 animations on push and pop transitions:
    -   iPhone 6, iOS 8.4: no issue at all, all transitions are smooth and fast; 
    -   Nexus 5,  Google Android 5.1._:  transitions are smooth, a little bit slower, but ok (hardware is cheaper);
     -  Galaxy S6, Samsung Android 5.1._:  animations flicker during all transition and it seems to perform transition in a very slow timing.

The weird thing is that S6 HW is on top edge of “potential” performance.
Setting animations on “none” for tranitions let the UI fast as desired on other DOM manipulations (both NG and JQ driven) on S6.

I’ll investigate on how to tweak this in onsenui.js CSS3 attachments but I hope this will be fixed on 1.3.9 

Bye from Italy

**Comment by john156** [comment]
:+1:

**Comment by argelius** [comment]
Thanks @mork80 @john156 !

This sounds like a serious bug. We will try to find it but actually we don't have access to a S6 device right now.

If you guys are able to find the CSS that triggers this we would love to get a pull request! :)

By the way, are you running Crosswalk?

**Comment by mork80** [comment]
Just to begin to dig in....
in onsenui.js at 11878 is locate the function delegated to perform the default android page transition.
"SimpleSlideTransitionAnimator"
playing with the value in mask definition and the animation timing, i can obtain a better performance.
For example try to modifiy like this before "init":
```javascript
/** Black mask */
      backgroundMask : angular.element(
       '<div style="z-index: 2; position: absolute; width: 100%;' +
       'height: 100%; background-color: transparent; opacity: 0;"></div>'
      ),

      timing: 'cubic-bezier(.1, .7, .4, 1)',
      //timing: 'cubic-bezier(0.3, 0, 1, 1)',
      duration: 0.2,
      blackMaskOpacity: 0.0,

```

**Comment by Hirbod** [comment]
I can confirm, S6 Edge Push is very choppy

**Comment by rdosrz** [comment]
Is not just on Samsung S6. I have the same issue on any device with Android 5 Lollipop. If I put {transition:none} in pushPage sentence works fine. Obviously, without transitions the app looks more like a web app in place to a native app (wich is the point using cordova or phonegap right?).
i've tried fix this unsuccessfully:
-Phonegap
-Angular
-CSS3
Must to be a onsen ui issue.
Somebody has recent news about it?

**Comment by mork80** [comment]
Last Onsen version i've tried is 1.3.9 and transitions were still not smooth as expected.
I see in 2.0dev changelog new core animations. Hope this will render well in future developments.
For now, i've opted to transition:none in android.

**Comment by asial-matagawa** [comment]
This issue was superseded by #922. Closing this.
