### ISSUE TITLE
lazy repeat incredibly slow on iOS and Android

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#841]
Hi,

I have following setup:

``` js
        $scope.MyDelegate = {


            configureItemScope: function(index, itemScope) {

                itemScope.item = {};

                var person = $scope.photos.items[index];
                itemScope.item.uid = person.uid;
                itemScope.item.firstname = person.firstname;
                itemScope.item.picture = person.picture;
                itemScope.item.lastactivity = $scope.formatTime(person.last_activity);

            },

            calculateItemHeight: function(index) {
                return 91;
            },

            countItems: function() {
                return $scope.photos.items.length;
            },

            destroyItemScope: function(index, itemScope) {
                /*
                itemScope.canceler.resolve();
                console.log("Destroyed item #" + index);
                */
            }
        };
```

``` js
$scope.photos.items
```

is a json object with 1500 nodes. I catch it from remote on init and store it there. The list loads and work fast on simulator but it is so laggy and choppy on all real devices. What am I doing wrong?

It's really hard to understand the lazy repeat (imho not good documented). Before I've switched to lazy repeat, I had a scroll-observer and pulled 25 elements from the server and made a LIMIT on MySQL, then I added the new elements to my scope array (with ng-repeat)

I switched this cause I did not want to have 1500 HTML nodes. But it was way more performant then lazy-repeat. Any suggestions?

**Comment by Hirbod** [comment]
Seems like formatTime is playing bad with performance. After I've removed it (I format it on the server right now) it is much better, but still, not the "native" feeling. Especially when I sroll slowly. @argelius

**Comment by Hirbod** [comment]
After the changes, my Galaxy S6 Edge is perfectly fast. It just don't feel that good on iOS. I hope you guys have some recommendations how to optimize this hole thing. I've also changed my code a bit


```js
$scope.item = {};

        $scope.MyDelegate = {


            configureItemScope: function(index, itemScope) {
                
                //console.log(itemScope);

                itemScope.item = $scope.photos.items[index];
                /*
                itemScope.item.uid = person.uid;
                itemScope.item.firstname = person.firstname;
                itemScope.item.picture = person.picture;
                itemScope.item.lastactivity = person.last_activity;
                */

            },

            calculateItemHeight: function(index) {
                return 91;
            },

            countItems: function() {
                return $scope.photos.items.length;
            },

            destroyItemScope: function(index, itemScope) {
                /*
                itemScope.canceler.resolve();
                console.log("Destroyed item #" + index);
                */
            }
        };

``

**Comment by Hirbod** [comment]
@argelius 

the ons-lazy-repeat needs  debouncing, or it will never be really performant (due to UIWebViews limitation and throttled scroll-event-publishing). This behaviour will be better once WkWebView will be working on iOS 8+ cordova.

I've patched the Lazy directive and I have a 100% performance boost now.

```js
      _debounce: function(func, wait, immediate) {
		var timeout;
		return function() {
			var context = this, args = arguments;
			var later = function() {
				timeout = null;
				if (!immediate) func.apply(context, args);
			};
			var callNow = immediate && !timeout;
			clearTimeout(timeout);
			timeout = setTimeout(later, wait);
			if (callNow) func.apply(context, args);
		}
	   },
	   _doubleFireOnTouchend: function(){
	   		this._render();
        	this._debounce(this._render.bind(this), 100);
	   },

      _addEventListeners: function() {
        this._boundOnChange = this._debounce(this._onChange.bind(this), 30);

        this._pageContent.addEventListener('touchmove', this._boundOnChange, true);
        this._pageContent.addEventListener('scroll', this._boundOnChange, true);
        this._pageContent.addEventListener('touchend', this._doubleFireOnTouchend, true);


        $document[0].addEventListener('resize', this._boundOnChange, true);
      },

      _removeEventListeners: function() {
        this._pageContent.removeEventListener('scroll', this._boundOnChange, true);
        this._pageContent.removeEventListener('touchmove', this._boundOnChange, true);
        this._pageContent.removeEventListener('touchend', this._doubleFireOnTouchend, true);


        $document[0].removeEventListener('resize', this._boundOnChange, true);
      },
```

It does not break anything - it just works 100% better than before. You can't recalculate so many elements without strugglin on performance. If I've a long list and do a really really fast scroll, it can happen that the elements will be rendered after the scroll event has finished. I tried to eliminate with a "doubleFireOnTouch" but it don't work always. But the problem was there also before I've patched (but due to stutter on scroll less visible)

Nontheless, adding 30ms of debouncing will give 
a) memory boost
b) performance boost
c) will not break current flow

**Comment by argelius** [comment]
Thanks a lot for the fix @Hirbod ! This is really helpful. :)

Since it's a significant performance boost I will implement this as soon as I have time.

**Comment by Hirbod** [comment]
Hi @argelius,

thank you. One hint: my "deviceIsIOS" call does not work. How to determine the device inside of Lazy?

**Comment by argelius** [comment]
Hi!

You can use `ons.platform.isIOS()`. It's using User-agent sniffing though so if the User-agent string is spoofed it will return the incorrect value.

It's using this code:

```
return /iPhone|iPad|iPod/i.test(navigator.userAgent);
```

**Comment by Hirbod** [comment]
Ok. I think Onsen should consider to use the device-plugin (when installed) to prevent user agent fakes.

**Comment by Hirbod** [comment]
Ok, changed code above. This is just a way of optimizing. Try to load an json with 1-2k of data (remote) and incoporate my fixes. Maybe you find a way to prevent "white screen till scroll is finished". I've seens some patches even for FastClick which looks like to be the same. But debouncing is imporant. Thanks for answering!

**Comment by argelius** [comment]
Thanks a lot!

You mean white screen during inertial scroll, right? I'd love to find a way to fix that. The iOS WebView doesn't seem to do any rendering during the inertial scrolling (probably to ensure a smooth scroll animation). I've tried to find a way to force rendering during scrolling but didn't have any success.

The only way I found was to emulate scrolling but we like to use the native scrolling if possible.

**Comment by Hirbod** [comment]
Yes, this is exactly what I mean. This changed in WKWebview (scroll events fire in realtime).
Due to apples bug on WKWebView, it isn't possible to run it currently on iOS. But the bug also occurs on Android somtimes.

By the way:

Before optimize:
https://youtu.be/CcClaDEhSew

After: optimize: (see the white screen bug on fast scroll)
http://youtu.be/SS8OQwutFgI

**Comment by argelius** [comment]
That's a great speed improvement. Will definitely add the debouncing.

Also thanks for the tip about the device plugin. We will change `ons.platform` methods to use that and only fall back to user-agent if it's not present.

**Comment by Hirbod** [comment]
:+1: I'm going to bed right now! Thanks a lot.

**Comment by Hirbod** [comment]
@argelius

I think i have an idea.

http://jsfiddle.net/6EYxz/

We could hack a little bit. On touchend (with a little Delay) a inertial/Momentum scroll stop. Maybe not beautiful but a solid woraround based on native scrolling. Or iScroll 5. But with that hack we could prevent long white screen durations (we could add the overflow hidden hack, check if there is more space for scroll, and trigger a fake (scrollOut) immediately after stopping (to prevent hard stops).

What you think ?
