### ISSUE TITLE
ons-scroller bugs with ons-pull-hook

### ISSUE THREAD

**Issue by yesman99** [OnsenUI/OnsenUI#843]
When I use ons-scroller with height set with ons-pull-hook, I found these two problems.

1. When I try to scroll inside of ons-scroller tag, the whole html is scrolled too.
2. After scrolling inside of ons-scroller tag to the bottom and left my finger, I could not scroll to the top anymore.

```
    <ons-page>
      <ons-pull-hook ng-action="load($done)" var="loader">
        <span ng-switch="loader.getCurrentState()">
          <span ng-switch-when="initial"><ons-icon size="35px" icon="ion-arrow-down-a"></ons-icon> Pull down to refresh</span>
          <span ng-switch-when="preaction"><ons-icon size="35px" icon="ion-arrow-up-a"></ons-icon> Release to refresh</span>
          <span ng-switch-when="action"><ons-icon size="35px" spin="true" icon="ion-load-d"></ons-icon> Loading data...</span>
        </span>
      </ons-pull-hook>
    
      <ons-scroller style="height: 230px;">
        <p>hadskfj</p>
        <p>hadskfj</p>
        <p>hadskfj</p>
        <p>hadskfj</p>
        <p>hadskfj</p>
        <p>hadskfj</p>
        <p>hadskfj</p>
        <p>hadskfj</p>
        <p>hadskfj</p>
        <p>hadskfj</p>
        <p>hadskfj</p>
        <p>hadskfj</p>
        <p>hadskfj</p>
        <p>hadskfj</p>
        <p>hadskfj</p>
        <p>hadskfj</p>
        <p>hadskfj</p>
      </ons-scroller>
    </ons-page>
```

**Comment by yesman99** [comment]
Hi there, can I expect that this bug is on going? Someone is investigating?
Thank you.

**Comment by argelius** [comment]
Hi @yesman99 !

Sorry for the delay. I was on vacation. The reason why this happens is that the `<ons-pull-hook>` overrides the default scroll behavior.

If you stop propagation of the `touchmove` event at the `<ons-scroller>` element you should be able to scroll it in both directions.

You can do something like this if you still want to be able to use the pull hook when the `<ons-scroller>` is at the top scroll position:

```javascript
ons.ready(function() {
  document.querySelector('#scroller > .ons-scroller__content');
    .addEventListener('touchmove', function(event) {
      if (scroller.scrollTop > 0) {
        event.stopPropagation();
      }
    });
});

**Comment by yesman99** [comment]
Thank you for your reply, @argelius!

As a result, I could get what I wanted.

I tried as you told, but I could not get the object "document.querySelector('#scroller > .ons-scroller__content')".
So I changed the ons-scroller to "<div style="overflow: scroll>" then I could get the object to affect "stopPropagation()".

Thank you!

**Comment by argelius** [comment]
@yesman99 I'm glad you were able to solve it! :)
