### ISSUE TITLE
Nested ons-carousel

### ISSUE THREAD

**Issue by ramingar** [OnsenUI/OnsenUI#844]
I'm trying with this code (a little bit modified code of http://codepen.io/onsen/pen/xbbzOQ):

```html
<ons-page>
    <ons-toolbar>
      <div class="center">Carousel</div>
    </ons-toolbar>
    
    <ons-carousel style="height: 500px; width:100%" initial-index="0"
    auto-refresh var="carouselTop" item-width="100%">
      
      <ons-carousel-item style="background-color: gray;">
        <div class="item-label">GRAY</div>
      </ons-carousel-item>

      <ons-carousel-item style="background-color: gray;">
        <ons-carousel swipeable overscrollable auto-scroll fullscreen
        var="carouselInner{{$index}}" initial-index="1"
        ng-repeat="carousel in [1,2,3,4,5,6,7,8]">
            <ons-carousel-item style="background-color: gray;">
              <div class="item-label">SURPRISE</div>
            </ons-carousel-item>
          
            <ons-carousel-item style="background-color: gray;">
              <div class="item-label">GREEN</div>
            </ons-carousel-item>
        </ons-carousel>
      </ons-carousel-item>
    
    </ons-carousel>
  </ons-page>
```

When I do

```javascript
carouselTabBar.setActiveCarouselItemIndex(9999999999);
carouselTabBar.getActiveCarouselItemIndex();
```
I realized that Onsen creates 17 ons-carousel-item for carouselTop (it counts all ons-carousel-item below carouselTop). I think Onsen should count only his ons-carousel-item direct children (that is two children) and discard the other ones.

For me it's an important odd behaviour because it causes messy results when you want to show nth(1+) children items with carouselTop.next(). What do you think?

Greetings!

**Comment by argelius** [comment]
Thanks @ramingar !

It should definitely just count the direct descendants. I have fixed this and it will be included in the next release.

**Comment by ramingar** [comment]
Thanks! You are absolutely great.
