### ISSUE TITLE
WebKit discarded an uncaught exception in the webView:willRemoveScrollingLayer:withContentsLayer:forNode: delegate: 

### ISSUE THREAD

**Issue by sriram275** [OnsenUI/OnsenUI#863]
Hi..,

While running cordova app( with using onsenUI ) we are seeing the following message in log( xcode )

*** WebKit discarded an uncaught exception in the webView:willRemoveScrollingLayer:withContentsLayer:forNode: delegate: <NSInvalidArgumentException> -[WebActionDisablingCALayerDelegate setBeingRemoved:]: unrecognized selector sent to instance 0x7f9640c06030

Some one saying like it is because of using  -webkit-overflow-scrolling: touch;

So let me know what is the exact issue to get this error message?

**Comment by Hirbod** [comment]
There is no real fix for this - but this warning does not harm your application. It happens due to overflow-scroll:touch (when you have two elements with that property)

you can ignore this one

**Comment by Sikandarkhan** [comment]
Still I am encountering this issue.

**Comment by pulimento** [comment]
Me too, having exactly the same error

**Comment by Hirbod** [comment]
As said, you can just ignore this. It's not OnsenUI causing this. It happens also to other Frameworks.

**Comment by Harryteja** [comment]
Me too, throwing error with same message...It is not displaying webContent showing blank and crashes by showing this error in log..Can anyone tell me exact solution for this?

**Comment by tubie** [comment]
Me too
