### ISSUE TITLE
jquery/angularJS click event not triggered in ons-back-button in onsenui v1.3.8

### ISSUE THREAD

**Issue by dineshprodapt** [OnsenUI/OnsenUI#865]
With the latest version of Onsen v1.3.8, I couldn't write specific jquery click events for `ons-back-button` like below.

    $(document).on('click', 'ons-back-button', function(e){
    alert('clicked');
    });

But, with the older versions like `/* onsenui - v1.2.1 - 2014-12-01 */`   jquery click events are triggered. 

Using latest version `/*! onsenui - v1.3.8 - 2015-07-27 */`  (onsenui_all.js or onsenui.js), jquery click events not triggered specifically for `ons-back-button`!

`ons-button`, `ons-list` jquery click events are triggering with the latest versions.

**Edit:**

`ng-click` event also not triggered

    <ons-back-button ng-click="onsPay()"></ons-back-button>
    
    function onsPay()
    {
     console.log("Clicked");
    }

Any help on this?

**Comment by frankdiox** [comment]
Looks like this is the reason (included in 1.3.0): https://github.com/OnsenUI/OnsenUI/blob/master/core/lib/navigator-page.es6#L43

@argelius @anatoo what do you think about that?

**Comment by argelius** [comment]
Thanks @dineshprodapt ! 

@frankdiox That fix is to prevent scrolling the page while the transition animation is running on iOS.

I have changed so it only stops `touchmove` since that's the one that causes the scrolling. If there's no trouble we can include this in the next release.
