### ISSUE TITLE
"center" class using in ons-toolbar is not set center 

### ISSUE THREAD

**Issue by radiocat** [OnsenUI/OnsenUI#867]
Sample code : http://codepen.io/onsen/pen/yrhtv
http://ja.onsen.io/guide/overview.html#PageNavigation

    <ons-toolbar>
      <div class="center">Simple Navigation</div>
    </ons-toolbar>

build with cordova for android.
Title "Simple Navigation" is set left(not set center) in toolbar.
iOS is set center.

Android OS : 4.4.1
Cordova : 4.3
OnsenUI : 1.3.8

**Comment by frankdiox** [comment]
@radiocat Hello! This has been asked many times before. Please search in SOF, issues here or just check the docs. Last attribute here: http://onsen.io/reference/ons-toolbar.html#attributes

**Comment by radiocat** [comment]
Sorry for the same question.
I solved the problem by reading the docs. 
Thank you.
