### ISSUE TITLE
Onsen UI Minimum Template for universal App - PushPage Problem

### ISSUE THREAD

**Issue by pancitjef** [OnsenUI/OnsenUI#868]
If you double click the push button, page gets pushed twice. Try going back, click pop only once(not twice).
![screenshot 2015-09-02 at 9 21 58 am](https://cloud.githubusercontent.com/assets/14074687/9621049/5e46c018-5154-11e5-92a3-c1c81ed57228.png)
![screenshot 2015-09-02 at 9 19 59 am](https://cloud.githubusercontent.com/assets/14074687/9621050/5e4c24e0-5154-11e5-880e-e466b52fb4f0.png)

**Comment by argelius** [comment]
Thanks @pancitjef !

It seems like if the animation is delayed it's possible to push two pages. You can do something like this:

```
<ons-navigator ng-init="pushing = false" ons-prepush="pushing = true" ons-postpush="pushing = false">
```

And on the button you can disable the button so it's not possible to click it twice:

```
<ons-button
  ng-click="myNavigator.pushPage('page2.html');"
  ng-disabled="pushing">
  Push Page 2
</ons-button>
```
