### ISSUE TITLE
Feature request: navigator.bringToTop( page );

### ISSUE THREAD

**Issue by frankdiox** [OnsenUI/OnsenUI#877]
It checks if the provided page already exists in the navigator's page stack and brings it to the top in such case. If it doesn't exist it could use `pushPage()` as fallback.

It can also be implemented as a new option for `pushPage()`.

@argelius @anatoo, thoughts?

**Comment by anatoo** [comment]
Nice feature. It's good to me.

**Comment by argelius** [comment]
@frankdiox I think it looks good, but I'm wondering what should happen if they have pushed the same page twice? Should it bring the page closest to the top?

Maybe not a common scenario but they might push the same template page but with different content. Should we also support `navigator.bringToTop(index)` where `index` is an integer?

**Comment by frankdiox** [comment]
@argelius That could work. I guess it's better to start counting from the top, so `index=0 / default` would be the closest page to the page-stack top and so on.
