### ISSUE TITLE
ons-navigator as a main page of ons-slide-menu flickering

### ISSUE THREAD

**Issue by c58** [OnsenUI/OnsenUI#879]
II have three templates: one with ons-slide-menu, another(page) with ons-page and last with ons-navigator with default page attribute set.
When i navigate with slide menu to a page without navigator all is fine. But when i navigate to a page with ons-navigator page is flickering (black page before actual page).
Problem occurred on desktop Chrome and on IOS 9 (Cordova), others not tested.
There is a proof.
![page-flickering.gif](https://cloud.githubusercontent.com/assets/1871220/9728522/eaafe4ae-5621-11e5-9394-536d30786a94.gif)

**Comment by c58** [comment]
Page one:
```
<ons-navigator animation="slide" var="pageNav"
  page="partials/app/selector/list.html">
</ons-navigator>
```

Page two:
```
<ons-page var="pageTimetable" ng-controller="TimetableController as ctrl">
  <ons-toolbar class="st-nav" modifier="android">
  ...
```

Page list.html:
```
<ons-page class="st-selector" var="pageSelector" ng-controller="SelectorController as ctrl">
  <ons-toolbar class="st-nav">
  ...
```

**Comment by argelius** [comment]
Thanks for reporting @c58 !

This looks like a bug. We will investigate it.

**Comment by frankdiox** [comment]
I can confirm the flickering.
In sliding menu: http://codepen.io/frankdiox/pen/VvLNpK
In tabbar: http://codepen.io/frankdiox/pen/EVjzag

We will try to fix it!

**Comment by c58** [comment]
Thanks! Just for now i've made a workaround. Flickering is still there, but not so ick :)
<ons-navigator style="background: #fff;">
</ons-navigator>

**Comment by Hirbod** [comment]
same flickering when having tabbar with own navigator. as soon as there are nested ons-pages, it will flicker. This is why I still have never implemented a second navigator (I lose my tab-bar on pushPage, I would love to keep it, but played around more than 10 hours to fix the flickerin.) no chance..

**Comment by c58** [comment]
I think my strategy of the fix may be applied on tabbar too. I'll try to fix it, maybe in the evening.

**Comment by c58** [comment]
I've investigated, that the problem is with using a promises in `getPageHTMLAsync` and `getTemplateHTMLAsync`. They should be synced when template already in a templates cache. Then a ons-navigator's main page will be initialized synchronously (within the same run cycle that _appendMainPage called) and no flickering will be appeared.

**Comment by Hirbod** [comment]
seems obvious +1

**Comment by c58** [comment]
It's a part of the problem, but it does not solve it completely. In `_pushPageDOM` of the `ons-navigator` is another async callback, and i don't understand why it must be there?

```
this._isPushing = true;

        this._compilePageHook.run(function (element) {
          _this9._linkPageHook.run(function (element) {
            setTimeout(function () {
              if (_this9._pages.length > 1) {
                var leavePage = _this9._pages.slice(-2)[0];
                var enterPage = _this9._pages.slice(-1)[0];

                _this9.appendChild(element);
                leavePage.element._hide();
                enterPage.element._show();

                options.animator.push(enterPage, leavePage, done);
              } else {
                _this9.appendChild(element);
                element._show();

                done();
              }
            }, 1000 / 60);
          }, element);
        }, element);

**Comment by c58** [comment]
@Hirbod , check my latest commit, no flickering detected in ons-navigator with cached templates. I also fixed a `tab` element, it means you problem maybe fixed too.
I have only one problem – tests not passed, broken within iOS animation, but manual test of all transitions does not detect any issues with it.

**Comment by logicweb** [comment]
Any news about this?
I have the same issue with the 2.0 on several iOS devices, even in the simulator, but not always, depends on model and os version.
![flicker](https://cloud.githubusercontent.com/assets/7430566/15044014/1e3dfdf2-12d2-11e6-99a9-ab0f58623dd0.gif)

**Comment by argelius** [comment]
@logicweb Thanks for the screenshot! We will look into this

**Comment by argelius** [comment]
@logicweb By the way, are you using `<ons-sliding-menu>` or the new `<ons-splitter>` component?

**Comment by Neron-X5** [comment]
Hi, I am using v1.3.15 and this flicking issue is observed on several iPhone and iPad devices ranging from iOS 8.0 to 9.3.1. Is there any fix for the same on version 1.x.x stream?
I can not update to version 2 till a stable release is available.

**Comment by logicweb** [comment]
@argelius we are using `<ons-sliding-menu>,` inside the mainPage.html we have a single `<ons-navigator>` where we push every pages.
If you look the gif carefully you can see a single frame where the page is visible with al the angular tags not populated yet.
Maybe it's something on our side, but on android this never happen.
