### ISSUE TITLE
popover conflicting with bootstrap

### ISSUE THREAD

**Issue by rahilwazir** [OnsenUI/OnsenUI#880]
Boostrap `.popover` css declaration `display: none` applies the styling to `ons-popover .popover` element which is causing popover to be hidden.

Example: http://codepen.io/anon/pen/xwGLvq?editors=100

Which can be solved by applying css to custom stylesheet

    ons-popover .popover {
        display: block;
    }

**Comment by argelius** [comment]
Thanks for pointing this out @rahilwazir ! We will add this rule.
