### ISSUE TITLE
Delayed iOS status bar filling in ons-navigator

### ISSUE THREAD

**Issue by c58** [OnsenUI/OnsenUI#897]
I have an `<ons-sliding-menu>` and two pages with an `<ons-navigator>`. In iOS 9 simulator (and on device too) there is a delay of applying status bar filling to the page__content after setting some of my page as "main". I think it's an iOS browser related issue. 

![proof](https://cloud.githubusercontent.com/assets/1871220/9822391/9f0c6710-58d9-11e5-9d75-45797c010ec7.gif)

**Comment by Hirbod** [comment]
In my case, sometimes it just down even apply the right height and my elements are behind the Navigation-bar. But just on the iOS simulator

**Comment by Hirbod** [comment]
and also on Device, it is related to iOS 9

**Comment by Hirbod** [comment]
Hi @c58 @argelius 
this is related to #950

Please just apply (as a workaround) the suggested fix from argelius. It also fixed it for me.

**Comment by argelius** [comment]
Thanks @Hirbod ! I will close this issue as well.

@c58 Please open it again if the problem persists. However, I think this is also related to broken ~ behavior.
