### ISSUE TITLE
ons-tabbar setActiveTab bug

### ISSUE THREAD

**Issue by synapse** [OnsenUI/OnsenUI#900]
I think I’ve found a bug in the "ons-tabbar”. I have a tabbar with 5 tab elements. When I’m trying to set the active tab using the tabbar method “mytabbar.setActiveTab(1);” it always actives the 3 element with should have index 2. If I activate any other index seems to be working. Another bug is when I’ trying to set the “active” attribute of the tab by setting the true/false values inline by reading a property on the controller. In this case it stucks with the second tab activated (index 1).

**Comment by argelius** [comment]
Thanks @synapse !

We will investigate this. It would be great if you could supply a source code example that reproduces this bug.

**Comment by andipavllo** [comment]
@synapse  I'll take a look at it as soon as possible. As @argelius already said, an example would be appreciated.

**Comment by synapse** [comment]
Ok, I found the bug. If I have a ng-if on a tab then the whole index thingie is broken. Here is codepen example. To temporarily fix it I used the ng-show directive so that it would remove the element.

http://codepen.io/anon/pen/EVPQQy

**Comment by Hirbod** [comment]
ng-if also breaks / makes problem when used with toolbar buttons (like menu/ons-back-button)
Also managed to use it with ng-show instead of ng-if

**Comment by andipavllo** [comment]
@synapse I checked the first issue you reported. The bug is Onsen 1.3.10 but the 1.3.10 dev works fine. Maybe it's cause of the web components, maybe not, I have found sono differences also between other files (views and angular directives). I'll also check the second bug you reported as soon as possible.

**Comment by andipavllo** [comment]
@synapse I also checked the second issue that you reported, but it seems working as it should. After you add the attribute, you should rember to compile the element using `ons.compile()` function.
Here is an example:

```
var tab = document.getElementById("tab3");
tab.setAttribute("active","true");
ons.compile(tab)
```
