### ISSUE TITLE
Snackbar component for android meterial 

### ISSUE THREAD

**Issue by JcDenton86** [OnsenUI/OnsenUI#902]
It's great to see that onsen adds the option for a material touch on hybrid apps! Among other components it would be great to see the [snackbar](https://www.google.com/design/spec/components/snackbars-toasts.html) component. 

I created a plugin for that but there are a lot of things to consider as it needs the design library and gets on top of the webview

**Comment by argelius** [comment]
Thanks for the suggestion @JcDenton86 ! The Snackbar is definitely an important component.

Actually the Snackbar has been implemented in a separate branch. It's still work in progress but will be merged pretty soon

https://github.com/OnsenUI/OnsenUI/pull/850

**Comment by rtholmes** [comment]
I think #850 was closed a few days ago without being merged. Has this feature been dropped?

**Comment by philolo1** [comment]
@rtholmes i think @argelius can answer this better, but we are currently focussing on the components we have right now and make them as bugfree as possible in the upcoming version of OnsenUI 2.0. The component was not 100% working and that is why we dropped it for now, but in the future we might implement a component like that.

**Comment by argelius** [comment]
There were some issues with the implementation so we decided to remake it. It will probably be added in 2.1.0.

**Comment by frandiox** [comment]
Closing old issue: this was implemented as `ons-toast` and `ons.notification.toast` :+1:
