### ISSUE TITLE
ons-sliding-menu.setMainPage doesnot fire 'ons.ready' event

### ISSUE THREAD

**Issue by bdedardel** [OnsenUI/OnsenUI#904]
Description
-----------

### Short Description

I want to write 2 pages:
- index.html, with a sliding menu
- page2.html, another page that works alone

If I call page2.html, everything is ok.
But if I call page2.html from the sliding menu, ons.ready function is never called.

(see examples above)

### Technical Description

- *setMainPage* method does not fire 'ons.ready' event on the new page.

```
myMenu.setMainPage('page2.html', {closeMenu: true})
```

- *setMainPage* callback raise an error: mySwitchVar is not defined

```
myMenu.setMainPage('page2.html', {closeMenu: true,callback:myInitEvent})
```

So, I must use:
- myNavi.pushPage('page2.html')
- and use the 'postpush' event to init mySwitchVar.on( "change") listener

Solution
--------

Would it be better to have a unique initialisation process, by fireing ons.ready in ons-sliding-menu.setMainPage ?

Example
--------

### index.html

```
<ons-sliding-menu var="myMenu" main-page="main.html" menu-page="menu.html"></ons-sliding-menu>

[...]

<ons-template id="menu.html">
<ons-list>
<!--
/!\ myMenu.setMainPage('page2.html', {closeMenu: true})
DOES NOT FIRE ons.ready or postpush, so I cannot call myInitEvent() method !
-->
<ons-list-item onclick="myNavi.pushPage('page2.html');myMenu.closeMenu();">

[...]

<script>
ons.ready(function() {
    myNavi.on('postpush', function(event) {
	if (event.enterPage.name == 'page2.html') {
	    myInitEvent();
	}
    });

});
</script>
```

### page2.html

```
<ons-switch var="mySwitchVar"></ons-switch>

[...]

<script>
ons.ready(function() {
    myInitEvent();
});
</script>
```

### myInitEvent()

```
function myInitEvent() {

    // <ons-switch var="mySwitchVar"
    // mySwitchVar is instanciated once ons.ready is called
    mySwitchVar.on( "change", function() {
      alert('mySwitchVar changed');
    });
}
```

**Comment by frankdiox** [comment]
@bdedardel Hello! I'm sorry but I think you misunderstood the purpose of `ons.ready()`. This is triggered only once at the beginning of the application. It is not supposed to be fired by `setMainPage()` or any other method. You cannot initialize pages that are not created from the beginning there.
I suggest you to use `pageinit` event for that purpose. More info in the docs: http://onsen.io/guide/overview.html#Pageinitevent

**Comment by bdedardel** [comment]
Thanks for the tip, it works fine !
