### ISSUE TITLE
Navigator animations throwing errors in master

### ISSUE THREAD

**Issue by frankdiox** [OnsenUI/OnsenUI#905]
`lift` and `simpleslide` animations for navigator throw errors in master branch. `none` does not disable animations.

http://codepen.io/frankdiox/pen/avdaJM

**Comment by argelius** [comment]
Thanks @frankdiox ! Will take a look at this.

**Comment by anatoo** [comment]
Fixed on "fix-905" branch. This branch is merged on to master branch.
