### ISSUE TITLE
too large to download with bower

### ISSUE THREAD

**Issue by sofish** [OnsenUI/OnsenUI#909]
will u guys provide a bower-only repo like [bower-angular](https://github.com/angular/bower-angular) to solve the problem?

**Comment by frankdiox** [comment]
@sofish Yes, thanks for reminding. We tried to change the repo structure and add ignored files to bower.json, but looks like bower still downloads everything and a specific repo is needed for bower.

**Comment by argelius** [comment]
@sofish We have made a new repo for bower now.

**Comment by sofish** [comment]
:+1:
