### ISSUE TITLE
ons-carousel crashes safari on iphone 6 plus

### ISSUE THREAD

**Issue by davidwahl** [OnsenUI/OnsenUI#914]
Hi, I'm using onsen-ui in a cordova based app and I've struggled a bit with memory related crashed.

This only happens on iPhone 6+ and only when ons-carousel in fullscreen has many slides. The problem is probably related to bad memory handling in iPhone 6+ and how lots of 3d accelerated css animations on this high resolution quickly consumes to much memory, causing the application to quit unexpectedly.

I've found a solution though, a little hack maybe, and because of all my struggles i wanted to spare others for the same waste of time. I guess the same "logic" could be implemented in the Library in some better way.

First I made sure no slides are actually visible, so even with 50 or 100 slides it doesn't consume much memory for the GPU.

```
ons-carousel-item {
    display:none;
}

ons-carousel-item.visible  {
    display:block;
}
```

Then, all you have to do is to make sure, at all time, that current, previous and next slide is visible. I'm using Angular so I created a function i scope which checks current slide. (It shouldn't be a problem to do something simular with jQuery, just hook up some logic with carousel.on("postchange".)

```
<ons-carousel swipeable overscrollable auto-scroll auto-refresh fullscreen var="carousel">
<ons-carousel-item ng-repeat="slide in slidesList track by slide.id" ng-class="{visible:prepareVisible(slide,$index)}">
</ons-carousel>
```

And the the scope function:

```
$scope.prepareVisible = function (offer, index) {
    var currentIndex = carousel.getActiveCarouselItemIndex();        
    if (index >=currentIndex - 1 && index <= currentIndex + 1) return true;
    return false;
}  
```

I hope this is helpful for someone :)

**Comment by argelius** [comment]
Hi @davidwahl !

Thanks for the fix :)

We could implement this for the fullscreen carousel since it makes sense that the items that are not shown are hidden.

**Comment by argelius** [comment]
@andipavllo Reassigned to you

**Comment by Hirbod** [comment]
I did something similar, and the benefits are huge. +1

**Comment by andipavllo** [comment]
I will work on this in the next few days

**Comment by asial-matagawa** [comment]
This problem seems to have been fixed by the Andi's commit above.

Closing this.
