### ISSUE TITLE
ons-splitter issues

### ISSUE THREAD

**Issue by andipavllo** [OnsenUI/OnsenUI#915]
I was taking a look at the new ons-splitter element and I found some issues. Creating an example with two `ons-splitter-side` (one left, one right, both swipeable) and one `ons-splitter-content`, there are the following issues:
- Very poor overall performance, laggy animations and interaction (for example during an `ons-button` click).
- After opening an `ons-splitter-side` it's possible to close it by clicking/touching the external area. This behaviour works fine if just one `ons-splitter-side` has been set as `swipeable` but gets randomly bugged when there are two `ons-splitter-side` elements (always the second toggled element gets bugged, no error messages are displayed).
- An `ons-splitter-side` element with `swipeable` and `collapse="landscape"` attributes gets bugged. The element gets toggled by default in `portrait` mode and it's not possible to close it anymore (tried with touch action and internal functions). It collapses as it should when the orientation gets changed.

**Comment by anatoo** [comment]
@andipavllo Thanks for reporting. I will investigate this issues.

**Comment by andipavllo** [comment]
@anatoo no problem! I forgot, tested on LG G3 Android 5.0

**Comment by anatoo** [comment]
@andipavllo 

>Very poor overall performance, laggy animations and interaction (for example during an ons-button click).

I can't get this performance problem on Nexus7 Android 5.1.1. But I removed some possibilities of performance bottleneck for ons-splitter-side's interaction and animation just in case. Can you check for this problem on your android device?

>After opening an ons-splitter-side it's possible to close it by clicking/touching the external area. This behaviour works fine if just one ons-splitter-side has been set as swipeable but gets randomly bugged when there are two ons-splitter-side elements (always the second toggled element gets bugged, no error messages are displayed).

I fixed.

>An ons-splitter-side element with swipeable and collapse="landscape" attributes gets bugged. The element gets toggled by default in portrait mode and it's not possible to close it anymore (tried with touch action and internal functions). It collapses as it should when the orientation gets changed.

>  it's not possible to close it anymore

In "portrait" screen orientation, it should be correct behavior. "ons-splitter-side" elements on "split" mode should show self always.

**Comment by andipavllo** [comment]
>I can't get this performance problem on Nexus7 Android 5.1.1. But I removed some possibilities of performance bottleneck for ons-splitter-side's interaction and animation just in case. Can you check for this problem on your android device?

The performance has improved a lot, well done! There is a small performance issue when opening the menu, I make a video so you can understand better:

https://www.youtube.com/watch?v=oq_8sPRmu3o

My device is a good one, so should not be related with it.

>In "portrait" screen orientation, it should be correct behavior. "ons-splitter-side" elements on "split" mode should show self always.

I understand, thank you for the explenation.

**Comment by anatoo** [comment]
@andipavllo Thanks for making video. Ok, I continue to improve this performance issue.

**Comment by anatoo** [comment]
@andipavllo I optimized ons-splitter-side's animation again on "fix-915" branch. Could you confirm the performance again?

**Comment by andipavllo** [comment]
Yes sure, I'll test it immediately

**Comment by andipavllo** [comment]
@anatoo Seems that you merged the branch, so I tested on master. Unfortunatelly, the performance seems to be the same, tomorrow I'll test also in a more low performance device to see if it's just related with my device or it's a general issue.

**Comment by anatoo** [comment]
@andipavllo Please test on "fix-915" branch. Yesterday I pushed several commits on "fix-915" branch and that all commits is not merged on master branch.

**Comment by andipavllo** [comment]
@anatoo I didn't notice it before, I thought you merged everything. I tested `fix-915` branch and the performance is the same

**Comment by anatoo** [comment]
@andipavllo Thanks for testing. hmm... I can't figure out why the performance is poor on your android device.

**Comment by Hirbod** [comment]
The performance is generally poor on android. Even on Crosswalk, no matter if I use an old or new device. I have a Samsung Galaxy S6 Edge and pushPage with slide animation is so sluggish, but there a several bug reports with the animation performance..

**Comment by andipavllo** [comment]
@anatoo I also tried on a Galaxy S3 mini with android 4.1.2, same issue
