### ISSUE TITLE
Pop/Push page transitions in Android

### ISSUE THREAD

**Issue by mork80** [OnsenUI/OnsenUI#922]
As follow up of https://github.com/OnsenUI/OnsenUI/issues/836,
I've started to investigate the page transitions in Onsen UI (version 1.3.2 to 1.3.10).
Why some transitions (ex. slide or fade) have choppy effect in some Android devices ?
I've probably have a clue.
In my opinion the problem is that popPage triggered transition are not exactly the reverse of the correspondent pushPage transition. 
In normal functional pattern, to open details page from an index page, you can use the navigator object like this:
`nav.pushPage(“details.html”, {animation: slide});`
To return back to index page, the simple function is
`nav.popPage();`

The desired effect is that popping “details” page performs a reverse slide effect back to an index page.
This reverse animation is sometimes “choppy” and not “smooth”.

I’ve tried this pattern, instead:
`nav.pushPage(“details.html”, {animation: slide});`
and to return 
`nav.resetToPage(“index.html”, {animation: reverseslide});`

adding the “reverslide” transition as new animation as in http://codepen.io/frankdiox/pen/azQMZE.
The reverseslide is exactly the same simpleslidetransition function extracted from pop function.

You can test the same different behaviour, using “fade” transition in the two patterns.

In the second pattern all animations are smooth like a silk :D.

For some reason, popPage trigger some other functions during or before the actual reverse transition that make the whole effect ugly. The pushPage instead do the transitions as expected without any glitch or slowdown.
Can you test it in your android devices ?
Am I wrong I my hypothesis ?

**Comment by asial-matagawa** [comment]
For Onsen UI team:
- If you want more information about this issue, see #836.
