### ISSUE TITLE
Input of type email is throwing an InvalidStateError exception

### ISSUE THREAD

**Issue by igordelorenzi** [OnsenUI/OnsenUI#923]
This is happening when I just touch the input (of type email) to start typing.

I'm on **Mac OS X 10.10.5** and debugging on **Chrome 45.0.2454.99 (64-bit)**.

The stack trace is:

```
FastClick.focus (onsenui.js:570)
FastClick.onTouchEnd (onsenui.js:818)
methods (onsenui.js:350)
```

Exception message:
`Uncaught InvalidStateError: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('email') does not support selection.`

It throws the exception when `targetElement.setSelectionRange(length, length);` is called. Also there's a strange behavior because sometimes the exception is not thrown at all, but I can't figure out why :s

**Comment by argelius** [comment]
Hi @igordelorenzi !

What version of Onsen UI are you using?

Can you create an example on Codepen that reproduces this issue? Does it happen on other versions of Chrome or just 45?

**Comment by DILEEP-YADAV** [comment]
http://www.plugbunch.com/

**Comment by igordelorenzi** [comment]
Hey, @argelius.

I'm using Onse UI version v1.3.8. Unfortunatelly I can't create the example now.

**Comment by igordelorenzi** [comment]
@argelius I think I understood why it happens. It's because of a possibly bug on Chrome's iPhone 5s simulator. Can you try it on your browser?? I'm curious.

**Comment by asialgearoid** [comment]
This was a FastClick issue which has since been fixed.
