### ISSUE TITLE
ROADMAP.md File Should Be Updated

### ISSUE THREAD

**Issue by lkaragol** [OnsenUI/OnsenUI#924]
Could you update ROADMAP.md file? It still contains v1.2.3 and v1.3.0 but v1.3.10 has already been released. It would be nice if we could know incoming features and improvements.

**Comment by argelius** [comment]
Hi @lkaragol !

Thanks for pointing this out. The `ROADMAP.md` file is very out of date.

Actually we have started publishing upcoming features in the [blog](https://onsen.io/blog/) so I will remove the file and the link to it. We will keep announcing new features and publish the current roadmap in the blog.
