### ISSUE TITLE
Select not work on android 4.1.2

### ISSUE THREAD

**Issue by danfador** [OnsenUI/OnsenUI#925]
Hello, I have a form with an select box that it work fine on all devices (android, iOS and web browser) ecept on android 4.1.2.
I have try also with an fresh onsen ui instal and the issue is present

Thank you!

**Comment by argelius** [comment]
Hi!

In what way is it not working? Does it not display at all? Does it work without loading Onsen UI?
Could you try using Crosswalk instead of the native WebView?

**Comment by danfador** [comment]
Hello, thanks for your reply, when I try to slect an value it show the native select from android for half select and after it disappears, the real issue is that i cannot select an value because the select close itself  after half second.

**Comment by argelius** [comment]
Thanks @danfador !

Does this only happen when you have loaded Onsen UI?

**Comment by andipavllo** [comment]
@danfador can you please provide an example? I have an Android 4.1.2 device so I can test it

**Comment by asial-matagawa** [comment]
@danfador 
Sorry but Onsen UI 2 no longer supports Android 4.1.2 because we are now supporting only Android 4.4+ (and Android 4.0 + Crosswalk WebView).
Thank you for your understanding.

Closing this.
