### ISSUE TITLE
Feature request: Make ons-navigator.resetToPage() to accept empty arguments.

### ISSUE THREAD

**Issue by anatoo** [OnsenUI/OnsenUI#931]
### Background

ons-navigator.resetToPage(page) is method that push first parameter's page and clear old page stack.
It's needed "page" parameter to call this method. But initial inner content in ons-navigator has no page name.

### Proposal

This feature request proposed that resetToPage() with empty arguments push initial inner content page and clear old page stack. 

```
<ons-navigator>
  <div>initial content</div>
</ons-navigator>
```

Old way:
```
navigator.pushPage('foobar.html', {animatin: none}); // page stack => ['', 'foobar.html']
navigator.restToPage('hoge.html'); // page stack => ['hoge.html']
```

New way:
```
navigator.pushPage('foobar.html', {animatin: none}); // page stack => ['', 'foobar.html']
navigator.resetToPage(); // page stack is [''], and its content is '<div>initial content</div>'
```

**Comment by argelius** [comment]
This looks good. I have no objections! :+1:
