### ISSUE TITLE
Trigger lazy-repeat reload manually

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#935]
There is no way to manually trigger a reload of the `ons-lazy-repeat` component.

I propose the following syntax.

```html
<div ons-lazy-repeat="Delegate">
  {{ item }}
</div>
```

A `Delegate.reload()` method is automatically injected.

AngularJS
```javascript
module.controller('MyController', function($scope) {
  $scope.Delegate = {
    ...
  };

  $scope.$on('someEvent', function() {
    $scope.Delegate.reload();
  });
});
```

Plain JavaScript
```
var Delegate = {
  ...
};

el.addEventListener('someEvent', Delegate.reload);
```

**Comment by anatoo** [comment]
It's looks good to me.

**Comment by andipavllo** [comment]
Same here!

**Comment by argelius** [comment]
Ok! I will implement like this.

**Comment by anatoo** [comment]
Implemented on https://github.com/OnsenUI/OnsenUI/pull/937 and merged this changes.
