### ISSUE TITLE
Onsen UI not compatible with CSP's unsafe-eval

### ISSUE THREAD

**Issue by chriskaya** [OnsenUI/OnsenUI#936]
Hi,

I'm working on a Cordova app using Onsen UI, and I started using Content Security Policy to make it a little more secure.
I've found out that Onsen UI uses new Function(), so eval(), which forces me to use the csp unsafe-eval.
I don't want to, so I had to modify the onsenui.js file:
I replace line 4888 :
`}(new Function("return this")()));`
by :
`}(function() {return this;}()));`

Is it ok to do that ? If so, could you make it permanent in master ?

Thanks,

Chris

**Comment by andipavllo** [comment]
Dear @chriskaya, thank you for reporting this. We need to check it but, if you want, you can make a pull request by your own and we can review it :)

**Comment by chriskaya** [comment]
Well I'm not really used to git so I'll let you do it ;)
Thanks for all your work! Onsen UI is still young but it is already awesome!

**Comment by andipavllo** [comment]
Thanks, we will take care of it then :)

**Comment by andipavllo** [comment]
@argelius the issue is located in `core/vendor/setImmediate.js`, should we modify it even if it's an external resource?

**Comment by argelius** [comment]
@andipavllo Sure, go ahead.
