### ISSUE TITLE
Lazy-repeat bugged since 1.3.8

### ISSUE THREAD

**Issue by andipavllo** [OnsenUI/OnsenUI#940]
These is a bug in `ons-lazy-repeat` element since 1.3.8 release. Sometimes, in case of a large amount of datas loaded, the element gets bugged and doesn't work at all.

I was able to find the wrong commit, which is the following one:

https://github.com/OnsenUI/OnsenUI/commit/c8ca1285f6d4943490fd32b0409859a54bbd5325

The exact portion of code is the following:

```
if (cnt !== this._itemCount){
        this._recalculateItemHeightSum();
        this._maxIndex = cnt - 1;
}
this._itemCount = cnt;

```

Removing it, the element works fine. Probably it's because it executes the assertion while the datas are still being fetched.

**Comment by argelius** [comment]
@andipavllo Can you please write an example that reproduces this?

**Comment by salztorte** [comment]
Same Problem.
If you want use lazy-repeat with more than 80 Items you see nothing

**Comment by andipavllo** [comment]
@salztorte in your case, was it getting bugged with exactly more than 80 items or it's just an indicative number?

**Comment by salztorte** [comment]
80 Items worked, 81 don´t.

**Comment by andipavllo** [comment]
@argelius I'm going to send you an example privately

**Comment by argelius** [comment]
@salztorte Super sorry for the late reply.

I looked at this today and it seems like there is an issue if you put `overflow: hidden;` on the container element.

Can you try adding `overflow: visible;` to the container?

So if you have a `<ons-list>` with `ons-lazy-repeat` you can do something like this:

```css
ons-list[ons-lazy-repeat] {
  overflow: visible;
}
```

**Comment by argelius** [comment]
I will release a better fix soon.
