### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#945]
This demo is broken:
https://github.com/OnsenUI/OnsenUI/blob/master/demo/navigator_inside_tabbar/index.html

It worked in 1.3 so some change in 2.0 broke it.

**Comment by andipavllo** [comment]
@argelius are you sure it doesn't work? In my forked repository it works well, same here:

https://onsenui.github.io/OnsenUI/demo/navigator_inside_tabbar/index.html

**Comment by argelius** [comment]
Can you check again? It doesn't work on master for me.

**Comment by argelius** [comment]
@andipavllo I have fixed this now so please ignore it.
