### ISSUE TITLE
Sliding menu idea

### ISSUE THREAD

**Issue by charitha1995** [OnsenUI/OnsenUI#951]
http://designmodo.com/wp-content/uploads/2013/07/Cuberto-Design.jpg 
like design for sliding menu.

**Comment by andipavllo** [comment]
It looks very nice, but probably it would be quite hard to implement :)

**Comment by Hirbod** [comment]
https://developer.mozilla.org/en-US/demos/detail/paperfold-css/launch

Wow, even with drag/touch support
http://oridomi.com/

**Comment by charitha1995** [comment]
future web haha.... :+1:

**Comment by charitha1995** [comment]
@andipavllo yes sir :) it is quite hard, we just post that :+1:
