### ISSUE TITLE
Multiple templates in one file : templates showing at the bottom

### ISSUE THREAD

**Issue by chriskaya** [OnsenUI/OnsenUI#954]
Hi,

I keep having issues with <ons-template>.
They keep showing at the bottom of the page (more precisely: the page allows to scroll beyond the end of the rendered area), not rendered.
I've described the problem here : http://stackoverflow.com/questions/33065668/onsenui-multiple-templates-in-one-file-templates-showing-at-the-bottom, but no comments from SO community yet (it's only been 4 days).
I'm not sure whether it's a bug or I am doing it wrong...
I've found out that using <script type="text/ng-template"> solves everything, but I thought I should tell you.

What do you think ?

Chris

**Comment by asial-matagawa** [comment]
This question seems to be already solved in http://stackoverflow.com/questions/33065668/onsenui-multiple-templates-in-one-file-templates-showing-at-the-bottom .
(`ons-template` should have `ons-page` as a child. `ons-toolbar` cannot be located in `ons-template` directly.)

Closing this.
