### ISSUE TITLE
animit.js not working in FireFox

### ISSUE THREAD

**Issue by argelius** [OnsenUI/OnsenUI#958]
Since this commit:

https://github.com/OnsenUI/OnsenUI/commit/45e7ee03294553e8314aba42540be3d810ce561a

Onsen UI doesn't work in FireFox anymore.

**Comment by argelius** [comment]
@anatoo: Could you take a look at this when you have time?

**Comment by anatoo** [comment]
@argelius Thanks for this report. Ok, I will investigate this problem on next week.

**Comment by argelius** [comment]
Thanks @anatoo!
