### ISSUE TITLE
ons-carousel move by n items

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#960]
Hi @argelius,

when I have a ons-carousel showing multiple items at the same time, on swipe, it will only move by 1  default. I would like to have the case, where it would move by _max visible items_ (or _max_, when next page have less items then the slide before)

It would be nice to have the option by 1, by n, by max visible items.

**Comment by argelius** [comment]
Hi @Hirbod !

I think this is a good idea. 

By "max visible items" I take it you mean that if there are currently 5 items displayed, it should slide to the next 5 items (if they exist, otherwise to the maximum index)?

**Comment by Hirbod** [comment]
Exactly @argelius.
