### ISSUE TITLE
Codepen demos on website are buggy

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#961]
Hi,

everytime I want to view a Code-Example (after I click the play button) I get a grey screen inside that demo.

TypeError: CodePenEmbed.showCodePenEmbeds is not a function
CodePenEmbed.showCodePenEmbeds();

After I reload the page, I'm able to look exactly one demo, after I click the next one, it won't work until I refresh again.

Only tested on Firefox (Mac)

Example:
http://onsen.io/guide/overview.html#UsingCarousel

**Comment by Hirbod** [comment]
@argelius

**Comment by andipavllo** [comment]
@Hirbod thank you for reporting this! I'm actually not sure that the issue is related with us, it seems more related with CodePen. Anyway, we will investigate because it's very important for us to have all the CodePens examples working.

**Comment by Hirbod** [comment]
@andipavllo yes this is important. Just checked Chrome and Safari, same bug there!

**Comment by argelius** [comment]
Thanks a lot @Hirbod !

Sorry for the late response. CodePen changed something on their side. It should be working now (or in 15 minutes since CloudFront cache must be updatet).

**Comment by Hirbod** [comment]
Confirmed. It is fixed. By the way, it was broken at least for 1-2 months.
