### ISSUE TITLE
google map cannot work within ons elements

### ISSUE THREAD

**Issue by ehlaumarc** [OnsenUI/OnsenUI#962]
Im developing using cordova app and onsen ui. However i cant load the map properly. The map will appear as a image . But when remove ons elements, the map will work as normal. Please help. 

Im using vs 2015 to work with.

**Comment by andipavllo** [comment]
@ehlaumarc please provide some code, it's impossible to help you otherwise. Also, you can take a look at [this tutorial](onsen.io/blog/onsen-ui-google-maps-javascript-api-v3-angularjs-sample-application/) about how to integrate Google Maps into Onsen UI.

**Comment by ehlaumarc** [comment]
Hi , i went through the tutorial and even try it on VS2015 cordova app, it also did not work .

The following are my code for this development:
index.html

<!DOCTYPE html>
<html ng-app="scheduleplanner">
<head>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    
    
    <title>SchedulePlannerApp</title>

    
    <link href="css/onsen/onsenui.css" rel="stylesheet" />
    <link href="css/onsen/onsen-css-components-blue-basic-theme.css" rel="stylesheet" />
    <link href="css/jqwidgets/jqx.base.css" rel="stylesheet" />
    <link href="css/jqwidgets/jqx.bootstrap.css" rel="stylesheet" />
    <link href="css/scheduler.css" rel="stylesheet" />
    <link href="css/login.css" rel="stylesheet" />
    <link href="css/map.css" rel="stylesheet" />
    <link href="css/index.css" rel="stylesheet" />

    
    <script src="scripts/angular/angular.js"></script>
    <script src="scripts/onsen/onsenui.v1.2.1.js"></script>
    <script src="scripts/jquery-1.11.1.min.js"></script>
    <script src="scripts/jqwidgets/jqxcore.js"></script>
    <script src="scripts/jqwidgets/jqxangular.js"></script>
    <script src="scripts/jqwidgets/jqxcalendar.js"></script>
    <script src="scripts/jqwidgets/jqxdatetimeinput.js"></script>
    <script src="scripts/jqwidgets/globalize.js"></script>
    <script src="https://maps.googleapis.com/maps/api/js"></script>
    <script src="scripts/controller/controller.js"></script>
    <script src="cordova.js"></script>
    <script src="scripts/platformOverrides.js"></script>
    <script src="scripts/index.js"></script>
</head>
<body >
    <ons-navigator var="navigator">
        <ons-page ng-controller="LoginController">
            <ons-toolbar>
                <div class="center">Log In</div>

                
            </ons-toolbar>

            <div class="login-form">

                <input type="email" class="text-input--underbar" placeholder="Email" value="">
                <input type="password" class="text-input--underbar" placeholder="Password" value="">
                <br><br>
                <ons-button modifier="large" class="login-button" ng-click="navigator.pushPage('home.html')">Log In</ons-button>
                <br><br>
                <ons-button modifier="quiet" class="forgot-password">Forgot password?</ons-button>
            </div>

        </ons-page>
        
    </ons-navigator>
    <ons-template id="home.html">
        <ons-page>

            <ons-tabbar>
                <ons-tab page="main.html" active="true" ng-init="main.html">
                    <ons-icon icon="ion-home"></ons-icon>
                    <span style="font-size: 14px">Home</span>
                </ons-tab>
                <ons-tab page="scheduler.html">
                    <ons-icon icon="ion-star"></ons-icon>
                    <span style="font-size: 14px">Favorites</span>
                </ons-tab>
                <ons-tab page="setting.html">
                    <ons-icon icon="ion-gear-a"></ons-icon>
                    <span style="font-size: 14px">Settings</span>
                </ons-tab>
            </ons-tabbar>
        </ons-page>
    </ons-template>

    <ons-template id="main.html">
        <ons-page>
            <div>Content goes here.</div>
        </ons-page>
    </ons-template>

    <ons-template id="scheduler.html">
        <ons-page ng-controller="CalendarController">
            <ons-toolbar>
                <div class="left">
                </div>
                <div class="center">
                    Schedule
                </div>
                <div class="right">
                    <ons-toolbar-button>
                        <ons-icon icon="ion-plus" fixed-width="false" style="vertical-align: -4px;"></ons-icon>
                    </ons-toolbar-button>
                </div>
            </ons-toolbar>
            <div>
                <jqx-calendar jqx-settings="calendarSettings" ng-click="changeDate()"></jqx-calendar>
            </div>
            <div class="navigation-bar">
                <div class="navigation-bar__center">

                    
                    <div class="button-bar" style="width:200px; margin:8px auto 0;">
                        <div class="button-bar__item">
                            <input type="radio" name="navi-segment-a" checked>
                            <div class="button-bar__button">{{todayString }}{{date | date:'dd-MMM-yyyy'}}</div>
                        </div>
                    </div>

                </div>
            </div>

            <ons-list class="plan-list" ng-controller="ListController">
                <ons-list-item modifier="chevron" class="plan" ng-repeat="a in [1,2,3,4,5,6,7,8,9,10]">
                    <ons-row ng-click="navigator.pushPage('map.html')">
                        <ons-col width="80px" class="plan-left">
                            <div class="plan-date">5:30 PM</div>
                            <div class="plan-duration">1h</div>
                        </ons-col>

                        <ons-col width="6px" class="plan-center" ng-style="{backgroundColor:a % 3 == 1 ? '#3399ff' : '#ccc'}">
                        </ons-col>

                        <ons-col class="plan-right">
                            <div class="plan-name">Onsen UI Meetup</div>

                            <div class="plan-info">
                                <div ng-hide="a % 4 == 0">
                                    <ons-icon icon="fa-phone"></ons-icon>123-456-789
                                </div>

                                <div ng-hide="a % 3 == 0">
                                    <ons-icon icon="fa-map-marker"></ons-icon>Moscone, San Francisco
                                </div>
                            </div>
                        </ons-col>
                    </ons-row>
                </ons-list-item>

            </ons-list>

        </ons-page>
    </ons-template>

    <ons-template id="setting.html">
        <ons-page>
            <div>Content goes here.</div>
        </ons-page>
    </ons-template>

    <ons-template id="map.html">
        
        <ons-page ng-controller="MapController">
           
            <ons-toolbar>
                <div class="left">
                    <ons-toolbar-button ng-click="navigator.popPage('map.html')"><ons-icon icon="ion-arrow-left-c" style="color: dodgerblue; font-size: 28px;" fixed-width="false"></ons-icon></ons-toolbar-button>
                </div>
                <div class="center">
                    Schedule
                </div>
                <div class="right">
                </div>
            </ons-toolbar>


            <div id="map_canvas"></div>

            <ons-list style="margin-top: 12px;">
                <ons-list-item modifier="chevron">
                    <div class="prop-desc">
                        <ons-icon icon="fa-book"></ons-icon>
                        User's name
                    </div>
                </ons-list-item>

                <ons-list-item modifier="chevron">
                    <div class="prop-desc">
                        <ons-icon icon="fa-mobile"></ons-icon>
                        User's number
                    </div>
                </ons-list-item>


                <ons-list-item modifier="chevron">
                    <div class="prop-desc">
                        <ons-icon icon="fa-map-marker"></ons-icon>
                        Address
                    </div>
                </ons-list-item>


                <ons-list-item modifier="chevron">
                    <div class="prop-desc">
                        <ons-icon icon="fa-clock-o"></ons-icon>
                        Directions
                    </div>
                </ons-list-item>
            </ons-list>
        </ons-page>
    </ons-template>
    


</body>
</html>

controller.js

(function () { 
    var app = angular.module('scheduleplanner', ['jqwidgets', 'onsen']);
    app.controller('LoginController', function ($scope) { });

    app.controller('CalendarController', function ($scope) {
        $scope.calendarSettings = {
            theme: 'bootstrap',
            height: '350px',
        }
        $scope.todayString = "(Today)";
        $scope.date = new Date();
        $scope.changeDate = function () {
            $scope.tempDate = new Date();
            $scope.date = $scope.calendarSettings.jqxCalendar('getDate');
                $scope.todayString = "";
        }

        this.appointments = appointmentArr;
    });
    //Static address 
    var appointmentArr = {
        name: 'Elaine Loh',
        address: '701 Ang Mo Kio Ave 7 #09-01',
        postal: '789203',
        start: '14:00',
        end: '16:00'
    }
    app.controller('ListController', function ($scope) { });

    app.controller('MapController', function ($scope, $timeout) {
     
            $timeout(function(){
            var options = {
                zoom: 10,
                center: new google.maps.LatLng(1.366131, 103.808079),
                mapTypeId: google.maps.MapTypeId.ROADMAP
            };

           $scope.map_canvas = new google.maps.Map(document.getElementById("map_canvas"), options);
            },500);
  });
})();


As i mention , the google map will appear as an image within ons-elements. The moment i remove the ons-elements, the map will load as normal . Please advice. Thank you
Hope to hear from you soon.

**Comment by ehlaumarc** [comment]
@andipavllo , sorry to trouble you. do you face the same problem when you place the map div into the ons-elements ?? I'm a student working on an industrial project for my FYP, i hope to resolve this problem asap, Onsen UI provides very good interface , i wanted it to be a part of my project .

**Comment by andipavllo** [comment]
Well, I have placed my map inside an `ons-page` element, exactly like you, with no issue. Which element breaks it? The `ons-list` immediately below? Is there any error in the console log?

**Comment by ehlaumarc** [comment]
No. it is within the ons-page , but above the ons-list . Not only i have this issue , my classmate also faces the same issue. May i know which version of onsen api you are using ? what platform / application you are using . Both of us are using Visual Studio 2015

**Comment by andipavllo** [comment]
I was using Google Maps Javascript API 3 and Onsen 1.2.1 (the tutorial is from February). I cannot understand where the problem is, the structure seems fine. No errors are displayed? Please try using Onsen 1.2.1 and let me know if it works. 

Also, take a look here:

http://stackoverflow.com/questions/31092907/google-maps-v3-in-cordova-onsenui-app-map-displays-in-browser-but-not-on-phone/31099018#31099018
