### ISSUE TITLE
Bug: Tabbar "postchange" wrong index..

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#963]
Hi @argelius @andipavllo 

I have a tab-bar, with a `var="rootTab"`.
I have some registered events. (prechange, postchange)

Postchange will behave buggy as soon as `persistent="true"` is set.

```html
<div ng-controller="TabBarController">
    
    <ons-tabbar animation="none" keepPage="true" var="roottab">

		<ons-tab page="match.html" label="">
			<ons-icon icon="ion-arrow-swap" class="tab-icon step-tab-1"></ons-icon>
		</ons-tab>

		<ons-tab page="gossip.html" label="" persistent="true">
			<ons-icon icon="ion-ios-paper" class="tab-icon step-tab-2"></ons-icon>
		</ons-tab>

		<ons-tab page="neighbor.html" label="" active="true" persistent="true" class="map-btn step-tab-3">
			<img src="img/nnlogo.svg" class="tabbar-nn-logo svg">
		</ons-tab>

		<ons-tab page="chatrooms.html" label="">
			<div class="notification reply-notification"></div>
			<ons-icon icon="ion-chatbubbles" class="tab-icon step-tab-4"></ons-icon>
		</ons-tab>

		<ons-tab page="tab-news.html" label="">
			<div class="notification earth-notification"></div>
			<ons-icon icon="ion-earth" class="tab-icon step-tab-5"></ons-icon>
		</ons-tab>
    </ons-tabbar>

</div>
```

As you can see, gossip.html and neighbor.html have the `persistent="true"` flag.

* When I had active gossip.html (eg. index 1) and change to neighbor.html (index 2), postchange will not fire, as the last tab was persistent and the new one also.

* When I change from gossip.html to chatrooms.html it will fire.
* When I change from chatrooms.html to neighbors.html it will fire.

So postchange will never fire when the last tab was persistent and the new tab is persistent.
So I don't have any chance to detect the tabchanges and this will break my application, as it's urgent to change something inside of my neighbor.html on postchange.

Please, this is a production-ready app and I need to upload the update asap.
Thank you very much!

**Comment by Hirbod** [comment]
I got it. @andipavllo @argelius  - this is for sure a bug.

Postchange will trigger, but the index keys are wrong, thats why I could not call my code.

When I change to 
* gossip.html, getActiveTabIndex() is 1
* when I change to neighbors.html, getActiveTabIndex() is 1 (wrong, should be 2)
* when I change to chatrooms.html, index is 3 (correct)
* I change back to neighbors.html, index is 2 (correct)
* I change to match.html, index is 0 (correct)
* I change back to neighbors.html, index is 0 (wrong, should be 2)

So, `persistent="true"` will cause that the index won't update.
Any fast fix for this?

**Comment by Hirbod** [comment]
Alright.. it's a timing issue. Seems like postchange will fire too fast when persistent flag is set. Adding a $timeout will help (quick and dirty). You need to investigate please

**Comment by andipavllo** [comment]
@Hirbod which version of Onsen UI are you using? I just tried with the master version and everything seems working fine

**Comment by Hirbod** [comment]
1.3.11

**Comment by Hirbod** [comment]
As said, wrapping around inside of an $timeout (with 0 second), it work. Seems like some $digest did not apply correctly.

**Comment by andipavllo** [comment]
@Hirbod I just tried it also for 1.3.11 and it works fine in my case. Which browser have you used to test? Can you also try with the master version of Onsen? Can you provide a working CodePen example that simulates the wrong behavior? Thank you for your cooperation.

**Comment by Hirbod** [comment]
I used iOS simulator and iPhone 6 (both on iOS9)
Did you set the persistent-flags like I described?

**Comment by andipavllo** [comment]
Yes I did, I tried it on chrome. A CodePen example would be appreciated.

**Comment by Hirbod** [comment]
My app is very complex, building and example is not that easy.

I don't think that you will have this timing issue on chrome, maybe it's hardware related

**Comment by argelius** [comment]
@Hirbod @andipavllo I will take a look at this.

**Comment by Hirbod** [comment]
👍🏼
