### ISSUE TITLE
onsen ui carousel' post change event not fire.

### ISSUE THREAD

**Issue by githubkyo** [OnsenUI/OnsenUI#964]
ons.ready(function () {
            carousel.on('postchange', function (event) {
                var newActiveIndex = event.activeIndex - 1;

                console.log($scope.bookmarkArr);
                $scope.nowPage = Math.floor((event.activeIndex) / 33) * 33;

                // ブックマークのアイコンを切り替え
                if ($scope.bookmarkArr.indexOf(newActiveIndex) > -1) {
                    $scope.bookmarkFlag = true;
                } else {
                    $scope.bookmarkFlag = false;
                }

                // ブックマークのナビアイコンを切り替え
                var len = $scope.bookmarkArr.length;
                $scope.selectRightHave = false;
                $scope.selectLeftHave = false;

                for (var i = 0; i < len; i++) {
                    if ($scope.bookmarkArr[i] > newActiveIndex) {
                        $scope.selectRightHave = true;
                    }

                    if ($scope.bookmarkArr[i] < newActiveIndex) {
                        $scope.selectLeftHave = true;
                    }
                }

                if ((event.activeIndex + 1) > $scope.pageNum) {
                    carousel.setAutoScrollRatio(1.0);
                    carousel.setActiveCarouselItemIndex(event.activeIndex - 1);
                } else {
                    carousel.setAutoScrollRatio(0.1);
                }

            });
        });

ReferenceError: carousel is not defined

please help me.

**Comment by frankdiox** [comment]
The error says that `carousel` variable does not exist. Have you included `var="carousel"` in your `ons-carousel` HTML? And if you did, is that `ons-carousel` in your index.html? Because otherwise it won't be created by the time `ons.ready` is executed.

**Comment by githubkyo** [comment]
yes,  i included var="carousel" in my html. but, not in index.html.

I use window.carousel fixed this problem.

ons.ready(function () {

            // カルーセルオブジェクトを取得
            var carousel = window.carousel;

            carousel.on('postchange', function (event) {
                var newActiveIndex = event.activeIndex - 1;

                console.log($scope.bookmarkArr);
                $scope.nowPage = Math.floor((event.activeIndex) / 33) * 33;

                // ブックマークのアイコンを切り替え
                if ($scope.bookmarkArr.indexOf(newActiveIndex) > -1) {
                    $scope.bookmarkFlag = true;
                } else {
                    $scope.bookmarkFlag = false;
                }

                // ブックマークのナビアイコンを切り替え
                var len = $scope.bookmarkArr.length;
                $scope.selectRightHave = false;
                $scope.selectLeftHave = false;

                for (var i = 0; i < len; i++) {
                    if ($scope.bookmarkArr[i] > newActiveIndex) {
                        $scope.selectRightHave = true;
                    }

                    if ($scope.bookmarkArr[i] < newActiveIndex) {
                        $scope.selectLeftHave = true;
                    }
                }

                if ((event.activeIndex + 1) > $scope.pageNum) {
                    carousel.setAutoScrollRatio(1.0);
                    carousel.setActiveCarouselItemIndex(event.activeIndex - 1);
                } else {
                    carousel.setAutoScrollRatio(0.1);
                }

            });
        });
