### ISSUE TITLE
ons-pull-hook - error in documentation and when using slide-menu-ignore="true"

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#965]
Hi @argelius @andipavllo 

On
http://onsen.io/reference/ons-pull-hook.html
 
you are referencing `var="loaded"` but try to access `loader.getCurrentState()`. This will lead into bugs and no display of the status. (change var to loader and it works)

And when you add `sliding-menu-ignore="true"` to ons-page, the pull-hook won't work and jitter extremely

It's related to my old bug report #449 - thought I will give it a try today, and found the cause of this problem

**Comment by andipavllo** [comment]
@Hirbod thank you very much for reporting this, I'll fix it immediately. For next time, please report the website issues in this repository :)

https://github.com/OnsenUI/onsen.io/issues

**Comment by Hirbod** [comment]
@andipavllo shall I open another ticket for the sliding-menu issue?

**Comment by andipavllo** [comment]
@Hirbod yes please, open another ticket :)

**Comment by Hirbod** [comment]
But you closed #449 which was not related to the documentation

**Comment by andipavllo** [comment]
sorry, I missunderstood, I'll open it again
