### ISSUE TITLE
lazy-repeat should be allowed inside of ons-scroller

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#966]
@argelius @andipavllo 

Since this commit
https://github.com/OnsenUI/OnsenUI/commit/a0f31c2dbc6dfc743a8a566e9813da70dcceaf0c
pull-hook is allowed for ons-scroller, so it should be for lazy-repeat

**Comment by andipavllo** [comment]
@Hirbod you are right about this, we should probably implement it
