### ISSUE TITLE
ons-pull-hook won't work with sliding-menu-ignore="true"

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#967]
It just won't work. Jittering and flickering, see video on #449 
After I removed the slide-menu-ignore from ons-page, it worked

**Comment by andipavllo** [comment]
@Hirbod I tried to replicate this but I couldn't. Actually, `sliding-menu-ignore="true"` is not working at all for me. Here is a CodePen example, please let me know if there is somenthing that shoud have been implemented differently to reproduce the issue.

http://codepen.io/andipavllo/pen/MaVORN

**Comment by Hirbod** [comment]
Well, it should. For me, it will jitter and flicker as soon as I set this element.

**Comment by Hirbod** [comment]
@andipavllo yeah your code is broken.

You have
```html
sliding-menu-ignore"true"
```

while it should be
```html
sliding-menu-ignore="true"
```

**Comment by andipavllo** [comment]
Oh, you are right, sorry for the mistake. I'll take a look at it.

**Comment by Hirbod** [comment]
I just checked it inside of your codepen, the error is reproducable.
