### ISSUE TITLE
ons-pull-hook - don't apply any styles on negative value

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#969]
Currently, ons-pull-hook will break inertial/momentum scroll when end of list is reached (while dragging), as it triggers also on overbouncing at ons-page-bottom. Please do not trigger / apply any styles on .scroll when end of list is reached. Just leave it native, as it also feels buggy right now.

Dragging and releasing works as expected at bottom end, but touchmove not. Please improve this to give the user more native feeling. I'm very focused on details.

https://www.youtube.com/watch?v=UR6a1NMoGME&feature=youtu.be

**Comment by Hirbod** [comment]
@andipavllo @argelius also see #968

**Comment by Hirbod** [comment]
another bug, related to this one. Since ons-pull-hook applys css while scrolling, I can't scroll fast up and down, as soon as my finger touches the element, it will jump around... this is nasty :(

**Comment by andipavllo** [comment]
@Hirbod thanks for all this reports, we will investigate. Anyway, if you want, you can also implement the fixes by yourself and make a pull request :)

**Comment by Hirbod** [comment]
@andipavllo I don't want to sound demanding, but actually I'm taking care of some open source projects and have to finish this annoying app :D 

It's quite difficult. I will provide code and fixes as much as I can, but I'm quite busy currently. Will try to look at it.

**Comment by Hirbod** [comment]
Just had a look at the source.
@argelius @andipavllo 

### Fixing style onDone
For now, adding 
```js
      _onDone: function(done) {
        // Check if the pull hook still exists.
        if (this._element) {
          this._translateTo(0, {animate: true});
          this._setState(this.STATE_INITIAL);

          // we could also consider listening to a webkitTransitionEnd
          setTimeout(function(){
          	this._scrollElement.removeAttr('style')
          }.bind(this), 310);
        }
      },
```

the timeout to the _done function will work fine for resetting styles at the end of animation.

### Concept

Conceptional, ons-pull-hook is not final nor really production ready. It should be changed to following, as anything else does not make sense and will have negative side-effects.

* only add CSS to `this._scrollElement` when `scroll > 0`. Dont add any rule when view is in normal use. _onDone timeout will also make sure, that the styles are removed after legit css-style-apply.
* _onDone need to reset the style attribute added to _scrollElement (see code above)
* scroll < 0 should not interrupt touch event. Let it be native, don't block it, overscroll is welcome. Blocking cause jittering
* do not apply any style to _scrollElement on normal drag/scroll when moving down. Only call `_translateTo` when scroll is > 0

**Comment by Hirbod** [comment]
@andipavllo I've also seen another bug. When I scroll down rapidly (and let the inertial scroll a bit) and want to give it some more speed, as soon as I touch the screen, it jumps up (I think it's related to fastclick or something in this case), as fastclick won't update it's last known click position while inertial is running. Won't happen on Simulator, but at device.

And when I scroll slow (just dragging a bit down) it's jittering awful on iOS

**Comment by andipavllo** [comment]
@Hirbod please open a new issue for any bug you find, otherwhise it's easy to miss something

**Comment by Hirbod** [comment]
yes, but's related to this one, that's why I wrote this down here

**Comment by argelius** [comment]
@Hirbod: I have merged a fix. It's a bit different from your proposed fix but I don't want to add the transform except when absolutely necessary to avoid issues with transformed children.

**Comment by Hirbod** [comment]
@argelius I will check that, but I guess that this won't fix the jittering problems. I will open another issuse when other errors come up
