### ISSUE TITLE
Generated document is broken.

### ISSUE THREAD

**Issue by anatoo** [OnsenUI/OnsenUI#971]
I checked out current master branch and notice generated document is broken:
```
onsenui (master) $ ls build/docs/                       
undefined
```

EXPECTED: 
```
onsenui (master) $ ls build/docs/                       
ja
en
```

**Comment by argelius** [comment]
Thanks @anatoo. I can take a look at this.

**Comment by argelius** [comment]
@anatoo I broke something when updating dependencies. I have fixed it now.
