### ISSUE TITLE
Onsen 2.0 bugs in IE and Edge

### ISSUE THREAD

**Issue by frankdiox** [OnsenUI/OnsenUI#973]
Onsen 2.0 bugs found in IE and Edge. PR #993

## IE and Edge:
- dialog, alert, popover:
	- [x] Missing: `z-index: 20001`.
        * `z-index` is type number in IE/Edge.
	- [x] Scrollbars are visible in dialogs.
        * [`-ms-overflow-style` property](https://msdn.microsoft.com/es-es/library/hh771902(v=vs.85).aspx)
- progress:
	- [x] Not displaying circular ones. Throws: `Unable to get property '1' of undefined or null reference`.
        * IE/Edge don't implement [`children` property for SVG elements](https://msdn.microsoft.com/en-us/library/ff972069(v=vs.85).aspx).
        * IE/Edge need [polyfill for `classList`](http://purl.eligrey.com/github/classList.js/blob/master/classList.js).
        * SVG animations are limited in IE.
- range:
	- [x] Styles are completely broken in IE. Edge has some differences with Chrome.
- scroller:
	- [x] There is no inertial scrolling.
        * [`-ms-scroll-snap-type` property](https://msdn.microsoft.com/en-us/library/hh772038(v=vs.85).aspx).
- splitter:
	- The left menu can be detached from the side for a moment.
        * There are bugs in splitter also for Chrome that probably affect this.

## IE:

- fab:
	- Shadow animation is not displayed (it is displayed in the small buttons of speed-dial though).
        * IE bug: [Clicking a child doesn't trigger the parent's :active state](http://stackoverflow.com/q/10753215/4468962).
- icon:
	- Console error: `Object doesn't support property or method '_show'`.
        * Looks like a bug in CustomElements polyfill.
- list:
	- Tappable effect doesn't work when list-items have children tags.
        * IE bug: [Clicking a child doesn't trigger the parent's :active state](http://stackoverflow.com/q/10753215/4468962).
- toolbar:
	- Tappable effect on toolbar buttons with icons doesn't work.
        * IE bug: [Clicking a child doesn't trigger the parent's :active state](http://stackoverflow.com/q/10753215/4468962).
- navigator:
	- [x] Throws: `Object doesn't support property or method 'remove'` when pushing.
        * IE doesn't implement `childNode.remove()` method.
- tabbar:
	- [x] Throws: `Object doesn't support property or method 'remove'` when changing a non-persistent tab.
        * IE doesn't implement `childNode.remove()` method.
- search_input:
	- [x] No icon, placeholder, etc.
        * IE needs SVG in base64.
- text_input:
	- [x] MD styles are not displayed.
        * `background-size` is [not animatable property in IE](https://msdn.microsoft.com/en-us/library/dn254934%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396).
- buttons, switchs, fab:
	- [x] Developer console crashes and closes IE.
        * Crashes due to `fontawesome.min.css`. It accepts `fontawesome.css`.

## Edge:

- if-platform:
	- [x] Detects Chrome.
        * [Edge just adds a suffix to Chrome's UA](http://www.useragentstring.com/pages/Edge/).

**Comment by argelius** [comment]
Thanks @frankdiox ! Please work on solving these bugs since it should work in these browsers as well.

**Comment by frankdiox** [comment]
@argelius The error thrown in `demo/icon/index.html` is related to a `show` event fired from `ons-navigator`. It works well in Chrome but is broken in IE, Edge and Firefox. If I add `document.registerElement = undefined;` it also breaks in Chrome. Do you think it's a problem with the polyfill?

**Comment by argelius** [comment]
@frankdiox Sorry for not replying to this. I forgot.

I think this has been fixed in 23d737ceb8f26e0dfa8db9006578aaf6ed6504b2

**Comment by frankdiox** [comment]
@argelius Yes, it's fixed :) Thanks!
