### ISSUE TITLE
Tabbar is bugged when clicking tabs very quickly

### ISSUE THREAD

**Issue by frankdiox** [OnsenUI/OnsenUI#974]
Related: #948 (already fixed)

In this demo 
https://github.com/OnsenUI/OnsenUI/blob/master/demo/tabbar/index.html

With `fade` or `slide` animations:
- Memory leak. 
- It doesn't remove the `ons-page` from the DOM and keeps adding new pages.

With `animation: 'none'`:
- Memory leak.
- Throws: `Uncaught Error: Fail to fire "pageinit" event. Attach "ons-page" element to the document after initialization.`

**Comment by argelius** [comment]
I'll take a look at this.

**Comment by argelius** [comment]
@frankdiox I think this is fixed now. Can you verify?

**Comment by frankdiox** [comment]
@argelius Yes, memory leak fixed :) The only thing that remains is the `pageinit` error, but since it's going to be deprecated I guess it's not very important. Thanks!

**Comment by argelius** [comment]
@frankdiox Actually I was unable to reproduce the pageinit error. What browser and what version are you running?

**Comment by frankdiox** [comment]
@argelius Chrome Version 46.0.2490.80 m
You have to modify the demo and use `none` for tabbar animation.
