### ISSUE TITLE
Blink bug in ons-split-view

### ISSUE THREAD

**Issue by ghost** [OnsenUI/OnsenUI#975]
I'm developing a cordova application using onsenui.

The environment is:
OnsenUI 1.3.11, iOS9, cordova 5.3.3.

When I change a main page by calling setMainPage of `ons-split-view`, the page always blinks.
I checked it on iOS9 simulator, iPhone and iPad.

On Safari and Chrome, it works fine.

**Comment by pressentir** [comment]
http://codepen.io/onsen/pen/nKqfv

I also tried the code above, but the same problem occurred.

**Comment by argelius** [comment]
Thanks for reporting @pressentir !

We will investigate this bug.
