### ISSUE TITLE
Password input no focus on firefox and safari

### ISSUE THREAD

**Issue by cdiaz** [OnsenUI/OnsenUI#978]
http://onsen.io/pattern-login.html

Fix  class="underbar"  ,  no focus and placeholder is hidden

the css box-sizing: border-box property

**Comment by cdiaz** [comment]
box-sizing: border-box;

**Comment by argelius** [comment]
Thanks for reporting! We will fix this.

**Comment by leocaseiro** [comment]
This is happening on Onsen 2 as well.

**Comment by argelius** [comment]
Thanks @leocaseiro ! We will take a look.

**Comment by argelius** [comment]
@frankdiox Can you take a look at this?

**Comment by frankdiox** [comment]
@leocaseiro @argelius This was actually fixed in 0dc6cf0, but looks like wasn't updated in the website.

**Comment by leocaseiro** [comment]
Sorry @frankdiox, but it isn't working in my app either...
Perhaps hasn't been compiled...

**Comment by frankdiox** [comment]
@leocaseiro Are you copying `login.css` content in your app? That file is changed in Onsen 2: https://github.com/OnsenUI/OnsenUI/blob/master/css-components/www/patterns/login.css
Check that the CSS in your app is like that.

**Comment by leocaseiro** [comment]
Oh Thanks @frankdiox. I didn't notice that. I replaced with ```height:100%``` and now it's working fine.
Thanks
