### ISSUE TITLE
Sliding menu -disappearing toolbar button and content

### ISSUE THREAD

**Issue by Saurabh995** [OnsenUI/OnsenUI#980]
I am using materialize css with onsen. The date picker is causing the toolbar button an dcontent to disappear. I would attach the screenshot of the app.
![screenshot_2015-10-24-08-42-15](https://cloud.githubusercontent.com/assets/5358306/10711183/5642e3cc-7a91-11e5-9cfe-70664139671c.png)
![screenshot_2015-10-24-08-42-37](https://cloud.githubusercontent.com/assets/5358306/10711185/5e552d5e-7a91-11e5-9121-8f4f8bd1731c.png)
![screenshot_2015-10-24-08-42-44](https://cloud.githubusercontent.com/assets/5358306/10711186/5ea0be04-7a91-11e5-8a2f-0e530c1d0aa5.png)

Secondly the swipeable feature is not working on android but when I tested it on browser it works fine.

<ons-sliding-menu menu-page="menu.html" main-page="home.html" side="left"
               var="menu" type="reveal" max-slide-distance="260px" swipeable="true">
            </ons-sliding-menu>

You can see swipeable parameter has been set to true.

**Comment by argelius** [comment]
Hi @Saurabh995 !

That's really weird. Is it possible for you to create an example that reproduces this? Preferably on codepen.io but just pasting a runnable example here works as well.

I need to check if some classes or CSS rules changed when the date picker was displayed. Maybe there is a transform working?
