### ISSUE TITLE
input  tag's value's position and default message's position is a shift

### ISSUE THREAD

**Issue by githubkyo** [OnsenUI/OnsenUI#986]
<input type="search" placeholder="default message" class="search-input" id="search"/>

input  tag's value's position and default message's position is a shift。

input  tag's value's position near the bottom. But ,default message's position  is middle.

**Comment by argelius** [comment]
Thanks for the report @githubkyo !

Can you explain exactly what you mean. Can you create an example on codepen that reproduces this?
