### ISSUE TITLE
iOS Bug: Slide Menu > ons-nav > page__content 

### ISSUE THREAD

**Issue by d3orn** [OnsenUI/OnsenUI#988]
The pictures bellow show 2 different situations which were both taken within the same App running on iOS 9.
As you can see somehow the page__contents top:64px is ignored in the first picture. In the second, the page content starts where it is supposed to start.
The first scenario is achieved by navigating (menu.setMainPage(foo.html)) from another page whereas the second by doing so from within the side menu.

I also disabled our CSS complete to see if this is cause by some of our CSS rules, which it isn't.

Bugged version:
![screen shot 2015-10-28 at 13 49 44](https://cloud.githubusercontent.com/assets/411479/10789279/b4bfcc74-7d7c-11e5-902a-a5eb5ee924cb.png)

How it should be:
![screen shot 2015-10-28 at 13 49 51](https://cloud.githubusercontent.com/assets/411479/10789282/b6ca735c-7d7c-11e5-9087-997a744c7481.png)

Some more informations: Within the page__content a lazy-repeat list is displayed.
I pin pointed it down to where I had a normal ons-scroller list and it worked perfectly but as soon as I have a lazy-repeated list within an ons-scroller it breaks.

I think it could be that somehow the statusbar from iOS is ignored.

EDIT: I compared the two different scenarios base on the HTML created and it is identical -> it has something to do with timing or css

**Comment by Hirbod** [comment]
This is fixed in 1.3.11 - just update.

**Comment by argelius** [comment]
@d3orn 

Can you try overriding with the following rules?

```
.page__status-bar-fill + ons-toolbar + .page__background + .page__content {
  top: 64px;
  padding-top: 0px;
}

.page__status-bar-fill + .page__background + .page__content {
  padding-top: 20px;
}
```

**Comment by d3orn** [comment]
well this fixed the misplaced content. Thanks a lot!

**Comment by argelius** [comment]
That's great! :+1:
