### ISSUE TITLE
Change ons-pull-hook completely with following libs

### ISSUE THREAD

**Issue by Hirbod** [OnsenUI/OnsenUI#994]
Hi,

I don't want to be mean - but ons-pull-hook - is just a buggy solution. It's not meant for production or large lists etc. It's just buggy. Too buggy, too sluggish.

There are few more and better concepts out there.

First of all, you guys should split the behaviour, to get maximum performance.

1) Don't use translate. Really, don't. It sucks monkeyballs.
2) Use different implementation for iOS (elastic) and Android (material design style).

**iOS**
iOS has elastic scroll. Pulling will return a negative scroll value, which we can PERFECTLY listen to, even on non-wkwebview-devices.
There is something out, I've incorporated inside of Onsen-UI myself. (iOS only)
https://github.com/infomofo/angular-md-pull-to-refresh

60 Lines of code for perfection.

This one is just missing different states, it just knows initial, loading, finish. I think we don't need any other states, maybe it should be enough to just zoom the spinner a bit till it's endposition is reached, fire loading, fire finish. I tried this directive on a 10k List, NO LAGS. It works awesome!

**Android**
Android does not have elastic scroll. So don't try to simulate it with some dirty hacks. Just use the material-design concepts.
http://lightningtgc.github.io/material-refresh/

This one here is just perfect. It just pulls down an loading element instead of simulating an elastic pull.
Please, get the code, add it to Onsen.

**Comment by Hirbod** [comment]
@argelius I forgot to mention that material-refresh will also work for iOS (but it's buggy) and should not be used. Just add a check if iOS (use md-directive style) or Android for material. These are just suggestions, hope you will consider to make that hole thing more performant

**Comment by argelius** [comment]
Thanks for testing this @Hirbod !

If there's no way to make it performant with translate3d on iOS, I guess we need to remake it.

It will probably not happen right now but we can add it in the next minor version. I think in that case we will not replace this component but instead make a new one and deprecate this one.

**Comment by Hirbod** [comment]
@argelius sounds really good!
