### ISSUE TITLE
ons-splitter sliding issue

### ISSUE THREAD

**Issue by frankdiox** [OnsenUI/OnsenUI#997]
@anatoo I have found some problems with `ons-splitter`. In this demo:  https://jsfiddle.net/rry8pgxx/4/

The second `ons-splitter` (right side) is taking the width of the first one (left side) for the opening animation. When sliding the right menu you can see that it gets stuck at 100px and then opens 300px when releasing the click.

Also, the menu just disappear without animation if you open and close it without releasing the click.

**Comment by argelius** [comment]
I can take a look at this.

**Comment by anatoo** [comment]
@frankdiox @argelius Thanks!
