### ISSUE TITLE
Onsen UI Select / Dropdown / Autocomplete

### ISSUE THREAD

**Issue by dieunt** [OnsenUI/OnsenUI#998]
Hi,
Is there any components like Select / Dropdown / Autocomplete in Onsen UI?

Thank you.

**Comment by frankdiox** [comment]
Hello @dieunt 
There is no specific component for that but probably you can use `ons-popover` like this: http://stackoverflow.com/a/27141353/4468962

**Comment by rockneverdies55** [comment]
C'mooon, really... no `select` widget in onsen ui?

**Comment by FREEZX** [comment]
This is ridiculous. At least style or somehow mask the native mobile browser dropdown box.

**Comment by billouboq** [comment]
@rockneverdies55 @FREEZX Do you know what Open source means? You are free to contribute and improve Onsen UI. If you want this component so bad then do it and make a pull request. I'm pretty sure OnsenUI members will be pleased to review it.

**Comment by FREEZX** [comment]
@billouboq Challenge accepted!

**Comment by FREEZX** [comment]
Here's my shot, simple masking of an actual select component
https://github.com/FREEZX/OnsenUI
Can we get the issue reopened as it's still an issue?
